### ISSUE TITLE
data of type protein_sequence_feature_or_motif

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1003]
I guess this is a chado loader problem rather than a Canto problem per see.

can't handle data of type protein_sequence_feature_or_motif
can't handle data of type protein_sequence_feature_or_motif

It is in the Canto log
https://curation.pombase.org/dumps/latest_build/logs/log.2022-07-19-18-27-04.curation-tool-data-load-output

**Comment by kimrutherford** [comment]
Looks like I forgot to change the Chado loading code to handle the new "Protein sequence feature or motif" annotation type from Canto.  I've done that now, hopefully in time for the current load.  I'll check in the morning.

**Comment by kimrutherford** [comment]
All seems good.  Some of the new annotation is here: https://www.pombase.org/reference/PMID:19606211
