### ISSUE TITLE
error log for phaf file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1004]
Do you know what this means?

https://curation.pombase.org/dumps/latest_build/logs/log.2022-07-19-18-27-04.phenotypes_from_PMID_18503029_phaf

**Comment by kimrutherford** [comment]
Sorry about that.  I broke it when fixing https://github.com/pombase/pombase-chado/issues/995

The bug only caused problems for that one PHAF file because it had allele names without gene prefixes (like "F245R").
