### ISSUE TITLE
chado_checks.duplicated_allele_names

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1006]
These look OK,   its only that in one case the gene name isn't prefixed on the allele. I will fix these but I thought they were automagically repaired - so I wanted to check what this issue is (I would have expected a lot more so I must be missing something).

https://curation.pombase.org/dumps/latest_build/logs/log.2022-07-22-03-00-16.chado_checks.duplicated_allele_names

  cce1-D230N	SPAC25G10.02:allele-2	D230N	amino_acid_mutation	68c407dfd4d11f5e
  cce1-D230N	SPAC25G10.02:allele-9	D230N	amino_acid_mutation	7ab16ed95ce889ee
  cce1-D46N	SPAC25G10.02:allele-10	D46N	amino_acid_mutation	7ab16ed95ce889ee
  cce1-D46N	SPAC25G10.02:allele-6	D46N	amino_acid_mutation	68c407dfd4d11f5e
  grx4-C172S	SPBC26H8.06:allele-4	C172S	amino_acid_mutation	57ee19731b127383
  grx4-C172S	SPBC26H8.06:allele-6	C172S	amino_acid_mutation	4f30f3893b88315a
  grx4-C35S	SPBC26H8.06:allele-3	C35S	amino_acid_mutation	57ee19731b127383
  grx4-C35S	SPBC26H8.06:allele-5	C35S	amino_acid_mutation	4f30f3893b88315a
The 8 above are now fixed in 7ab16ed95ce889ee

  cut1-C1730A	SPCC5E4.04:allele-33	C1730A	amino_acid_mutation	310b16bb1a103044
  cut1-C1730A	SPCC5E4.04:allele-35	C1730A	amino_acid_mutation	809618c56c11583b,809618c56c11583b

**Comment by ValWood** [comment]
Ignore. I get it. These are warnings because for most of the repaired ones there is not already an existing allele with that name. These are all fixed now.

**Comment by kimrutherford** [comment]
Can this be closed?
