### ISSUE TITLE
delta/ Δ

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1008]
Hi Kim,

In canto and submission formats we are pragmatically allowed to write "delta" and this will automagically be converted to  xxxΔ on the website.

However,  when we export the files to other places (Mondo, Pombemine ) I think we export "xxxdelta".

Really, the correct nomencature is xxxΔ, and I think we should export  and gene with with xxxΔ as the  primary names  and  xxxdelta as an synonym (and display the "text" synonym on the website too).

@manulera  does this make sense?

**Comment by ValWood** [comment]
This would also apply to Δ symbol embedded in allele names other than deletions.

If this agreed, it would be useful to do before the pombemine load for release in early August.

**Comment by kimrutherford** [comment]
> This would also apply to Δ symbol embedded in allele names other than deletions.

Do you have an example of that?

**Comment by manulera** [comment]
> display the "text" synonym on the website too

Does this mean to write alp14delta as a synonym? For the allele page I would say that's ok.

Here problematic examples @kimrutherford in which the typesetting of the delta character didn't go well:
https://curation.pombase.org/dumps/latest_build/logs/log.2022-07-19-18-27-04.chado_checks.only_ascii_characters_in_feature_name

In those same sessions, there are other non-deletion alleles with delta in their names.

**Comment by kimrutherford** [comment]
> Here problematic examples @kimrutherford in which the typesetting of the delta character didn't go well:

Hi Manu.  Those are just warnings.  The three allele names are correct in Chado and they display correctly on the website.

The deltas don't look correct in my browser but they're OK in the log file:

```
curl https://curation.pombase.org/dumps/builds/pombase-build-2022-07-24/logs/log.2022-07-24-19-25-22.chado_checks.only_ascii_characters_in_feature_name
```

```
uniquename      name    session
  SPCC895.07:allele-9   alp14Δmid       f134593392c70d97
  SPCC895.07:allele-10  alp14ΔtubBD     f134593392c70d97
  SPAC20G4.02c:allele-8 pfus1:fus1N-cdc12Δolig  345d6b0c8bf7e493
```

**Comment by kimrutherford** [comment]
> Really, the correct nomencature is xxxΔ, and I think we should export and gene with with xxxΔ as the primary names

We'll need to document this and announce it in case anyone is using those files with their own code.  Sometimes non-ascii characters get mangled if care isn't taken (which is why Canto has so many bugs with non-ascii curator names).

As a data point, FlyBase export "upd2Δ" as "upd2[Delta]"

**Comment by manulera** [comment]
> The three allele names are correct in Chado and they display correctly on the website.

I see that in the last log that you sent they are still like that. I had re-entered the delta character from other alleles that did not give errors, thinking that may fix it, but I see it doesn't. As you say, curl gets it right, while the browser doesn't.

**Comment by ValWood** [comment]
OK, lets discuss. We could also do it the Flybase way.

**Comment by ValWood** [comment]
> As a data point, FlyBase exports "upd2Δ" as "upd2[Delta]"
so I think what we do now is fine if we emulate FlyBase.

@manulera  you had some additional comments, if they are still relevant could you put them in a new ticket as I will close this one.
v
