### ISSUE TITLE
Don't fail the whole load if GOA can't be updated

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1009]
The load script checks for a new GOA differently (worse) to how it checks for a new RNAcentral annotations file.  If the check for a new version of GOA fails, the whole script fails.  But for RNAcentral it's more sensible, so if it fails to connect to the EBI or it hangs for too long it writes a message and carries on with the previous version of the file.

We should do the same for GOA to make the load more reliable.  GOA isn't updated often so we can cope with a out of date version for a day or two.

**Comment by ValWood** [comment]
Agreed. I think it is only updated every month or two. but ebi needs to sort this, its  affecting everything...(and it doesn't seem to be only FTP)

**Comment by kimrutherford** [comment]
That's done now.  I was a quick fix and it worked in last night's load.
