### ISSUE TITLE
QC: additional chado load check?/ gene names

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#101]
The genedb loader complained about
/primary_name="rtt10"
/primary_name="rtt10"
for the same gene product

which isn't a big deal, but we should make sure we check for 
i) different primary names for the same gene
in addition to 
ii) the same primary name used for more than one gene (check was recently implemented)

...you proba bly already make  both of these checks (basically primary_name unique AND cardinality 1)

Original comment by: ValWood

**Comment by ValWood** [comment]
I think both of these checks already take place, can you confirm?
I'm guessing that a duplicate for the same gene doesn't cause a problem anyway.
Closing, but reopen if you think we need  any additional checks.

**Comment by kimrutherford** [comment]
There's a warning like:
```
SPCC18B5.03 has more than one /primary_name
```
