### ISSUE TITLE
Should we be sending annotation for pseudogenes to GO?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1015]
I've just noticed that we don't include annotation for pseudogenes in the GPAD file we created for GO.  The pseudogenes are in the GPI file though.

I don't know why I implemented that way.  I thought I'd check before fixing it: should we be sending annotation for pseudogenes to GO in the GPAD file?

(The GAF file includes the pseudogene annotation)

**Comment by ValWood** [comment]
Rereading the original issue, you  don't need to export annotations to pseudognes, but this should also prevent us accumulating. any.

A log file of "GO annotation to pseudogenes" might be useful.

**Comment by kimrutherford** [comment]
I've done a quick check.  We don't have any annotations to pseudogenes now.

GOA have a few annotations for wtf12: https://www.uniprot.org/uniprotkb/Q8NIP8/entry

Those GOA annotation aren't being loaded: https://www.pombase.org/gene/SPCC622.21
but I'm not sure why.  Maybe they are being filtered.

It's seems odd that Uniprot doesn't mention that it's pseudo: https://www.uniprot.org/uniprotkb/Q8NIP8/entry

**Comment by ValWood** [comment]
Let's close. We can open if we need to do anything, but I tend to ignore pseudos since there are not many. We can revisit in the future.
