### ISSUE TITLE
Update to InterPro 90.0, released 4th August 2022

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1016]
This will also fix this message caused by changes in gene structures:
```
TM domain coord is outside of protein sequence, 513..532 for MDSGLKSDSHEVERSNFQLNKPEKSLKRYALLSFYV...
```
(This sequence is from gpi17 / SPAC1F12.09)

I'm downloading v90 now and I'll start processing when it's done.

**Comment by ValWood** [comment]
i dont know if it will fix the message because the InterPro is pre-computed on the protein sequences in Uniprot. This wont be fixed until we resubmit the genome, and UniProt update their protein sequences.

Next task!

**Comment by ValWood** [comment]
Hopefully we will be able to resubmit regularly. Quite a lot of domain coordinates will currently  be slightly off! I'm surprised terre are not more warnings?

**Comment by kimrutherford** [comment]
Sorry, I should have been more clear.  The TM domains are calculated using TMHMM at the same time and by the same program that processes the InterPro XML file.  It made sense to handle both tasks together.  So we should be able fix the message while updating InterPro.

**Comment by ValWood** [comment]
Got it!

**Comment by kimrutherford** [comment]
> I'm downloading v90 now and I'll start processing when it's done.

The processing has finished and the new InterPro and TMHMM data will be in the next build.

The InterPro processing for japonicus is still running.
