### ISSUE TITLE
New 5'UTRs checks required for loading

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1019]
The data for the 5’UTR are annotated from the Thodburg paper PMID:30566651  are now available in 

pombe-embl/genome_reannotation
chr1_5UTR.contig     2078    (old 2110)
chr2_5UTR.contig    1639    (old 1694)
chr3_5UTR.contig     799    (old 839)

So overall the number has dropped a little, but rather than being a random assortment from different sources and conditions of dubious provenance - this is a single high-quality dataset. I think nearly every single UTR has coordinate changed.

I have not swapped the old for new yet because there are a couple of things to fix (below).

They are  annotated like: 

FT   5'UTR           complement(60771..60842)
FT                   /systematic_id="SPAC977.14c"
FT                   /note="feature created using major TSS peak, vegetative
FT                   growth, EMM PMID:30566651"
FT                   /db_xref="PMID:30566651"
FT                   /Score="10.285300"

Things to do:

1.
It might be worth a double check that all features have  /systematic_id, at least one note, at least one db_ref (some may have more than one because if the match was exact too existing I kept both), Score. I guess this will happen during loading anyway but all should be present.

2. I  realised that the TSS data were "2 nucleotide spans" and so but I annotated to the end of them, so every feature will have been over-extended by one nucleotide.

<img width="182" alt="pof13_in_art" src="https://user-images.githubusercontent.com/7359272/187510128-95729f23-b7e9-4ca9-828a-d0027f15df06.png">

So the files will need the coordinates fixed for every feature before import.

(SEE COMMENT BELOW)

3. This annotation type would probably be more systematic if we converted this note to some sort of “controlled curation”.
It could be:
/controlled_curation=“cv=five_prime_UTR_source;  evidence=ECO:0000309; source=SO:0001238;  condition=FYECO:0000126; during=GO:0072690; score=blah; db_xref=PMID:30566651"

SO: major_TSS
ECO:CAGE (method)
This replaces the existing note and dbxref.

Chado storing can come after. Important part first is to get features updated. Curation is supplementary

4. 19 features have additional notes, I just wanted to record when there was another strong TSS that was quite distant from the strong 'cluster' to see if they align with. Known alternative transcripts (this probably isn't all of them).  No action, only a heads up.
FT                   /note="alternative TSS 135695"
FT                   /note="alternative TSS 633892"
FT                   /note="alternative TSS 165746"
FT                   /note="alternative TSS 177232"
FT                   /note="alternative TSS 177232"
FT                   /note="alternative TSS 661608"
FT                   /note="alternative TSS 934238"
FT                   /note="alternative TSS 1046544"
FT                   /note="alternative TSS 1106789"
FT                   /note="alternative TSS 1520787
FT                   /note="alternative TSS 2947249"
FT                   /note="alternative TSS 3381575"
FT                   /note="alternative TSS 441501"
FT                   /note="alternative TSS 1244107"
FT                   /note="alternative TSS 1518672"
FT                   /note="alternative TSS 1891168"
FT                   /note="alternative TSS 2009919"
FT                   /note="alternative TSS 2140994"
FT                   /note="alternative TSS 2192045"

5. Once the. Data is loaded we need to represent it on the gene pages (transcript section).

**Comment by kimrutherford** [comment]
> It might be worth a double check that all features have /systematic_id

The load will fail if a systematic_id is missing but it's probably to a good idea to check while merging.

> I guess this will happen during loading anyway but all should be present.

We'll need to explicitly check for the note and the db_xref.

> so every feature will have been over-extended by one nucleotide

Is that at the 3' or the 5' end?

> This annotation type would probably be more systematic if we converted this note to some sort of “controlled curation”.

Let's talk about that on a call.

> Another thought. We also need to retain the existing 5' UTRs for the alternatively spliced genes....

It should be possible to avoid removing those.  Is the plan to remove all the existing 5'UTRs and replace them with the features in `pombe-embl/genome_reannotation`?

**Comment by ValWood** [comment]
Re point 2 about. The forward strand features are overextended 1 (therefore need 1 base adding to shorten). The reverse strand features are correct.

**Comment by kimrutherford** [comment]
Hi Val.

Here's a list of the features with no `systematic_id`:
```
genome_reannotation/chr1_5UTR.contig:
5'UTR  complement(93872..93879)
5'UTR  146883..146973
5'UTR  complement(515609..515639)
5'UTR  complement(1134303..1134334)
5'UTR  1376582..1376586
5'UTR  1497008..1497146
5'UTR  complement(1704002..1704098)
5'UTR  complement(2067765..2067914)
5'UTR  complement(2349271..2349324)
5'UTR  complement(2537901..2537936)

genome_reannotation/chr2_5UTR.contig:
5'UTR  complement(1130426..1130473)
5'UTR  complement(1497492..1497555)
5'UTR  complement(2090944..2091343)
5'UTR  3390939..3390967

genome_reannotation/chr3_5UTR.contig:
5'UTR  937703..937802
5'UTR  complement(1712955..1713533)
```

**Comment by kimrutherford** [comment]
List of duplicate qualifiers:

```
genome_reannotation/chr1_5UTR.contig:
/score="98.3163" at line: 767  loc: 411798..412083
/score="14.031700" at line: 1408  loc: complement(join(710024..710366,710413..710479))
/score="40.2777" at line: 2755  loc: 1285615..1285626
/score="3.84555" at line: 5526  loc: complement(2450504..2451065)

genome_reannotation/chr2_5UTR.contig:
/score="74.011300" at line: 195  loc: complement(186676..186950)
/systematic_id="SPBC839.14c" at line: 1119  loc: complement(625197..625360)

genome_reannotation/chr3_5UTR.contig:
/score="14.420200" at line: 1855  loc: 922633..923068
```

**Comment by kimrutherford** [comment]
Features with missing `/db_xref`:

```
genome_reannotation/chr1_5UTR.contig:
5'UTR  complement(1189111..1189269)
5'UTR  complement(1622869..1622887)
5'UTR  2167176..2167205
5'UTR  complement(2172096..2172147)

genome_reannotation/chr2_5UTR.contig:
5'UTR  complement(40144..41387)
```

**Comment by kimrutherford** [comment]
Feature with no `/note' qualifier:

```
genome_reannotation/chr1_5UTR.contig:
5'UTR  complement(3589950..3591355)
5'UTR  complement(4651351..4651623)
```

**Comment by kimrutherford** [comment]
Features with no `/Score' qualifier:

```
genome_reannotation/chr1_5UTR.contig:
5'UTR  complement(110282..110512)
5'UTR  complement(113310..113337)
5'UTR  116338..116692
5'UTR  125256..125581
5'UTR  complement(135102..135147)
5'UTR  151899..151912
5'UTR  complement(182195..182238)
5'UTR  complement(195583..195634)
5'UTR  204395..205212
5'UTR  complement(207914..208136)
5'UTR  259610..259718
5'UTR  305605..305722
5'UTR  complement(307948..308026)
5'UTR  complement(325281..325444)
5'UTR  complement(332744..332808)
5'UTR  complement(334337..334564)
5'UTR  334616..334659
5'UTR  338301..338391
5'UTR  complement(345130..345171)
5'UTR  complement(346619..346678)
5'UTR  347111..347194
5'UTR  350406..350476
5'UTR  353774..353899
5'UTR  complement(363603..363857)
5'UTR  complement(402195..402246)
5'UTR  complement(528772..528876)
5'UTR  complement(530167..530282)
5'UTR  complement(537726..537873)
5'UTR  complement(576623..577153)
5'UTR  complement(606850..607211)
5'UTR  610847..610885
5'UTR  complement(632842..633054)
5'UTR  644671..644710
5'UTR  689352..689482
5'UTR  complement(753211..753405)
5'UTR  778402..778531
5'UTR  complement(783145..783271)
5'UTR  complement(792169..792254)
5'UTR  818002..818116
5'UTR  complement(821705..821774)
5'UTR  complement(869528..869684)
5'UTR  complement(887173..887252)
5'UTR  887647..887660
5'UTR  complement(894424..894487)
5'UTR  894998..895365
5'UTR  896769..896876
5'UTR  1090722..1090728
5'UTR  1139093..1139129
5'UTR  1271853..1271888
5'UTR  complement(1432656..1432802)
5'UTR  complement(1433376..1433398)
5'UTR  complement(1489583..1489755)
5'UTR  complement(1545814..1546092)
5'UTR  complement(1554792..1554820)
5'UTR  complement(1618745..1618903)
5'UTR  complement(1622869..1622887)
5'UTR  1631323..1632067
5'UTR  complement(1711068..1711082)
5'UTR  1875585..1876258
5'UTR  1902075..1902318
5'UTR  1907054..1908267
5'UTR  1957472..1959310
5'UTR  2016366..2016384
5'UTR  complement(2028753..2028867)
5'UTR  complement(2047145..2047166)
5'UTR  2228954..2229014
5'UTR  2788021..2788069
5'UTR  2999060..2999087
5'UTR  3127659..3127688
5'UTR  3166427..3166455
5'UTR  complement(3181137..3181157)
5'UTR  3380540..3380755
5'UTR  complement(3452609..3452749)
5'UTR  3504035..3504260
5'UTR  complement(3589950..3591355)
5'UTR  complement(4435914..4437145)
5'UTR  4443029..4443077
5'UTR  4639814..4639883
5'UTR  complement(4651351..4651623)
5'UTR  4754813..4755006
5'UTR  5476837..5476876

genome_reannotation/chr2_5UTR.contig:
5'UTR  212352..212374
5'UTR  complement(244952..244982)
5'UTR  1248557..1248595
5'UTR  complement(1285085..1285216)
5'UTR  complement(2958431..2958635)
5'UTR  3011511..3012933
5'UTR  3092003..3092082
5'UTR  3209885..3210021
5'UTR  3390939..3390967
5'UTR  complement(3454536..3454661)
5'UTR  complement(4300453..4300497)

genome_reannotation/chr3_5UTR.contig:
5'UTR  complement(117848..117933)
5'UTR  complement(332484..332566)
5'UTR  525200..525360
5'UTR  complement(1186168..1186233)
5'UTR  complement(1712955..1713533)
5'UTR  1809319..1809364
5'UTR  1939236..1939264
5'UTR  complement(2190730..2190875)
```

**Comment by kimrutherford** [comment]
Systematic IDs that appear more than once:

```
genome_reannotation/chr1_5UTR.contig:
SPAPB1A10.02  (three times)

genome_reannotation/chr2_5UTR.contig:
SPBC3D6.06c
SPBC25H2.11c

genome_reannotation/chr3_5UTR.contig:
SPCC16C4.22
SPCC18B5.08c
SPCC24B10.12  (three times)
SPCC550.01c
SPCC1223.05c
SPCP1E11.10
```

**Comment by kimrutherford** [comment]
> We also need to retain the existing 5' UTRs for the alternatively spliced genes....

It looks like this two new UTRs are out of date?  SPAC17G6.02c doesn't have two transcripts in the chr1 contig file. 

```
FT   5'UTR           complement(3589950..3590570)
FT                   /systematic_id="SPAC17G6.02c.1"
FT                   /db_xref="PMID:18276645"
FT                   /db_xref="PMID:30566651"
FT                   /note="feature created using major TSS peak, vegetative
FT                   growth, EMM PMID:30566651"
FT                   /Score="58.5465"
FT   5'UTR           complement(3589950..3591355)
FT                   /systematic_id="SPAC17G6.02c.2"
FT                   /db_xref="PMID:18276645"
```

**Comment by kimrutherford** [comment]
(Sorry for all the comments)

Could you check the systematic_id of this new UTR?  `SPBC30D10.01` is now a synonym of `SPBC1778.01c`

```
FT   5'UTR           complement(3096323..3096342)
FT                   /systematic_id="SPBC30D10.01"
FT                   /note="feature created using major TSS peak, vegetative
FT                   growth, EMM PMID:30566651"
FT                   /db_xref="PMID:30566651"
FT                   /Score="536.435000"
```

**Comment by kimrutherford** [comment]
I've implemented most of what's needed to merge the new UTRs into the contigs.  Below is an example of what chr1 looks like after running my script.

I decided to use `/utr_source` for now rather than `/controlled_curation` to make it clear that they're different.

I haven't tried sharing a file with this service before.  Let me know if there's a problem:
https://files.inbox.eu/shared/file/808f87d3887b9463c6b4ea45338eefaaa79c6acd

**Comment by kimrutherford** [comment]
> I haven't tried sharing a file with this service before. Let me know if there's a problem:

I just tried loading with Artemis.  It failed with an unbalanced quote.  Here's a fixed version:
https://files.inbox.eu/shared/file/d9bad61cc111ee6deb6903b59f8e903128e6f02d

**Comment by ValWood** [comment]
All of the changes [checked] above are checked into svn. There are 2 things left to do which I will  finish tonight but I need to pop out for dinner now. There may be a few more  errors generated because I suspect that  if there are more than one error per feature only the first error is reported, and often the error occur together.

**Comment by ValWood** [comment]
All changes checked in. I think there will be a few residual to fix if you re run.
v

**Comment by kimrutherford** [comment]
> I think there will be a few residual to fix if you re run.

Only two problems left I think:

There's a systematic ID to fix: https://github.com/pombase/curation/issues/3431

and from  https://github.com/pombase/pombase-chado/issues/1019#issuecomment-1376789810 one of these needs to be removed and change SPAC17G6.02c.1 to SPAC17G6.02c if that's the one you keep:

```
FT   5'UTR           complement(3589950..3590570)
FT                   /systematic_id="SPAC17G6.02c.1"
FT                   /db_xref="PMID:18276645"
FT                   /db_xref="PMID:30566651"
FT                   /db_xref="PMID:21511999"
FT                   /db_xref="PMID:18276645"
FT                   /note="feature created using major TSS peak, vegetative
FT                   growth, EMM PMID:30566651"
FT                   /Score="58.5465"
FT   5'UTR           complement(3589950..3590572)
FT                   /systematic_id="SPAC17G6.02c"
FT                   /db_xref="PMID:18276645"
FT                   /score=38.315300
FT                   /note="feature created using major TSS peak, vegetative
FT                   growth, EMM PMID:30566651"
```

**Comment by kimrutherford** [comment]
> All done. If all looks OK you can go ahead and "out with the old/in with the new"

There is only one thing left for fixing:

> one of these needs to be removed and change SPAC17G6.02c.1 to SPAC17G6.02c if that's the one you keep:

```
FT   5'UTR           complement(3589950..3590570)
FT                   /systematic_id="SPAC17G6.02c.1"
FT                   /db_xref="PMID:18276645"
FT                   /db_xref="PMID:30566651"
FT                   /db_xref="PMID:21511999"
FT                   /db_xref="PMID:18276645"
FT                   /note="feature created using major TSS peak, vegetative
FT                   growth, EMM PMID:30566651"
FT                   /Score="58.5465"
FT   5'UTR           complement(3589950..3590572)
FT                   /systematic_id="SPAC17G6.02c"
FT                   /db_xref="PMID:18276645"
FT                   /score=38.315300
FT                   /note="feature created using major TSS peak, vegetative
FT                   growth, EMM PMID:30566651"
```

**Comment by ValWood** [comment]
Sorry, I forgot to do my final check-in. now done (there were some other fixes in here too)

**Comment by kimrutherford** [comment]
Both features for SPAC17G6.02c are still there?

**Comment by ValWood** [comment]
I only see one feature?

**Comment by ValWood** [comment]
Which features do you see is it CDS or UTR?

**Comment by ValWood** [comment]
got it, fixed

**Comment by kimrutherford** [comment]
Thanks.  I'll go ahead and merge the new RNAs into the contig files.

**Comment by kimrutherford** [comment]
> I'll go ahead and merge the new RNAs into the contig files.

Done!

There are two new 5'UTR features that need manually handling because the genes have multiple transcripts.  Could you have a look?

chr1:
```
FT   5'UTR           complement(1172127..1172209)
FT                   /systematic_id="SPAC22A12.08c"
FT                   /db_xref="PMID:18641648"
FT                   /db_xref="PMID:20118936"
FT                   /db_xref="PMID:30566651"
FT                   /Score="63.071"
FT                   /note="feature created using major TSS peak, vegetative
FT                   growth, EMM PMID:30566651"
```

chr2:
```
FT   5'UTR           complement(180609..180628)
FT                   /systematic_id="SPBC1198.04c"
FT                   /db_xref="PMID:30566651"
FT                   /note="feature created using major TSS peak, vegetative
FT                   growth, EMM PMID:30566651"
FT                   /Score="4.336450
```

**Comment by ValWood** [comment]
The UTRs  will be identical for CDs.01 and CDS.02 in both cases, the variation is in a splice site and  a truncated shorter version. So should we have two  identical 5'UTRS
for each 1. and .2

**Comment by kimrutherford** [comment]
> The UTRs will be identical for CDs.01 and CDS.02 in both cases

Thanks.  I forgot to include those in time for the current load.  I've added them now and I'll check the load on Saturday morning.

**Comment by kimrutherford** [comment]
Hi Val.

There's a 5'UTR that's causing the load to fail.  The code that creates the website is failing on this because the coordinates are inside first exon of the CDS:
```
FT   5'UTR           3338720..3338750
FT                   /systematic_id="SPBC17D1.06"
FT                   /db_xref="PMID:30566651"
FT                   /feature_source="evidence=ECO:0000309; source=SO:0001238; condition=FYECO:0000126; during=GO:0072690; score=123.941000; db_xref=PMID:30566651"
```

It should just warn rather than failing but I haven't got around to making that change.

This is the only 5'UTR with this problem.  I tested by removing that 5'UTR from Chado and running the code locally.

There are some other warnings though:

```
5'UTR and exon don't meet up: SPAC977.10.1 at pos 52117
5'UTR and exon don't meet up: SPAC13C5.06c.1 at pos 436022
5'UTR and exon don't meet up: SPAC1D4.06c.1 at pos 649565
5'UTR and exon don't meet up: SPAP27G11.08c.1 at pos 1622887
5'UTR and exon don't meet up: SPAC1783.05.1 at pos 2195018
5'UTR and exon don't meet up: SPAPB1E7.05.1 at pos 3294110
5'UTR and exon don't meet up: SPAC26A3.03c.1 at pos 3337594
5'UTR and exon don't meet up: SPAC4F10.02.1 at pos 4832928
5'UTR and exon don't meet up: SPBC839.14c.1 at pos 625360
5'UTR and exon don't meet up: SPBC337.16.1 at pos 1058420
5'UTR and exon don't meet up: SPBC1709.20.1 at pos 1112733
5'UTR and exon don't meet up: SPBC3D6.07.1 at pos 1282754
5'UTR and exon don't meet up: SPBC8D2.23.1 at pos 1378510
5'UTR and exon don't meet up: SPBC15C4.02.1 at pos 2238826
5'UTR and exon don't meet up: SPBP4H10.12.1 at pos 2895854
5'UTR and exon don't meet up: SPBC2D10.07c.1 at pos 2979730
5'UTR and exon don't meet up: SPBC15D4.07c.1 at pos 3025771
3'UTR and exon don't meet up: SPCC553.05c.1 at pos 297216
5'UTR and exon don't meet up: SPCC736.05.1 at pos 320607
5'UTR and exon don't meet up: SPCC4B3.10c.1 at pos 1158148
5'UTR and exon don't meet up: SPCC70.09c.1 at pos 2369852
```

**Comment by ValWood** [comment]
I fixed the one which is making the load fail temporarily so the CDS matches the UTR. I'll look into this tomorrow, and the other warnings.

**Comment by kimrutherford** [comment]
OK, thanks.  I did a local test load and it's all fine now.

**Comment by kimrutherford** [comment]
> I fixed the one which is making the load fail temporarily so the CDS matches the UTR.

Thanks.  That's good now: https://www.pombase.org/gene/SPBC17D1.06
The load finished and the main site is now updated with the new UTRs.  :+1:

**Comment by ValWood** [comment]
Woo Hoo, thanks. I started this on my month in the lake district in May 2021! I'll  do 
- [ ] the final fixes to the non aligned UTRs, 
- [ ] draft an announcement/news item 
- [ ] review the alternatively spiced 
- [ ] update FAQ text

**Comment by ValWood** [comment]
I only need to write a news item, on my list

**Comment by ValWood** [comment]
I just wanted to chek that the reverse strand off-by one error was fixed during this ticket. This is the only place i can find it mentioned and it isn't completely clear if it was done (I'm just checking off an old  task list for the paper)

**Comment by ValWood** [comment]
Yes, OK, just updating the task list. I was pretty sure it was done...
