### ISSUE TITLE
Fixing modifications

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1021]
For many of the altered protein sequence, modification data will also be incorrect.

After table updated:
https://github.com/pombase/curation/issues/3024
we need to

1) export table
2) check which sequences have affected residues 
(note this is not as simple as just checking on a residue basis, will need to be done on a dataset&protein basis because many residues  will be correct by chance)
also whether something needs repairing will depend on the age of the change and the age of the publication (although I imagine most HTP data will be old versions sequence because most proteomics pipelines use protein sequence from uniprot)
3) Need to record somewhere the difference between the old and new (most of the recent ones are truncations, but not all)
4) Kim can "repair" the spreadsheet data. 
5) we can get a separate report of which genes have modification in Canto, and the numbers to decide whether to manually or automatically fix

**Comment by ValWood** [comment]
This is a really bad description of what needs to happen to fix the "modified residue" problems.

**Comment by kimrutherford** [comment]
> Kim can "repair" the spreadsheet data

Which spreadsheet?

**Comment by ValWood** [comment]
I mean the 'phaf' files, but @manu can do this no we have no need to reduce his work load imminently ;)

**Comment by ValWood** [comment]
@manu this ticket is probably covered by one of yours?

**Comment by manulera** [comment]
This is in the pipeline yes, after I discuss with Kim. The ones from the svn folder (vast majority of mistakes were there, I guess because they used Uniprot sequences for mass spec or other HT method) are fixed.

**Comment by ValWood** [comment]
This is done
