### ISSUE TITLE
Alleles not beginning with a gene name

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1025]
https://curation.pombase.org/dumps/latest_build/logs/log.2022-09-15-22-14-05.chado_checks.AlleleNotStartingWithGeneName

Also filter from this file
any gene name beginning with

GST-
GFP-
EGFP-
nmt1-
nmt41-
nmt81-
NLS-
NES-
TetR-

as long as they are followed immediately by a gene name

**Comment by ValWood** [comment]
@manulera  one  question- should we do these as

GFP-name or   GFP:    ?

(and for the others- I guess the nmt issue will go away once we can do expression sensibly)

(note - we only curate GFP constructs if they are known to have a severe phenotype- )

**Comment by kimrutherford** [comment]
How does this relate to #1027?  I'm a bit confused.

**Comment by ValWood** [comment]
These prefixes are also allowed for alleles not starting with a gene name (although in these cases the allele should also _contain_ the gene name)

**Comment by ValWood** [comment]
Another "allowed" is anything gene#delta-ANYTHING

**Comment by manulera** [comment]
Sorry never saw this one.

@kimrutherford The position of GFP or other tags represents whether it is on the 3' (if the name is before) or 5' (if the name is after) of the protein.

I think the dash is the preferred way for people to do this, the `::` is used to indicate replacement (e.g. removing a gene and inserting a resistance cassette instead `cls1::KanMX`). The single`:` I am not sure, but I have used it to indicate that things are adjacent to each other, but not linked in any meaningful way (as in a genetic resistance marker (`KanMX`) inserted along with a GFP, could be `cls1-GFP:KanMX`). This is how I do it though, no particular reason for it.

The original nomenclature from [Kohli 1987](https://pubmed.ncbi.nlm.nih.gov/3329975/) is a bit cumbersome and predates the wide usage of tags I think, so falls a bit short, but their suggestion would be (`cls1-GFP int::KanMX`). I am not a huge fan of having spaces within the allele name.

**Comment by manulera** [comment]
> the allele should also contain the gene name

I think this should be the requirement for tagged alleles indeed.

**Comment by ValWood** [comment]
> a huge fan of having spaces within the allele name.

I think we should outlaw this, it's terrible for parsing. We don't have so many (I expect) most are things like:

his2 mutant	his2	SPBC1711.13	393d0a5aae35d3ac
his7 mutant	his7	SPBC29A3.02c	393d0a5aae35d3ac

I am making these his2- if I can't track them down

Some just have random info in the allele name (synonyms etc), and some replace what should be a ' '  with a space to separate a superscript.

I requested a log of allele names  with spaces here earlier:
https://github.com/pombase/pombase-chado/issues/1048

**Comment by kimrutherford** [comment]
> Another "allowed" is anything gene#delta-ANYTHING

Is that a typo?  I can't see any alleles in Chado that have a "#" in the name.

> as long as they are followed immediately by a gene name

Are there any extra restrictions about what can come after the gene name in those cases?

**Comment by manulera** [comment]
> Is that a typo?

I think so

> as long as they are followed immediately by a gene name

I don't know what would come after the gene name in that case, it might be that it is a chimera or something, so hard to anticipate. I would not add restrictions on that.

**Comment by ValWood** [comment]
yes sorry typo.

It is to cover things like :
TetR-stc1-deltaZF2(89-126)	stc1	SPBP8B7.28c	1e00c626a8ce874f
TetR-stc1-deltaZF1+2(32-126)	stc1	SPBP8B7.28c	1e00c626a8ce874f
TetR-stc1-C(1-126)	stc1	SPBP8B7.28c	1e00c626a8ce874f
TetR-stc1-deltaC(126-215)	stc1	SPBP8B7.28c	1e00c626a8ce874f
TetR-stc1-D4A(D192A,D193A,D194A,D195A,D197A,E198A,D199A)	stc1	SPBP8B7.28c	1e00c626a8ce874f
TetR-stc1-D2A(D144A,D145A,D147A,D149A,D150A,D151A)	stc1	SPBP8B7.28c	1e00c626a8ce874f
TetR-stc1-D1A(D127A,D129A,D130A)	stc1	SPBP8B7.28c	1e00c626a8ce874f
TetR-stc1-D3A(D166A,D167A,D170A,D173A)	stc1	SPBP8B7.28c	1e00c626a8ce874f

**Comment by kimrutherford** [comment]
I forgot to do a "git push" yesterday so my changes weren't in for last night's load.  I'll check again on Thursday morning.

**Comment by kimrutherford** [comment]
> I forgot to do a "git push" yesterday so my changes weren't in for last night's load. I'll check again on Thursday morning.

I think those changes are working.

It's still reporting allele names like this: `orc1delta::ura4+`
Should those be allowed?

**Comment by ValWood** [comment]
> It's still reporting allele names like this: orc1delta::ura4+
Should those be allowed?

yes we can filter those. It isn't so many...

**Comment by kimrutherford** [comment]
> It's still reporting allele names like this: orc1delta::ura4+

Those should be gone in the morning.

**Comment by kimrutherford** [comment]
> > It's still reporting allele names like this: orc1delta::ura4+
>
> Those should be gone in the morning.

That's done.  Is there anything else to do on this issue?

**Comment by ValWood** [comment]
Keep it open. I am currently  fixing  some at the problems (spaces in names etc)  at the moment,  then I will provide a list of 'grandfathered' alleles which don't conform to our "new"  standard , but that we will not fix because they are in common use 
I hope to finish in the next few days, but not today which is a GO day.

**Comment by ValWood** [comment]
These are legacy alleles which do not start with a gene name and do not need fixing.
Could we filter these from the list of alleles that do not begin with a gene name?
[temp.txt](https://github.com/pombase/pombase-chado/files/10537947/temp.txt)

(there will be more.. I'm still checking these)

**Comment by kimrutherford** [comment]
> Could we filter these from the list of alleles that do not begin with a gene name?

That's done for Tuesday night's load.
