### ISSUE TITLE
number of curated paper reported on front page drop

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1026]
In the SAB report I used the number of publications approved in Canto 4232. 
Oddly the front page now reports 3593 curated publications. I'm sure this was also over 4000 recently.

**Comment by ValWood** [comment]
yep, screenshot from  departmental presentation:
<img width="491" alt="Screenshot 2022-09-20 at 13 36 56" src="https://user-images.githubusercontent.com/7359272/191259355-1201315f-89ca-44ba-b875-d49c8e140c58.png">

**Comment by kimrutherford** [comment]
Sorry about that.  The way the number is calculated changed in the issues below.  The number was the count of approved sessions, including those with no annotation in Canto.  It's now the number of approved sessions in Canto ignoring those with no annotation.

We now mark a publication as community curated if the community curator added at least one annotation (see pombase/canto#2594).  If there are no community annotations, but there is at least one admin annotations we mark the publication as admin curated.  If there are no annotations, it's not included in the curated publication count.

Perhaps we need to change the algorithm?

 - pombase/website#525
 - pombase/canto#2594
 - pombase/website#1933

**Comment by ValWood** [comment]
I think it's K. It's a shame about the drop but  quite a few papers go through Canto, but when inspected do not have data that is curatable   on closer inspection (i.e a structure with no biochemical. or interaction details that we can extract).
I am surprised it is 600 though!
