### ISSUE TITLE
Check for dashes in AlleleNotStartingWithGeneName chado check

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1027]
From pombase/canto#2642:

Could you tighten the check so that we see everything where there is not a dash. i.e. we should check for csi1- OR csi1delta not just csi1 (I have been trying to ensure that there is always a "-" seperator are delta after the gene name).

This will pick up things with spaces, and we can repair these with the proposed script if there are many.

**Comment by kimrutherford** [comment]
> csi1- OR csi1delta

I assume `csi1+` is OK too?  There are some disruptions too like: `mog1::ura4`

**Comment by kimrutherford** [comment]
Here's a sample where I changed the code so that the allele name has to start with a gene, followed "-" or "::", or needs to be like csi1delta or csi1+:

https://curation.pombase.org/kmr44/log.file.AlleleNotStartingWithGeneName.txt

Sorry, there are lots.

**Comment by ValWood** [comment]
Sorry there are other exceptions. 
The name can be a synonym. 
name(
namedelta*

**Comment by ValWood** [comment]
I don't think it will add many. to the existing query

**Comment by kimrutherford** [comment]
> The name can be a synonym.

It should be allowed that already.

> namedelta*

Do you mean `namedelta` followed by anything is OK?

**Comment by ValWood** [comment]
Name followed by either  delta,  "(" or "-" or "+" or ":"

namedelta can be followed by "(" or a number or letter (I think)

**Comment by kimrutherford** [comment]
OK, I've checked in my changes in time for the nightly load.

**Comment by kimrutherford** [comment]
Let's close this and open new issues for other changes.
