### ISSUE TITLE
help needed with log file error

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1028]
I can't figure this one out. I don't see these annotations in the session? even once let alone twice???

warning in c6ced0325cbf00af: storing feature_cvterm from c2a8d0f860ace791-genotype-7 to increased protein localization to centromere outer repeat [assayed_using] PomBase:SPBC1105.17 - failed to store feature_cvterm: that annotation has already been stored in Chado with properties:  evidence: "Chromatin immunoprecipitation experiment"  from session: c6ced0325cbf00af
warning in c6ced0325cbf00af: storing feature_cvterm from c2a8d0f860ace791-genotype-7 to increased protein localization to centromere outer repeat [assayed_using] PomBase:SPBC1861.01c - failed to store feature_cvterm: that annotation has already been stored in Chado with properties:  evidence: "Chromatin immunoprecipitation experiment"  from session: c6ced0325cbf00af
warning in c6ced0325cbf00af: storing feature_cvterm from c2a8d0f860ace791-genotype-7 to increased protein localization to subtelomeric heterochromatin during vegetative growth [assayed_using] PomBase:SPBC1105.17 - failed to store feature_cvterm: that annotation has already been stored in Chado with properties:  evidence: "Chromatin immunoprecipitation experiment"  from session: c6ced0325cbf00af

(I don't see any phenotypes with increased localization)

**Comment by kimrutherford** [comment]
Aren't these them?:

![image](https://user-images.githubusercontent.com/90474/192352738-b2a7df7f-dc83-47ef-b98b-3c7b6a070649.png)

The genotypes are the same: `cnp1+[Overexpression]`

**Comment by ValWood** [comment]
Ignore me I was using the 2nd session ID feature_cvterm from c2a8d0f860ace791
