### ISSUE TITLE
Load genes from PubMed keywords into Chado

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1038]
Use PubMed keywords to extend literature mentioning a gene on the gene pages, and flag  (colour) as curated/uncurated 

(Aside this will also be very useful to curators to identify important uncurated papers on a specific gene)

Edit: also show these genes from keywords on the publication pages.

**Comment by kimrutherford** [comment]
I don't understand what's needed here.

**Comment by ValWood** [comment]
The SAB (and me) are concerned that a gene only gets into the literature list once a publication is curated and the genes are manually assigned to the publication in Canto. This means that 1000s of publications for a gene will not appear in the literature section.

We thought it would be better also to associate PMIDs to genes using PubMed keywords (for a small-scale paper authors will always put the gene of interest in the keyword list). This would make it more likely that people will find relevant publications for a specific gene. It will also assign review papers to specific genes (we don't assign genes to these).

(We also wanted to flag curated and uncurated papers in some way. Currently only curated are displayed)

**Comment by kimrutherford** [comment]
Thanks, that makes sense except for:

> We also wanted to flag curated and uncurated papers in some way. Currently only curated are displayed

What do you mean by displayed?  Displayed where?

**Comment by ValWood** [comment]
In the literature section of a gene page. At the moment, the literature section only includes curated papers. The SAB were a bit disturbed by this. If a publication has a gene_name as a keyword, it should be included in the literature section even if it isn't curated yet.

**Comment by kimrutherford** [comment]
OK, thanks.

Note to self, here's an example of a gene name in the keywords: https://pubmed.ncbi.nlm.nih.gov/37189341/
XML: http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&retmode=xml&retmax=99999&id=37189341

**Comment by kimrutherford** [comment]
This might be useful for publications with genes from keywords but with no annotation:
 - pombase/website#2087

**Comment by kimrutherford** [comment]
On the pages for publications that have no annotations but have genes from keywords, we could think about including a genes table directly in the publication page.

**Comment by kimrutherford** [comment]
> On the pages for publications that have no annotations but have genes from keywords, we could think about including a genes table directly in the publication page.

Here's my mock up for discussion:

![image](https://github.com/pombase/pombase-chado/assets/90474/053d7d16-93b3-400d-9be0-bb9c32966d35)

**Comment by ValWood** [comment]
Looks good. What will we do if a gene listed in the keywords does not end up being curated (this can happen quite  if it isn't a gene of  direct study.


For exmaple here
https://www.pombase.org/reference/PMID:34686329
hsp90 is  in the title and an integral part of the model, but there is no data for hsp90 in the paper (although in this case I made some TAS annotations)

Should we still keep a table with the remaining genes?

**Comment by kimrutherford** [comment]
> Should we still keep a table with the remaining genes?

I think so, as long as we are clear in the description of the table that it's only for the unannotated genes.

**Comment by kimrutherford** [comment]
We should also show these genes from keywords on the publication pages.

**Comment by kimrutherford** [comment]
> I think so, as long as we are clear in the description of the table that it's only for the unannotated genes.

Possibly we don't won't to put the "Unannotated genes" section at the top of the page because the annotations are more important.  Let's discuss that.

**Comment by kimrutherford** [comment]
Done!  At least as a first pass.  From tomorrow we will have 526 publications with genes from PubMed keywords stored in Chado.  296 of the publications don't have an approved Canto session so we'll be picking up a lot of information.

After the New Year we'll [need to decide how to display the genes](https://github.com/pombase/website/issues/2123).
