### ISSUE TITLE
Load curation tool genes with no annotation into Chado

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#104]
Currently only genes with annotation are loaded into Chado from the curation tool.

If a gene added to a curation session but no annotation is made for it, it doesn't get written out.  It should be written out then loaded into the feature_pub table.

~Some changes will be needed at the Ensembl end too.~

Original comment by: kimrutherford

**Comment by ValWood** [comment]
Do we do this?
I think this is so we can add genes to a review paper etc?

**Comment by kimrutherford** [comment]
> I think this is so we can add genes to a review paper etc?

I think so.

Only the annotations from Canto are stored in Chado for now.  If you have a session with just genes we don't store in Chado that the genes are associated with the paper.

We do have some associations like that from the contig files.  If you have /db_xref="PMID:..." on a gene, eg. SPAC688.16 then that is stored in Chado.

**Comment by ValWood** [comment]
Is this still the case?

**Comment by kimrutherford** [comment]
> Is this still the case?

Yep, but maybe it's good to fix it soon-ish.  It's sort-of related to this issue from the SAB about showing genes from PubMed on the publication pages: #1038

> If a gene added to a curation session but no annotation is made for it, it doesn't get written out.

I checked and that's not true.  Maybe it used to be like that but now if you add genes to a session and the session is APPROVED then the genes will be written out from Canto even if they have no annotation.

But the code to read the Canto data into Chado currently only loads genes that have annotation.

Example of a session with lots of genes but a sad publication page:
  - https://curation.pombase.org/pombe/curs/97ae62f3a3b65885/ro
  - https://www.pombase.org/reference/PMID:31364709

Fixing this is relatively quick I think - maybe an hour or two.

**Comment by ValWood** [comment]
In that case it can be "high priority"

**Comment by kimrutherford** [comment]
I've implemented that in time for the nightly load.   But the BioGRID download server is having issues so it's possible that the load will fail.

**Comment by kimrutherford** [comment]
> I've implemented that in time for the nightly load. But the BioGRID download server is having issues so it's possible that the load will fail.

The load worked fine but my change didn't work.  I forgot that I needed to change two places in the code.

**Comment by kimrutherford** [comment]
> I'm going to put it aside for now while I think over how to do this properly

I have a plan now and I've started chipping away at this.

I'm changing the code so that when a feature to publication relation is stored, it also store a "feature_pub_source" property on the relation.  So the feature<->pub relations from the embl files get tagged with `contig_file_dbxref`.  We'll tag the Canto relations with `canto` and the relations from PubMed keywords with the source `pubmed_keyword`.

With those properties added the web code will be able to see why a gene is associated with publication so we'll be able to show genes that come from PubMed in a table.

**Comment by kimrutherford** [comment]
> I have a plan now and I've started chipping away at this.

This is finally done and committed, this time without causing a bug like pombase/website#2120

Next:
  - pombase/website#2123
