### ISSUE TITLE
where are the complex file instructions and filters

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1041]
I need to work out why condensin complex (GO:0000796) is filtered. I think it is to do with the removal of the nuclear versions of the complex, I suspect this is an ID I used to filter.

**Comment by kimrutherford** [comment]
Hi Val.

It's configured in the "file_exports" section of the config file: https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L9161

Have a look in `"excluded_terms"`

Sorry I haven't documentation this part of the config file.  I've added an issue about that:
  - https://github.com/pombase/website/issues/1961

**Comment by ValWood** [comment]
Sorry you didi tell mer recently, and I forgot it moved into the config.

**Comment by ValWood** [comment]
fixed
