### ISSUE TITLE
has_direct input, replace with has_input

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1042]
THIS MIGHT BE DONE

has_direct_input is a legacy relation. 

Can we do a **global replace of has_direct_input with has_input** (anywhere that we have used it). 

(for some reason I thought we had done this, but perhaps we just replace has_direct_input with has_input in the GO export?)

**Comment by ValWood** [comment]
val to check the PomBAse GAF

**Comment by ValWood** [comment]
There are no
has_direct input in 
[gene_association.pombase.gz](https://www.pombase.org/data/annotations/Gene_ontology/gene_association.pombase.gz)

but I'm still not sure that they would be in this file....

**Comment by kimrutherford** [comment]
> THIS MIGHT BE DONE

I thought this sounded familiar: https://github.com/pombase/pombase-chado/issues/974

> but I'm still not sure that they would be in this file....

I checked the code.  All relations in that file are the same as they are in Canto.  No mapping is done.
