### ISSUE TITLE
remove line from log files?

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1045]
| log.2022-12-10-21-25-22.allele-comments-from-supporting-data | 2022-12-11 00:56 | 
  | log.2022-12-10-21-25-22.allele-synonyms-from-supporting-data | 2022-12-11 00:56 | 

can the lines
loading extra allele comments

be removed from these files so I don't need to look to see they are zero?

**Comment by kimrutherford** [comment]
Done, but not in time for tonight's load.  Should be gone on Tuesday morning.
