### ISSUE TITLE
No longer classify antisense ncRNA

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1047]
We decided that we will no longer try to classify non-coding RNAs as antisense.
So far around 689 ncNRAs are classified as antisense but this is only a small subset.

It would be impossible to maintain this classification because
i) we are not sure of the exact boundaries of the ncRNAs
ii) the UTRs can vary in different conditions.

Actions
 - [x] remove `FT                   /SO="SO:0000644"`
 - [x]  make names of the format "xxx-antisense=#" into obsolete_name
 - [x] change product line "antisense RNA" or "antisense RNA (predicted) to ncRNA

**Comment by ValWood** [comment]
This will also fix the new bug where the missing ncRNAs with an antisense SO label are missing from the query builder

**Comment by kimrutherford** [comment]
I have a script ready to go.  Do you have any contig file changes to commit before I mangle the files?

**Comment by ValWood** [comment]
I'm up to date. But you prbably don't want to do it now. I will be up to date at the end of every day.

WHile you are parsing, could you also remove all
/fasta_file="fasta/
AND all
/gene

data are legacy
/gene, we will need to recreate from primary_nmaes when we submit to EMBL, but the current ones are not actively maintained and are very out of date (many genes do not have /gene at all) . It would be best to recreate them genome-wide upon submission.

**Comment by kimrutherford** [comment]
> remove FT /SO="SO:0000644"
> make names of the format "xxx-antisense=#" into obsolete_name
> change product line "antisense RNA" or "antisense RNA (predicted) to ncRNA

That's all done.

> remove all
> /fasta_file="fasta/
> AND all
> /gene

That's done too now, as a separate commit.

**Comment by ValWood** [comment]
This is good, but I mande a mistake. 

The products should be "non-coding RNA" not "ncRNA" (for consistency)
and could you also do
"antisense RNA (predicted), possible alternative UTR"
 to
"non-coding RNA (predicted), possible alternative UTR" 

I will review the rest manually

**Comment by kimrutherford** [comment]
> The products should be "non-coding RNA" not "ncRNA" (for consistency)

That's done now.

> and could you also do
> "antisense RNA (predicted), possible alternative UTR"
> to
> "non-coding RNA (predicted), possible alternative UTR"

Done.

**Comment by ValWood** [comment]
Looks good. Will keep this open as there are a couple of other things. Will chat about  it but this will remind me.

**Comment by ValWood** [comment]
ping

**Comment by ValWood** [comment]
I
