### ISSUE TITLE
A  new allele name log (alleles with spaces)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1048]
Could you provide a log of any allele name containing spaces.
I will fix these with higher priority than other allele  name fixes, because most are a bit crazy shoehorning multiple things into the allele name.

**Comment by kimrutherford** [comment]
I've added a new log file to report allele with spaces in the name.  I didn't make the edit in time for tonight's load but it should be there on Wednesday morning.  The file name will look something like `log.2023-01-02-21-23-20.chado_checks.allele_with_space_in_name`
