### ISSUE TITLE
Store more data from session in Chado

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#105]
Store the triage status of the publication in Chado so that the information can get through to Ensembl.  This will allow us to put a note on a gene page that says which reviews the gene was mentioned in.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/27

**Comment by mah11** [comment]
Did this actually get done? I don't see any follow-up comment from Kim, tho it is ancient ...

**Comment by ValWood** [comment]
possibly not

**Comment by ValWood** [comment]
is this covered by
 https://github.com/pombase/pombase-chado/issues/67?

**Comment by mah11** [comment]
If Kim has any current reason to do this part:

> Store the triage status of the publication in Chado

fine and dandy, but if not, we can close this ticket.

I think this part

> so that the information can get through to Ensembl

 is superseded by the lovely, delightful fact that we no longer have to get any literature curation data through to Ensembl.

If I understand correctly, we could get genes onto publication pages (which already exist) for reviews by creating a Canto session for each one, adding the gene list, and putting the session through. Or we may want Kim to help with some more automated route, but that would be a whole different ticket.

**Comment by ValWood** [comment]
Let's close. If/when we need to do this as part of publication page info it will soon become apparent...
