### ISSUE TITLE
yos9 had no Methionine

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1052]
Fixing the UTRs I found a gene  that I had not fixed correctly.
https://www.pombase.org/gene/SPAC227.11c
@manulera  be aware,  will have a new N-term exon.  the fix is incorrectly described here:
https://github.com/pombase/curation/issues/3024

@kimrutherford  can we run a check for features (ex-pseudo) which do not have N-terminal Methionine?

**Comment by ValWood** [comment]
Another check would  be to check that the 3' end of the 5' UTRs are always  adjacent to the gene. For this one, I had got the 5' UTR in the correct place for the start, but I hadn't added the new exon, so there was. gap between the UTR and the CDS.

**Comment by kimrutherford** [comment]
> can we run a check for features (ex-pseudo) which do not have N-terminal Methionine?

https://www.pombase.org/results/from/id/f1f21341-502d-478a-8266-136e263ca0db

It's also possible to find them with `^[^M]` in the motif search.

> Another check would be to check that the 3' end of the 5' UTRs are always adjacent to the gene.

Is that covered by this log file?:
https://curation.pombase.org/dumps/latest_build/logs/log.2023-01-09-21-24-08.web-json-write

**Comment by ValWood** [comment]
> Is that covered by this log file?:
https://curation.pombase.org/dumps/latest_build/logs/log.2023-01-09-21-24-08.web-json-write

yes!

**Comment by kimrutherford** [comment]
Is there anything else to do here?
