### ISSUE TITLE
filter  Complex portal  protein binding annotations with non-pombe IDs in the "with"field

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1053]
I don't think these should be in GO, since GO is representing normal, actual biology. The only  inter-species protein-protein interactions should be between host and pathogen proteins.

https://github.com/geneontology/go-annotation/issues/4241

so, we should  filter any annotation with a non pombe uniprot Id in the with filed.

Not urgent

**Comment by ValWood** [comment]
_This is a smal task that can be slotted in some time, but I don't know if there are any, so maybe they are filtered anyway (do we filter protein binding from Complex Portal? I think we might? in which case this can close)_

**Comment by ValWood** [comment]
this is largely a duplicate (because  I think Complex Portal is the only source) https://github.com/pombase/pombase-chado/issues/1001

**Comment by kimrutherford** [comment]
There are only 35 pombe annotations that are assigned by ComplexPortal.  Are those the ones you're thinking of here?

Only 5 of those have a with/from and in those 5 cases the value is "ComplexPortal:CPX-565".

**Comment by ValWood** [comment]
OK do we load those?

**Comment by kimrutherford** [comment]
> OK do we load those?

Yep, those numbers were from Chado queries.

Although now when I query again I see only 23 annotations assigned_by ComplexPortal and 4 annotations have a "with" value that's a ComplexPortal ID.

These are the 4 annotations with a "with":
```
 SPAC140.01   | mitochondrial respiratory chain complex II, succinate dehydrogenase complex (ubiquinone)
 SPAC140.01   | tricarboxylic acid cycle
 SPCC330.12c  | tricarboxylic acid cycle
 SPAC1556.02c | tricarboxylic acid cycle
```
