### ISSUE TITLE
publication number

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1055]
Is the number of curated papers correct on the front page?
 3625 curated publications
it was once over 4000, I'm sure?

and

https://curation.pombase.org/pombe/stats/annotation
Totals: | 4265 | 3213 | 1052 | 70401 | 21358
-- | -- | -- | -- | -- | --

**Comment by ValWood** [comment]
sab report days 
 To date, we have curated >300,000 ontology-based or controlled annotations  (with appropriate metadata), standardising data from >4209 individual

**Comment by kimrutherford** [comment]
Sorry, the count for admin curated publications was wrong.  It's fixed now.
