### ISSUE TITLE
Check Gaf/GPAD excludes dubious

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1056]
I noticed that Amigo has more proteeins than we submit.
<img width="609" alt="Screenshot 2023-01-23 at 21 12 16" src="https://user-images.githubusercontent.com/7359272/214304893-0d40478d-22dd-4172-99c1-ee0979f80325.png">

since we are the DBAuthortiy all proteins should come through us. Before I report it I just wanted to check,
 did we start submitting dubious when we moved to GPAD?

**Comment by kimrutherford** [comment]
> did we start submitting dubious when we moved to GPAD?

Yep, I caused a GAF bug when we moved to the new code for GAF/GPAD writing.  The GPAD files don't have the dubious proteins but the GAF files do.

I've fixed the code and I'll check the GAF files on Thursday morning.

**Comment by kimrutherford** [comment]
> I've fixed the code and I'll check the GAF files on Thursday morning.

The GAF file is fixed.
