### ISSUE TITLE
List of all uncurated papers with structures

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1061]
it would be useful to get this list for annotation priority.  These are usually  the quickest papers to curate, because mostly we cna only get some binding information, and occasionally as activity, or they might throw in a couple of phenotypes. Most could probably be curated in about 15 minutes (this would also increase our stats! ;)

At present it's a bit annoying that these don't link to the gene pages (although, if we can't make a single annotations, they still will not, so we need to think about  this too).

http://dev.pombase.kmr.nz/reference/PMID:17937917

**Comment by ValWood** [comment]
ACtully I realize that you already mentioned this 

here
https://github.com/pombase/website/issues/1997#issuecomment-1426576811
There are a few things to decide about the publication page view, like should we show a list of the genes for the current structure? If so where?

**Comment by kimrutherford** [comment]
> although, if we can't make a single annotations, they still will not, so we need to think about this too

I don't understand that bit.  The gene IDs come from PDB so we can add links even if there is no annotation.

**Comment by kimrutherford** [comment]
Here's the list of publications with pombe structures that aren't in Chado:

```
 PMID:10801440
 PMID:11709168
 PMID:11832950
 PMID:15979093
 PMID:16138082
 PMID:16790931
 PMID:19026779
 PMID:19581297
 PMID:22001694
 PMID:25619998
 PMID:26062005
 PMID:26292707
 PMID:28467824
 PMID:28988770
 PMID:31048492
 PMID:31740076
 PMID:32374864
 PMID:32518066
 PMID:32958768
 PMID:33536435
 PMID:34100774
 PMID:34194665
 PMID:34678589
 PMID:36250672
```

**Comment by ValWood** [comment]
> I don't understand that bit. The gene IDs come from PDB so we can add links even if there is no annotation.

Yes ignore. I wrote this before I saw that you were suggesting  just having the list.

I was thinking that we would need to have a curation to creat a link.

**Comment by ValWood** [comment]
Wow not so many. Perfect taks while waiting for GO continuous integration check to run ;)

**Comment by kimrutherford** [comment]
I don't know if it's useful but here's the list of publications with structures in PDB but don't have an APPROVED session:

```
 PMID:10801440
 PMID:11273706
 PMID:11709168
 PMID:11832950
 PMID:12018481
 PMID:14614509
 PMID:15979093
 PMID:16138082
 PMID:16777962
 PMID:16790931
 PMID:17190600
 PMID:17937917
 PMID:18381891
 PMID:18676809
 PMID:19026779
 PMID:19028693
 PMID:19307292
 PMID:19362535
 PMID:19363481
 PMID:19394293
 PMID:19474788
 PMID:19516334
 PMID:19581297
 PMID:19680239
 PMID:19884503
 PMID:20008938
 PMID:20089861
 PMID:21217703
 PMID:21444718
 PMID:21481773
 PMID:21610214
 PMID:22001694
 PMID:22081013
 PMID:22085934
 PMID:22437499
 PMID:22658721
 PMID:22971103
 PMID:23019579
 PMID:23201273
 PMID:23273506
 PMID:23481256
 PMID:23583778
 PMID:23609449
 PMID:23857276
 PMID:24449894
 PMID:24862735
 PMID:24939935
 PMID:25414009
 PMID:25428765
 PMID:25619998
 PMID:25883047
 PMID:25959226
 PMID:26062005
 PMID:26088418
 PMID:26215567
 PMID:26292707
 PMID:26673708
 PMID:26960127
 PMID:27105116
 PMID:27165520
 PMID:28162934
 PMID:28223353
 PMID:28241144
 PMID:28467824
 PMID:28533364
 PMID:28572513
 PMID:28735863
 PMID:28988770
 PMID:29160296
 PMID:29681468
 PMID:29804820
 PMID:29892076
 PMID:30051891
 PMID:30295604
 PMID:30651569
 PMID:30808655
 PMID:30911189
 PMID:31048492
 PMID:31740076
 PMID:32374864
 PMID:32518066
 PMID:32610137
 PMID:32755595
 PMID:32839613
 PMID:32958768
 PMID:33106658
 PMID:33536434
 PMID:33536435
 PMID:34100774
 PMID:34194665
 PMID:34678589
 PMID:35058438
 PMID:35512546
 PMID:35849625
 PMID:36002457
 PMID:36250672
 PMID:36423630
 PMID:36468882
```

**Comment by ValWood** [comment]
We should check why this structure isn't in
https://www.pombase.org/reference/PMID:36358328
(maybe it takes pdb a while to get the structures curated...)

**Comment by ValWood** [comment]
>Here's the list of publications with pombe structures that aren't in Chado:

presumably these authors did not mention pombe, or fission yeast in their Keywords? I should send a reminder about this at some point...

**Comment by ValWood** [comment]
> Here's the list of publications with pombe structures that aren't in Chado:

presumably these authors did not mention pombe, or fission yeast in their Keywords? I should send a reminder about this at some point...

could you add these to the load?

**Comment by ValWood** [comment]
> We should check why this structure isn't in
https://www.pombase.org/reference/PMID:36358328
(maybe it takes pdb a while to get the structures curated...)

I mailed pdb to see why this structure is missing

**Comment by kimrutherford** [comment]
> could you add these to the load?

Should we load these into Canto or directly into Chado?

**Comment by ValWood** [comment]
>Should we load these into Canto or directly into Chado?

I'm not sure. Both?

**Comment by kimrutherford** [comment]
> I'm not sure. Both?

**Comment by kimrutherford** [comment]
> I'm not sure. Both?

If they are in Canto and approved (or in progress) they end up in Chado automatically even if there is no annotation.  So Canto is best if you plan to eventually do that.  Otherwise directly into Chado makes sense.

**Comment by ValWood** [comment]
They will need to go through curation, so Canto please

**Comment by kimrutherford** [comment]
I've loaded the list into Canto.  Only 14 weren't already there.

Here is the list with the triage status after loading: [pdb_pubs.tsv.txt](https://github.com/pombase/pombase-chado/files/10728920/pdb_pubs.tsv.txt)

**Comment by ValWood** [comment]
we can close this?
