### ISSUE TITLE
fix RNA Central export

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1062]
As per Andrew's email
@afg1

**Comment by kimrutherford** [comment]
I've fixed the RNAcentral export config by adding "lncRNA" to the list of types that are exported.  The file will be updated by the (UK) morning.

**Comment by kimrutherford** [comment]
>  The file will be updated by the (UK) morning.

It's updated now: https://www.pombase.org/nightly_update/misc/rnacentral.json

**Comment by ValWood** [comment]
Is sncRNA in too?

**Comment by kimrutherford** [comment]
> Is sncRNA in too?

Yep!  Everything except mRNA.
