### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1065]
Some annotations that were there last week have disappeared form the query builder.

No results for: genes annotated with "LYR family" ([PBO:0091211](https://www.pombase.org/term/PBO:0091211))

There were 8 annotations.
They are annotated in the contig files, and usually appear in the protein feature section of the page.

**Comment by ValWood** [comment]
and the ID now goes to 

<div _ngcontent-eni-c108="" class="details-page-name-and-id" style="box-sizing: border-box; margin: 0px 0px 0.5em; padding: 0.6em 0px 0px; max-width: 1400px; font-size: 30.8px; color: rgb(51, 51, 48); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span _ngcontent-eni-c108="" class="details-page-name-and-id-prefix" style="box-sizing: border-box; color: rgb(102, 102, 102);">:</span><span> </span><span _ngcontent-eni-c108="" class="name-id-highlight" style="box-sizing: border-box; font-weight: 700;">DNA-binding transcription factor, zn(2)-C6 fungal-type, truncated</span><span> </span>(PBO:0091211)</div><div _ngcontent-eni-c108="" id="term-summary" class="details-page-summary" style="box-sizing: border-box; font-size: 16.94px; border-width: 1px 0px; border-right-style: initial; border-left-style: initial; border-right-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(187, 187, 187); border-bottom-style: solid; border-bottom-color: rgb(187, 187, 187); padding: 0.5em 0px; display: inline-block; max-width: 1400px; margin-bottom: 1em; min-width: 1150px; color: rgb(51, 51, 48); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">





</div>

**Comment by ValWood** [comment]
I see it is associated with a different PBO:ID, but up until now these IDs have been stable haven't they? or no?
I just never saw my PBO queries change before.

**Comment by kimrutherford** [comment]
> I see it is associated with a different PBO:ID, but up until now these IDs have been stable haven't they? or no?

It's a slightly messy situation that I haven't got around to fixing yet.  The PBO IDs from Ensembl PomBase days are stable but the IDs that have been created since aren't stable.  :-(

I'll work on a fix and I can explain why things are so messy on the next call.

**Comment by kimrutherford** [comment]
I found an old issue where Antonia found this problem: https://github.com/pombase/website/issues/1055#issuecomment-443505675

I commented there that I'd fixed it, but I didn't make all the changes needed.

**Comment by kimrutherford** [comment]
> but I didn't make all the changes needed

I've now fixed the loading to keep the PBO IDs stable, hopefully.  I'll check things on Tuesday morning.

This old issue is related as well: https://github.com/pombase/pombase-chado/issues/563

**Comment by kimrutherford** [comment]
> I've now fixed the loading to keep the PBO IDs stable, hopefully. I'll check things on Tuesday morning.

It didn't work out well.  :-)

There were a couple of problems.

The OBO file loading code had a bug that meant that non-ASCII characters (like "β", "é" and "ü") were getting mangled.  That's fixed now and I'll check again on Wednesday morning.

The non-ASCII characters are mostly from names in MONDO terms, (like ["attenuated Chédiak-Higashi syndrome"](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http://purl.obolibrary.org/obo/MONDO_0018133)) so not a problem for making the PBO IDs stable.

I doesn't look great on some pages at the moment: https://www.pombase.org/term/MONDO:0018133
but it should be OK tomorrow.

The "β" is from an SGD gene product.  The products get written into Chado OK but aren't written to the OBO file correctly.  It gets written out to an OBO file because gene product are stored as terms and have there own PBO IDs.

The reason for this complication is that the PBO terms are written to an OBO file at the end of each load and then that file is read into Chado the next day.  That's how we keep the PBO term IDs the same over time.

**Comment by kimrutherford** [comment]
Change 
FT                   cv=warning; db_xref=PMID:26615217; date=20170404"
FT                   /controlled_curation="term=warning, Chr_II:1987101!C->GC

chr3:g.178936091G>A

**Comment by kimrutherford** [comment]
@manulera

**Comment by manulera** [comment]
I have fixed some of these in the svn file (diff below). See next comment.

```diff
-FT                   /controlled_curation="term=warning, Chr_I:101871!A->AG;
+FT                   /controlled_curation="term=warning, I:g.101871_101872insG;
-FT                   /controlled_curation="term=warning, Chr_I:682993!TC->T;
+FT                   /controlled_curation="term=warning, I:g.682994delC;
-FT                   /controlled_curation="term=warning, Chr_I:1424708!CA->C;
+FT                   /controlled_curation="term=warning, I:g.1424709delA;
-FT                   /controlled_curation="term=warning, Chr_I:1625092!T->TC;
+FT                   /controlled_curation="term=warning, I:g.1625092_1625093insC;
-FT                   /controlled_curation="term=warning, Chr_I:2343703!G->GA;
+FT                   /controlled_curation="term=warning, I:g.2343703_2343704insA;
-FT                   /controlled_curation="term=warning, Chr_I:2588066!C->CA;
+FT                   /controlled_curation="term=warning, I:g.2588066_2588067insA;
-FT                   /controlled_curation="term=warning, Chr_I:2588021!C->CA;
+FT                   /controlled_curation="term=warning, I:g.2588021_2588022insA;
-FT                   /controlled_curation="term=warning, Chr_I:3125118!A->AT;
+FT                   /controlled_curation="term=warning, I:g.3125118_3125119insT;
-FT                   /controlled_curation="term=warning, Chr_I:3197528!A->AG;
+FT                   /controlled_curation="term=warning, I:g.3197528_3197529insG;
-FT                   /controlled_curation="term=warning, Chr_I:3450130!GT->G;
+FT                   /controlled_curation="term=warning, I:g.3450131delT;
-FT                   /controlled_curation="term=warning, Chr_I:4407494!T->TG;
+FT                   /controlled_curation="term=warning, I:4407494_4407495insG;
-FT                   /controlled_curation="term=warning, Chr_I:4410191!CG->C;
+FT                   /controlled_curation="term=warning, I:g.4410192delG;
-FT                   /controlled_curation="term=warning, Chr_I:5142627!A->AG;
+FT                   /controlled_curation="term=warning, I:g.5142627_5142628insG;
-FT                   /controlled_curation="term=warning, Chr_II:825012!G->A;
+FT                   /controlled_curation="term=warning, II:g.825012G>A;
-FT                   /controlled_curation="term=warning, Chr_II:1948953!GA->G;
+FT                   /controlled_curation="term=warning, II:g.1948954delA;
-FT                   /controlled_curation="term=warning, Chr_II:1950050!A->AG;
+FT                   /controlled_curation="term=warning, II:g.1950050_1950051insG;
-FT                   /controlled_curation="term=warning, Chr_II:1960392!A->AG;
+FT                   /controlled_curation="term=warning, II:g.1960392_1960393insG;
-FT                   /controlled_curation="term=warning, Chr_II:1987117!TG->T;
+FT                   /controlled_curation="term=warning, II:g.1987118delG;
-FT                   /controlled_curation="term=warning, Chr_II:2049891!AT->A;
+FT                   /controlled_curation="term=warning, II:g.2049892delT;
-FT                   /controlled_curation="term=warning, Chr_II:2053516!G->GC;
+FT                   /controlled_curation="term=warning, II:g.2053516_2053517insC;
-FT                   /controlled_curation="term=warning, Chr_II:2219928!A->AT;
+FT                   /controlled_curation="term=warning, II:g.2219928_2219929insT;
-FT                   /controlled_curation="term=warning, Chr_II:2709414!G->GC;
+FT                   /controlled_curation="term=warning, II:g.2709414_2709414insC;
-FT                   /controlled_curation="term=warning, Chr_II:2798040!CT->C;
+FT                   /controlled_curation="term=warning, II:g.2798041delT;
-FT                   /controlled_curation="term=warning, Chr_II:3040332!C->CG;
+FT                   /controlled_curation="term=warning, II:g.3040332_3040333!insG;
-FT                   /controlled_curation="term=warning, Chr_II:3619003!A->AG;
+FT                   /controlled_curation="term=warning, II:g.3619003_3619004insG;
```

**Comment by manulera** [comment]
Hi @ValWood I am fixing these, but I found some with discrepancies or errors. I did not manage to understand what they are comparing the table in the link below with the contents of the contig files.

https://www.pombase.org/status/sequence-updates-pending

in mvp1

```
# In contig, Not clear what this means
FT                   /controlled_curation="term=warning, Chr_I:3460318!T->T;

# in the table it seems to be a C insertion
I	3460320	TTTACAAAGTCGGACAATCC	C		TGGCGGCGGTGTTCTAAAAA	No

# possible solution if the table is correct
FT                   /controlled_curation="term=warning, I:g.3460320insC;
```

in tam41
```
# in the contig (would mean addition)
FT                   /controlled_curation="term=warning, Chr_II:1987101!C->GC;
# Note that it says GC and not CG

# in the table (would mean deletion)
1987101	TCGCATAGACATATACCAAC		G	GAACGAATGACACCTGGCAG

# what it probably is
FT                   /controlled_curation="term=warning, II:g.1987102delG;
```


in SPBC23G7.06c

```
FT                   /controlled_curation="term=warning, Chr_II:2108180!->TTA;

# in the table
II	2108180	GTAAGATAATAAAGCATAAT	A		CCAATCTTCTTTGTTTGAAG	No		PMID:16823372

# Don't know which one is correct
```

in pta1

```
# in the contig
FT                   /controlled_curation="term=warning, Chr_I:3855790!G->TG;

# in the table
I	3855791	GGCATTTTTCACGTACAGGT		T	AGTCGAAACATTATTAAATA	No

# don't know which one is correct

```

in lsc1

```
FT                   /controlled_curation="term=warning, II:g.825012G>A;

# this one is missing in the table
```

**Comment by manulera** [comment]
BTW the full rules for this kind of syntax are in this site:

https://varnomen.hgvs.org/recommendations/DNA/variant/insertion/

**Comment by kimrutherford** [comment]
Thanks @manulera

Those fixes worked.

**Comment by ValWood** [comment]
OK:

tam1 table is correct
<img width="649" alt="tam41" src="https://user-images.githubusercontent.com/7359272/221858468-c8226516-24c6-4add-9d02-d9d02de9114f.png">


mvp1
Table is correct
<img width="616" alt="mvp1" src="https://user-images.githubusercontent.com/7359272/221858546-b28c69c6-4b6d-4f4b-af40-eb9321bb66ec.png">

23G7.06 Table is correct

<img width="640" alt="23G7 06" src="https://user-images.githubusercontent.com/7359272/221858597-9c5dfe9f-5c98-4487-9386-cdde2bbdf197.png">


pta1
<img width="654" alt="pta1" src="https://user-images.githubusercontent.com/7359272/221858641-b485aecd-da16-4f67-8554-9df6c00bd893.png">

**Comment by ValWood** [comment]
Lsc1
<img width="675" alt="Screenshot 2023-02-28 at 12 45 14" src="https://user-images.githubusercontent.com/7359272/221859508-d82a76dc-0f40-4a09-aa8a-77e45182adfb.png">

**Comment by ValWood** [comment]
I clearly never created a 'full length, frameshifted coding version' of SPAC11D3.11c

**Comment by ValWood** [comment]
Actually that is because in this strain it isn't a sequencing error, it has
this warning:
truncation LoF variant reverts to normal in strain CBS5557

**Comment by kimrutherford** [comment]
I'm not sure that the original problem Val reported is fixed as there were other terms that were causing problems.  I'll need to wait for a new load or two to confirm.

**Comment by kimrutherford** [comment]
Unfortunately there are two term names still to fix:

```
chromosome3.contig
26273-FT                   /controlled_curation="term=warning,
26274:FT                   Chr_III:1774235!T->TGATC; cv=warning;
26275-FT                   db_xref=PMID:26615217; date=20170404"

chromosome2.contig
50131-FT                   /controlled_curation="term=warning,
50132:FT                   II:g.3040332_3040333!insG; db_xref=PMID:26615217;
50133-FT                   date=20170404"
```

**Comment by manulera** [comment]
Should be fixed now, sorry about that.

**Comment by kimrutherford** [comment]
Thanks looks good.

My next step is to compare tonight's Chado database with tomorrow's database to make sure that the PBO IDs are now all stable.

**Comment by kimrutherford** [comment]
Hi.  There is still one warning that needs fixing:

```
FT                   /controlled_curation="term=warning,
FT                   Chr_III:1774235!T->TGATC; cv=warning;
FT                   db_xref=PMID:26615217; date=20170404"
```

Thanks.

**Comment by manulera** [comment]
Should be fixed again, let me know if it works out

**Comment by kimrutherford** [comment]
> Should be fixed again, let me know if it works out

Thanks.  I'm testing again this weekend.

**Comment by kimrutherford** [comment]
> I'm testing again this weekend.

It's taken a while but I think it's all fixed now.  The PBO IDs should now be stable across versions.

Val, the original result set you had trouble with (genes annotated with "LYR family") is now:
https://www.pombase.org/results/from/id/5f276ff8-44cf-45fc-9577-663d47060ec7

**Comment by ValWood** [comment]
Thanks!
