### ISSUE TITLE
Add new PHAF columns

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1066]
- Ploidy   -    needs to be mandatory (add to all files
 - allele variant ( add url for genotype format variant syntax)               
 - Use Condition column
   - Temperature (degrees C)                
   - Chemical or agent (concentration units)
   - 
 - Chemical or agent dose   
 - Phenotype score / Phenotype score units
   - use Severity column
     - currently: `FYPO_EXT:0000003` etc.
     - add:
       - fitness_log2(0.123)
       - normalised_difference(-0.4234)
       - store as properties in Chado (`feature_cvtermprop`)

* FYECO -> Glucose present (CHEBI)
* CHEBI,concentration
* FYECO (UV) -> FYECO:X(mJ)

**Comment by manulera** [comment]
Related to https://github.com/pombase/curation/issues/3465

**Comment by manulera** [comment]
@kimrutherford I am almost done with the file, would just have to figure out those exceptional systematic ids and what the alleles should be called. Going swimming now but will check tomorrow 🏊

https://github.com/manulera/phenomics_paper_HTP/blob/master/results/pombase_dataset.tsv

**Comment by kimrutherford** [comment]
Thanks Manu.  I've changed the loading code to handle the changes to the severity and condition columns.

**Comment by kimrutherford** [comment]
I've changed the PHAF loader to store the `allele_variant` and the phenotype score in Chado.  I'm still trying to think of a good way to store the new condition details.

We need to think about how and where to display the new information on the website.

**Comment by kimrutherford** [comment]
> Ploidy - needs to be mandatory

I've changed my mind on that.  It can continue to be optional in the cases where there is no allele variant.

**Comment by kimrutherford** [comment]
> I guess the assumption is haploid unless otherwise stated, but why does this have to do with the allele variant present or absent?

I was thinking that we would need to put something in the "Ploidy" column only if we have an allele variant column.  If there is no allele variant column, we won't need a "Ploidy" column.

**Comment by manulera** [comment]
I am looking at the PHAF headers and I think I see what you mean, but I don't think this problem is restricted to the allele variant column. The headers are clearly meant to describe either haploids or homozygous diploids, but it is not clear how you would describe a heterozygous diploid. Separating allele names, expression levels and all with a spacer? Two lines for the same phenotype, but then what would be the unique identifier of the pair?

You can call me on skype if you want to quickly discuss this.

**Comment by kimrutherford** [comment]
> but it is not clear how you would describe a heterozygous diploid.

There isn't a way to store these in the PHAF file.  The "Ploidy" column is a hack to allow loading the commonest diploids ("homozygous diploid").  That format doesn't support anything more complicated.

We have plans for a new PHAF format to handle this problem (see pombase/pombase-chado#496) but we haven't implemented it yet.  [Stable allele identifiers](pombase/pombase-chado#986) will make this problem easier.

**Comment by kimrutherford** [comment]
Hi @manulera

Sorry to come back to this after 2 weeks.

In the new PHAF file (`pombe-embl/external_data/phaf_files/chado_load/htp_phafs/PMID_34984977_phaf.tsv`), some of the FYECO conditions have empty brackets, like: `FYECO:0000211()`.  Does that need fixing?

Also should we include the unit ("C") after temperatures in conditions?  Or is the unit obvious in that case?

Here an example line that has examples of both questions:

| Gene systematic ID | FYPO ID      | Allele description | Expression | Parental strain | Background strain name | Background genotype description | Gene name | Allele name | Allele synonym | Allele type | Evidence    | Condition                                                     | Penetrance | Severity           | Extension | Reference     | taxon | Date       | Ploidy  | Allele variant         |
| ------------------ | ------------ | ------------------ | ---------- | --------------- | ---------------------- | ------------------------------- | --------- | ----------- | -------------- | ----------- | ----------- | ------------------------------------------------------------- | ---------- | ------------------ | --------- | ------------- | ----- | ---------- | ------- | ---------------------- |
| SPNCRNA.1130       | FYPO:0000725 | deletion           | null       | 972 h-          |                        |                                 |           |             |                | deletion    | ECO:0001563 | FYECO:0000138,FYECO:0000211(),FYECO:0000334,FYECO:0000005(32) |            | fitness_log2(0.11) |           | PMID:34984977 | 4896  | 2023-02-23 | haploid | III:g.319210_319876del |

Thanks!

**Comment by kimrutherford** [comment]
> Hi @kimrutherford, fixed here and updated on revision 8824 of svn

Thanks!  The finished the changes needed to load the conditions with temperatures and quantities into Chado.  The new PHAF file loads perfectly now.

I think this in done now.

We now need to think about how to show this new information:
   - pombase/website#2029
