### ISSUE TITLE
A few alleles with no name.

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1067]
<img width="322" alt="Screenshot 2023-03-03 at 08 42 44" src="https://user-images.githubusercontent.com/7359272/222674545-b23646c4-d757-4780-a4cd-3d0ed5cf40eb.png">
<img width="630" alt="Screenshot 2023-03-03 at 08 42 24" src="https://user-images.githubusercontent.com/7359272/222674565-8272da4c-a2dd-46dc-bbbd-07308f5ef509.png">

and a few others

**Comment by manulera** [comment]
Should be fixed now
