### ISSUE TITLE
Improve messages in legacy GAF file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1069]
Some warnings don't include line numbers:

```
Failed to load row: {UNKNOWN}: no value when storing assigned_by prop into feature_cvtermprop at /local-homes/pbuild/git/pombase-chado/lib/PomBase/Import/GeneAssociationFile.pm line 514
```

**Comment by kimrutherford** [comment]
Duplicates:
 - https://github.com/pombase/pombase-chado/issues/1075
 - https://github.com/pombase/pombase-chado/issues/1074

**Comment by kimrutherford** [comment]
> I've improved the GAF loader so that all message start with a line number.

Much better now:
https://curation.pombase.org/dumps/builds/pombase-build-2023-04-05/logs/log.2023-04-04-21-42-39.legacy_go_from_contigs

The fix has tidied up the main GAF log file too:
https://curation.pombase.org/dumps/builds/pombase-build-2023-04-05/logs/log.2023-04-04-21-42-39.gaf-load-output

**Comment by ValWood** [comment]
I was just about to fix these up. I notice that when I open in vi, the file now displays a control character at the end of every line. It never did before. Before I proceed, is this OK?

**Comment by kimrutherford** [comment]
> I was just about to fix these up. I notice that when I open in vi, the file now displays a control character at the end of every line. It never did before. Before I proceed, is this OK?

That's odd.  The extras characters appeared in this commit:

```
r8852 | vw253 | 2023-04-04 03:02:18 +1200 (Tue, 04 Apr 2023) | 1 line
curation/issues/3364
```

Were you using a different editor or copying and pasting?

I've removed the extra characters.

**Comment by ValWood** [comment]
I sometimes used TextEdit and sometimes vi depending what I am doing. It's odd that it never happened before (maybe it is a consequence to the extension change?). Anyway I should be using VSC now its a TSV
