### ISSUE TITLE
Update structures from PDB

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1072]
Haven't done this in a while.  For now it has to be done manually.

Update instructions are here: `pombe-embl/external_data/protein_structure/README.txt`

**Comment by kimrutherford** [comment]
We should see structures for three extra publications on Wednesday morning:

PMID:35314193
PMID:36442092
PMID:36797353

We also need to check this issue on Wednesday: https://github.com/pombase/pombase-chado/issues/1063

**Comment by kimrutherford** [comment]
> We should see structures for three extra publications on Wednesday morning

Yep, all good.

**Comment by ValWood** [comment]
nice, i just approved the session for the respiratory chain complex.
