### ISSUE TITLE
Combine not_assayed and wild-type product level in Chado

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1076]
We need not_assayed and wild-type product level  geneotypes to be stored in the same way (and therefore displayed together on the website)

**Comment by kimrutherford** [comment]
> We need not_assayed and wild-type product level geneotypes to be stored in the same way

What should the combined expression level be labelled as?   Is it OK to call it "Wild type".

I was just checking how things are labelled in Chado at the moment and noticed that we have an extra expression type that isn't available in Canto: "Endogenous"

It's from: `pombe-embl/external_data/phaf_files/chado_load/ltp_phafs/PMID_12615979_phaf.tsv`

Should we merge endogenous with not assayed and wild type?

The full list is:

|  expression              | count  |
|-------------------------- | --------|
|  Endogenous              | 32     |
|  Knockdown               | 458    |
|  Not assayed             | 13398  |
|  Null                    | 192    |
|  Overexpression          | 3382   |
|  Wild type product level | 3415   |

**Comment by ValWood** [comment]
>Should we merge endogenous with not assayed and wild type?

I guess so. Out of curiosity, where is it used?

**Comment by kimrutherford** [comment]
> Out of curiosity, where is it used?

It only occurs in this file: `pombe-embl/external_data/phaf_files/chado_load/ltp_phafs/PMID_12615979_phaf.tsv`

**Comment by ValWood** [comment]
Actually Iwe changed our minds on this one. The final ticket was
https://github.com/pombase/canto/issues/2544#issuecomment-1497375354
add an extra option for ectopic expression. So these will be classed using "ectopic" once the change is made

cc @manulera

**Comment by kimrutherford** [comment]
> Actually Iwe changed our minds on this one

I thought we were still going to merge not_assayed and wild_type in Chado?

**Comment by ValWood** [comment]
>I thought we were still going to merge not_assayed and wild_type in Chado?

we are, but  we are also adding an additional option for "ectopic expression" in the selector.

**Comment by kimrutherford** [comment]
> we are, but we are also adding an additional option for "ectopic expression" in the selector.

That's Canto though.  Are we changing the plan for loading into Chado?

**Comment by ValWood** [comment]
We still want to merge the display of not_assayed and wild_type in Canto


I think it would be good to flag the endogenous alleles clearly on the allele pages if possible, so it would be good to store this flag, even if we don't put it on the gene pages.  Somebody recently was a bit concerned that the ectopic constructs from his paper would not be clear to others (I can't find the e-mail now). But we will partly deal with this by clearer labeling of the allele type as a chimera, and the endogenous phenotype annotations.

**Comment by kimrutherford** [comment]
> Null | 192

Job for kmr: query Chado / PHAF files to find these.  

Also display Ectopic expression like `[Ectopic]`

**Comment by kimrutherford** [comment]
As we discussed, I've change "Endogenous" to "wild type product level" in `external_data/phaf_files/chado_load/ltp_phafs/PMID_12615979_phaf.tsv`

**Comment by ValWood** [comment]
These look like mistakes. Null would be odd for most.   
we need to check if they should be "not recorded" or "knockdown"

COuld you put this on the curation tracker. That will keep it near the top of my list.

**Comment by ValWood** [comment]
I have opened a ticket.
https://github.com/pombase/curation/issues/3495

**Comment by ValWood** [comment]
are you seeing NULL expression for rad3-136.

I only see
https://www.pombase.org/genotype/rad3-136-unknown-unknown-expression-not_assayed

**Comment by ValWood** [comment]
Also for ste11-mutant I only see
https://www.pombase.org/genotype/ste11-mutant-unknown-unknown-expression-not_assayed

**Comment by kimrutherford** [comment]
> are you seeing NULL expression for rad3-136.
> I only see
> https://www.pombase.org/genotype/rad3-136-unknown-unknown-expression-not_assayed

There's a diploid:

http://dev.pombase.kmr.nz/genotype/rad3-136-unknown-unknown-expression-null_rad3-136-unknown-unknown-expression-null

**Comment by kimrutherford** [comment]
> Also for ste11-mutant I only see
> https://www.pombase.org/genotype/ste11-mutant-unknown-unknown-expression-not_assayed

The genotype is here but there are no annotations so it doesn't get through to the website:
https://curation.pombase.org/pombe/curs/133b9a4cefba1a78/genotype_manage/ro

**Comment by ValWood** [comment]
cgs2-2
I only see WT product level ?
https://www.pombase.org/genotype/cgs2-2-T1366-T-nucleotide_insertion-expression-wild_type_product_level

**Comment by kimrutherford** [comment]
There are two other alleles in that list that are in Chado but not on the website because they have no annotation:
 - wee1+[Null]
 - cgs2-2[Null]

**Comment by ValWood** [comment]
I deleted this one

>The genotype is here but there are no annotations so it doesn't get through to the website:
https://curation.pombase.org/pombe/curs/133b9a4cefba1a78/genotype_manage/ro

**Comment by ValWood** [comment]
I don't understand  this

because 
cgs2-2  has 219e86a87274fe5f,0d638c12aef4db07,0d638c12aef4db07
in the table so presumably  therse are not all   sessions with no annotation?

**Comment by ValWood** [comment]
same question for wee1+
, presumably that's every session with the allele, not onlyu the "null expression" session

**Comment by ValWood** [comment]
Update as descrtibed here:
https://github.com/pombase/curation/issues/3495#issuecomment-1516135992

**Comment by kimrutherford** [comment]
> We need not_assayed and wild-type product level geneotypes to be stored in the same way (and therefore displayed together on the website)

I've made a separate issue about the website changes:
  - pombase/website#2039

**Comment by kimrutherford** [comment]
Use "Not assayed or wild type" as new text.

**Comment by kimrutherford** [comment]
This is done now.  I'll check it OK on Wednesday morning.

**Comment by kimrutherford** [comment]
> This is done now. I'll check it's OK on Wednesday morning.

Looks OK.
