### ISSUE TITLE
pombase-prediction.gaf

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1077]
log 
https://curation.pombase.org/dumps/latest_build/logs/log.2023-04-05-21-42-28.gaf-load-output

has

Updating /var/pomcur/sources/pombase-prediction.gaf
failed to download pombase-prediction.gaf
notice: no taxon filter - annotation will be loaded for all taxa
line 1: not enough fields - skipping
line 2: not enough fields - skipping
line 3: not enough fields - skipping
line 4: not enough fields - skipping
line 5: not enough fields - skipping
line 6: not enough fields - skipping
line 7: not enough fields - skipping
line 8: not enough fields - skipping
line 9: not enough fields - skipping
line 10: not enough fields - skipping
line 11: not enough fields - skipping
line 12: not enough fields - skipping
line 13: not enough fields - skipping
line 14: not enough fields - skipping
line 15: not enough fields - skipping
line 16: not enough fields - skipping
line 17: not enough fields - skipping
line 18: not enough fields - skipping
line 19: not enough fields - skipping
line 20: not enough fields - skipping
counts after loading pombase-prediction.gaf:

Is there a problem with the source file?
Let me know if I need to ask GO

**Comment by kimrutherford** [comment]
> Is there a problem with the source file?
> Let me know if I need to ask GO

Maybe it has moved?  We get a 404: http://snapshot.geneontology.org/products/annotations/pombase-prediction.gaf

**Comment by kimrutherford** [comment]
> Maybe it has moved? We get a 404:

This must be very recent because there was no problem in Tuesday night's load.

The version of pombase-prediction.gaf from my backup from Tuesday looks fine.  I've copied it to the appropriate place on the server for tomorrow's load.

I've also fixed the load script so that a missing pombase-prediction.gaf won't cause this problem in future.

If that URL from GO is incorrect, I'll update the script with the new URL.

**Comment by ValWood** [comment]
@pgaudet do you know if the file has been moved, or deprecated, and if so what the replacement it?

**Comment by kimrutherford** [comment]
> Maybe it has moved? We get a 404: http://snapshot.geneontology.org/products/annotations/pombase-prediction.gaf

I think I've found it: http://snapshot.geneontology.org/products/upstream_and_raw_data/pombase-prediction.gaf

**Comment by ValWood** [comment]
@kltm, Hi Seth, can you confirm that  the snapshot files have moved and that we have located the correct files. Also, if anything else has moved that we (and others) need to know about?
Cheers
Val

**Comment by ValWood** [comment]
@kltm  I see I did tag you already. Let us know which location we should be using.

**Comment by ValWood** [comment]
@kltm sorry I didn't not record the correct location for the snapshot.
Just to be sure, can you specify.

**Comment by kltm** [comment]
@ValWood 
http://snapshot.geneontology.org/products/upstream_and_raw_data/pombase-prediction.gaf

**Comment by ValWood** [comment]
Thanks, I was multi-tasking
