### ISSUE TITLE
separator in legacy GO file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1082]
https://curation.pombase.org/dumps/latest_build/logs/log.2023-04-13-21-43-31.legacy_go_from_contigs

ignoring IC from value containing a pipe ("|") at line 11: GO:0006281|GO:0005739

not urgent but IC-from filed "|" separator should be allowed

**Comment by kimrutherford** [comment]
We added that warning on purpose.  Does this comment still apply?: https://github.com/pombase/website/issues/1855#issuecomment-1104998992

**Comment by ValWood** [comment]
No I need to change it to a comma, it used to be a pipe!
