### ISSUE TITLE
Build the allele_qc container in the nightly load script

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1084]
In `allele_qc`:

```
docker build -f Dockerfile -t pombase/allele_qc:v5 .
```

Add a Docker service

@manulera

**Comment by manulera** [comment]
RElated to https://github.com/pombase/allele_qc/issues/42

**Comment by kimrutherford** [comment]
The container is now re-built and re-deployed by the nightly load script.  I'll check on Thursday to make sure it worked OK.

**Comment by kimrutherford** [comment]
> I'll check on Thursday to make sure it worked OK.

Yep, that worked.
