### ISSUE TITLE
Store Canto allele promoter info in Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1087]
Moved from:
  - https://github.com/pombase/canto/issues/2544

The promoter details will need to be stored somewhat like expression in Chado, so we'll be storing more `feature_relationshipprop` entries.

**Comment by kimrutherford** [comment]
> Store Canto allele promoter info in Chado

That's implemented now but I'm going to leave this open until we have a few examples in approved sessions for testing.

**Comment by kimrutherford** [comment]
> That's implemented now but I'm going to leave this open until we have a few examples in approved sessions for testing.

@ValWood @PCarme  Could you let me know when you've curated a few promoters?  Thanks.

**Comment by kimrutherford** [comment]
> Could you let me know when you've curated a few promoters? Thanks.

I didn't notice this comment:
https://github.com/pombase/canto/issues/2544#issuecomment-2003332763

I'll look out for them.

**Comment by ValWood** [comment]
I fixed 21 nmt1  promoters in this session PMID:28476936

**Comment by ValWood** [comment]
A few more fixes from the log files

P.rad21-cdc25+	cdc25	SPAC24H6.05	915dd27f11d0b65d -promter swap

pADH:cdc25+	cdc25	SPAC24H6.05	27524319ad84c25c -endogenous

P81nmt1-dis3+	dis3	SPBC26H8.10	f2202f3e99350d80

P81nmt1-rrp41+	rrp41	SPAC3G9.10c	f2202f3e99350d80

**Comment by kimrutherford** [comment]
The promoters from [ed9652a888c24c94](https://github.com/pombase/canto/issues/2544#issuecomment-2003332763) got stored correctly in Chado.

New issue about the website:
  - pombase/website#2160
