### ISSUE TITLE
Add a flag to export comments to GAF and PHAF

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1089]
We decided to add a flag (`--add-submitter-comment-column`?) to the export script to add the `submittter_comment` as an extra column in the output for GAF and PHAF.  We won't include this flag and output in the nightly load.  We'll use it when needed.

See also pombase/canto#2727

**Comment by kimrutherford** [comment]
That's done now.  On Thursday morning (assuming #1088 works OK), we'll be able to export GAF and PHAFs with the comments as an extra column.

We'll be missing any comments on multi-locus phenotype annotations.  We'll need a different plan for that.

**Comment by kimrutherford** [comment]
> We can worry about multi-allele comments alter. Are they a lot trickier?

It's tricky because we don't have an existing export format for multi-locus genotype annotations that we can add a column too.

**Comment by kimrutherford** [comment]
> On Thursday morning (assuming https://github.com/pombase/pombase-chado/issues/1088 works OK), we'll be able to export GAF and PHAFs with the comments as an extra column.

Here's a GAF file, with comments as an extra column:
https://curation.pombase.org/kmr44/pombase-build-2023-05-04.gaf-with-comments.tsv
(Only includes annotations with comments)

Same but PHAF/phenotypes:
https://curation.pombase.org/kmr44/pombase-build-2023-05-04.phaf-with-comments.tsv

**Comment by ValWood** [comment]
>It's tricky because we don't have an existing export format for multi-locus genotype annotations that we can add a column too.

Yes, I realised that last night ,

**Comment by kimrutherford** [comment]
This is done now and I've emailed Bjoern Peters.
