### ISSUE TITLE
Add /protein_id from EMBL to Chado when loading

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1090]
See: https://github.com/pombase/curation/issues/3345#issuecomment-1539240931

Example EMBL parsing code here: https://github.com/pombase/pombase-python/blob/61b108d2a22eca9da64f78ba8ec6b3e70ccad37a/make_embl_file.py#L61

**Comment by ValWood** [comment]
Is this done?

**Comment by kimrutherford** [comment]
I've now added `pombe-embl/supporting_files/pombe_protein_id_mapping.tsv` containing the protein IDs from the EMBL files.  And added an extra load step to read that file into Chado.

I'll check the result on Tuesday, then close this issue.
