### ISSUE TITLE
add a log file of alleles of type "unknown"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1091]
no hurry.
Periodically you have generated this list, but we may as well have a log file

**Comment by kimrutherford** [comment]
As a temporary solution, all the unknowns are in this file:
https://curation.pombase.org/kmr44/canto_allele_table_example.tsv
(Or at least they will be once oliver1 is working again)

From: https://github.com/pombase/canto/issues/2726

**Comment by kimrutherford** [comment]
> Can you let me know the numbe of unknowns we had 12 months ago? This will allow me to estimate the number fixed

Here are the numbers from Chado.  It's more of pain to get the older number from Canto, but let me know if you need them.

| date | count |
| --- | --- |
| 2022-05-21 | 1162 |
| 2023-05-21 | 1111 |

**Comment by ValWood** [comment]
That'll do!

**Comment by kimrutherford** [comment]
> As a temporary solution, all the unknowns are in this file:
> https://curation.pombase.org/kmr44/canto_allele_table_example.tsv

If you need just the unknowns from Canto (with PMIDs and sessions):
```sh
curl https://curation.pombase.org/kmr44/canto_allele_table_example.tsv | perl -ne '@a=split/\t/; print if $a[5] eq "unknown"' > canto_unknowns.tsv
```

It's less useful (no PMIDs or sessions) but you get a table of unknown alleles from Chado with:
```sh
curl https://curation.pombase.org/dumps/latest_build/misc/all_alleles.tsv | perl -ne '@a=split/\t/; print if $a[4] eq "unknown"' > chado_unknowns.tsv
```

I think this can be closed now?
