### ISSUE TITLE
GAF load bug: duplicated extension: "[part_of] autophagosome assembly"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1093]
This annotation from GOA:
```
UniProtKB O74312  atg9    enables GO:0017128      GO_REF:0000024  ISS     UniProtKB:Q12142        F       Autophagy-related protein 9     atg9|apg9|SPBC15D4.07c  protein taxon:284812    20230510        UniProt has_input(CHEBI:58088),part_of(GO:0045332),part_of(GO:0000045)|has_input(CHEBI:57643),part_of(GO:0045332),part_of(GO:0000045)|has_input(CHEBI:57262),part_of(GO:0045332),part_of(GO:0000045)|has_input(CHEBI:64612),part_of(GO:0045332),part_of(GO:0000045)     
```

doesn't load because of the error:

```
duplicated extension: "[part_of] autophagosome assembly""
```

which looks like a bug as each of the independent parts of the extension is unique:

 - `has_input(CHEBI:58088),part_of(GO:0045332),part_of(GO:0000045)`
 - `has_input(CHEBI:57643),part_of(GO:0045332),part_of(GO:0000045)`
 - `has_input(CHEBI:57262),part_of(GO:0045332),part_of(GO:0000045)`
 - `has_input(CHEBI:64612),part_of(GO:0045332),part_of(GO:0000045)`

**Comment by kimrutherford** [comment]
I looked into this.  The GAF reading code is messing up when an extension has a "|".  It's treating them like commas.

Here's an example of the problem.  This should be three separate annotations with a single "in ..." extension each:

![image](https://github.com/pombase/pombase-chado/assets/90474/b026d4f9-07e2-4d62-88c1-89f9ce37b8ef)
https://pombase.org/gene/SPAC6G9.13c

There are 6 pombe lines in the GOA GAF with a "|"

**Comment by ValWood** [comment]
Note that we decided for PomBAse that we would not use | in annotation extensions for this reason, so they should all be reported and fixed.
We always make separate annotations, which is much clearer.

**Comment by kimrutherford** [comment]
> Note that we decided for PomBAse that we would not use | in annotation extensions for this reason, so they should all be reported and fixed.

The annotations from Canto are always exported after splitting the annotations when there are pipes in the extensions.

> There are 6 pombe lines in the GOA GAF with a "|"

I got that wrong, there are 9.  One is from UniProt and 8 from IntAct.

**Comment by kimrutherford** [comment]
I've fixed the GAF loader to handle pipes in extensions.  I'll check the load in the morning to make sure it's all OK.

**Comment by kimrutherford** [comment]
> Is this the reason this log file is empty:

It has been empty for a few months but it has a weird error in it today.  At first look it seems to be related to the issue you just made: pombase/pombase-chado#1094
