### ISSUE TITLE
update FYPO slim set

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1096]
change  slim term

transmembrane transporter activity phenotype | FYPO:0002114
to
abnormal transport" (FYPO:0001720)

**Comment by ValWood** [comment]
Correction, I will change to "transport. phenotype" not "abnormal transport phenotype"

**Comment by ValWood** [comment]
I can'\t remember where to do this, @kimrutherford can you let me know.

**Comment by ValWood** [comment]
Done, check tomorrow

**Comment by kimrutherford** [comment]
Just checked. This is done.
