### ISSUE TITLE
PMID:35811551  qualitative level

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1098]
loading: /var/pomcur/sources/pombe-embl/external_data/Quantitative_gene_expression_data/Esposito_RNA_PMID_35811551_quantitive.txt
skipping this annotation:
SPBC3D6.04c mad1 RNA during(GO:0072690) 2-3.3  ECO:0005518 single_cell FYECO:0000126,FYECO:0000005 PMID:35811551 4896 2023-06-29
because copies per cell must be a positive floating point number with an optional '>' or '<' at the start

So this row is failing
SPBC3D6.04c	mad1	RNA	during(GO:0072690)	2-3.3		ECO:0005518	single_cell	"FYECO:0000126,FYECO:0000005"	PMID:35811551	4896	2023-06-29

(indicates a range, can the hyphen be allowed)
I think range is allowed  if integers are used, because I used it earlier on this session before the numbers were refined and it appeared OK

**Comment by ValWood** [comment]
Also,
even though this session was assigned to Silke,
https://curation.pombase.org/pombe/search/type/all_publications?model=track&search-term=PMID%3A35811551&submit=search

It appears in the "pombase curated" list, not the community curated list

**Comment by ValWood** [comment]
> It appears in the "pombase curated" list, not the community curated list
it is possible this is becasue it wasn't approved, I'm not sure ...will check tomorrow.

**Comment by ValWood** [comment]
Nope it is still "PomBase curated" even though Silke is the assigned curator.
Because there is no curation in the actual session (it's either in contigs or external files), I can probably fix it by deleting and creating a new session, but it would be good to know why.

**Comment by kimrutherford** [comment]
> Because there is no curation in the actual session (it's either in contigs or external files), I can probably fix it by deleting and creating a new session, but it would be good to know why.

The current algorithm is that if a session has any community annotations then it counts as a community session, otherwise it's an admin session.  We made that change because sometimes sessions are assigned to a community member but they never do any annotation.

This change happened for issue pombase/canto#2594

**Comment by ValWood** [comment]
Right. Silke is in the header of the external file. Does that get taken into account?
It might not be formatted correctly. I could add her ORCID.

**Comment by kimrutherford** [comment]
The headers aren't processed yet.

**Comment by ValWood** [comment]
Ah got it. I see others are attribute to PomBAse when they were really submitted by community
PMID:23101633

This will be good for community curation stats.
We should add these to the paper count (It might increase the percentage quite a bit), but because these are HTP we  woudl not want to include them in the

Canto curator summary table here:
https://curation.pombase.org/pombe/stats/annotation

only in the "response rate" 
so we should make it clear the table is only Canto/low throughput)

**Comment by kimrutherford** [comment]
> so we should make it clear the table is only Canto/low throughput

Unfortunately, the response rate in the Canto stats is calculated differently to how we decide if a paper is community curated on the main site.

The response rate on the Canto stats page includes all sessions that have a community curator as the most recent curator and ignores the number of community annotations (which could be none).

The web site will only say a paper is community curated if there is at least one annotation by a community curator.

I think the web site algorithm is probably more precise.

>  I see others are attribute to PomBAse when they were really submitted by community
> PMID:23101633

That one is included in the response rate calculation.  PMID:35811551 is too.

**Comment by ValWood** [comment]
OK, so the stats are correct and only action is to get these to appear in the community curated feed with the author rather than "pombase curated" somehow?
We have the info, just not from Canto.
Is that possible easily? Maybe there is already a ticket for this?

**Comment by kimrutherford** [comment]
> OK, so the stats are correct and only action is to get these to appear in the community curated feed with the author rather than "pombase curated" somehow?

I don't think the Canto stats page is correct.  Currently, sessions assigned to a community curator where they did no annotation are counted as community sessions in the response rate calculation.  Here's the issue about the changes on the website site to handle that: https://github.com/pombase/canto/issues/2594

Let's chat about this tomorrow.  It's a bit complicated.

**Comment by ValWood** [comment]
Can we allow range 2-3.3 in this colunm (I think range is allowed in some circumstances)

**Comment by ValWood** [comment]
The display as "community curated" part will be covered by
https://github.com/pombase/pombase-chado/issues/886

The range part is because it is in the wrong column.
