### ISSUE TITLE
placeholder features without coordinates (i.e promoters where exact sequence unknown)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#110]
I didn't really want to go down the "curating features without coordinates" route for genes (as the info isn't so useful unless we know what object it actually refers to,  and most are published).

Howevver, we are likelty o want to use promoters in extensions, when we sometimes don't know the exact sequence of the promoter. We will add these with names like 
SPAC1AX.01-promoter

Is it easy to store these features if we have no coordinates?

Val

Original comment by: ValWood

**Comment by ValWood** [comment]
Well, we have been limping along without this for 4 years so I'll put at low priority so that you don't need to worry about it. Once we have "protein coding" gene pages, we will move on to the feature types that we never got pages for, and at this point we  raise priority.

@mah11  this might benefit from a "shiny new ticket" tying in with other things needed for website? For now I'm adding low_priority tag . We'll need to bring this forward as gene page migration nears completion.

**Comment by mah11** [comment]
> @mah11 this might benefit from a "shiny new ticket" tying in with other things needed for website?

As I understand it, the coordinate-less features still need to be loaded into Chado -- which is what this ticket is about -- and a website ticket would require, and follow, that Chado-loading work. Given that even this ticket is low priority, I think we can wait to even open the website ticket. I also don't know what "other things" you envision "tying in" ...

Anyway, to sum up - this is the outstanding thing for this ticket (when it does bubble up to the top of the heap):
Kim to test loading supporting_files/features_without_coordinates.txt and report any problems or room for improvement to curators.

**Comment by ValWood** [comment]
OK,  summary is good. I wasn't quite sure what the next step was.
This can sit for a while...

**Comment by kimrutherford** [comment]
To fix #598 I added a script that can read systematic IDs and names of features from an arbitrary tab delimited file.

I think we can use that as a basis for reading these placeholder features.  The code needs to be extended to handle connecting the new features to existing features (probably genes) via a relation and to load the extra information like the PMID.  That shouldn't take too long.  I'm planning to have a go at that in the morning while this is fresh in my mind.

**Comment by kimrutherford** [comment]
> supporting_files/features_without_coordinates.txt

Thanks for the files.  I'm nearly done implementing this but I have one question: what is date in the "Date" column the date of?

**Comment by mah11** [comment]
> what is date in the "Date" column the date of?

It's been long enough that I'm not 100% sure, but I think it's the date I added the line to the file, which would also be either the date I curated or approved the paper, or (for papers I didn't handle at all) the date when I noticed a new "can't find feature" warning in the Canto log.

**Comment by kimrutherford** [comment]
> It's been long enough that I'm not 100% sure

I mainly asked to decide how to label it in Chado.  We don't store dates in Chado for other features so I wasn't sure what to do.

We have date attached to annotations.  Those dates have the property type "date" which is possibly not as specific as it should be.

For features we could use the property type "date" too or we could be good citizens and use something more specific.  If no-one has a strong opinion we could go with the type "date" as at least it's the same as for annotations.  Any thoughts?
 
Also: are we going to display these promoters on the gene pages in the future?

**Comment by mah11** [comment]
> We don't store dates in Chado for other features so I wasn't sure what to do.

I don't have any pre-formed expectations about what to do with those dates, let alone a preference. See what @ValWood and @Antonialock say, or just do what's easiest, I guess.

> Also: are we going to display these promoters on the gene pages in the future?

Good question. It seems like promoters would be more useful connected to genes than as stand-alone features (even if Chado stores them as features), analogous to the UTRs except without coordinates.

To be honest, I haven't thought about how to display them yet, since loading them was on the back burner until now. We curators will have a natter and open a website ticket at some point.

**Comment by Antonialock** [comment]
I don't think we need to give their own space to "promoters without coordinates" on the gene pages.

promoters _with_ coordinates on the other hand...

**Comment by ValWood** [comment]
> promoters with coordinates on the other hand...

this is in another ticket for later.....
after browser set up.....

**Comment by kimrutherford** [comment]
> We have date attached to annotations. Those dates have the property type "date" which is possibly not as
> specific as it should be.

For features I'm going to go for calling the property "annotation_date", unless anyone objects.

**Comment by kimrutherford** [comment]
> For features I'm going to go for calling the property "annotation_date", unless anyone objects.

That's done for the next load.

**Comment by kimrutherford** [comment]
I'm closing this.  It's now done.  It only took just over five years.  :-)
