### ISSUE TITLE
new residue=x on RNA methytransferase

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1100]
I put the residue=X on this publication in Canto
https://www.pombase.org/reference/PMID:37403782
and now the original annotation has disappeared from the website

**Comment by kimrutherford** [comment]
Transferred to the Chado tracker.  I'll fix it today.

**Comment by ValWood** [comment]
It might be my fault. This is actually a "methylation guide"
and I can't remember if I asked for the "residue=" on guide activities (although I was able to add it in Canto, which I wasn't for methyltransferases, so I am assuming that isn't the problem)

**Comment by kimrutherford** [comment]
I've fixed the Chado loader to accept modified_residue() in extensions.  The change went in after the load so I'll check on Saturday.

**Comment by kimrutherford** [comment]
> I've fixed the Chado loader to accept modified_residue() in extensions.

That worked but last night's load has a different error:
```
warning in eec0954c4a56c293: modified_residue() not allowed for molecular_function, annotation: SPNCRNA.530.1 <-> snRNA 2'-O-ribose methylation guide activity
warning in eec0954c4a56c293: modified_residue() not allowed for molecular_function, annotation: SPSNORNA.25.1 <-> snRNA 2'-O-ribose methylation guide activity
```

I've fixed the configuration in [load-pombase-chado.yaml](https://github.com/pombase/pombase-legacy/blob/master/load-pombase-chado.yaml) and I'll check again tomorrow.

**Comment by kimrutherford** [comment]
New day, new error.  "modified_residue" isn't isn't a relation in any of the CVs we have configured for extension relations:
 
```
warning in eec0954c4a56c293: can't find relation cvterm for: modified_residue in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
warning in eec0954c4a56c293: can't find relation cvterm for: modified_residue in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
```

I'll add modified_residue to go/extensions/gorel which we get from SVN these days:
```
pombe-embl/mini-ontologies/gene_ex_extension_relations.obo
```

I'll also change the GAF exporter to remove that relation from the extension while exporting for GO.

**Comment by kimrutherford** [comment]
Still not fixed.  This time because I made a typo in the code that checks the modified_residue extension when loading into Chado.  Fixed now and I'll have a look at the logs on Tuesday morning.

**Comment by kimrutherford** [comment]
Finally working!

https://www.pombase.org/reference/PMID:37403782

**Comment by ValWood** [comment]
Thanks!
