### ISSUE TITLE
Should this file be empty

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1102]
I wanted to check that this is OK, because I expected to have accumulated some  error and it's empty:

https://curation.pombase.org/dumps/latest_build/logs/log.2023-08-03-23-59-32.chado_checks.canto_annotations

Also this file is empty:
https://curation.pombase.org/dumps/latest_build/logs/log.2023-08-03-23-59-32.chado_checks.go_annotation_count

**Comment by kimrutherford** [comment]
Both those are checking for serious failures so should always be empty.

canto_annotations checks that there are a reasonable number of annotations from Canto.  This is a last-resort check so we can spot if the Canto annotation loading goes completely wrong.

And go_annotation_count checks that we don't have too many GO annotations, as would happen if the GO filtering failed.

My original plan for the chado checks was that if any failed we would exit the load script and not do a release.  We haven't got to that point yet so the release goes ahead even if a check fails.

**Comment by ValWood** [comment]
OK! thats good, I could,t remember
