### ISSUE TITLE
Add biotype=protein_coding to GFF files

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1106]
Only for coding genes.

**Comment by kimrutherford** [comment]
I implemented this as "so_term_name=..." which one of the suggestions from Sue Rhee.  It seemed clearer that "biotype".  I've added it to all genes including non-coding genes.

It was deployed before the nightly load exported the GFF so the latest files have the new attribute:
https://curation.pombase.org/dumps/latest_build/gff/

Here are the numbers of each type:
```
   7163 lncRNA_gene
      1 ncRNA_gene
   5134 protein_coding_gene
     31 pseudogene
     49 rRNA_gene
     38 sncRNA_gene
     66 snoRNA_gene
      6 snRNA_gene
    196 tRNA_gene
```

**Comment by ValWood** [comment]
Thanks Kim!
