### ISSUE TITLE
use universal modification syntax for histones.

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1108]
This is more problematic than alleles, because at least for alleles we can name universally but have the description standardized. What should we do for modifications though?

Everyone refers to modifications by their methionine removed proition.

For example see this new paper:
<img width="1163" alt="Screenshot 2023-08-26 at 21 03 17" src="https://github.com/pombase/pombase-chado/assets/7359272/1c42d801-a7ca-4fa7-a5b9-d1d6a2b84645">

https://www.pombase.org/gene/SPAC1834.04
but we have  S58

<img width="1095" alt="Screenshot 2023-08-26 at 21 03 10" src="https://github.com/pombase/pombase-chado/assets/7359272/e8a7778f-1899-4006-92c6-bc5ad001deae">

**Comment by ValWood** [comment]
I also wonder if all of the errors are reporting here:
https://curation.pombase.org/dumps/latest_build/logs/log.2023-08-26-21-47-51.chado_checks.modification_on_wrong_residue

because hht1 has K5 reported as both K4 and K5. Whichever system we are using one should be reported as incorrect.

@manulera 
@kimrutherford 

(Apologies for conflating 2 issues but we can discuss next week and split onto the correct trackers)

**Comment by manulera** [comment]
> because hht1 has K5 reported as both K4 and K5

Hi @ValWood, regarding the K4 / K5. This is from the reference that has `PB_REF:0000001`, and therefore was not fixed by kim's script that fed my changes. I am not sure we ruled out where these annotations come from / how to fix them. We should report K5, I think.

**Comment by manulera** [comment]
> This is more problematic than alleles

Not sure what to say. SGD uses the "normal" coordinates (counting the methionine). https://www.yeastgenome.org/locus/S000000214/protein#phosphorylation_strain

I think histone researchers will probably realise that we are counting the methionine, while people that are not working on histones might not notice if we don't, and be confused about it. I think for the export dataset, we should definetely use the normal index. In the website, maybe we can put a warning at the top of the modification section for histone genes?

**Comment by ValWood** [comment]
OK, I agree to use the normal index.

I think a warning at the top of the modification section for histones is a good idea.

The inferred modifications are in the contig files. There are not many (60) and most are GPI anchors or farnesylation sites. Most do not have residues reported. We are slowly moving things out of the contigs into csv files so @kimrutherford  could move this out at some point. In the meantime, I have fixed the problem ones that I am aware of (on two of the histones). Let me know if there are others.

**Comment by ValWood** [comment]
Reopen if there are more for me to fix
