### ISSUE TITLE
Update PDB structures

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1109]

**Comment by kimrutherford** [comment]
I've updated the PDB data file:
```
  pombe-embl/external_data/protein_structure/systematic_id_to_pdbe_mapping.tsv
```

The changes will be visible on Tuesday morning.

There are no new publications with structures.  There are new structures for these genes:

SPBC29B5.03c
SPAC13C5.07
SPAC1F7.02c
SPBPJ4664.04
SPAC1006.03c
SPBC365.03c

**Comment by ValWood** [comment]
Oh good there is a paper here that I mis-triaged and I can turn a gene from colour7->2
