### ISSUE TITLE
list required (gene coordinate change, new genes)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#111]
Hi Kim,

At some point could we get a list of
warning, new gene with PMID:21511999
and a list of "warning, gene coordinate change" with PMID:21511999

...we need to put them in these tables
http://www.pombase.org/status/gene-coordinate-changes

http://www.pombase.org/status/new-and-removed-genes

....or we could wait and just make these lists available  as "canned queries", which is the preferred long term option
I think maybe we'd better update the lists in the meantime.....

Original comment by: ValWood

**Comment by ValWood** [comment]
We can manage this  until  we are through the "changes"

**Comment by ValWood** [comment]
@manulera work addressed this 2012 ticket!
