### ISSUE TITLE
Error reported for diploid, looks OK, can't fix:

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1111]
warning in 089bad866432ef28: description for new allele "ras1+(C215A)" does not match the existing allele with the same name "ras1+(wild type)" (from session a64b97197e845b5b)

warning in 089bad866432ef28: allele_type for new allele "ras1+(amino_acid_mutation)" does not match the existing allele with the same name "ras1+(wild_type)" (from session a64b97197e845b5b)

but this is how the session genotypes look in Canto:
<img width="832" alt="Screenshot 2023-09-13 at 06 55 01" src="https://github.com/pombase/pombase-chado/assets/7359272/5f6dda6e-5872-41ad-88ea-edb9611a1242">

**Comment by kimrutherford** [comment]
Hi Val.

I think this is the session that's causing the warning:
https://curation.pombase.org/pombe/curs/089bad866432ef28/genotype_manage/ro

![image](https://github.com/pombase/pombase-chado/assets/90474/fd952a72-bcbd-4b56-85b3-0255bbd6490f)

![image](https://github.com/pombase/pombase-chado/assets/90474/4adea47b-d057-4668-b23b-76ac54b1bb9c)

**Comment by ValWood** [comment]
fixed
