### ISSUE TITLE
Update the precedence for GO filtering of non-experimental

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1112]
inferred by curator
inferred from sequence orthology
inferred from sequence or structural similarity
inferred from sequence model
traceable author statement
non-traceable author statement
inferred from expression pattern
inferred from electronic annotation
inferred from reviewed computational analysis
inferred from biological aspect of ancestor
inferred from biological aspect of descendant

to

inferred from biological aspect of ancestor
inferred from biological aspect of descendant

inferred by curator
inferred from sequence orthology
inferred from sequence or structural similarity
inferred from sequence model
traceable author statement
non-traceable author statement
inferred from expression pattern
inferred from electronic annotation
inferred from reviewed computational analysis

I wanted to keep PAINT at the bottom so there were fewer to check  during the QC phase. We should have swapped them up ages ago.  I forgot. They are now better than any of the other methods because they often have supporting evidence from multiple species. Most of the problems have been. weeded out now.

**Comment by kimrutherford** [comment]
No problem.  Just to double check, IBA and IBD should be the highest priority and RCA the lowest?  I want to make sure I don't get it backwards.

Should make this change for tonight's load?  Would you like to review the results before it goes live?

**Comment by ValWood** [comment]
That is correct.

I think it should be fine. I could review just to be sure, but since this will only replace existing annotations, even if something goes wrong the annotations shouldn't be worse

**Comment by kimrutherford** [comment]
OK, thanks.  I've checked in the change of priority so it changed on the main site in the morning.
