### ISSUE TITLE
modification log file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1113]
https://curation.pombase.org/dumps/latest_build/logs/log.2023-09-17-21-41-34.modification

I don't  look at this file very often because it always has content, but it rarely has errors.

However, right now it has quite a lot of errors that I missed, eg:

extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 8:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 9:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 10:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 12:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 13:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 14:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 27:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 30:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 32:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 45:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 47:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 55:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 65:
extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
failed to load line 3816:
storing feature_cvterm from SPBC16E9.16c.1 to O-phospho-L-serine [present_during] mitotic M phase - failed to store feature_cvterm: that annotation has already been stored in Chado with properties:  evidence: "experimental evidence", residue: "S713"  from session: UNKNOWN
failed to load line 4825:
storing feature_cvterm from SPAC630.14c.1 to O-phospho-L-serine [present_during] mitotic M phase - failed t

would it be possible not to write out
loading: /var/pomcur/sources/pombe-embl/external_data/modification_files/PMID_22633491_modifications.tsv
loading: /var/pomcur/sources/pombe-embl/external_data/modification_files/PMID_23297348_modifications.tsv
loading: /var/pomcur/sources/pombe-embl/external_data/modification_files/PMID_24763107_modifications.tsv
loading: /var/pomcur/sources/pombe-embl/external_data/modification_files/PMID_25720772_modifications.tsv
etc into the log, so that the file only has content when errors are present?

**Comment by kimrutherford** [comment]
> However right now it has quite a lot of errors which I missed, eg:
> extension contains an unhandled pipe ("|") character: present_during(GO:0000087)|added_by(PomBase:ark1)
> failed to load line 8:

I had a look.  The warnings have been there since June.  Before that the pipes were silently treated to commas in extensions.

Should I go ahead and fix the file?

> would it be possible not to write out

I've made that change for tonight's load.

**Comment by ValWood** [comment]
If you could fix that file that would be great. I'll fix what is left tomorrow.
Thanks

val

**Comment by kimrutherford** [comment]
> If you could fix that file that would be great.

OK, done.

I also fixed this error:

> loading: /var/pomcur/sources/pombe-embl/external_data/modification_files/PMID_25720772_modifications.tsv
> can't find modification term "psimod id" in Chado, skipping line 4

**Comment by kimrutherford** [comment]
I think this is done.  There are still a few warnings in the log file, but they aren't urgent:
  https://curation.pombase.org/dumps/builds/pombase-build-2023-10-23/logs/log.2023-10-23-01-50-30.modification
