### ISSUE TITLE
ingest: structure

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1115]
https://www.pombase.org/reference/PMID:37340985
should have one (might be in the next load?I can't remember when we updated)

**Comment by kimrutherford** [comment]
I looked up the PMID in PDBe and got no results.

> The coordinate of the spPH domain has been deposited in the RCSB PDB with code 8I53.

But then I looked up the structure ID directly in PDB and found that it's not released yet https://www.rcsb.org/structure/8I53

**Comment by ValWood** [comment]
OK, just checking in case some pdb issue with the species. Lets keep open until the next pdb update.

**Comment by kimrutherford** [comment]
> But then I looked up the structure ID directly in PDB and found that it's not released yet https://www.rcsb.org/structure/8I53

It looks like it's released and I haven't done a PDB data update recently, so I'll do that now

**Comment by kimrutherford** [comment]
There are three new entries:
  - https://www.ebi.ac.uk/pdbe/entry/pdb/8i53
     - PMID:37340985
  - https://www.ebi.ac.uk/pdbe/entry/pdb/8px5
     - PMID:37828292 but I can't see any mention of pombe in the text of the paper?
  - https://www.ebi.ac.uk/pdbe/entry/pdb/8j0h
     - no publication?

They should be on the main site on Saturday.

**Comment by kimrutherford** [comment]
> - https://www.ebi.ac.uk/pdbe/entry/pdb/8i53
>     - PMID:37340985

That one is there now: https://www.pombase.org/reference/PMID:37340985

> - https://www.ebi.ac.uk/pdbe/entry/pdb/8px5
>     - PMID:37828292 but I can't see any mention of pombe in the text of the paper?

That should appear once the publication goes through Canto.

> - https://www.ebi.ac.uk/pdbe/entry/pdb/8j0h
>     - no publication?

That shows up on the gene page: https://www.pombase.org/gene/SPAC4H3.06

**Comment by ValWood** [comment]
> PMID:37828292 but I can't see any mention of pombe in the text of the paper?

This is probably because this is to demonstrate a method. I guess they weren't interested in specific species

**Comment by kimrutherford** [comment]
> This is probably because this is to demonstrate a method. I guess they weren't interested in specific species

I also couldn't see a pombe systematic ID in the paper so I wondered how PDBe matched the structure to a pombe gene.

**Comment by ValWood** [comment]
Is there no UniProt ID (that woud be more ikey) If not perhaps they do a sequence match in this situation?

**Comment by kimrutherford** [comment]
> If not perhaps they do a sequence match in this situation?

Maybe!  Whatever they're doing, I'm impressed by how thorough they are.
