### ISSUE TITLE
"No features available for thc1"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1117]
This gene has no protein features: https://www.pombase.org/gene/SPCC18B5.09c

I'll check that it isn't a bug.

**Comment by kimrutherford** [comment]
> I'll check that it isn't a bug.

InterPro knows nothing about this protein so I guess it's not a bug:
https://www.ebi.ac.uk/interpro/protein/reviewed/Q9USL2/

**Comment by ValWood** [comment]
I reported to Interpro
