### ISSUE TITLE
Additional filter for log file check

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1119]
https://curation.pombase.org/dumps/latest_build/logs/log.2023-10-19-20-29-52.chado_checks.AlleleNotStartingWithGeneName

Running: PomBase::Check::AlleleNotStartingWithGeneName
failed: Check that all allele names start with a gene name or gene synonym

You can exclude any alleles from this file which are tyre "fusion or chimera"
because these will often begin with the name of the fused gene

**Comment by kimrutherford** [comment]
Done for Saturday night's load.
