### ISSUE TITLE
query resistance

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1121]
genes/annotations
genes annotated with "increased resistance to chemical" (FYPO:0002682) [single locus haploid genotypes]

Sepember vs  after 04 Oct (not sure that this is the precise date)

**Comment by kimrutherford** [comment]
Oct 1st:
  - 26226 single locus haploid genotypes
  - 3299 "increased resistance to chemical" annotations for those genotypes

Yesterday:
  - 29772 single locus haploid genotypes
  - 29483 "increased resistance to chemical" annotations for those genotypes

**Comment by ValWood** [comment]
so how many genes on Oct 1st?

**Comment by kimrutherford** [comment]
Oct 1st: 863 

Today: 3624

**Comment by ValWood** [comment]
OK thanks increased resistance annotations were more common than I thought. I will ask Jurg about the conflicts
