### ISSUE TITLE
Include new genotype interactions in stats and graphs

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1124]
The graphs here don't include include the new genotype to genotype interaction annotations (I think, but I'll check):
https://curation.pombase.org/pombe/stats/annotation

Need to fix "Cumulative annotations by type and year" and "Annotations/genes for low throughput publication in 5-year intervals"

**Comment by ValWood** [comment]
Might be worth doing this while you are aligning the graphs

**Comment by kimrutherford** [comment]
> Might be worth doing this while you are aligning the graphs

OK, will do.

**Comment by kimrutherford** [comment]
As a first step, I've fixed the code to include the annotation date when storing genotype-genotype interactions in Chado.
It was missing.  I'll be able to include the genotype interactions in the stats after the next nightly load.

**Comment by kimrutherford** [comment]
> As a first step, I've fixed the code to include the annotation date when storing genotype-genotype interactions in Chado.  It was missing.

There were a bunch of annotation properties that weren't being stored for genotype-genotype interactions (like the curator, the session and the community curated flag).

I've added those for tonight's load.

**Comment by kimrutherford** [comment]
This is fixed for Friday night's load.
