### ISSUE TITLE
Protein sequence feature viewer: Find external active site sources

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1126]
Pdb have them but we should also be able to get active site residues for proteins without structures

I will check  with Uniprot and Pfam

**Comment by ValWood** [comment]
example krp1
https://www.uniprot.org/uniprotkb/Q09175/entry#ptm_processing

**Comment by kimrutherford** [comment]
> example krp1
> https://www.uniprot.org/uniprotkb/Q09175/entry#ptm_processing

There's a download link in that section so we can definitely get that data.

**Comment by ValWood** [comment]
This is split into separate tickets
