### ISSUE TITLE
log fie needs more info

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1129]
https://curation.pombase.org/dumps/latest_build/logs/log.2023-11-28-00-12-18.legacy_modifications_from_contigs

gives
column value for date missing at line 29
column value for date missing at line 193
column value for date missing at line 211
column value for date missing at line 230
column value for date missing at line 276
column value for date missing at line 325
column value for date missing at line 404
column value for date missing at line 428
column value for date missing at line 489
column value for date missing at line 566
column value for date missing at line 657
column value for date missing at line 662
column value for date missing at line 674
column value for date missing at line 763
column value for date missing at line 788
column value for date missing at line 793
column value for date missing at line 816
column value for date missing at line 840
column value for date missing at line 889
column value for date missing at line 927
column value for date missing at line 992
column value for date missing at line 994
column value for date missing at line 1023
column value for date missing at line 1079

**Comment by kimrutherford** [comment]
What other information should be added?  Should we print the line contents as well as the line number?

**Comment by ValWood** [comment]
ignorte me, I forgot there was a legacy fil, I though this was from the datasts
