### ISSUE TITLE
fix, two alleles with the same name

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1132]
I found this in the comments log file, but I don't thin it appears in the logs, check?

alp7-5A(S50A,S51A,T100A,T116A,T131A)	warning: same name as alp7-5A(K341,Y344,R346,K347,Y348)	PMID:29021344
alp7-5A(K341,Y344,R346,K347,Y348)	warning: same name as alp7-5A(S50A, S51A, T100A, T116A, T131A)	PMID:24790093

**Comment by ValWood** [comment]
I can't see this in the logs, it isn't in the expected  file:
https://curation.pombase.org/dumps/latest_build/logs/log.2024-01-01-21-44-33.chado_checks.duplicated_allele_names

I won't fix it until the logs are reporting the error (no hurry)

**Comment by kimrutherford** [comment]
> alp7-5A(S50A,S51A,T100A,T116A,T131A) warning: same name as alp7-5A(K341,Y344,R346,K347,Y348) PMID:29021344
> alp7-5A(K341,Y344,R346,K347,Y348) warning: same name as alp7-5A(S50A, S51A, T100A, T116A, T131A) PMID:24790093

Hi Val.  I can't see that message in the logs now.

The allele comments load log has this message which might be related:

> can't find feature with name "alp7-5A(K341,Y344,R346,K347,Y348)" at line 81 - skipping

https://curation.pombase.org/dumps/builds/pombase-build-2024-01-02/logs/log.2024-01-01-21-44-33.allele-comments-from-supporting-data

**Comment by ValWood** [comment]
I can't figure out why this wouldn't cause an error to appear in 
https://curation.pombase.org/dumps/latest_build/logs/log.2024-01-01-21-44-33.chado_checks.duplicated_allele_names
though.
It's a duplicated allele name?

**Comment by kimrutherford** [comment]
> It's a duplicated allele name?

They have different names.  One is "alp7-5A(S50A,S51A,T100A,T116A,T131A)" and the other is "alp7-5A(K341,Y344,R346,K347,Y348)" in the allele_comments.txt file.  The first column is the allele name, not the allele name + description.

http://dev.pombase.kmr.nz/allele/SPAC890.02c:allele-24
http://dev.pombase.kmr.nz/allele/SPAC890.02c:allele-6

**Comment by ValWood** [comment]
Val to fix
