### ISSUE TITLE
other species in "with field" for binding annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1135]
cut8 has a S. cerevisiae ID in the with field.  I think this is imported. For GO (unless a host pathogen interaction) we should not have these ( I think ti must be imported)

<img width="540" alt="Screenshot 2024-01-29 at 14 06 12" src="https://github.com/pombase/pombase-chado/assets/7359272/7aac7e90-1984-4bc3-b636-e0dc26739227">

**Comment by kimrutherford** [comment]
I had a quick look and found 9 genes with non-pombe genes in the *with* field of a protein binding annotation:

https://www.pombase.org/results/from/id/f381863d-181c-4a65-8128-c1d29130d12d

All are from IntAct.

Is this a GO problem or do with need to filter these out of PomBase?

**Comment by ValWood** [comment]
Filter from PomBase. They should eventually get picked up via GO checks,
v

**Comment by kimrutherford** [comment]
That's done for tonight's load.  I'll close the issue once I've checked the result.
