### ISSUE TITLE
curation migration FYPO term

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1136]
Could you migrate the annotation from

increased subtelomere-derived RNA level (FYPO:0004574)

to
increased subtelomeric heterochromatin RNA level

(I will need to move a few annotations back to 
increased subtelomere-derived RNA level (FYPO:0004574)
and tweak the label)

**Comment by kimrutherford** [comment]
Are these Canto annotations?

**Comment by ValWood** [comment]
They should be.....but they will be in multiple sessions so maybe not that easy?

**Comment by kimrutherford** [comment]
I've written a small script to do this.  I'll run it on Saturday night.

**Comment by kimrutherford** [comment]
That's done now.  The changes will be visible on pombase.org on Sunday morning.
