### ISSUE TITLE
annotations with column 17 in legacy GO file don't appear to parse

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1138]
I. have added a few annotations to the legacy GO file with a modified form (column 17): 

PomBase	SPBC28F2.12			GO:0030674	PMID:19328067	TAS		F	XXX		protein	taxon:4896	20240204	PomBase	has_input(PomBase:SPCC330.10),part_of(GO:0006370)	PR:000044737	

PomBase	SPBC28F2.12			GO:0030674	PMID:19328067	TAS		F	XXX		protein	taxon:4896	20240204	PomBase	has_input(PomBase:SPBC32H8.10),part_of(GO:0006368)	PR:000044737	

PomBase	SPBC28F2.12			GO:0030674	PMID:18457900	TAS		X	XXX		protein	taxon:4896	20240204	PomBase	has_input(PomBase:SPAC4G9.04c)	PR:000044738

I don't think these parse (they didn't appear on the gene page, but there is no error in the logs)

**Comment by kimrutherford** [comment]
I think they were added after the load started at 9pm.  The SVN log says:
```
r9476 | vw253 | 2024-02-05 23:23:24 +0000 (Mon, 05 Feb 2024) | 1 line
```

**Comment by ValWood** [comment]
Ah yes, I did it early and didn't commit until around 11pm
