### ISSUE TITLE
GO evidence code with incorrect reference

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1140]
Could you change any GO annotation with 
ISM which has GO_REF:0000024 to GO_REF:0000050
in 
legacy_go_annotations_from_contigs.gaf.tsv

**Comment by ValWood** [comment]
Ansy ISS with PANTHER:***** to  ISM/GO_REF:0000050

**Comment by kimrutherford** [comment]
> Could you change any GO annotation with
> ISM which has GO_REF:0000024 to GO_REF:0000050

I've done that with:

```
perl -pne 's/GO_REF:0000024\tISM/GO_REF:0000050\tISM/' legacy_go_annotations_from_contigs.gaf.tsv > legacy_go_annotations_from_contigs.gaf.tsv.new
mv legacy_go_annotations_from_contigs.gaf.tsv.new legacy_go_annotations_from_contigs.gaf.tsv
```

> Ansy ISS with PANTHER:***** to ISM/GO_REF:0000050

There were only two of those, which I changed in emacs.
