### ISSUE TITLE
global fix

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1147]
Any allele that has name, or synonym
rpb1-CTD-P3A(r2-r29-2) 
should have the description
CTD-P6A(r2-r29-2)

Is it possible to check and fix these?

**Comment by kimrutherford** [comment]
I've changed the ones in Canto and will check after the load.

**Comment by kimrutherford** [comment]
Sorry, I left the closing bracket off the new descriptions when I made the change:
```
CTD-P6A(r2-r29-2
```

I've just fixed that and I'll check again on Wednesday morning.

**Comment by kimrutherford** [comment]
> I've just fixed that and I'll check again on Wednesday morning.

I got it right this time.
