### ISSUE TITLE
legacy annotations not visible in PomBase

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1150]
I don't see these annotations (from legacy file)

PomBase	SPCC1753.01c	ssb2	contributes_to	GO:0003697	PMID:8702843	IDA		F	XXXX	rpa2|SPCC584.06c	protein	taxon:4896	20050628	PomBase		
PomBase	SPCC23B6.05c	ssb3	contributes_to	GO:0003697	PMID:8702843	IDA		F	XXXX	rpa3	protein	taxon:4896	20050510	PomBase

**Comment by kimrutherford** [comment]
I see them here: https://www.pombase.org/reference/PMID:8702843

**Comment by ValWood** [comment]
OK! sorry about that, I didn't realise they were binding annotations
