### ISSUE TITLE
remove a legacy data remapping

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1151]
somewhere in the code, there is some remapping of legacy data.

One of these remappings maps
GO:0006269 to 
GO:1902981 Or  GO:1903458

we need to remove this mapping so they remain as GO:0006269 

Also it would be useful to see a list of these mappings, or a link to them so that I can add to the docs (it took me ages to remember that this happens!)

**Comment by kimrutherford** [comment]
Hi Val.

The mappings are in this file:
`pombe-embl/chado_load_mappings/GO_mapping_to_specific_terms.txt`

I've removed this line:
```
GO:0006269      GO:1902981      synthesis of RNA primer involved in mitotic DNA replication
```

**Comment by kimrutherford** [comment]
I think this is done.
