### ISSUE TITLE
version of GAF for annotation checking

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1152]
could you make a version of the GAF file  for me which also includes 
1) the gene product description
2) the GO term label
it will make it much easier  to review the IEAs
(I don't need every column, but I can just cut out the ones I need)

**Comment by kimrutherford** [comment]
How's this: https://desktop.kmr.nz/local/pombase_style_gaf.tsv.gz

**Comment by ValWood** [comment]
This is good. I don't think this version includes the TreeGrafter IEA though

**Comment by kimrutherford** [comment]
Sorry, I made that from yesterday's load.

Try this one instead: https://desktop.kmr.nz/local/pombase_style_gaf-2024-03-12.tsv.gz

**Comment by kimrutherford** [comment]
Hi @ValWood 

Was this a one-off or should we make an expanded GAF-like file each nightly load?

**Comment by ValWood** [comment]
Yuou could add it for a while as it makes it easier for me to review IEAs  for the manuscript (also tell me the permanent location, it could be a log file).

Eventually we can get rid of it.

**Comment by kimrutherford** [comment]
> also tell me the permanent location, it could be a log file

Here it is:
https://curation.pombase.org/dumps/latest_build/misc/extended_pombase_style_gaf.tsv

It's updated nightly.  I've found it useful too.
