### ISSUE TITLE
some WT alleles have systemtic IDs when genes are named 

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1153]
I'm wondering why these don't get replaced with 
msy1+ automatically ...should they?

from 
https://curation.pombase.org/dumps/latest_build/logs/log.2024-03-17-22-17-05.chado_checks.AlleleNotStartingWithGeneName

SPCC1183.11+	msy1	SPCC1183.11	8ffe6ded62ad4ebc
SPAC2C4.17c+	msy2	SPAC2C4.17c	8ffe6ded62ad4ebc
SPCC31H12.03c+	mlo1	SPCC31H12.03c	06b4ab309bde03c9

**Comment by kimrutherford** [comment]
I'm surprised that this case wasn't already covered.  I've fixed it for tomorrow morning.

**Comment by kimrutherford** [comment]
Fixed!
