### ISSUE TITLE
Switch some RNA allele "other" type to nucleotide_deletion

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1155]
From @ValWood:

-----------------------

pombe-embl/external_data/phaf_files/chado_load/htp_phafs

PMID_34984977_phaf.tsv

switch other in these

SPNCRNA.103(9-528),SPNCRNA.103:allele-2,II:complement(339484..340003),{}
SPNCRNA.1303(93-419),SPNCRNA.1303:allele-1,II:63695..64021,{}
SPNCRNA.1501(1098-2471),SPNCRNA.1501:allele-1,II:2301759..2303132,{}
SPNCRNA.1559(365-735),SPNCRNA.1559:allele-2,II:2886001..2886371,{}
SPNCRNA.1624(15-1422),SPNCRNA.1624:allele-3,II:3620593..3622000,{}
SPNCRNA.1651((-9)-95),SPNCRNA.1651:allele-1,II:3962690..3962794,{}
SPNCRNA.388(75-1575),SPNCRNA.388:allele-1,II:2115667..2117167,{}
SPNCRNA.627(606-995),SPNCRNA.627:allele-2,I:238509..238898,{}
SPNCRNA.628(732-1573),SPNCRNA.628:allele-3,I:239730..240571,{}
SPNCRNA.808((-7)-150),SPNCRNA.808:allele-3,I:complement(2265688..2265845),{}
SPNCRNA.941(145-922),SPNCRNA.941:allele-2,I:3846893..3847670,{}
SPNCRNA.996((-74)-487),SPNCRNA.996:allele-2,I:4531070..4531631,{}

to nucleotide_deletion

I don't trust myself to do it

**Comment by kimrutherford** [comment]
> to nucleotide_deletion

Just to check, do you mean "partial_nucleotide_deletion"?

**Comment by ValWood** [comment]
Oops, yes!

**Comment by kimrutherford** [comment]
OK, that's done for tonight's load.
