### ISSUE TITLE
PHAF files change gene name to "gene symbol"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1157]
For consistency across the site, from the changes for
https://academic.oup.com/genetics/article/225/3/iyad143/7283026?login=false

we should probably call gene name "gene symbol" in out PHAF files too

https://github.com/monarch-initiative/monarch-app/issues/661#issuecomment-2023337110

This would be consistent with HGNC and Alliance

**Comment by kimrutherford** [comment]
A bit related to:
 - pombase/website#2061

**Comment by kimrutherford** [comment]
How urgent is this?

**Comment by ValWood** [comment]
Not super urgent, just fit it in when you can. It's  more to be consistent for users but it isn't a blocker.

**Comment by kimrutherford** [comment]
Fixed for Monday night's load.
