### ISSUE TITLE
log file alleles not beginning with a gene name

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1159]
I thought that this file only provided  entries which did not match a gene name OR a synonym?

but I see that
sam3	rad24	SPAC8E11.02c	aee38813cc53380f
is reported even though sam3 is a synonym?

Can this restriction be added?

**Comment by kimrutherford** [comment]
Hi Val.  The code does check for alleles starting with synonyms but currently there has to be something after the gene name or synonym.  If the allele name was "sam3-a1" it wouldn't appear in the logs.

Should I change the code?

**Comment by kimrutherford** [comment]
Should we keep this open?

**Comment by ValWood** [comment]
no can close.
this file is almost cleaned up!

https://curation.pombase.org/dumps/latest_build/logs/log.2024-04-21-21-08-46.chado_checks.AlleleNotStartingWithGeneName
