### ISSUE TITLE
Find all synonym fields with spaces

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1161]
List all synonym fields with spaces and session IDs

**Comment by kimrutherford** [comment]
[allele_synonyms_with_spaces.csv](https://github.com/pombase/pombase-chado/files/14891829/allele_synonyms_with_spaces.csv)


|pmid            |session           |allele\_name        |synonym                                                |
|----------------|------------------|--------------------|-------------------------------------------------------|
|PB\_REF:0000004 |                  |spt5-delta-CTD    |1-835 deltaCTD                                        |
|PMID:10373582   |0ffa8093b9b4d8e5  |rad32-1            |rad32-D135N mre11-D135N                              |
|PMID:10574765   |88d2e1acdc9993bc  |ral3-cor-C-GFP   |ral3-cor-C-GFP fusion                               |
|PMID:10930468   |977c41e138dc2e0d  |mid1-delta1-506   |mid1 1-506                                            |
|PMID:12456004   |a09d826a70b1a2d4  |git7-93            |duplication of codons 345 to 363                       |
|PMID:1314171    |eb4340d44f575950  |nhe1delta           |sod2delta neh1delta                                    |
|PMID:14008      |cc0a2203f689cfc8  |dap1-              |dap 1                                                  |
|PMID:14008      |cc0a2203f689cfc8  |pur1-              |pur 1                                                  |
|PMID:15164362   |54a26a25997d999a  |ntp1-CRE-like-promoter|ntp1-CRE-like promoter mutant                        |
|PMID:15448137   |65ee22c229c3e125  |cgs2-p.CRE-mut   |cgs2-CRE promoter binding site mutant                 |
|PMID:15791259   |d5580f5ec3f29d85  |slp1(1-453)      |slp1 1-453                                            |
|PMID:15791259   |d5580f5ec3f29d85  |slp1(166-488)    |slp1 166-488                                          |
|PMID:16325501   |bc9efc288e644f66  |pmo25-2            |T551TG,T616G(exon sequence)                          |
|PMID:16444015   |affec7759847d81d  |his3-              |his3 mutant                                            |
|PMID:16775007   |574df5dbdb6edf7f  |sid4-ppc89         |Sid4-Ppc89 fusion                                     |
|PMID:17952063   |223cbaaac1c064d0  |pyp2deltaUTRs       |pyp2-no UTRs                                          |
|PMID:18157149   |0205e2ea9f154b73  |ter1-B             |ter1-Mutant B                                         |
|PMID:18223116   |3dc265797d97f877  |fep1-p.CCAAT      |fep1 CCAAT promoter mutant                             |
|PMID:18562692   |c9f65982114faaaa  |act1-R183A,D184A   |act1-LatA resistant                                   |
|PMID:18799626   |d31bdd99cf204c6f  |klp5N/klp6C         |Klp5N/klp6C chimera                                    |
|PMID:18799626   |d31bdd99cf204c6f  |klp6N/klp5C         |Klp6N/Klp5C chimera                                    |
|PMID:19371376   |7a0e423521cbb7b4  |ssp1-VEV431AAA,EV437AA|ssp1-stretch Ala                                      |
|PMID:19371376   |7a0e423521cbb7b4  |ssp1delta431-438   |ssp1-stretch deletion                                 |
|PMID:19487461   |6c335a4e1d1a262d  |cdc13+             |cdc13 switch-off                                      |
|PMID:19915076   |feedc5a07a1dde86  |abc3-M1            |GATA promoter mutant                                   |
|PMID:19915076   |feedc5a07a1dde86  |abc3-M1,M2         |GATA promoter mutant                                   |
|PMID:19915076   |feedc5a07a1dde86  |abc3-M2            |GATA promoter mutant                                   |
|PMID:2046669    |803cfb382ebb41c6  |byr2delta(389-606)|byr2-catalytic domain deleted                         |
|PMID:22150589   |10205a1be0d30851  |pdp1-deltaPWWP     |pdp1-delta-PWWP domain                               |
|PMID:22281223   |4d4822dbe566aaac  |bub1-KD            |bub1-kinase dead                                      |
|PMID:22281223   |4d4822dbe566aaac  |mph1-kd            |mph1-kinase dead                                      |
|PMID:22438582   |5524d2f4237ade3e  |cut12-hrs1         |cut12-hrs1 fusion                                     |
|PMID:22438582   |5524d2f4237ade3e  |pcp1-hrs1          |pcp-hrs1 fusion                                       |
|PMID:22438582   |5524d2f4237ade3e  |plo1-sid4C         |plo1-sid4C fusion                                     |
|PMID:22809626   |cf4899040d72592d  |dma1-delta-RF     |dma1-delta-RF domain                                 |
|PMID:22809626   |cf4899040d72592d  |dma1delta-FHA      |dma1delta-FHA domain                                  |
|PMID:22952839   |8a099f2c6d1a0af1  |swi1-DDT-h2       |swi1-DDT h2                                           |
|PMID:22952839   |8a099f2c6d1a0af1  |swi1-DDT-h3       |swi1-DDT h3                                           |
|PMID:23936074   |c6ced0325cbf00af  |cnp1+              |nmt41-CENP-A-Cnp1 nmt41-CENPA(cnp1+)            |
|PMID:23936074   |c6ced0325cbf00af  |cnp1+              |nmt81-CENP-A-Cnp1 nmt81-CENPA(cnp1+)            |
|PMID:24554432   |ea5eb1c311e9f19d  |cdr2-tea4N         |tea4N-cdr2 fusion                                     |
|PMID:24554432   |ea5eb1c311e9f19d  |ppc89-GFP-tea4    |tea4-pcp89 fusion                                     |
|PMID:24831008   |bf037075feb20f28  |loz1+              |loz1+  zhf1 promoter                                  |
|PMID:25103238   |7f17aec8a060844d  |cut11-2            |cut11-3 cut11-4                                      |
|PMID:25203555   |ad3cea5e630841a3  |pxd1delta108-226   |pxd1deltaM pxd1-deltaM                                |
|PMID:25240800   |f2202f3e99350d80  |dis3-endo-        |dis3 endo-                                            |
|PMID:25240800   |f2202f3e99350d80  |dis3-endo-exo-   |dis3 endo- exo-                                      |
|PMID:25240800   |f2202f3e99350d80  |dis3-exo-         |dis3 exo-                                             |
|PMID:25240800   |f2202f3e99350d80  |rrp41-co           |rrp41 channel-occluded                                |
|PMID:2537310    |dfcd11b5fda97a5f  |top1-              |top1 mutant                                            |
|PMID:2537310    |dfcd11b5fda97a5f  |top2-              |top2 mutant                                            |
|PMID:25724335   |3ae02f9ef40a096c  |aco2(1-811)      |aco2-aconitase domain only                            |
|PMID:25724335   |3ae02f9ef40a096c  |aco2(807-902)    |aco2-ribosomal-domain only                           |
|PMID:25724335   |3ae02f9ef40a096c  |aco2-RDdeltaNLS    |aco2-MTS+ribosomal domain                            |
|PMID:25733668   |d17a6f8397b4b058  |shu1-M1-GATA-box-mutant|shu1-M1 GATA box mutant                               |
|PMID:26137436   |8b8d3cc2e5f5c371  |nup189(uncleavable)|nup98-nup96 (uncleavable)                           |
|PMID:26137436   |8b8d3cc2e5f5c371  |nup189(unspliced) |nup98-nup96 (unspliced)                             |
|PMID:26137436   |8b8d3cc2e5f5c371  |nup189(unspliced-uncleavable)|nup98-nup96 (unspliced and uncleavable)             |
|PMID:26527280   |f8b9e68a8b938c8d  |cut2+              |cut2-GFP OE                                           |
|PMID:26696398   |393d0a5aae35d3ac  |his7-              |his7 mutant                                            |
|PMID:27655872   |1edc814df6ff1176  |sre2-MS+G772L,N773L,Y774L|sre2-MS+ G772L,N773L,Y775L                           |
|PMID:27811944   |3cb710700bc0a9b7  |sre1-ERG           |sre1 ERG                                               |
|PMID:27811944   |3cb710700bc0a9b7  |sre1-WY            |sre1 WY                                                |
|PMID:28366743   |cb1516626fc1f680  |slp1+              |slp1+(cohesin promoter)                             |
|PMID:28552615   |205df3a82b504d79  |rrp2deltaRING       |rrp2-RING deletion                                    |
|PMID:28572514   |bc974ef58d58c8aa  |sod1-H64A          |sod1 H64A                                              |
|PMID:28821619   |bea1c1e13005750d  |cdc48-E319K        |ntG1029A cdc48-8                                      |
|PMID:2908246    |9e29d45d34f5263a  |cdc13-delta785-1599nt|cdc13 disruption                                       |
|PMID:29083304   |54b4f3fa56c4718d  |rps23-deltaN(1-46)|rps23-deltaN-terminal extension domain               |
|PMID:29083304   |54b4f3fa56c4718d  |rps23deltaN(1-23)|rps23-N-terminal deletion                            |
|PMID:29352077   |865ebc50ec806a07  |cdc48-353          |cdc48-G338D cdc48-G332D                              |
|PMID:29735656   |16ad711046a3f839  |cut2-364           |cut2-R267->stop cut2-R262*                        |
|PMID:29813053   |6788fbad2542709a  |cdc15-gc1          |cdc15-GFP cdc15-hypomorph                            |
|PMID:30640914   |6e5ece46806fb848  |rec14-cdk-site1,2 |rec14-cdk1 cdk2                                       |
|PMID:30640914   |6e5ece46806fb848  |rec7-cdk-site1,2  |rec7-cdk1 cdk2                                        |
|PMID:30759079   |23ea57b8910e06c0  |cdk9-T212A         |cdk9 T loop                                            |
|PMID:31257143   |0cfe17c3c16e2b0c  |TetR-bub1          |TetR-bub1-WT fusion                                  |
|PMID:31257143   |0cfe17c3c16e2b0c  |TetR-bub1-CD1     |TetR-bub1-CD1 fusion                                 |
|PMID:31257143   |0cfe17c3c16e2b0c  |TetR-bub1-N700delta|TetR bub1deltakinase fusion                            |
|PMID:31257143   |0cfe17c3c16e2b0c  |TetR-bub1-N700delta|TetR-bub1-N700delta fusion                           |
|PMID:31257143   |0cfe17c3c16e2b0c  |TetR-bub1-TPR     |TetR-bub1-TPR fusion                                 |
|PMID:31257143   |0cfe17c3c16e2b0c  |TetR-bub1N         |TetR-bub1-N terminus fusion                          |
|PMID:31257143   |0cfe17c3c16e2b0c  |TetR-mps1          |TetR-mps1-WT fusion                                  |
|PMID:31941401   |cd18b7b226e58591  |atg38-F178A,V181A  |atg38-[AIM mut]                                     |
|PMID:31941401   |cd18b7b226e58591  |atg8-P52A,R67A     |atg8[AB mut]                                         |
|PMID:32319721   |e630ab034081e15c  |pyk1-T343A         |pyk1-high activity allele                             |
|PMID:32361273   |9b6d37d028f7da71  |rum1-BM1AA         |rum1 BM1 AA                                            |
|PMID:32892625   |3232c9219ab0f2d2  |ain1-L2-R5A       |ain1 L2-R5A                                           |
|PMID:32892625   |3232c9219ab0f2d2  |ain1-L2-R5E       |ain1 L2-R5E                                           |
|PMID:33176152   |96b76559a6d410c0  |hsf1+              |purg1-hsf1 OFF                                        |
|PMID:33670267   |4ca3e303dba088f4  |hrp3-deltaSANT     |Delta SANT domain                                      |
|PMID:33670267   |4ca3e303dba088f4  |hrp3-deltaSLIDE    |Delta SLIDE domain                                     |
|PMID:33670267   |4ca3e303dba088f4  |hrp3-deltachromo   |Delta CHROMO domain                                    |
|PMID:33670267   |4ca3e303dba088f4  |hrp3-deltacoupling_region|Delta COUPLING region                                  |
|PMID:34086083   |ebc037f099adf95b  |rst2-C2H2delta     |rst2 (C2H2delta)                                     |
|PMID:34389684   |67f8ea3e5c1c1bfc  |rpb1-CTD-P3A(r2-r29)|rpb1-P3.P3A rpb1-CTD-P3.P3A rpb1-P3-P3A(1-29)|
|PMID:34967420   |af39cc71da933c2d  |thi20-G271D        |SPBP8B7.17c Gly271Asp                                 |
|PMID:35012333   |4228fd893e7a1a88  |gde1-E846A,D848A   |gde1-(met1)E845A,D847A gde1-(met1)E845A-D847A   |
|PMID:35012333   |4228fd893e7a1a88  |gde1-H811A,R812A   |gde1-(met1)H810A,R811A gde1-(met1)H810A-R811A   |
|PMID:35012333   |4228fd893e7a1a88  |gde1-Y22F,K26A,N140A|gde1-(met1)Y21F,K25A,N139A gde1-(met1)Y21F-K25A-N139A|
|PMID:35012333   |4228fd893e7a1a88  |rpb1-CTD-S5A(r2-r29)|rpb1-S5-S5A(1-29) rpb1-CTD-S5A(r2-r29-2)    |
|PMID:36361590   |f45b7c9c20201a38  |gpl1(C)259-534   |gpl1(C): 259â534                                     |
|PMID:36361590   |f45b7c9c20201a38  |gpl1(M)111-259   |gpl1(M): 111â259                                     |
|PMID:36361590   |f45b7c9c20201a38  |gpl1(N)1-110     |gpl1(N): 1-110                                      |
|PMID:37788281   |aee38813cc53380f  |sam2                |pka1 C358Y                                             |
|PMID:7791776    |ef2da839886aa260  |fus1-deltaTR1      |fus1-TR1 deleted                                      |
|PMID:7791776    |ef2da839886aa260  |fus1-deltaTR2      |fus1-TR2 deleted                                      |
|PMID:9003326    |621ee5f0491cf6af  |mat2-Pc-          |mat1-PC JM161                                         |
|PMID:9321395    |37af2321f43c3188  |wis4deltaN1-958,K1066R|wis4-deltaN terminus,K1066R                           |
|PMID:9514947    |67fc6a2ee3c6c565  |byr2-delta(88-151)|disrupted RBD domain                                   |

**Comment by ValWood** [comment]
OK I will fix
PMID:35012333	4228fd893e7a1a88	rpb1-CTD-S5A(r2-r29)	rpb1-S5-S5A(1-29) rpb1-CTD-S5A(r2-r29-2)
PMID:35012333	4228fd893e7a1a88	gde1-E846A,D848A	gde1-(met1)E845A,D847A gde1-(met1)E845A-D847A
PMID:35012333	4228fd893e7a1a88	gde1-H811A,R812A	gde1-(met1)H810A,R811A gde1-(met1)H810A-R811A
PMID:35012333	4228fd893e7a1a88	gde1-Y22F,K26A,N140A	gde1-(met1)Y21F,K25A,N139A gde1-(met1)Y21F-K25A-N139A
PMID:34389684	67f8ea3e5c1c1bfc	rpb1-CTD-P3A(r2-r29)	rpb1-P3.P3A rpb1-CTD-P3.P3A rpb1-P3-P3A(1-29)
PMID:23936074	c6ced0325cbf00af	cnp1+	nmt41-CENP-A-Cnp1 nmt41-CENPA(cnp1+)
PMID:23936074	c6ced0325cbf00af	cnp1+	nmt81-CENP-A-Cnp1 nmt81-CENPA(cnp1+)
PMID:10373582	0ffa8093b9b4d8e5	rad32-1	rad32-D135N mre11-D135N
PMID:1314171	eb4340d44f575950	nhe1delta	sod2delta neh1delta

that isn't too bad!

Also move
PMID:12456004	a09d826a70b1a2d4	git7-93	duplication of codons 345 to 363

to allele comment

**Comment by ValWood** [comment]
OK, I think I fixed the problems
