### ISSUE TITLE
Remove code for reading exogenous_promoter from Canto JSON

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1163]
See: pombase/canto#2823 and pombase/website#2161

We also need to remove the code that associates promoter genes with the publication to avoid extra publications in the Literature section.

Then test that we have 239 values of promoter_gene for feature_relationshipprop:

```sql
select * from feature_relationshipprop
   where type_id in (select cvterm_id from cvterm where name = 'promoter_gene');
```

**Comment by kimrutherford** [comment]
> Remove code for reading exogenous_promoter from Canto JSON

This is done but I won't push the code changes until I've applied the Canto changes at the weekend.

**Comment by kimrutherford** [comment]
All done.

**Comment by ValWood** [comment]
Thanks, this has been another long project! .....it is much  better for phenotype  integration
