### ISSUE TITLE
Fix weird feature_cvtermprop source_file from GOA loading

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1164]
Value is "pipe:[250445082]"

**Comment by ValWood** [comment]
does this need reporting to GOA?

**Comment by kimrutherford** [comment]
It's a bug in the loading script when loading the GOA GAF.  It should be a quick fix.

It's not urgent this value in Chado isn't used on the website.  I'm the only person who looks it.  :-)

**Comment by kimrutherford** [comment]
It's fixed for tonight's load.  I'll check in the morning.

**Comment by kimrutherford** [comment]
This is fixed now.

This property is mostly for tracking down problems.  We store the source for each GO annotation as a property of the annotation in Chado so it can be queried if needed.

The current list is:
 - from_curation_tool  (the session ID and other details also stored for each annotation)
 - GO_ORFeome_localizations2.txt
 - PMID_20838651_gaf.tsv
 - PMID_22146723_gaf.tsv
 - PMID_26412298_gaf.tsv
 - PMID_27984725_gaf.tsv
 - chromosome1.contig
 - chromosome2.contig
 - chromosome3.contig
 - gene_association.goa_uniprot.pombe+japonicus.gz
 - legacy_go_annotations_from_contigs.gaf.tsv
 - mating_type_region.contig
 - pMIT.contig
 - pombase-prediction.gaf
 - snapshot.geneontology.org/pombase.gaf.gz
 - telomeric.contig

**Comment by ValWood** [comment]
Should contigs still be in the list? We don't load GO annotations from contigs anymore. They are all in the 'legacy' file

**Comment by kimrutherford** [comment]
There is still GO annotation in the contig files for multi-transcript genes.

**Comment by ValWood** [comment]
Of course.
