### ISSUE TITLE
Store IDs of public GO-CAMs as featureprops in Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1165]
We need to know which GO-CAMs to display in the gene pages to implement:
  - pombase/website#2169

**Comment by kimrutherford** [comment]
I've just added a mapping file: `pombe-embl/supporting_files/production_gocams.tsv`

It will need to be manually updated for now.

**Comment by kimrutherford** [comment]
> pombe-embl/supporting_files/production_gocam_id_mapping.tsv

I've added that to the load so they'll be in Chado from tomorrow.

**Comment by ValWood** [comment]
excellent!
