### ISSUE TITLE
malformed GO annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1168]
These only have a partial "with filed" but don't appear to be reported in any logs:

PomBase	SPCC970.03			GO:0016653	GO_REF:0000024	ISO	SGD:	F	XXXX		protein	taxon:4896	20220314	PomBase	has_input(PomBase:SPAC8F11.02c),part_of(GO:0002098)	
PomBase	SPCC970.03			GO:0004128	GO_REF:0000024	ISO	SGD:	F	XXXX		protein	taxon:4896	20220314	PomBase	has_input(PomBase:SPBC29A10.16c),part_of(GO:0006696)	
PomBase	SPCC970.03			GO:0004128	GO_REF:0000024	ISO	SGD:	F	XXXX		protein	taxon:4896	20220314	PomBase	has_input(PomBase:SPCC16A11.10c),part_of(GO:0006696)	
PomBase	SPCC970.03			GO:0006696	GO_REF:0000024	ISO	SGD:	P	XXXX		protein	taxon:4896	20240504	PomBase

**Comment by ValWood** [comment]
I will fix once they are logged so  you can test

**Comment by kimrutherford** [comment]
I've added a check for that problem but not in time for the load.  There should be warnings in the legacy GO log file on Friday morning.

**Comment by kimrutherford** [comment]
> I will fix once they are logged so you can test

Thanks.  The new warning works:

https://curation.pombase.org/dumps/builds/pombase-build-2024-05-10/logs/log.2024-05-09-21-20-23.legacy_go_from_contigs

**Comment by ValWood** [comment]
thanks, annotations fixed.
