### ISSUE TITLE
 PTM processing from Uniprot

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1171]
I think we got this data in the Intermine grab, but did not use it. I remember these features being there

Some of these will go on the modification track   (like glycosylation)
So it would be useful to get a full list of the feature types first to decide what to display and on which track

and how to provide provenance

e.g.
https://www.uniprot.org/uniprotkb/Q09175/entry#ptm_processing

**Comment by kimrutherford** [comment]
> I think we got this data in the Intermine grab, but did not use it. 

Can you remind what that is?  I don't remember getting any UniProt data.

**Comment by ValWood** [comment]
Added to tuesday list

**Comment by kimrutherford** [comment]
I had a look at what's available from the UniProt API.  We can get the coordinates for these:
 - Propeptide
 - Chain
 - Glycosylation
 - Disulfide bond

It wouldn't take long to add any/all of these.

**Comment by ValWood** [comment]
glycosylation, add as modification,  "glycosylated residue" ([MOD:00693](https://www.pombase.org/term/MOD:00693))
but only if we don't have it from the same source.

Disulphide bond, add as "disulfide crosslinked residues" ([MOD:00689](https://www.pombase.org/term/MOD:00689))
if we don't have it from the same source (we don't have many of these curated)

"Propeptide" and "chain" can be added as features 

Thanks!

**Comment by kimrutherford** [comment]
> glycosylation, add as modification, "glycosylated residue" ([MOD:00693](https://www.pombase.org/term/MOD:00693))
but only if we don't have it from the same source.
>
> Disulphide bond, add as "disulfide crosslinked residues" ([MOD:00689](https://www.pombase.org/term/MOD:00689))
if we don't have it from the same source (we don't have many of these curated)

Ah, OK.  I hadn't thought about those sort of cases.  That will take a bit longer because they'll need to be included in Chado and annotation.  The data for the other new tracks we get from UniProt isn't going into Chado, it's just displayed in the protein feature viewer.

> "Propeptide" and "chain" can be added as features

I can do those quickly.

**Comment by kimrutherford** [comment]
> "Propeptide" and "chain" can be added as features

That's done for tomorrow.

https://desktop.kmr.nz/gene_protein_features/SPAC19G12.10c

![image](https://github.com/user-attachments/assets/c3b7792b-7391-453d-be91-043914d22e97)

**Comment by kimrutherford** [comment]
>> "Propeptide" and "chain" can be added as features
>
> That's done for tomorrow.

Yet again I forgot to push my changes.  I'll check again on Friday.

**Comment by kimrutherford** [comment]
> "Propeptide" and "chain" can be added as features

That's on the main site now.  Example: https://www.pombase.org/gene_protein_features/SPAC22E12.09c

**Comment by kimrutherford** [comment]
I've add Glycosylation and Disulfide bond from the UniProt date to the protein feature viewer.   It was easier than adding SO features to Chado (which I'll do soon) and the file parsing code is needed for displaying the features and adding them to Chado.

This will be on pombase.org on Saturday morning.  Unless I forgot to commit a change again.

https://desktop.kmr.nz/gene_protein_features/SPBC342.03

Are the track labels OK?

![image](https://github.com/user-attachments/assets/089855e9-23fe-4486-9875-baeb8c38a246)

**Comment by kimrutherford** [comment]
> This will be on pombase.org on Saturday morning.

Looks OK.  Let me know if anything needs rewording:

https://www.pombase.org/gene_protein_features/SPBC342.03

**Comment by ValWood** [comment]
Existing glycosylation sites are shown in the modification section as  "pink dots"
so we should do the same with these imported ones
<img width="1353" alt="Screenshot 2024-08-10 at 09 20 07" src="https://github.com/user-attachments/assets/df251ba5-064d-411d-a20a-067087025327">

**Comment by ValWood** [comment]
We probably also need a way to let the user know how to find the details of the modifications on the gene page  etc

**Comment by ValWood** [comment]
crosslinks are a special case, and we have not curated many of them.
https://www.pombase.org/term/MOD:00033

I agree these should go on a separate track which shows the connections between them.
So far we have only one with residues, and we only display this as individual residues

(to discuss on next weeks call)

**Comment by ValWood** [comment]
glycosylation sites
for example here:
https://www.pombase.org/gene_protein_features/SPAC22E12.09c
uniprot doesn't add anything, there are fewer sites, and the term is less specific

**Comment by ValWood** [comment]
and they arent experimentally sourced

**Comment by ValWood** [comment]
Maybe we keep them both (I see we describe modifications as 'curated')
but  if so we should put the tracks next to each other and use the same symbols

**Comment by kimrutherford** [comment]
> Existing glycosylation sites are shown in the modification section as "pink dots"
so we should do the same with these imported ones

I've changed the configuration so that should be fixed in the morning.

> we should put the tracks next to each other and use the same symbols

I've done that too.

**Comment by ValWood** [comment]
fab. eventually we want. to merge these onto the same track, I think...

**Comment by kimrutherford** [comment]
> eventually we want. to merge these onto the same track, I think...

That will help.  I've made a change to put the glycosylation sites track directly under the modifications track to group them together.  That will be visible tomorrow:

![image](https://github.com/user-attachments/assets/8981203e-4c9a-48ed-a57b-5f69f24a95c2)

**Comment by ValWood** [comment]
Change mouse over to be more explicit

MODIFICATIONS

GLYCOSYLATION SITE - mouse over Inferred glycosylation sites imported from uniprot
(these should also  appear in the modification section of the gene page)

Check if disulphide cross-links are displayed
and display like this :
https://www.uniprot.org/uniprotkb/Q01663/entry#ptm_processing

**Comment by kimrutherford** [comment]
> (these should also appear in the modification section of the gene page)

So we should make PSI-MOD annotations for the glycosylation sites from UniProt?  In that case we we'll be able to remove the glycosylation sites track.

**Comment by kimrutherford** [comment]
> GLYCOSYLATION SITE - mouse over Inferred glycosylation sites imported from uniprot

I've added "Inferred" to the mouse overs.

> Check if disulphide cross-links are displayed

They now look like:
![image](https://github.com/user-attachments/assets/389f6961-83ab-4c19-a6b1-dc4c207a24e0)

The changes will be on pombase.org soon.

**Comment by ValWood** [comment]
>They now look like:
the look great!

**Comment by kimrutherford** [comment]
> The changes will be on pombase.org soon.

I forgot that it will need an over night load for those changes.  So it will be on pombase.org in the morning.

**Comment by kimrutherford** [comment]
> I forgot that it will need an over night load for those changes. So it will be on pombase.org in the morning.

The improved disulphide cross-links display is now on pombase.org

I think this issue is done now (and it's long) so I'll close it and move the remaining task to a new issue:
  - pombase/pombase-chado#1210

**Comment by kimrutherford** [comment]
>> Check if disulphide cross-links are displayed
>
> They now look like:
> ![image](https://github.com/user-attachments/assets/389f6961-83ab-4c19-a6b1-dc4c207a24e0)

While working on pombase/website#2203 I noticed a display option that allows us to display the disulphide cross-links like this:

![image](https://github.com/user-attachments/assets/f2adb5fe-2e73-4851-85e8-ce3a7b79a01d)

https://www.pombase.org/gene/SPBC342.03

I think it looks better because it matches the modifications.

Do you think it's an improvement?

**Comment by ValWood** [comment]
Yes, that looks great!

**Comment by kimrutherford** [comment]
OK, I won't revert the change then.  :-)

**Comment by kimrutherford** [comment]
I noticed that I had misconfigured the modification loading.  Now fixed so get one extra modification annotation from UniProt:
https://www.pombase.org/term/MOD:00793
