### ISSUE TITLE
Display 'binding and ' active site' from UniPRot

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1172]
This is quite hidden unt her the function section in a subsection 'features'
So this is different from  the "PTM-type" features

It seemed to include only: 
binding site and
catalytic site, but there may be more

These could be  1 track or 2 tracks

eg
<img width="1079" alt="Screenshot 2024-05-08 at 16 13 09" src="https://github.com/pombase/pombase-chado/assets/7359272/ec6dbb12-aab2-438c-9619-47a6696aa738">

need to acknowledge UniProt as source in the pop-up

**Comment by kimrutherford** [comment]
> eg

Do you have a link to that page?

**Comment by ValWood** [comment]
Sorry!.
Now I can't remember what that was.
Here is a different one
https://www.uniprot.org/uniprotkb/Q9P376/entry#function

**Comment by ValWood** [comment]
This ticket is related to website
https://github.com/pombase/website/issues/2159

**Comment by ValWood** [comment]
Also related, although a different datatype 
https://github.com/pombase/pombase-chado/issues/1172

**Comment by kimrutherford** [comment]
See also:
  - https://github.com/pombase/pombase-chado/issues/52

**Comment by kimrutherford** [comment]
I've had a look at the data from the UniProt file (https://github.com/pombase/pombase-chado/issues/52).

For binding site we get:
 - position: `123` or can be a range `138..146`
 - `/evidence="ECO:0000250"` or `/evidence="ECO:0000250|UniProtKB:G0SHW7"`
 - `/ligand="1,2-diacylglycero-3-phosphoethanolamine"` or `/ligand="DNA"`
 - `/ligand_id="ChEBI:CHEBI:29991"`
 - notes, for example: `/note="in chain C"` or `/note="Nucleophile"`

For active sites we get:
 - position: always a point not a  range
 - `/evidence="ECO:0000250|UniProtKB:O22317"`
   - a few have multiple evidence: `/evidence="ECO:0000250|UniProtKB:P15731, ECO:0000255|PROSITE-ProRule:PRU00388"`
 - notes

We need to decide which of these qualifiers we want to display.

**Comment by kimrutherford** [comment]
> Also related, although a different datatype
> https://github.com/pombase/pombase-chado/issues/1172

This this issue?

**Comment by kimrutherford** [comment]
I've added the code for binding sites and active sites in time for the current load.  Here's how it looks:

![image](https://github.com/user-attachments/assets/5dc2f8ad-16cd-4d04-b59b-094edf4ec240)

Let me know if we should change the formatting of the text in the mouse-over for binding sites.

The new display is on my desktop for now: https://desktop.kmr.nz/gene/SPAC11E3.13c
It should be on the main site in the morning.

**Comment by kimrutherford** [comment]
> It should be on the main site in the morning.

That's live now:
https://www.pombase.org/gene_protein_features/SPBC1105.02c

**Comment by kimrutherford** [comment]
I forgot to say: for now the binding and active sites are only shown on the full view, not in the widget on the gene pages.

**Comment by ValWood** [comment]
> That's live now:

nice!

**Comment by ValWood** [comment]
I think full view is OK.

**Comment by kimrutherford** [comment]
I'll add something to the docs before closing:
https://www.pombase.org/documentation/gene-page-protein-features-widget

**Comment by kimrutherford** [comment]
> I'll add something to the docs before closing:
> https://www.pombase.org/documentation/gene-page-protein-features-widget

I've added this documentation by copy and pasting from the UniProt track descriptions.  Is this OK?

  - **Signal peptide** N-terminal signal peptide position, imported from UniProt
  - **Transit peptide** Transit peptide position, imported from UniProt
  - **Active sites** Amino acid(s) directly involved in the activity of an enzyme, imported from UniProt
  - **Binding sites** Binding site for any chemical group (co-enzyme, prosthetic group, etc.), imported from UniProt
  - **Beta strands** Experimentally determined beta strands, imported from UniProt
  - **Helices** Experimentally determined helical regions, imported from UniProt

**Comment by ValWood** [comment]
Sounds good except 
Signal peptide N-terminal signal peptide position, imported from UniProt
should be a mixture of imported, curated, and running signal peptide locally

**Comment by kimrutherford** [comment]
I think all the signal peptides in the protein feature viewer are from UniProt, because they have positions.

**Comment by ValWood** [comment]
>I think all the signal peptides in the protein feature viewer are from UniProt, because they have positions.

yes they seem to be.
I think we need to get the others from phobius to fil in the gaps.

**Comment by ValWood** [comment]
I think this can close?
