### ISSUE TITLE
Metric : Total genes in  GO CAM models

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1176]
It would be nice once you have figured out the "Shrec turtles" to have a simple metric

"number of genes in models"

It will motivate us! Aiming for 1000 by the  end of the grant, (but I think that might be a bit optimistic, because we are doing the low hanging fruit first)

**Comment by kimrutherford** [comment]
It's not quite what you asked for, but I've added the code to the query system to allow querying for genes that are in models.

On my desktop I have a "Genes in GO-CAM models" in the commonly used queries list in the advanced search.

![image](https://github.com/pombase/pombase-chado/assets/90474/cfffe74a-0b34-4dc6-9b1f-3bf59f927640)

This could be added to pombase.org at any time with a config change.

**Comment by ValWood** [comment]
This. is a good start. Remind me what the process is for production models to get into pombe (if you know).
do we get them after a Noctua update, or after a GO update?

**Comment by kimrutherford** [comment]
> Remind me what the process is for production models to get into pombe (if you know). do we get them after a Noctua update, or after a GO update?

Currently we have to manually edit these files:
 - `pombe-embl/supporting_files/production_gocam_id_mapping.tsv` (model ID to gene ID mapping)
 - `pombe-embl/supporting_files/production_gocam_term_id_mapping.tsv` (model ID to process term mapping)

But I've been working today on automating the update of the files using:
  - http://snapshot.geneontology.org/products/upstream_and_raw_data/noctua_pombase.gpad.gz which has the pombe GO-CAM IDs and the genes in the models
  - API https://api.geneontology.org/api/go-cam/{ID} to get the process terms and model titles

**Comment by kimrutherford** [comment]
This number should increase to 160 tomorrow:

![image](https://github.com/pombase/pombase-chado/assets/90474/cfffe74a-0b34-4dc6-9b1f-3bf59f927640)

And there will be 15 models in PomBase.

**Comment by ValWood** [comment]
Excellent
CC @PCarme

**Comment by kimrutherford** [comment]
> This number should increase to 160 tomorrow:

![image](https://github.com/pombase/pombase-chado/assets/90474/5902d684-7b9b-4953-bbc8-8724e1a3b963)

**Comment by kimrutherford** [comment]
"Genes in GO-CAM models" is now available from the commonly used queries list on pombase.org.

Is the wording "Genes in GO-CAM models" OK?  It was the first thing I thought of.  Let me know if you have any suggestions for improving it.

**Comment by ValWood** [comment]
Let's say "genes in GO-CAM pathway models"

**Comment by kimrutherford** [comment]
> Let's say "genes in GO-CAM pathway models"

That's done now.

Is there anything else to do here?

**Comment by ValWood** [comment]
nope
