### ISSUE TITLE
Query GO for pombe GO-CAMs

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1177]
We want to be able query for pombe GO-CAMs rather than having to manually curate files in SVN (like `pombe-embl/supporting_files/production_gocam_id_mapping.tsv`)

See also:
  - pombase/pombase-chado#1174
  - pombase/website#2173

SPARQL query for use here: https://geneontology.org/sparql:
```sparql
PREFIX metago: <http://model.geneontology.org/>
PREFIX provided_by: <http://purl.org/pav/providedBy>

SELECT distinct ?gocam WHERE {
  GRAPH ?gocam {
    ?gocam provided_by:  "http://www.pombase.org" .
  }
}
```
(Currently it returns no results)

**Comment by kimrutherford** [comment]
> (Currently it returns no results)

This (fixed) query returns three GO-CAM IDs provided_by PomBase.  Progress!

```
PREFIX gocam: <http://model.geneontology.org/>
PREFIX provided_by: <http://purl.org/pav/providedBy>

SELECT distinct ?gocam WHERE {
  GRAPH ?gocam {
    ?gocam provided_by: "http://www.pombase.org"^^<http://www.w3.org/2001/XMLSchema#string> .
  }
}
ORDER BY ?gocam
```

The query results are:
[gocam:66187e4700001573](http://model.geneontology.org/66187e4700001573)
[gocam:66187e4700001781](http://model.geneontology.org/66187e4700001781)
[gocam:66187e4700002284](http://model.geneontology.org/66187e4700002284)


For comparison, we have these GO-CAMs manually configured:

66187e4700001573
66187e4700001781
66187e4700002284
66187e4700003150
662af8fa00000408
662af8fa00000499

**Comment by kimrutherford** [comment]
We can query model IDs and gene IDs in GO-CAM models provided by PomBase with:

```
PREFIX gocam: <http://model.geneontology.org/>
PREFIX provided_by: <http://purl.org/pav/providedBy>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX pombasegeneid: <http://identifiers.org/pombase/>

SELECT distinct ?gocam ?geneid WHERE {
  GRAPH ?gocam {
    ?gocam provided_by: "http://www.pombase.org"^^<http://www.w3.org/2001/XMLSchema#string> .
    ?modelgeneid rdf:type ?geneid
  }
  FILTER(strstarts(str(?geneid), str(pombasegeneid:)))
}
ORDER BY ?gocam ?geneid
```

Results look something like:

[gocam:66187e4700001573](http://model.geneontology.org/66187e4700001573) [pombasegeneid:SPAC644.04](http://identifiers.org/pombase/SPAC644.04)
[gocam:66187e4700001573](http://model.geneontology.org/66187e4700001573) [pombasegeneid:SPBC2F12.08c](http://identifiers.org/pombase/SPBC2F12.08c)
[gocam:66187e4700001573](http://model.geneontology.org/66187e4700001573) [pombasegeneid:SPCC330.10](http://identifiers.org/pombase/SPCC330.10)
[gocam:66187e4700001781](http://model.geneontology.org/66187e4700001781) [pombasegeneid:SPAC1B3.17](http://identifiers.org/pombase/SPAC1B3.17)
...

I'm hoping we can wrap this in a script that gets run nightly or maybe weekly.

**Comment by kimrutherford** [comment]
> We can query model IDs and gene IDs in GO-CAM models provided by PomBase with:

I meant to say that this query returns every gene ID used anywhere in the model.  I think that's probably what we want but the query could be made more precise if needed later (once I understand the GO-CAM model better).

**Comment by kimrutherford** [comment]
I've added a script that makes a SPARQL query to get the GO-CAM IDs and corresponding gene IDs.  The output is the same format as `pombe-embl/supporting_files/production_gocam_id_mapping.tsv`

As with the file generated for process terms (pombase/website#2173), there are only three models in the output of the script:
 - 66187e4700001573
 - 66187e4700001781
 - 66187e4700002284
 
I'm assuming that more will be available after the next GO update.

I hope that eventually we'll be able automatically update `production_gocam_id_mapping.tsv` nightly or weekly using the new script.

**Comment by kimrutherford** [comment]
SPARQL is being deprecated by GO in favour of the [GO API](https://api.geneontology.org)

It looks like we can use this API end-point to return gene products given a list of GO-CAM IDs: /api/models/gp

https://geneontology.org/docs/tools-guide/

**Comment by kimrutherford** [comment]
And this end-point should return a list of pombe models: `/api/taxon/{taxon}/models`

There's an issue at the moment though:
  - geneontology/go-fastapi#94

**Comment by kimrutherford** [comment]
If necessary, we can get the pombe GO-CAM IDs and genes from: http://snapshot.geneontology.org/products/upstream_and_raw_data/noctua_pombase.gpad.gz

**Comment by kimrutherford** [comment]
I've writing a script that uses the [Noctua PomBase GPAD file](http://snapshot.geneontology.org/products/upstream_and_raw_data/noctua_pombase.gpad.gz) and the GO model API (`https://api.geneontology.org/api/go-cam/{ID}`) to update the data files for Chado:
  - `pombe-embl/supporting_files/production_gocam_id_mapping.tsv` - gene ID to GO-CAM ID mapping
  - `pombe-embl/supporting_files/production_gocam_term_id_mapping.tsv` - process term ID to GO-CAM ID mapping

The script is also retrieves the GO-CAM model titles from the API for adding to Chado.

I've run the script and committed the updated files to SVN.  So on Tuesday morning we should have a bunch of extra models and the models will have titles.

**Comment by kimrutherford** [comment]
For now I plan to run the script manually until I'm convinced that it's reliable.

I'm going to close this issue since we can now get what we need from GO.

**Comment by kimrutherford** [comment]
From email, but I wanted to attach it to this issue:

-------------
I remembered the discussion with FlyBase yesterday about GO-CAMs.
We talked about how the Alliance seem to have their own internal
API for GO data.  It's used by the GO-CAM widget.  I had thought that
the widget needed a Alliance special API to work but it occurred to me
today that maybe the data from that API could be in the correct format
for the GO-CAM update script we use.  After trying a few things I was
able to get that to work and we'll have much more up-to-date GO-CAM
information for tonight's load.  There will be 290 genes from this
query tomorrow:
https://www.pombase.org/results/from/id/f99d8133-3206-4941-b44e-9314e7cae3d2

**Comment by kimrutherford** [comment]
> There will be 290 genes from this query tomorrow:
> https://www.pombase.org/results/from/id/f99d8133-3206-4941-b44e-9314e7cae3d2

These are the 290 genes:
https://www.pombase.org/results/from/id/690ab3eb-0db5-4698-82e4-ea006399c40a

**Comment by ValWood** [comment]
Its odd that these arent in the list


SPBC3D6.07 | gpi3 | pig-A, phosphatidylinositol N-acetylglucosaminyltransferase subunit Gpi3
SPCC16A11.06c | gpi10 | pig-B
SPAC13G6.03 | gpi7 | Pig-G, CP2 mannose-ethanolamine phosphotransferase GPI anchor biosynthesis protein Gpi7
SPBC27B12.06 | gpi13 | pig-O
SPAC4G8.12c | smp3 | pig-Z, alpha-1,2-mannosyltransferase Smp3

they have been in the production model for quite a while...

[SPBC3D6.07](https://www.pombase.org/gene/SPBC3D6.07)	[gpi3](https://www.pombase.org/gene/SPBC3D6.07)	pig-A, phosphatidylinositol N-acetylglucosaminyltransferase subunit Gpi3
[SPCC16A11.06c](https://www.pombase.org/gene/SPCC16A11.06c)	[gpi10](https://www.pombase.org/gene/SPCC16A11.06c)	pig-B
[SPAC13G6.03](https://www.pombase.org/gene/SPAC13G6.03)	[gpi7](https://www.pombase.org/gene/SPAC13G6.03)	Pig-G, CP2 mannose-ethanolamine phosphotransferase GPI anchor biosynthesis protein Gpi7
[SPBC27B12.06](https://www.pombase.org/gene/SPBC27B12.06)	[gpi13](https://www.pombase.org/gene/SPBC27B12.06)	pig-O
[SPAC4G8.12c](https://www.pombase.org/gene/SPAC4G8.12c)	[smp3](https://www.pombase.org/gene/SPAC4G8.12c)	pig-Z, alpha-1,2-mannosyltransferase Smp3

**Comment by kimrutherford** [comment]
> they have been in the production model for quite a while...

Which model.  I can look it up if you let me know the ID.

**Comment by ValWood** [comment]
this one
http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A665912ed00000192

**Comment by ValWood** [comment]
similarly

SPAC3A11.08 | cul4 | CLRC complex subunit, cullin 4
-- | -- | --
SPCC970.07c | raf2 | CLRC ubiquitin ligase complex subunit Raf2
SPCC613.12c | raf1 | CLRC ubiquitin ligase complex WD repeat subunit Raf1/Dos1
SPCC11E10.08 | rik1 | CLRC ubiquitin ligase complex WD repeat subunit Rik1

[SPAC3A11.08](https://www.pombase.org/gene/SPAC3A11.08)	[cul4](https://www.pombase.org/gene/SPAC3A11.08)	CLRC complex subunit, cullin 4
[SPCC970.07c](https://www.pombase.org/gene/SPCC970.07c)	[raf2](https://www.pombase.org/gene/SPCC970.07c)	CLRC ubiquitin ligase complex subunit Raf2
[SPCC613.12c](https://www.pombase.org/gene/SPCC613.12c)	[raf1](https://www.pombase.org/gene/SPCC613.12c)	CLRC ubiquitin ligase complex WD repeat subunit Raf1/Dos1
[SPCC11E10.08](https://www.pombase.org/gene/SPCC11E10.08)	[rik1](https://www.pombase.org/gene/SPCC11E10.08)	CLRC ubiquitin ligase complex WD repeat subunit Rik1

are in
http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A66187e4700001781
http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A665912ed00001983
http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A665912ed00000652

**Comment by kimrutherford** [comment]
OK, thanks.

I'm now testing an even more dodgy hack to get all the details of all the production models.  We can talk about what I've done next time we have a chat.  It's quite a fragile solution that queries the Noctua server (which Seth recommended / requested that we don't do) and the Alliance GO-CAM API (which seems like a temporary hack on their part).  So I don't know how long it will work for us.  But it works for now and it seems quite up to date.

With the new hack we get 354 genes in models and all the missing genes from your comment are present.  Here's the list on my desktop:
https://desktop.kmr.nz/results/from/id/89524fcb-3b06-4943-ae78-6f748e141108

(Lots of data is missing from that version as it was a quick load to test the GO-CAMs)

**Comment by kimrutherford** [comment]
> With the new hack we get 354 genes in models

I've committed those changes into SVN so they'll be on pombase.org tomorrow.

**Comment by ValWood** [comment]
excellent, lets use that for the time being. It's really taking shape, we have done about 10% of likely possible in 3 months!

**Comment by kimrutherford** [comment]
> they'll be on pombase.org tomorrow

That worked:
https://www.pombase.org/results/from/id/f99d8133-3206-4941-b44e-9314e7cae3d2

Let me know if you notice any missing genes.  (Or genes that shouldn't be there)

**Comment by ValWood** [comment]
Perfect,  the progress is pretty amazing because we have quite a lot in development and things to add to existing pathways.

**Comment by kimrutherford** [comment]
New model tomorrow: 67086be200002266

**Comment by kimrutherford** [comment]
> New model tomorrow: 67086be200002266

Big model!
https://dev.pombase.org/gocam/docs/67086be200002266

**Comment by ValWood** [comment]
That model  looks great!

**Comment by ValWood** [comment]
boom! 
409 | ~383~ | Genes in GO-CAM pathway models

**Comment by PCarme** [comment]
> That model looks great!

Thanks, it took me a while to put it together.
