### ISSUE TITLE
Update PDB data file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1180]
Last updated 2024-03-04

https://github.com/pombase/pombase-chado/wiki/Updating-the-PDB-data-file

**Comment by kimrutherford** [comment]
I'll check the result after the load.

Four extra publications in the new data:
 - PMID:38448439 (in PomBase, not curated)
 - PMID:38603491 (not in PomBase)
 - PMID:38740643 (not in PomBase)
 - PMID:38773107 (in PomBase, not curated)

New structures for:
 - SPBC2F12.17
 - SPAC23C11.15
 - SPAC23H4.12
 - SPAC29A4.18
 - SPACUNK4.14
 - SPAC6F6.10c
 - SPAC25A8.01c
 - SPBC16C6.08c (first structure in PDB)
 - SPBC6B1.09c
 - SPBC29A3.18 (first structure)
 - SPBC36.05c
 - SPCC1682.01 (first structure)
 - SPCC1739.09c
 - SPCC737.02c (first structure)
 - SPCC338.10c
 - SPCC1442.08c
 - SPCC1259.05c
 - SPAC19G12.06c
 - SPCC622.09 (first structure)
 - SPMIT.05 (first structure)
 - SPMIT.01
 - SPMIT.04
 - SPMIT.11
 - SPAC630.03
 - SPAC1782.07 (first structure)
 - SPCC613.10 (first structure)
 - SPBC14C8.06
 - SPAC1296.02
 - SPBC16H5.06 (first structure)
 - SPAC13C5.07
 - SPAC2F7.07c
 - SPAC16C9.05
 - SPBC12D12.01
 - SPAC17G8.04c
 - SPAC6G9.07c
 - SPBPJ4664.04
 - SPAC1565.01
 - SPAC24C9.16c
 - SPBP4H10.08 (first structure)
 - SPBP23A10.15c (first structure)
 - SPAC1B2.04
 - SPBP23A10.15c (first structure)
 - SPAC1B2.04
 - SPAC11H11.06
 - SPBC1778.08c

**Comment by kimrutherford** [comment]
All good:

> Four extra publications in the new data:
>  - PMID:38448439 (in PomBase, not curated)

https://www.pombase.org/reference/PMID:38448439

>  - PMID:38603491 (not in PomBase)

https://www.pombase.org/reference/PMID:38603491

>  - PMID:38740643 (not in PomBase)

https://www.pombase.org/reference/PMID:38740643

>  - PMID:38773107 (in PomBase, not curated) 

https://www.pombase.org/reference/PMID:38773107

**Comment by ValWood** [comment]
could you check this one?
https://www.pombase.org/reference/PMID:38773107

in the list above it says sad1, but on this page 
https://www.pombase.org/reference/PMID:38773107
and at pdb we have rss1.

I already reported to pdb , the pdb page has rss1 so I think the problem is at their end, but then I saw that is says sad1 in the list above (and rss1 isn't in the list), so I wondered where these 2 different identifiers come from?

**Comment by ValWood** [comment]
Also 
https://www.pombase.org/reference/PMID:37939086
genes are listed as no previous structure, but they have been in for a while?
I have been waiting for the author to curate....

**Comment by kimrutherford** [comment]
> in the list above it says sad1

The "New structures for" list?  Looking at it again it seems to be full of errors.  Sorry!  It was a bit too late at night.

This is the actual list of genes with new structures.  Much less exciting:

 - SPAC1565.02c
 - SPAC1805.12c
 - SPAC1805.15c
 - SPAC1F5.04c
 - SPBC119.02
 - SPBC1604.21c
 - SPBC337.08c

It looks like I got the list of new publications with structures correct.

> I already reported to pdb , the pdb page has rss1 so I think the problem is at their end, but then I saw that is says sad1 in the list above (and rss1 isn't in the list), so I wondered where these 2 different identifiers come from?

Sorry if my nonsense list of genes has confused things.

The previous datafile had an entry for Q10214 / rss1 / SPAC4H3.06 for structure 8j0h, but no PMID.  The update adds this publication: PMID:38773107

The PDB entry has sad1 in the title but the IDs are all for rss1: https://www.ebi.ac.uk/pdbe/entry/pdb/8j0h
so I think it's a problem at PDB.

> https://www.pombase.org/reference/PMID:37939086
> genes are listed as no previous structure, but they have been in for a while?

Yep, sorry again.  There has been no change for PMID:37939086

**Comment by ValWood** [comment]
I curated

    PMID:38448439 (in PomBase, not curated)
    PMID:38603491 (not in PomBase)
    PMID:38740643 (not in PomBase)
because they were easy

    PMID:38773107 (in PomBase, not curated)
has more data an is out for CC.

**Comment by ValWood** [comment]
I updated pdb with
Rss1  structure does not seem to be associated with any publication yet.

The Sad1 structure which should be associated with  PMID:38773107 The SUN-family protein Sad1 mediates heterochromatin spatial organization through interaction with histone H2A-H2B.

is [https://www.ebi.ac.uk/pdbe/entry/pdb/7ybf](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ebi.ac.uk%2Fpdbe%2Fentry%2Fpdb%2F7ybf&data=05%7C02%7Cvw253%40cam.ac.uk%7Cb3f320aa51c847b230e808dc8d1aaeab%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638540392944016009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=%2FwoHLhOO4pwupFd%2F9NQi5fhb38q5s7Oc%2BAOR%2FIr0tUE%3D&reserved=0)

we cant do anything about this so this ticket can close now?

**Comment by kimrutherford** [comment]
> we cant do anything about this so this ticket can close now?

We can fix the gene of 8j0h just for us by editing the data file that we load:
```
pombe-embl/external_data/protein_structure/systematic_id_to_pdbe_mapping.tsv
```
Is that a good plan?

**Comment by ValWood** [comment]
We can do that , will hopefully be fixed properly before the next update...

**Comment by kimrutherford** [comment]
> We can fix the gene of 8j0h just for us by editing the data file that we load:

I've done that for tonight's load.  I'll check on Monday morning.

**Comment by kimrutherford** [comment]
> We can fix the gene of 8j0h just for us by editing the data file that we load:

Done!

https://www.pombase.org/gene/SPBC12D12.01
