### ISSUE TITLE
correlated_with disease list

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1183]
follow on from
https://github.com/pombase/pombase-chado/issues/853

Could you provide me with the "correlated-with" disease gene list?

It  could be useful to have a filter for this in the query tool

**Comment by kimrutherford** [comment]
Do you mean "contributes_to"?

**Comment by ValWood** [comment]
Yes!

**Comment by kimrutherford** [comment]
There are 119 contributes_to annotations.  Is this all the information you need?:

[disease_contributes_to.csv](https://github.com/user-attachments/files/15965563/disease_contributes_to.csv)


|uniquename     |name     |termid         |term_name                                                             |
|---------------|---------|---------------|-----------------------------------------------------------------------|
|SPBC2G2.08    |ade9     |MONDO:0011120  |neural tube defects, folate-sensitive                                 |
|SPAC56F8.06c  |alg10    |MONDO:0013367  |long QT syndrome 2                                                     |
|SPAC664.14    |amt2     |MONDO:0859172  |hemolytic disease of fetus and newborn, RH-induced                    |
|SPAC2E1P3.02c |amt3     |MONDO:0859172  |hemolytic disease of fetus and newborn, RH-induced                    |
... | ... | ... | ...

**Comment by kimrutherford** [comment]
> It could be useful to have a filter for this in the query tool

I'm working on that now.  It will probably be 3-4 hours work.

**Comment by ValWood** [comment]
Yep!

**Comment by kimrutherford** [comment]
> I'm working on that now. It will probably be 3-4 hours work.

I didn't get very far before we had our call and decided not do implement that.  I changed one line of code.  :-)

But I did establish how much work it would be so if it becomes useful to constrain by qualifier it could be done in half a day.
