### ISSUE TITLE
UniPathway mapping, not filtered

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1186]
I filter a number of UniPathway mappings:

filtered_mappings:UniPathway:UPA00868
filtered_mappings:UniPathway:UPA00259
filtered_mappings:UniPathway:UPA00331
filtered_mappings:UniPathway:UPA00326
filtered_mappings:UniPathway:UPA00042
filtered_mappings:UniPathway:UPA00143
filtered_mappings:UniPathway:UPA00392
filtered_mappings:UniPathway:UPA00617
filtered_mappings:UniPathway:UPA00906

however this one isn't filtered:
filtered_mappings:UniPathway:UPA00868

I can't figure out why.
Also the link doesn't work, is that related?
[https://www.pombase.org/term/GO:0033512](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.pombase.org%2Fterm%2FGO%3A0033512&data=05%7C02%7Cvw253%40cam.ac.uk%7C394ed68bb0e04a8520ca08dc911c0161%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638544796659440126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=mqlHN0ZE0ehXqX1CvViK836sTA6iMDeFm65iTrjaEjY%3D&reserved=0)

**Comment by ValWood** [comment]
Maybe this is a time lag issue, I though I had checked it on, perhaps not?

**Comment by kimrutherford** [comment]
Looks like you changed UniRule:UPA00868 to UniPathway:UPA00868 in goa-load-fixes/filtered_mappings at 7:30 this morning?

I think that will be picked up in tonight's load.
