### ISSUE TITLE
allele name update mcm4-td

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1187]
Re

  SPCC16A11.17    mcm4-tstd 20a419e583ad61e6,37237b530ab38bc9,56ce08f89dc9d46c,7097a362b55929af Ub-DHFRts-mcm4    mcm4td    7097a362b55929af,bcb5a5b99a75c27a 

COuld you change all allers named
Ub-DHFRts-mcm4
or mcm4td
to mcm4-td ?

Ub-DHFRts-mcm4 is the description but the name is mcm4-td

**Comment by ValWood** [comment]
Before allele pages

**Comment by kimrutherford** [comment]
> Ub-DHFRts-mcm4 or mcm4td

There is only one session in Canto with either of those names:
https://curation.pombase.org/pombe/curs/bcb5a5b99a75c27a/genotype_manage/ro
