### ISSUE TITLE
small changes to evidence code remapping /quick

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#119]
these can be remapped when loading from Artemis as follows:

These can be sequence ortholog
&gt; dictyBase     |     2
&gt;   ECOGENE       |     2
&gt;   CGD           |     3
&gt;   RGD           |     4
&gt;   WB            |     5
&gt;   CBS           |     9
&gt;   AGI\_LocusCode |     9
&gt;   FB            |    11
&gt;   MGI           |    13

These can be sequence model

Prosite       |     6
SMART         |     2

Original comment by: ValWood

**Comment by mah11** [comment]
upgraded at source (i.e. contig files), so closing
