### ISSUE TITLE
chance evidence for TMMs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1190]
<img width="895" alt="Screenshot 2024-07-07 at 21 10 23" src="https://github.com/pombase/pombase-chado/assets/7359272/64752af1-5245-4646-be4d-01500b651403">

Anything with manual assertion  each annotation should be applied manually.  

Here, I think we should use
match to sequence model evidence

https://docs.google.com/document/d/1Fj1BZ4ixwVmA3aYkeoFpVWpkZGmpMQDuJnw7Ki-tuZc/edit

**Comment by kimrutherford** [comment]
No problem.  I've made that change for tonight's load.  I'll check in the morning and close this issue then.
