### ISSUE TITLE
Include manual orthologs in the annotation counts / stats

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1191]
Now pombase/pombase-chado#578 is done we should include ortholog counts in these graphs: 
 - Cumulative annotation type count by year
 - Average annotations per publication by year range

See:
  - https://github.com/pombase/pombase-chado/issues/570#issuecomment-245517143
  - pombase/pombase-chado#578

**Comment by kimrutherford** [comment]
Now I've looked I think this will happen automatically thanks to:
  - #578

I'll check on Tuesday morning.

**Comment by kimrutherford** [comment]
> Now I've looked I think this will happen automatically thanks to:

I was wrong.  :-)

I've made a small tweak to include orthologs in the annotation counts.  I'll check on Wednesday.

**Comment by kimrutherford** [comment]
From tomorrow the annotation type graph will look something like this.  The ortholog annotation count includes all orthologs, but I think that matches the logic for the other numbers.

![image](https://github.com/user-attachments/assets/4bf5683f-8d54-40da-b150-01cc7838fdd9)

**Comment by ValWood** [comment]
Wow, we cruise past 400,000!

**Comment by kimrutherford** [comment]
> Wow, we cruise past 400,000!

https://www.pombase.org/metrics

![image](https://github.com/user-attachments/assets/02ab365b-ce2a-42fb-b813-b385f582ecb0)
