### ISSUE TITLE
some rpb alleles are conflated

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1192]
rpb1-CTD-S7A(aaCTD-S7A)[Not assayed] 

has synonyms
rpb1-S5.S5A  (this is incorrect, which session was it added?)
rpb1-CTD-S5.S5A (this is incorrect, which session was it added?)
rpb1-S5-S5A(1-29)  (this is incorrect, which session was it added?)
rpb1-CTD-S5A(r2-r29-2)  (this is incorrect, which session was it added?)
rpb1-P6.P6A  (this is incorrect, which session was it added?)
rpb1-CTD-P6.P6A  (this is incorrect, which session was it added?)
rpb1-S7A rpb1-S7A(1-29)
 rpb1-CTD-S7A29 -

**Comment by ValWood** [comment]
rpb1-CTD-P6A(r2-r29)(aaCTD-P6A(r2-r29))[Not assayed] 

has synonyms
rpb1-S5.S5A rpb1-CTD-S5.S5A  (this is incorrect, which session was it added?)
rpb1-S5-S5A(1-29) (this is incorrect, which session was it added?)
 rpb1-CTD-S5A(r2-r29-2)  (this is incorrect, which session was it added?)
rpb1-P6.P6A rpb1-CTD-P6.P6A  (this is incorrect, which session was it added?)

**Comment by ValWood** [comment]
rpb1-CTD-S5A(r2-r29)(aaCTD-S5A(r2-r29))[Not assayed] 

rpb1-S5.S5A  (this is incorrect, which session was it added?)
rpb1-CTD-S5.S5A    (this is incorrect, which session was it added?)
rpb1-S5-S5A(1-29) 
rpb1-CTD-S5A(r2-r29-2)   (this is incorrect, which session was it added?)

**Comment by ValWood** [comment]
In case this isn't clear, I need the session(s) the the synonym is instantiated in .
I need to remove the incorrect synonyms, and possibly create the correct allels and migrate the annotations.

**Comment by kimrutherford** [comment]
> rpb1-CTD-S7A(aaCTD-S7A)[Not assayed]
> has synonyms

Are you seeing those synonyms in Canto?  Sorry, what's shown in Canto is a bit bogus.  The synonyms labelled "existing" should be ignored because they include synonyms that aren't valid anymore.  We need to re-visit that functionality because it's clearly not right.  The "existing" synonyms seem to be include all synonyms that the allele has had ever.  Not great.

Only the "new" synonyms from a session are loaded into Chado.

So "rpb1-CTD-S7A" only has a few synonyms on the website: https://dev.pombase.org/allele/SPBC28F2.12:allele-9

**Comment by ValWood** [comment]
I'm a bit confused so maybe we can chat about this on Tuesday and I can demo the problem.

**Comment by ValWood** [comment]
FInd and add a session

**Comment by kimrutherford** [comment]
Could you add an example session when you get a chance?  Sorry I've lost the example I had.

**Comment by ValWood** [comment]
Are you sure you haven't fixed it? I have searched lots, and I can't find any examples.

**Comment by kimrutherford** [comment]
I don't remember fixing anything.  I'll do a Canto database search to see if I can track down an example.

**Comment by kimrutherford** [comment]
I think I've tracked down the session that was messed up:
https://curation.pombase.org/pombe/curs/6339283c028dd2d6/genotype_manage/ro

I've made a copy to my desktop to investigate.

**Comment by kimrutherford** [comment]
> There is a bug (or multiple bugs) in the handling of existing allele synonyms. When the details for an existing allele are brought into the allele dialog, the previous synonyms aren't cleared. This is especially a problem for the copy and edit function.

I finally tracked down the problem and it's now fixed.  So in future allele synonyms won't accumulate if you edit existing alleles in genotypes.

Now I've fixed the bug I'll need to fix the sessions where this problem has occurred.  The easy solution is to clear the synonyms from each session that were loaded from Chado and just leave the synonyms that have been added.

**Comment by kimrutherford** [comment]
> rpb1-S5.S5A (this is incorrect, which session was it added?)
> ...

I think this is the session that has the problem synonyms:
https://curation.pombase.org/pombe/curs/67f8ea3e5c1c1bfc/genotype_manage/ro

Sorry it took so long to track down.  I was focused on the Canto bug which I thought was causing the problem synonyms.  I should have just looked in the Canto database.

**Comment by ValWood** [comment]
excellent!
glad you found it,

**Comment by kimrutherford** [comment]
Moved to curation tracker:
 - pombase/curation#3775
