### ISSUE TITLE
legacy GO error, not oading, not reported

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1193]
Line in legacy GO not loading but has no warning:

PomBase	SPCC1884.02	nic1		GO:0005887	PMID:10748059	TAS		C	XXXX	SPCC757.01	protein	taxon:4896	20060206	PomBase		

I think this is because it has a with field populated and it shouldn't, but there is no warning in here:
https://curation.pombase.org/dumps/latest_build/logs/log.2024-07-25-21-51-08.legacy_go_from_contigs

(I will fix it once  it appears in the log, but leave it for now for checking)

**Comment by kimrutherford** [comment]
Is this not it?:

![image](https://github.com/user-attachments/assets/19edb7f4-7067-4932-b056-a59be9cef500)

**Comment by ValWood** [comment]
So it is! I got confused because it does not show up as an existing annotation  for the publication  session in Canto  (I think it should, even though we can't make TAS/NAS etc in Canto it would be good to see them)

**Comment by kimrutherford** [comment]
It turns out that Canto is configured to not show TAS annotation from Chado.  It's been that way since 2012.

TAS is the only evidence code that is configured to be ignored.

**Comment by ValWood** [comment]
Odd that I haven't noticed before, but we don't make many TAS from pombe papers...

**Comment by kimrutherford** [comment]
Should we remove the configuration so that TAS annotations are shown too?

**Comment by ValWood** [comment]
Yes I think that would be helpful
