### ISSUE TITLE
Load fails if a term in GO-CAM data is obsolete

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1199]
```
loading GO-CAM ID to term ID mapping
can't find term for GO:0006490
```
:arrow_right:  :skull:

**Comment by kimrutherford** [comment]
That's fixed now.  It will produce a warning rather than killing the whole load.

**Comment by ValWood** [comment]
Oddly when I search Noctua with that term I don't find a model using it?

**Comment by ValWood** [comment]
Maybe it is now mapped over to the replace_by term?

**Comment by kimrutherford** [comment]
> Oddly when I search Noctua with that term I don't find a model using it?

I couldn't see the term either.  I assumed you'd fixed it.  But automatically using the replace_by term would make sense.
