### ISSUE TITLE
delete coiled-coil from contigs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1201]
coiled_coil
--
  | alm1, alp7, atg11, atg17, atg38, blt1, ccq1, cgr1, csm1, ctr1, cut7, cwf25, cyp8, dbl1, ede1, efg1, eis1, get1, grp1, grp2, jnm1, ker1, klp2, klp3, klp5, klp6, klp8, klp9, kms1, kms2, kri1, luc7, mad1, mcp1, mcp3, mcp4, mcp6, mcp7, mdn1, meu1, meu13, meu14, meu23, mis17, miy1, msd1, mto1, mto2, ndc80, new22, nod1, nro1, nst1, nuf2, num1, nup211, opa3, pcp1, pdc1, pkl1, pnn1, pos1, ppc89, psm1, psm3, rad60, rdl1, red1, rmn1, rng8, rng9, rpa34, rqc1, rss1, sfr1, sid4, sim4, snu66, spa2, spc24, spc7, spo15, ssr4, sst6, tea2, tea3, tho5, tho7, tmf1, ucp8, uso1, vps38, yaf9, SPAC29A4.06c, SPAC2C4.09, SPAC3H1.08c, SPAC6G10.10c, SPAC9.11, SPAC9E9.04, SPBC1703.09, SPBC23G7.14, SPBC36.11, SPBC713.09, SPBP4H10.14c, SPCC24B10.03, SPCC297.06c

[coiled_coil](https://www.pombase.org/term/SO:0001080)
[alm1](https://www.pombase.org/gene/SPAC1486.04c), [alp7](https://www.pombase.org/gene/SPAC890.02c), [atg11](https://www.pombase.org/gene/SPAC7D4.04), [atg17](https://www.pombase.org/gene/SPAC10F6.11c), [atg38](https://www.pombase.org/gene/SPBC660.08), [blt1](https://www.pombase.org/gene/SPBC1A4.05), [ccq1](https://www.pombase.org/gene/SPCC188.07), [cgr1](https://www.pombase.org/gene/SPAC1556.05c), [csm1](https://www.pombase.org/gene/SPAC11E3.03), [ctr1](https://www.pombase.org/gene/SPAC140.04), [cut7](https://www.pombase.org/gene/SPAC25G10.07c), [cwf25](https://www.pombase.org/gene/SPBC146.05c), [cyp8](https://www.pombase.org/gene/SPAC21E11.05c), [dbl1](https://www.pombase.org/gene/SPCC2H8.05c), [ede1](https://www.pombase.org/gene/SPBC800.10c), [efg1](https://www.pombase.org/gene/SPAC12G12.02), [eis1](https://www.pombase.org/gene/SPCC63.14), [get1](https://www.pombase.org/gene/SPBC543.10), [grp1](https://www.pombase.org/gene/SPAC27D7.02c), [grp2](https://www.pombase.org/gene/SPBC365.11), [jnm1](https://www.pombase.org/gene/SPCC11E10.03), [ker1](https://www.pombase.org/gene/SPBC1718.03), [klp2](https://www.pombase.org/gene/SPAC664.10), [klp3](https://www.pombase.org/gene/SPAC1834.07), [klp5](https://www.pombase.org/gene/SPBC2F12.13), [klp6](https://www.pombase.org/gene/SPBC1685.15c), [klp8](https://www.pombase.org/gene/SPAC144.14), [klp9](https://www.pombase.org/gene/SPBC15D4.01c), [kms1](https://www.pombase.org/gene/SPAC3A11.05c), [kms2](https://www.pombase.org/gene/SPBC947.12), [kri1](https://www.pombase.org/gene/SPAC22G7.05), [luc7](https://www.pombase.org/gene/SPCC16A11.13), [mad1](https://www.pombase.org/gene/SPBC3D6.04c), [mcp1](https://www.pombase.org/gene/SPAC1687.10), [mcp3](https://www.pombase.org/gene/SPAC1006.04c), [mcp4](https://www.pombase.org/gene/SPBC16E9.08), [mcp6](https://www.pombase.org/gene/SPBC582.06c), [mcp7](https://www.pombase.org/gene/SPAC13A11.03), [mdn1](https://www.pombase.org/gene/SPCC737.08), [meu1](https://www.pombase.org/gene/SPAC1556.06), [meu13](https://www.pombase.org/gene/SPAC222.15), [meu14](https://www.pombase.org/gene/SPBC1347.03), [meu23](https://www.pombase.org/gene/SPCC613.11c), [mis17](https://www.pombase.org/gene/SPBC21.01), [miy1](https://www.pombase.org/gene/SPAC12G12.11c), [msd1](https://www.pombase.org/gene/SPBC13E7.06), [mto1](https://www.pombase.org/gene/SPCC417.07c), [mto2](https://www.pombase.org/gene/SPBC902.06), [ndc80](https://www.pombase.org/gene/SPBC11C11.03), [new22](https://www.pombase.org/gene/SPCP20C8.04), [nod1](https://www.pombase.org/gene/SPAC12B10.10), [nro1](https://www.pombase.org/gene/SPCC4B3.07), [nst1](https://www.pombase.org/gene/SPAC29E6.10c), [nuf2](https://www.pombase.org/gene/SPAC27F1.04c), [num1](https://www.pombase.org/gene/SPBC216.02), [nup211](https://www.pombase.org/gene/SPCC162.08c), [opa3](https://www.pombase.org/gene/SPBC1703.11), [pcp1](https://www.pombase.org/gene/SPAC6G9.06c), [pdc1](https://www.pombase.org/gene/SPAC20G4.08), [pkl1](https://www.pombase.org/gene/SPAC3A11.14c), [pnn1](https://www.pombase.org/gene/SPAC26F1.02), [pos1](https://www.pombase.org/gene/SPAC16E8.08), [ppc89](https://www.pombase.org/gene/SPAC4H3.11c), [psm1](https://www.pombase.org/gene/SPBC29A10.04), [psm3](https://www.pombase.org/gene/SPAC10F6.09c), [rad60](https://www.pombase.org/gene/SPBC1921.02), [rdl1](https://www.pombase.org/gene/SPAC17H9.03c), [red1](https://www.pombase.org/gene/SPAC1006.03c), [rmn1](https://www.pombase.org/gene/SPBC902.04), [rng8](https://www.pombase.org/gene/SPAC4H3.14c), [rng9](https://www.pombase.org/gene/SPBP8B7.02), [rpa34](https://www.pombase.org/gene/SPBC11G11.05), [rqc1](https://www.pombase.org/gene/SPAC1142.01), [rss1](https://www.pombase.org/gene/SPAC4H3.06), [sfr1](https://www.pombase.org/gene/SPBC28F2.07), [sid4](https://www.pombase.org/gene/SPBC244.01c), [sim4](https://www.pombase.org/gene/SPBC18E5.03c), [snu66](https://www.pombase.org/gene/SPAC167.03c), [spa2](https://www.pombase.org/gene/SPAC3G9.05), [spc24](https://www.pombase.org/gene/SPBC336.08), [spc7](https://www.pombase.org/gene/SPCC1020.02), [spo15](https://www.pombase.org/gene/SPAC1F3.06c), [ssr4](https://www.pombase.org/gene/SPBP23A10.05), [sst6](https://www.pombase.org/gene/SPAC11H11.01), [tea2](https://www.pombase.org/gene/SPBC1604.20c), [tea3](https://www.pombase.org/gene/SPAC6G10.02c), [tho5](https://www.pombase.org/gene/SPBC577.04), [tho7](https://www.pombase.org/gene/SPCC24B10.11c), [tmf1](https://www.pombase.org/gene/SPBC365.07c), [ucp8](https://www.pombase.org/gene/SPBC83.01), [uso1](https://www.pombase.org/gene/SPAC29E6.03c), [vps38](https://www.pombase.org/gene/SPBC18H10.19), [yaf9](https://www.pombase.org/gene/SPAC17G8.07), [SPAC29A4.06c](https://www.pombase.org/gene/SPAC29A4.06c), [SPAC2C4.09](https://www.pombase.org/gene/SPAC2C4.09), [SPAC3H1.08c](https://www.pombase.org/gene/SPAC3H1.08c), [SPAC6G10.10c](https://www.pombase.org/gene/SPAC6G10.10c), [SPAC9.11](https://www.pombase.org/gene/SPAC9.11), [SPAC9E9.04](https://www.pombase.org/gene/SPAC9E9.04), [SPBC1703.09](https://www.pombase.org/gene/SPBC1703.09), [SPBC23G7.14](https://www.pombase.org/gene/SPBC23G7.14), [SPBC36.11](https://www.pombase.org/gene/SPBC36.11), [SPBC713.09](https://www.pombase.org/gene/SPBC713.09), [SPBP4H10.14c](https://www.pombase.org/gene/SPBP4H10.14c), [SPCC24B10.03](https://www.pombase.org/gene/SPCC24B10.03), [SPCC297.06c](https://www.pombase.org/gene/SPCC297.06c)

**Comment by kimrutherford** [comment]
Are these from the contigs?  Can you give me an example of what the `/controlled_curation` looks like?

**Comment by ValWood** [comment]
They don't seem to be in the contigs, but they are on the gene pages  in the "protein domains and properties" section so I don't know where they are!

And definitely independent of these:
https://www.pombase.org/results/from/id/94f24d84-a998-4d7d-8cec-4690842d4372
which don't appear in the "protein domains and properties" section of the gene pages!

**Comment by ValWood** [comment]
Got it. They are already migrated (In the SO file) manual_so_term_annotations.tsv:SPBC36.11		SO:0001080	ECO:0000044			region	

We should just remove them because it is such a small incomplete  subset, they are already  displayed in the viewer with coordinates.

**Comment by kimrutherford** [comment]
> We should just remove them because it is such a small incomplete subset,

We'll need to remove this option from the query builder to:

![image](https://github.com/user-attachments/assets/d05b06d9-3859-4ff3-9e0b-25e8bd52632a)

**Comment by ValWood** [comment]
the seems to be powerd by the data from InterPro


972 |   | coiled_coils_count(≥1)
so its OK

**Comment by ValWood** [comment]
The stuff above is just some random shit we created way back when

**Comment by ValWood** [comment]
It's a bit weird though.

The query builder gives 
https://www.pombase.org/results/from/id/94f24d84-a998-4d7d-8cec-4690842d4372

the random shit gives
https://www.pombase.org/results/from/id/b8e37320-1572-426f-809b-712a68e3b5d8

I expected most of the random shit to be covered by the query and  100 are.

of the  6 that aren't we annotated low complexity regions as coils (sometimes they are)

**Comment by kimrutherford** [comment]
> the seems to be powerd by the data from InterPro

Ah, I forgot about that.   The manually annotated coiled-coils aren't included in the query builder.  Whoops.

So should we still remove the ones in the manual SO file?

**Comment by ValWood** [comment]
Yes, the manual ones are either a). redundant (100)  or b) incorrect (6)

**Comment by kimrutherford** [comment]
I've removed them.
