### ISSUE TITLE
PMID mentioning gene not shown in leterature section

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1204]
https://pubmed.ncbi.nlm.nih.gov/?cmd=Search&term=(SPAC22H10.11c+OR+crf1+OR+ifh1)+AND+(pombe+OR+fission+yeast)

this seach retrieves 
PMID: 31431504

but this publication doesn't appear in the literature list.

I thought we changed things recently so that the literature list also included the "uncurated" appears that mentioned a specific gene? (I have been using this to look for uncurated papers, and I was wondering why our coverage looked so good!).

**Comment by kimrutherford** [comment]
> this publication doesn't appear in the literature list.

Which literature list do you mean?

>  I thought we changed things recently so that the literature list also included the "uncurated" appears that mentioned a specific gene? 

We now find genes in the keywords.  Is that what you're thinking of?

**Comment by ValWood** [comment]
The literature at the bottom of the gene page. Maybe it wasn't implemented. I'll check if there is a ticket for it....

**Comment by kimrutherford** [comment]
The code only checks for genes in the PubMed keywords.  PMID:31431504 doesn't have any.

**Comment by ValWood** [comment]
It's this ticket:
https://github.com/pombase/pombase-chado/issues/1038

We can discuss next week if it doesn't make sense. I think we both got sidetracked from the original intent of the ticket!

**Comment by kimrutherford** [comment]
> It's this ticket:
> https://github.com/pombase/pombase-chado/issues/1038

That's implemented and working as far as I know.

**Comment by ValWood** [comment]
I think I explained badly what was needed.  We wanted all papers mentioning a gene to appear in the literature list  on the gene pages even if not curated.  I don't think that is happening?

**Comment by ValWood** [comment]
> The code only checks for genes in the PubMed keywords. PMID:31431504 doesn't have any.

Ah OK I see. Why don't authors use keywords????? especially for the gene of focus...

**Comment by kimrutherford** [comment]
> I think I explained badly what was needed. We wanted all papers mentioning a gene to appear in the literature list on the gene pages even if not curated. I don't think that is happening?

The code only checks the keywords.

**Comment by ValWood** [comment]
OK, we will miss some.
