### ISSUE TITLE
A question for the review I'm writing

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1207]
How many  unique annotations does cdc2 have (and how many total)

also what is the number for our most annotated gene (is that sty1 I can't remember?)

**Comment by kimrutherford** [comment]
> How many unique annotations does cdc2 have

Aren't all annotations unique?

**Comment by ValWood** [comment]
Sorry, detail! I mean unique at the term level (can have different source and evidence)

**Comment by kimrutherford** [comment]
> also what is the number for our most annotated gene (is that sty1 I can't remember?)

Do you just want to count ontology annotations and ignore interactions and orthologs for finding the most annotated gene?

> Sorry, detail! I mean unique at the term level (can have different source and evidence)

Should we include annotations from non-PomBase sources?

Do you want to include all of these CVs?:

  - PSI-MOD
  - PomBase gene characterisation status
  - PomGeneExProt
  - PomGeneExRNA
  - biological_process
  - cellular_component
  - complementation
  - molecular_function
  - name_description
  - pombase_family_or_domain
  - species_dist

And count any phenotype terms where an allele of cdc2 is part of the genotype?

**Comment by ValWood** [comment]
yes for this question everything because it is to illustrate what needs to be summarized (I.e it's source independent)

**Comment by kimrutherford** [comment]
>  I mean unique at the term level (can have different source and evidence)

How should that work for interactions and orthologs?

**Comment by ValWood** [comment]
each interaction, and each ortholog annotation can be counted because it is potentially something that could be referred to in the summary depending how the summary is crafted

**Comment by kimrutherford** [comment]
cdc2 has 427 ontology annotations.  88 distinct terms.

genotypes with cdc2 have 972 annotations.  242 distinct terms.

cdc2 has 282 interactions and 5 ortholog annotations

So 1686 total annotations and 617 unique annotations if we ignore the details for ontology annotations.

**Comment by ValWood** [comment]
wow! I don't even think that's our highest

**Comment by kimrutherford** [comment]
Do you need any other numbers?

**Comment by ValWood** [comment]
Out of curiosity, do we know whcih gene has the most ?  If it takes more than 10 mins I don't need to know (just wondering if the number is much higher, but I don't think it is). This example will do just fine,

**Comment by kimrutherford** [comment]
> Out of curiosity, do we know which gene has the most?

From quick look it's probably fft3 / SPAC25A8.01c because of a zillion genetic interactions.

**Comment by ValWood** [comment]
oh yeah, not so useful . I think cdc2 is close to the top. it's fine.

**Comment by ValWood** [comment]
> So 1686 total annotations and 617 unique annotations if we ignore the details for ontology annotations.

What do you mean by "details" here?
Doe this include extensions making different annotations?

**Comment by kimrutherford** [comment]
Sorry that was unclear.  I meant ignore the details so they are unique at the term level.

**Comment by ValWood** [comment]
i.e publication and evidence?

**Comment by kimrutherford** [comment]
I followed what you said here:

> Sorry, detail! I mean unique at the term level (can have different source and evidence)

So I counted the annotations that were unique at the term level, ignoring the other details.  Should an annotation count as unique if the extension is different?  Sorry, I didn't think about that.

When counting I also ignored conditions.

**Comment by ValWood** [comment]
It should count as unique if the extension is different.

probably for conditions not

**Comment by ValWood** [comment]
Hi @kimrutherford  no hurry but could you provide this number 
classing different extensions and different annotations (essentially they are unique annotations because the extension _extends_ the term

**Comment by kimrutherford** [comment]
> Hi @kimrutherford no hurry but could you provide this number
> classing different extensions and different annotations (essentially they are unique annotations because the extension extends the term

That's in this comment: https://github.com/pombase/pombase-chado/issues/1207#issuecomment-2297703945

> So **1686 total annotations** and 617 unique annotations if we ignore the details for ontology annotations.

**Comment by ValWood** [comment]
Ah ok so "if we ignore the details for ontology annotations." means you observe extensions but ignore different source/evidence (if so this is perfect)
