### ISSUE TITLE
Move SO annotations out of contig files

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1208]
Move to `pombe-embl/supporting_files/manual_so_term_annotations.tsv`.

See:
  - https://github.com/pombase/website/issues/2199

-------------------------------

Edit; Note to self:

Query all SO terms with evidence, date, qualifier and residue:
```sql
SELECT f.uniquename,

  db.name || ':' || x.accession AS termid,

  t.name AS term_name,

  (SELECT value FROM feature_cvtermprop p
   WHERE p.feature_cvterm_id = fc.feature_cvterm_id
     AND p.type_id IN (SELECT cvterm_id FROM cvterm WHERE name = 'evidence')
   LIMIT 1)
  AS evidence,

  (SELECT value FROM feature_cvtermprop p
   WHERE p.feature_cvterm_id = fc.feature_cvterm_id
     AND p.type_id IN (SELECT cvterm_id FROM cvterm
        WHERE name = 'residue')
   LIMIT 1)
  AS residue,

  array_to_string(array (SELECT value
          FROM feature_cvtermprop p
          WHERE p.feature_cvterm_id = fc.feature_cvterm_id
            AND p.type_id IN (SELECT cvterm_id FROM cvterm WHERE name = 'qualifier')), '|')
  AS qualifier,

  (SELECT value FROM feature_cvtermprop p
   WHERE p.feature_cvterm_id = fc.feature_cvterm_id
     AND p.type_id IN (SELECT cvterm_id FROM cvterm WHERE name = 'date')
   LIMIT 1)
  AS date,

  pub.uniquename AS pmid

FROM feature_cvterm fc
JOIN feature f ON f.feature_id = fc.feature_id
JOIN cvterm t ON t.cvterm_id = fc.cvterm_id
JOIN dbxref x ON t.dbxref_id = x.dbxref_id
JOIN db ON db.db_id = x.db_id
JOIN cv ON cv.cv_id = t.cv_id
JOIN pub ON pub.pub_id = fc.pub_id
WHERE cv.name = 'sequence';
```

-----------------------

Edit 2

Perl to remove SO annotations from the contig files:
```sh
(for i in  *.contig                                     
do
perl -ne 'BEGIN { $ft = ""; $in = 0; } if ($ft && !$in) { warn "$ft\n"; $ft = "" } if (/controlled_curation="term=sequence feature/) { $in = 1; } if ($in) { s/^FT\s+//; chomp $_; $ft .= "$_ "; } else { print }; if ($in && /"$/) { $in = 0 }' $i > $i.new && mv $i.new $i
done) 2> sequence_features.txt
```

**Comment by kimrutherford** [comment]
Hi @ValWood 

Before doing the move I wanted to double check a current special case.  If an annotation has `qualifier=predicted` then that gets turned into evidence code ISS in Chado.  It has been doing that forever.  Should we put ISS in the TSV file?

**Comment by kimrutherford** [comment]
@ValWood 

Do we need to tidy up this annotation on SPAC22A12.08c / crd1 ?

![image](https://github.com/user-attachments/assets/68b6790e-39a5-43a4-869d-5c2126f62590)

**Comment by kimrutherford** [comment]
> Do we need to tidy up this annotation on SPAC22A12.08c / crd1 ?

I decided it's just as easy to do this in the TSV file so I've now moved the SO annotations from the contig files into: `pombe-embl/supporting_files/manual_so_term_annotations.tsv`

I'll check the load on Wednesday morning,

**Comment by ValWood** [comment]
I tideied the annotations on crd1 (removed redundant)

**Comment by ValWood** [comment]
>Should we put ISS in the TSV file?

the equivalent ECO, yep (I think you have...)

**Comment by kimrutherford** [comment]
> the equivalent ECO, yep (I think you have...)

I have the GO evidence codes in the file for the SO annotations I've just moved.  But I'll change them to ECO.

**Comment by kimrutherford** [comment]
It looks like that worked OK.  Example: https://www.pombase.org/term/SO:0002159
