### ISSUE TITLE
Make annotations in Chado for some of the data from UniProt

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1210]
From:
 - https://github.com/pombase/pombase-chado/issues/1171#issuecomment-2268296118

For some of the data from UniProt (`pombe-embl/external_data/uniprot_data_from_api.tsv`) we should create annotations as well as showing in the protein feature view. 

Features to create:

 - glycosylation, add as modification, "glycosylated residue" ([MOD:00693](https://www.pombase.org/term/MOD:00693))
but only if we don't have it from the same source.

 - disulphide bond, add as "disulfide crosslinked residues" ([MOD:00689](https://www.pombase.org/term/MOD:00689))
if we don't have it from the same source (we don't have many of these curated)

**Comment by kimrutherford** [comment]
> I think I've got it a bit wrong. I've included the residues but some of the protein sequences in UniProt are out of date so the residue positions are probably wrong. I was hoping to get this done today but I've got to re-work things a bit to only add the residues if the sequence is the same in UniProt.

I got the fix in before the load started so the glycosylation site annotations are on pombase.org now:
https://www.pombase.org/term/MOD:00693

I'll add disulphide bond annotations next.

**Comment by kimrutherford** [comment]
> I'll add disulphide bond annotations next.

Looks like this that's working.  Perhaps they shouldn't be called "modified residue" for cross links?
 
![image](https://github.com/user-attachments/assets/adf164d2-6643-4b24-a537-1619fbd903ff)

**Comment by ValWood** [comment]
Looks good, it would be better if it said residues, but its such a small issue i think its fine unless it is a really quick fix.

**Comment by kimrutherford** [comment]
> it would be better if it said residues, but its such a small issue i think its fine unless it is a really quick fix.

It's just configuration, so no problem.

**Comment by kimrutherford** [comment]
All done.  We can open new issues if there are other annotations to create from the UniProt data.
