### ISSUE TITLE
more paralogs, I missed

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1214]
My  suggested heuristic for generating the paralogs had a small flaw. It would miss the proteins which had duplicated,  and were not species specific, but had been lost from S, cerevisiae.

These are the ones that I could get from the human orthologs. Can you get the pombe orthologs for these and add?

   2 ACAP1,ACAP2,ACAP3
   2 ACLY
   2 ADD1,ADD2,ADD3
   2 AOC1,AOC2,AOC3
   2 ARK2C
   2 CBX1,CBX3,CBX5
   2 COMT
   2 DHDH
   2 DPEP1,DPEP2,DPEP3
   2 EIF2AK2,EIF2AK3
   2 GEMIN2
   2 KDM1A,KDM1B
   2 MFSD11
   2 MTF2,PHF1,PHF19
   2 MTRR
   2 PIPOX
   2 RBPJ,RBPJL
   2 RCHY1
   2 SREBF1,SREBF2
   2 SYNE4
   2 TERF1,TERF2
   2 TSC2
   3 AGMAT
   3 GAA,MGAM,SI
   3 TUT4,TUT7 

I will need to think of another way to create paralogs for the protein which have duplicates, and are conserved in fungi only but have no S. cerevisiae orthologs. I will probably need to do these manually so I hope there aren't too many....

**Comment by kimrutherford** [comment]
I think I'll cheat and use the ortholog mapper.  :-)

---------------------

![image](https://github.com/user-attachments/assets/f28ce8e4-9da8-4bd7-a0d7-eee28c7a5763)

-----------------------------

![image](https://github.com/user-attachments/assets/f9364e5b-b52c-41ba-bd76-1ddcd1efbc5d)

**Comment by kimrutherford** [comment]
> Can you get the pombe orthologs for these and add?

Should we add them to the contigs or create a new file `pombe-embl/supporting_files/manual_paralogs.tsv`?

**Comment by kimrutherford** [comment]
Here are the paralog groups using pombe IDs:
```
SPAC1039.11c,SPAC30D11.01c,SPAPB24D3.10c
SPAC11D3.09,SPAPB24D3.03,SPBC8E4.03
SPAC139.04c,SPBC354.15
SPAC13G7.10,SPAC16A10.07c
SPAC1783.01,SPBC12C2.03c
SPAC17H9.01,SPAC19D5.03,SPBC1685.06
SPAC18B11.11,SPAC630.13c
SPAC19B12.12c,SPAPB17E12.02
SPAC20G4.03c,SPAC222.07c
SPAC22A12.16,SPBC1703.07
SPAC23E2.02,SPBC146.09c
SPAC26A3.10,SPBC17G9.08c
SPAC2E1P3.04,SPBC1289.16c
SPAC2F3.16,SPBC18H10.09
SPAC30D11.08c,SPCC4G3.07c
SPAC3A11.05c,SPBC947.12
SPAC3A11.10c,SPCC965.12
SPAC513.06c,SPACUNK4.17
SPAC664.01c,SPBC16C6.10
SPAC6F6.04c,SPAC922.05c
SPBC119.03,SPBPB21E7.04c
SPBC1289.14,SPBC359.06
SPBC19C2.09,SPBC354.05c
SPBP4H10.07,SPCC4G3.12c
SPCC1223.13,SPCC736.08
```

**Comment by ValWood** [comment]
Where are the others?

Should we add them to the contigs or create a new file pombe-embl/supporting_files/manual_paralogs.tsv?

**Comment by ValWood** [comment]
I would pull them all out into a paralogs file.
That will also help when I come to fill in the remaining gaps, and fits with the plan to remove data from the contigs

**Comment by kimrutherford** [comment]
Hi Val.

I've pulled the manual paralogs out of the contigs and noticed that some of the paralogs in your new list are already annotated in the contigs and are on the gene pages.  I'm reporting these in case you need to double check anything:

|pombe|human|
|--|--|
|SPAC1039.11c,SPAC30D11.01c,SPAPB24D3.10c|  GAA,MGAM,SI|
|SPAC11D3.09,SPAPB24D3.03,SPBC8E4.03| AGMAT|
|SPAC1783.01,SPBC12C2.03c| MTRR|
|SPAC18B11.11,SPAC630.13c| TSC2 |
|SPAC26A3.10,SPBC17G9.08c| ACAP1,ACAP2,ACAP3|
|SPAC30D11.08c,SPCC4G3.07c| MTF2,PHF1,PHF19|
|SPBP4H10.07,SPCC4G3.12c| ARK2C|

**Comment by ValWood** [comment]
Hi KIm, could you provide me a list of "all genes with paralogs" as my starting point (I think the ones above are OK)

NO hurry, I wont do this until I get back

**Comment by ValWood** [comment]
> Would that be of any use as a commonly used query?

yes I think so!

**Comment by kimrutherford** [comment]
> Would that be of any use as a commonly used query?

Er, turns out we already have one.  I have no memory of this.  :-)

![image](https://github.com/user-attachments/assets/6e3c8030-8ece-45ed-b4c1-3e738fe8e66d)

**Comment by ValWood** [comment]
wow, I never saw that! or I forgot too!

**Comment by ValWood** [comment]
https://www.pombase.org/gene/SPAC4F8.07c
and
https://www.pombase.org/gene/SPAC4F8.07c
should be paralogs of each other because they are both orthologs of

 cerevisiae	GLK1 &  cerevisiae	EMI2

Can you find any more like that (I have 1000 to review so I'd like to reduce further!)

**Comment by ValWood** [comment]
Actually I only have 337 to revive, 
but I wonder if we middes these "many to many" ones

**Comment by ValWood** [comment]
yep
https://www.pombase.org/gene/SPAC24H6.04

**Comment by kimrutherford** [comment]
> wow, I never saw that! or I forgot too!

Here's the issue:
 - https://github.com/pombase/website/issues/2215

We both forgot.  :-)

**Comment by kimrutherford** [comment]
> should be paralogs of each other because they are both orthologs of
> cerevisiae GLK1 & cerevisiae EMI2

SPAC24H6.04 isn't an ortholog of those genes?

**Comment by ValWood** [comment]
yep ignore!

**Comment by ValWood** [comment]
I'll open a ticket on the curation tracker to proceed
