### ISSUE TITLE
Attempt to install and run InterProScan

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1218]
From:
  - https://github.com/pombase/pombase-chado/issues/52#issuecomment-2331756653

Val:
> I mailed Interpro to ask if this is possible, but now I started worrying that we have a lot of features from intoPro that incorrect coordinates based on the current Pase sequences (because they are based on UniProt) i.e. everything that has any features does have coordinate changes.
> This will include InterPro domains but also the coil-coil etc. How much hassle would it be, instead of updating with every InterPro release, to run InterProScan locally a couple of times a year ?
> I would rather the features were accurate coordinates, but maybe lagging a little bit behind InterPro in content ( because there is never too much new stuff for pombe in a release)

Kim:
> Last time I tried to install InterProScan it was too hard and I failed. That was a long time ago though and they now provide a helpful Docker image. I'll give it a go. There will be a bit of downstream work because the output format of InterProScan isn't the same as the XML file from InterPro.

**Comment by kimrutherford** [comment]
InterProScan is running now on oliver1 so apologies if Canto or JaponicusDB are a little slow for the next day (or two/three?).

**Comment by ValWood** [comment]
Wow, it takes that long, phew!

**Comment by kimrutherford** [comment]
I vastly overestimated how long it would take.  It's just finished.  :-)

The documentation said:
> InterProScan is a computationally expensive program, sometimes taking a couple of minutes to characterise a single sequence.

so I assumed it would take many hours.

One thing that helps the speed is that if the sequence matches something already in InterPro, it just uses those results rather than re-calculating.  That seems to have helped a lot.

The next task is parsing the output.  It's a TSV file which is helpful.  Here's a sample:

| Accession | MD5 | Length | Analysis | Signature_accession | Signature_description | Start | Stop | Score | Status | Date | InterPro_annotations_accession | InterPro_annotations_description | GO_annotations | Pathway_annotations |
|--------------------|--------------------|-----|-----------------|--------------------|--------------------|-----|-----|--------------|----|------------|--------------------|--------------------|--------------------|--------------------|
|SPAC13G6.15c.1:pep|3e384f1f8cb0c23464a589559bd6892c|163  |PANTHER          |PTHR10300           |CALCIPRESSIN        |7    |153  |6.8E-18     |T   |26-09-2024|IPR006931           |Calcipressin        |-                  |-                  |
|SPAC13G6.15c.1:pep|3e384f1f8cb0c23464a589559bd6892c|163  |Pfam             |PF04847             |Calcipressin        |6    |143  |2.4E-14     |T   |26-09-2024|IPR006931           |Calcipressin        |-                  |-                  |
|SPBC56F2.10c.1:pep|1348925e1231a87b6524f7ef1369cece|322  |Gene3D           |G3DSA:3.90.550.10|Spore Coat Polysaccharide Biosynthesis Protein SpsA; Chain A|43   |318  |1.6E-36     |T   |26-09-2024|IPR029044           |Nucleotide-diphospho-sugar transferases|-                  |-                  |
|SPBC56F2.10c.1:pep|1348925e1231a87b6524f7ef1369cece|322  |CDD              |cd04188             |DPG_synthase       |66   |287  |3.90202E-104|T   |26-09-2024|IPR035518           |Dolichyl-phosphate beta-glucosyltransferase|-                  |-                  |
|SPBC56F2.10c.1:pep|1348925e1231a87b6524f7ef1369cece|322  |SUPERFAMILY      |SSF53448            |Nucleotide-diphospho-sugar transferases|57   |313  |9.38E-37    |T   |26-09-2024|IPR029044           |Nucleotide-diphospho-sugar transferases|-                  |-                  |
|SPBC1718.07c.1:pep|de8b11899e677a78f30bed4d3f186adb|404  |ProSiteProfiles  |PS50103             |Zinc finger C3H1-type profile.|326  |354  |17.253035    |T   |26-09-2024|IPR000571           |Zinc finger, CCCH-type|-                  |-                  |

**Comment by kimrutherford** [comment]
I've now had a better look at the results from running InterProScan manually.  We mostly get the same domains but the descriptions vary a bit.  Apart from that, I think the results from InterProScan will be fine.

The only thing missing is the low complexity regions.  Maybe there is another tool we could use for that?  I haven't investigated yet.

The predictions for disordered regions will change, possibly by a lot, because it's a different source/method.

As an example for changing descriptions, for [SPBC2D10.14c](https://www.pombase.org/gene/SPBC2D10.14c) we get this from InterPro XML:
```
 cd01380     CDD     class V myosin, motor domain
 cd15474     CDD     cargo binding domain of fungal myosin V -like proteins
```

(that's what's on pombase.org)

but we get this from InterProScan:
```
 cd01380      CDD     MYSc_Myo5                           
 cd15474      CDD     Myo5p-like_CBD_fungal      
```

So it's the same hits, but a different (worse) descriptions.

In some cases though the description from InterProScan is better.  For example ([SPBC2D10.14c](https://www.pombase.org/gene/SPBC2D10.14c) again), we have this on the website from the InterPro XML:
```
PR00193   PRINTS      _____      IPR001609    Myosin head, motor domain 
````

From InterProScan we get:
```
PR00193    PRINTS    Myosin heavy chain signature    IPR001609    Myosin head, motor domain
```

So in this case we get a description for the PRINTS match where we currently don't have one.

**Comment by ValWood** [comment]
It seems that, for CDD, what we call "interPro name" is provided as "match name" (which seems to be the more human readable description)
https://www.pombase.org/gene/SPBC2D10.14c

Ideally both would be provided. I'll ask InterPro to comment.

**Comment by ValWood** [comment]
Actually, I got that wrong.
There is a short name, and a long name (the InterPro description is separate)
We want the long (human readable) name display, but it seems that for CDD the  short name is provided instead. 
Is that correct?

**Comment by kimrutherford** [comment]
As far as I can tell, for each match there's an ID (like "PTHR23065") and a match name (like "PROLINE-SERINE-THREONINE PHOSPHATASE INTERACTING PROTEIN 1") and then mostly there is an InterPro ID and an InterPro name.  Occasionally there is no match name and slightly more often there is no InterPro ID and name.

Example: https://www.pombase.org/gene/SPAC20G8.05c

What we see in the Protein families and domains table on the gene pages is more or less the same as the columns in the output of InterProtScan.

> We want the long (human readable) name display, but it seems that for CDD the short name is provided instead.
Is that correct?

Sorry, I don't know what CDD is.   I don't know if they provide short and long names.

**Comment by kimrutherford** [comment]
Here's my first attempt to parse and display the InterProScan output.  There is a bit of work to do:

![image](https://github.com/user-attachments/assets/8a5cf6a3-4f44-4c5f-90f3-af903e9ed8d0)

(This is SPBC16A3.15c /  nda2 - picked rather at random)

This is what we have currently for the same gene:

![image](https://github.com/user-attachments/assets/c9f8ec7d-1d53-4e02-9a0f-4e99371a54ef)

(Sorry the tracks aren't in the same order - that needs some work)

**Comment by ValWood** [comment]
iQ5
https://desktop.kmr.nz/gene/SPBC2D10.14c

**Comment by kimrutherford** [comment]
There is also information in the JSON output about discontinuous features like the SUPERFAMILY feature here:
pho84 / SPBC8E4.01c  https://www.ebi.ac.uk/interpro/protein/reviewed/O42885/

![image](https://github.com/user-attachments/assets/bcd152a5-35a3-4dd6-a242-f2e810e224e3)

We should be able to show those sort of features in the same way.  I haven't implemented that yet though.

https://desktop.kmr.nz/gene_protein_features/SPBC8E4.01c

**Comment by ValWood** [comment]
I think we should show the different types, it could be very useful.

Here 
https://desktop.kmr.nz/gene/SPBC1604.12 in the InterPro part
we do not display a consensus row (but it is in the table) . I don't know if you plan to include

**Comment by kimrutherford** [comment]
> we do not display a consensus row (but it is in the table) .

What do you mean by consensus row?

**Comment by kimrutherford** [comment]
> Like the MOBIDB-LITE row here, which I guess has everything?

Sorry, got it now.  I'll investigate that.  It does show on other gene pages.

**Comment by kimrutherford** [comment]
> Sorry, got it now. I'll investigate that. It does show on other gene pages.

I was imaging that it showed up on other pages.  :-)

It's fixed now.  You might need to shift-reload.

https://desktop.kmr.nz/gene/SPBC1604.12

**Comment by kimrutherford** [comment]
I've updated my desktop version so that is now only one coiled-coils track.  I've removed the Pfam coils version.  The whole site (on my desktop) including the query builder now use the coils features from InterProScan.

The two data sets are mostly similar.  There will be differences when the sequence has changed and in that case the InterProScan will be hopefully be more accurate.

As far as I can tell both datasets were generated with "COILS", which I think is this old, unmaintained software: https://bio.tools/coils

Oddly, there are some prediction differences so maybe the algorithm changed (improved?) at some point.  Two examples where the prediction covers more of the residues in the data from InterProScan:

pfd6:
 - https://www.pombase.org/gene/SPAC3A11.13
 - https://desktop.kmr.nz/gene/SPAC3A11.13

 cdc8:
 - https://www.pombase.org/gene/SPAC27F1.02c
 - https://desktop.kmr.nz/gene/SPAC27F1.02c

**Comment by kimrutherford** [comment]
I've now replaced the disordered regions from Pfam with the MobiDB predictions in the query buidler.  There are some quite big differences which will mean query results are different.

For example:

Pfam: https://www.pombase.org/gene/SPAC22F8.10c
![image](https://github.com/user-attachments/assets/36b6815d-fa17-4a02-ba0d-1094fe07fd86)

MobiDB: https://desktop.kmr.nz/gene/SPAC22F8.10c
![image](https://github.com/user-attachments/assets/ea60051e-a39f-46e0-b869-a9118e450dde)

**Comment by ValWood** [comment]
I'll explain that in the announcement...

**Comment by kimrutherford** [comment]
I have now removed the last use of the data downloaded from Pfam a couple of years ago.  The final step was to use segmasker to generate low complexity regions for the query builder and the protein feature viewers.

The results are mostly the same except for a few cases where the new regions overlap.

As an example, here's what we used to have for  pfl2 / SPAPB15E9.01c:
![image](https://github.com/user-attachments/assets/1454e7e3-3f23-4b67-995f-a243ef83c621)
https://www.pombase.org/gene_protein_features/SPAPB15E9.01c

We now have this:
![image](https://github.com/user-attachments/assets/f68bf89f-f026-4ce0-8a82-db8c6f85c2e5)
https://desktop.kmr.nz/gene_protein_features/SPAPB15E9.01c

That's not great for the query builder.  The query for percent of protein covered by low complexity produces the wrong result.

I think the solution is to merge overlapping regions.  I'll do that tomorrow.

**Comment by ValWood** [comment]
I agree to merge the overlapping features

**Comment by kimrutherford** [comment]
The current low complexity regions are a bit weird: https://www.pombase.org/gene_protein_features/SPAPB15E9.01c

There is no gap between most of the regions of that gene.  I think perhaps Pfam did some post-processing of the segmasker results to prevent overlaps.  I think they should have just merged them.

**Comment by kimrutherford** [comment]
> I agree to merge the overlapping features

I've done that and it's much better now:

![image](https://github.com/user-attachments/assets/b618b5b3-f548-44da-8bab-29f4b7151cdd)

**Comment by ValWood** [comment]
nice!

**Comment by kimrutherford** [comment]
I think we can close this.  The only remaining issue is the missing descriptions for the CDD matches.  I've asked about that:
  - ebi-pf-team/interproscan#385

**Comment by kimrutherford** [comment]
I'm running InterProScan for japonicus now.

The new `run_and_process_interpro.sh` script will process pombe and japonicus proteins. 
Documentation: https://github.com/pombase/pombase-chado/wiki/Updating-InterPro
