### ISSUE TITLE
Is GO updating?

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1219]
I noticed that 
attachment of GPI anchor to protein
is part_of 
phosphatidylinositol biosynthetic process (GO:0006661)
<img width="1305" alt="ticket, incorrect parents" src="https://github.com/user-attachments/assets/d6a5b912-a700-4a72-85a7-72b46efb2756">

but i fixed that in GO 3 weeks ago
https://github.com/geneontology/go-ontology/issues/28227
see screenshot (it was already not a child of PI metabolism)

**Comment by ValWood** [comment]
Its quite out of date
https://snapshot.geneontology.org/metadata/date.txt
should we use whatever QuickGO is using.
I will report that the daily snapshots aren't working.

v

**Comment by kimrutherford** [comment]
> I will report that the daily snapshots aren't working.

I don't think the snapshots are meant to be daily.  This is the daily build: https://ontology-build.geneontology.org/
We have talked about that but haven't tried it yet.

**Comment by kimrutherford** [comment]
> Ah I thought they were daily. So what are they?

The snapshots seems to be like beta testing of releases as far as I can tell.

The documentation is a bit out of date:

"If you have need to access the snapshot (daily) version, use /snapshot/ in the URL."
https://geneontology.org/docs/download-ontology/

**Comment by kimrutherford** [comment]
> This is the daily build: https://ontology-build.geneontology.org/

From an email from Pascale on March 21:

> I just checked with Seth, it’s OK to use these ‘daily versions’ – which we have now agreed to relabel ‘rolling builds’, as this more closely represents what the product is.
>
> This is no different from using snapshot – a build which is not QC’ed, not versioned, and not archived.
