### ISSUE TITLE
Add Lipidation data from UniProt

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1220]
From:
  - https://github.com/pombase/pombase-chado/issues/52#issuecomment-2331289445

---------------------------------------------

We can map all of the:

LIPID 485; /note="GPI-anchor amidated serine"; /evidence="ECO:0000255"
maps to N-seryl-glycosylphosphatidylinositolethanolamine
https://www.pombase.org/term/MOD:00171
(currently 1 in PomBase)

LIPID 202; /note="S-geranylgeranyl cysteine"; /evidence="ECO:0000250|UniProtKB:P62745"
maps to geranylgeranylated residue (All should be cysteine)
https://www.pombase.org/term/MOD:00441
(currently 2 in PomBase)

LIPID 404; /note="S-farnesyl cysteine"; /evidence="ECO:0000250"
maps to S-farnesyl-L-cysteine
https://www.pombase.org/term/MOD:00111
(currently 3 in PomBase)

LIPID 116; /note="Phosphatidylethanolamine amidated glycine"; /evidence="ECO:0000250|UniProtKB:P38182"
maps to N-glycyl-1-(phosphatidyl)ethanolamine
https://www.pombase.org/term/MOD:00351
(currently 1 in PomBase)

LIPID 2; /note="N-myristoyl glycine"; /evidence="ECO:0000269|PubMed:14722091"
to N-myristoylglycine
https://www.pombase.org/term/MOD:00068
(currently 21 in PomBase)

The remaining mappings

SPBC13G1.11; LIPID 193; /note="S-palmitoyl cysteine"; /evidence="ECO:0000250";
maps to https://www.pombase.org/term/MOD:00115
S-palmitoyl-L-cysteine

SPBPJ4664.02; LIPID 3944; /note="GPI-anchor amidated alanine"; /evidence="ECO:0000255"0250"
https://www.pombase.org/term/MOD:00818
glycosylphosphatidylinositolated residue
(MOD does not have further specificity)

SPAC212.08c; LIPID 96; /note="GPI-anchor amidated glycine"; /evidence="ECO:0000255"
https://www.pombase.org/term/MOD:00818
glycosylphosphatidylinositolated residue
(MOD does not have further specificity)

SPCC1322.10; LIPID 242; /note="GPI-like-anchor amidated asparagine"; /evidence="ECO:0000255"
Ignore

**Comment by kimrutherford** [comment]
I've updated `pombe-embl/external_data/uniprot_data_from_api.tsv` with the Lipidation data.

**Comment by kimrutherford** [comment]
That's all done for Wednesday morning.  The lipidation sites will appear in the protein feature viewer and each site will be a PSI-MOD annotation in Chado.

I'll close this once I've checked that it looks OK on pombase.org

**Comment by kimrutherford** [comment]
> note that these don't currently show in the modification viewer although they have positions

What do you mean by modification viewer?

**Comment by ValWood** [comment]
In the  modification track of the  protein feature viewer.
We can display these because we have the positional information.

**Comment by kimrutherford** [comment]
Currently they are in the lipidation sites track.  I'll merge them into the modification track.

**Comment by ValWood** [comment]
Right got it. Are  all of the others on the modification track?

**Comment by kimrutherford** [comment]
> Are all of the others on the modification track?

Do you mean the PomBase curated modifications?  They should all be there.

I haven't worked on the modifications from UniProt yet:
  - https://github.com/pombase/pombase-chado/issues/1216

**Comment by kimrutherford** [comment]
This is done.
