### ISSUE TITLE
can't locate these

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1221]
They aren't in my legacy localization file or the CAnto session.
Where else could they be? I would like to remove

mug170 | GO:0005737 | cytoplasm | IDA |   |  
opy1 | GO:0005737 | cytoplasm | IDA |   |  
SPBP8B7.26 | GO:0005737 | cytoplasm | IDA |   |  
mor2 | GO:0005737 | cytoplasm | IDA |   |  
mug113 | GO:0005737 | cytoplasm | IDA |   |  
SPAPB1A10.13 | GO:0005737 | cytoplasm | IDA |   |  
SPAPB17E12.09 | GO:0005737 | cytoplasm | IDA

<br class="Apple-interchange-newline">

**Comment by kimrutherford** [comment]
Some at least are in: `pombe-embl/supporting_files/legacy_go_annotations_from_contigs.gaf.tsv`

**Comment by ValWood** [comment]
I didn't check them all, the one I was specifically looking for was  opy1 SPCPB16A4.02c and I couldn't find that one. In the session I could see there were a number of IDA in "existing  annotation"  which is why I included the full list. I have no idea where these could be? (there are no IDAs in the legacy file). I thought they must be UniProt annotations, but they are definitely  PomBAse

**Comment by kimrutherford** [comment]
> the one I was specifically looking for was opy1 SPCPB16A4.02c

That one is there?:

```
PomBase SPCPB16A4.02c   opy1            GO:0005737      PMID:16823372   IDA             C       XXXX            protein taxon:4896      20080115     PomBase
```

> there are no IDAs in the legacy file

I can see lots?

**Comment by ValWood** [comment]
weird , when i search with
SPCPB16A4.02c i find only 2 HDA?

**Comment by ValWood** [comment]
and I still find no IDA

**Comment by ValWood** [comment]
The file we use is
GO_ORFeaome_localizations2.txt

**Comment by ValWood** [comment]
ah got it, its in thee old contig files, sorry, durr

**Comment by ValWood** [comment]
Ah hang on, are all the annotations from 
GO_ORFeaome_localizations2.txt
now in
pombe-embl/supporting_files/legacy_go_annotations_from_contigs.gaf.tsv

i didn't reilse that, I remove a lot of false positives from this dataset and copy them to

GO_ORFeaome_localizations2_deleted.txt

i have continued to do that. can we identify any annotatins in the 'deleted' file that ate still in legacy_go_annotations_from_contigs.gaf.tsv
and remove them?

Then we should achive 
GO_ORFeaome_localizations2.txt

**Comment by ValWood** [comment]
or we could remove all PMID:16823372
from legacy_go_annotations_from_contigs.gaf.tsv
and point bach to the old file? 
It might be good to keep this dataset in on file.

**Comment by ValWood** [comment]
ignore me there are only 10 annotations from PMID:16823372 in legacy_go_annotations_from_contigs.gaf.tsv
