### ISSUE TITLE
Odd non filtering cases

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1225]
https://www.pombase.org/gene/SPBC11G11.04
has a prediction for 
GO:0012505 | endomembrane system | IEA with ARBA00028953
but it is annotated to 
GO:0005801 | cis-Golgi network | IC with TRAPP complex
which has this parent (also applies to sec22)

also rpn9
https://www.pombase.org/gene/SPAC607.05
GO:0000502 | proteasome complex | IEA with ARBA00029017
but it is annotated to 
GO:0008541 | proteasome regulatory particle, lid subcomplex | IDA
which has this parent.
(also rpn12, rpn7)

I can't see any obvious reason whey these are not filtered (I.e recent ontology changes, or odd relationships)?
could you have a look to see if there is anything obvious?

**Comment by ValWood** [comment]
Another one
mrps16 https://www.pombase.org/gene/SPBC354.06

has IEA to cytoplasm, but his is in the ancestry

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005763

**Comment by ValWood** [comment]
https://www.pombase.org/gene/SPCC5E4.07 rpl2801
seems to be no longer annotate to cytoplasm, even though it is in the parentage
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0022626

**Comment by ValWood** [comment]
These are all component terms. I wonder if there have been some recent GO changes that we are picking up, but have not yet filtered through to QuickGO?

@pgaudet. Does this make any sense to you?

In summary, we do not  display IAEs if we already have annotation, but these IEAs are not filtered, implying some change in the ontology parentage?

**Comment by ValWood** [comment]
cox1
is picking up mitochondrion, even though we have mitochondrial inner membrane?
<img width="1146" alt="Screenshot 2024-09-26 at 10 30 14" src="https://github.com/user-attachments/assets/1794cd97-fb1f-476f-9b38-b5f7775bf4ae">

**Comment by kimrutherford** [comment]
It seems to have gone wrong when we switched to using the daily ontology build.  I haven't tracked down why yet.

**Comment by balhoff** [comment]
@kimrutherford very sorry about this! Trying to clean things up but not seeing all the ramifications. I put some of them back here: https://github.com/geneontology/go-ontology/pull/28995

**Comment by kimrutherford** [comment]
No problem Jim.  We expect a few bumps in the road using the daily build of the ontology.  :-)

>  I put some of them back here:

Thanks!  I'll watch out for those to appear back in the daily ontology build.

Val, I patched the Typedef definitions in a local copy of go-basic.obo and ran an out-of-band Chado and website update.  So I think the problems you found are fixed.

**Comment by ValWood** [comment]
Thanks for the speed. It wasn't major, but nice to fix.

**Comment by kimrutherford** [comment]
> I'll watch out for those to appear back in the daily ontology build.

The fix has come through to ontology-build.geneontology.org/ so we're back to daily updates.

Thanks Jim!
