### ISSUE TITLE
decouple modifications

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1226]
Here Ye De Tay's modifications are comma separated.

<img width="1217" alt="Screenshot 2024-09-26 at 18 14 40" src="https://github.com/user-attachments/assets/1604d2d9-c1f0-42f3-9dc5-f7ff75e4f90e">
Although this indicates they were phosphorylated at the same time, we demonstrate this with during phase annotations (essentially it is a bit arbitrary to represent co modified residues together because they need to be on the same small fragment).
We decided that comma separating them would prevent useful removal of redundancy and better display.

Would it be possible to decompose the modifications in this file?

**Comment by kimrutherford** [comment]
So just to make sure I know what you mean, annotations like this should be split into two (or however many) separate annotations?:

![image](https://github.com/user-attachments/assets/3fe42a81-2e11-40b0-a7a5-2ad88823c58a)

**Comment by kimrutherford** [comment]
OK, thanks.  I've fixed the fixed for tonight's load.
