### ISSUE TITLE
Add residues to UniProtKB import

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1227]
We can add the residues (and hence QC checks) to the following residues from 
https://www.pombase.org/reference/PMID:36408920

H	MOD:00226	1'-(8alpha-FAD)-L-histidine
G	MOD:01625	1-thioglycine
H	MOD:00153	3'-(8alpha-FAD)-L-histidine
C	MOD:00257	dipyrrolylmethanemethyl-L-cysteine
C	MOD:00689	disulfide crosslinked residues
C	MOD:00441	geranylgeranylated residue
K	MOD:00125	hypusine
Y	MOD:00156	L-2',4',5'-topaquinone
D	MOD:00042	L-aspartic 4-phosphoric anhydride
C	MOD:00234 	L-cysteine glutathione disulfide
C	MOD:00114 	L-cysteine methyl ester
L	MOD:00304	L-leucine methyl ester
G	MOD:01982	N,N,N-trimethylglycine
A	MOD:00050	N-acetyl-L-alanine
S	MOD:00060	N-acetyl-L-serine
G	MOD:00351	N-glycyl-1-(phosphatidyl)ethanolamine
G	MOD:00068	N-myristoylglycine
S	MOD:00171	N-seryl-glycosylphosphatidylinositolethanolamine
R	MOD:00310	N5-methyl-L-arginine
Q	MOD:00080	N5-methyl-L-glutamine
K	MOD:00083	N6,N6,N6-trimethyl-L-lysine
K	MOD:00084	N6,N6-dimethyl-L-lysine
K	MOD:00064	N6-acetyl-L-lysine
K	MOD:00126	N6-biotinyl-L-lysine
K	MOD:00123	N6-carboxy-L-lysine
K	MOD:00127	N6-lipoyl-L-lysine
K	MOD:00085	N6-methyl-L-lysine
K	MOD:00128	N6-pyridoxal phosphate-L-lysine
S	MOD:00046	O-phospho-L-serine
T	MOD:00047	O-phospho-L-threonine
S	MOD:00159	O-phosphopantetheine-L-serine
Y	MOD:00048	O4'-phospho-L-tyrosine
H	MOD:00890	phosphorylated L-histidine
C	MOD:00111	S-farnesyl-L-cysteine
C	MOD:00115	S-palmitoyl-L-cysteine

We can't map these because they are not to a single residue:

[G/D/S/N/C]	MOD:00818	glycosylphosphatidylinositolated residue
[S/T/K]	MOD:01154	pyruvic acid

**Comment by kimrutherford** [comment]
> We can add the residues (and hence QC checks) to the following residues

That's done on pombase.org.  Example: https://www.pombase.org/term/MOD:00084

> We can't map these because they are not to a single residue:

We could check which AA is at that position and add it to the residue?

**Comment by kimrutherford** [comment]
> We could check which AA is at that position and add it to the residue?

I've implemented that, but not in time for the current load.  I'll check things on Wednesday.

There's one annotation from UniProt that produces a warning.

> [G/D/S/N/C] MOD:00818 glycosylphosphatidylinositolated residue

SPBPJ4664.02 has a lipidation annotation at residue 3944.  We map this lipidation annotation to MOD:00818 but the residue at that position is "A" not one of G/D/S/N/C:
https://www.uniprot.org/uniprotkb/Q96WV6/feature-viewer
