### ISSUE TITLE
 GO terms bug

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1229]
Some sessions have obsolete terms e.g.

https://curation.pombase.org/pombe/curs/760045d7bb2de1aa

but these are not reported in this file

https://curation.pombase.org/dumps/latest_build/logs/log.2024-09-30-21-55-49.curation-tool-data-load-output

I thought this is where they went?

**Comment by kimrutherford** [comment]
I don't know what's going on here.  Is the term taxon restricted?  It's not obsolete:
https://www.ebi.ac.uk/QuickGO/term/GO:1903139

> but these are not reported in this file

Because the term isn't obsolete, those annotations get loaded into Chado without a warning:
https://www.pombase.org/term/GO:1903139
https://www.pombase.org/reference/PMID:24498240

It seems like Canto is the problem.  I'm looking into it now.

**Comment by ValWood** [comment]
Yes I was just going to add that it isn't an obsolete term!

**Comment by kimrutherford** [comment]
I noticed that parent term `GO:0000196` has weird taxon constraints.  Does it make sense to have two "Only in Taxon" constraints like this?

We create a pombe-only OBO file for loading into Canto using OWLTools.  When I remove that taxon constraint from the input file (`go-plus.owl`), and re-run OWLTools the missing term (`GO:1903139`) reappears.  So the constraint does look like at least part of the problem.

Parent term: https://www.ebi.ac.uk/QuickGO/term/GO:0000196

![image](https://github.com/user-attachments/assets/f06d7a4f-2e08-4c7b-8f56-7a5a4b4b4b94)

**Comment by kimrutherford** [comment]
It looks like the "Viridiplantae or Bacteria or Euglenozoa" constraint was added in this PR:
 - https://github.com/geneontology/go-ontology/pull/26802

**Comment by ValWood** [comment]
Yep that taxon constraint is incorrect. I will open a ticket

cc @pgaudet @balhoff

**Comment by kimrutherford** [comment]
Looks like this is fixed now.
