### ISSUE TITLE
Modifications, add assigned by column

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1232]
How many non automated Modification annotations do we import from UniProt?
(and how many do we keep after filtering the redundancy).

I am trying to establish how much  duplication of effort there has been historically so I can include that information in my 
e-mail.  

These have their own PMID so they don't appear here:
https://www.pombase.org/reference/PMID:36408920

**Comment by ValWood** [comment]
I just looked at the modifications download file, but it doesn't have an assigned_by column. We should add that.

Although I still s would not be able to get the numbers because I would not know how many were in the intersection (filtered as duplicates).
v

**Comment by kimrutherford** [comment]
> How many non automated Modification annotations do we import from UniProt?

Here are the counts of modifications with each evidence code.  I wasn't sure which code count as non automated.

| count | evidence_code | evidence_name |
|--|--|--| 
|   204 |  ECO:0000250 |  sequence similarity evidence used in manual assertion|
|    55 |  ECO:0000255 |  match to sequence model evidence used in manual assertion|
|  2370 |  ECO:0000269 |  experimental evidence used in manual assertion|
|    7 | ECO:0000305 |  curator inference used in manual assertion|


> (and how many do we keep after filtering the redundancy).

We're keeping them all at the moment.  The filtering isn't implemented:
  - https://github.com/pombase/pombase-chado/issues/1223

**Comment by ValWood** [comment]
Thanks.
 Could you extract
PMID number for the EXP codes I think most are from  single dataset (Wilson -Grady)

**Comment by kimrutherford** [comment]
| count | evidence+PMID |
|--|--|
|    204  | ECO:0000250 |
|     55  | ECO:0000255 |
|      2  | ECO:0000269 PubMed:10364209 |
|      1  | ECO:0000269 PubMed:10485849 |
|      1  | ECO:0000269 PubMed:10488332 |
|      1  | ECO:0000269 PubMed:10617667 |
|      4  | ECO:0000269 PubMed:10921878 |
|      2  | ECO:0000269 PubMed:11283354 |
|      4  | ECO:0000269 PubMed:11486016 |
|      5  | ECO:0000269 PubMed:11937031 |
|      2  | ECO:0000269 PubMed:12135491 |
|      2  | ECO:0000269 PubMed:12697825 |
|      3  | ECO:0000269 PubMed:12773390 |
|      3  | ECO:0000269 PubMed:12805221 |
|      1  | ECO:0000269 PubMed:12931193 |
|      1  | ECO:0000269 PubMed:14585996 |
|      4  | ECO:0000269 PubMed:14633985 |
|      2  | ECO:0000269 PubMed:15226425 |
|      3  | ECO:0000269 PubMed:1547790 |
|      4  | ECO:0000269 PubMed:16087749 |
|     14  | ECO:0000269 PubMed:18076573 |
|   2258  | ECO:0000269 PubMed:18257517 |
|      2  | ECO:0000269 PubMed:18378696 |
|      2  | ECO:0000269 PubMed:19155267 |
|      5  | ECO:0000269 PubMed:19804755 |
|      1  | ECO:0000269 PubMed:20444689 |
|      1  | ECO:0000269 PubMed:207525 |
|      1  | ECO:0000269 PubMed:20924356 |
|      6  | ECO:0000269 PubMed:21376600 |
|      1  | ECO:0000269 PubMed:22375062 |
|      1  | ECO:0000269 PubMed:22375066 |
|      2  | ECO:0000269 PubMed:22682245 |
|      1  | ECO:0000269 PubMed:22792081 |
|      3  | ECO:0000269 PubMed:22976295 |
|      1  | ECO:0000269 PubMed:23415232 |
|      2  | ECO:0000269 PubMed:24074952 |
|      1  | ECO:0000269 PubMed:24247430 |
|      2  | ECO:0000269 PubMed:24352239 |
|      2  | ECO:0000269 PubMed:24550462 |
|      1  | ECO:0000269 PubMed:29192674 |
|      6  | ECO:0000269 PubMed:30051891 |
|      3  | ECO:0000269 PubMed:33836577 |
|      1  | ECO:0000269 PubMed:3910104 |
|      3  | ECO:0000269 PubMed:7628693 |
|      1  | ECO:0000269 PubMed:7957097 |
|      1  | ECO:0000269 PubMed:8226998 |
|      1  | ECO:0000269 PubMed:8524294 |
|      2  | ECO:0000269 PubMed:9430640 |
|      3  | ECO:0000305 |
|      1  | ECO:0000305 PubMed:14585996 |
|      1  | ECO:0000305 PubMed:22792081 |
|      2  | ECO:0000305 PubMed:37731000 |

**Comment by ValWood** [comment]
OK after the filtering it would be good to know how many of these are filtered as a consistency check.

Then I will contact UniProt about ingesting our additional  ~67000, but I can show them the precise overlap

**Comment by kimrutherford** [comment]
The modifications export file now has an "assigned_by" column:
https://curation.pombase.org/dumps/builds/pombase-build-2024-10-13/misc/modifications.tsv
