### ISSUE TITLE
Add RNAcentral IDs to GPI files

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1235]
@ValWood I think you mentioned this on the last call?

I can't find any discussion of what to do with RNA genes in the GPI/GPAD documentation.  Perhaps we just need an entry for RNAcentral in the dbxrefs columns of the GPI file.

**Comment by ValWood** [comment]
Probably.  @vanaukenk  @pgaudet would that work?

**Comment by kimrutherford** [comment]
Thanks Pascale!

From tomorrow morning, the PomBase GPI file will include the RNAcentral ID as a db_xref.

**Comment by pgaudet** [comment]
Wow! That's very efficient! Thanks @kimrutherford
