### ISSUE TITLE
block a legacy term remapping

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1240]
somewhere in ancient history, there is a script that maps some GO lecacy data evidence codes to more specific codes.

I think it is mapping 
GO:0033260 ->GO:1902969
we need to block that remapping because GO:1902969 is to. be obsoleted in favour of GO:0033260

I can't remember when the remapping  occurs, but I think it must be during or before loading

**Comment by kimrutherford** [comment]
Hi Val.

I think this is the file you need:
`pombe-embl/chado_load_mappings/GO_mapping_to_specific_terms.txt`

**Comment by ValWood** [comment]
thanks
