### ISSUE TITLE
QC: check allele descriptions match current gene sequence  (possible student project)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#131]
Gene structures are sometimes updated which may make some allele descriptions incorrect. Luckily this won't usually happen because if a gene structure is wrong it is usually an uncharacterised gene, not one which has been studied in depth. However we need to be aware of this. At some point in the future, maybe we can get a student to make a program to alert us when the allele residues do not match  the protein. I guess this will happen any way if we try to do anything with these down the line....

Original comment by: ValWood

**Comment by kimrutherford** [comment]
Done!

Thanks @manulera !

**Comment by ValWood** [comment]
Thanks @manulera , I'm glad that we didn't entrust this task to a summer student. We got something much, much better than we envisaged!
