### ISSUE TITLE
external GO file precedence

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#140]
At present, all external GO date is given the same precedence.
It would be better if the "NAS" mappings in  go_func.txt go_proc.txt and go_comp.txt  were given lowere precedence (I think this would involved loading the other files first?)

(We discussed doing this at some point, and then I think we postponed it, so I don't think there is an open item?)

Original comment by: ValWood

**Comment by ValWood** [comment]
This is a duplicate of the more detailed ticket
https://github.com/pombase/pombase-chado/issues/594
