### ISSUE TITLE
Small change to GO export (unknowns with NOT annotation only  need root node ND)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#147]
Using the slimmer tool
These 2 identifiers were found to be unannotated: SPCC736.09c  SPAC30.03c
(for a process slim)

This is because they only have "NOT" annotations, which I am guessing the slimmer correctly ignores.
So that this doesn't happen, if an aspect has only NOT annotations, it should be assume we don't know and create an ND annotation.

**Comment by ValWood** [comment]
I don't know if this was fixed by the NOT changes because we no longer have any annotations of unknown proteins  with  NOT annotation that would then require an ND to the root node. For now, I will put this at "future" and I'll bump up if  the problem is still present if we ever have any unknowns with NOT"

**Comment by ValWood** [comment]
note to self, test this

**Comment by ValWood** [comment]
Do we have an example of a NOT annotation  for a gene with otherwise no annotation for that aspect?

**Comment by kimrutherford** [comment]
I found 3 examples with a rather dodgy bit of SQL:

```
  uniquename |                               term_name                               |      cv_name       
---------------+-----------------------------------------------------------------------+--------------------
 SPCC126.12  | NOT GTP cyclohydrolase activity                                       | molecular_function
 SPCC794.10  | NOT UTP:glucose-1-phosphate uridylyltransferase activity              | molecular_function
 SPAC3H8.09c | NOT termination of RNA polymerase II transcription, exosome-dependent | biological_process
```


--------------------------------------------

Note to self:
```sql
create temp table not_fc as
  select fc.feature_id, t.name, cv.name as cv_name,
      (select count(inner_fc.*)
        from feature_cvterm inner_fc
          join cvterm inner_t on inner_fc.cvterm_id = inner_t.cvterm_id
          join cv inner_cv on inner_cv.cv_id = inner_t.cv_id
        where not inner_fc.is_not and inner_cv.cv_id = cv.cv_id
          and inner_fc.feature_id = fc.feature_id) 
  from feature_cvterm fc join cvterm t on fc.cvterm_id = t.cvterm_id join cv on cv.cv_id = t.cv_id
  where is_not;

select f.uniquename, 'NOT ' || not_fc.name as term_name, cv_name
  from not_fc join feature f on f.feature_id = not_fc.feature_id
 where count = 0;
```

**Comment by ValWood** [comment]
Thanks I'll dig into this shortly

**Comment by ValWood** [comment]
added
PomBase	SPAC23G3.05c		NOT	GO:0006260	GO_REF:0000051	NAS		P	XXXX		protein	taxon:4896	20241023	PomBase	 
to test

**Comment by kimrutherford** [comment]
> I'll add a NOT annotation that cannot be true to an unknown (i.e mitochondrial DNA replication to a plasma membrane unknown) to test

Hi Val.  Could you explain what that is testing for?

**Comment by ValWood** [comment]
It's for me to test that we still export and ND annotations for process if  the gene has only a NOT annotation for process

**Comment by ValWood** [comment]
we only get
PomBase	SPAC23G3.05c	SPAC23G3.05c	NOT|involved_in	GO:0006260	GO_REF:0000051	NAS		P	conserved endomembrane protein, RGS domain, implicated in signal transduction, cell polarity, possibly via membrane tethering		protein	taxon:4896	20241023	PomBase	

but because the only annotation for this aspect (P) is a NOT annotation we should also see the root node annotation

PomBase	SPAC23G3.05c	SPAC23G3.05c	involved_in	GO:0006260	GO_REF:????	ND		P	conserved endomembrane protein, RGS domain, implicated in signal transduction, cell polarity, possibly via membrane tethering		protein	taxon:4896	20241023	PomBase

**Comment by ValWood** [comment]
Add  discuss if this doesn't make sense, can explain easily on Tuesday

**Comment by kimrutherford** [comment]
Have I got this right: we should ignore NOT annotations when deciding if an ND annotation is needed for an aspect?

**Comment by ValWood** [comment]
Yes, correct!

**Comment by kimrutherford** [comment]
Thanks.  I think it's fixed now.  From tomorrow there will be 4 extra ND annotations:

```
PomBase       SPAC23G3.05c    SPAC23G3.05c    involved_in     GO:0008150      GO_REF:0000015  ND              P       conserved endomembrane protein, RGS domain, implicated in signal transduction, cell polarity, possibly via membrane tethering            protein taxon:4896      20241122        PomBase
PomBase       SPAC3H8.09c     nab3    involved_in     GO:0008150      GO_REF:0000015  ND              P       poly(A) binding protein Nab3            protein  taxon:4896      20241122        PomBase
PomBase       SPCC126.12      SPCC126.12      enables GO:0003674      GO_REF:0000015  ND              F       mitochondrial protein, DUF34 family, possible chaperone or insertase (PMID: 34572495)            protein taxon:4896      20241122        PomBase
PomBase       SPCC794.10      ugp1    enables GO:0003674      GO_REF:0000015  ND              F       UTP-glucose-1-phosphate uridylyltransferase-like Ugp1            protein taxon:4896      20241122        PomBase
```

**Comment by kimrutherford** [comment]
> From tomorrow there will be 4 extra ND annotations:

Those ND annotations will be in the GAF file (https://www.pombase.org/data/annotations/Gene_ontology/gene_association.pombase.gz) and also in the GPAD file.  Although for GPAD it's "ECO:0000307" rather than "ND".

**Comment by ValWood** [comment]
Ah so there were some hidden. I think I knew that because they appear as unknown IDentifiers in GO term finder.

Thanks!

**Comment by kimrutherford** [comment]
Excellent.  I'll double check the GAF file in the morning.

This is the oldest open issue on the Chado tracker.  :-)

Next oldest:
 - pombase/pombase-chado#227

**Comment by ValWood** [comment]
Yes I saw that!
