### ISSUE TITLE
QC: warn obsolete GO terms in from field

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#158]
We currently get warned when a GO term is obsolete, but not when the term is in the "from field" of an IC annotation.

This isn't urgent, as it doesn't happen often, but at present we will need to fix them in the GAF (they will reject at submission), and in the contigs. If we had a warning, we would only need to fix them in the contigs.

e.g
chromosome1.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome1.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome1.contig:FT                   db_xref=GO_REF:0000001; from=GO:0016585; date=20051128"
chromosome1.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome1.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome1.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome1.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome1.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome1.contig:FT                   db_xref=GO_REF:0000001; from=GO:0016585; date=20051128"
chromosome1.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome2.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome2.contig:FT                   db_xref=GO_REF:0000001; from=GO:0016585; date=20051128"
chromosome2.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome2.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome2.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome2.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;
chromosome3.contig:FT                   db_xref=GO_REF:0000001; from=GO:0016585; date=20051128"
chromosome3.contig:FT                   db_xref=GO_REF:0000001; from=GO:0016585; date=20051128"
chromosome3.contig:FT                   evidence=IC; db_xref=GO_REF:0000001; from=GO:0016585;

I haven't fixed these yet ......(they may need to be changed to ISO or something else....
becasue i think they are mainly probably chromating remodeling IC from chromatin remodeling complex)

Original comment by: ValWood

**Comment by ValWood** [comment]
@mah11  is this one of the Jenkins checks? If so, this ticket can be closed as duplicate of
https://github.com/pombase/pombase-chado/issues/300

**Comment by mah11** [comment]
This is in Mike's old GAF-checking script, which Kim already runs (the gaf-check log is essentially its output).
