### ISSUE TITLE
logs: equivalent allele descriptions aa vs nucleotide

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#172]
Kim: these are nucleotide descriptions (which can be slightly more informative because of degenerate codons). Can awe allow each allele to have an AA and an NT description?

We need to devise the way for checking equivalence of these, and store both (for now, this is not urgent if we just store the first one, and this is only a warning if)

Curators: What if we  display the AA one in PomBase by default, but make the nt one visible by mouse over if stored?

error in 58d8ad0dec113279: description for new allele "cdc10-K30(C1434T)" does not match the existing allele with the same name "cdc10-K30(T429I)"
error in 58d8ad0dec113279: description for new allele "cdc10-P2(A1209G)" does not match the existing allele with the same name "cdc10-P2(D354G)"
error in 58d8ad0dec113279: description for new allele "cdc10-M15(G1325A)" does not match the existing allele with the same name "cdc10-M15(A393T)"
error in 58d8ad0dec113279: description for new allele "cdc10-V50(C1232T)" does not match the existing allele with the same name "cdc10-V50(H362Y)"
error in 58d8ad0dec113279: description for new allele "cdc10-M71(G1325A)" does not match the existing allele with the same name "cdc10-M71(A393T)"
error in 58d8ad0dec113279: description for new allele "cdc10-I29(A1433G)" does not match the existing allele with the same name "cdc10-I29(T429A)"
error in 58d8ad0dec113279: description for new allele "cdc10-MBC4(C2268T)" does not match the existing allele with the same name "cdc10-MBC4(R707->STOP)"
error in 58d8ad0dec113279: description for new allele "cdc10-M47(G1607A)" does not match the existing allele with the same name "cdc10-M47(A487T)"
error in 58d8ad0dec113279: description for new allele "cdc10-M4(G1325A)" does not match the existing allele with the same name "cdc10-M4(A393T)"
error in 58d8ad0dec113279: description for new allele "cdc10-MBC41(C1434T)" does not match the existing allele with the same name "cdc10-MBC41(T429I)"
error in 58d8ad0dec113279: description for new allele "cdc10-K28(C1295T,C1705T,C1976T)" does not match the existing allele with the same name "cdc10-K28(P383S,R610C)"
error in 58d8ad0dec113279: description for new allele "cdc10-M17(G1325A)" does not match the existing allele with the same name "cdc10-M17(A393T)"
error in 16802f31036c5732: description for new allele "cut8-563(S201P)" does not match the existing allele with the same name "cut8-563(ntY1283C)"
error in 7bf893a86d94196c: description for new allele "cdc23-M36(D232G,V265I)" does not match the existing allele with the same name "cdc23-M36(A695C)"
error in 4d6014a904a1e84b: description for new allele "ned1-1(deletion)" does not match the existing allele with the same name "ned1-1(G402D)"
error in 4d6014a904a1e84b: description for new allele "ned1-1(deletion)" does not match the existing allele with the same name "ned1-1(G402D)"
error in 42b53662d27d7951: description for new allele "M6(C328A,C330A,C334A,C336A,C339A,H342A)" does not match the existing allele with the same name "M6(  C328A,C330A,C334A,C336A,C339A,H342A)"

Original comment by: ValWood

**Comment by kimrutherford** [comment]
Need to fix: #481 first

**Comment by kimrutherford** [comment]
Descriptions like this "cdc10-M71(A393T)" assume that there is only every one transcript for a gene.  To future-proof things, I'll make sure the code warns if there is ever more than one transcript.

**Comment by kimrutherford** [comment]
I'm quite close to finishing this.

I'm a bit worried by examples like this:

    "cdc10-P2(A1209G)" does not match the existing allele with the same name "cdc10-P2(D354G)"

Is the "1209" the base position in the mRNA sequence or the position in the coding bit?  If it's the position in the CDS then the numbers don't make sense - the position in the CDS should be around 1060, not 1209.

If it's the position in the mRNA that doesn't seem very future-proof.  What happens if the UTR length is modified or if a UTR is added to an mRNA?

**Comment by mah11** [comment]
> Is the "1209" the base position in the mRNA sequence or the position in the coding bit?

It's supposed to be the position in the coding bit. If it doesn't match, that means someone made a mistake (could've been a curator or an author) that we'd like to fix, so we want a warning in the logs.

I don't think there's a separate ticket for log warnings (tho #131 is somewhat related); there's just a brief comment above from 2 years ago.

**Comment by kimrutherford** [comment]
> so we want a warning in the log

Great.  Thanks for clarifying.

**Comment by kimrutherford** [comment]
Thanks to https://github.com/pombase/pombase-legacy/commit/8bf908e04c90525014fce6e30af5480c83f9250f we now have the transcript and protein sequences in Chado so this issue is easier to fix now.

**Comment by ValWood** [comment]
We don't need to do this.  @mah11  will switch to amino acid and record the nucleotide in the "allele comment"
