### ISSUE TITLE
logs: report legacy gene expression data in logs

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#187]
For the next load can you report any  qualitative gene expression data which does not fit the format described here:
https://sourceforge.net/apps/trac/pombase/wiki/CapturingGeneExpression

i.e
Example Artemis string: /controlled_curation="term=gene expression, RNA level; annotation_extension=during(GO:xxxxxxx); qualifier=increased; evidence=ECO:xxxx; db_xref=; date=YYYYMMDD" 

val

Original comment by: ValWood

**Comment by ValWood** [comment]
This might have been addressed by recent updates to log file reporting/

**Comment by ValWood** [comment]
I wonder if this is done? Do we have any "controlled curation" lines in the contig files  that do not load?

**Comment by kimrutherford** [comment]
I checked, if there were any errors they would be reported for /controlled_curation lines in `all_warnings.txt` in the logs directory.  Last night's load looks good.
