### ISSUE TITLE
QC: filter *EXACT* duplicate annotation from UniprotKB

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#193]
If an annotation from UniPROT KB has the _exact_ same annotation as a Pombase one (publication/evidience code). Please filter the uniProt annotation.
- Hmm, this makes me wonder if, as we remove  some of the PomBase annotations using IMP which are _indirect_ we may then  reveal the corresponding UniProt annotation with an IMP ecvidence code, if there is one.

Kim, next time you grab the GOA file, could you let me know:
i) How many EXP annotations we get from GOA? (IMP/IDA/IGI)
ii) How many remain after filtering (this will be possible from the GO GAF after the asigned by is corrected, so we can do this)

.....we could exclude the Uniprot  EXP altogether if we had them fully covered. I know I only used to pick up a 100 or so after filtering (probably lower now), so if we made sure these papers were covered we could just have a log file for Uniprot annotations which are not covered by our annotations,and decide whether they are appropriate to include.
I'm suggesting this because it will be a diminishing set...I don't think Uniprot curators do pombe papers anymore as they have lots of uncared for fungi to look after.

v

Original comment by: ValWood

**Comment by ValWood** [comment]
This appears to be an exact duplicate of
https://github.com/pombase/pombase-chado/issues/536
