### ISSUE TITLE
Store all evidence in Chado using ECO term IDs not names

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#195]
Currently we use ECO term IDs sometimes but for GO we use the GO evidence name (like "Inferred from Mutant Phenotype").

For FYPO there are still a few missing ECO terms: [curation-tasks:#192]

Original comment by: kimrutherford

**Comment by ValWood** [comment]
I don't think this has any dependencies or impedes our work flows, so can be postponed until required

**Comment by mah11** [comment]
fyi, I've updated the chado_load_mappings/ECO_evidence_mapping.txt file in svn

**Comment by kimrutherford** [comment]
I think this is done quite a few years ago using the mapping file created by Midori.  We now store ECO evidence codes for all annotation as well as the usual long name for the evidence.

So where we store "Inferred from Sequence Orthology" as the `evidence` property of an annotation (a `feature_cvtermprop` in Chado), we also store "ECO:0000201" as an `eco_evidence` property.

http://purl.obolibrary.org/obo/ECO_0000201
