### ISSUE TITLE
placeholder: loader required for gene specific description lines

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#197]
Antonia is collating "short gene descriptions"
(In a flatfile with ID/description)

Once we have a critical number, a loader will be required.
When this is done we will need a jira ticket to store  and display the descriptions in PomBase

Original comment by: ValWood

**Comment by ValWood** [comment]
I had completely forgotten about this, had @Antonialock ?
Do we still want to do this?
Discuss clever ways to do it (small grant?)

**Comment by Antonialock** [comment]
I think this would be really appreciated by the community.

**Comment by ValWood** [comment]
Should we do this?

**Comment by ValWood** [comment]
Is there a curation tracker ticket for this?
If not, I think we should  open one, and close this until there is a task for Kim to do.

@Antonialock

**Comment by Antonialock** [comment]
we decided not to do this, that the product description should be sufficient.

**Comment by ValWood** [comment]
OK!

**Comment by Antonialock** [comment]
(would be great to have but too much work/not enough time)

**Comment by ValWood** [comment]
Should we keep as "blue sky" on the curation tracker. We could ask in next survey and put into next grant if users really want it......

**Comment by Antonialock** [comment]
I think it is something that would be generally very appreciated, and generally a lot of work (to make and maintain).

I think the feeling is that the product description is not enough to give a feel of what the gene product does (unless you know more about all things cell biology than what the average process-expert/PhD student... knows). I guess it is good for scanning gene lists, but if you want to check out more detail there is no good intermediate step between product line and delving deep into the literature (I know the annotations are there but I don't think they are not regarded as friendly as 'text')

**Comment by Antonialock** [comment]
it should be easy to seed automagically :)

"ser/thr protein kinase involved in blah during blah phase. Phosphorylated by blah during blah. Localizes to blah. Expression downregulated during blah.
