### ISSUE TITLE
:pep in cDNA file

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#198]
I cant remember if this was done or not and my connection is too slow to access the file via ftp
but lat time I looked the cDNA file had :pep in the IDs (which were establised to come from chado)

ftp://ftp.ensemblgenomes.org/pub/fungi/current/fasta/schizosaccharomyces_pombe/cdna/

(If this makes no sense, assign to me and I'll figure out what it was meant to be when I get back)

val

Original comment by: ValWood

**Comment by ValWood** [comment]
@kimrutherford is this still relevant?

**Comment by kimrutherford** [comment]
I think we can close this and think about it later if it's a problem.

**Comment by ValWood** [comment]
I like that plan. I'm in ticket closing mode...
