### ISSUE TITLE
Write a new cvterm OBO loader - maybe

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#199]
The current GMOD method using Stag is quite slow - an hour or two for GO and FYPO.  (Loading the cvtermpath table takes another 10-ish hours after that).

If no one has written a new loader, maybe we should.

Notes to self:
try reading all the current cvterm table contents into memory about then read all the OBO files into memory - we have lots of memory, let's use it.

needs to update cvterm_relationship too

don't use DBIx::Class

use the COPY FROM support in DBD::Pg to make loading fast: http://search.cpan.org/~turnstep/DBD-Pg/Pg.pm#pg_putcopydata

see also: http://tapoueh.org/blog/2013/03/15-batch-update

Original comment by: kimrutherford

**Comment by ValWood** [comment]
is this superseded by chobo?

**Comment by kimrutherford** [comment]
> is this superseded by chobo?

Yep, fixed!
