### ISSUE TITLE
Add extra cerevisiae genes (deal with cerevisiae orthologs absent from sequenced strain)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#200]
There are a few curated orthologs to cerevisiae genes that aren't in the sequenced strain.  We don't get the identifiers for them from Ensembl/BioMart so we'll need to load them separately.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
duplicate of
https://github.com/pombase/pombase-chado/issues/823
