### ISSUE TITLE
import extra info for ortholog table and write out at update time

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#202]
New ortholog (version 19 is made)
https://sourceforge.net/p/pombase/curation-tasks/208/

All of the genes which are tandem fusions, or map to a tandem fusion are annotated thus:

/controlled_curation="term=orthologous to S. cerevisiae YDR267C; qualifier=SPAC806.02c,C_term; date=19700101"
/controlled_curation="term=orthologous to S. cerevisiae YIL003W; qualifier=SPAC806.02c,N_term; date=19700101" 

OR
tandem fusion in S. cerevisia
his7
/controlled_curation="term=orthologous to S. cerevisiae YCL030C; qualifier=YCL030C(N-term); date=19700101"
his2
/controlled_curation="term=orthologous to S. cerevisiae YCL030C; qualifier=YCL030C(C-term); date=19700101"

So next  you need to
1. Make sure "qualifier= is parsed and stored (this might happen already)
2. Make sure db_xref is parsed and stored
Let us know if this is happening as we can open a jira ticket to display these
1. Write out an equivalent version (V.19) from Chado
   (I will compare this to my existing V 19 to amke sure nothing has gon awry, because  the table is currently  maintained independently  from the data in Artemis).
   Once I have checked it, this will become the official release.

Original comment by: ValWood

**Comment by ValWood** [comment]
Closing. Will open a new ticket for the outstanding task.
