### ISSUE TITLE
stats : reports: relations used

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#228]
Could you update this list for us at some point?
28 | condition
1 | dependent\_on
179 | during
3 | exists\_during
119 | has\_part
10 | has\_regulation\_target
113 | has\_substrate
4 | independent\_of
20 | localization\_dependent\_on
998 | localizes
8 | modified\_by
5 | occurs\_in
156 | part\_of
16 | requires\_feature
1 | requires\_regulator

I wondered if I could access this within the curations tool.

I found the list of relations
http://oliver0.sysbiol.cam.ac.uk/pombe/view/object/cv/6?model=chado
but they are all "0"

Original comment by: ValWood

**Comment by mah11** [comment]
now included in chado logs
