### ISSUE TITLE
publication related data

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#229]
In the first instance this is wanted to be able to "spotlight" community curated papers on the front page
In the medium term it would be useful to be able to flag HTP papers on the gene pages
Longer term (probably future grant as we have to do the stuff we are funded for this time first), will be useful to make "publication pages" available and contents searchable.

So the "publication record" should store
publication associated data and gene list
session ID
curator name
CC flag
HTP flag

Original comment by: ValWood

**Comment by kimrutherford** [comment]
I've added the per-publication metadata mentioned in this issue except for the HTP flag.  I thought the data would be useful for pombase/canto#1180 but I didn't need it in the end.  The data will be in the next load.

**Comment by ValWood** [comment]
Closing this as "out of date"...
