### ISSUE TITLE
Fix warnings about SO types in Chado load

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#235]
What's causing these?:

5'UTR SPAC8E11.03c.1:5'UTR:1 from gene: SPAC8E11.03c: no SO type for mRNA - skipping
CDS SPBP22H7.09c.1 from gene: SPBP22H7.09c: no SO type for mRNA - skipping
CDS SPBP22H7.09c.1 from gene: SPBP22H7.09c: no SO type for mRNA - skipping
mRNA SPMTR.04.1: no SO type for source - skipping
mRNA SPMIT.11.1: no SO type for source - skipping

Original comment by: kimrutherford

**Comment by ValWood** [comment]
this is related, its the polycistronic trancript covering SPAC8E11.03c above (it probably has 2 IDs as it covers 2 genes...)

FT mRNA 3382284..3385575
FT /note="polycistronic mRNA from AB008545"
FT /gene="rad24"
FT /gene="SPAC8E11.02c"

**Comment by ValWood** [comment]
Out of date?
