### ISSUE TITLE
support transcript IDs in extensions

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#236]
example from session d604bc516ecb12dc

SPAC19D5.03/cid1 GO:0050265 (MF that acts on RNA) annotation_extension=has_substrate(PomBase:SPBC32H8.12c.1)

means Cid1 modifies the act1 transcript

Val remembers discussing this sort of thing a while ago - basically, we can either use a gene systematic ID and assume/infer that it really means a transcript when it's used to extend an RNA-related term, or we can use transcript IDs. It's not a big deal now, but could become useful later when some genes have more than one transcript in the db.

In the short term, let us know if we should change the example to the gene ID.

Original comment by: mah11

**Comment by ValWood** [comment]
Woo Hoo, Out of date?

**Comment by kimrutherford** [comment]
> Out of date?

Maybe?  I don't remember doing anything to change this.

**Comment by ValWood** [comment]
I think its all handled by the annotation extension config files. We can open new if I got this wrong and there is something to do.
@mah11  did I miss the point of this ticket in any way?

**Comment by mah11** [comment]
There's no longer any motivation for curators to paste "blah.1" transcript IDs into extensions, even in text-only admin mode. Instead, we may eventually want something automated - whether it's at the level of Canto, the Chado loader, or output from Chado to GAF & GPAD - to convert gene IDs to transcript or protein IDs as appropriate. But that's new-ticket territory.

I see from the original ticket description that we also thought about the possibility of more than one transcript per gene, but that's so far in the future that we can just wait and open whatever new tickets we need when we actually have any alternative transcripts.
