### ISSUE TITLE
extensions using SO

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#238]
For GO DNA binding annotation extensions that use SO IDs, the relation should be 'occurs at'. I've fixed offending annotations for now, but for future-proofing, can we have a warning for any annotation extensions where:

the ID is a SO:nnn ID 

AND the relation isn't one of these:
- occurs_at
- not_occurs_at
- requires_sequence_feature
- has_regulation_target

thanks!

Original comment by: mah11

**Comment by mah11** [comment]
will soon be superseded by the configurations for the shiny Canto extension interface
