### ISSUE TITLE
Load PAINT annotations for checking  (but not into chado release version!)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#241]
When we eventually load the PAINT annotations we need to exclude the NOT annotations.
The PAINT annotations use NOT differently...and the consequence is annotations with NOTS which you would not expect to be true in the first place.

Longer term, there might be a place for comprehensive NOT annotation in the database, but not yet....

I'll update here
https://sourceforge.net/apps/trac/pombase/wiki/ExternalGOData

Original comment by: ValWood

**Comment by ValWood** [comment]
replaced by shiny new ticket 
https://github.com/pombase/pombase-chado/issues/594
