### ISSUE TITLE
what to do when external  annotation files  use names which are now synonyms

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#246]
These genes no longer exist.
http://www.pombase.org/status/new-and-removed-genes

can you let me know where they are referred to?
Thanks
Val

skipping annotation: can't find feature for: SPAC1F12.03c
skipping annotation: can't find feature for: SPBC1348.13

Original comment by: ValWood

**Comment by ValWood** [comment]
I'm not sure  if this is still an issue?

**Comment by kimrutherford** [comment]
I think we should close this since it's so old.
