### ISSUE TITLE
GOA data load error?

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#259]
There are a big bunch of errors in
http://curation.pombase.org/dumps/pombase-build-2013-11-01-v1-l1/logs/log.2013-11-02-12-01-03.gaf-load-output

which I don't really understand...are you having problems matching annotations woth pombe genes?

/var/pomcur/sources/gene_association.goa_uniprot.pombe
didn't download new ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/gene_association.goa_uniprot.gz
feature not found, no synonym matches a feature (A4CYJ4_SCHPM RPL22 A4CYJ4 RPL22)
feature not found, no synonym matches a feature (A4CYJ4_SCHPM RPL22 A4CYJ4 RPL22)
feature not found, no synonym matches a feature (A4CYJ4_SCHPM RPL22 A4CYJ4 RPL22)
feature not found, no synonym matches a feature (A4CYJ4_SCHPM RPL22 A4CYJ4 RPL22)
feature not found, no synonym matches a feature (A6YRR9_SCHPM A6YRR9 A6YRR9)
feature not found, no synonym matches a feature (A6YRR9_SCHPM A6YRR9 A6YRR9)
feature not found, no synonym matches a feature (A6YRR9_SCHPM A6YRR9 A6YRR9)
feature not found, no synonym matches a feature (A6YRR9_SCHPM A6YRR9 A6YRR9)
feature not found, no synonym matches a feature (A8DNH7_SCHPM A8DNH7 A8DNH7)
feature not found, no synonym matches a feature (A8DNH7_SCHPM A8DNH7 A8DNH7)
feature not found, no synonym matches a feature (A8DNH7_SCHPM A8DNH7 A8DNH7)
feature not found, no synonym matches a feature (A8DNH7_SCHPM A8DNH7 A8DNH7)
feature not found, no synonym matches a feature (A8DNH7_SCHPM A8DNH7 A8DNH7)
feature not found, no synonym matches a feature (A9QAE1_SCHPM A9QAE1 A9QAE1)
feature not found, no synonym matches a feature (A9QAE1_SCHPM A9QAE1 A9QAE1)
feature not found, no synonym matches a feature (A9QAE1_SCHPM A9QAE1 A9QAE1)
feature not found, no synonym matches a feature (A9QAE1_SCHPM A9QAE1 A9QAE1)
feature not found, no synonym matches a feature (A9QAE1_SCHPM A9QAE1 A9QAE1)
feature not found, no synonym matches a feature (A9QGZ7_SCHPM A9QGZ7 A9QGZ7)
feature not found, no synonym matches a feature (A9QGZ7_SCHPM A9QGZ7 A9QGZ7)
feature not found, no synonym matches a feature (A9QGZ7_SCHPM A9QGZ7 A9QGZ7)
feature not found, no synonym matches a feature (A9QGZ7_SCHPM A9QGZ7 A9QGZ7)
feature not found, no synonym matches a feature (A9QGZ7_SCHPM A9QGZ7 A9QGZ7)
feature not found, no synonym matches a feature (A9QUS1_SCHPM A9QUS1 A9QUS1)
feature not found, no synonym matches a feature (A9QUS1_SCHPM A9QUS1 A9QUS1)
feature not found, no synonym matches a feature (C5IGP5_SCHPM pik1 C5IGP5 pik1)
feature not found, no synonym matches a feature (C5IGP5_SCHPM pik1 C5IGP5 pik1)
feature not found, no synonym matches a feature (C5IGP5_SCHPM pik1 C5IGP5 pik1)
feature not found, no synonym matches a feature (C5IGP5_SCHPM pik1 C5IGP5 pik1)
feature not found, no synonym matches a feature (C5IGP5_SCHPM pik1 C5IGP5 pik1)
feature not found, no synonym matches a feature (C5IGP5_SCHPM pik1 C5IGP5 pik1)
feature not found, no synonym matches a feature (C5IGP5_SCHPM pik1 C5IGP5 pik1)
feature not found, no synonym matches a feature (C5IGP6_SCHPM pik1 C5IGP6 pik1)
feature not found, no synonym matches a feature (C5IGP6_SCHPM pik1 C5IGP6 pik1)
feature not found, no synonym matches a feature (C5IGP6_SCHPM pik1 C5IGP6 pik1)
feature not found, no synonym matches a feature (C5IGP6_SCHPM pik1 C5IGP6 pik1)
feature not found, no synonym matches a feature (C5IGP6_SCHPM pik1 C5IGP6 pik1)
feature not found, no synonym matches a feature (C5IGP6_SCHPM pik1 C5IGP6 pik1)
feature not found, no synonym matches a feature (C5IGP6_SCHPM pik1 C5IGP6 pik1)
feature not found, no synonym matches a feature (C5IGP7_SCHPM pik1 C5IGP7 pik1)
feature not found, no synonym matches a feature (C5IGP7_SCHPM pik1 C5IGP7 pik1)
feature not found, no synonym matches a feature (C5IGP7_SCHPM pik1 C5IGP7 pik1)
feature not found, no synonym matches a feature (C5IGP7_SCHPM pik1 C5IGP7 pik1)
feature not found, no synonym matches a feature (C5IGP7_SCHPM pik1 C5IGP7 pik1)
feature not found, no synonym matches a feature (C5IGP7_SCHPM pik1 C5IGP7 pik1)
feature not found, no synonym matches a feature (C5IGP7_SCHPM pik1 C5IGP7 pik1)
feature not found, no synonym matches a feature (C5IGP8_SCHPM pik1 C5IGP8 pik1)
feature not found, no synonym matches a feature (C5IGP8_SCHPM pik1 C5IGP8 pik1)
feature not found, no synonym matches a feature (C5IGP8_SCHPM pik1 C5IGP8 pik1)
feature not found, no synonym matches a feature (C5IGP8_SCHPM pik1 C5IGP8 pik1)
feature not found, no synonym matches a feature (C5IGP8_SCHPM pik1 C5IGP8 pik1)
feature not found, no synonym matches a feature (C5IGP8_SCHPM pik1 C5IGP8 pik1)
feature not found, no synonym matches a feature (C5IGP8_SCHPM pik1 C5IGP8 pik1)
feature not found, no synonym matches a feature (D0EJL8_SCHPM pdi2 D0EJL8 pdi2)
feature not found, no synonym matches a feature (D7UTC9_SCHPM SOD2 D7UTC9 SOD2)
feature not found, no synonym matches a feature (D7UTC9_SCHPM SOD2 D7UTC9 SOD2)
feature not found, no synonym matches a feature (D7UTC9_SCHPM SOD2 D7UTC9 SOD2)
feature not found, no synonym matches a feature (D7UTC9_SCHPM SOD2 D7UTC9 SOD2)
feature not found, no synonym matches a feature (D7UTC9_SCHPM SOD2 D7UTC9 SOD2)
feature not found, no synonym matches a feature (YI4D_SCHPO SPBC1348.13 G2TRS8 SPBC1348.13)
feature not found, no synonym matches a feature (G9JY47_SCHPM RPB1 G9JY47 RPB1)
feature not found, no synonym matches a feature (G9JY47_SCHPM RPB1 G9JY47 RPB1)
feature not found, no synonym matches a feature (G9JY47_SCHPM RPB1 G9JY47 RPB1)
feature not found, no synonym matches a feature (G9JY47_SCHPM RPB1 G9JY47 RPB1)
feature not found, no synonym matches a feature (G9JY47_SCHPM RPB1 G9JY47 RPB1)
feature not found, no synonym matches a feature (G9JY47_SCHPM RPB1 G9JY47 RPB1)
feature not found, no synonym matches a feature (I7A0C5_SCHPM I7A0C5 I7A0C5)
feature not found, no synonym matches a feature (I7A0C5_SCHPM I7A0C5 I7A0C5)
feature not found, no synonym matches a feature (I7A0C5_SCHPM I7A0C5 I7A0C5)
feature not found, no synonym matches a feature (I7A0C5_SCHPM I7A0C5 I7A0C5)
feature not found, no synonym matches a feature (I7A0C5_SCHPM I7A0C5 I7A0C5)
feature not found, no synonym matches a feature (I7A0C5_SCHPM I7A0C5 I7A0C5)
feature not found, no synonym matches a feature (J9USB3_SCHPM msrB J9USB3 msrB)
feature not found, no synonym matches a feature (J9USB3_SCHPM msrB J9USB3 msrB)
feature not found, no synonym matches a feature (J9USB3_SCHPM msrB J9USB3 msrB)
feature not found, no synonym matches a feature (O14373_SCHPM O14373 O14373)
feature not found, no synonym matches a feature (O14373_SCHPM O14373 O14373)
feature not found, no synonym matches a feature (O14373_SCHPM O14373 O14373)
feature not found, no synonym matches a feature (O14373_SCHPM O14373 O14373)
feature not found, no synonym matches a feature (O14373_SCHPM O14373 O14373)
feature not found, no synonym matches a feature (O14374_SCHPM O14374 O14374)
feature not found, no synonym matches a feature (O14376_SCHPM O14376 O14376)
feature not found, no synonym matches a feature (O14376_SCHPM O14376 O14376)
feature not found, no synonym matches a feature (O14376_SCHPM O14376 O14376)
feature not found, no synonym matches a feature (O14376_SCHPM O14376 O14376)
feature not found, no synonym matches a feature (O14377_SCHPM O14377 O14377)
feature not found, no synonym matches a feature (O14377_SCHPM O14377 O14377)
feature not found, no synonym matches a feature (O14377_SCHPM O14377 O14377)
feature not found, no synonym matches a feature (O14383_SCHPM O14383 O14383)
feature not found, no synonym matches a feature (O14387_SCHPM O14387 O14387)
feature not found, no synonym matches a feature (O14389_SCHPM O14389 O14389)
feature not found, no synonym matches a feature (O14389_SCHPM O14389 O14389)
feature not found, no synonym matches a feature (O14389_SCHPM O14389 O14389)
feature not found, no synonym matches a feature (O14389_SCHPM O14389 O14389)
feature not found, no synonym matches a feature (O14391_SCHPM O14391 O14391)
feature not found, no synonym matches a feature (O14391_SCHPM O14391 O14391)
feature not found, no synonym matches a feature (O14391_SCHPM O14391 O14391)
feature not found, no synonym matches a feature (O14391_SCHPM O14391 O14391)
feature not found, no synonym matches a feature (O14396_SCHPM O14396 O14396)
feature not found, no synonym matches a feature (O14396_SCHPM O14396 O14396)
feature not found, no synonym matches a feature (O14396_SCHPM O14396 O14396)
feature not found, no synonym matches a feature (O14461_SCHPM O14461 O14461)
feature not found, no synonym matches a feature (O14461_SCHPM O14461 O14461)
feature not found, no synonym matches a feature (O14461_SCHPM O14461 O14461)
feature not found, no synonym matches a feature (O14461_SCHPM O14461 O14461)
feature not found, no synonym matches a feature (O42711_SCHPM O42711 O42711)
feature not found, no synonym matches a feature (P78865_SCHPM P78865 P78865)
feature not found, no synonym matches a feature (P78865_SCHPM P78865 P78865)
feature not found, no synonym matches a feature (P78865_SCHPM P78865 P78865)
feature not found, no synonym matches a feature (P78865_SCHPM P78865 P78865)
feature not found, no synonym matches a feature (P78865_SCHPM P78865 P78865)
feature not found, no synonym matches a feature (Q01910_SCHPM retrotransposon Tf1-107 Q01910 retrotransposon Tf1-107)
feature not found, no synonym matches a feature (Q01910_SCHPM retrotransposon Tf1-107 Q01910 retrotransposon Tf1-107)
feature not found, no synonym matches a feature (Q01910_SCHPM retrotransposon Tf1-107 Q01910 retrotransposon Tf1-107)
feature not found, no synonym matches a feature (Q01910_SCHPM retrotransposon Tf1-107 Q01910 retrotransposon Tf1-107)
feature not found, no synonym matches a feature (Q01910_SCHPM retrotransposon Tf1-107 Q01910 retrotransposon Tf1-107)
feature not found, no synonym matches a feature (Q01910_SCHPM retrotransposon Tf1-107 Q01910 retrotransposon Tf1-107)
feature not found, no synonym matches a feature (Q01910_SCHPM retrotransposon Tf1-107 Q01910 retrotransposon Tf1-107)
feature not found, no synonym matches a feature (Q01910_SCHPM retrotransposon Tf1-107 Q01910 retrotransposon Tf1-107)
feature not found, no synonym matches a feature (Q01910_SCHPM retrotransposon Tf1-107 Q01910 retrotransposon Tf1-107)
feature not found, no synonym matches a feature (Q06Y82_SCHPM COXII Q06Y82 COXII)
feature not found, no synonym matches a feature (Q06Y82_SCHPM COXII Q06Y82 COXII)
feature not found, no synonym matches a feature (Q06Y82_SCHPM COXII Q06Y82 COXII)
feature not found, no synonym matches a feature (Q06Y82_SCHPM COXII Q06Y82 COXII)
feature not found, no synonym matches a feature (Q06Y82_SCHPM COXII Q06Y82 COXII)
feature not found, no synonym matches a feature (Q06Y82_SCHPM COXII Q06Y82 COXII)
feature not found, no synonym matches a feature (Q06Y82_SCHPM COXII Q06Y82 COXII)
feature not found, no synonym matches a feature (Q06Y82_SCHPM COXII Q06Y82 COXII)
feature not found, no synonym matches a feature (Q06Y82_SCHPM COXII Q06Y82 COXII)
feature not found, no synonym matches a feature (Q06Y82_SCHPM COXII Q06Y82 COXII)
feature not found, no synonym matches a feature (YDA3_SCHPO SPAC1F12.03c Q10345 SPAC1F12.03c)
feature not found, no synonym matches a feature (YDA3_SCHPO SPAC1F12.03c Q10345 SPAC1F12.03c)
feature not found, no synonym matches a feature (YDA3_SCHPO SPAC1F12.03c Q10345 SPAC1F12.03c)
feature not found, no synonym matches a feature (YDA3_SCHPO SPAC1F12.03c Q10345 SPAC1F12.03c)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q12728_SCHPM Q12728 Q12728)
feature not found, no synonym matches a feature (Q152U6_SCHPM Q152U6 Q152U6)
feature not found, no synonym matches a feature (Q152U6_SCHPM Q152U6 Q152U6)
feature not found, no synonym matches a feature (Q152U6_SCHPM Q152U6 Q152U6)
feature not found, no synonym matches a feature (Q152U6_SCHPM Q152U6 Q152U6)
feature not found, no synonym matches a feature (Q1L843_SCHPM Q1L843 Q1L843)
feature not found, no synonym matches a feature (Q1L858_SCHPM Q1L858 Q1L858)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35901_SCHPM Q35901 Q35901)
feature not found, no synonym matches a feature (Q35904_SCHPM Q35904 Q35904)
feature not found, no synonym matches a feature (Q564N4_SCHPM MOE1 Q564N4 MOE1)
feature not found, no synonym matches a feature (Q564N4_SCHPM MOE1 Q564N4 MOE1)
feature not found, no synonym matches a feature (Q564N4_SCHPM MOE1 Q564N4 MOE1)
feature not found, no synonym matches a feature (Q683Z9_SCHPM Cds1 Q683Z9 Cds1)
feature not found, no synonym matches a feature (Q6LEP6_SCHPM ssp2+ Q6LEP6 ssp2+)
feature not found, no synonym matches a feature (Q6LEP6_SCHPM ssp2+ Q6LEP6 ssp2+)
feature not found, no synonym matches a feature (Q6LEP6_SCHPM ssp2+ Q6LEP6 ssp2+)
feature not found, no synonym matches a feature (Q6LEP6_SCHPM ssp2+ Q6LEP6 ssp2+)
feature not found, no synonym matches a feature (Q6LEP6_SCHPM ssp2+ Q6LEP6 ssp2+)
feature not found, no synonym matches a feature (Q6LEP6_SCHPM ssp2+ Q6LEP6 ssp2+)
feature not found, no synonym matches a feature (Q7YFV0_SCHPM CoxII Q7YFV0 CoxII)
feature not found, no synonym matches a feature (Q7YFV0_SCHPM CoxII Q7YFV0 CoxII)
feature not found, no synonym matches a feature (Q7YFV0_SCHPM CoxII Q7YFV0 CoxII)
feature not found, no synonym matches a feature (Q7YFV0_SCHPM CoxII Q7YFV0 CoxII)
feature not found, no synonym matches a feature (Q7YFV0_SCHPM CoxII Q7YFV0 CoxII)
feature not found, no synonym matches a feature (Q7YFV0_SCHPM CoxII Q7YFV0 CoxII)
feature not found, no synonym matches a feature (Q7YFV0_SCHPM CoxII Q7YFV0 CoxII)
feature not found, no synonym matches a feature (Q7YFV0_SCHPM CoxII Q7YFV0 CoxII)
feature not found, no synonym matches a feature (Q7YFV0_SCHPM CoxII Q7YFV0 CoxII)
feature not found, no synonym matches a feature (Q7YFV0_SCHPM CoxII Q7YFV0 CoxII)
feature not found, no synonym matches a feature (Q9T654_SCHPM cox1I1a Q9T654 cox1I1a)
feature not found, no synonym matches a feature (Q9T654_SCHPM cox1I1a Q9T654 cox1I1a)
feature not found, no synonym matches a feature (Q9T654_SCHPM cox1I1a Q9T654 cox1I1a)
feature not found, no synonym matches a feature (Q9T654_SCHPM cox1I1a Q9T654 cox1I1a)
feature not found, no synonym matches a feature (S6BDF9_SCHPM S6BDF9 S6BDF9)
feature not found, no synonym matches a feature (S6BDG7_SCHPM rho1 S6BDG7 rho1)
feature not found, no synonym matches a feature (S6BDG7_SCHPM rho1 S6BDG7 rho1)
feature not found, no synonym matches a feature (S6BME7_SCHPM fip1 S6BME7 fip1)
feature not found, no synonym matches a feature (S6BME7_SCHPM fip1 S6BME7 fip1)
feature not found, no synonym matches a feature (S6BMF4_SCHPM spt6 S6BMF4 spt6)
feature not found, no synonym matches a feature (S6BMF4_SCHPM spt6 S6BMF4 spt6)
feature not found, no synonym matches a feature (S6BMF4_SCHPM spt6 S6BMF4 spt6)
feature not found, no synonym matches a feature (S6BMF4_SCHPM spt6 S6BMF4 spt6)
feature not found, no synonym matches a feature (S6BMF4_SCHPM spt6 S6BMF4 spt6)
feature not found, no synonym matches a feature (S6BMF4_SCHPM spt6 S6BMF4 spt6)
feature not found, no synonym matches a feature (S6BMF4_SCHPM spt6 S6BMF4 spt6)
feature not found, no synonym matches a feature (S6BMF4_SCHPM spt6 S6BMF4 spt6)
feature not found, no synonym matches a feature (S6BSJ4_SCHPM S6BSJ4 S6BSJ4)
feature not found, no synonym matches a feature (S6BSJ4_SCHPM S6BSJ4 S6BSJ4)
feature not found, no synonym matches a feature (S6BSJ4_SCHPM S6BSJ4 S6BSJ4)
feature not found, no synonym matches a feature (S6BSJ4_SCHPM S6BSJ4 S6BSJ4)
feature not found, no synonym matches a feature (S6BSK0_SCHPM spt6 S6BSK0 spt6)
feature not found, no synonym matches a feature (S6BSK0_SCHPM spt6 S6BSK0 spt6)
feature not found, no synonym matches a feature (S6BSK0_SCHPM spt6 S6BSK0 spt6)
feature not found, no synonym matches a feature (S6BSK0_SCHPM spt6 S6BSK0 spt6)
feature not found, no synonym matches a feature (S6BSK0_SCHPM spt6 S6BSK0 spt6)
feature not found, no synonym matches a feature (S6BSK0_SCHPM spt6 S6BSK0 spt6)
feature not found, no synonym matches a feature (S6BSK3_SCHPM cdc22 S6BSK3 cdc22)
feature not found, no synonym matches a feature (S6BSK3_SCHPM cdc22 S6BSK3 cdc22)
feature not found, no synonym matches a feature (S6BSK3_SCHPM cdc22 S6BSK3 cdc22)
feature not found, no synonym matches a feature (S6BSK3_SCHPM cdc22 S6BSK3 cdc22)
feature not found, no synonym matches a feature (S6CCW0_SCHPM rps2502 S6CCW0 rps2502)
feature not found, no synonym matches a feature (S6CCW7_SCHPM has1 S6CCW7 has1)
feature not found, no synonym matches a feature (S6CCW7_SCHPM has1 S6CCW7 has1)
feature not found, no synonym matches a feature (S6CCW7_SCHPM has1 S6CCW7 has1)
feature not found, no synonym matches a feature (S6CCW7_SCHPM has1 S6CCW7 has1)

Original comment by: ValWood

**Comment by ValWood** [comment]
I think this is dealt with another way...
