### ISSUE TITLE
capturing penetrance as a %

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#268]
We would like to begin to be able to capture pentracne as a percentage when possible, enven though we do not intend to display it immediately.

Therefore we would like you to accept annotations in this format into chado:

current
has_penetrance(FYPO_EXT:0000001)

new
 % range     :     has_penetrance(FYPO_EXT:0000001),10%-20%
absolute %   :     has_penetrance(FYPO_EXT:0000001),
or 
has_penetrance(10%)
has_penetrance(10%-20%)

Original comment by: ValWood

**Comment by kimrutherford** [comment]
Drat!  The code isn't coping.  From the latest log:
  warning in 1203df6a6f3957f8: in annotation extension for 1203df6a6f3957f8-genotype-2, can't parse identifier: 20%
