### ISSUE TITLE
load annotation extensions on external data

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#269]
According to Rachel there are 98 extensions from IntAct and 4 from UniProt

However when I look in the current gaf pombase-build-2013-11-25-v1-l1.gaf

 cut -f 15,16 pombase-build-2013-11-25-v1-l1.gaf  | grep PomBase | grep "(" |wc
    1872 
rows from PomBase with extensions

but none  when I do
cut -f 15,16 pombase-build-2013-11-25-v1-l1.gaf  | grep -v PomBase | grep "(" |wc

which should show any extensions on these:
 741 GOC        
2001 InterPro   
3864 UniProt

Could you have a look in the GOC file and see if they are there. If they are we are discarding them during import.

Original comment by: ValWood

**Comment by ValWood** [comment]
duplicate
https://github.com/pombase/canto/issues/1155
