### ISSUE TITLE
logs: report incorrectly formated mutated multiple  amino acid description

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#273]
I noticed on this page that the allele was reported
D118A adn C198S instead of   D118A,C198S 

can you report allle descrptions which are not in the  format documented in the Canto instructions in the logs 

(probalby quick but not urgent I fixed this one and there may not be any others)

Original comment by: ValWood

**Comment by ValWood** [comment]
replaced by  https://github.com/pombase/pombase-chado/issues/527
