### ISSUE TITLE
GPAD/GPI export from chado

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#276]
Export GO annotations and supporting data in GPAD and GPI formats instead of GAF.

File format spec here:
http://wiki.geneontology.org/index.php/Final_GPAD_and_GPI_file_format

raise priority when GOC set a deadline - that's when we'll actually have to do it

Original comment by: mah11

**Comment by ValWood** [comment]
@hdrabkin

when we do this, we should also try to include PRO 

Harold:
Hi Val

Our GPI file here will have samples of how we associate them.

Here are a couple of examples

 

They are treated as separate identifiers (hence the PR in column 1), but then map to the mgi gene (MGI:MGI:))

Here’s one for an isoform:

PR           Q9ESQ8-2             mNPVF/iso:m2    pro-FMRFamide-related neuropeptide VF isoform m2 (mouse)                             protein  taxon:10090        MGI:MGI:1926488            UniProtKB:Q9ESQ8-2

 

Here’s one for a modified form (not of the example above).

 

PR           000030074           mLNP/Phos:1       protein lunapark phosphorylated 1 (mouse)                                protein  taxon:10090                MGI:MGI:1918115

**Comment by mah11** [comment]
upping to medium priority because GO has a timeline at last:
- June 1st: finalize annotation properties and header
- July 1st: review by contributing groups
- October 1st: implementation

proposed spec: https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md

**Comment by mah11** [comment]
Update: GO now has a ticket angling for comments on the GPAD/GPI spec:

https://github.com/geneontology/go-annotation/issues/2864

... so now seems like a good time for @kimrutherford to take a look and make sure there won't be any problems producing those files.

**Comment by kimrutherford** [comment]
> take a look and make sure there won't be any problems producing those files.

I think it won't be a problem.  The only part that will require a bit of care (if I'm reading it correctly) is the mapping from GO evidence codes to ECO.

**Comment by mah11** [comment]
Yeah. They've tried to include cross-references to GO codes in ECO, but IIRC there have been a few where mapping wasn't totally straightforward. Try looking at the "xref: GOECO:"  lines in ECO and see how much that covers.

**Comment by mah11** [comment]
It might be worth paying attention to this ticket - https://github.com/evidenceontology/evidenceontology/issues/251

**Comment by mah11** [comment]
Chris also recommends this: https://github.com/evidenceontology/evidenceontology/wiki/Gene-Ontology-GafEcoMapping

**Comment by mah11** [comment]
or the "derived" version might be better so we don't "have to walk up the ECO graph yourself when going from ECO -> GAF" ... although I think we're mostly concerned about going from GAF -> ECO

https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt

**Comment by mah11** [comment]
Returning to this ticket again now that GO is seeking sign-off on the spec (linked above) ... there are two main points for us -- one is the relations between terms/IDs and gene products that GO now wants, and the other is submitting extensions with the small set of relations that GO now allows (where we've retained some more specific ones locally).

Term-gene product relations for GPAD column 3:

- For molecular function (F), use RO:0002327 'enables' (hideous usage, but it's what they've settled on) unless we have explicitly used contributes_to (RO:0002326).
- For biological process (P), ignore all the blather and just always use RO:0002331 'involved in'.
- For cellular component (C) it could be a bit tricky.
  - If we have used colocalizes_with anywhere, leave it (i.e. RO:0002325) as the relation, but I don't think we do use it any more.
  - For the rest, GO's preference depends on the term ancestry, so if this is realistically feasible:
    - if_descendant_of GO:0032991, use BFO:0000050 'part of'
    - otherwise, use RO:0001025 'located in'
   - If it would be a colossal pain in the ass to make this distinction, we could see if just using 'part of' (BFO:0000050) for all CC causes any ructions.

Extension relations (also noted for GAF in #744):

- Delete all "negated" extensions (i.e. ones that use not_happens_during or not_exists_during).
- Convert a whole bunch of relations to RO:0002233 (has input):
  - has_direct_input
  - regulates_activity_of
  - has_regulation_target
  - directly_negatively_regulates
  - directly_positively_regulates
- Convert occurs_at to BFO:0000066 (occurs in)
- I don't think we're using regulates_expression_of, regulates_transcription_of, or regulates_translation_of, but if we ever do, convert them to (wait for it) RO:0002233 (has input).

**Comment by kimrutherford** [comment]
Thanks Midori.  I'm very glad you have a handle on that.

> For the rest, GO's preference depends on the term ancestry, so if this is realistically feasible:
>  if_descendant_of GO:0032991, use BFO:0000050 'part of' otherwise, use RO:0001025 'located in'
> If it would be a colossal pain in the ass to make this distinction, we could see if just using 'part of' (BFO:0000050) for all CC causes any ructions.

It should be OK.  I don't recognise "if_descendant_of" though.

**Comment by mah11** [comment]
>  I don't recognise "if_descendant_of" though.

Don't worry, as long as it's clear how the file should come out. I cribbed "if_descendant_of" from website display config (it's not a relation that would end up in any output files).

**Comment by kimrutherford** [comment]
In the GPI file do we need to put anything in columns 7 to 11?  They''re all optional.

**Comment by kimrutherford** [comment]
As a first step I've added the code to write a GPI file during the nightly update.  That's the easy part of GPI/GPAD.

Here's a sample of the output:
http://curation.pombase.org/misc/gene_product_information_taxonid_4896.tsv

> In the GPI file do we need to put anything in columns 7 to 11? 

I've left those columns empty for now.

I'll chip away at implementing GPAD writing.

**Comment by mah11** [comment]
Great start; thanks!

It does need more tweaking (sorry to bear bad news).

This is probably the most important point:
We definitely shouldn't put the gene product description in column 2. That column is for the gene symbol; it's set up that way to accommodate species where the gene name and gene symbol are different (e.g. all those mad Drosophila names, where the symbols are usually abbreviations).

We might as well just put the gene name in both columns 2 and 3. It's redundant for us (and SGD) but I think it's the best workaround we've got.

> In the GPI file do we need to put anything in columns 7 to 11? They're all optional.

Unfortunately, it's not quite that simple.

- For protein-coding genes, we do have to put the UniProtKB accession in column 10. This is kind of buried, and if you think it looks not-entirely-consistent with "cardinality 0 or greater", well, I'm right there with ya.

- On a related note, I'm finding the spec a bit woolly with respect to whether we can leave SO:0000704 in column 5 for all rows, or if we're actually required to use SO:0001217 for protein-coding genes (our feature type = protein coding) and SO:0001263 for the rest. Unless it would be a big pain, it might be worth using the more specific SO IDs.

- Since we can't put the gene product description in column 2, we could include it in column 11 with the "go-annotation-summary" tag (e.g. go-annotation-summary=M phase inhibitor protein kinase Wee1). Despite using go-annotation-summary as the tag text, the description of allowed content is "A textual gene or gene product description.", so they'd better not complain.

**Comment by kimrutherford** [comment]
> Extension relations (also noted for GAF in #744):

I'm not sure what term ID to use for "exists_during".  There is a Typedef in gorel.obo with the id "exists_during".  Term IDs without a prefix look wrong to me.

It also has "xref: GOREL:0000032".  Maybe we should use that instead?  Any thoughts?

**Comment by kimrutherford** [comment]
> I'm not sure what term ID to use for "exists_during"

Some for: activated_by

**Comment by mah11** [comment]
For exists_during, watch this ticket: https://github.com/oborel/obo-relations/issues/384https://github.com/oborel/obo-relations/issues/384 ... and I guess use the GOREL thing in the meantime?

I think we can just ditch the extensions that use activated_by in what generate for GO -- we only have 4, and we may get round to changing or removing them anyway.

**Comment by kimrutherford** [comment]
Thanks, I'll use that for now.

**Comment by kimrutherford** [comment]
I've made these changes:

- > We might as well just put the gene name in both columns 2 and 3.
- > For protein-coding genes, we do have to put the UniProtKB accession in column 10.
- > Since we can't put the gene product description in column 2, we could include it in column 11 with the "go-annotation-summary" tag

I haven't fixed the SO term for the features yet.  Currently it's either SO:0000704 (gene) or SO:0000336 (pseudogene).  I'll fix that soon.

**Comment by kimrutherford** [comment]
I've also had a first pass at the GAPD file.  It's not done yet. (Especially column 3 which current just says "dunno" on every row).

> Chris also recommends this: https://github.com/evidenceontology/evidenceontology/wiki/Gene-Ontology-GafEcoMapping

The evidence column is populated using this GO-ECO mapping.

Here's an example: http://curation.pombase.org/misc/gene_product_annotation_data_taxonid_4896.tsv

From tomorrow (if all goes well) the in-progress GPI and GAPD files will be written out each night and should appear here:
https://curation.pombase.org/dumps/latest_build/misc/

I'll do some more work on the output tomorrow.

> Extension relations (also noted for GAF in #744):

These rules are encoded in a new section of the config file called "extension_relation_mappings", currently at the end.  It looks like this for now.  If the value is `null` then that extension relation will not be written to the GPAD file.   Please tweak as needed.

```json
    "gpad_gpi": {
      "extension_relation_mappings": {
        "not_happens_during": null,
        "not_exists_during": null,
        "activated_by": null,
        "exists_during": "GOREL:0000032",
        "has_direct_input": "RO:0002233",
        "regulates_activity_of": "RO:0002233",
        "has_regulation_target": "RO:0002233",
        "directly_negatively_regulates": "RO:0002233",
        "directly_positively_regulates": "RO:0002233",
        "regulates_expression_of": "RO:0002233",
        "regulates_transcription_of": "RO:0002233",
        "regulates_translation_of": "RO:0002233",
        "occurs_at": "BFO:0000066"
      }
    }
```

**Comment by mah11** [comment]
> [various GPI fixes]

yay, thanks

> (Especially column 3 which current just says "dunno" on every row)

I am highly sympathetic to this attitude.

The proto-GPAD looks like it's shaping up well, to the extent that I can tell. Thanks again.

**Comment by kimrutherford** [comment]
> If we have used colocalizes_with anywhere, 

I can't see any examples in the nightly GAF file.

> > I don't recognise "if_descendant_of" though.
>
> Don't worry, as long as it's clear how the file should come out.

Sorry, it's not clear to me.  Could you explain this more?  What does "if_descendant_of GO:0032991" mean?  Just "is_a/part_of GO:0032991"?

For now column 3 for CC annorations is BFO:0000050 if the term is_a GO:0032991 and RO:0001025 otherwise.  Let me know if that short include part_of GO:0032991 for BFO:0000050.

Am example is here:
http://curation.pombase.org/misc/gene_product_annotation_data_taxonid_4896.tsv

**Comment by kimrutherford** [comment]
> Unless it would be a big pain, it might be worth using the more specific SO IDs.

I've changed to using more specific gene SO IDs as you suggested.  Like SO:0001217 "protein_coding_gene" and SO:0001268 "snRNA_gene".  If less specific terms are needed we can change the output.

This is configured in yet another setting in the config file ("transcript_gene_so_term_map"), which is a map from the SO term of the transcript (from Chado) to the specific SO term to use for the gene in the GPI file.  We just use the general "gene" and "pseudogene" SO terms for genes in Chado hence the need for configuration.  This table could probably have been generated by inferring things directly from the Sequence Ontology but that was going to hurt my brain and the list isn't going to change often.

The table looks like this:
```json
      "transcript_gene_so_term_map": {
        "SO:0000234": "SO:0001217",
        "SO:0000516": "SO:0000336",
        "SO:0000252": "SO:0001637",
        "SO:0000253": "SO:0001272",
        "SO:0000274": "SO:0001268",
        "SO:0000275": "SO:0001267",
        "SO:0000655": "SO:0001263"
      }
```

The updated file is here:
http://curation.pombase.org/misc/gene_product_information_taxonid_4896.tsv

Now that the files are getting closer to ready, do you know if there is a GPAD/GPI validator tool that we can test them on?

**Comment by mah11** [comment]
> I've changed to using more specific gene SO IDs as you suggested. Like SO:0001217 "protein_coding_gene" and SO:0001268 "snRNA_gene". 

That looks excellent. I don't think that column needs any further work.

> What does "if_descendant_of GO:0032991" mean? Just "is_a/part_of GO:0032991"?

Yep, that's it. Sorry to have been overly cryptic.

> For now column 3 for CC annotations is BFO:0000050 if the term is_a GO:0032991 and RO:0001025 otherwise. Let me know if that should include part_of GO:0032991 for BFO:0000050.

Yes, I think it should include part_of, and then it'll be ready for prime time.

> do you know if there is a GPAD/GPI validator tool that we can test them on?

Aaahahahahahaha ha ha he's funny :P

Seriously, I haven't heard anything about a validation tool per se, but there's a woollier claim in the [minutes from the July 28th GO annotation call](http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2020-07-28) that "Berkeley will have parsing scripts available to share and can otherwise assist in helping groups with the transition". So I guess ping them via the ticket they have open for comments? It's https://github.com/geneontology/go-annotation/issues/2864

**Comment by kimrutherford** [comment]
> Yes, I think it should include part_of, and then it'll be ready for prime time.

I've made that config and code change.  It looks look only there are only one term and two annotations where it makes a difference.

GO:0042788 polysomal ribosome: https://www.pombase.org/term/GO:0042788

**Comment by kimrutherford** [comment]
> So I guess ping them via the ticket they have open for comments?

Thanks for the suggestion.  I've done that.

Perhaps we're a bit ahead of the game?  I hope the GPAD/GPI spec doesn't change too much.  :-)

**Comment by kimrutherford** [comment]
I was thinking about closing this issue then I noticed this comment:

> when we do this, we should also try to include PRO

What does that involve?

**Comment by kimrutherford** [comment]
While writing this essay, https://github.com/pombase/pombase-chado/issues/744#issuecomment-675251087, I realised that the GPAD output has "binds(...)" where it should have "with" entries due to: pombase/website#108

That needs fixing.

**Comment by mah11** [comment]
> when we do this, we should also try to include PRO
> 
> What does that involve?

I don't know, but I suspect it might be something we could hive off into its own ticket, to be got round to in a while rather than making the rest of the GPAD/GPI export wait for it.

**Comment by kimrutherford** [comment]
> I suspect it might be something we could hive off into its own ticket,

I think so too.  I'll leave that for Val to summarise in a new issue when she's back from her world tour.

**Comment by ValWood** [comment]
I'n not sure that anything needs doing especially for PRO.  If we use PRO as modified by forms that should be handled automatically? I would close. If anything is required we can open a new ticket once we know what it is.
Val

**Comment by kimrutherford** [comment]
OK, thanks Val.

I'll do this then close the issue: https://github.com/pombase/pombase-chado/issues/276#issuecomment-675268875

Once GO start accepting or validating GPAD/GPI files I'll open new issues for any problems.

**Comment by kimrutherford** [comment]
>  I realised that the GPAD output has "binds(...)" where it should have "with" entries due to: pombase/website#108

Fixed!  (After tonight's load)

So I'll close this issue and wait until GO are ready for GPAD/GPI files.

For reference, the files are here for now:
https://curation.pombase.org/dumps/latest_build/misc/gene_product_annotation_data_taxonid_4896.tsv
https://curation.pombase.org/dumps/latest_build/misc/gene_product_information_taxonid_4896.tsv
and are generated every night.
