### ISSUE TITLE
remove duplicate lines from GAF

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#303]
The last few GAFs have had 3 duplicate lines caught by the older checking script. They arise for a couple of different reasons (2 from UniProt; one from us stripping out extensions that GO can't use) but until the happy day when they can be fixed further upstream ...

Do something to remove duplicate lines at the point of producing the GAF.

Low priority because it's not that big a deal for me to delete them manually in the meantime.

Original comment by: mah11

**Comment by ValWood** [comment]
Is this still an issue, I guess so...

**Comment by ValWood** [comment]
We have log files for duplicate GO now.
