### ISSUE TITLE
Filtering redundant annotations is very slow

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#304]
The "filtering redundant annotations" step of the Chado load (for filtering GO annotation) is very slow - it takes more than 2 hours.  

Original comment by: kimrutherford

**Comment by ValWood** [comment]
@kimrutherford is this still an issue?

**Comment by kimrutherford** [comment]
> is this still an issue?

Yep.

**Comment by ValWood** [comment]
Ah, talking to yourself...

**Comment by kimrutherford** [comment]
> Yep.

Nope.

Fixed by 2009421d2b5f075c in 2014.  :-)
