### ISSUE TITLE
Exporting GAF files is very slow

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#305]
It takes over an hour to export the GAF file from Chado.  Very, very slow!

Original comment by: kimrutherford

**Comment by ValWood** [comment]
Is this still an issue?

**Comment by kimrutherford** [comment]
> Is this still an issue?

Yep, it's still stupidly slow.

**Comment by ValWood** [comment]
Still an issue?

**Comment by kimrutherford** [comment]
> Still an issue?

Yep.  The overnight load gets very slightly slower each time an annotation gets added.  At some point it will be too slow to run overnight. Then things like this will become more urgent.

**Comment by kimrutherford** [comment]
After more thought, this is very low priority.

Just replacing oliver0 would solve this problem.  And replacing oliver0 is a thing that's likely to happen soon anyway.

I'm able to run the full load on my not super high-spec desktop in less than 4 hours.  It takes more than 8 hours on oliver0.

**Comment by kimrutherford** [comment]
> Just replacing oliver0 would solve this problem.

On the new server (oliver1) the load finishes in 3 hours instead of 8.  I think we're going to be fine for a few years of growth.

**Comment by ValWood** [comment]
That sounds like a reasonable improvement...a good side benefit!

**Comment by Antonialock** [comment]
bidaily updates? :p

**Comment by kimrutherford** [comment]
> bidaily updates?

Probably not.  :-)

But!  Because it will be a lot quicker there's more time for me fix Chado load problems and then re-run things before the UK morning.  So daily updates will be a bit more reliably daily, rather than daily-ish as they are at the moment.

**Comment by ValWood** [comment]
Actually, if this is now a non-issue this ticket can be closed?

**Comment by ValWood** [comment]
Closing, reopen if you want to do anything else
