### ISSUE TITLE
Make --organism-taxonid arg optional on pombase-import.pl

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#307]
The pombase-import.pl script assumes that the taxon ID of each organism is stored as an organismprop.  We should remove that requirement as the taxon_id organismprop is PomBase specific.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
Is tis still current. Does it affect PHIBase?

**Comment by kimrutherford** [comment]
It's still current.  I think the Rothamsted people said that they have a taxon ID for all the hosts.

**Comment by kimrutherford** [comment]
I'm closing this because it's still not important after 4 years.
