### ISSUE TITLE
Infer  paralogs (and report on gene pages)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#31]
if A is orthologous to Y
and
B is orthologous to Y
then A and B are paralogs

**Comment by ValWood** [comment]
website related ticket
https://github.com/pombase/website/issues/486

**Comment by kimrutherford** [comment]
This is the oldest pombase-chado issue and it's medium priority.  It's not too much work (a few hours to half a day, depending) if this is still the plan:

> if A is orthologous to Y
> and
> B is orthologous to Y
> then A and B are paralogs

If we infer the paralogs, should we keep the manually annotated ones in the contig files?

See also:
 - https://github.com/pombase/website/issues/2195

**Comment by ValWood** [comment]
We should just infer them, we don't need the manually annotated ones.
We need to use ortholog against S. cerevisiae as the speciation nose to make the call (paralogy differes based on species of comparison)

**Comment by ValWood** [comment]
Actually we can't fully automate. 
We have the ones we can infer because 2 genes will be orthologs of the same S. cerevisiae protein. Then we have the ones we can't infer because they are fission yeast-specific duplicates. We need to keep those.

**Comment by kimrutherford** [comment]
From a quick look there are some orthologs that are inconsistent?

----------------------

pombe gpd1 is an ortholog of cerevisiae GPD1 and GPD2.
but pombe gpd2 is an ortholog only of GPD1

gpd1: https://www.pombase.org/gene/SPBC215.05
gpd2: https://www.pombase.org/gene/SPAC23D3.04c

----------------------

These three genes have three cerevisiae orthologs in common, but SPBC16A3.17c has an extra ortholog: VBA5 (YKR105C) 
 - https://www.pombase.org/gene/SPAC1399.02
 - https://www.pombase.org/gene/SPBC16A3.17c
 - https://www.pombase.org/gene/SPAC3H1.06c

-----------------------

These two have similar cerevisiae ortholog lists:
 - https://www.pombase.org/gene/SPAPB24D3.09c
 - https://www.pombase.org/gene/SPCC18B5.01c
but SPCC18B5.01c has an extra one: AUS1 (YOR011W)

**Comment by ValWood** [comment]
I fixed the missing  S. cerevisiae paralogs in this ticket

**Comment by kimrutherford** [comment]
Should we make a PB_REF for the inferred paralogs?

**Comment by kimrutherford** [comment]
> I fixed the missing S. cerevisiae paralogs in this ticket

Hi Val.  Did you commit these fixes?  I can't see the changes on the website.

**Comment by ValWood** [comment]
Fist draft of PB reference:

Paralog "calls"  are based on the common ancestor of fission yeast and budding yeast  (approximates to the fungal common ancestor for this purpose).  Paralogs are automated so that where  S. pombe gene A is orthologous to  S. cerevisiae gene Y and  S. pombe gene B is orthologous to  S. cerevisiae gene Y then gene A and gene  B are paralogs. These paralogs are supplemented by manually curated oparalogs  for S. pombe specific gene family duplications or larger expansions.

**Comment by kimrutherford** [comment]
Sorry Val, I've found some more inconsistent ortholog.  The ones I reported a few days ago were just from a quick check.  I've now done a more complete check:

SPBC16C6.01c has orthologs YBR030W|YDR257C
SPAC688.14 has just YDR257C

SPAC2E1P3.01  has  YCR102C|YLR460C|YNL134C
SPBC337.11   has  YBL069W|YCR102C|YER101C|YLR460C|YNL134C

For human:

SPAC12G12.03    HNRNPM
SPAC328.05      HNRNPM|MYEF2

SPAC23E2.02     KDM1B
SPBC146.09c     KDM1A|KDM1B

SPAC1782.08c    REXO1
SPAC637.09      REXO1|REXO1L1P|REXO5

SPAC11E3.01c    EP400|SRCAP
SPCC1795.08c    EP400|EP400P1

SPAC6F6.04c     MFSD11|UNC93A|UNC93B1
SPAC922.05c     MFSD11|UNC93A

SPBC577.13      OCRL
SPAC9G1.10c     INPP5J|OCRL

SPBC1347.02     FKBP1B
SPBC839.17c     FKBP1A|FKBP1B

SPCC1919.01     CAMKK2
SPCC297.03      CAMKK1|CAMKK2

SPBC16H5.08c    ABCF2
SPBC29A3.09c    ABCF3
SPCC417.08      ABCF2|ABCF3

**Comment by kimrutherford** [comment]
I've had first attempt at implementing this.

Here's how it looks on my desktop: https://desktop.kmr.nz/gene/SPBC19F8.06c

I'll change the table so that it's ordered by gene name to make it tidier.

![image](https://github.com/user-attachments/assets/0cea680d-b834-4a70-a991-cca4b2fe59d9)

**Comment by ValWood** [comment]
I don't see it on the desktop  link?

**Comment by kimrutherford** [comment]
Sorry, I was testing something else.  Try it now: https://desktop.kmr.nz/gene/SPAP7G5.06

**Comment by kimrutherford** [comment]
The Paralogs section is missing a help text / help link.  I'll do that before closing the issue.

The docs need a bit of work though:
https://www.pombase.org/documentation/orthologs

**Comment by ValWood** [comment]
I'll put ortholog docs on my list, I have been thinking about orthologs a lot.

**Comment by kimrutherford** [comment]
> I'll put ortholog docs on my list, I have been thinking about orthologs a lot.

The ortholog and paralog docs are here if you'd like to add or edit anything:
https://github.com/pombase/website/blob/master/src/docs/documentation/orthologs.md

I'll try to pad out the paralogs section tomorrow.

**Comment by kimrutherford** [comment]
I might have jumped the gun, but the inferred paralogs are now on the main site: https://www.pombase.org/gene/SPAP7G5.06

**Comment by ValWood** [comment]
> I might have jumped the gun, but the inferred paralogs are now on the main site: https://www.pombase.org/gene/SPAP7G5.06


Thats fine, they look great , I will review and fix the missing ones today and review the docs, we can announce tommorrow

**Comment by kimrutherford** [comment]
> I'll try to pad out the paralogs section tomorrow.

Sorry, I didn't get very far.

Current text:
```
The Paralogs section lists any curated paralogous fission yeast genes.
```

I guess we need to say that most paralogs are now inferred by orthology with S. cerevisiae.  But I wasn't sure how to word that and I didn't know what else needs to be added.

**Comment by ValWood** [comment]
Paralog text

Paralogs are based on the common ancestor of fission yeast and budding yeast (this approximates to the fungal common ancestor). Paralog assignments are automated based on the manually curated orthoog assignments,  so that where S. pombe gene A is orthologous to S. cerevisiae gene Y, and S. pombe gene B is orthologous to S. cerevisiae gene Y,  then gene A and gene B are paralogs. The automated paralogs are supplemented by manually curated paralogs for S. pombe specific gene family duplications or larger expansions.

**Comment by kimrutherford** [comment]
Thanks, that's great.  I've put that text in for tonight's load.

**Comment by ValWood** [comment]
I fixed the orthologs, there were a few howlers in there!

**Comment by kimrutherford** [comment]
> I fixed the orthologs, there were a few howlers in there!

Thanks!

**Comment by kimrutherford** [comment]
Sorry Val, there is one last inconsistent human ortholog to fix:

```
SPBC16A3.18       HNRNPM
SPAC12G12.03      HNRNPM|MYEF2
SPAC328.05        HNRNPM|MYEF2
```

The annotations for `SPAC328.05`  and `SPBC16A3.18` are in `pombe-embl/orthologs/conserved_multi.txt`.  The annotation for `SPAC12G12.03` is in the contig files.

**Comment by ValWood** [comment]
cip2
currently doesn't have
conserved in metazoa 
or conserved in  vertebrates
in artemis. but, it appears on the gene pages. I don't remember ever recording this anywhere but in artemis. did I misremember? I can't figure out where it is coming from?  is there any inference if it is present on a paralog?

**Comment by kimrutherford** [comment]
Looks like it does to me?

```
FT                   /systematic_id="SPAC12G12.03"
FT                   /controlled_curation="term=rrm RNA recognition motif;
FT                   date=19700101"
FT                   /controlled_curation="term=orthologous to S. cerevisiae
FT                   YBL051C; date=19700101"
FT                   /controlled_curation="term=species distribution, conserved
FT                   in eukaryotes; date=20081110"
FT                   /controlled_curation="term=species distribution, conserved
FT                   in metazoa; date=20081110"
FT                   /controlled_curation="term=species distribution, conserved
FT                   in vertebrates; date=20081110"
```

**Comment by ValWood** [comment]
weird, i must have removed it? I put it back

**Comment by ValWood** [comment]
inconsistent ortholog fixed

**Comment by kimrutherford** [comment]
> inconsistent ortholog fixed

Thanks!  I think is issue is finished.

**Comment by ValWood** [comment]
yay
