### ISSUE TITLE
Cope better with multiple features with the same name

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#312]
When the loader queries for a feature by name and gets two results it throws an error like:

c29f51c4cc86096d: DBIx::Class::Schema::txn_do(): can't find feature using identifier: rga4 (error too many matches for rga4)

In this case the name matched a gene and an allele.  It should cope.  The error above was thrown soon after this line in ExtensionProcessor.pm:
  if ($identifier =~ /^(PomBase|GeneDB_?Spombe):([\w\d.-]+)/i) {

I'm leaving the priority low for now as an error is throw if this happens.  It's not the best error message but it's enough to point at the problem.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
I'm not sure how to prioritise this one as I'm not sure what it is/affects

**Comment by kimrutherford** [comment]
I'm going to close this because I think it's never going to be high enough priority.
