### ISSUE TITLE
exact duplicate GO annotation, reporting

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#324]
I spotted an exact duplicate GO annotation here (php5)

GO:0001077  RNA polymerase II core promoter proximal region sequence-specific DNA binding transcription factor activity involved in positive regulation of transcription                26

regulates fbp1  IMP     Janoo RT et al. (2001)

regulates fbp1  IMP     Janoo RT et al. (2001)

(I artemis, I fixed it now, but should't these get reported somewhere, probably it isn't reported in the logs but the GO checking script used to report exact duplicates. Does it no longer so so?)

Original comment by: ValWood

**Comment by kimrutherford** [comment]
> Also check conditions and evidence for uniqueness.

And:
 - the residue (for modifications)
 - the "with"/"from" fields
 - the GAF column 17 / "Gene Product Form ID".

Note to self: the query from #660 is a good start.

**Comment by kimrutherford** [comment]
I've add a query to the Chado checks that reports duplicate GO annotation (I hope).

Here's how it should look in tomorrow's logs:
 https://www.dropbox.com/s/mlhvvd0wwjm64hj/new_check_chado_results.txt?dl=0

Note that this list also includes all the protein binding duplicates so they appear twice in the log file.  Tomorrow, I'll fix that by removing the query from #660.

**Comment by mah11** [comment]
What is the task for me? Is it simply to look at the log and fix where needed? (If so, no need for a ticket as I do logs ~weekly anyway.)

**Comment by ValWood** [comment]
> I've add a query to the Chado checks that reports duplicate GO annotation (I hope).

yep, if it made it to the logs, this can close

**Comment by mah11** [comment]
Some duplicates reported in the log ought to be filtered - I'll add a list to #536. I've fixed the ones that needed it.
