### ISSUE TITLE
is PHAF allele type case sensitive?

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#346]
For two of the newest PHAFs, the logs reported a slew of errors with "no such allele type: Amino acid mutation". So I changed them all to amino_acid_mutation, and will see if that fixes it.

It's not a big deal for curators, but it will probably be friendlier to users if allele type is not case sensitive.

(I found an email where you said the loader should already accept with or without underscores; that's good.)

Original comment by: mah11

**Comment by kimrutherford** [comment]
This should be fixed now.  If you see it again, please re-open the issue.
