### ISSUE TITLE
NOT annotation filtering behaviour

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#35]
Re:
If a gene is annotated with a quite general
term (like enzyme), but we also have a more specific annotation (like
ADH) on the same gene that has the NOT qualifier, my code is going to
delete the "enzyme" annotation if it is an IEA, IEP etc. 

Solution:
Add a warning to the log files when a NOT annotation results in the filter of another external annotation

Original comment by: ValWood

**Comment by ValWood** [comment]
consider with
https://github.com/pombase/pombase-chado/issues/397

**Comment by ValWood** [comment]
consider with
https://github.com/pombase/pombase-chado/issues/35

**Comment by kimrutherford** [comment]
> We need to rethink this...one for a call I think

What was the rethink?  Do we need to chat about it?

**Comment by ValWood** [comment]
that's a comment from 2014.

I think this will be covered by the website filtering we discussed?

**Comment by ValWood** [comment]
I can't find the active ticket about filtering NOTs on website tracker?

**Comment by kimrutherford** [comment]
> I can't find the active ticket about filtering NOTs on website tracker?

I don't remember discusses NOT filtering on the website.

**Comment by ValWood** [comment]
It was this ticket
which I closed with the instruction
"migrate to chado tracker"
because I think we decided to 
Ignore NOTs for slimming purposes
https://github.com/pombase/website/issues/617
I did not open a ticket it seems...

anyway I think I need to rake another look but I'm not  aware with an issue with NOT filtering behaviour on the gene pages....

**Comment by ValWood** [comment]
Ignore NOTs when filtering. Filtering code should not consider NOT annotations.

**Comment by kimrutherford** [comment]
> Ignore NOTs when filtering.

I've made the change to the GO filtering to ignore NOT annotation.  The results will be available on Tuesday morning.

**Comment by kimrutherford** [comment]
Do you have any examples that we can check to see if the fix is OK?

**Comment by ValWood** [comment]
My example was
https://www.pombase.org/gene/SPAC1B3.15c
which is working perfectly.
