### ISSUE TITLE
QC/log files  report NAS/TAS/IC still retained after filtering for papers processed through canto

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#350]
This is a QC check

Redundant IC/NAS/TAS are filtered. This means that we do not always  delete old annotations in Artemis using this evidence code. However, we would like to know if, when we have annotated a paper in Canto, any Artemis annotations with these evidence  codes remain.

This could indicate one of 2 things
i) the old annotation was incorrect and needs deleting
ii) the  new annotation is missing something which was captured by the old annotation 

If these were reported we could distinguish and fix appropriately

Original comment by: ValWood

**Comment by ValWood** [comment]
I don't think we do filter redundant IC, need to re-check what is filtered... we  should suppress these if there is an EXP annotation (NAS, IC,TAS)


![i thought we supresses redundent ic](https://cloud.githubusercontent.com/assets/7359272/17867066/d1c343b8-68a0-11e6-8965-9b9ae0228fc1.jpg)

I usually delete them, but obviously this takes time...

**Comment by ValWood** [comment]
closing because  we don't really need to do this...
