### ISSUE TITLE
term merge into different ontology aspect

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#375]
Today we noticed that the term 

GO:0006467 protein thiol-disulfide exchange (BP)
had merged into
protein disulphide isomerase activity (MF)

but 
GO:0006467 was still showing as a BP annotation in canto.

What happens when terms are merged from different ontologies ?
I think we should probably report these in the logs so we can check is we still want to make the annotation....

For Canto, the annotations which move aspect should move to be displayed under the new aspect

Original comment by: ValWood

**Comment by ValWood** [comment]
I'm going to close this, It shouldn't be an issue but if its a problem it should surface somewhere...
