### ISSUE TITLE
early paper list to assess citations

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#380]
We have the list of first curated pre 2000 papers, but we would like this list refined as follows:

Filter this list so that it only provides us with papers which have resulted in GO or phenotype annotation (many are complementation only which we would not expect to result in a citation increase).

Ideally I'd also like to see only those which had not been annotated _at all_ to GO previously, although I don't t think it is easy for you to do this? at least I cannot think of a way, unless it is possible to query against an old chado to see if there were existing annotations. Have a think.....

First part is more important. We could probably manually filter others later quite easily by referring to an old GAF.

Original comment by: ValWood

**Comment by ValWood** [comment]
Will close this for now, collaborators are assessing  stats for citation.
