### ISSUE TITLE
Chado allele for cdc2-33 has no type

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#391]
The Canto->Chado loader is coping badly with cdc2-33.  In Canto cdc2-33 mostly has type "unknown".  There are 8 sessions where it is "unknown" and one with "mutation of single amino acid residue". There are 7 session where the description is "unknown" and 2 where it is "A177T". The Canto->Chado loader isn't being smart about this.

Unfortunately cdc2-33 is ending up with type "unknown" in Chado but should be "mutation of single amino acid residue".

Code to check Canto:

./script/canto_curs_map.pl 'for my $al ($curs_schema->resultset("Allele")->search({ name => "cdc2-33"})->all()) { print $al->name(), " ", $al->description(), " ", $al->type, " ", $curs->curs_key(), "\n"; }' | uniq

Results:
cdc2-33 A177T mutation of single amino acid residue 57f3a3b217f0cd70
cdc2-33 unknown unknown c2b25694958a17bc
cdc2-33 unknown unknown d4ae29a798ec94dd
cdc2-33 unknown unknown abf32a065b08bcd5
cdc2-33 unknown unknown 69403b8ceb819841
cdc2-33 unknown unknown 8855a2414459b824
cdc2-33 unknown unknown cfa1ac27dc7acf6c
cdc2-33 unknown unknown 8759012da61b3559
cdc2-33 A177T unknown d676d3ce9ba0d3fe

Original comment by: kimrutherford

**Comment by kimrutherford** [comment]
From an old email exchange:

On 19/11/2014 01:19, Kim Rutherford wrote:
> I wanted to check before I start:
>
> if the allele name "cdc2-33" is used in two different sessions and in
> one the type "unknown" and in the other the type is "mutation of single
> amino acid residue" (for example), is it always the case that the two
> alleles are the same allele?

Val's reply:
> I think we can make this assumption. Usually we curate the earlier
> papers where it was unknown (ot the paper we are reading does not report
> it), then we find it in another paper. So a real description always
> 'trumps' unknown.

> The only ones which need to be reported as differences are the 'real'
> conflicts (which at present includes the aa/nt differences but we will
> deal with that later.

On 19/11/2014 08:55, Kim Rutherford wrote:
> If two labs call an allele "cdc2-33" with no description is it always
> the same allele?

Val's reply:
> I haven't come across a case where it isn't. They are pretty good like
> that....
> If there are conflicts we will end up with
> cdc2-33 x123Y and cdc2-33 x444z
> so we will see them.
>
> It happens rarely (if at all). There are rare situation where we will
> see conflcits I am sure. For instance some protein kinase alleles where
> described and then the  sequence changed, so they will described by the
> old designation in older papers which can generate conflicts.
>
> I think we are pretty safe  plugging a description into anything which
> is "unknown"...in the rare cases this isn't the case somebody will tell
> us (or it will come to light from us plugging in the different
> descriptions at some point).

**Comment by kimrutherford** [comment]
I'm hoping this is fixed now.  I'll check after the next load.
