### ISSUE TITLE
PomBase specific "legacy qualifiers"

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#398]
This is a place holder ticket.

It is likely that PomBase with have a set of annotation qualifiers which will be excluded from GO because they extend the information about the  annotated gene product rather than the term (they are really a qualifier with a "relation')

Curators will go through the deprecated terms in the New Year and decide if they are useful, if we can capture any other way to define a set which we wish to keep.

We will not export these in the GO file
# 

In addition, we  would like to use the "PomBase specific" relations to create an annotation extension with the relation "binds" for the interacting partner of the GO "protein binding" annotations with IPI evidence and the interacting PomBase gene in the 'with' field

These will also not be exported in the GO file

Original comment by: ValWood

**Comment by ValWood** [comment]
It seems we no longer have any remaining do closing.
