### ISSUE TITLE
standardize allele names and store  synonyms

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#400]
I noticed this in the feedback of one of Ryoko's sessions that I was updating.

cdc2-M55 is a synonym of cdc2-M26. 
Cdc2-130 is a synonym of cdc2-56. 
Cdc2-2w is a synonym of cdc2-1w.  

However we use a combination of these names on the gene page.

We should 
i) decide which is 'primary' and use that (curators can start on this part)
ii) add the other names as allele synonyms 
iii) How to handle allele synonyms in Canto
iv) decide how to show allele synonyms on the  gene  (and/or eventual allele) page

This needs linking or transferring to any existing ticket about allele synonyms.
Will do this later.

Original comment by: ValWood

**Comment by ValWood** [comment]
another example:
crm1-809 and AC1 are both E430K

This is a bit confusing so we should talk about how to deal with (both existing, and possibly in Canto
e.g.
"This allele description  is already known as crm1-809 add xxx as a synonym of this allele" ?
![same phenotype 2 names](https://cloud.githubusercontent.com/assets/7359272/11238351/da99e0b8-8ddc-11e5-9ba4-21295e120caa.jpg)

**Comment by kimrutherford** [comment]
> How to handle allele synonyms in Canto

We should have a chat about how to handle this in Canto for PomBase.  The FlyBase case is straightforward because we only need to show the synonyms that get loaded and we don't need to worry about adding, editing and removing synonyms.

**Comment by ValWood** [comment]
synonyms can now be included so I will close this . I'll open a curation tracker ticke to check the 
issues reported above get synonyms correctly recorded.
