### ISSUE TITLE
esyN files

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#401]
At some point we need to make a slight adjustment to the EsyN file export.
I think we should represent the data in the directed and the non-directed file non redundantly.
Sometimes you get more than one connector between nodes (this also happens when we have curated reciprocally).

We should address what to do about "reciprocal protein binding annotation"...and we should probably so this _quite_ soon, as it is confusing to have protein binding annotations represented in one direction on the gene pages, but not in the other.

We need to think about a few things here (like what BIoGRID do, and how this will affect the data exchange)

We'll talk about it soon, and try to pull together any related SF tickets.

Val

Original comment by: ValWood

**Comment by ValWood** [comment]
I would love this, but can work around it in medium term ;), I just delete the duplicate links in the networks I'm working on......

**Comment by ValWood** [comment]
this part

>At some point we need to make a slight adjustment to the EsyN file export.
I think we should represent the data in the directed and the non-directed file non redundantly.
Sometimes you get more than one connector between nodes (this also happens when we have curated reciprocally).

was done

**Comment by ValWood** [comment]
and 

> We should address what to do about "reciprocal protein binding annotation"...and we should probably so this quite soon, as it is confusing to have protein binding annotations represented in one direction on the gene pages, but not in the other.

I this is done too.
