### ISSUE TITLE
strange evidence in  report for go

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#418]
http://curation.pombase.org/dumps/latest_build/logs/log.2015-01-23-04-40-03.gaf-load-output

has

reading go_proc.txt
no taxon filter - annotation will be loaded for all taxa

  5605 | Microscopy
 6 | immunofluorescence evidence
15 | RNA protection assay evidence

but we don't use these evidences for GO?

(also function)

Original comment by: ValWood

**Comment by mah11** [comment]
from the comments, looks like this turned out to be a non-issue
