### ISSUE TITLE
Solving db_xref problems on modifications

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#431]
I have updated one annotation using the db_xref to check that it loads., 

/product="Rho family GTPase Rho3"
/systematic_id="SPAC23C4.08"
/controlled_curation="term=modification, far
db_xref=PB_REF:0000001; date=19700101"

this is the first annotation in
http://curation.pombase.org/dumps/latest_build/logs/db_xref_problems.txt
should disappear.

After this, we probably need to open a corresponding jira ticket to ensure that the PB_references.txt file  is read ? 

Original comment by: ValWood

**Comment by mah11** [comment]
nothing to do for this except what's in the jira ticket
