### ISSUE TITLE
Making sure GO protein binding interactions are presented in both directions on gene pages and in GAF

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#433]
Summary:

Although it isn't ideal, we will probably go ahead and store GO protein binding annotations in reciprocal in Canto. Even though this annotation only represents a single interaction/experiment the annotation itself is equally valid for both gene products. Its a little hacky  from a storing in a database perspective, but as a biological representation it is probably OK. 
-Kim was worried that the annotation numbers would be overinflated, but as these are included as 2 annotation in GO annotation counts, this is probably OK.

What needs to happen:
1.  Logs need to report any GO protein binding annotation which are not curated in reciprocal from the artemis files (manual or automated, fix depending on scale)
2. Canto  needs to automatically generate a reciprocal annotation when a GO protein binding annotation is made, AND to delete this reciprocal annotation when a GO protein binding annotation is deleted (I will open a Canto ticket for this). This will make annotation consistent, and clear for users, if the annotation is automatically created we won't get a mixed bag of curating in both directions or not.

1 & 2 above should ensure  that:
1. GO GAF should automatically contain reciprocal protein binding annotation (required)
2. GO protein annotation will automatically display on gene pages (required), Mark does not need to do anything.
3. Mechanisms are in place to ensure that protein binding annotation is synchronized so that everything is consistent.
4. Querying should work OK against Chado with a single query, as if you specify all of the interactions for gene a, you do not also need to query for all genes  x,y,z which interact with gene a, but where "a" is not the subject of the annotation.

Did I miss anything:
1. Anything else which needs to happen here?
2. Any unforeseen consequences ?

Original comment by: ValWood

**Comment by ValWood** [comment]
Only 2 pipe separated protein exist
SPAC17H9.19c IPI	PomBase:SPAC29B12.03|PomBase:SPAC17H9.10c
SPAC17H9.19c IPI	PomBase:SPCC1223.06|PomBase:SPCC895.05

(note that this may change to a comma)

the reciprocal of these is 
SPAC29B12.03 -> SPAC17H9.19c
SPAC17H9.10c -> SPAC17H9.19c

**Comment by ValWood** [comment]
PomBase	SPAC6G9.13c	bqt1		GO:0030674	PMID:16615890	IPI	PomBase:SPAC1002.06c	F	bouquet formation protein Bqt1	rec26|mug23	protein	taxon:4896	20140714	PomBase	has_direct_input(PomBase:SPBC12D12.01),has_direct_input(PomBase:SPBC1778.02)	
some are
PomBase	SPAC1002.06c	bqt2		GO:0030674	PMID:16615890	IPI	PomBase:SPAC6G9.13c	F	bouquet formation protein Bqt2	rec23|mug18	protein	taxon:4896	20140714	PomBase	has_direct_input(PomBase:SPBC12D12.01),has_direct_input(PomBase:SPBC1778.02)	

before you proceed I will check with GO what we should be using and then we can standardize.

**Comment by ValWood** [comment]
Note that also, to complicate this, sometimes we might have curated the reciprocal  "protein binding" GO annotation and sometimes we will not have. At least I used to, all the time, and Antonia has....
So, some will exist already.

**Comment by ValWood** [comment]
e.g. for discuss  plo1 cut23

**Comment by ValWood** [comment]
Here we have an example 
drc1 has 
binds rad4, active form PR:000027529

but rad4 does not have drc1 binding

But this raises another issue.
The active form here refers to drc1...at first glance at the annotation, I thought this was more specificity about the bound protein rad4

Do we need to make this clearer .....(maybe the mouseover will make this OK)
BUT, do we want to know when we are on the  rad4 page that rad4 only binds to the phosphorylated form of drc1???

**Comment by ValWood** [comment]
This is the canto ticket for displaying interactions in both directions

You might want to treat this as only a "display" issue?

This is the website ticket:
https://github.com/pombase/website/issues/376

**Comment by ValWood** [comment]
Only consider "protein binding" not it's children.
Evidence always IPI, will always have pombe ID in with field (we display this as a binds extension)

1. Always make sure reciprocal annotations exists
2. Duplicates from different PMID  are OK

**Comment by kimrutherford** [comment]
I think I've implemented this.  There are 394 missing protein binding IPI annotations.  Does that sound right?

I'm going to run a local Chado load test to double check.  If that works it should be in tomorrow's nightly load.

**Comment by ValWood** [comment]
Good question, I don't even have a feel for this, but it is probably ball park correct.

we have 948 genes with protein binding annotations. According to amigo 1980 annotations.

I thought it would be more than 394 that were not reciprocated...
But it could be correct.....

**Comment by kimrutherford** [comment]
> I'm going to run a local Chado load test to double check. If that works it should be in tomorrow's nightly load.

I found a bug in more thorough testing.  I got the fix in before the nightly load got to that point so it should be OK.

**Comment by kimrutherford** [comment]
I've made a thorough check of last night's load.  The reciprocal IPI annotations are mostly being created successfully.

I noticed an oddity though.  I counted the IPI protein binding annotations per publication and noticed that some publications had an odd number of matching annotations.  I thought that since every annotation should have a reciprocal, something had gone wrong.  I hadn't considered the situation where a gene has an IPI with itself.  I checked and that seemed explain things.

But then I noticed anything things I hadn't considered: the dreaded column 17

For example for cdc2:

binds cdc13 active form PR:000045540  IPI Caspari T et al. (2015)
binds cdc13 active form PR:000045541  IPI  Caspari T et al. (2015)
binds cdc13 active form PR:000045542  IPI  Caspari T et al. (2015)

The code I wrote to add the reciprocals is ignoring the column 17 / "active form" part of the annotation and is making three new identical reciprocal annotations like:

cdc13 protein binding with cdc2 - IPI Caspari T et al. (2015)

Whoops.

How should the column 17 part be handled in these cases?

**Comment by ValWood** [comment]
we don't need to worry about this much. there are not many.

The reciprocal could just show the gene name for the modified form, so in this case just store 1 annotation maybe?

**Comment by ValWood** [comment]
Looks good in that the ones I checked are there, the number of individual gene products with protein binding annotation jumps from 948 -> 1006

**Comment by kimrutherford** [comment]
> The reciprocal could just show the gene name for the modified form, so in this case just store 1 annotation maybe?

Great.  That's what it does now.

I'll close this now, but let me know if you spot any oddities.
