### ISSUE TITLE
logs; syntax check required

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#441]
phosphorylated residue	S47 annotation_extension=added_during(GO:0000089)
is appearing in the modification section of csm1 gene page

(need to check that all annotation statements are terminated by ';'

Original comment by: ValWood

**Comment by kimrutherford** [comment]
> I think this will be fixed when I fix: https://sourceforge.net/p/pombase/chado/434/

Which is now: #419 confusingly.

**Comment by kimrutherford** [comment]
> residue=S47 annotation_extension=added_during(GO:0000089)

I haven't fixed the residue parsing (#419), but you will now get a warning for missing semi-colons like this.  Something like:
  qualifier value ('S47 annotation_extension=added_during(GO:0000089)') contains an equals '='
