### ISSUE TITLE
missing F-P link annotation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#445]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008233#term=ancchart has an F-P link to proteolysis
erm1 has proteolysis annotation on www (currently) from UniProtKB-KW:KW-0645. 

I filtered the mapping so this annotation should disappear on stage (it has), but it should be replaced by an annotation derived from the F-P link (it hasn’t). Can anyone figure out why?

Original comment by: ValWood

**Comment by mah11** [comment]
opened https://github.com/geneontology/go-annotation/issues/1336
