### ISSUE TITLE
primary name changes

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#446]
Hi Kim,

What would happen if a primary name changes  to the existing extensions which use the old primary name. Do they get fixed automatically? I am thinking this would be the same situation if a systemtic ID was used in an extension for an unnamed gene which was subsequently named. I don't know if we have any examples of this either. I guess we need to

Report any use of extensions which do not match the primary name.

We might have a test case soon.

Original comment by: ValWood

**Comment by kimrutherford** [comment]
I'm going to close this because I think we're already doing what you need.  Please re-open if I have that wrong.
