### ISSUE TITLE
report various qualifier anomalies in logs

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#448]
This annotation:

/GO="aspect=F; qualifier=NOT; term=adenosine deaminase activity; GOid=GO:0004000; evidence=IKR; with=; db_xref=PMID:14643670; date=20120927"

is not visible in PomBase. could you check that iti s in chado.
It might be the empty with statement (which I can delete), but things with "with=;" should appear in the logs for fixing.

VAl

Original comment by: ValWood

**Comment by kimrutherford** [comment]
> i) Empty with field with=;
> ii) Absent "with" field for ISS

I've done these bits because they were easy.  I'll test them tomorrow.

> iii) Incorrect SGD ID in with field (I think we stoer these in chado so, anything
> which does not match SGD:stored_id

That's harder because we currently only store the "Y" IDs like "YJR076C".  We could get the SGD: IDs from Ensembl too but we haven't needed them so far.

**Comment by ValWood** [comment]
transferred to 
https://github.com/pombase/pombase-chado/issues/527
for odd bod log reporting
