### ISSUE TITLE
annotation consistency checks, reciprocal "added by" on modification for modifier activity

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#452]
For any
MF protein modifier activity  (i.e kinase/acetylate etc) with has_direct_input target gene extension, the target gene extensions should always have the appropriate modified residue annotation with adde_by/removed_by extensions for the modifier.
(and vice versa)

Original comment by: ValWood

**Comment by ValWood** [comment]
hta1,2 check #1077
contains an example. I won't fix it for now...

**Comment by ValWood** [comment]
I don't think this requires discussion.
I might need to describe in more detail though @kimrutherford ?

**Comment by kimrutherford** [comment]
> I might need to describe in more detail though

Yep, I'll probably need a quick chat to you when I get to this.  You're right that it doesn't need discussion.

**Comment by ValWood** [comment]
We opened a new ticket for this recently so I will close this old one which  doesn't really explain  what is rquired
https://github.com/pombase/pombase-chado/issues/1197
