### ISSUE TITLE
Cope with disruption allele names like cdc8::(disruption)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#454]
Cope with disruption allele names like:

Sma::(1311-1485) and Xba::(1220-1485) from http://curation.pombase.org/pombe/curs/6f1818d4183cd160

and

cdc8::(disruption) from http://curation.pombase.org/pombe/curs/82154f75e067e7cd/

The text in () is missing in Chado:

   select * from feature where name like '%::';

Original comment by: kimrutherford

**Comment by ValWood** [comment]
Is this done? Note that  if this is the way we do these:

Sma::(1311-1485) and Xba::(1220-1485)  we should add this to the  'instructions'
But, I did not see  these in the list of "other alleles" created by Kim

**Comment by ValWood** [comment]
Actually, I checked the  Sma::(1311-1485) are Sma(1311-1485) and described as amino acid truncations, which is fine.
I fixed the Sma to sma (correct convention for alleles).

Closing this. Open a new ticket if anything still to do. I think its covered?

**Comment by ValWood** [comment]
Kim, If there are others which need fixing, please add them to 
The curation tracker ticket https://github.com/pombase/curation/issues/664

**Comment by kimrutherford** [comment]
> Kim, If there are others which need fixing

None that I know of at the moment.
