### ISSUE TITLE
new 'minimal' annotation file for phenotype enrichment tools

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#456]
We need an additional phenotype file for a 'generic' enrichment tool which is being set up by a collaborator of Steve and Duygu.

The format is

File of annotations

Tab delimited with the following columns:
i) systematic ID
ii) phenotype ontology ID

Header with versioning info.
# Annotation Source: PomBase Chado v51
# Created: yyyy-mm-dd

and it should probably go in
http://curation.pombase.org/dumps/latest_build/
called 
pombase-build-2015-05-11-v2-l1.phaf_simple.gz

Original comment by: ValWood

**Comment by ValWood** [comment]
Not been mentioned recently. Will raise later.

**Comment by ValWood** [comment]
This seems to have dropped of the radar, and now we have Angeli. Long term, it would be great to have an enrichment tool as part of PomBase...

**Comment by kimrutherford** [comment]
> Long term, it would be great to have an enrichment tool as part of PomBase...

InterMine can do enrichment stuff.

**Comment by ValWood** [comment]
Yep that was part of the grant plan... sort of at the end...and then dropped by cuts...but who knows.
We had a collaborator who was doing it for a while but I think they bailed when Angeli came along...

**Comment by ValWood** [comment]
Enrichment will happen (too many citations to lose!). Year 4 maybe ;)

I'm going to delete these comments ;)

**Comment by ValWood** [comment]
out of date.
