### ISSUE TITLE
multi-allele: store strain background from Canto

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#457]
Make sure that the background strain is added to the JSON files and that we load it.

Original comment by: kimrutherford

**Comment by kimrutherford** [comment]
The Canto JSON export now writes out the genotype background and the Chado loader code has been changed to store it.  Needs a full load to test.

**Comment by ValWood** [comment]
I guess this should be done soon.
Is it part of the proposed display?

**Comment by kimrutherford** [comment]
> I guess this should be done soon.

Should be in V54 if the next load works OK.

> Is it part of the proposed display?

Not at the moment I think.

**Comment by kimrutherford** [comment]
The background is stored no.  It's a featureprop on the genotypes with the type "genotype_background".

I've just documented that on the pombase-chado wiki.
