### ISSUE TITLE
Complex annotation file

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#458]
To remove any confusion can we cease copying the complex file to here:

http://curation.pombase.org/dumps/latest_build/pombe-embl/supporting_files/
[   ]	Complex_annotation	25-May-2015 11:54	360K	 
[   ]	Complex_annotation_filters	25-May-2015 11:54	1.7K	 

and remove the file  
"Complex_annotation"
from svn
supporting_files directory.

Mark now creates this file so it first appears in a public place with a stable URL, no need to transfer it to anywhere else.

The  file is now Complex_annotation in
ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Complexes/

I'm not sure but I think Mark uses 
Complex_annotation_filters
in the supporting files directory in the file creation so we need to keep this here.

Original comment by: ValWood

**Comment by ValWood** [comment]
This should be fairly quick, it is just to cease creating a file

**Comment by ValWood** [comment]
I'm putting this at V 55 as it is only to cease copying over a file.

**Comment by kimrutherford** [comment]
It looks like you deleted supporting_files/Complex_annotation from SVN.  Is there anything I need to do?

**Comment by ValWood** [comment]
nope
