### ISSUE TITLE
allele expression inference

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#459]
On some pages certain alleles are listed with different expression

For example cdc2 alleles we have
cdc2-1w (G146D) Not specified 
cdc2-1w(G146D) Endogenous

and

cdc23w (C67Y) Not specified 
cdc2-1w(G146D) Endogenous

We need to implement a system so that if Endogenous is supplied it replaces "not specified" for all other instances (Endogenous trumps not specified), because if we know the expression, we know.

This would collapse down quite a lot of phenotype annotations which are currently displayed separately.

 

Original comment by: ValWood

**Comment by kimrutherford** [comment]
Is there anything to be done on the Chado or loading side for this issue or is it a curation task?
