### ISSUE TITLE
Use FYPO from Git/GitHub in Chado load

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#460]
The Chado load scripts are still pointing at the subversion repo on SourceForge

**Comment by mah11** [comment]
The latest curation-tool-data-load-output logs suggest this isn't done ... I've stuck the next-load label on.

**Comment by kimrutherford** [comment]
I've had trouble with the ontology loading step so we haven't had a new FYPO in a few days.  That's fixed now so the next load should be better.

**Comment by kimrutherford** [comment]
The load failed due a typo in the load script.  The path to fypo-simple.obo has moved - loading again.
