### ISSUE TITLE
name description with 'during" extension

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#462]
Spotted in
http://curation.pombase.org/dumps/latest_build/logs/log.2015-05-27-06-26-29.extension_relation_counts

We need to track down and fix...could you report any extensions on name_description in the main logs (if not already)....

**Comment by mah11** [comment]
I spotted the offending name description whilst looking at something else, so I can just delete the extension.

**Comment by ValWood** [comment]
Hoooooowwww?????? Its OK, don't tell me.....
I'll just think you are parsing the EMBL files daily

**Comment by mah11** [comment]
I'm special ;)

anyway, done (and for posterity, it was meu13)

**Comment by ValWood** [comment]
We know :)

**Comment by kimrutherford** [comment]
Can this be closed?

**Comment by mah11** [comment]
I suppose so

**Comment by ValWood** [comment]
We don't have any extensions defined for use with name_description, so this should appear in the logs....
not a big-ee  but I thought that now any extensions which did not fit the allowed extensions in the Yaml file would be reported in the logs? Isn't that correct?

**Comment by kimrutherford** [comment]
Currently if a cv name isn't configured then any extension is allowed.  That's probably not best.

As a quick fix, I've explicitly disallowed name_description from having extensions:

pombase/pombase-legacy@ed90d21c103f0d434c99885e8f91ba70a75971a8

**Comment by ValWood** [comment]
Good plan. Probably do the same for PBO too. I doubt we have used any, but if we have we can document and allow.

**Comment by kimrutherford** [comment]
> Probably do the same for PBO too.

Unfortunately it the allow/disallow code works by ontology name and "PBO" is just the namespace for the ID (eg. "PBO:0000123").

Would it be better if the code complained when the extension isn't explicitly allowed for a given ontology?

**Comment by ValWood** [comment]
I think so...

**Comment by kimrutherford** [comment]
OK, I'll change the code.
