### ISSUE TITLE
IC filtering

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#464]
based on our current filtering procedures, IC annotations should be filtered if a more specific experimental annotation exists.
This does not seem to be the case for cig2 where we display an annotation to
"regulation of mitotic cell cycle" with "IC" evidence enven though there are many experimental annotations to more specific children

positive regulation of G1/S transition of mitotic cell cycle
positive regulation of cyclin-dependent protein serine/threonine kinase activity involved in G1/S transition of mitotic cell cycle

etc.

This seems odd as I have not seen this happen elsewhere.....

val

**Comment by ValWood** [comment]
might be a bug....?

**Comment by kimrutherford** [comment]
Yep, looks like a bug.  I've checked the data in Chado and it all looks OK.  I'll check the code.

**Comment by kimrutherford** [comment]
Is this because of #449?

**Comment by ValWood** [comment]
yes you are right . i forgot.I deleted the redundant annotation. One day when there is time we might change the filtering precedence.
