### ISSUE TITLE
spurious "term suggestion" warnings

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#467]
The 2015-07-30-04-49-38 Canto log has a lot of warnings that say "annotation with term suggestion not loaded", but I checked the first few and I can't see any term suggestions in the sessions. I haven't done them all (see above re: lots) but I have yet to find a session that does have a term suggestion.

One of them is for a paper I curated, and I know I didn't put any term suggestions in the session (at all, let alone leave them in after approval) - e8278d6fd6c40079.

Can't tell if this is related to the #466 session ID weirdness.

**Comment by kimrutherford** [comment]
Fixed by ebb089d7c821.  I've also fixed the Canto export code to not put empty term suggestions in the export file.
