### ISSUE TITLE
erroneous excluded-FYPO warnings

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#471]
Still there in log.2015-08-05-02-31-39.excluded_fypo_terms, so here's the ticket.

There are some warnings in the latest excluded_fypo_terms flagging FYPO:0004044 (elongated tetranucleate vegetative cell). But that term snuck into the do-not-annotate set by mistake, and I fixed the mistake quite a while ago. It hasn't been in the subset for at least a couple months. And now the canto load log suggests that FYPO is now up to date.

(They've been there for the last several builds, but I didn't worry about them when FYPO was generally out of date anyway.)

**Comment by kimrutherford** [comment]
It's reading the subsets from: mini-ontologies/FYPO_qc_do_not_annotate_subsets.obo
last updated Fri, 13 Feb 2015.

Does that sounds right?

That version of the file still has FYPO:0004044.

**Comment by mah11** [comment]
aha! I thought it was doing something clever with the main FYPO obo file. I can update that subset file today (thought I'd done it more recently than Feb ... hey ho ...) to make it all better for the next load.

**Comment by kimrutherford** [comment]
Great.  At some point soon we (mostly me) need to be cleverer about dealing with subsets.

**Comment by mah11** [comment]
... and done. I'll close this if the next load is ok.

**Comment by kimrutherford** [comment]
I've just started a new load.  It should finish in 4.5 -ish hours.

**Comment by mah11** [comment]
yay, fixed
