### ISSUE TITLE
a few more oddball allele warnings

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#474]
Now that the session IDs in the logs have calmed down, I can spot some more anomalous warnings.

> warning in 2598fac4f5efa38a: description for new allele "cdc3(cdc3-6)" does not match the existing allele with the same name "cdc3(cdc3-124)" (from session bd4f213d7cad1349)

1) Why does it think "cdc3-6" and "cdc3-124" are the same name? Neither has a known description, but the names are different. 2) I don't see a "cdc3-124" in bd4f213d7cad1349; it has an unnamed cdc3 allele with unknown description.

> warning in 2598fac4f5efa38a: description for new allele "cdc4(cdc4-8)" does not match the existing allele with the same name "cdc4(cdc4-31)" (from session 2598fac4f5efa38a)

Similar to previous - "cdc4-8" and "cdc4-31" look different to me.

> warning in 83c8a0868d64f0a1: trying to store an allele with the name "cdc15deltash3" but the name exists with different case: "cdc15deltaSH3" (from session d5300c7f4c45c39f)

I don't see the one with lower case in session 83c8a0868d64f0a1.

> warning in d616690bf410cea4: description for new allele "tsc1delta(deletion but with background auxotrophy markers)" does not match the existing allele with the same name "tsc1delta(deletion)"
> warning in d616690bf410cea4: allele_type for new allele "tsc1delta(other)" does not match the existing allele with the same name "tsc1delta(deletion)"
> warning in d616690bf410cea4: description for new allele "tsc2delta(deletion but with background auxotrophy markers)" does not match the existing allele with the same name "tsc2delta(deletion)"
> warning in d616690bf410cea4: allele_type for new allele "tsc2delta(other)" does not match the existing allele with the same name "tsc2delta(deletion)"

I only see one allele for tsc1 and one for tsc2 in that session, and the warnings don't mention a second session. The names in the warnings also don't match what's in the session now. I'm just generally confused here. (There are several copies of these, presumably for different annotations.)

> warning in fa30fa9e2e0880e6: description for new allele "gea1+/gea1-(heterozygous diploid,contains ~50% gea1 RNA)" does not match the existing allele with the same name "gea1+/gea1-(heterozygous diploid)" (from session fa30fa9e2e0880e6)

another one where I only see one thing in the session

> warning in 893c30409873a782: description for new allele "psf1-HBD(steroid hormone-binding domain fusion)" does not match the existing allele with the same name "psf1-HBD(psf1 HDB fusion)" (from session 893c30409873a782)
> warning in 893c30409873a782: description for new allele "psf1-HBD(steroid hormone-binding domain fusion)" does not match the existing allele with the same name "psf1-HBD(psf1 HDB fusion)" (from session 893c30409873a782)

For these, there are two genotypes with the same allele but different expression. Both have "psf1-HBD" as the name, "other" as the allele type, and "steroid hormone-binding domain fusion" as the description, so I don't know where the warning is getting a different name.

> warning in f96ed996276b8e88: allele_type for new allele "WY/DPS(other)" does not match the existing allele with the same name "WY/DPS(amino_acid_mutation)" (from session f96ed996276b8e88)
> warning in ad3cea5e630841a3: description for new allele "pxd1(227â€“351)" does not match the existing allele with the same name "pxd1(Pxd1(227â€“351))" (from session ad3cea5e630841a3)
> warning in 53af9f6726121d19: description for new allele "Pnmt81-mtl1-2xHA-AID(thiamine-repressible nmt1 promoter variant (nmt81) and auxin-inducible degron (AID))" does not match the existing allele with the same name "Pnmt81-mtl1-2xHA-AID(nmt41 promoter / degron tagged mtl1)" (from session 53af9f6726121d19)
> warning in 53af9f6726121d19: description for new allele "ars2-AID(degron tagged ars2)" does not match the existing allele with the same name "ars2-AID(auxin-inducible degron (AID))" (from session 53af9f6726121d19)
> warning in 53af9f6726121d19: description for new allele "ars2-AID(degron tagged ars2)" does not match the existing allele with the same name "ars2-AID(auxin-inducible degron (AID))" (from session 53af9f6726121d19)
> warning in 2697c460cee0ce6a: description for new allele "rhb1GS(G63D,S165N)" does not match the existing allele with the same name "rhb1GS(G63D,S165S)" (from session 2697c460cee0ce6a)

More where I can't find both allele descriptions in the session.

This can be bumped past v55, if it turns out it's not quick.

**Comment by kimrutherford** [comment]
I think most of these warning are due to pombase/canto#938 - I'll definitely fix that soon.

We should check this again after that is fixed.

**Comment by kimrutherford** [comment]
> We should check this again after that is fixed.

I'm running a new load now with a fixed up dataset from Canto.

**Comment by kimrutherford** [comment]
Most of these warnings are gone now.  I hope the remaining ones make sense.

A lot seem to be because of #172 - I'll try to get that done before the next release.

**Comment by mah11** [comment]
I'm happy to open new tickets if I see any more weird things ;)
