### ISSUE TITLE
one ISS to allow without 'with'

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#478]
Here's an annoying one (because it requires an exception):

The 10-Aug-2015 qualifier_problems.txt log is flagging an ISS annotation that it should allow in. The annotation in question fits the GO criteria for making an exception to the "must have a 'with' entry" rule: "If the annotation is based on a method such as tRNASCAN, which cannot be referred to with an accession number, the with field may be left empty." (and it's a lot like the second annotation example on the doc page, http://geneontology.org/page/iss-inferred-sequence-or-structural-similarity).

snoRNA SPSNORNA.52.1: ISS must have a "with=": failed to load qualifier 'aspect=F; term=RNA pseudouridylation guide activity; GOid=GO:0030558; evidence=ISS; db_xref=PMID:15716270; date=20140815' from SPSNORNA.52.1:

**Comment by kimrutherford** [comment]
So is the fix that we should not check "with=" on snoRNA features?  Or does it apply to other RNA feature types too?

**Comment by mah11** [comment]
Regrettably, it's more complicated than that. The exception isn't because of what kind of feature it is, but because the actual sequence comparison method doesn't provide anything to put in the 'with' column. 

If I'm interpreting the GO documentation correctly, we can work around this one by changing the evidence to ISM (sorry, didn't spot the relevant bit when I opened this ticket).

For ISM, a 'with' entry is allowed but not mandatory.
