### ISSUE TITLE
FYPO terms missing in the fypo-simple.obo file

### ISSUE THREAD

**Issue by markmcdowall** [pombase/pombase-chado#480]
The following accessions are used in the accessions but are missing in the dumped obo file that is present here:

http://curation.pombase.org/dumps/releases/pombase-chado-v54-2015-08-13/ontologies/

Accessions:
+---------------+
| FYPO:0004700  |
| FYPO:0004701  |
| FYPO:0004702  |
| FYPO:0004703  |
| FYPO:0004704  |
| FYPO:0004705  |
| FYPO:0004706  |
| FYPO:0004707  |
| FYPO:0004708  |
| FYPO:0004710  |
| FYPO:0004711  |
| FYPO:0004712  |
| FYPO:0004713  |
| FYPO:0004714  |
| FYPO:0004715  |
| FYPO:0004716  |
| FYPO:0004719  |
| FYPO:0004720  |
| FYPO:0004721  |
| FYPO:0004722  |
| FYPO:0004723  |
| FYPO:0004726  |
| FYPO:0004728  |
| FYPO:0004730  |
| FYPO:0004731  |
| FYPO:0004732  |
| FYPO:0004733  |
| FYPO:0004734  |
| FYPO:0004737  |
| FYPO:0004742  |
| FYPO:0004743  |
| FYPO:0004744  |
| FYPO:0004745  |
| FYPO:0004746  |
| FYPO:0004747  |
| FYPO:0004749  |
| FYPO:0004750  |
| FYPO:0004751  |
| FYPO:0004752  |
| FYPO:0004753  |
| FYPO:0004754  |
| FYPO:0004755  |
| FYPO:0004761  |
| FYPO:0004763  |
| FYPO:0004764  |
| FYPO:0004765  |
| FYPO:0004766  |
| FYPO:0004767  |
| FYPO:0004768  |
| FYPO:0004769  |
| FYPO:0004770  |
| FYPO:0004771  |
| FYPO:0004772  |
| FYPO:0004774  |
| FYPO:0004775  |
| FYPO:0004776  |
| FYPO:0004778  |
| FYPO:0004779  |
| FYPO:0004780  |
| FYPO:0004781  |
| FYPO:0004782  |
| FYPO:0004784  |
| FYPO:0004785  |
| FYPO:0004787  |
| FYPO:0004788  |
| FYPO:0004789  |
| FYPO:0004791  |
| FYPO:0004792  |
| FYPO:0004793  |
| FYPO:0004794  |
+---------------+

**Comment by mah11** [comment]
Did you close this on purpose?

Anyway, as a stopgap you can use the FYPO file here:
https://cdn.rawgit.com/pombase/fypo/master/release/fypo-simple.obo

**Comment by markmcdowall** [comment]
Can do.

Yes, the file seems to be fine when I manually go to the FTP directory, but the script does not seem to receive the same file.

**Comment by mah11** [comment]
Ah, I bet the script hasn't been updated to point to GitHub. Should be no problem for Kim to fix.

**Comment by markmcdowall** [comment]
Found the cause in my own script
