### ISSUE TITLE
Fix modelling of exons in Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#481]
According to this:
  http://gmod.org/wiki/Chado_Best_Practices#Trans-spliced_Gene

we need to store a rank in the feature_relationship table that determines the exon order.

We also need to fix the exon uniquenames.  On the reverse strand we currently have exon 1 last.  eg.

fmin, fmax, uniquename:
 1807717 | 1807781 | SPAC1002.06c.1:exon:3
 1807482 | 1807642 | SPAC1002.06c.1:exon:2
 1807269 | 1807402 | SPAC1002.06c.1:exon:1

Needed for #172

**Comment by ValWood** [comment]
This says "trans spliced gene". All of our genes are 'cis spliced'
https://en.wikipedia.org/wiki/Trans-splicing

**Comment by kimrutherford** [comment]
Yep, but it also talks about how all exons should be modeled, including in the cis-spliced case.

**Comment by kimrutherford** [comment]
I checked with @markmcdowall and he's happy that these changes won't break the Ensembl loading.

**Comment by kimrutherford** [comment]
Fixed by pombase/pombase-legacy@7db710364b2675f5589eb267eeba3d43fbc1bdc4
