### ISSUE TITLE
Is SPAC823.17 in Chado?

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#482]
SPAC823.17 is one of the new genes added last year from Caia & Juan's ribosome profiling stuff (PMID:24929437). It's right there in the chromosome1.contig file, but to Mark it appears as though it's "no longer in PomBase". Is it in Chado?

see https://www.ebi.ac.uk/panda/jira/browse/PB-2290

**Comment by kimrutherford** [comment]
Yep, it's in v54.

**Comment by mah11** [comment]
Thanks for checking. Over to Mark ...
