### ISSUE TITLE
Deal with GAF spec change

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#483]
> We have extended the With/From column (Column 8) of the GAF2 to 
> allow the use of commas as delimiters as well as pipes ("|").

Check that the loader can cope.

http://geneontology.org/article/minor-change-formatting-gene-association-files-gaf

**Comment by mah11** [comment]
as noted in a comment on #504, there are warnings in the qualifier_problems.txt log, indicating that it can't cope at the moment

**Comment by kimrutherford** [comment]
> allow the use of commas as delimiters as well as pipes

The code now allows only commas and not pipes.  That seems to be OK for our case as far as I can tell.  If it isn't I'll fix it.  Please let me know if you spot any problems.
