### ISSUE TITLE
GO annotation from InterPro that should be filtered.

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#484]
I can't figure this out.

In this log file
http://curation.pombase.org/dumps/latest_build/logs/log.2015-09-02-21-42-47.excluded_go_terms

we have
SPAC3H8.10.1 GO:0006810 transport InterPro

BUT
This is an IEA, which should be filtered if there are more specific manual annotations, and there are...

on www
http://www.pombase.org/spombe/result/SPAC3H8.10
GO:0006893 Golgi to plasma membrane transport IMP
GO:0048193 Golgi vesicle transport IMP
GO:0015914 phospholipid transport ISO SGD:S000004684

on stage
GO:0006893 Golgi to plasma membrane transport IMP
GO:0048193 Golgi vesicle transport IMP
GO:0015914 phospholipid transport ISO SGD:S000004684

in canto
http://curation.pombase.org/pombe/view/object/pub/4886?model=track

The parentage of these seems to be OK....

Also this is the ONLY mapping to transport that I'm picking up. You would think if there was a problem with the filtering or the loader or the ontology we would get 100's....

I really can't think why this particular annotation is appearing....I must have forgotten something, but what???

**Comment by ValWood** [comment]
MORE

SPBC83.04.1 GO:0030071 regulation of mitotic metaphase/anaphase transition InterPro
but this has a more specific manual annotation:
positive regulation of mitotic metaphase/anaphase transition Evidence With/From Reference
IMP Yoon HJ et al. (2002)
again its the only one to this term that is showing?....

SPAC977.10.1 GO:0006814 sodium ion transport UniProt
SPAC15A10.06.1 GO:0006814 sodium ion transport UniProt
these have experimental annotation to sodium ion import into cell

SPBC16C6.01c.1 GO:0006479 protein methylation PomBase
SPAC3C7.09.1 GO:0006479 protein methylation PomBase
have more specific annotation but via ISM. Maybe this is not filtered against?

**Comment by ValWood** [comment]
Comment from Midori>
the offending annotations all have the datestamp 20150718 in the latest-build GAF; they’re not in the v54 GAF (i.e. the problem, which does look like filtering, arose recently)

**Comment by ValWood** [comment]
SPBP22H7.09c.1		GO:0007059	chromosome segregation		InterPro
is 
mitotic sister chromatid segregation
in
curs/6bede5008acef48c/ro/
http://www.pombase.org/spombe/result/SPBP22H7.09c

**Comment by ValWood** [comment]
SPBC409.04c.1		GO:0007067	mitotic nuclear division		InterPro
has
mitotic sister chromatid segregation

**Comment by ValWood** [comment]
and
SPBC2G5.07c.1		GO:0006351	transcription, DNA-templated		InterPro

**Comment by kimrutherford** [comment]
Sorry for the hassle.  I think at least part of the problem is that I forgot to add the "disruption" allele type to the load configuration.  That caused the Canto data loading to completely bail out.  The Chado checks log file shows some of the problems:
  http://curation.pombase.org/dumps/builds/pombase-build-2015-09-01-v1-l1/logs/log.2015-09-02-21-42-47.chado_checks

I've fix that and I'm running a new load.  I'll check the excluded_go_terms when that's done.

**Comment by ValWood** [comment]
that makes sense. I should have checked the main logs!

**Comment by kimrutherford** [comment]
The exclude_go_terms output is looking a lot better now.  Could you take a look when you have a chance?

**Comment by ValWood** [comment]
Yep, fixed I think  ;)
