### ISSUE TITLE
logs enquiry , some phenotype annotation failure?

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#486]
Haven't seen this one before, not sure what it means...

http://curation.pombase.org/dumps/latest_build/logs/log.2015-09-05-05-12-28.export_warnings
Use of uninitialized value $extensions in substitution (s///) at /home/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 348.
Use of uninitialized value $extensions in substitution (s///) at /home/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 348.
Use of uninitialized value $extensions in substitution (s///) at /home/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 348.
Use of uninitialized value $extensions in substitution (s///) at /home/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 348.
Use of uninitialized value $extensions in substitution (s///) at /home/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 348.
Use of uninitialized value $extensions in substitution (s///) at /home/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 348.
Use of uninitialized value $extensions in substitution (s///) at /home/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 348.
Use of uninitialized value $extensions in substitution (s///) at /home/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 348.
Use of uninitialized value $extensions in substitution (s///) at /home/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 348.
Use of uninitialized value $extensions in substitution (s///) at /home/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 348.
Use of unin

**Comment by kimrutherford** [comment]
Sorry about that.  I noticed it yesterday and fixed it in 1742b0ae8.

Should be OK in the next load.

**Comment by ValWood** [comment]
OK, I think we could do a release for Monday after all if I manage to get the logs done today...
They look pretty clean. They have been Midori'd.
