### ISSUE TITLE
PECO IDs not found

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#487]
@Antonialock can you let me know when in
Val

warning in 679551fd20beff97: can't load condition, PECO:0000284 not found in database
warning in 8570af08389340e2: can't load condition, PECO:0000285 not found in database

warning in 466c4197f9cf80c6: can't load condition, PECO:0000286 not found in database
warning in 466c4197f9cf80c6: can't load condition, PECO:0000286 not found in database
warning in 466c4197f9cf80c6: can't load condition, PECO:0000286 not found in database
warning in 466c4197f9cf80c6: can't load condition, PECO:0000286 not found in database

warning in b5fde7a48c34bee4: can't load condition, PECO:0000285 not found in database
warning in b5fde7a48c34bee4: can't load condition, PECO:0000285 not found in database

**Comment by kimrutherford** [comment]
Sorry, that was my fault.  The load script was pointing at the SVN version of PECO instead of the Git one so those IDs were missing.  I've fixed that and started a new load.
