### ISSUE TITLE
annotation extension not displayed in PomBase

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#489]
I don't know if this is related to

https://www.ebi.ac.uk/panda/jira/browse/PB-2371

this annotation is appearing,
PomBase	SPAC11G7.02	pub1		GO:0006511	PMID:8635463	IMP		P	HECT-type ubiquitin-protein ligase E3 Pubprotein	taxon:4896	20081001	PomBase	has_input(PomBase:SPAC24H6.05)

but its extension is not.

If it is fine in chado close and I'll pop it on jira
v

**Comment by markmcdowall** [comment]
The issue with pub1 (SPAC11G7.02), the with field is present on the gene page in the full view.
This is what is present in chadov54:
```sql
SELECT
  f.uniquename,
  fc.pub_id,
  fcc.name,
  fccd.name,
  fccx.accession,
  fcpt.name,
  fcp.value
FROM
  feature f
  JOIN feature_cvterm fc ON (f.feature_id=fc.feature_id)
  JOIN cvterm fcc ON (fc.cvterm_id=fcc.cvterm_id)
  JOIN dbxref fccx ON (fcc.dbxref_id=fccx.dbxref_id)
  JOIN db fccd ON (fccx.db_id=fccd.db_id)
  LEFT JOIN feature_cvtermprop fcp ON (fc.feature_cvterm_id=fcp.feature_cvterm_id)
  LEFT JOIN cvterm fcpt ON (fcp.type_id=fcpt.cvterm_id)
WHERE
  f.uniquename LIKE 'SPAC11G7.02%' AND
  fcc.name LIKE '%ubiquitin-dependent protein catabolic process%';
```
  uniquename   | pub_id |                     name                      | name | accession |    name     |               value               
---------------|--------|-----------------------------------------------|------|-----------|-------------|-----------------------------------
 SPAC11G7.02.1 |    260 | ubiquitin-dependent protein catabolic process | GO   | 0006511   | assigned_by | PomBase
 SPAC11G7.02.1 |    260 | ubiquitin-dependent protein catabolic process | GO   | 0006511   | with        | PomBase:SPAC24H6.05
 SPAC11G7.02.1 |    260 | ubiquitin-dependent protein catabolic process | GO   | 0006511   | evidence    | Inferred from Genetic Interaction
 SPAC11G7.02.1 |    260 | ubiquitin-dependent protein catabolic process | GO   | 0006511   | date        | 20081001

**Comment by kimrutherford** [comment]
Hi Mark.  I'm a bit confused.  Is there a problem in Chado?  If so, I can fix it tomorrow.

**Comment by markmcdowall** [comment]
Hi Kim,

Val just asked if I could have a look in the Chado db to see what I could find.

It looks fine to me and what is in the Chado is present on the gene pages. The with cdc25 is present on the gene pages in the full view.

Val: What extension is missing from the gene pages?

**Comment by ValWood** [comment]
for this one I think the entire annotation is missing. The visible annotation to 
Term ID	Term Name	Evidence	With/From	Reference	Count
GO:0006511	ubiquitin-dependent protein catabolic process	IGI	cdc25	Nefsky B et al. (1996)	178

is IGI. This one is IMP with cdc25 as has_input.

Does that make sense?

**Comment by ValWood** [comment]
I think I know what this might be....its a long shot...For some terms (localization terms) curated with IGI and with the qualifier "localization_dependency" you convert them to IMP with has_input (for the gene pages and for GO export), this usually works fine.

It seems as though something similar could be happening with this term, but only in the GO export file?

**Comment by markmcdowall** [comment]
Val: So should there be 2 annotations in the Chadodb? One with IGI and one via IMP?

**Comment by kimrutherford** [comment]
The v54 Chado has an annotation to:
  ubiquitin-dependent protein catabolic process  (IGI with SPAC24H6.05)

The latest load has the extension:
  ubiquitin-dependent protein catabolic process [has_input] SPAC24H6.05
but with the evidence code IMP.

The current annotation in Chado matches what is in the EMBL contig file.  Maybe the annotation was changed since v54?

**Comment by kimrutherford** [comment]
> Maybe the annotation was changed since v54?

Hi Val.  I checked the log and you made this change on Aug 13th:

    -FT                   process; GOid=GO:0006511; evidence=IGI;
    -FT                   db_xref=PMID:8635463; with=PomBase:SPAC24H6.05;
    +FT                   process; GOid=GO:0006511; evidence=IMP;
    +FT                   db_xref=PMID:8635463;
    +FT                   annotation_extension=regulates(PomBase:SPAC24H6.05);

Midori changed that on the 19th:

    -FT                   annotation_extension=regulates(PomBase:SPAC24H6.05);
    +FT                   annotation_extension=has_input(PomBase:SPAC24H6.05);

So I think that explains things.

**Comment by ValWood** [comment]
OK, sorry non issue!
