### ISSUE TITLE
TEMPORARY PAINT file to import

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#493]
We need to import the PAINT data soon because it now is included in the GO database. GO annotation in AmiGO will now differ from PomBase.

First I wan't to sanity check the PAINT data-  (although from the quick look I did at the GO meeting, it does seem to be much improved).

There are 3970 annotation lines in the current PAINT annotation file. PAINT, annotations are generated if we have an existing annotation with ISO/ISS/IC/ (non-EXP) evidence codes.
This duplication  doesn't bother me (I suspect most annotation duplicates whet we already have -at least from the spot check I did).  So, I only really want to look at the ones we don't have covered already.

To do this I have created a version of the file where I TEMPORARILY substituted all of the IBA evidence codes for IEA. Can you import this data for the next  chado interim release?
Annotations which have an existing annotation with ISO or IC will be suppressed during the import. I can then grep the remaining PANTHER annotations out of the file and check them (if there are not to many), or at least spot check them if there are lots.

If there are way too many errors, I'll ask GO if  these pombe annotations can be validated  by us before inclusion (i.e we are the authority) as happens for the other GOC annotation (at least I thought, but maybe this has changed?)

**Comment by ValWood** [comment]
The file is in the Dropbox data directory PAINT_tmp.txt

**Comment by ValWood** [comment]
As soon as its imported, let me know and I can grab the current GAF, then we should not re import it for the next build

**Comment by ValWood** [comment]
We also need to decide what to do with the NOT annotations in this file.

**Comment by kimrutherford** [comment]
> The file is in the Dropbox data directory PAINT_tmp.txt

Hi Val.  I can't see the file in Dropbox.

**Comment by ValWood** [comment]
My dropbox never seems to synch, I'll look into it. In the meantime I'll send it to you.....

**Comment by ValWood** [comment]
That *kinda* worked

Some stuff got filtered.

However, some stuff which  would get filtered normally did not ?

For example
PomBase	SPAC13G6.07c	rps601		GO:0042274	PAINT_REF:11502	IEA	PANTHER:PTN000161291	P	40S ribosomal protein S6	rps6-1	proteitaxon:4896	20110207	GO_Central

was retained

but we already have:
ribosome biogenesis	 ISO	SGD:S000006011	GO_REF:0000024

and IEA is always dropped if there is an ISO.

Can you have a look (I was also thinking we  if we are only  able to get rid of IEA's randomly against each other, we can run the  reduced file thorough a few times to get rid of more IEAs?)
I will send you the smaller file (it's about 50% down)

**Comment by mah11** [comment]
The specific example above is OK - GO:0042274 (IEA) is a bit more specific than ribosome biogenesis (ISO), so it makes sense that both are retained.

**Comment by ValWood** [comment]
OK, if I come across any redundant IEAs I'll update the ticket and we can go ahead and "refilter"

**Comment by kimrutherford** [comment]
I copied the results from that build to:
  http://curation.pombase.org/dumps/builds/pombase-build-2015-09-15-v1-l1-PAINT/

Shall I close this?

**Comment by ValWood** [comment]
yep.  I think all of the IEAs got filtered so probably not possible to reduce size further...
