### ISSUE TITLE
phaf format field description

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#494]
I wondered if the name of the genotype column should be changed?
http://www.pombase.org/submit-data/phenotype-data-bulk-upload-format
to background? as that is what is in this field.

transferred from
https://github.com/pombase/canto/issues/951

**Comment by ValWood** [comment]
From Midori:

As for what to call the columns, right now upload 7/download 8 is "Genotype description", and the "Strain name" column has (up6/down7) "background" as a bit of explanatory text. Both actually refer to background-related information, and the current PHAF the "genotype description" column isn't really doing the job of a proper, multi-allele-friendly "genotype details" file or column. I don't have strong feelings about what the column headers are, but I do think that's a separate issue from the multi-allele file question.

We haven't decided what to do for multi-allele phenotype upload or download formats. I've become pretty well convinced that a single file won't work well enough. (It won't be pretty with single or multiple files, but trying to adapt a single file would be uglier.)

**Comment by mah11** [comment]
related to https://github.com/pombase/curation/issues/693

**Comment by ValWood** [comment]
closing this. Should be dealt with by
https://github.com/pombase/curation/issues/693
