### ISSUE TITLE
regenerate the file which has the alleles described as "other"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#495]
We need a new version of this file so we can see which allele types are described as "other" and regenerate them. It might be quite nice to have this file in the log directory?

Alleles where the description is only "disruption"

i.e
cki1::ura4+,SPBC1347.06c,cki1,disruption,1b9692f34c4ac74a
pcn1::ura4+,SPBC16D10.09,pcn1,disruption,68f20cc081d78bc5
rrp6::ura4+,SPAC1F3.01,rrp6,disruption,d68db45202ee441d
cki2::ura4+,SPBP35G2.05c,cki2,disruption,1b9692f34c4ac74a

should be migrated to 'disruption' and excluded from this file?

For the others,  we will check and standardise

**Comment by ValWood** [comment]
Hi Kim, 

first just need to regenerate the file.  Then curators can decide  which other allele "types" we need.
Closing 
https://github.com/pombase/canto/issues/944 (wrong tracker)

**Comment by kimrutherford** [comment]
Is this what you need?:
   https://www.dropbox.com/s/ea70enxsst3g4rb/other_alleles-2015-09-17.csv?dl=0

The Chado query was:

    select f.name, f.uniquename, (select value from featureprop p where
    p.feature_id = f.feature_id and p.type_id in (select cvterm_id from cvterm
    where name = 'canto_session')) from feature f where type_id in (select
    cvterm_id from cvterm where name = 'allele') and feature_id in (select
    feature_id from featureprop p where p.type_id in (select cvterm_id from cvterm
    where name = 'allele_type') and p.value = 'other');

**Comment by ValWood** [comment]
Yep, can you include the allele description in the next version. Also is 
it possible to  include it  in the logs regularly?
Once we have fixed "disruptions" and decided what to do with "diploids" 
we can slowly look at the rest.

I see some which look like "multi gene" and some which could probably be 
done as "partial deletion" (truncation etc)



On 17/09/2015 02:19, Kim Rutherford wrote:
>
> Is this what you need?:
> https://www.dropbox.com/s/ea70enxsst3g4rb/other_alleles-2015-09-17.csv?dl=0
>
> The Chado query was:
>
> |select f.name, f.uniquename, (select value from featureprop p where 
> p.feature_id = f.feature_id and p.type_id in (select cvterm_id from 
> cvterm where name = 'canto_session')) from feature f where type_id in 
> (select cvterm_id from cvterm where name = 'allele') and feature_id in 
> (select feature_id from featureprop p where p.type_id in (select 
> cvterm_id from cvterm where name = 'allele_type') and p.value = 
> 'other'); |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pombase/pombase-chado/issues/495#issuecomment-140938239>.
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by kimrutherford** [comment]
I've added the query (including the allele description) to the load script.  Should be in the next load.  The log file ends with ".alleles_of_type_other"

**Comment by ValWood** [comment]
great, we can chip away slowly at that now.
Val

**Comment by kimrutherford** [comment]
Here's what it looks like:
  http://curation.pombase.org/dumps/builds/pombase-build-2015-09-15-v2-l1/logs/log.2015-09-21-05-58-41.alleles_of_type_other

It's a mess, but it's comma separated so it will load into Excel.

**Comment by ValWood** [comment]
Its fine. We will be ignoring it until the disruptions and diploids are migrated anyway. Then we'll take a look if anything else can move to standard descriptions, or if we need any new ones.
