### ISSUE TITLE
Don't create duplicated genotype on Chado load

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#497]
Example of a duplicate:

```
select g.name, g.uniquename, a.name, a.uniquename
  from feature g
  join feature_relationship r on g.feature_id = object_id
  join feature a on r.subject_id = a.feature_id
where g.type_id in (select cvterm_id from cvterm where name = 'genotype') and a.name = 'prp10delta';
```

**Comment by ValWood** [comment]
@kimrutherford is this high priority?

**Comment by kimrutherford** [comment]
> is this high priority?

It's not a big deal so not high priority.  It isn't causing problems for Ensembl loading, it's just a bit ugly.

**Comment by kimrutherford** [comment]
Val provided a good example in #611.

**Comment by kimrutherford** [comment]
> Example of a duplicate:

My example disappeared so here's a query for find all duplicated genotypes.

```sql
create temp table genotypes_and_alleles as
 select g.uniquename, array_to_string(array_agg(a.name order by a.name), ' ') as display_name
   from feature g
      join feature_relationship r on g.feature_id = object_id
      join feature a on r.subject_id = a.feature_id
    where g.type_id in (select cvterm_id from cvterm where name = 'genotype')
 group by g.uniquename;

select count(uniquename), display_name
   from genotypes_and_alleles
   group by display_name having count(uniquename) > 1;
```

**Comment by kimrutherford** [comment]
Val's example from #611 is still a problem - there are two identical genotypes like this:
cdc2-3w(C67Y aa) cdc25-22(C532Y aa) mcs2-75(unknown)

**Comment by kimrutherford** [comment]
This is still not fixed.  I'm going to leave it until we decide how we plan to store genotype background.

**Comment by ValWood** [comment]
Is this still current?

**Comment by kimrutherford** [comment]
> Is this still current?

Yes, it's still a problem.

**Comment by ValWood** [comment]
pinging this because it seems related to more recent issues...

**Comment by kimrutherford** [comment]
> pinging this because it seems related to more recent issues...

Which related issues?

This is only a problem in Chado.  The website code should merge all identical genotypes for display.

**Comment by kimrutherford** [comment]
I think this isn't worth fixing since it's an edge case in Chado only.  The website is fine.

Also the example in the first comment:
https://github.com/pombase/pombase-chado/issues/497#issue-107835012
isn't a duplicate because the background is different.
