### ISSUE TITLE
List of External databases used in Chado (standardization of database prefixes)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#50]
In this list we have
ChEBI/CHEBI
PomBse
PubMed/PMID
Rfam/RFAM
TAIT possibly TAIR?
Uniprot/UniProKB/ UniProtKB/Swiss-Prot
url/URL

Need to
1. Identify correct ones
2. Identify where errors are coming from
3. Fix
4. Implement checks to prevent incorrect Ids (dbxrefs list = PomBase specific/inhouse?)

Original comment by: ValWood

**Comment by ValWood** [comment]
Is this ticket still valid now?

**Comment by kimrutherford** [comment]
There are lots of DBs in Chado that don't come from PomBase annotation because we load lots of OBO files and external GAF files.  It's going to difficult to fix all the odd DB names that come from the sources.

**Comment by ValWood** [comment]
They should all conform to the GO db xrefs?
Can discuss tomorrow, and decide if we need to do anything.

**Comment by kimrutherford** [comment]
> They should all conform to the GO db xrefs?

It looks like there are a lot of cases where no checking is done.  The dbxrefs in the term definition ("def:") lines in OBO files are all over the place and often don't match anything in GO.xrf_abbs

**Comment by ValWood** [comment]
seems to overlap with
https://github.com/pombase/pombase-chado/issues/614

**Comment by ValWood** [comment]
This is a *very* long ticket, and I'm not sure it is still required. I think it is covered by 
#614 which  involved standardization of  database prefixes and is now close.

I'll close this. If anything buried in this ticket is still required please open new.
I'll have a poke around for any specific oddities  outstanding and open tickets to address those.

**Comment by ValWood** [comment]
and 
https://github.com/pombase/pombase-chado/issues/227
