### ISSUE TITLE
loading parser check required for unrecognised EMBL qualifiers

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#500]
Jist spotted and fixed:

/O="aspect=P; term=positive regulation of transcription from RNA polymerase II promoter; GOid=GO:0045944; evidence=IDA; db_xref=PMID:19101542; date=20090108"

problem annotation doesn't appear in logs , or on gene page
solution: report any "unrecognised" qualifier 'types"?

**Comment by ValWood** [comment]
We don't  need to do this, it can be checked with the grep command below.
There is nothing else like /O
but there are a few synonyms which need fixing, and an allele to delete which I will do now.

grep "/" *.contig |grep -v "/GO=" |grep -v "/controlled_curation"  | grep -v "/product=" |grep -v "/SO=" |grep -v  "/gene=" |grep -v "fasta_file=" |grep -v "/db_xref=" |grep -v "/systematic_id=" |grep -v "/colour=" |grep -v "/synonym" |grep -v "primary_name=" |grep -v "/note=" |grep -v "/EC_number=" | grep  " /" |grep -v "/obsolete_name=" |grep -v "pseudo" |grep -v "codon_start=" |grep -v "/transl_table" |grep -v "protein_id" |grep -v "/strain" |grep -v "estimated_length" |grep -v "/partial" |grep -v "/organism=" |grep -v chromosome= |grep -v /mol_type |grep -v "organelle="

gives:

chromosome1.contig:FT                   /shared_id="SPAC1556.06"
chromosome1.contig:FT                   /other_transcript="SPAC1556.06.1"
chromosome1.contig:FT                   /shared_id="SPAC1556.06"
chromosome1.contig:FT                   /obsolete_name_name="B22918-2"
chromosome2.contig:FT                   /sysnonym="SPNCRNA.1308"
chromosome2.contig:FT                   /synomym="png1"
chromosome2.contig:FT                   /synomym="mif2"
pMIT.contig:FT                   /allele="ad7-50h-."

**Comment by ValWood** [comment]
I'm flagging as 'required for Artemis migration' as we should run  to check that there are no malformed qualifiers which fail to load.
Everything which does not load should be reported somewhere.

**Comment by kimrutherford** [comment]
I think this is fixed by #635.
