### ISSUE TITLE
anomalies in exported PHAF

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#502]
I spotted a couple of odd things about the PHAF in the latest chado dump (pombase-build-2015-11-01-v1-l1.phaf.gz):

- No percentage values are being written out to the file.
- 546 lines have entries in the extension column like this: ",has_penetrance(FYPO_EXT:0000001)".

**Comment by kimrutherford** [comment]
I think I've fixed this now.  I'll check after the next load.
