### ISSUE TITLE
The changed_by field is JSON encoded

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#503]
The changed_by ~`cvtermprop`~ `feature_cvtermprop` is JSON encoded.  eg.
    [{"change_date":"2015-01-18","curator_name":"Midori Harris"}]

It should be plain text.

**Comment by ValWood** [comment]
I'm deprioritising  "internal" but this one has "next" , is it done (or important?) or quick?

**Comment by kimrutherford** [comment]
It's quick but not important until we need to use that Chado field in the web site (which may be never).  I've removed "next".

**Comment by kimrutherford** [comment]
Note to future self: the tricky thing here is that there can be more than one `changed_by` record and more than one curator:

```json
[{"change_date":"2014-10-06","curator_name":"Antonia Lock"},{"change_date":"2014-11-12","curator_name":"Midori Harris"}]
```

**Comment by kimrutherford** [comment]
I think this is fine as is.  It's bad form to put JSON is a database field like this but it works OK for us so let's leave it.
