### ISSUE TITLE
Do we filter redundant IC

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#505]
I thought we did? Did we change that.

If we do, there is a redundant IC on nbs1 page (nucleus, also has IDA)

**Comment by kimrutherford** [comment]
We don't filter redundant IC annotations.

Here's the list of evidence codes for filtering:
  https://github.com/pombase/pombase-chado/blob/master/lib/PomBase/Chado/GOFilter.pm#L87

**Comment by ValWood** [comment]
thanks, I remember now that we keep them (we don't make them if they are present from another source anyway)...I just wondered why we has a redundant one from uniProt but that all makes sense.
