### ISSUE TITLE
curatable and approved sessions

### ISSUE THREAD

**Issue by Antonialock** [pombase/pombase-chado#506]
Hi Kim, 
could you regenerate
approved_publications_per_year
curatable_publications_per_year
(the ones that live in dropbox, curation tool, queries)

thanks!

**Comment by kimrutherford** [comment]
Hi.  Hope this is what you need:
https://www.dropbox.com/s/u8niqsrdkvvaw1v/approved_publications_per_year-2015-11-26.csv?dl=0
https://www.dropbox.com/s/q4s1h8382hy8qb8/curatable_publications_per_year-2015-11-26.csv?dl=0

If not, I'll be around until 11am-ish in the morning.
