### ISSUE TITLE
stale PHAF log

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#509]
The last couple of dumps have included a log file from the 2015-11-14 build:
log.2015-11-14-12-16-36.phenotypes_from_PMID_15821139_phaf.txt

I guess it's not being updated because the PHAF in question was deleted a few days after it was added, but that doesn't explain why the old log is still hanging around.

affected builds include pombase-build-2015-11-28-v2-l1 and at least one before it

snippet from svn log -v external_data/phaf_files/chado_load/ :

    ------------------------------------------------------------------------
    r3094 | antonia | 2015-11-16 14:59:08 +0000 (Mon, 16 Nov 2015) | 1 line
    Changed paths:
       M /trunk/chromosome1.contig
       M /trunk/chromosome2.contig
       D /trunk/external_data/phaf_files/chado_load/PMID_15821139_phaf.txt
    
    gene exp 
    ------------------------------------------------------------------------
    r3082 | antonia | 2015-11-12 17:42:33 +0000 (Thu, 12 Nov 2015) | 1 line
    Changed paths:
       A /trunk/external_data/phaf_files/chado_load/PMID_15821139_phaf.txt
    
    added phaf 15821139
    ------------------------------------------------------------------------

**Comment by kimrutherford** [comment]
Thanks for catching that.  I've removed the rogue log file.  The problem was triggered by the PHAF file ending in .txt (PMID_15821139_phaf.txt)
