### ISSUE TITLE
Gracefully handle missing genes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#510]
If a gene in a session is missing from Chado the load fails (the transaction rolls back).  A warning would be much better.

**Comment by ValWood** [comment]
@kimrutherford  is this high priority?

**Comment by kimrutherford** [comment]
> is this high priority?

It's a pain when it happens because the whole load fails, but it's easy to spot (not enough genes).  So not high priority.

**Comment by ValWood** [comment]
Is this still the case?

**Comment by kimrutherford** [comment]
Yep, I haven't fixed it.

**Comment by ValWood** [comment]
Still the case, I think you might have done this?

**Comment by kimrutherford** [comment]
It's not fixed.  It's a bit tricky because there are many places in the loading code where it tries to lookup gene details in Chado.  All of those places need to be fixed to handle a missing gene.

I suggest we leave this for now and I'll have a go at fixing next time we have the problem, when it will suddenly become more urgent.  :-)

**Comment by kimrutherford** [comment]
After 9 years, I've finally made an attempt to fix this.  I'm doing a local load to test my changes.

**Comment by kimrutherford** [comment]
Fixed!

(Although I'll re-open if there's a problem with tonight's load)
