### ISSUE TITLE
Chado check failure - not enough genes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#511]
We're getting this in the Chado check log:

    pombe_genes - FAILURE:  expected >= 6980 but got 6966

It might be caused by the deletion of the dubious genes, but it needs checking.

**Comment by mah11** [comment]
Jira tickets from Val mention 14 deleted genes - 12 "dubious" in https://www.ebi.ac.uk/panda/jira/browse/PB-2501 and 2 ncRNA in https://www.ebi.ac.uk/panda/jira/browse/PB-2485

Does that cover everything?

**Comment by kimrutherford** [comment]
Yep, that's probably OK then.  The Chado check was expecting 6980 but got 6966 which is 14 genes less.

Thanks for checking Jira.  I'll modify the Chado check.
