### ISSUE TITLE
check if we import a score for BioGRID data

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#515]
A score is provided for Biogrid data when available

i) check if we import into Chado

i)  When we do, open a jira ticket to display on gene pages

**Comment by kimrutherford** [comment]
Just checked and we ignore the score column from the BioGRID files so it's not in Chado.  Should we be loading it?

**Comment by ValWood** [comment]
Yeah lets, no hurry. There are a couple of other biogrid related tickets so can adress together...  we'll go through them shortly....

**Comment by kimrutherford** [comment]
Maybe the score is useful on the gene pages?  Sometimes it's negative and sometimes it's positive so I'm not sure scores from different publications are comparable?  BioGRID show the score but they don't say what it means:

![image](https://github.com/user-attachments/assets/81fbb48d-22de-476d-9bf4-f0178009b18b)

**Comment by ValWood** [comment]
I had forgotten about this ticket. I think we should close.  Its going to be a bit arbitrary. because it includes many different methods and datasets.

Our rule is to ask BioGrid to filter known Falso positives. We usually only recorded the high confidence anyway.
