### ISSUE TITLE
exported PHAF has shrunk between builds

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#518]
It's far less alarming than in #516, but the PHAFs exported in the first few builds after that was fixed were 518-520K, whereas in latest (pombase-build-2016-01-23-v1-l1, currently the latest_build) it's 352K.

Should we worry?

**Comment by ValWood** [comment]
That sounds worrying. Kim ran out of time to make the chado version for Mark today and He's gone to bed now. He can look at this first tomorrow.

Val

**Comment by ValWood** [comment]
there is one error, but it seems that it would not make this much difference to the file size?

http://curation.pombase.org/dumps/latest_build/logs/log.2016-01-24-23-22-46.phenotypes_from_PMID_9563836_phaf

**Comment by mah11** [comment]
don't see how that could be it -- I thought only the affected line wouldn't get loaded (and it is literally only one line)

(also, I've fixed it, so it'll be ok in the next load)

**Comment by ValWood** [comment]
Ah OK, I wasn't sure if the file loading was aborted or just the line.

Is it obvious what is missing from the current file? Presumably a large number of rows are missing?

**Comment by mah11** [comment]
I could look, but surely Kim will when he goes to fix it tomorrow.

**Comment by ValWood** [comment]
OK

**Comment by kimrutherford** [comment]
I've tracked down the problem.  When I did the hack to get the terms loaded so we could get on with the release I accidentally removed the relations between the FYPO terms and their extended version.  eg. "resistance to lovastatin [has_expressivity] medium" should be an is_a descendant of "resistance to lovastatin", but the is_a relation is missing in Chado.

So the annotations were stored but the PHAF exporter isn't finding them for export.

I'll fix the problem and reload.  It should be ready in the morning.  Sorry for all the delays.

**Comment by ValWood** [comment]
that doesn't sound as though it would affect the *number* of annotations....

**Comment by kimrutherford** [comment]
> that doesn't sound as though it would affect the number of annotations....

All the terms in the DB, but because the relation structure is broken the PHAF exporter isn't exporting all the annotation.  I fixed it (I hope) and started a load as I went to bed.  It's about to finish then I'll check it.

**Comment by kimrutherford** [comment]
The load finished and it's all fine again.  I'm doing a final load now.
