### ISSUE TITLE
Update to Chado 1.31

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#519]
https://sourceforge.net/projects/gmod/files/gmod/chado-1.31/

The schema has changed so it would be good to try this soon.

**Comment by kimrutherford** [comment]
Release announcement:
  https://sourceforge.net/p/gmod/mailman/gmod-schema/thread/CA%2BJTaox%3D9jszXvvHHZkBj2CKcF1t%2B0O%2BXQEM7%2B8bh5U13yWeoQ%40mail.gmail.com/#msg34785399

**Comment by ValWood** [comment]
@kimrutherford  How soon?

**Comment by kimrutherford** [comment]
If we had known users of the Chado dumps it might be important for them to use the latest Chado as a base.  For us it doesn't matter because everything we have in Chado is compatible with the latest version of Chado from GMOD.  The tables and columns we use are standard core ones that have been in the Chado schema forever and aren't likely to change.

**Comment by ValWood** [comment]
OK, we can be "user lead" and put at "low priority" unless forced?

**Comment by kimrutherford** [comment]
> OK, we can be "user lead" and put at "low priority" unless forced?

Good plan.  I've changed the priority.

**Comment by kimrutherford** [comment]
> OK, we can be "user lead" and put at "low priority" unless forced?

After some thought and 8 years of this issue being ignore, I think we can close it.  It's unlikely we'll ever updated the schema.
