### ISSUE TITLE
contents of "modifications" file weird...

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#521]
Looks like this ;)

SPAC6F6.11c             MOD:01148       mass spectrometry evidence      K165            PMID:26412298   4896    20151111
$VAR1 = [
          'SPAC9.11',
          '',
          'MOD:00046',
          'experimental evidence',
          'S207',
          '',
          'PMID:24763107',
          '4896',
          '20140423'
        ];

**Comment by kimrutherford** [comment]
Whoops, thanks for spotting that. It's fixed now.
