### ISSUE TITLE
biogrid update

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#524]
Need to check biogrid updating is working.

We are wating on a big dataset which is already curated by BioGRiD. 
A Proteome-wide Fission Yeast Interactome Reveals Network Evolution Principles from Yeasts to Human

I thought it would come through this time...

chp1 tas3 for an example
PMID: 26771498

**Comment by kimrutherford** [comment]
We got the biogrid data for v57 on Dec 31.  I checked that set and PMID:26771498 isn't there.

**Comment by ValWood** [comment]
Thats fine. We can keep an eye on this for the next update.

**Comment by ValWood** [comment]
@kimrutherford  
Whoops I nearly forgot...we need to check this is in the update, it should be
(genome wide physical interaction data)

@markmcdowall  delay if not

**Comment by ValWood** [comment]
Its there, closing
