### ISSUE TITLE
no extensions in GO GAF

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#526]
Opeing a ticket in case its a separate issue

cut -f 16 pombase-build-2016-03-06-v2-l1.gaf  | sort |uniq

is zero

**Comment by kimrutherford** [comment]
OK, thanks.  I'll check the GAF file after fixing the loading.

CC @markmcdowall

**Comment by ValWood** [comment]
if the current  (new) GAF is now in place, still no annotation extensions...

**Comment by kimrutherford** [comment]
The new load isn't finished yet.

**Comment by kimrutherford** [comment]
Looks like this is fixed.
