### ISSUE TITLE
Improve speed and reliability of OBO loading

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#528]
Use https://github.com/pombase/chobo once it's done.

**Comment by ValWood** [comment]
wow your back up already!

**Comment by ValWood** [comment]
is this done?

**Comment by kimrutherford** [comment]
There's still a bit of work to do - maybe a week or two.  I haven't had a chance to work on it.

**Comment by ValWood** [comment]
okay doke

**Comment by ValWood** [comment]
Removed next for now, can bump back up when other 'next' done

**Comment by kimrutherford** [comment]
This is a mostly done now, although I've realised that the code doesn't load term synonyms.  That shouldn't take too long to fix.

**Comment by kimrutherford** [comment]
> although I've realised that the code doesn't load term synonyms.

That's done now and it's looking good.  I'm doing a test load.

**Comment by kimrutherford** [comment]
The load results are looking good now.  I'll close this and open issues for any bugs.
