### ISSUE TITLE
PHAF file empty fields

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#529]
(for next update)

some expression fileds are empty:
   1 Expression
 444 Knockdown
11015 Not specified
17952 
18121 Null
2136 Endogenous
2732 Overexpression

(should probably be not specified?)

**Comment by ValWood** [comment]
385 unrecorded
 802 wild type
33242 deletion
3481 unknown
3655 

3655 blank descriptions (unknown or unrecorded?)

**Comment by ValWood** [comment]
whoops, showstopper
  1 Genotype description
52400 

(i f this only affects the file  maybe the file can be regenerated but we can go ahead with the update?)

**Comment by kimrutherford** [comment]
> Genotype description

Should that be?:

   background + allele name + (allele description)

Some genotypes have a name but I guess that's now what you mean by description.

**Comment by ValWood** [comment]
ignore me. I was confusing this with "allele description" which is in column 3. This column isn't mandatory
http://www.pombase.org/submit-data/phenotype-data-bulk-upload-format
