### ISSUE TITLE
modification file content

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#530]
is

SPBC2F12.05c		MOD:00046	experimental evidence	S365	present_during(GO:0000087)	PMID:21712547	4896	20110628
$VAR1 = [
          'SPAC23D3.13c',
          '',
          'MOD:00046',
          'experimental evidence',
          'S662',
          'present_during(GO:0000087)',
          'PMID:21712547',
          '4896',
          '20110628'
        ];
 
SPAC23D3.13c		MOD:00046	experimental evidence	S662	present_during(GO:0000087)	PMID:21712547	4896	20110628
$VAR1 = [
          'SPBC14C8.17c',
          'spt8',
          'MOD:00046',
          'experimental evidence',
          'S329',
          'level_fluctuates_during(GO:0000278)',
          'PMID:24763107',
          '4896',
          '20140423'

etc

**Comment by kimrutherford** [comment]
I've fixed the code and replaced the data file.
