### ISSUE TITLE
QC check log.2016-03-10-20-59-59.excluded_fypo_terms

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#534]
is this file updating?
https://curation.pombase.org/dumps/latest_build/logs/log.2016-03-10-20-59-59.excluded_fypo_terms

I have been adding terms to here
FYPO_terms_excluded_from_pombase.txt 
which I know have direct annotations, but the violations have not appeared.

e.g.
FYPO:0001369    mislocalized actomyosin contractile ring
FYPO:0000608    abnormal cell cycle arrest in mitotic M phase

**Comment by kimrutherford** [comment]
The loader reads pombe-embl/mini-ontologies/FYPO_qc_do_not_annotate_subsets.obo find fypo terms to exclude.  It doesn't look at FYPO_terms_excluded_from_pombase.txt

It's been that way since it was first implement on 2015-01-06.

**Comment by ValWood** [comment]
Doh.
OK, I forgot to tell you. We have a new file for a 'soft check' on FYPO annotations, which matched the GO soft checks file. I forgot to let you know we were doing this.

The GO soft checks file is

pombe-embl/supporting_files/GO_terms_excluded_from_pombase.txt
is used to generate
log.2016-03-10-20-59-59.excluded_go_terms

The pombe-embl/mini-ontologies/FYPO_qc_do_not_annotate_subsets.obo find fypo terms 
is used to generate
log.2016-03-10-20-59-59.excluded_fypo_terms


Can we make the new file
pombe-embl/supporting_files/FYPO_terms_excluded_from_pombase.txt
generate a file
log.2016-03-10-20-59-59.excluded_fypo_terms_softcheck

We can also rename the GO  excluded file
log.2016-03-10-20-59-59.excluded_go_terms_softcheck
for consistency (especially if we decide to use the GO do not annotate subset for a hardcheck)

**Comment by kimrutherford** [comment]
What is the difference between a "soft check" and the current excluded terms files?  The excluded_fypo_terms and excluded_go_terms files are produced in the same way except that for fypo the term IDs are read from the OBO file.  Does that make both of them "soft checks"?

**Comment by ValWood** [comment]
You can treat them the same. The difference for us is whther they definitely need to be fixed or not.

The hard check ones should not be used at all.

The soft heck ones it is likely that they shouldn't be used and so we check them. It is possible that we will not be able to fix every occurence, but we might still want to keep the term in the sort checks file to alert us about any new uses.

Does that make sense?

**Comment by ValWood** [comment]
Do we need to discuss this one?

**Comment by ValWood** [comment]
maybe worth looking at when you do 
https://github.com/pombase/pombase-chado/issues/539
(same type of external file)

**Comment by kimrutherford** [comment]
I think I understand this now.

**Comment by kimrutherford** [comment]
I've renamed the GO soft check log file and add a FYPO soft check file.  Should be in the next load.

**Comment by kimrutherford** [comment]
Sorry, I checked in the wrong fix.  The FYPO soft check is there now:
  https://curation.pombase.org/dumps/latest_build/logs/log.2016-05-31-22-08-20.excluded_fypo_terms_softcheck
https://curation.pombase.org/dumps/latest_build/logs/

It's quick small.
