### ISSUE TITLE
Rename annotated_gene_feature_per_publications

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#535]
Add "pombase_" to match the other PomBase views.

Also maybe feature_id and pub_id would be more useful columns.

@markmcdowall

**Comment by ValWood** [comment]
We are on 58 now, 59 pending.  Is this needed urgently? If not I'll remove the "next" label (unless its quick or it breaks things)

**Comment by kimrutherford** [comment]
The renaming it done but the extra columns aren't there.  It's not urgent at all so I removed "next".

**Comment by ValWood** [comment]
@kimrutherford , is this still relevant?

**Comment by ValWood** [comment]
@kimrutherford , is this still relevant?

**Comment by ValWood** [comment]
adding low priority, remove if not

**Comment by kimrutherford** [comment]
Done!
