### ISSUE TITLE
filtering of duplicate annotations from the same paper

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#536]
We need to check that this is working correctly. There are a lot of  duplicate IPI annotations for example on the skp1 page.

for example:
![exact duplicates from the same paper](https://cloud.githubusercontent.com/assets/7359272/13745696/6066f5e4-e9e7-11e5-830f-de613b6bb26e.jpg)

and

![exact duplicates from the same paper2](https://cloud.githubusercontent.com/assets/7359272/13745712/746bf4f4-e9e7-11e5-84e1-794f3e32dab6.jpg)

**Comment by ValWood** [comment]
this appears to be because we occasionally make duplicated annotation with Unprot, although this shouldn't happen anymore. However I just noticed that Intact are making LOTs of duplicates

see attached

![duplication](https://cloud.githubusercontent.com/assets/7359272/13745775/cba72e78-e9e7-11e5-9b02-c99818179b30.jpg)

so the situation will get worse bacause some annotations will be represented 3 times now!

**Comment by ValWood** [comment]
Solution:

After converting  to standard systematic IDs (column 2 and the 'with field (column8)

Only keep annotations if  they are unique  *apart from*
submitter  
date
(for these purposes you can ignore other synonyms, names and object symbols).


Also, discard if the ontology term is less specific than the one we have used for the same gene from the same paper.

I'm not sure how much of this is happening in the current filtering pipeline.
If its all happening, maybe there are some extensions which are making these annotations unique (I don't think we do anything yet with extensions on external data wrt display but they might be used to determine 'uniqueness')

**Comment by ValWood** [comment]
We'll look to slotting this in before the next chado update

**Comment by ValWood** [comment]
from https://github.com/pombase/pombase-chado/issues/594 and
from https://github.com/pombase/pombase-chado/issues/640
as it should be addressed wen this is done

Something else to think about for the filtering. I am transferring this from
pombase/canto#1155 (comment)
because it is more relevant here. I was confusing extensions in GOA GAF with extensions from web-services.

According to Rachel there are 98 extensions from IntAct and 4 from UniProt (this was a while ago)

 So we need to check that extension are arriving in the GOA GAF
 Then we need to convert IDs in extensions to PomBAse IDs
 When filtering we will need to retain any annotations with unique extensions

**Comment by ValWood** [comment]
This isn't a huge problem yet, can bump up later

**Comment by mah11** [comment]
Many of the duplicate annotations reported in the log created for #324 come from UniProt or from GOC MF-BP inferences, and therefore should get filtered somewhere along the line. The list as of today (from the log.2018-03-23-01-21-03.chado_checks log) is attached.

[duplicate_GO_to_filter_20180323.txt](https://github.com/pombase/pombase-chado/files/1842552/duplicate_GO_to_filter_20180323.txt)

**Comment by ValWood** [comment]
If they are experimental evidence codes they won't get filtered by our current filtering because we don't filter any experimental annotation.

The redundancy via F-P links should be fixed by
https://github.com/geneontology/go-site/issues/576

we will need to think about what to do about uniprot/Intact duplicates ....

**Comment by mah11** [comment]
> we will need to think about what to do about uniprot/Intact duplicates

I think if they're identical to or less specific than our annotations, chuck 'em. We're the authoritative source for pombe annotations.

**Comment by ValWood** [comment]
good  ;)

**Comment by ValWood** [comment]
We now filter duplicates from uniprot and report in a logfile
