### ISSUE TITLE
non-ASCII characters in allele names 

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#538]
Reported in Jira ticket https://www.ebi.ac.uk/panda/jira/browse/PB-2596

Quoth Mark: "There are non-ascii characters in the features.name column in the alleles. This is causing an issue with the loading of the BioMart which backs up the query builder on the PomBase site."

The jira ticket also has a table with further details.

**Comment by mah11** [comment]
genotypes in question now fixed at source (canto session a525406360ac556a)

**Comment by kimrutherford** [comment]
> genotypes in question now fixed at source (canto session a525406360ac556a)

Thanks!

Mark, if you query like:
  select regexp_replace(name, '[^\x01-x7f]', '', 'g') from feature where ...

it should remove the non-ascii characters.

I've added a Chado check to report non-ascii characters when the load finishes.

@markmcdowall

**Comment by kimrutherford** [comment]
Mark, is the a bug lodged with the Biomart people to fix the problem at their end?  Do they have a public bug tracker?

**Comment by ValWood** [comment]
Is this one reported?

**Comment by ValWood** [comment]
So there is a chado check now, we can close this ticket. 
@markmcdowall  was this reported to Ensembl. Should I open a ticket  on the jira tracker?
