### ISSUE TITLE
GO terms not to annotate filter

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#539]
This file
GO_terms_excluded_from_pombase.txt

has had these terms for a while:

GO:0005816	spindle pole body
GO:0005819	spindle

There are definitely direct annotations (can't remember which gene)
![mitotic](https://cloud.githubusercontent.com/assets/7359272/14120020/df6a1fda-f5e8-11e5-97bb-50485f0603b6.jpg)

but this does not appear in the log file as a violator
https://curation.pombase.org/dumps/latest_build/logs/log.2016-03-10-20-59-59.excluded_go_terms

**Comment by ValWood** [comment]
klp9 is one eg

**Comment by ValWood** [comment]
These should appear in the GO filtered logs but don't.
Its fine for this release as these aren't wrong  and it's a soft check, but we should try to have a look at this before the next update,

/GO="aspect=C; term=spindle; annotation_extension=exists_during(GO:0000090); GOid=GO:0005819; evidence=IDA; db_xref=PMID:19570910; date=20090707"
/GO="aspect=C; term=spindle midzone; annotation_extension=exists_during(GO:0000090); GOid=GO:0051233; evidence=IDA; db_xref=PMID:19570910; date=20090707"

**Comment by ValWood** [comment]
in:
/pombe-embl/supporting_filesGO_terms_excluded_from_pombase.txt

**Comment by kimrutherford** [comment]
The query wasn't allowing for annotation extensions.  I've fixed it for the next load.

Here is the output when I run it against v59:
  https://www.dropbox.com/s/eqeynkggahlp14m/pombase-v59.excluded_go_terms.txt?dl=0

**Comment by ValWood** [comment]
Yep, everything is expected is now there. Fixed a big chunk, will do the rest later...
