### ISSUE TITLE
partial amino acid deletion

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#540]
I just created one like this. I don't know if comma separated is allowed (not documented), but I guess ti should be...(allowed)

1-1244,1672-1828

**Comment by Antonialock** [comment]
yeah pretty sure I've done that too..

**Comment by kimrutherford** [comment]
> I just created one like this.

Is that the description of the allele?  I don't think there is much checking at the moment so it shouldn't be a problem.

**Comment by ValWood** [comment]
OK, we'll know if it turns up in the logs, otherwise ignore.
I'll close anyway...
