### ISSUE TITLE
PHAF error message improvement

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#541]
The awesome users who submitted the PHAF for PMID:26791325 didn't have data for expressivity, penetrance, or extensions, so they omitted those columns (now fixed; my oops for not spotting it until the error message appeared, and I've just updated the format description on the web).

The tiny little outstanding problem is that all we get in the logs is "Taxon missing - skipping", so when the taxon is actually there in all rows (as in this case) it's kind of misleading, and actually makes it take longer to figure out what's really wrong.

It would be easier to spot the actual problem - and therefore great - if the error message could be a little more specific, and less cryptic. Even a generic "some columns missing" would be a better lead, because at least we'd know we should check which one(s).

(Tangential wittering: in the even longer term, perhaps look into making the loader clever enough not to require non-mandatory columns? It could just use the headers to determine which columns are present, and in what order. The beerfestdb loading code does this, and it's really convenient. Not that the prospect of an evening full of beer data munging is making me obsess at all, oh no ...)

**Comment by kimrutherford** [comment]
Thanks for fixing that PHAF file.

> Even a generic "some columns missing" would be a better lead

Good point.  I've improved the message.

>  in the even longer term, perhaps look into making the loader clever enough not to require non-mandatory columns?

I made a ticket for that: #542
