### ISSUE TITLE
munge pHAF file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#543]
Hi Kim,

No urgency, but when you get a moment could you do a quick perl to munge the PHAF file into a GAF to try  the AmiGO installation:

GAF 1 -> PHAF 1
yes (though we've actually omitted this column from the files Kim loads into Chado because we haven't taken any external files to date)

GAF 2 -> PHAF 2
yes

GAF 3 -> PHAF 10
very dodgy, because GAF 2 and 3 refer to the SAME object, whereas PHAF 10 refers to a specific allele, NOT the same db object as the gene; I would go with the gene name as we do with actual GAFs, i.e. PHAF 9

GAF 4 -> n/a
yes

GAF 5 -> PHAF 3
yes

GAF 6 -> PHAF 18
yes

GAF 7 -> PHAF 13
yes

GAF 8 ->n/a
yes

GAF 9 -> n/a
yes

GAF 10 -> n/a
true, there's no exact equivalent, but this would be a safer place than GAF 3 for PHAF 10

GAF 11 ->n/a
true, there's no exact equivalent, but could use PHAF 11 (it's no worse, and maybe slightly better, than mapping GAF 3 to PHAF 10)

GAF 12 -> n/a
true, there's no exact equivalent, but could use PHAF 12 (it's no worse, and maybe slightly better, than mapping GAF 3 to PHAF 10)

GAF 13 -> PHAF 19
yes

GAF 14 -> PHAF 20
yes

GAF 15 -> n/a
will always be "PomBase" for the foreseeable future, so we could plug it in

GAF 16 -> 15, 16 and 17
yes

GAF 17 -> n/a
no exact equivalent, but could use for an allele ID 

(I was hoping I could do it with cut, but you can't change the output order, hence I'd need to do a quick script...if anyone can do before Kim gets to it, go ahead......I might  but probably not this week)

**Comment by mah11** [comment]
could have a look at Dropbox/pombase/ontologies/phenotype/phaf_to_crap_gaf.pl ...

**Comment by ValWood** [comment]
;-)))))

**Comment by ValWood** [comment]
If I'm all packed will take a look soon.....

**Comment by kimrutherford** [comment]
> could have a look at Dropbox/pombase/ontologies/phenotype/phaf_to_crap_gaf.pl

Thanks Midori.  I like the script name.

Can this issue be closed now?

**Comment by ValWood** [comment]
I think so...
we are done until we hear back from Seth
