### ISSUE TITLE
filtering issue check (IC)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#547]
Remind me...I though we filtered redundant IC but
![supress ic](https://cloud.githubusercontent.com/assets/7359272/15658565/ce3522a2-26b5-11e6-9027-3aa2767b74f5.jpg)

**Comment by kimrutherford** [comment]
> I though we filtered redundant IC

Yep, IC is filtered.  I'll check this annotation.

**Comment by kimrutherford** [comment]
I forgot to ask, which gene is that?

**Comment by kimrutherford** [comment]
No problem, found it: cwg2 (SPAC2E1P5.04c).  I don't know what the problem is yet though.

**Comment by kimrutherford** [comment]
> Yep, IC is filtered. I'll check this annotation.

Sorry, I got that wrong.  IC is kept.  Here is a previous discussion: #505

**Comment by ValWood** [comment]
Yes I forgot.  We can delete if we have experimental....
