### ISSUE TITLE
file names for soft checks

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#548]
log.2016-05-31-22-08-20.excluded_fypo_terms		 
[   ]	log.2016-05-31-22-08-20.excluded_go_terms_softcheck

rename FYPO one too?

**Comment by kimrutherford** [comment]
Hi Val.  I left this too long and now I can't work it out.

The output of comparing with FYPO_qc_do_not_annotate_subsets.obo goes into:

    log.2016-06-19-23-03-25.excluded_fypo_terms

And the output of pombe-embl/supporting_files/FYPO_terms_excluded_from_pombase.txt goes to:

    log.2016-06-19-23-03-25.excluded_fypo_terms_softcheck

Is that right?

**Comment by ValWood** [comment]
yes
