### ISSUE TITLE
unused annotation_extension terms

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#55]
Get rid of unused annotation_extension terms in chado
http://oliver0.sysbiol.cam.ac.uk/pombe/view/object/cv/47?model=chado

**Comment by ValWood** [comment]
Do you have a list?

**Comment by kimrutherford** [comment]
> Do you have a list?

There are 10,000 or so in Chado.

> We need a database check to report these and a tidy-up script to remove them.

I think I've changed my mind.  They aren't causing a problem and the aren't visible to users.  The advantage of keeping them is that the internal "PBO:..." term IDs remain stable.  That isn't essential but it is sometimes helpful for tracking down problems.

**Comment by ValWood** [comment]
OK
