### ISSUE TITLE
Merge duplicate genotype when loading

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#551]
When loading Canto sessions into Chado if two identical genotypes come from different sessions you'll get two genotype features.

Moved from pombase/canto#966

**Comment by ValWood** [comment]
Is this a duplicate?
https://github.com/pombase/pombase-chado/issues/497

**Comment by kimrutherford** [comment]
> Is this a duplicate?

Yep.  Thanks for spotting that.
