### ISSUE TITLE
Missing annotation in Chado v59 and v60

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#552]
From pombase/curation#946:

These gene have no annotation in Chado, not even a product:

SPBC713.13
SPAC823.02
SPAPB1A11.05

There is annotation for these in v58.

Fix this and add a post load check that all genes have a product.

**Comment by kimrutherford** [comment]
Update https://www.ebi.ac.uk/panda/jira/browse/PB-2633 when fixed.

**Comment by kimrutherford** [comment]
> These gene have no annotation in Chado, not even a product:

That's true, but due to poor querying that's not the full answer.  My dodgy query returned no annotation because those genes aren't in Chado.  In the contig files and in Chado all three IDs are synonyms of other genes.

There is one fix that is needed in the contig files.  The systematic_id here should be changed to "SPAC823.17":

    FT   intron          2583903..2583940
    FT                   /controlled_curation="term=misc, confirmed intron"
    FT                   /systematic_id="SPAC823.02"
    FT                   /gene="SPAC823.17"

Please don['t fix it just yet because when the current load finishes I'll look into why that didn't generate a warning.

**Comment by ValWood** [comment]
I won't but we need to  careful here. The gene on the opposite strand is SPAC823.17
http://www.pombase.org/spombe/result/SPAC823.17

I think it might be correct in Art. This is the intron feature, not the CDS (no product on inton) ? Will take a look later...

**Comment by kimrutherford** [comment]
> Please don't fix it just yet because when the current load finishes I'll look into why that didn't
> generate a warning.

I've added a warning to the logs.  I'll run a load soon now with the change.

**Comment by ValWood** [comment]
This is how 'Art' looks

CDS
/systematic_id="SPBC713.14c"
/product="Schizosaccharomyces pombe specific protein"
/synonym="SPBC713.13"

pombase
http://www.pombase.org/spombe/result/SPBC713.14c

but there is also a page for the synonym?
http://www.pombase.org/spombe/result/SPBC713.13

I think the other 2 might be similar.....

**Comment by kimrutherford** [comment]
This isn't a Chado problem so I'll close it.
