### ISSUE TITLE
go terms not to annotate, file filtering check

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#553]
In this file
https://curation.pombase.org/dumps/latest_build/logs/log.2016-06-19-23-03-25.excluded_go_terms_softcheck

I see
SPBC359.01.1		GO:0006865	amino acid transport		InterPro

but in artemis we have:
/GO="aspect=P; term=amino acid transmembrane transport; GOid=GO:0003333; evidence=ISS; db_xref=GO_REF:0000024; with=InterPro:IPR002293; date=20091214"

(a  more specific ISS, note this gets converted to ISM I think)

This is odd because the file contents otherwise look OK?
 This could happen if a relationship disappeared temporarily

but all looks OK here:
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0003333#term=ancchart

a bit baffled by this one.....

**Comment by ValWood** [comment]
here is another one

SPBC29A10.04.1		GO:0005694	chromosome		UniProt

but this has 
	nuclear mitotic cohesin complex IDA and this is a child of chromosome...

**Comment by ValWood** [comment]
Can double check after the next log files generated in case some ontology temporary glitch?...

**Comment by mah11** [comment]
This is a GO issue - the links are missing in the current ontology files. Nothing for Kim to do but wait ...

(QuickGO just hasn't been updated since the problem cropped up)

**Comment by ValWood** [comment]
Also first for  https://github.com/pombase/pombase-chado/issues/557 no filtering at present so lots of stuff in there which would not be normally

**Comment by ValWood** [comment]
All fine,  nce filtering fixed, remainder were ontology issues etc....
