### ISSUE TITLE
error for all PHAF files

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#554]
Just spotted that this is in all of the files. I don't know what it means.....

more the one relation cvterm returned for part_of:
terms: BFO:0000050 and _global:part_of

**Comment by mah11** [comment]
I emailed Kim about these last week. It's an OBO relations oddity that neither of us completely understands ...

**Comment by kimrutherford** [comment]
I've made an Chobo issue for it: pombase/chobo#5
