### ISSUE TITLE
Create a phenopackets format file writer

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#556]
See discussion: phenopackets/phenopacket-format#67

**Comment by kimrutherford** [comment]
I spotted this announcement: https://www.ga4gh.org/news/phenopackets-v2-expands-utility-to-provide-a-more-complete-medical-picture/

**Comment by ValWood** [comment]
I'm sure I found a publication about phenopackets recently, but can't find it in PubMed or Bio-archive.  It seems to be more about person/pedigrees and clinical data, samples etc. So it doesn't seem appropriate for our  phenotype data.

Monarch seems happy to import the PHAF 
@cmungall is this true?

(although at some point we will need to address multi-gene phenotypes which do not fit PHAF format)

**Comment by kimrutherford** [comment]
> See discussion: https://github.com/phenopackets/phenopacket-format/issues/67

That repo has been archived, along with the issue.

New repo: https://github.com/phenopackets/phenopacket-schema

**Comment by ValWood** [comment]
I think this is out of date,
