### ISSUE TITLE
status totals (quick?)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#561]
I usually get the status totals from the query builder, but JB would like an interim update for a grant.

Could you  supply me with 
protein coding status
1. published
2. biological role interred
3. conserved unknown
4. S. pombe specific protein uncharacterised
5. Schizosaccharomyces specific proetin, uncharacterized
(I'm not sure how these are stored in Chado, but they come from the artemis 'colour' qualifier.

In fact there might be a   link where I can access them for the current build directly?, so you might only need to point me here?

 - [ ] update totals  in spreadsheet for JB (vw)

**Comment by mah11** [comment]
https://curation.pombase.org/pombe/view/object/cv/21?model=chado

**Comment by ValWood** [comment]
Thanks, I sent the updated spreadsheet to JB
