### ISSUE TITLE
more stats

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#562]
We should aim to make all possible stats available on a public page (in addition to the Canto curation stats). This is a placeholder to describe anything that could be included.

Add ideas to the list:
 - [ ] Curation counts by type see https://github.com/pombase/pombase-chado/issues/570
 - [x] Curation counts community vs curator (by time)
 - [x] Annotation quantity by paper over time
 - [ ] Webstats (eventually)

**Comment by kimrutherford** [comment]
> We should aim to make all possible stats available on a public page

Should that be on the main PomBase web site?

**Comment by ValWood** [comment]
I think so (in the long term), but the Canto subset would also be available from Canto. We can concentrate only on the Canto specific ones now, and add the others in the future....

**Comment by ValWood** [comment]
Closing this, need a ticket for webstats, but thats a longer way off
