### ISSUE TITLE
Add a post-process to set the feature.residues field where possible

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#568]
That would makes querying sequences easier for others.

**Comment by ValWood** [comment]
@kimrutherford  how urgent is this one. if after website put at low priority....

**Comment by kimrutherford** [comment]
I think doing this in Chado will make the website code easier and it's a nice thing to have anyway.

**Comment by ValWood** [comment]
OK will keep this here.

**Comment by kimrutherford** [comment]
Note to self: cope with /codon_start=...
