### ISSUE TITLE
Update to latest obo-relations / ro-chado.obo

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#572]
is_a has been removed - see oborel/obo-relations#115

**Comment by kimrutherford** [comment]
Actually, we can delay this as it's not urgent.  As long as we don't manually update obo-relations the load will be fine.  It doesn't get updated automatically.

**Comment by ValWood** [comment]
@kimrutherford Higher or lower priority than web pages?

**Comment by kimrutherford** [comment]
> Higher or lower priority than web pages? 

Much lower.  :-)

I think we could avoid updating until we need a relation from the latest obo-relations.  That doesn't happen very often.

**Comment by ValWood** [comment]
OK, can move forward when required...

**Comment by ValWood** [comment]
status?

**Comment by kimrutherford** [comment]
Since I'm able to do test loads on my desktop now, I've updated to the latest version of the obo-relations repository and I'm going run a load now as a test.  obo-relations removed the is_a relation so I've changed things so that is_a is added before any other ontologies are loaded.

If my local load works I'll update on oliver0 and then close this issue.

**Comment by kimrutherford** [comment]
It seems fine locally so I'm trying the latest obo-relations ontology in tonight's load.

**Comment by kimrutherford** [comment]
> It seems fine locally so I'm trying the latest obo-relations ontology in tonight's load.

After a few failures the load now works again and we're on the latest obo-relations ontology.
