### ISSUE TITLE
log file problem, modification extension

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#573]
warning in 3aac4505bb3ec2e8: in annotation extension for SPAC22A12.15c.1, can't parse identifier: 10

looks fine to me:

![error](https://cloud.githubusercontent.com/assets/7359272/18211263/b4d9fce6-7134-11e6-878b-1abf5a8e2fd0.jpg)

or did anyone fix it already?

**Comment by ValWood** [comment]
did @mah11  or @Antonialock  fix this annotation?

**Comment by mah11** [comment]
I have never done anything with this paper or session.

It may have something to do with the fact that we added the "occupancy" option for bulk modification data (and then the submitter decided not to use it after all!), and never properly thought about how it would play with Canto.

**Comment by mah11** [comment]
smidge of background in https://github.com/pombase/pombase-chado/issues/392

**Comment by ValWood** [comment]
Are OK, this is probably the only use case. It's likely that Kim needs to  so something to allow it?

First off is the config file correct? It says:

MOD:00000       is_a    occupancy       %       proportion of proteins with modification                0,1     user

**Comment by ValWood** [comment]
seems to be....
FYPO:0000002    is_a|has_part   has_penetrance  FYPO_EXT:1000002|%      penetrance      proportion of the population that shows the phenotype (can be quantitative or qualitative)      0,1     user

**Comment by kimrutherford** [comment]
> FYPO_EXT:1000002|%

Thanks Val.  I think that's the clue I needed.  I had a look at the code I couldn't see a problem.
Now you've pointed out the config, I think the code is being dumb and tries to parse the "10" as a FYPO extension - it's not handling the "|".

**Comment by ValWood** [comment]
Its working for FYPO, but not for modification. Maybe the  config file isn't quite right?

**Comment by kimrutherford** [comment]
> Its working for FYPO, but not for modification.

Ah, thanks.  It was working for has_penetrance but not for occupancy.  Fixed now.
