### ISSUE TITLE
qualifiers PBHQ: errors

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#574]
This file

https://curation.pombase.org/dumps/latest_build/logs/log.2016-09-04-23-07-57.qualifier_counts_by_cv

has
   3 | PBHQ:002                 | biological_process
     2 | PBHQ:004                 | biological_process
 26 | PBHQ:004                 | molecular_function

I'm assuming this is colocalizes_with or contributes to, but also has
 319 | contributes_to           | molecular_function
 34 | colocalizes_with         | cellular_component

**Comment by kimrutherford** [comment]
> has
> 3 | PBHQ:002 | biological_process
> ...
> 34 | colocalizes_with | cellular_component

It looks like the PBHQ is coming from the Canto loading and the colocalizes_with is coming from GOA.  I'm not sure if the name or the ID is the best thing to store in this case.  I'll have a little think then make them consistent.

**Comment by kimrutherford** [comment]
I've looked harder and it seems that the problem will sort itself out if the PBHQ OBO file was loaded into Chado.  It was missing but it will be in the next load.

**Comment by ValWood** [comment]
Is that the same problem as this?
I screen grabbed this yesterday, but forgot to record which session it was. I wondered it it was already reported in the logs, but I can't see anything?


![canto](https://cloud.githubusercontent.com/assets/7359272/19433849/531db210-945a-11e6-879f-d50559c13f5e.jpg)

**Comment by ValWood** [comment]
deleting the above comment. I found a better eg, and its a different issue. Will open a new ticket for this

**Comment by kimrutherford** [comment]
> I've looked harder and it seems that the problem will sort itself out

It didn't - I'll investigate.

**Comment by kimrutherford** [comment]
I've fixed the code that stores qualifiers.  I'll check after the next load.

**Comment by kimrutherford** [comment]
All OK now.
