### ISSUE TITLE
logs warning from checking feature

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#575]
I'm ignoring this- what does it mean?

warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked
warning in 26a7509190100074: some data from annotation isn't used: checked

**Comment by mah11** [comment]
https://github.com/pombase/canto/issues/1184

**Comment by ValWood** [comment]
Yep I'm not sure what this means in the logs... (if we  don't use this feature we don't need anything in the logs, but if we do need this feature we don't need anything in the logs....)

**Comment by kimrutherford** [comment]
> Yep I'm not sure what this means in the logs...

Sorry, the "checked" flag is leaking though into the Canto file that gets loaded into Chado.  It's harmless.  I'll fix the Canto exporter.
