### ISSUE TITLE
Deletion alleles which do not match

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#576]
Please generate this list

https://github.com/pombase/canto/issues/1162#issuecomment-227117944

(Ensuring it contains only differences marked deletion)

**Comment by kimrutherford** [comment]
name         |       uniquename        |  value
---------------------+-------------------------+----------
 ral2                | SPBC21.05c:allele-2     | deletion
 dfp1delta::ura4+    | SPCC550.13:allele-7     | deletion
 sec61delta::ura4+   | SPBC354.02c:allele-3    | deletion
 cyr1delta::ura4+    | SPBC19C7.03:allele-3    | deletion
 cdc13delta::ura4+   | SPBC582.03:allele-5     | deletion
 cig1::ura4          | SPCC4E9.02:allele-2     | deletion
 met11::his3         | SPAC343.10:allele-3     | deletion
 met9::ura4          | SPAC56F8.10:allele-4    | deletion
 cuf2                | SPCC584.02:allele-3     | deletion
 mcm7delta::his3+    | SPBC25D12.03c:allele-14 | deletion
 ypt3delta::ura4+    | SPAC18G6.03:allele-4    | deletion
 ypt1delta::ura4+    | SPBC1703.10:allele-2    | deletion
 orc1::ura4+         | SPBC29A10.15:allele-3   | deletion
 qtrtd1              | SPAC2F3.13c:allele-3    | deletion
 mdm31delta::LEU2    | SPAC3H1.04c:allele-2    | deletion
 his1::ura4          | SPAC25G10.05c:allele-3  | deletion
 his5::ura4          | SPBC21H7.07c:allele-3   | deletion
 orc1delta::ura4+    | SPBC29A10.15:allele-4   | deletion
 rec10-155::LEU2     | SPAC25G10.04c:allele-3  | deletion
 gad7-/gad7- diploid | SPBC29B5.01:allele-4    | deletion
 gad7::ura4          | SPBC29B5.01:allele-5    | deletion
 rad15delta::LEU2    | SPAC1D4.12:allele-5     | deletion
 dis2delta::ura4+    | SPBC776.02c:allele-8    | deletion
 rep1delta::ura4+    | SPBC2D10.06:allele-4    | deletion
 rep2delta::ura4+    | SPBC2F12.11c:allele-3   | deletion
 mcm5delta::his3+    | SPAC1B2.05:allele-4     | deletion
 mcm6delta::his3+    | SPBC211.04c:allele-19   | deletion
 mcm2delta::his3+    | SPBC4.04c:allele-7      | deletion
 mcm4delta::his3+    | SPCC16A11.17:allele-18  | deletion
 swi10::ura4+        | SPBC4F6.15c:allele-3    | deletion
 mcm3delta::his3+    | SPCC1682.02c:allele-3   | deletion
 cap1delta::ura4+    | SPCC306.09c:allele-12   | deletion
 pch1::his7          | SPBC32F12.06:allele-2   | deletion
 php2delta::ura4+    | SPBC725.11c:allele-3    | deletion
 mam1-A221           | SPBC25B2.02c:allele-4   | deletion
 bip1delta::ura4+    | SPAC22A12.15c:allele-2  | deletion
 pac1delta::ura4+    | SPBC119.11c:allele-15   | deletion
 orc4delta::ura4+    | SPBP23A10.13:allele-4   | deletion

**Comment by ValWood** [comment]
pmc1delta | med14

**Comment by ValWood** [comment]
To double check the contents, there are some known unfixed problem in the old list:
https://github.com/pombase/curation/issues/951

**Comment by kimrutherford** [comment]
Hopefully this is a better list.  I've included the session for those alleles that come from Canto.

       allele_name       | gene_name |  uniquename   |     session
    ---------------------+-----------+---------------+------------------
     pmc5delta           | med6      | SPAC1002.15c  |
     mrpl6delta          | mrpl1602  | SPAC12G12.08  |
     ptr6delta           | taf7      | SPAC13F5.02c  |
     sts1delta           | erg4      | SPAC20G4.07c  |
     hsp3106delta        | sdj1      | SPAC22E12.03c |
     mrpl11delta         | mrp11     | SPAC31A2.03   |
     mrps5delta          | mrp5      | SPAC4G9.17c   |
     mug82delta          | pth4      | SPAC589.11    |
     sep11delta          | med18     | SPAC5D6.05    |
     sod2delta           | nhe1      | SPAC977.10    |
     mrpl16delta         | mrpl1601  | SPBC1105.03c  |
     fub2delta           | uba2      | SPBC16H5.03c  |
     ran1delta           | pat1      | SPBC19C2.05   |
     pmc1delta           | med14     | SPBC1A4.10c   |
     pfd1delta           | gim6      | SPBC1D7.01    |
     mug80delta          | clg1      | SPBC1D7.03    |
     vps13adelta         | vps1301   | SPBC21C3.01c  |
     eic1delta           | mis19     | SPBC27B12.02  |
     mim1delta           | tom13     | SPBC713.08    |
     eic2delta           | mis20     | SPBC776.16    |
     alf1delta           | knk1      | SPBC947.01    |
     mug55delta          | fzr3      | SPCC1620.04c  |
     gcg1delta           | ggc1      | SPCC1682.09c  |
     mft1delta           | tho7      | SPCC24B10.11c |
     ral2                | ral2      | SPBC21.05c    |
     rad32delta          | mre11     | SPAC13C5.07   |
     scn1delta           | scn3      | SPAC688.13    | d51f6cb3611bc670
     pap1-delta          | pap1      | SPAC1783.07c  | 0370b9834de2dfe6
     972-tsc1delta       | tsc1      | SPAC22F3.13   | d616690bf410cea4
     972-tsc2delta       | tsc2      | SPAC630.13c   | d616690bf410cea4
     atg18delta          | atg1801   | SPAC589.07c   | 7e33223e7aa2a9d8
     mug179delta         | atg1802   | SPAC823.16c   | 7e33223e7aa2a9d8
     ppg1delta           | ppa3      | SPAC22H10.04  | feac1fe40f21f7a9
     mug66delta          | atg101    | SPAC25H1.03   | 577bf3d48e3ab2d6
     h90 sty1delta       | sty1      | SPAC24B11.06c | a505689e6c78deee
     rhp1delta           | rhp14     | SPBC649.03    | efa1583765ddce89
     cuf2                | cuf2      | SPCC584.02    | 2306fd737a53d0b4
     qtrtd1              | qtr2      | SPAC2F3.13c   | 466ed4e946c15c3f
     gad7-/gad7- diploid | atf1      | SPBC29B5.01   | 6ff4c9edff12167b
     dss1delta           | rpn15     | SPAC3G6.02    | bdc65ab8c484c62c
     abc1delta           | ybt1      | SPAC9E9.12c   | b00a5065fbeb471
     dil1delta           | dhc1      | SPAC1093.06c  | c7fac5251ee4f493
     san1-delta          | san1      | SPBC2A9.04c   | 0d6e46fca4be8cc5
     csi11delta          | csi1      | SPBC2G2.14    | 5c30b3bf5c5da95c
     matMidelta          | mat1-Mi   | SPBC23G7.17c  | 24e9f1d9ea02f952
     matPidelta          | mat2-Pi   | SPMTR.02      | 24e9f1d9ea02f952
     rad22delta          | rad52     | SPAC30D11.10  | 55c12e425ccc4499
     sks1-delta          | rpn11     | SPAC31G5.13   | 26d744db2d025a87
     ehs1delta           | yam8      | SPAC1F5.08c   | 373f4c6a1e37adf9
     mat1-mc-delta       | mat1-Mc   | SPBC23G7.09   | 66b209326b30f74b
     mam1-A221           | mam1      | SPBC25B2.02c  | 66b209326b30f74b
     mat1-Mmdelta        | mat1-Mi   | SPBC23G7.17c  | 5289777e56b6c6be
     matPcdelta          | mat2-Pc   | SPMTR.01      | 5289777e56b6c6be
     lrp1delta           | sog2      | SPBC887.09c   | 59ec05d8416a6e4d
(54 rows)

**Comment by ValWood** [comment]
Much better. We can work thorough these and fix any typos. Most look OK, they are just alternative names... we should record them if they exist (and can display them later)

**Comment by ValWood** [comment]
probably only need to fix

remove hyphen
pap1-delta          | pap1      | SPAC1783.07c  | 0370b9834de2dfe6
san1-delta          | san1      | SPBC2A9.04c   | 0d6e46fca4be8cc5

add 'delta'
cuf2                | cuf2      | SPCC584.02    | 2306fd737a53d0b4

add backgrounds or whatever required
972-tsc1delta       | tsc1      | SPAC22F3.13   | d616690bf410cea4
 972-tsc2delta       | tsc2      | SPAC630.13c   | d616690bf410cea4

we have a ticket about handling diploids? Do we have a plan?
gad7-/gad7- diploid | atf1      | SPBC29B5.01   | 6ff4c9edff12167b


The others probably do represent alternative allele names?

**Comment by mah11** [comment]
> we have a ticket about handling diploids? Do we have a plan?

https://github.com/pombase/canto/issues/976

**Comment by kimrutherford** [comment]
Note to self.  Here is the Chado query to get the list:

select '    ' || allele.name as allele_name, gene.name as gene_name, gene.uniquename, (select value from featureprop p where p.type_id in (select cvterm_id from cvterm where name = 'canto_session') and p.feature_id = allele.feature_id limit 1) as session from feature allele join feature_relationship r on r.subject_id = allele.feature_id join feature gene on r.object_id = gene.feature_id join cvterm gene_type on gene.type_id = gene_type.cvterm_id join featureprop p on allele.feature_id = p.feature_id join cvterm pt on pt.cvterm_id = p.type_id where pt.name = 'allele_type' and p.value = 'deletion' and allele.name <> gene.name || 'delta' and allele.name <> gene.uniquename || 'delta' and allele.name not like '%::%' and gene_type.name = 'gene';

**Comment by ValWood** [comment]
Closing, Kim you don't need to worry about  the allele stuff until we decide which  new allele types,  or other changes we require


lumped
https://github.com/pombase/pombase-chado/issues/205
