### ISSUE TITLE
Add a source_database property on orthologs

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#578]
We'll need to add a new command line argument to the ortholog loader.

This is needed so we can add manual PomBase orthologs to the annotation by type/year chart.  See: #570.

**Comment by ValWood** [comment]
OK, its more complicated so no hurry for this.

**Comment by kimrutherford** [comment]
> We'll need to add a new command line argument to the ortholog loader.

I've added a `--source-database` flag to the ortholog file loader and change the load script to pass `--source-database=PomBase` or `--source-database=Compara` where appropriate.

This stores a "source_database" `feature_relationshipprop` in Chado for the ortholog annotations.

I'll check Chado on Tuesday morning.
