### ISSUE TITLE
ECO code warning

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#580]
I just spotted this

cannot find the evidence code for "ECO:0000095" at /home/FILESERVER5/pombase/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 403.
cannot find the evidence code for "ECO:0000095" at /home/FILESERVER5/pombase/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 403.
cannot find the evidence code for "ECO:0000095" at /home/FILESERVER5/pombase/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 403.
cannot find the evidence code for "ECO:0000095" at /home/FILESERVER5/pombase/kmr44/git/pombase-chado/lib/PomBase/Retrieve/PhenotypeAnnotationFormat.pm line 403.
cannot find the evidence code for "ECO:0000095" at /home/FILESERVER5/pombas

etc

https://curation.pombase.org/dumps/latest_build/logs/log.2016-09-15-10-11-52.export_warnings

**Comment by ValWood** [comment]
@kimrutherford  is this still an issue

**Comment by ValWood** [comment]
I'll presume its fixed, if not we can open new

**Comment by kimrutherford** [comment]
It's still there.  I'll put this on high priority because it means some annotation is not loading.

**Comment by ValWood** [comment]
OK right!

**Comment by kimrutherford** [comment]
I've added the new evidence code to the config file: load-pombase-chado.yaml

Should be fixed in tomorrow's load.

https://github.com/pombase/pombase-legacy/commit/89c727bfcd920546af4f486447f1b93a9cb0e2d1#diff-155f41c6c501a8c7c7def8123902f2ce
