### ISSUE TITLE
pombe_mini_PR.obo change

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#582]
The Protein Ontology is (utterly unsurprisingly) getting too big for the hacky method I'd been using for updating our pombe_mini_PR.obo file (onto-jargon-rich gory details available upon request).

So when I updated mini-PRO today (on a tangent from https://github.com/pombase/website/issues/67), I did a simpler filter that doesn't try to grab the hierarchy of non-pombe-specific terms; instead, anything that needed a parent gets 'is_a: PR:000000001 ! protein', much like all the mini-CHEBI entries.

If that causes any problems, (a) holler and (b) go ahead and revert to the previous mini-PRO file in svn. If everything quietly works just fine, close this.

**Comment by ValWood** [comment]
I'll leave this to you ;) Its off my radar....

**Comment by kimrutherford** [comment]
Yesterday's load worked fine so I think this in OK.

**Comment by mah11** [comment]
Whew! thanks :)
