### ISSUE TITLE
Issue a log warning for any annotation without a date

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#584]
Follow on from
https://github.com/pombase/pombase-chado/issues/583

Would be useful as we could see at a glance if anything is missing from the stats.

**Comment by kimrutherford** [comment]
> Would be useful as we could see at a glance if anything is missing from the stats.

How would that work?

**Comment by ValWood** [comment]
Maybe I misunderstood. I'm assuming that anything without a date isn't counted....

What happens to all the stuff which used to have the 1970 unix start date?

**Comment by kimrutherford** [comment]
> Maybe I misunderstood. I'm assuming that anything without a date isn't counted....

That's true but some annotation doesn't have a date in the source data files.  In the #583 case it was a loading problem.  It's hard to write a general check for missing dates that would have caught that if some annotation never had a date to start with.  We'd get a lot of false positives if we had a check that reported annotation without a date.

> What happens to all the stuff which used to have the 1970 unix start date?

No date is stored in Chado for those so they don't show up in the per-year stats tables.

**Comment by ValWood** [comment]
It's OK, it isn't so many,
 val$ grep "date=1970" *.contig | wc
    7356 

and *most* seem to be pombe/cerevisiae orthologs, and some manually curated domains which the protein family  databases miseed which makes sense. That must have been one of the first things I  did as at that point most of the annotation came from orthology but was n't stored in Artemis.

So we can ignore these.

I think we are slowly chipping away at the phenotypes which are still in Artemis...at some point we will need a list of the "dateless" ones of these....

**Comment by ValWood** [comment]
We probably won't do this. But Kim will elt us know how many for different ontologies, juxt so we know...
