### ISSUE TITLE
manual fixes for GO taxon restricted annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#589]
- [ ]  80b382d361649949 - GO:0000918
replace with
GO:1903486 establishment of mitotic actomyosin contractile ring localization
This seems to fit because 
a) in fission yeast the position of the barrier septum is determined by the position of the actinomyosin ring
b) phenotype FYPO:0002026 actomyosin contractile ring displaced from midpoint

please double check that the GP is pxl1 ( I can't see the annotation)

- [ ] 9e6658619f3b13c3 GO:0035082 axenome assembly. I have no idee why I have done this, its a mistake, so just delete it....

- [ ]  c57f22a897472fa7 - GO:0009008 NOT
delete, not required

**Comment by kimrutherford** [comment]
You should be able to do these changes yourself now that pombase/canto#1268 is done.

**Comment by ValWood** [comment]
yep I fixed them when I woke in the middle of the night!
