### ISSUE TITLE
Troubleshooting ommissions in esyN graphs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#593]
https://github.com/pombase/curation/issues/960

I'm trying to figure out why the esyN networks  do not seem to be updating correctly.

The first example problem I looked at, and I can't see the data in the  file that Dan uses:

On the gene pages
SPAC1782.09c (clp1) has_substrate SPAC24H6.05 (cdc25)
This is present on www and dev.

Can you see if you can figure out why it doesn't get into the esyN file?

http://curation.pombase.org/dumps/releases/pombase-chado-latest/exports/pombase-go-substrates.tsv.gz

**Comment by kimrutherford** [comment]
I'm confused.  That file has:

    SPAC1782.09c    SPAC24H6.05     PMID:15128870

What am I missing?

**Comment by ValWood** [comment]
Sorry! missed that!
