### ISSUE TITLE
pombase-go-physical-interactions.tsv.gz

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#596]
The
pombase-go-physical-interactions.tsv.gz file here
https://curation.pombase.org/dumps/latest_build/exports/
is empty....

(I have a feeling this happened very recently, because  esyN is currently displaying these interactions)

**Comment by kimrutherford** [comment]
Thanks for spotting that.  It looks like it happened in the last day or two.  I've copied the most recent good version of the file to the latest_build/exports/ directory so esyN will update OK while I fix things.

**Comment by kimrutherford** [comment]
It looks like owltools was failing and it caused a bunch of problem.  I ran the load manually and it's fine.  I think I've fixed the load script.  I see how it goes over night.

**Comment by kimrutherford** [comment]
It's working now.
