### ISSUE TITLE
Cope with loading Canto annotation with alt_id and extension

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#597]
The Canto JSON loader is failing in the case with an alt_id is used in an annotation and that annotation has an extension.  The bug is that the is_a relationship between the base term (eg. "decreased intergenic meiotic recombination") and the term+extension (eg. "decreased intergenic meiotic recombination [has_expressivity] medium") doesn't get stored.

These terms without the is_a cause the GAF exporter to fail (see #595).

**Comment by ValWood** [comment]
Is this still current (I don't fully understand the issue)

**Comment by kimrutherford** [comment]
As far as I know the bug is still there.

**Comment by ValWood** [comment]
Is this still current? Are e losing these annotations (I don't really understand so maybe we should discuss)

**Comment by kimrutherford** [comment]
> Is this still current? Are e losing these annotations 

Sorry, I didn't make a good note of what goes wrong in this case.   #595 isn't very helpful.

I'll check and make sure we at least get a loud log message if this problem is noticed by the loading code.

**Comment by kimrutherford** [comment]
I can't reproduce this now so I'm going to close the issue until it happens again.
