### ISSUE TITLE
Gene name and  description from authoritative source for non-pombe genes (SGD and HGNC)

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#598]
We need to add a description or product for cerevisiae and human genes.  We can get that from Ensembl.

**Comment by mah11** [comment]
Ensembl is not the authoritative source for cerevisiae gene info; SGD is. The last column of this file looks applicable:

http://downloads.yeastgenome.org/curation/chromosomal_feature/SGD_features.tab

**Comment by kimrutherford** [comment]
Ah, good point and thanks for the link.

We currently get the cerevisiae genes from Ensembl because it was easier to get cerevisiae and human from the same source.

I'll change the loader to use the SGD file.  I'll do it soon so any loading problems can be fixed before well before the next release.

**Comment by ValWood** [comment]
Yes Ensembl  import SGD  descriptions so it is  often out of date.
We could live with it during the early stages of development, but at some point it should definitely come from SGD.

**Comment by kimrutherford** [comment]
>I'll change the loader to use the SGD file. I'll do it soon so any loading problems can be fixed
> before well before the next release.

I haven't done that yet.  :-)

This looks like a good place to get the HGNC data from:
  ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt

Here are the first three columns for some random genes.  Is column 3 ("name") what you'd like for the "gene description"?:

    hgnc_id     symbol      name
    HGNC:26388  ARHGAP36    Rho GTPase activating protein 36
    HGNC:11393  AURKA       aurora kinase A
    HGNC:948    BAIAP3      BAI1 associated protein 3
    HGNC:1059   BLMH        bleomycin hydrolase
    HGNC:1474   CAPG        capping actin protein, gelsolin like
    HGNC:26900  CCDC96      coiled-coil domain containing 96
    HGNC:27023  COL6A6      collagen type VI alpha 6 chain
    HGNC:30359  CSDC2       cold shock domain containing C2
    HGNC:25628  DDX19A      DEAD-box helicase 19A
    HGNC:2854   DGKH        diacylglycerol kinase eta
    HGNC:32173  DPRXP7      divergent-paired related homeobox pseudogene 7
    HGNC:38160  ELOCP24     elongin C pseudogene 24
    HGNC:3663   FGD1        FYVE, RhoGEF and PH domain containing 1
    HGNC:43013  HIGD1AP18   HIG1 hypoxia inducible domain family member 1A pseudogene 18
    HGNC:44422  HMGN2P47    high mobility group nucleosomal binding domain 2 pseudogene 47
    HGNC:12028  HSP90B1     heat shock protein 90 beta family member 1
    HGNC:5992   IL1B        interleukin 1 beta

**Comment by ValWood** [comment]
>column 3 ("name") 
perfect

**Comment by kimrutherford** [comment]
Note to self: use the "HGNC:20498" IDs as the uniquename in Chado and store the symbols in the name column.

**Comment by kimrutherford** [comment]
The cerevisiae genes seem to have two systematic IDs.  eg.
    YAL067C
    S000000062

I've always found that mysterious.  We currently only store the YAL... ones in the feature table in Chado.

In the contig files we use both styles of ID in different places.  :-/

We use "with=SGD:S000004535" but also
/controlled_curation="term=orthologous to S. cerevisiae YAL049C; ..."

Are the S000... IDs what GO expects?

**Comment by kimrutherford** [comment]
> Note to self: use the "HGNC:20498" IDs as the uniquename in Chado and store the symbols in the
> name column.

Reply to self: that's great but what about the Ensembl IDs?

Currently we use the Ensembl "ENSG000..." IDs as the uniquename / systematic ID for human genes stored in the Chado feature table.  That works well because the pombe-human orthologs use the Ensembl IDs.

If we use HGNC IDs in Chado instead of Ensembl IDs we won't be able to load the orthologs.

I'm not sure what the best plan is.

**Comment by kimrutherford** [comment]
> http://downloads.yeastgenome.org/curation/chromosomal_feature/SGD_features.tab

Note to self, the columns are documented here:
  https://downloads.yeastgenome.org/curation/chromosomal_feature/SGD_features.README

**Comment by ValWood** [comment]
SGD:S00000 is the official database ID . GO expects this.

I always used YGL etc (the orf label), because it is more user friendly.
We want to display this in the  ortholog section.

It might seem  confusing, but most of the community who are familiar with S. cerevisiae understand the difference. In fact  we are the only people who really use the same label for both.

**Comment by ValWood** [comment]
Also... We don't really need to make any connection between the ortholog list and what is in the  GO with field for an ISS/ISO annotation.
Although 99% of the time it will be an ortholog in the "with" field,  for ISS if it is for a higher level annotation it might *not* be the ortholog, it could just be another family member but we are making an annotation general enough to use it....

**Comment by ValWood** [comment]
Re human names. I don't think we  need to use the Ensmbl IDs at all. We always convert them t HGNC IDs somewhere....


and in the contigs, and these files:
conserved_one_to_one.txt
conserved_multi.txt

I used HGNC  human friendly unique names

**Comment by ValWood** [comment]
We don't need to display Ensembl IDs in the ortholog section. 
The HGNC are the best source of names/IDs

**Comment by kimrutherford** [comment]
> Re human names. I don't think we need to use the Ensmbl IDs at all. We always convert them t HGNC IDs somewhere....

This file has Ensembl IDs: pombe-embl/orthologs/compara_orths.tsv

Currently that works fine because the Ensembl ID is the uniquename / systematic ID in the feature table in Chado.  Can we change those IDs to HGNC IDs?  I'm happy to do that.

**Comment by ValWood** [comment]
yes. we can change.

**Comment by kimrutherford** [comment]
> yes. we can change.

Great.  I've downloaded a Ensembl ID to NGHC ID mapping table from Biomart.  I'll change compara_orths.tsv but I won't check it in until the other changes are ready.

**Comment by kimrutherford** [comment]
> I'll change compara_orths.tsv but I won't check it in until the other changes are ready

I ended up using the data file (hgnc_complete_set.txt above) from HGNC because I trusted it more.

It's a small file so I added it to SVN as: pombe-embl/orthologs/compara_orths_hgnc_ids.tsv 

When we switch to HGNC IDs in Chado I'll rename it to compara_orths,tsv

There are three Ensembl genes in the ortholog file that don't have HGNC IDs.  Very annoying.  I'd rather not get all the human IDs from HGNC except for three.  Can you think of a work around?

Here are the three:

ENSG00000249209 - http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000249209;r=21:33584687-33931607;t=ENST00000429238

ENSG00000204790 - http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000204790;r=9:63974762-64004155;t=ENST00000485382

ENSG00000180574 - http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000180574;r=12:10505602-10523135

**Comment by ValWood** [comment]
fixing now......

**Comment by kimrutherford** [comment]
The code is now done for this.  I've had to change the way non-pombe genes are loaded so the genes can be read from a file.  Because of the changes needed, I'm a little worried about the load.  So I'm doing some local testing and I'll start the nightly load a bit later than normal tonight.

**Comment by kimrutherford** [comment]
> Because of the changes needed, I'm a little worried about the load.

The code seems fine but I forgot to put the updated compara_orths.tsv in place.  It now has HGNC IDs so should be OK for tonight's load.

**Comment by kimrutherford** [comment]
The load worked, mostly.  The Compara orthologs file now loads without warnings.

But there are now a bunch of missing snoRNA and ncRNA orthologs:
  https://curation.pombase.org/dumps/builds/pombase-build-2017-11-29/logs/ortholog_problems.txt

It looks like the problem is that I configured things so that only protein coding genes get loaded.  I've fixed the configuration for tomorrow's load.

**Comment by ValWood** [comment]
OK I fixed the issues with proteins. This is because we were using the names  (which change) rather than Ids which dont. I quite liked it because it alerted me to a name change which often menas "characterization", but it was a pain and  I will pick them up in other ways.

I was confused why it thinks that
mRNA SPBC1289.10c.1: ortholog (YER109C) not found
mRNA SPCC1494.10.1: ortholog (YER109C) not found

is not a valid name?

**Comment by kimrutherford** [comment]
> I was confused why it thinks that
> mRNA SPBC1289.10c.1: ortholog (YER109C) not found
> mRNA SPCC1494.10.1: ortholog (YER109C) not found
> is not a valid name?

That gene isn't being loaded because it has type "blocked_reading_frame" instead of "ORF" in the data file.  It's like that on the gene page too:
  https://www.yeastgenome.org/locus/S000000911

We are only loading rows from the data table that have "ORF" in the second column:
http://downloads.yeastgenome.org/curation/chromosomal_feature/SGD_features.tab

I can easily get it to load "ORF" and "blocked_reading_frame" rows if that makes sense.

A "blocked_reading_frame" is one the is "interrupted by one or more stop codons":
  http://www.sequenceontology.org/miso/release_2.4/term/SO:0000718

I don't understand how the makes sense for a coding gene?

**Comment by ValWood** [comment]
Yes I think we should include these. The problem is they are frame-shifted in the sequenced strain, but probably real in many very closely related strains, so it is good to represent them in the reference strain.
At PomBase we handle them slightly differently, we negociate the frameshift to give a valid translation.....

**Comment by kimrutherford** [comment]
OK, I've added blocked_reading_frame features too.  It's not in time for tonight's load but it will be in tomorrow night's load.

**Comment by kimrutherford** [comment]
> mRNA SPBC1289.10c.1: ortholog (YER109C) not found
> mRNA SPCC1494.10.1: ortholog (YER109C) not found

YER109C is now loaded correctly so those two orthologs are visible again in the main site.

There still some other ortholog warnings.  Are these because of missing genes?:
https://curation.pombase.org/dumps/builds/pombase-build-2017-12-05/logs/log.2017-12-05-21-10-56.manual-1-1-orths-output
https://curation.pombase.org/dumps/builds/pombase-build-2017-12-05/logs/log.2017-12-05-21-10-56.manual-multi-orths-output

**Comment by ValWood** [comment]
fixed all the orthologs (recent name changes in human)

**Comment by kimrutherford** [comment]
> fixed all the orthologs (recent name changes in human)

Thanks.  The logs should look very good in the morning.
