### ISSUE TITLE
A query BioGRID types

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#599]
BIOGRID are changing the way that genetic interactions are described 

I'm trying to make a plan (no hurry to implement, might take 2 years, but there might be small changes  we could make to curation procedures now, to makes the eventual  transition easier).

 I will address the existing "types" one by one on the curation tracker first and curators can make a plan.

So for now I have a question. Could you let me know how many annotations we have to each 
GI term (synthetic lethal etc)
(Is there anywhere I can look this up? I think there might be but I can't remember where it is)

**Comment by ValWood** [comment]
first part of this, getting the numbers, I put at high priority so we can see what we have

**Comment by kimrutherford** [comment]
It's easy to query Chado to get all the legacy interactions, but harder to query the genotype-genotype interactions.

Are these the numbers you were after?:

Old style genetic interactions:

|interaction\_type   |evidence            |count             |
|--------------------|--------------------|------------------|
|interacts\_genetically|Dosage Growth Defect|98                |
|interacts\_genetically|Dosage Lethality    |94                |
|interacts\_genetically|Dosage Rescue       |1164              |
|interacts\_genetically|Negative Genetic    |67112             |
|interacts\_genetically|Phenotypic Enhancement|1586              |
|interacts\_genetically|Phenotypic Suppression|1890              |
|interacts\_genetically|Positive Genetic    |29482             |
|interacts\_genetically|Synthetic Growth Defect|5422              |
|interacts\_genetically|Synthetic Lethality |3241              |
|interacts\_genetically|Synthetic Rescue    |1612              |

Physical interactions:

|interaction\_type   |evidence            |count             |
|--------------------|--------------------|------------------|
|interacts\_physically|Affinity Capture\-Luminescence|3                 |
|interacts\_physically|Affinity Capture\-MS|8618              |
|interacts\_physically|Affinity Capture\-RNA|456               |
|interacts\_physically|Affinity Capture\-Western|2637              |
|interacts\_physically|Biochemical Activity|586               |
|interacts\_physically|Co\-crystal Structure|190               |
|interacts\_physically|Co\-fractionation   |143               |
|interacts\_physically|Co\-localization    |35                |
|interacts\_physically|Co\-purification    |880               |
|interacts\_physically|FRET                |9                 |
|interacts\_physically|Far Western         |35                |
|interacts\_physically|PCA                 |1401              |
|interacts\_physically|Protein\-RNA        |23                |
|interacts\_physically|Protein\-peptide    |84                |
|interacts\_physically|Proximity Label\-MS |303               |
|interacts\_physically|Reconstituted Complex|1559              |
|interacts\_physically|Two\-hybrid         |3762              |


Note to self:
```sql
select p.value as evidence, rel_t.name as interaction_type, count(rel.feature_relationship_id)  from feature_relationship rel join feature_relationshipprop p on rel.feature_relationship_id = p.feature_relationship_id join cvterm pt on pt.cvterm_id = p.type_id join cvterm rel_t on rel.type_id = rel_t.cvterm_id where rel_t.name like '%interact%' and pt.name = 'evidence' group by p.value, rel_t.name order by rel_t.name, p.value;
```

**Comment by ValWood** [comment]
OK, thanks. I wondered if we used them all consistently thats all, it seems all are fairly well used.
I'm going to close this ticket, until prompted by BIOGRID, because I can't remember what the pending changes were, maybe they never happened?
