### ISSUE TITLE
IEA's missing from current gaf...

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#601]
grep IEA pombase-build-2016-12-12-v1.gaf |wc
       6     
(TFIIEA)

**Comment by kimrutherford** [comment]
I think I've fixed this.  Unfortunately the GOA GAF load has been failing since I changed to doing a nightly load.  Should be fixed in tonight's load.

**Comment by kimrutherford** [comment]
> GOA GAF load has been failing

It was completely failing so no GOA annotation has been in PomBase v2.

**Comment by ValWood** [comment]
not back yet:
 250 EXP
1699 IC
13493 IDA
  54 IEP
   1 IGC
 840 IGI
   1 IKR
5753 IMP
1795 IPI
1398 ISM
6632 ISO
1668 ISS
1216 NAS
2947 ND
   4 RCA
 427 TAS

**Comment by ValWood** [comment]
Midori did you re-annote the RCA?  that dropped a lot?

**Comment by ValWood** [comment]
Actually its been  that low for ages
May_2013 Oct2014	Dec2014	Jan2015	Feb15  Mar15  June 16
RCA 510		482		504		505		-        505   4

I must have forgotten......

**Comment by kimrutherford** [comment]
> not back yet:

I've only made the fixed today so it won't change until tonight's load.

**Comment by kimrutherford** [comment]
The load was failing for a few days but it worked last night.  The are now 4180 IEAs in the PomBase GAF file.

**Comment by ValWood** [comment]
yep, that looks spot on.
