### ISSUE TITLE
need to update SO?

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#604]
The last few Chado logs suggest that SO hasn't been updated quite recently enough. Some SO IDs can't be found despite existing in, well, SO.

From embl file qualifier_problems.txt:

    mRNA SPAC343.09.1: can't find 'SO:0002159' in sequence: failed to load qualifier 'term=sequence feature, SHP box; date=20161217' from SPAC343.09.1
    mRNA SPBC365.08c.1: can't find 'SO:0002159' in sequence: failed to load qualifier 'term=sequence feature, SHP box; date=20161217' from SPBC365.08c.1
    mRNA SPCC790.03.1: can't find 'SO:0002159' in sequence: failed to load qualifier 'term=sequence feature, SHP box; db_xref=PMID:27655872; date=20161217' from SPCC790.03.1

And from the Canto load log (today's is log.2017-01-03-22-35-36.curation-tool-data-load-output):

    warning in d505f490197e7842: can't find term with ID: SO:0002141
    warning in d505f490197e7842: can't find term with ID: SO:0002140
    warning in 9cf15ade89e44016: can't find term with ID: SO:0002156

They're all relatively new but available in the current SO files.

**Comment by kimrutherford** [comment]
SO moved to GitHub but I forgot to update the load script.  It's done now so hopefully this will be fixed in tonight's load.

**Comment by kimrutherford** [comment]
Those warnings are gone in the most recent load.
