### ISSUE TITLE
update human names file?

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#606]
there are a few human ortholog names reported in the logs, which appear to be current:

NCBP3
GON7
WAPL

Also current in ensembl if we still get them from there...

Ideally for next build (will use for V62)

**Comment by kimrutherford** [comment]
> Also current in ensembl if we still get them from there...

Yep, we get them from Ensembl.  I need to manually update to point to their latest version and I don't think I've done that for a while.  I'll update and see if that fixes it.

**Comment by kimrutherford** [comment]
I've updated the Ensembl database versions in time for tonight's load.

**Comment by ValWood** [comment]
great, will check tomorrow !

**Comment by kimrutherford** [comment]
Are the human IDs OK?

**Comment by ValWood** [comment]
Yes, the update  got rid of the old errors and  threw up a lot of new ones which I fixed yesterday, so all should be fine for the update.
