### ISSUE TITLE
GAF output changes commas to pipes (it shouldn't)

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#607]
Hmm, do I need to say more? The embl contig files have some GO annotations with multiple comma-separated entries in the with/from field. When the GAF is generated, they're getting changed to pipes. That shouldn't happen, because commas and pipes don't mean the same thing, and we intend the comma meaning (AND, i.e. the annotation needs all of them at once, as opposed to OR, which we're doing by making separate annotations).

Background in #483 and #504; current knock-on effect in https://github.com/pombase/website/issues/152; tangentially related Canto request in https://github.com/pombase/canto/issues/1094

**Comment by kimrutherford** [comment]
I've fixed this.  The change will be visible in the next nightly load.
