### ISSUE TITLE
 Add DOI to publications

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#610]
Add a post-process to retrieve the DOI (from PubMed maybe?) for each publication and store as a property.

Needed for pombase/website#164

**Comment by ValWood** [comment]
We will also require a way to add publications manually that have a DOI, but not yet a PubMed if we  have any takers to pilot pre-review curation....

**Comment by ValWood** [comment]
Removed the discuss label as there does not seem to be anything to discuss here. Add back if I'm wrong...

**Comment by kimrutherford** [comment]
>Add a post-process to retrieve the DOI (from PubMed maybe?) for each publication and store as a property.

I have finally got around to having a look at this.  The DOI is available in the PubMed XML so adding it during loading should be straightforward.

eg.

```xml
 <ArticleIdList>
     <ArticleId IdType="pubmed">27984725</ArticleId>
     <ArticleId IdType="pii">S0092-8674(16)31606-3</ArticleId>
     <ArticleId IdType="doi">10.1016/j.cell.2016.11.034</ArticleId>
     <ArticleId IdType="pmc">PMC5161751</ArticleId>
 </ArticleIdList>
```

There is also discussion about DOIs in this issue: https://github.com/pombase/canto/issues/1366

**Comment by ValWood** [comment]
Should do this if it is quick, since https://github.com/pombase/website/issues/164
depends on it...

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/1433

**Comment by kimrutherford** [comment]
I've added the code to get the DOIs into Chado.  I'm testing it locally now and I'll check the main load in the morning.

**Comment by kimrutherford** [comment]
> I've added the code to get the DOIs into Chado. I'm testing it locally now and I'll check the main
> load in the morning.

All good.
