### ISSUE TITLE
normalize genotype descriptions (incl. order of allele names)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#611]
![avoid](https://cloud.githubusercontent.com/assets/7359272/23132403/5f2e120a-f785-11e6-9505-e8bc08f2689c.jpg)

when naming "multi gene " alleles I think we need a system which organizes so that the
contributing alleles are treated alphabetically in the genotype, maybe?

(we need a way to ensure that we don't have duplicate alleles to describe the same genotype, like this, Oddly I thought we already did something like this but it seems not?)

**Comment by mah11** [comment]
so it's genotype descriptions that you want made consistent, right? (in the example the allele names are already the same)

**Comment by ValWood** [comment]
I mean the genotype
cdc25-22(C532Y) mcs2-75(unknown) cdc2-3w(C67Y)
vs 
mcs2-75(unknown) cdc2-3w(C67Y) cdc25-22(C532Y)

which spawss 2 genotype pages:
need to both be

cdc2-3w(C67Y) cdc25-22(C532Y) mcs2-75(unknown)

**Comment by mah11** [comment]
thought so. I'll correct the ticket title.

**Comment by ValWood** [comment]
Oh yes! sorry,

**Comment by kimrutherford** [comment]
I think this is the same bug as #497 ("Don't create duplicated genotype on Chado load").
