### ISSUE TITLE
change colour on curation graph

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#615]
At some point we discussed changing tis so that

The  admin curated papers are a "solid colour" , the "uncurated can be grey...this looks more like "negative space".

![colour](https://cloud.githubusercontent.com/assets/7359272/23333509/9c859706-fb84-11e6-807e-7d3148402c8b.jpg)

Whatever the colour change (it could just be a switch) all curated should be together
(maybe the grey uncurated would be better at the  top of the bars?)

no hurry until needed next...

**Comment by kimrutherford** [comment]
I've changed the colours and put the uncurated bars on top.  Let me know if you think that's an improvement.

**Comment by ValWood** [comment]
I think it's much better having both types of curated together.

I would  *marginally* prefer the "uncurated" papers to be   a colour like "pale grey"   so that visually they are "not there" if that makes sense....
What do you think?

**Comment by Antonialock** [comment]
yeah, for ordering I think we should have it like it is now (admin at bottom, community in middle and uncurated at top)

for colour I think a visually "sturdy/visible" colour for admin curated, a "visible" colour for community curated, and a lighter colour for uncurated

**Comment by ValWood** [comment]
God aren't we fussy ;)

the colour police ;)

**Comment by kimrutherford** [comment]
> for colour I think a visually "sturdy/visible" colour for admin curated, a "visible" colour for community
> curated, and a lighter colour for uncurated

I'll give that a go.

**Comment by kimrutherford** [comment]
Here's how it looks now.  I think with should probably do future changes on a call.

![community_curation_2](https://user-images.githubusercontent.com/90474/37691126-7accb000-2d14-11e8-97b1-89eb92310bd7.png)

**Comment by ValWood** [comment]
perfect!
