### ISSUE TITLE
 stats page graph title update

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#616]
I have had to explain to  numerous people that these graphs refer only to LOW THROUGHPUT data

![low throughput](https://cloud.githubusercontent.com/assets/7359272/23704186/930c7332-03fb-11e7-856f-cc0079a4de94.jpg)

this information is included in the explanation, but I think it needs to be in the graph title so people really get it.
Suggest

Annotations/ genes for low throughput publications in 5 year intervals...

(I discovered yesterday that Antonia also thought this was ALL data)

We do need a graph for "all data" though for comparison.
This will shop over 100 annotations per  gene.
In case it isn't clear, we want both graphs because the "low throughput" graph shows how much the curatorial burden has increased. The high throughput papers we can manage  much more quickly...

**Comment by ValWood** [comment]
@mah11  or better title suggestions.

Also the  title for the new graph when added

Annotations/ genes for  all publications in 5 year intervals...

**Comment by kimrutherford** [comment]
> Annotations/ genes for low throughput publications in 5 year intervals

I made that change because it was quick.  Easy to change it again.

It's here if you'd like to make changes:
  https://github.com/pombase/canto/blob/master/root/stats/annotation.mhtml#L335

**Comment by ValWood** [comment]
done

**Comment by ValWood** [comment]
I don't know why I typed done. I didn't do anything, just closed the ticket.
