### ISSUE TITLE
report  aa and nt alleles which exclude gene name

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#617]
Historically, some of us (probably just me), omitted to add the gene name to alleles if they were not names.

 so I may have put C67Y or even no name for the name.
Have been fixing but we need  a log report for any 
amino acid mutation or nucleotide mutation where the name is
a) identical to the description e.g. C67Y
b) noname

**Comment by ValWood** [comment]
We discussed this briefly today and we fix them when we see them.

It would be useful if  we could get a list of standard  allele descriptions like  C67Y which exclude the gene name. 
We can then  decide if we can automate fixing (if there are too many).

**Comment by ValWood** [comment]
Didn't we do this for pombemine?

**Comment by ValWood** [comment]
I can't see this, essentially we need a list of all alleles that are not preceeded by the gene name.

**Comment by kimrutherford** [comment]
Should we make a new log file for this?

**Comment by ValWood** [comment]
Yes please. I think we said we would  but I put it off because there would be some huge new logs. Maybe that was something else?
Anyway we can go ahead and add these to the logs.

**Comment by ValWood** [comment]
...actually didn't we discuss  automagically adding these? I know we discussed something? Maybe it is in another ticket...

**Comment by kimrutherford** [comment]
> I think we said we would but I put it off because there would be some huge new logs.

That was this one: https://github.com/pombase/pombase-chado/issues/883#issuecomment-973050904

> ...actually didn't we discuss automagically adding these? I know we discussed something? Maybe it is in another ticket...

I forgot about that.  It's here: https://github.com/pombase/pombase-chado/issues/868
But it only fixes the case where the name and description are the same and they look like a mutation ("A123K" etc.).

There are lots of other allele names that don't have the gene name as a prefix.
Here is a tab delimited file of them:  [alleles_without_gene_name.tsv.txt](https://github.com/pombase/pombase-chado/files/7826207/alleles_without_gene_name.tsv.txt)

I've added a new query and log file for allele names not starting with gene names.  I didn't commit it early enough so it won't be in the logs directory until Saturday.  Look for a file ending with: `.chado_checks.allele_names_not_starting_with_gene_name`

**Comment by ValWood** [comment]
Thanks.
It's not so bad, mostly typo's and non standard syntax, but they look like quick fixes mostly.

**Comment by kimrutherford** [comment]
Is there anything more for me to do on this?

**Comment by ValWood** [comment]
no, this log is good, I'm chipping away (lot's of typos in here, great check!)
