### ISSUE TITLE
Cant overwrite case of old allele name

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#619]
A whicle ago I fixed  Cdc2-F15(T15F)
to
cdc2-F15(T15F)

It is cdc2-F15(T15F) in canto, but Cdc2-F15(T15F) on gene page
https://curation.pombase.org/pombe/curs/3e2f643b12155f98/ro/

**Comment by mah11** [comment]
Two other papers use that allele, with the uncorrected case.

PMID:1703321 https://curation.pombase.org/pombe/curs/50a71e0348432087/genotype_manage/ro
PMID:9398669 https://curation.pombase.org/pombe/curs/9ef4b740616f8870/genotype_manage/ro

**Comment by kimrutherford** [comment]
Case is significant currently when deciding if alleles are equal.  So in Chado, cdc2-F15 is different to Cdc2-F15

**Comment by ValWood** [comment]
yep, need to fix in the other sessions....

**Comment by ValWood** [comment]
fixed the others
