### ISSUE TITLE
Annotations not updating

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#621]
I fixed this 
https://curation.pombase.org/pombe/view/object/cvterm/94103?model=chado

and others in this list:
https://curation.pombase.org/pombe/view/object/cv/43?model=chado

late last week, but they still  appear here?

**Comment by ValWood** [comment]
oddly, its correct on the gene page????
http://pombase2.aska.gen.nz/gene/SPCC1919.08c

**Comment by kimrutherford** [comment]
Sorry, Canto still doesn't point to the nightly Chado automatically so it was a few days old.  I've updated it now.  Does that fix things?

> oddly, its correct on the gene page????

That's always the latest Chado.

**Comment by ValWood** [comment]
I'm not sure because the links are to different things now.
How do I get to the list of CV's

**Comment by kimrutherford** [comment]
> How do I get to the list of CV's

It's the CVs link here:
  https://curation.pombase.org/pombe/track

**Comment by ValWood** [comment]
hmm, that's not the link/list I was thinking of.

before you updated, this link
https://curation.pombase.org/pombe/view/object/cv/43?model=chado
provided a list of types of cv terms (pombe specific ones)?

**Comment by ValWood** [comment]
got it
https://curation.pombase.org/pombe/view/list/cv?model=chado

all good
