### ISSUE TITLE
Do a nightly release when the chado checks pass

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#622]
We should update Canto and the nightly version of pombase v2 if the checks reported in the chado checks log file all pass. We don't have that many checks at the moment and perhaps should add more.  But even with the current checks if something serious goes wrong (like the Canto annotations fail to load), the checks usually catch it.

First step is to make a link in the dumps directory that points to the most recent nightly load where the checks pass.  Call it something like "nightly_update" for now.

See also: pombase/canto#1315

**Comment by kimrutherford** [comment]
> First step is to make a link in the dumps directory that points to the most recent nightly load where
> the checks pass. Call it something like "nightly_update" for now.

I've made that change.

**Comment by ValWood** [comment]
done?

**Comment by kimrutherford** [comment]
> done?

This still needs work.  At the moment the "nightly version of pombase v2" is pombase-dev and it currently gets updated even if the Chado check fail.

I update the main website a bit manually each day.  It takes about a minute.  I need to automate that more.

**Comment by kimrutherford** [comment]
> I update the main website a bit manually each day. It takes about a minute. I need to automate that more.

It's now almost completely automatic.  The nightly load does almost everything except for the final switch from last night's version to the current day's version.  The very last step is very quick but still manual.  The last step is running this command on the server: `sudo service httpd reload`

For now I'm going to continue to run that last command manually because it allow me to have a check of pombase-dev first if I'm worried about particular changes.  That `reload` command can be added to the nightly load whenever we're ready.

https://github.com/pombase/pombase-legacy/commit/acb2409eddd01462b8f7661639c8150e167a5f95

**Comment by ValWood** [comment]
Its quite nice to have the manual step, and we don't need to update *every* single day ;)
