### ISSUE TITLE
Merge identical genotypes when loading

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#624]
Currently every genotype referenced from every annotation is stored as a separate feature.  We should only store each unique genotype once.

This is related to: #577

**Comment by kimrutherford** [comment]
I've had a first go at this.   There is a good chance I've broken something because I had to change quite a lot of the loading code.  I'll check the load results on Tuesday Monday to see how it looks.

**Comment by ValWood** [comment]
example for single
http://pombase2.aska.gen.nz/genotype/PomBase-genotype-18000
http://pombase2.aska.gen.nz/genotype/59258724594b2b0c-genotype-2

example for multi
http://pombase2.aska.gen.nz/genotype/69acd91fe4ac8649-genotype-1
http://pombase2.aska.gen.nz/genotype/ea7f33ab6887fe6d-genotype-21

**Comment by ValWood** [comment]
Meant to say "not sure this worked"

**Comment by kimrutherford** [comment]
Sorry, I meant Wednesday morning.  The new code hasn't run yet.

**Comment by kimrutherford** [comment]
> Sorry, I meant Wednesday morning. The new code hasn't run yet.

There was a glitch that needed fixing so I re-started the load at midnight-ish UK time.  So it will be finishing later than usual.  I'm guessing it will be done by noon.

**Comment by kimrutherford** [comment]
> I've had a first go at this. There is a good chance I've broken something because I had to change quite a
> lot of the loading code.

The good news is that I didn't break the loading.  The bad news is that it didn't seem to fix the problem.  I'll investigate.

**Comment by kimrutherford** [comment]
> The bad news is that it didn't seem to fix the problem.

It looked bad but it actually worked quite well.  Genotypes were mostly merged except for deletions from PHAF files.  But because there are so many deletions from PHAF files it looked like it hadn't worked.  I've fixed that now so hopefully it will be better in tonight's load.

**Comment by kimrutherford** [comment]
> I've fixed that now so hopefully it will be better in tonight's load.

It was a bit better, but still not completely fixed.  I'll try again.

**Comment by ValWood** [comment]
Its a big step in the right direction!
Looks good here http://pombase2.aska.gen.nz/genotype/635732abd73e57de-genotype-7

**Comment by kimrutherford** [comment]
Fixed now I think.  Please open new issues if you spot other problems.
