### ISSUE TITLE
pipes in PHAF converted to commas in Canto and on web

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#625]
spotted as an aside in https://github.com/pombase/website/issues/288 for the PMID:9917066 PHAF and Canto session:

The PHAF has some pipe-separated extensions that are showing up in Canto as "existing annotations" but with the extensions displayed as comma-separated. The annotation display on PomBase2 web pages also treats them as AND instead of OR, leading to some of what got Val confused in the website ticket.

A spot check of some of the other affected papers reveals that it's a general problem. halp!

in case useful ...

    % grep -l '\|' external_data/phaf_files/chado_load/PMID_*
    external_data/phaf_files/chado_load/PMID_15797925_phaf.tsv
    external_data/phaf_files/chado_load/PMID_16096637_phaf.tsv
    external_data/phaf_files/chado_load/PMID_23173672_phaf.tsv
    external_data/phaf_files/chado_load/PMID_24362309_phaf.tsv
    external_data/phaf_files/chado_load/PMID_27172183_phaf.tsv
    external_data/phaf_files/chado_load/PMID_8665408_phaf.tsv
    external_data/phaf_files/chado_load/PMID_9917066_phaf.tsv

**Comment by kimrutherford** [comment]
Yep, it was treating pipes as commas when reading from PHAF files.  I've checked in a fix for Wednesday night's load.

**Comment by kimrutherford** [comment]
Looks OK to me:
  http://pombase2.bioinformatics.nz/gene/SPBC146.07
