### ISSUE TITLE
tor2 and  sck2 not appearing in network (gene corrected)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#626]
Figure out why...
http://pombase2.aska.gen.nz/term_genes/GO%3A1901990

First, me to check EsyN files and other obvious stuff...

(then note to self, make a ticket to ensure the dircetly activates_inhibits get into network building files)

**Comment by kimrutherford** [comment]
tor1 is on that page.  sck1 doesn't seem to have any annotations to a term with "regulation of mitotic cell cycle phase transition" as a parent?

**Comment by ValWood** [comment]
I mean tor2/sck2.
however this is not a good example of what I was trying to check. This is has_substrate.

anyway, this one is in the file "pombase-go-substrates (1).tsv"
SPBC216.07c	SPAC22E12.14c	PMID:22976295
The fat that these are missing must be an esyN issue, but we won't worry about that......this will go away with
https://github.com/pombase/website/issues/293

Now I will check some "directly_negatively_regulates" and + as I originally intended.....
