### ISSUE TITLE
database query for species distribution and orthologs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#627]
Hi Kim,

When you get change could you check and send me the list of anything which has a human ortholog annotated, but does not have
conserved in vertebrates		species_dist	

I think I sometimes forget and add only
conserved in metazoa		species_dist

cheers

Val

**Comment by kimrutherford** [comment]
There are 3477 pombe genes in Chado that have a human ortholog.  Sounds about right?

Only 4 don't have "conserved in vertebrates"

 pbi2 | SPCC338.12
 sol1 | SPBC30B4.04c
 spr1 | SPBC19G7.04
 etp1 | SPAC22E12.10c


Note to self, here's the query:

    SELECT name, uniquename
    FROM feature pombe_gene
    WHERE pombe_gene.type_id =
        (SELECT cvterm_id FROM cvterm WHERE name = 'gene')
      AND organism_id = 1
      AND pombe_gene.feature_id IN
        (SELECT object_id FROM feature_relationship fr
         WHERE type_id IN
             (SELECT cvterm_id FROM cvterm WHERE name = 'orthologous_to')
           AND subject_id IN
             (SELECT feature_id FROM feature WHERE organism_id = 2))
      AND pombe_gene.feature_id NOT IN
        (SELECT feature_id FROM feature_cvterm fc JOIN cvterm t ON fc.cvterm_id = t.cvterm_id
             WHERE t.name = 'conserved in vertebrates');

**Comment by ValWood** [comment]
yep 68.5 % to human  
68.9% to metazoa (small number in C. elegans etc not detected in vertebrates).

still hoping get to 70% with those distant orthologs.....

**Comment by ValWood** [comment]
etp1 | SPAC22E12.10c
is a weird one, its one of the tandem fusions. these will be resolved by

https://github.com/pombase/curation/issues/810

**Comment by ValWood** [comment]
fixed
