### ISSUE TITLE
add total to  curation stats table

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#628]
When you get chance it would be good to add a "total" column to this table, so we don't need to keep "adding up"

![add total](https://cloud.githubusercontent.com/assets/7359272/26494615/60823dca-4217-11e7-831f-9a93404d183f.jpg)

I can see "roughly" where we are but it would be good to see the number

**Comment by kimrutherford** [comment]
That's done now: http://curation.pombase.org/pombe/stats/annotation

**Comment by ValWood** [comment]
great. because the table isn't always visible, could you also make the total appear on the mouse over when  you hover over the histogram bars?

**Comment by kimrutherford** [comment]
> could you also make the total appear on the mouse over when you hover over the histogram bars?

Done!

![stats_tooltip_1](https://user-images.githubusercontent.com/90474/37749919-1f309b0e-2def-11e8-9fc8-8392f7309752.png)

**Comment by ValWood** [comment]
lovely.....I hate adding up ;)
