### ISSUE TITLE
filtering

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#629]
we filter NAS if they are redundant with other annotation.
But one is visible here
http://preview.pombase.org/gene/SPAC688.09
I checked the parentage and it looks OK so I con't figure why.

**Comment by ValWood** [comment]
Actually it might have recently been deleted, but quickgo isn't caught up...

**Comment by kimrutherford** [comment]
I can't see a NAS on there now.  Maybe fixed?

**Comment by ValWood** [comment]
OK I'm not sure what was happening but its gone so closing ;)
