### ISSUE TITLE
number drop in GO slim GO:0000070 - mitotic sister chromatid segregation, can't figure out why

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#631]
GO:0000070 - mitotic sister chromatid segregation

I check the list @kimrutherford  supplied of genes annotated to 
http://preview.pombase.org/term_genes/GO%3A0000070
to those on the old site
http://www.pombase.org/spombe/related/GO:0000070

The difference appears to be that gene products annotated to +/- regulation of the mitotic metaphase /anaphase transition are not longer annotated to GO:0000070

GO appears to be correct.

![parentage](https://user-images.githubusercontent.com/7359272/26874063-16897b0a-4b74-11e7-942f-2b1a07da49a0.jpg)

(i.e. regulation of the mitotic metaphase /anaphase transition has mitotic chromosome segregation parentge)

so I'm now stuck.

Any ideas?

**Comment by ValWood** [comment]
Labelled as a bug, but cause unknown...

**Comment by kimrutherford** [comment]
We get the term ancestors from OWLTools.  For each term and its ancestor we get the relation that connects them.  We have configured to only follow "is_a", "part_of" and "regulates" for making the subsets.

The relation from OWLTools connecting "positive regulation of mitotic metaphase/anaphase transition" and "mitotic sister chromatid segregation" is "positively_regulates" which makes sense.

So this would be fixed if we add positively_regulates to the config.

**Comment by kimrutherford** [comment]
I did a test adding "positively_regulates" and "negatively_regulates" to the config.  With that the subset has 167 genes.

**Comment by ValWood** [comment]
yes we should use regulates, negatively regulates and positively regulates.
It's interesting that most things slim already (although not unexpected now I think about it)

**Comment by kimrutherford** [comment]
I've added "positively_regulates" and "negatively_regulates" to the config.  The term_genes pages now include descendants via those relations:
  http://preview.pombase.org/term_genes/GO%3A0000070

The terms pages will have those extra descendant annotations too:
  http://preview.pombase.org/term/GO%3A0000070

> With that the subset has 167 genes.

I misread that.  It's actually 173.

**Comment by ValWood** [comment]
that's correct. the slim now mirrors the numbers annotated here:
http://preview.pombase.org/term_genes/GO%3A0000070

Genes annotated with GO:0000070 or its descendants: 173

**Comment by ValWood** [comment]
is plain "regulates included as well as +ve and -ve?
If so can close

**Comment by kimrutherford** [comment]
Yep, it include regulates.
