### ISSUE TITLE
some physical interactions (but not all) showing in duplicate

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#632]
sad1

![saf1](https://user-images.githubusercontent.com/7359272/27214049-323b6706-5262-11e7-895c-4515bad23632.jpg)

**Comment by ValWood** [comment]
Oh I see. This means   (proabably) that we are already doing the reciprocal interaction display thing for bioGRID.  BUT, that we don't need to do this for self-self binding .

(Note that there is another ticket for ensuring that GO protein binding terms are "reciprocated", I don't think we do this yet?)

**Comment by ValWood** [comment]
should this be moved to website tracker instead then?

**Comment by kimrutherford** [comment]
Move to website tracker: https://github.com/pombase/website/issues/417
