### ISSUE TITLE
F-P links GAF check

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#633]
From
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0051920#term=ancchart

http://preview.pombase.org/gene/SPBC17D11.03c
should get an annotation to 
GO:0098869 cellular oxidant detoxification
and slim to cellular detoxification but it doesn't?

First off, I can't remember now if we get the F-P links from GOA or pick up the file. And I can't remember where the file is.  Whichever this is, need to check that it isn't in the file before I report to GO.

**Comment by ValWood** [comment]
I can follow up I just need to be reminded of the source file...

**Comment by kimrutherford** [comment]
I think that's the file that has gone missing?:
  https://github.com/pombase/website/issues/263#issuecomment-295708515

**Comment by ValWood** [comment]
https://github.com/geneontology/go-annotation/issues/1576
will deal with this...
