### ISSUE TITLE
Update Uniprot mapping file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#634]
Transferred from
https://github.com/pombase/curation/issues/1503

There are the new accessions for the de-merged entries

SPAC212.01c P0CT98
SPAC977.01 P0CU16
SPAC977.02 P0CU07
SPAC977.07c P0CU05
SPAC977.08 P0CU00
SPAC977.09c P0CU02
SPAC977.11 P0CU19
SPAPB17E12.02 P0CU09
SPAC19B12.12c P0CU08
SPAC750.02c P0CU10
SPBC1348.02 P0CU14
SPBC1348.06c P0CU13
SPBC1348.09 P0CU01
SPBPB10D8.04c P0CT94
SPBPB10D8.05c P0CT95
SPBPB10D8.06c P0CT96
SPBPB10D8.07c P0CT97
SPBPB2B2.15 P0CU12
SPBPB2B2.16c P0CU11
SPBPB2B2.19c P0CU15
SPBCPT2R1.04c P0CT99

and some that were not in the list
SPAC750.04c P0CU06
SPBC1348.08 P0CU04
SPBPB8B6.06c P0CU20

These need to be updated in the UniPRot->pombase mapping file.
Up until now I think this was mainteined by the EBI?
(It really should  never change again)

**Comment by mah11** [comment]
Which file is this?

I updated the gp2protein file in GO SVN in March, and it has all of the accessions listed as "new" here. No idea why the PomBase2UniProt.tsv file in ftp doesn't match it; maybe I did the gp2protein based on an email. Anyway, I think that means we can use gp2protein to load chado ...

**Comment by ValWood** [comment]
It's this file:

PomBase2UniProt.tsv
http://www.pombase.org/downloads/data-mappings

Paul K and Mark got it all aligned last time, and I don't think we have ever touched it. As far as I know Mark just copies across to the ftp site. So now we need to keep a local copy somewhere...

**Comment by mah11** [comment]
True, we haven't ever touched PomBase2UniProt.tsv. The point of my previous comment, though, is that the gp2protein.pombase file appears to be more up-to-date - it has all of the "new" accessions you listed in the original ticket summary. The current gp2protein.pombase also passes the validation checks (https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=198454), so perhaps we ought to just use it and let PomBase2UniProt.tsv fade into oblivion.

**Comment by ValWood** [comment]
Ah OK,  so we were maintaining 2 files which did the same job!

What does the gp2protein file look like?

Is it close enough to replace the download file here?
http://www.pombase.org/downloads/data-mappings

(A lot of the mass spec people use this file because all the software works on UniProt IDs)

**Comment by mah11** [comment]
> Ah OK, so we were maintaining 2 files which did the same job!

Pretty much, yes. A while ago it took me ages to figure out that Mark et al. weren't updating gp2protein.pombase at GO in sync with changes to the other file. I had naively thought that was part of their spec ...

> What does the gp2protein file look like?

erm, it looks like a text file with 2 columns, PomBase systematic ID and UniProt accession

> Is it close enough to replace the download file here?
> http://www.pombase.org/downloads/data-mappings

To the best of my knowledge the only significant difference is that gp2protein.pombase is up to date. (gp2p-yada also has ID prefixes, but that difference is not significant.)

**Comment by ValWood** [comment]
wow a problem solved.
Yes it was probably my fault. Historically I created/maintained protein2GO, and then when you arrived I promptly forgot about it. I probably never mentioned it to any one. Originally its main purpose was for Quest for Orthologs and it got to the point where EBI appeared to be creating it when Dan Barrell was around, so it fell off my radar...

**Comment by mah11** [comment]
We both did mention gp2protein to then-pombase EBI folk, and told them explicitly that updating it at GO should become part of the pipeline (see https://www.ebi.ac.uk/panda/jira/browse/PB-542). But am I surprised it never happened? ha.

**Comment by ValWood** [comment]
I know this one can be closed!
