### ISSUE TITLE
loader check for annotations with malformed  "qualifier type"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#635]
/controlled_curation="term=species distribution, conserved in fungi; date=20100824"
was not showing on gene page

because it was typed
/controlled_curatio="term=species distribution, conserved in fungi; date=20100824"

no log report.

**Comment by ValWood** [comment]
would
https://github.com/pombase/website/issues/665
identify
/controlled_curatio=
?

**Comment by kimrutherford** [comment]
> would
> pombase/website#665
> identify
> /controlled_curatio=

Unfortunately not.  The current code goes looks for qualifiers that it can process (like /GO and /EC_number) and stores the data in Chado.  It doesn't then go back and check for qualifiers it doesn't recognise.  I'll see if I can fix that.

**Comment by ValWood** [comment]
Would the most useful approach, rather than trying to identify specific errors, be just to report any qualifier that cannot be parsed  (in part or entirety) in the logs (would probably be able to close a few tickets!)

**Comment by kimrutherford** [comment]
> be just to report any qualifier that cannot be parsed

That's pretty much what happens.  But in the case of "/controlled_curatio=" the syntax is fine so there's no parse error.

**Comment by kimrutherford** [comment]
I've changed the loader to report unknown qualifier names.  It's too late for the current load but should be in the logs on Friday morning.

**Comment by ValWood** [comment]
fixed:
mRNA SPAC823.17.1: unknown qualifier: /obsolete_synonym
mRNA SPBC13G1.14c.1: unknown qualifier: /name
could not see a problem with mRNA SPCP20C8.01c.1: unknown qualifier: /controlled_curatio
@mah11  did you fix?

**Comment by mah11** [comment]
> could not see a problem with mRNA SPCP20C8.01c.1: unknown qualifier: /controlled_curatio
> @mah11 did you fix?

Not recently, but it's not in the logs generated since Kim's loader changes this week. It's entirely plausible that I fixed it back when this ticket was opened.

**Comment by ValWood** [comment]
Oh no it was me...thats why I opened the ticket, doh!

**Comment by kimrutherford** [comment]
> I think because I guess somewhere Canto must know

Do you mean Chado?  We currently store the /codon_start in Chado, but we don't store the /partial.  We should do that for completeness so I'll make that change.

> the mitochondrial genome uses a different translation table

The /transl_table qualifier isn't stored in Chado but when we write out the protein sequence files for the FTP site the sequences are translated using the mitochondrial translation table.

**Comment by kimrutherford** [comment]
> you can ignore

I've stopped it warning about the four qualifiers you listed.  The change will be visible on Saturday morning.

> but we don't store the /partial. We should do that for completeness so I'll make that change

I've done that so I think this issue can be closed.

**Comment by ValWood** [comment]
yep, chado.
