### ISSUE TITLE
The GO GAF loader needs to handle extensions. 

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#636]
https://github.com/pombase/curation/issues/1516

fairly soon.....

**Comment by kimrutherford** [comment]
I've made the changes needed and it seems OK when I test it locally.  I'll check the results of tonight's load in the morning.

**Comment by ValWood** [comment]
well the update is on http://pombase2.aska.gen.nz/

and modifications are present:
http://pombase2.aska.gen.nz/gene/SPAC15A10.15

but the cdc2 substrates with extensions not:
http://pombase2.aska.gen.nz/gene/SPBC11B10.09

**Comment by kimrutherford** [comment]
Sorry!  I made the change locally but forgot to "git push".  So the file wasn't included.

I've just added it from the command line and it's now visible:
  http://pombase2.bioinformatics.nz/reference/PMID%3A27984725
(Might need a reload)

**Comment by ValWood** [comment]
OK, that is all working. I think we can improve, but I don't  know if this is the submission file or a display issue.

1. For M @mah11  can we use "cyclin-dependent protein serine/threonine kinase activity"?

2. I expected the grouping to be slightly different, but i can't remember where our precedence is documented.

For sure I would not expect to see

has substrate ase1 , abp1 , adn2 , ask1 , atf1 , alp14 , bir1  during mitotic M phase
has substrate bud6 , cdc12 , byr4 , bun107 , brf1 , bqt4 , ccq1 , bpb1  during mitotic M phase
has substrate cph1 , clp1 , cmk2 , cdc25 , cnt5  during mitotic M phase
has substrate dbl7 during mitotic M phase
 


instead I would expect to see
has substrate  ase1 , abp1 , adn2 , ask1 , atf1 , alp14 , bir1, bud6, bpb1, cph1 , clp1 , cmk2 , byr4 , bun107 , brf1 , bqt4 ,  cdc25 , cnt5  , cdc12 , ccq1 , dbl7 during mitotic M phase
(that isn't quite alphabetical but you get the picture).

I would  only expect to see them separated out *if* there is additional information.

**Comment by ValWood** [comment]
Above I am looking at the cdc2 page
http://pombase2.aska.gen.nz/gene/SPBC11B10.09
rather than the publication page, but I think the same issues apply.

Maybe we haven't addressed this yet  because we usually have information about  the process *before* we have information about the phase?
I even wonder if there is an outstanding ticket about precedence that might help?

**Comment by mah11** [comment]
Hmm. I have reloaded several times, and shift-reloaded once or twice, and I do not see the GO annotations on either the publication page or the cdc2 gene page. Kim also hasn't updated the ticket (#637) about loading the GAF for this paper.

I have updated the GAF to use GO:0004693.

**Comment by kimrutherford** [comment]
> I have reloaded several times

Sorry about that.  I forgot to check in the change to the load script twice.  I've definitely done a successful "git push" now.  I've also added that file to the web data so it should be there now if you reload:
  http://preview.pombase.org/reference/PMID%3A27984725

**Comment by mah11** [comment]
They are indeed there now - yay!

**Comment by ValWood** [comment]
Odd that I could see them.

Kim could you look at the grouping query above next. Can you see why these aren't grouping as expected. Any insights anyone? Kim, if this doesn't make sense to you we can have a chat tomorrow.

**Comment by kimrutherford** [comment]
> Odd that I could see them.

I had added the new annotations temporarily so you could have a look but it got overwritten by the nightly load.

> Kim could you look at the grouping query above next. Can you see why these aren't grouping as expected.

Yep, I'll look into that.

**Comment by kimrutherford** [comment]
> instead I would expect to see

The summary is improved now:
  http://preview.pombase.org/reference/PMID%3A27984725

but because of the way I fixed it, the details view has changed.  The annotations are now ordered and grouped together by the during relation.  If you have a look it will be clearer than my explanation.

Grouping by phase probably makes sense but the order is alphabetical (G2, M, S) rather than the actual order.

Also it might not make so much sense for other relations.

Let me know what you'd like me to do.

**Comment by ValWood** [comment]
That looks great. I think the publication page is as I expected.
The gene page works as expected to. Grouping  by phase is a longer term goal. There is an open ticket about this.

One more improvement if it is quick, I think if a  GP has an  substrate +involved_in  it should come above anything which has substrate+ phase (only)...more information.

Is that easy  or tricky?
If tricky close this an'd I'll append to the other  open extension ordering ticket.

**Comment by ValWood** [comment]
If there is just a list of substrates

has substrate SPAC11G7.01 , mac1 , sgo2 , bud6 , cph1 , pom2 , shd1 , clp1 , ulp2 , lem2 , nup40 , pan3 , SPAC1B2.03c , mkh1 , spo15 , cdc12 , cdc15 , byr4 , snt1 , SPAC22H10.11c , cmk2 , plo1 , rad4 , nup146 , ies4 , SPAC24B11.07c , sid2 , cdc25 , sld3 , SPAC24H6.08 , gef1 , rga2 , mgs1 , rga3 , hal4 , sec16 , prp3 , pom1 , nup124 , rad52 , mis4 , dbp10 , rod1 , bun107 , mvp1 , spo12 , rad2 , nsk1 , mpd2 , ppc89 , pof1 , ies2 , drc1 , rif1 , iss10 , slf1 , wis4 , cyk3 , SPAC9G1.07 , inp53 , mdb1 , ase1 , abp1 , pre6 , pob1 , adn2 , sad1 , fkbp39 , cdc23 , SPBC13E7.03c , SPBC13E7.07 , brf1 , cut3 , tam10 , klp9 , tea2 , nrm1 , fkh2 , srp40 , SPBC17A3.05c , SPBC17D1.05 , cnt5 , sce3 , bqt4 , psy2 , mmb1 , dnt1 , ask1 , rga4 , sfr1 , hmo1 , orc1 , atf1 , ebs1 , csi1 , hip1 , pch1 , pic1 , tmf1 , mug176 , wis1 , SPBC428.10 , wpl1 , sep1 , kin1 , pxl1 , swi10 , mod5 , dbl7 , orc2 , ppk30 , mde4 , sog2 , kms2 , SPBC9B6.03 , SPBC9B6.11c , SPBP8B7.26 , SPBPB7E8.02 , utp502 , lnp1 , tfg1 , mcm4 , scw1 , ccq1 , SPCC23B6.04c , nup60 , msh6 , mto1 , nur1 , dfp1 , sup35 , epe1 , rgf3 , mmi1 , dis1 , bit61 , alp14 , bir1 , bpb1 , puf6 , vps5

These should default to alphabetical (one there is an involved in, we use that to sort alphabetically)

**Comment by ValWood** [comment]
Easier to locate gene of interest...

**Comment by ValWood** [comment]
> One more improvement if it is quick, I think if a GP has an substrate +involved_in it should come above anything which has substrate+ phase (only)...more information.

Ignore this request. It is in conflict with our long term request to order by phase, so gine as it is for now!

**Comment by kimrutherford** [comment]
> These should default to alphabetical

I thought there was an issue about that.  I couldn't find it so I made a new one: https://github.com/pombase/website/issues/437

**Comment by kimrutherford** [comment]
> Is that easy or tricky?
> If tricky close this an'd I'll append to the other open extension ordering ticket.

That's not completely easy so I'll close this.
