### ISSUE TITLE
new external GO file to load

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#637]
file from https://github.com/pombase/curation/issues/1516 is ready:

pombe-embl/external_data/external-go-data/PMID_27984725_gaf.tsv

It has extensions, so it'll require #636. For future-proofing it might be a good idea to have the loader look for `*PMID*` like it does for PHAFs and modification files.

**Comment by kimrutherford** [comment]
Add in https://github.com/pombase/pombase-legacy/commit/9d7d26c5ee1dbbbcfbf97b88a903db99760a78d8
