### ISSUE TITLE
A small fix in the export of data for EsyN

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#638]
Currently, we export  MF annotations using Has_substrate the following into the target_substrate file

Could we also export any MF annotations with "directly_negatively_regulates" and "directly_positively_regulates" into this file?
At the moment we don't export them, and we are crazily trying to fill gaps in signalling networks.

So, for example here:
https://github.com/pombase/curation/issues/1638
I needed to artificially connect  mug134->ppa2-> cdc25
because 
mug134(igo1) is captured as "directly inhibits" ppa2

Actually we have a lot of  directly_negatively_regulates and directly_positively_regulates
so I'm surprised some of these networks continue to look OK.....

**Comment by ValWood** [comment]
This is a bit temporary as the relationship will change
https://github.com/pombase/website/issues/277

but we need it to refine the signalling pathways for the GO signalling workshop.

**Comment by ValWood** [comment]
so its
pombase-go-substrates.tsv.gz
https://curation.pombase.org/dumps/latest_build/exports/

that they need to appear in to be included in the networks.

**Comment by kimrutherford** [comment]
It looks like it exports only those annotations with has_direct_input().  Does that make sense?

If so adding the other to extensions is quick.

**Comment by ValWood** [comment]
Yes that makes sense. We only used that  relation when we began.

Can you add also
directly_negatively_regulates
and
directly_positively _regulates
to the exported effecto/substrate file?

**Comment by kimrutherford** [comment]
I've added those relations to the exporter.  I'll check things in the morning.

There should be 2299-ish lines in the file tomorrow (2270 at the moment).

**Comment by ValWood** [comment]
OK not a big jump, which accounts for why there isn't much missing when we generate the networks. I suspect most also have a curated  has_substrate or physical interaction, so we would pick them up that way....

**Comment by ValWood** [comment]
Was just curious how many things we have  potentially in the global network in total.

Adding together reciprocal interactors, effectors substrates and complex members, unique gives 2363...pretty good...

( I forgot I probably need to check if I need to add any new high level complex grouping term filters, will add to my list)

**Comment by kimrutherford** [comment]
>  I'll check things in the morning.

Seems OK.  There are 2308 lines in the file now.

**Comment by ValWood** [comment]
yep, endosulphine and great wall which only have this relation are now in the file:
SPAPB18E9.02c	SPAC10F6.16	PMID:26776736
SPAC10F6.16	SPBC16H5.07c	PMID:26776736

So @Antonialock  everything should be present after next esyN update.
