### ISSUE TITLE
Get pombase-gafcheck-prediction.gaf automatically once GO pipeline is stable

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#639]
The downloading of new versions of pombase-gafcheck-prediction.gaf is currently disabled because sometimes the GO pipeline fails and the file is missing from the pipeline artefacts.  We should re-enable the downloading in load-all.sh when things are working consistently.

**Comment by ValWood** [comment]
Status?

**Comment by ValWood** [comment]
I'll put "next" since it has "high priority"

not sure what this one is.

**Comment by kimrutherford** [comment]
Downloading new versions is still disabled.  I've sent a follow-up email to Seth to ask where the file lives now.

**Comment by kimrutherford** [comment]
I edited the load script but failed to update the URL.  I had to make some other edits (which I think I got right) but it looks like I managed to paste the old URL in instead of the new one.

It ended up load no inferred annotations because it didn't handle the error well.  So I won't update www or the preview unless you think that's OK.

I've fixed the URL and made the loader more robust to download failures.  It should now just use the last GAF file it successfully downloaded so the load should now complete even if the GO pipeline fails.

**Comment by ValWood** [comment]
can wait

**Comment by kimrutherford** [comment]
The updating of pombase-prediction.gaf is now working. There are only 80-ish annotations in the file.

**Comment by ValWood** [comment]
wow!
@cmungall

**Comment by Antonialock** [comment]
what are these predictions? @ValWood

**Comment by ValWood** [comment]
they aren't predictions, they are "inferences" from F-P links.
We will only get them if we did not make the annotation already manually.
I suspect some of the remaining will  be to terms we do not use (like  modification process terms). I'm about to check the file to see how many are retained after our local filtering.

(That said, some I expected appear to be missing, probably due to ignoring non-experimental evidence codes. They are the ones we *really*  want.... because they will be things which are not so well-annotated)

**Comment by ValWood** [comment]
This is what we retain after local filtering

  11 GO:0000775
   3 GO:0005634
  12 GO:0005739
   2 GO:0005829
   9 GO:0034507

**Comment by ValWood** [comment]
Hmm, all of the  inferences currently are  CC...all of the F-P ones have disappeared.....

**Comment by ValWood** [comment]
@kimrutherford  you don't need to do anything, I don't think we lose very much...(it didn't change the slim)

Will report on GO annotation tracker...

**Comment by mah11** [comment]
> Hmm, all of the inferences currently are CC.

I think that's as it should be - F-P inferences have been in gene_association.pombase.inf.gaf (not the one with "prediction" in the file name) all along.

That said, there is still a problem with inf.gaf - it's still a lot smaller than the one I get running owltools (Jenkins) GAF checks locally, a la https://github.com/geneontology/go-annotation/issues/1336/

**Comment by ValWood** [comment]
Ah @kimrutherford  and I  misunderstood when we asked where the file had moved to. We thought the file was renamed... So now there are 2 files?

I'm hoping for  a drop in  size if the redundancy was removed.... although there is redundancy in the  file  with CC terms in it so  I expect it isn't fixed.

**Comment by mah11** [comment]
Yes, I think there have been two files for a while (not that I'm blown away by communication of that fact by GOC ...). F-P links were, and still are, in gene_association.pombase.inf.gaf (which is still at the location we've been using for a while, http://build.berkeleybop.org/job/gaf-check-pombase/lastSuccessfulBuild/artifact/gene_association.pombase.inf.gaf). That file now also has some CC annotations, but I don't know how it infers them.

It's the pombase-prediction.gaf that has moved. That one has CC annotations, but not the same annotations as in the .inf.gaf one. I don't know how either set of CC annotations are being inferred, nor what the difference is. I agree with you that some of them look stupid.

**Comment by ValWood** [comment]
So Kim, there are 2 files we need to take in....

I think for now, since  all of the  CC ones are
a) redundant
and
b) look a bit silly
we will drop this file...

( I will do a quick check that  the annotations are covered)

so we need to take only
gene_association.pombase.inf.gaf

**Comment by ValWood** [comment]
Actually I'm still confused.  We were definitely told  to use the new location....

**Comment by mah11** [comment]
yeah, but they may have thought you knew wanted the "prediction" file, and wanted to know where it had gone (iow they may not have realized we had predictions and inf.gaf confused)

... idle speculation, since I don't really have a good idea what's going on

**Comment by ValWood** [comment]
We were asking about the inferences. The implication was that the file name had changed...

**Comment by mah11** [comment]
Technically I think they're all inferences of some sort or other. The ones in "prediction" seem to be CCs inferred from BPs that are defined as taking place in some CC (my interpretation of 
http://build.berkeleybop.org/job/go-gaf-release-snapshot/lastSuccessfulBuild/artifact/pipeline/target/groups/pombase/pombase-prediction-report.txt contents).

**Comment by kimrutherford** [comment]
Just to confirm, load gene_association.pombase.inf.gaf instead of pombase-prediction.gaf?

**Comment by mah11** [comment]
I am so confused by which files GO puts where that I recommend getting Chris or Seth to confirm ...

(I thought the MF-BP inferences we want were still in gene_association.pombase.inf.gaf, because that file does get generated by GO Jenkins and does contain BP annotations ... but I'm no longer sure what's going on ...)

**Comment by kimrutherford** [comment]
> Just to confirm, load gene_association.pombase.inf.gaf instead of pombase-prediction.gaf?

I've made that change and filtered out the component annotations.  The change didn't make it into tonight's load so the changes won't appear until Saturday.

**Comment by kimrutherford** [comment]
The gene_association.pombase.inf.gaf file loaded successfully last night.  Is there anything else to do here?

**Comment by ValWood** [comment]
Not for now...
