### ISSUE TITLE
generate a file for iPTMnet

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#640]
iPTMnet (http://annotation.dbi.udel.edu/iptmnet/) is a collection of post-translational modification annotations from all over, which is getting dodgy "protein information" for pombe proteins from UniProtKB records (see helpdesk https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=204300). They're happy to use our up-to-date data if we provide them a file with these columns:

UniProt Accessions|Protein name|Gene name|PomBase ID

where, as I understand it, we can use the product description in the protein name column.

For now, as a stopgap, etc. etc., I have cobbled together a file consistent with legacy-PomBase v62 using the existing sysID2product.tsv and gp2protein files, so this can wait until after Shiny New PomBase is released. But it ain't a thing to keep doing manually in the long term.

I'm guessing that we can generate this file when we make monthly Chado snapshots and point the nice iPMTnet people to a stable location for the latest version of it. I have no particular prejudices regarding where that location should be.

**Comment by ValWood** [comment]
OK, so that's another file for this list.
https://github.com/pombase/website/issues/355

**Comment by mah11** [comment]
they should be able to use gene_IDs_names_products.tsv
