### ISSUE TITLE
Add warnings about unused/unknown qualifiers to the logs

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#642]
Things like:
 
    /synonymn=SPNCRNA.906

**Comment by ValWood** [comment]
whoops!

**Comment by ValWood** [comment]
Would this be detected at present?

**Comment by ValWood** [comment]
Hi @kimrutherford was this covered when you made recent additional checks on the artemis data loaded?

**Comment by kimrutherford** [comment]
Yep, that should be fixed now.
