### ISSUE TITLE
human ortholog name source

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#643]
Whats the status of human ortholog  name source...I forget where we are.

So, 
http://pombase2.bioinformatics.nz/gene/SPAC1F7.14c
has
/controlled_curation="term=human DMAC1 ortholog; db_xref=Pfam:PF15055; date=20161031"

which was fine until recently I think?

Now in the logs as
mRNA SPAC1F7.14c.1: can't find feature for: DMAC1
mRNA SPAC1F7.14c.1: can't find feature for: DMAC1

but
http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:30536

(If we don't get from HGNC yet ignore for now)

**Comment by kimrutherford** [comment]
> (If we don't get from HGNC yet ignore for now)

I haven't changed things to use the HGNC directly yet.

**Comment by ValWood** [comment]
ok will ignore this for now. I'm aligning with HGNC. Oddly the ensembl source seems to change somewhat independently of hgnc and newly added or existing names so I often get a bit confused.

**Comment by ValWood** [comment]
see
https://github.com/pombase/pombase-chado/issues/598
