### ISSUE TITLE
Move PomBase2UniProt.tsv to pombe-embl SVN

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#644]
The nightly load uses this file:
 ftp://ftp.ebi.ac.uk/pub/databases/pombase/pombe/Mappings/PomBase2UniProt.tsv

we should move it to the SVN directory.

**Comment by mah11** [comment]
Per #634, the gp2protein file in GO SVN has more up-to-date content. Do we want to continue to have two files with the different names?

One (gp2protein.pombase.gz) has prefixes and the other doesn't but there aren't supposed to be any other differences. If we want to continue offering PomBase2UniProt.tsv, one of the files should be the "master", and the other automagically generated by adding or removing prefixes, just in case we do ever have to edit it again.

**Comment by ValWood** [comment]
Sort of fixed?
If not @mah11  describe what needs to happen still?
