### ISSUE TITLE
new GO evidence codes

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#646]
HTP (ECO:0006056) inferred from high throughput experiment
HDA (ECO:0007005) inferred from high throughput direct assay
HEP (ECO:0007007) inferred from high throughput expression pattern
HGI (ECO:0007003) inferred from high throughput genetic interaction
HMP (ECO:0007001) inferred from high throughput mutant phenotype

we should not enable these in Canto as they will be rarely used.
I only envisage us using HDA (ECO:0007005) inferred from high throughput direct assay
for some HTP datasets.

Once Chado supports it, we should change the evidence code associated with the
http://preview.pombase.org/reference/PMID:16823372 dataset.

we can ddo others on a cse by case basis if required.

**Comment by ValWood** [comment]
What do we need to do to accept a new Evidence code. Is it just a configuration?

**Comment by kimrutherford** [comment]
The evidence code config is here:
  https://github.com/pombase/pombase-legacy/blob/master/load-pombase-chado.yaml

in the section "evidence_types".

I'm happy to add them.

> HTP (ECO:0006056) inferred from high throughput experiment

Is that a GO evidence code?

**Comment by ValWood** [comment]
yes but this is the only one we will like use in the immediate future:
HDA (ECO:0007005) inferred from high throughput direct assay

I can add...

**Comment by ValWood** [comment]
I hope I did it OK.

**Comment by kimrutherford** [comment]
> I hope I did it OK.

Yep, looks good.

**Comment by kimrutherford** [comment]
I've added the other codes.

**Comment by ValWood** [comment]
OK, I changed the evidence in 

pombe-embl/external_data/external-go-data/GO_ORFeome_localizations2.txt

to IDA.

If this looks OK, and gets to GO OK, we can change others....
