### ISSUE TITLE
New PHAF

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#647]
I added a
new PHAF
PMID_28945192_phaf.tsv

I think this is my first apart from the call cycle  morphology paper

I have no idea if it will load OK....

**Comment by ValWood** [comment]
needs
^M ->/n

**Comment by mah11** [comment]
There's a command line trick that I don't remember. I fixed them in emacs, and added the required row of column headers. It looks OK now, so anything else amiss should spawn log messages.

**Comment by ValWood** [comment]
OK thanks, I know I have the command line trick somewhere but I can *never* find it...
