### ISSUE TITLE
logs should report incorrect use of with /from

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#648]
"from" is only allowed with IC

spotted fex1:

![report iso from](https://user-images.githubusercontent.com/7359272/31850777-75ac8a4a-b650-11e7-8ce4-d3ae877012cb.jpg)

**Comment by mah11** [comment]
I have found and fixed a couple more. In case it's useful for log-generating purposes, the offending bit was this from chromosome1.contig:

    FT                   /GO="aspect=F; term=siderophore transmembrane transporter
    FT                   activity; GOid=GO:0015343; evidence=ISO;
    FT                   from=SGD:S000001032; db_xref=GO_REF:0000024;
    FT                   date=20160811"
    FT                   /GO="aspect=P; term=siderophore transport;
    FT                   GOid=GO:0015891; evidence=ISO; from=SGD:S000001032;
    FT                   db_xref=GO_REF:0000024; date=20160811"

**Comment by ValWood** [comment]
Hi @kimrutherford  was this covered when you made recent additional checks  on the artemis data loaded?

**Comment by ValWood** [comment]
Judging by this,

mRNA SPAC222.19.1: ISS must have a "with=": failed to load qualifier 'aspect=P; term=regulation of TOR signaling; GOid=GO:0032006; evidence=ISS; db_xref=GO_REF:0000111; from=GO:0071986; date=20180213' from SPAC222.19.1:

it now does, so closing!
