### ISSUE TITLE
stats for new curators

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#650]
This isn't super urgent but I'm sure the numbers of "first time communiyt curators" are fluctating a bit oddly. How are they calculated.
I ask because I'm sure that when I looked at them during the metrics session at the GO meeting, new curators for last year was in the 70's (and definitely we were a long way behind for this year).

Now we have
![first time](https://user-images.githubusercontent.com/7359272/32858915-f1d9a0fa-ca44-11e7-96d7-75e9b06200c7.jpg)

I know I  don't even know what day it is, but I really do think that the number for 2016 has dropped. Maybe the "reapproval date" is reclassifying as this year?

(this isn't urgent until we need to use the stats for anything real)

**Comment by kimrutherford** [comment]
> Maybe the "reapproval date" is reclassifying as this year?

Yep, I think that's it.

If I use the year of first submission I get:

     first_year | count 
    ------------+-------
           2012 |     9
           2013 |    52
           2014 |    49
           2015 |    36
           2016 |    50
           2017 |    36

Should we use that instead?

**Comment by ValWood** [comment]
that seems better!

**Comment by kimrutherford** [comment]
> that seems better!

OK, I've changed to use the submission date and I've re-released Canto.
