### ISSUE TITLE
standardize order of allele in multi-gene phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#652]
(I'm sure there was already a ticket about this

![standardize](https://user-images.githubusercontent.com/7359272/32991479-561e346c-cd34-11e7-81ec-6232e9639cc6.jpg)
 but I can't find it)

We need to standardize so we don't  have 2 geneotype entries/pages

orp1-4,cdc18-46
cdc18-46,orp1-4

I think we decided to alpahabetize?

**Comment by kimrutherford** [comment]
> I think we decided to alpahabetize?

That's quick to do.  Does it need discussion or should I go ahead and make the change?

**Comment by ValWood** [comment]
I think you can go ahead. Any objections anyone?

**Comment by mah11** [comment]
no, that sounds fine

**Comment by kimrutherford** [comment]
> I'm sure there was already a ticket about this

I think this is the ticket:
  https://github.com/pombase/pombase-chado/issues/497

It a quick fix to standardise the display order so I've done that for tomorrow's update.

But that won't fix the duplicate genotypes.  The Chado loader needs work to fix that.

We also need to handle genotypes that have the same alleles and expression, but with different backgrounds:
  https://github.com/pombase/website/issues/284

**Comment by ValWood** [comment]
OK, it will fix the  duplication where everything is the same except expression though won't it?

**Comment by kimrutherford** [comment]
> OK, it will fix the duplication where everything is the same except expression though won't it?

That needs the Chado loading fix (#497).  So far I've only fixed how they're displayed not how they're stored in Chado.

**Comment by kimrutherford** [comment]
I'm going to close this because #497 covers things.
