### ISSUE TITLE
new syntax to describe mutation of multipe Amino acids

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#654]
I just used this
S3,S66,S284,T89,T104,S113,S118,S143,S308,S332,S334,T351,T379->A

as shorthand for 
S3A,S66A,S284A,....etc

Can we allow this alternative, as it will make some very long allele descriptions fractionally shorter? I think its easy to human parse too....

**Comment by Antonialock** [comment]
I don’t think it is a great idea to invent our own system

**Comment by mah11** [comment]
I'm with Antonia - it's not standard, so it will cost everyone a few seconds to figure it out, and even then it will rely on making an assumption about something not explicitly stated.

I have no plan to use it even if it gets added.

**Comment by ValWood** [comment]
It isn't really a different "system", it's the same description behind the scenes, but its a simpler/shorter label if they mutate 13+ residues to the same residue.

But I can change to the longer version....no problem...

**Comment by ValWood** [comment]
fixed in PMID:22665807
