### ISSUE TITLE
query about relationship direction

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#655]
FYPO Canto suggestion “long mitotic spindle during anaphase” suggests abnormal mitotic spindle assembly

this seems wrong

@mah11  h ow are these related?

Over the holidays I'll look at this and other examples and see if I can figure. We can discuss after hols....

**Comment by mah11** [comment]
Is this on the right tracker? It looks like it has to do with Canto and FYPO more than Chado.

**Comment by ValWood** [comment]
moving to canto tracker
