### ISSUE TITLE
load all GAFs in external-go-data

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#656]
From https://github.com/pombase/website/issues/648 

The Chado loader should use all of the GAFs in the pombe-embl/external_data/external-go-data/ directory. It shoud work to load all files that match PMID*gaf.tsv, analogous to how it loads PHAFs.

**Comment by kimrutherford** [comment]
I made the change to the load script before the load started so we can check the GAF file sizes in the morning.

**Comment by kimrutherford** [comment]
I think this is fixed now.
