### ISSUE TITLE
list of genes which went from uncharacterized to characterized (for unknowns paper)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#657]
Hi Kim, below is what you did before Christmas.
I need exactly these queries, but I need the gene IDs rather than the totals.

Thanks

Val

--

I've fixed my query so I can get the numbers from 2014.  I forgot we
renamed the characterisation status terms in Chado in 2015.  So I now
get this, including the number from last week:

pombase-chado-v47-2014-10-27
 count |                   name
-------+-------------------------------------------
   535 | conserved_unknown
   145 | Schizosaccharomyces pombe specific family
   178 | Schizosaccharomyces specific family
(3 rows)

pombase-chado-v55-2015-09-09
 count |                            name
-------+-------------------------------------------------------------
   511 | conserved unknown
   144 | Schizosaccharomyces pombe specific protein, uncharacterized
   177 | Schizosaccharomyces specific protein, uncharacterized
(3 rows)

pombase-chado-v61-2016-09-12
 count |                            name
-------+-------------------------------------------------------------
   503 | conserved unknown
   149 | Schizosaccharomyces pombe specific protein, uncharacterized
   181 | Schizosaccharomyces specific protein, uncharacterized
(3 rows)

pombase-build-2017-12-11
 count |                            name
-------+-------------------------------------------------------------
   418 | conserved unknown
   123 | Schizosaccharomyces pombe specific protein, uncharacterized
   172 | Schizosaccharomyces specific protein, uncharacterized
(3 rows)

**Comment by kimrutherford** [comment]
I've added four files with the IDs to Dropbox in:

Dropbox/pombase/Chado/queries/unknowns_paper/

Let me know if that's what you meant.

**Comment by ValWood** [comment]
will look tomorrow

**Comment by ValWood** [comment]
Yup, perfect. I think I'll use 2016 compared 2018...tat seems to work  quite well.

Thanks

Val
