### ISSUE TITLE
current F-P inferences gaf

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#659]
where are we getting this file from currently?

here?
http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/gene_association.pombase.inf.gaf

https://curation.pombase.org/pombe/stats/annotation

**Comment by ValWood** [comment]
Once we have established if we are getting the file from the correct place, can we check if we still see this drop in numbers? This was the original issue.

@mah11 
That said, there is still a problem with inf.gaf - it's still a lot smaller than the one I get running owltools (Jenkins) GAF checks locally, a la geneontology/go-annotation#1336

**Comment by kimrutherford** [comment]
We're getting it from here:
http://build.berkeleybop.org/job/gaf-check-pombase/lastSuccessfulBuild/artifact/gene_association.pombase.inf.gaf

I don't know if it's the right one.  I'm very confused by it all.  That file is updated daily which I guess is a good sign.

**Comment by ValWood** [comment]
So I don't think we are getting the inferred gaf from the above location.
I did a spot check.

we don't get these annotations:
PomBase	SPCC663.12	cid12		GO:0000775	PMID:25274039	IMP		C	poly(A) polymerase Cid12	csp10|csp8	protein	taxon:4896	20141110	GOC		
PomBase	SPCC663.12	cid12		GO:0034507	PMID:25274039	IMP		C	poly(A) polymerase Cid12	csp10|csp8	protein	taxon:4896	20141110	GOC		

but we do get this one:

PomBase	SPCC737.09c	hmt1		GO:0071994	PMID:7876244	IMP		P	vacuolar phytochelatin transmembrane transporter Hmt1	SPCC74.08c	protein	taxon:4896	20120531	GOC	

odd?

**Comment by ValWood** [comment]
The one I pointed to is also updated.
!gaf-version: 2.0
! 
! Date: 2018/01/22

I don't know what the difference is  between these 2 files.

So we will work on the assumption that the one you are using is the correct  one.  Midori does this file still show reduced numbers?

I will do some spot checks on this one.

**Comment by ValWood** [comment]
OK both of these files are the same.

**Comment by ValWood** [comment]
I will list any problems  I find with the file here. I don't thhink this file is built from current data.

It contains this annotation:

PomBase	SPCC74.06	mak3		GO:0034599	PMID:20919928	IC	GO:0032874	P

this must be generated from an MF IC annotatiin, but as far as I can see pombe mak3 does not  have any IC annotation ( I checked in artemis to be sure that it is not filtered)

**Comment by ValWood** [comment]
Does anyone understand this row:
this is a process ID, but in the aspect column it has F, for function
How does the loader handle that?


PomBase	SPBC2F12.13	klp5		GO:1990758	PMID:21664573	IC	GO:0005515	F	kinesin-8 family plus-end microtubule motor Klp5	sot1	protein	taxon:4896	20161018	GOC-OWL	part_of(GO:1990758)

**Comment by mah11** [comment]
also see https://github.com/geneontology/go-site/issues/524. it's a ghastly mess.

**Comment by kimrutherford** [comment]
I'm confused again.  Is this the right file?:
  http://build.berkeleybop.org/job/gaf-check-pombase/lastSuccessfulBuild/artifact/gene_association.pombase.inf.gaf

In https://github.com/geneontology/go-site/issues/524#issuecomment-362797873 you mention a new location.  I thought the URL we're using _is_ the new location.  Is there a new new location?

**Comment by kimrutherford** [comment]
> Is there a new new location?

I've read the GO issue more carefully now.  Is this the new new location?:
http://snapshot.geneontology.org/annotations/pombase-prediction.gaf

I compared that file with the one we're using.  They are very similar except that column 9 ("Aspect") is different.  That's alarming.  Although it shouldn't cause problems for PomBase as we ignore that column.

Here's an example:

gene_association.pombase.inf.gaf:

    PomBase  SPAC1006.07  tif1  GO:0006412  PMID:10462529  IMP  P  translation init...

pombase-prediction.gaf:

    PomBase  SPAC1006.07  tif1  GO:0006412  PMID:10462529  IMP  C  translation init...

The only other different between the two files is that gene_association.pombase.inf.gaf has one extra annotation:

    PomBase  SPBC18H10.16  can1  GO:1903826  PMID:18357653  IMP  X  plasma membrane arginine/lysine transmembrane

**Comment by ValWood** [comment]
Don't worry yet,  if we don't include the file I don't think we will lose so much.
We can wait until resolved....

I'll check the file contents when I get the go ahead. There appears to still be a problem.

**Comment by mah11** [comment]
>  I've read the GO issue more carefully now. Is this the new new location?:
> http://snapshot.geneontology.org/annotations/pombase-prediction.gaf

Yes, this is the new new location, and what GO is now billing as the correct one. The billing is still fairly subtle, and Tanya-at-TAIR has asked them to make an announcement when they've got the bugs fixed. Oh yeah, as your snippet shows, they haven't fixed all the bugs yet, so as Val says, no rush.

**Comment by ValWood** [comment]
@kimrutherford  are we loading any of the  process-from function prediction gafs?
I didn't think we were, but we are definitely getting them from somewhere...

because I see some in here:
http://curation.pombase.org/dumps/latest_build/logs/log.2018-02-25-20-00-50.excluded_go_terms_softcheck

SPAC21E11.06.1		GO:0065009	regulation of molecular function		GOC
SPAC24H6.09.1		GO:0065009	regulation of molecular function		GOC
SPAC343.14c.1		GO:0065009	regulation of molecular function		GOC
SPAC4D7.09.1		GO:0065009	regulation of molecular function		GOC
SPBC19G7.08c.1		GO:0065009	regulation of molecular function		GOC

it's not a big deal,  because they will be  subject to our normal filtering I was just wondering where we get them from (probably from the GOA file?)

**Comment by ValWood** [comment]
I see it in goa so I think that's it. can you confirm.

**Comment by kimrutherford** [comment]
We load:
  http://build.berkeleybop.org/job/gaf-check-pombase/lastSuccessfulBuild/artifact/gene_association.pombase.inf.gaf

I haven't changed the loader to use the new location yet:
  http://snapshot.geneontology.org/annotations/pombase-prediction.gaf

But the two files are nearly identical.

The annotations you list in your comment are in gene_association.pombase.inf.gaf

**Comment by ValWood** [comment]
Yep the new file looks much better now, but we'll wait to switch. I'd still like to see better redundancy filtering (because it is difficult for us to discard experimental annotations, even when less specific than ours from the same source), but we get
rid of most ... after our various filtering we only retain  64 annotations, total....

**Comment by kimrutherford** [comment]
I've change the load script to get the inferred GAF file from the new location: http://snapshot.geneontology.org/products/annotations/pombase-prediction.gaf

**Comment by ValWood** [comment]
Ok when the issues are solved with the "occurs in" we can reassess whether to import the component annotations too.

phew...

(I'll check tomorrow though anyway)

**Comment by kimrutherford** [comment]
Can this be closed now?

**Comment by ValWood** [comment]
I think so....
