### ISSUE TITLE
duplicate GO physical interaction data

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#660]
I noticed that taz1 has a number of apparently exact duplicate protein binding annotations:

![taz1 duplicates](https://user-images.githubusercontent.com/7359272/36075252-35320998-0f44-11e8-93bf-6eee10c9f8ec.jpg)

**Comment by ValWood** [comment]
atg11, rap1, rif1

**Comment by kimrutherford** [comment]
Looks like they come from the with... annotations.  We need to add a check that we don't add the same protein binding + with annotations.

**Comment by kimrutherford** [comment]
I've added a new Chado check that reports duplicates.  It should appear in:
  http://curation.pombase.org/dumps/latest_build/logs/log.2018-03-yadda,yadda,yadda.chado_checks
in the morning.

**Comment by kimrutherford** [comment]
> I've added a new Chado check that reports duplicates.

Is this useful?:
http://curation.pombase.org/dumps/builds/pombase-build-2018-03-13/logs/log.2018-03-13-01-20-24.chado_checks

**Comment by kimrutherford** [comment]
I forgot to constrain the query to report just the protein binding annotation duplicates so there are a couple of other terms.  eg. "SAGA complex" and "endosome".  If those are useful warnings I'll rename the query.  Currently it's called "duplicate_protein_binding_annotation".

**Comment by ValWood** [comment]
Yes, I think mainly the duplicate annotations are those where the paper is curated by PomBAse, and then by Intact or UniProt(KB). So we have duplicate protein binding annotations. I mentioned this on the GO tracker at some point.

We can filter external duplicates...

**Comment by kimrutherford** [comment]
> I've added a new Chado check that reports duplicates.

All the warnings now also appear in the query added by  #324 so I've removed the binding only query.
