### ISSUE TITLE
Promoters not found when loading Canto annotation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#661]
I noticed messages like this in the logs:

warning in fc9305f756e323a2: in extension for PomBase-genotype-252, can't find feature with identifier: SPBC32C12.02-promoter - can't find feature for: SPBC32C12.02-promoter

That promoter is in Chado so this is a bug.

**Comment by ValWood** [comment]
I think this is OK for now, they might be in chado  but  I think we don't have coordinates for them but we wanted to refer to them.
So this is just "waiting" until we have "features" that we can link to.
I may have remembered this incorrectly, but it's something like that...

**Comment by kimrutherford** [comment]
Turns out that this had an easy fix.  The code was only allowing gene IDs in extensions.  I've changed it to allow promoters.  I'll check the log tomorrow.

**Comment by kimrutherford** [comment]
Fixed!
