### ISSUE TITLE
Failing to parse PubMed XML for PMID:29352077 - load failing

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#663]
The XML for new entry PMID:29352077 has differences from all the other pombe PubMed XML.  One is causing nonsense to be stored in Chado for the abstract and the other causes the load to fail.

Both the abstract and the title in the XML now have an embedded HTML tag to make Schizosaccharomyces pombe italicised:

    <i>Schizosaccharomyces pombe</i>

That's great, except that no other PubMed entries do that and it causes the XML parser to parse them differently and my Perl code to blow up.

**Comment by ValWood** [comment]
How annoying !

**Comment by kimrutherford** [comment]
I've made a dodgy fix: the XML loading code now strips out anything that looks like an HTML italics tag before attempting to parse the PubMed XML.  It works for me locally so hopefully tomorrow night's Chado load will be OK.

**Comment by kimrutherford** [comment]
After a dodgy fix for the dodgy fix, it seems OK now.
