### ISSUE TITLE
heads up new gaf

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#664]
I added a gaf with some gap filling IC annotations.
external_data/external-go-data/GO-0070647_gap_filling.gaf.txt

itd's checked in, i hope it loads OK

**Comment by kimrutherford** [comment]
> i hope it loads OK

It had old Mac line ending instead of new style Mac line endings.  Macs are annoying like that.  I checked in a fix for that and the file will be in tomorrow night's load.

**Comment by kimrutherford** [comment]
> file will be in tomorrow night's load.

I fixed the file but forgot to add it to the load script.  I've done that now so the new file will be in tonight's load.

(change: pombase/pombase-legacy@44f63a978181a4bdf9ea12e6a3a )

**Comment by ValWood** [comment]
all worked OK
