### ISSUE TITLE
write out 8 column file for HCOP/HGNC

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#665]
Systematic  ID,
Gene Standard Name,
Product,
Chromosome
NCBI Gene ID N/A (i don't think we have it)
UniProt ID
Ensembl gene ID
Feature type (protein)

cheers

Val

**Comment by kimrutherford** [comment]
> NCBI Gene ID N/A (i don't think we have it)

Yep, we don't have that.

> Ensembl gene ID

We don't have those IDs either.

**Comment by ValWood** [comment]
It's the same as the PomBase  gene ID, I made sure of that!

**Comment by kimrutherford** [comment]
> It's the same as the PomBase gene ID, I made sure of that!

Do we need to include that column then?

**Comment by kimrutherford** [comment]
> I'll send a link to the file tomorrow.

The load has finished.

The file from the nightly load is here:
  http://curation.pombase.org/dumps/latest_build/misc/all_ids.tsv

The columns are:

 - systematic ID
 - name
 - chromosome name/ID
 - gene product
 - UniProt ID
 - feature type
 - synonyms (comma separated)

The "feature type" is currently "mRNA gene" for protein coding gene.  I'll fix that to be more SO compliant.

The file should get copied here each night but there is an issue with the Babraham firewall (it doesn't like oliver1):
   ftp://ftp.pombase.org/nightly_update/misc/
Once the firewall config is updated, I'll copy this to the FTP site and let you know.

**Comment by kimrutherford** [comment]
> chromosome name/ID

I've just realised that I need to change the chromosome names from "chromosome_2" to "II" etc.

**Comment by ValWood** [comment]
maybe we should also include 
database ID PomBase:SPAC1002.01
it seems people are confused that the  PomBase database identifier and the systematic Identifier are the same thing (and to be fair there are so many label types locus tag, symbol, standard name etc etc.)

**Comment by kimrutherford** [comment]
> maybe we should also include database ID

It's easy enough to change.  Shall I go ahead?

**Comment by ValWood** [comment]
I guess so.

I'll provide the file to them now anyways....

**Comment by ValWood** [comment]
are we going to change "mRNA gene " to protein?

**Comment by kimrutherford** [comment]
I've changed "mRNA gene" to "protein coding gene" for tomorrow's update.

**Comment by kimrutherford** [comment]
> I've changed "mRNA gene" to "protein coding gene" for tomorrow's update.

That change is done and the file is now on the FTP site:
ftp://ftp.pombase.org/nightly_update/misc/all_ids.tsv

> maybe we should also include
> database ID PomBase:SPAC1002.01

I forgot to do that.  Were you thinking that we should have a separate "Database ID" column or should we put "PomBase:" in front of the systematic IDs in the first column of the file?

**Comment by ValWood** [comment]
I think we should have the redundancy of both columns. This will make it very clear that  SPAC1002.01 is  both a systematic identifier and a database identifier. This isn't the same for any other MOD.

**Comment by kimrutherford** [comment]
> I think we should have the redundancy of both columns.

OK, I've changed it to look like for tomorrow's load:

    SPAC1002.01  PomBase:SPAC1002.01  mrx11  chromosome_1  mitochondrial expression ...

Let me know if you think the column order needs to change.

**Comment by ValWood** [comment]
I think it will be fine.

Val

**Comment by kimrutherford** [comment]
> I think it will be fine.

Great.  It will be ready in the morning.

**Comment by kimrutherford** [comment]
The "PomBase:SPAC1002.01" style IDs are now in the nightly update:
ftp://ftp.pombase.org/nightly_update/misc/all_ids.tsv

Is there anything else that needs to be done here?

**Comment by ValWood** [comment]
nope done.

Val
