### ISSUE TITLE
heads up another new GAF

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#666]
signalling GAPS
external-go-data/GO-0023052_gap_filling.gaf.txt

(It might have control characters, could you check?)

**Comment by ValWood** [comment]
could you have a look at this? I don't think it will load if I left control characters (if you remind me of the one liner I can fix next time)

**Comment by ValWood** [comment]
Thanks. Embarrassingly I made the file in xcel.  Shhhh......

In my defence I use vi as a c-line editor...

**Comment by kimrutherford** [comment]
> external-go-data/GO-0023052_gap_filling.gaf.txt

It loaded without error.

**Comment by ValWood** [comment]
hmm that's odd, the signalling total didn't change...

**Comment by kimrutherford** [comment]
According to the log:
http://curation.pombase.org/dumps/builds/pombase-build-2018-02-28/logs/log.2018-02-28-20-00-49.gaf-load-output
the NAS total went up by the right amount.

It went from:

    3510 | Non-traceable Author Statement

to:

    3577 | Non-traceable Author Statement

I'll have a look at what the filtering is doing.

**Comment by ValWood** [comment]
here is one example,
http://pombase-dev.bioinformatics.nz/gene/SPAC1556.03

no "signalling" annotation.

v

**Comment by kimrutherford** [comment]
> here is one example, http://pombase-dev.bioinformatics.nz/gene/SPAC1556.03

I think the GO ID and with columns might be mixed up in the GAF file.  SPAC1556.03 has this annotation:

    GO:0070647  protein modification by small protein conjugation or removal  NAS  with signaling  GO_REF:0000051  249

"with signalling"

**Comment by ValWood** [comment]
Oh bummer, I know what I did now.
Shoot. I copied a previous file and   forgot it had a with column. I assumed the GO ID was column 5 and   replaced it with the intended one.

Bummer....don't load the file. I'll sort it tomorrow.

**Comment by ValWood** [comment]
perl -pi -e 's/GO:0023052/\t/g' GO-0023052_gap_filling.gaf.txt 
perl -pi -e 's/GO:0070647/GO:0023052/g' GO-0023052_gap_filling.gaf.txt 

which is what I intended.

Did I do that correctly  (did I need to replace the with filed entry by  a tab or will tat insert an extra column/)

I committed it anyway....

**Comment by kimrutherford** [comment]
> perl -pi -e 's/GO:0023052/\t/g' GO-0023052_gap_filling.gaf.txt

That added an unneeded tab.  It just needs to be:

    perl -pi -e 's/GO:0023052/\t/g' GO-0023052_gap_filling.gaf.txt

I've removed the extra tabs and checked it in.  I've also restarted the nightly load.  It will still finish before morning.

**Comment by ValWood** [comment]
Thank you!

**Comment by kimrutherford** [comment]
Looks like it worked:
  https://www.pombase.org/gene/SPAC1556.03

**Comment by ValWood** [comment]
yep all good!
