### ISSUE TITLE
allow ~ preceding percentage for penetrance

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#667]
I thought we already allowed this. I quite often precede a penetrance with "~"
because its quite difficult to record penetrance  from the histograms presented  without estimating ....

http://curation.pombase.org/dumps/latest_build/logs/log.2018-02-28-20-00-49.curation-tool-data-load-output

**Comment by ValWood** [comment]
![and this](https://user-images.githubusercontent.com/7359272/36868782-52776ace-1d91-11e8-8f6a-a7794897045f.jpg)
![like this](https://user-images.githubusercontent.com/7359272/36868786-54a034de-1d91-11e8-8ddc-164c7dedc366.jpg)

**Comment by ValWood** [comment]
We can ask the authors for precise %'s to replace but  without a ruler  of a lot of faffing it's difficult to get exact... I do a lot of these in chromosome segregation scenarios.

**Comment by ValWood** [comment]
I don't think my estimates are bad but  I don't use a ruler...

**Comment by kimrutherford** [comment]
> I thought we already allowed this. I quite often precede a penetrance with "~"

We currently only allow penetrance values like "50%", ">50%", "<50%" or ranges "30.5%-50.5%"

I've just change the code to allow a "~" in front of a percentage ("~50%").  Do you we need to allow approximate ranges too?  What about "<~50%"?

**Comment by ValWood** [comment]
We could allow than all. 
I have used approximate ranges!
I haven't used What about "<~50%" but it could b e useful. If authors want to refine, that's good...

**Comment by kimrutherford** [comment]
> We could allow than all.

OK, I've made that change too.

**Comment by kimrutherford** [comment]
I've just restarted the nightly load so the penetrance parsing changes should be fixed tomorrow.

**Comment by kimrutherford** [comment]
The warnings are gone and the approximate percentages are on the gene pages now: https://www.pombase.org/gene/SPBC13E7.06
