### ISSUE TITLE
making full literature collection visible

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#67]
Could load  firstly all 
i) reviews
and ii) methods papers

and make avaiable in Pombase
(later will need to sort by review topics)

Original comment by: ValWood

**Comment by ValWood** [comment]
replaced by
https://github.com/pombase/website/issues/27

**Comment by mah11** [comment]
If this ticket has been closed, does that mean the literature data are all in Chado now? (If not, the ticket should probably be open, because the website ticket requires, and doesn't replace, the chado-loading part of the big picture.)

**Comment by ValWood** [comment]
You are right we still need this ticket.
Was just chatting with Kim, and need to check that some other data is loaded (journal etc)

Elsevier need list of journals so they can flag the  ones of theirs which we curate are requiring PomBase links.

**Comment by kimrutherford** [comment]
> Briefly, we want PomBase to offer a web page for each pombe paper

That bit is done.

**Comment by mah11** [comment]
all papers have publication pages and this ticket is old, so closing
