### ISSUE TITLE
extensions on protein binding annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#672]
All extensions on protein binding annotations, except for " has_substrate" should also be represented on reciprocal annotations.

Here's an example:
tts1
https://www.pombase.org/gene/SPBC1539.04
binds yop1  part of endoplasmic reticulum tubular network membrane organization in equatorial cell cortex

on the yop1 page
binds tts1 | IPI | Zhang D et al. (2010)

**Comment by ValWood** [comment]
session
curs/c166fc9a9dd60e8d/ro/

**Comment by kimrutherford** [comment]
I'd like to have a chat about this at some point.

**Comment by ValWood** [comment]
yep, not super urgent...

**Comment by ValWood** [comment]
now the yop1 protein binding annotation is not showing at all, when I created this ticket it was present in duplicate)

**Comment by ValWood** [comment]
question 1
why does the tts1 annotation not get reciprocated (this might be because it has an extension?)

**Comment by ValWood** [comment]
yucky

**Comment by kimrutherford** [comment]
I think I've fixed this.  The change went in before the nightly load started so we should be able to check in the morning.

**Comment by ValWood** [comment]
yop1
has no binding annotation
http://pombase-dev.bioinformatics.nz/gene/SPCC830.08c

**Comment by kimrutherford** [comment]
> The change went in before the nightly load started so we should be able to check in the morning.

It didn't work on Friday night due to a typo, but it seems OK now.  The www.pombase.org is updated with the fix: https://www.pombase.org/gene/SPCC830.08c

**Comment by ValWood** [comment]
Wonderful.

Nice additional detail to provide the process extensions on the binding partner

yop1 is now much more informative, and we probably have LOTs of  part of and during on one binding partner..... should add lots of useful detail to gene pages.
