### ISSUE TITLE
query about number difference on stats page

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#674]
number difference https://curation.pombase.org/pombe/stats/annotation

Canto curator summary
table says

Totals: publications community  540

Community annotation response rate says
618 are finished and are either in the main PomBase database or are currently being checked by the PomBase curators. 

that's quite a big difference?

**Comment by kimrutherford** [comment]
The community curator rate (618) is a bit of a slack query.  It includes sessions like this one that were at some point assigned to a community curator:
 http://curation.pombase.org/pombe/view/object/curs/2102?model=track

The publications community (540) number includes only those sessions that still assigned to a community member when approved.  

Sorry about that.  I'll fix the community curator rate query.  Unfortunately that's going to change the response rate numbers.

**Comment by kimrutherford** [comment]
It changes to:

To date 1311 publications have been assigned to community members for curation. 546 are finished and are either in the main PomBase database or are currently being checked by the PomBase curators. That's a response rate of 41.6%

**Comment by kimrutherford** [comment]
> I'll fix the community curator rate query. 

I've made the change and it's now live.

**Comment by ValWood** [comment]
bummer ;(
oh well ......

we shouldn't take sessions back from the community unless absolutely necessary....
because we will never recover that into the response rate, and the person did not get chance to curate.....

**Comment by Antonialock** [comment]
>  the person did not get chance to curate.....

this sounds overly dramatic. The person did get a chance to curate but decided not to take it? 

If I "steal" a session from a community curator, they will typically have had the session sent to them at least twice (and if they haven't had the reminder I often send it) so they have had TWO chances to curate. The only reason I'd be looking at  the paper is because it is of particular interest to get the paper curated (probably something tracker related) and if the community curator hasn't acted on multiple chances to curate (often over the span of a couple of years) then they will probably not jump at it any time soon.

**Comment by ValWood** [comment]
I'm a drama queen !

Well as long as they aren't recent papers. We shouldn't be taking anything from the last few years. I still think a lot of these will be curated in the next push. I have avoided sending out reminders to people who are not already curating  until after the genotype interface changes, and lots of people have told me they will do it  "soon"

You can flag in the curation  tickets that a paper is out for community curation, and close it (or ut it to pending).
Of course there will be the odd case where we really do want to get the curation in to fill pathway gaps (I did the endosulphine/greatwall paper for this reason), but they should be relatively rare.

If you have done any which are recent and haven't really had reminders, you can  remove the community curator entirely (this might not be possible after  curation, but I have deleted the session and created a new one on the one or two occasions that I did this).

I don't want   to give people we will curate their papers any time soon if they don't do them ;)
