### ISSUE TITLE
stats page, Community annotation response rate

### ISSUE THREAD

**Issue by Antonialock** [pombase/pombase-chado#675]
can report "overall" + yearly break down, so that we see how the response rate is improving over time?

**Comment by Antonialock** [comment]
#674

**Comment by ValWood** [comment]
yes I would like to see this too....

It might even be in another ticket.... 
I remember drawing a sketch  of what I thought the graph would look like....

**Comment by ValWood** [comment]
duplicate
https://github.com/pombase/pombase-chado/issues/651
