### ISSUE TITLE
stats page, white space needed

### ISSUE THREAD

**Issue by Antonialock** [pombase/pombase-chado#676]
just a little bit of space needed here to make it look nicer

![screen shot 2018-03-20 at 08 51 58](https://user-images.githubusercontent.com/12727506/37644542-11e9c01c-2c1c-11e8-9498-191c5fac15b8.png)

**Comment by Antonialock** [comment]
(between "criteria for" and "Average genes per publication")

**Comment by kimrutherford** [comment]
I've added a bit of whitespace.
