### ISSUE TITLE
stats odd numbers

### ISSUE THREAD

**Issue by Antonialock** [pombase/pombase-chado#677]
Something weird is going on in the curation attribution graph.

eg. in the table
2017
curator: 204
community: 100

but in the graph
curator: 12
community: 65

**Comment by kimrutherford** [comment]
I think that's because the table in the "Canto curator summary" section has the counts for the year the paper was curated and the graph shows the year the paper was published.

**Comment by Antonialock** [comment]
ahh ok. 

maybe we need an additional cumulative graph for amount of papers published + community curated + staff curated?

**Comment by Antonialock** [comment]
it can go in the  Canto curator summary section

**Comment by ValWood** [comment]
@Antonialock please open a new ticket with "stats" & "low priority" label describing  new graph required.

**Comment by Antonialock** [comment]
ah it's ok, I'll open a ticket if I need it for anything
