### ISSUE TITLE
need to check we are using the most up to date  version of PSI-MOD

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#679]
From Kim in e-mail
The OBO foundry links to:
   https://raw.githubusercontent.com/MICommunity/psidev/master/psi/mod/data/PSI-MOD.obo
which is from 2014.

I can't remember if we  sorted this....

**Comment by ValWood** [comment]
It doesn't really change much so it might be OK?

**Comment by kimrutherford** [comment]
> It doesn't really change much so it might be OK?

I'm doing a test load now on my desktop.

Needed a slight tweak to allow it to load: https://github.com/HUPO-PSI/psi-mod-CV/pull/19

**Comment by kimrutherford** [comment]
> I'm doing a test load now on my desktop.

The latest PSI-MOD.obo loads fine so I'll add to the main Chado load for tonight.

**Comment by ValWood** [comment]
Great. All that for ONE modification. Nobody can say  we aren't comprehensive :)
