### ISSUE TITLE
PAINT data imported

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#680]
We  are now importing PAINT data. Presumably this has come in via GOA.

The good news is that it doesn't look too bad so we can keep them.
I think at present IBA must be the last evidence code in the filtering pipeline because after filtering there are only 69 IBAs to check. I will check these today, then we can prioritise IBA over IEA.

BUT, I want to check, because I did not expect the number to be so low. So @kimrutherford  how many PAINT (IBA) annotations do we have pre-filtering? Maybe they are not all included in UniProt/GOA, or maybe UniProt  do some pre-filtering of their own.

It's odd that there seem to be less to check  than I  already know are problematic......

**Comment by ValWood** [comment]
@pgaudet this will make you happy. PAINT import happened accidentally via GOA  an it looks good!

**Comment by pgaudet** [comment]
Great !! 
I must say
I am not clear at all with the pipeline. I would also like to see some stats about how many annotations make it, compared to how many annotations we have in the PAINT database, for example, to make sure all is OK. 

@huaiyumi

**Comment by ValWood** [comment]
I'm going to do some checking.....

**Comment by kimrutherford** [comment]
> So @kimrutherford how many PAINT (IBA) annotations do we have pre-filtering?

So the number of IBA evidence codes from GOA?  Here are the counts for all the codes from GOA for pombe:

        1 IKR
        5 IRD
       28 IEP
      420 TAS
      573 EXP
      740 NAS
      836 IGI
     1239 ISM
     1257 IC
     1535 HMP
     1604 ISS
     2116 ND
     3437 IPI
     4519 IMP
     5254 ISO
     6933 HDA
     7034 IDA
     8196 IBA
    37506 IEA

**Comment by ValWood** [comment]
OK, I don't believe we filter down to 69. This would imply that all of these were covered by existing annotation. I doubt it. I wonder if some are not loading form other reasons. I started to check the logs to see if there was anything in there (there isn't) but I'm still sidetracked fixing things in here .........

 How strange. I can check by looking at some of my  tickets on the annotation tracker
https://github.com/geneontology/go-annotation/issues?q=is%3Aopen+is%3Aissue+author%3AValWood+label%3A%22PAINT+annotation%22

**Comment by kimrutherford** [comment]
> OK, I don't believe we filter down to 69.

I think I understand this now.  When we load from the GOA GAF we only load annotation assigned by InterPro or UniProt.  It looks like all the IBA annotations in the GOA GAF are assigned by GO_Central.  Almost all the GO_Central annotations are IBA:

        5 IRD
     8196 IBA

I think the 69 IBA annotations we do have are from the inferred GAF file: pombase-prediction.gaf - there are 619 IBA annotation from that file before filtering.

**Comment by ValWood** [comment]
OK that makes sense! 

OK I will check these 69 today from the F-P inferred GAF today...
(I really think these should have a different evidence code!)

 We will  still not load the GO_Central PAINT annotation quite yet. I want to make sure the problems I know about are filtered first. Not so much checking to do then!

**Comment by kimrutherford** [comment]
> We will still not load the GO_Central PAINT annotation quite yet.

OK.  Let me know when you'd like me to do a test load including the extra annotation.

**Comment by ValWood** [comment]
nothing to do here, these as will go away.
