### ISSUE TITLE
erroro in logs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#681]
https://curation.pombase.org/dumps/latest_build/logs/log.2018-05-24-22-57-12.manual-1-1-orths-output

can't find feature in Chado for SPAC1D4.09

the gene is SPAC1D4.09c

but I don't know where SPAC1D4.09 has been used?

**Comment by kimrutherford** [comment]
It's in pombe-embl/orthologs/conserved_one_to_one.txt:

    SPAC1D4.09    RTF2

**Comment by ValWood** [comment]
wow OK, that must be a new error check! I haven't edited that file for ages? (or I forgot!)

**Comment by ValWood** [comment]
fixed. I clearly had changed it recently, it was the first line!
