### ISSUE TITLE
problem PHAF file PMID:21561865

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#682]
https://curation.pombase.org/dumps/latest_build/logs/log.2018-05-24-22-57-12.phenotypes_from_PMID_21561865_phaf

**Comment by ValWood** [comment]
PMID:21561865

**Comment by kimrutherford** [comment]
The PHAF loader doesn't handle "residue(S423)" in extensions.  Let me know how urgent it is to fix that.

**Comment by ValWood** [comment]
not hugely urgent, it was curated by Pombase staff, not community
https://www.pombase.org/reference/PMID:21561865
and it's only ~200 annotations. So just when you get to it.

Right now, go to bed ;)

**Comment by ValWood** [comment]
Q should we allow this as an option on some phenotype terms in canto too?
or have I misunderstood what it is?

**Comment by mah11** [comment]
I did the Canto configuration for these extensions last month when I curated the paper (admin-only at present).

**Comment by ValWood** [comment]
I'm using this in Canto a lot...how did we manage without it?

![residue](https://user-images.githubusercontent.com/7359272/42382583-a69c96ca-812c-11e8-800b-6fb2b99e3df2.jpg)


I have a question, do we have special syntax for the CDT repeat residues (see bottom one above).
I'm sure we discussed it, but I can't remember.....

**Comment by ValWood** [comment]
found it https://www.pombase.org/gene/SPBC28F2.12

CDT_S2

**Comment by mah11** [comment]
> syntax for the CDT repeat residues

https://github.com/pombase/curation/issues/139

**Comment by kimrutherford** [comment]
> The PHAF loader doesn't handle "residue(S423)" in extensions.

I've fixed the loader to handle that.  The results will be available on Friday.  In the meantime I'm running a Chado load locally to check for problems.

**Comment by kimrutherford** [comment]
I think this is done, but while checking I noticed the residue column is missing: #943

**Comment by kimrutherford** [comment]
> #943

That was a typo.  It's: pombase/website#943
