### ISSUE TITLE
cant see existing annotation ( artemis derived)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#684]
in
https://curation.pombase.org/pombe/curs/b9099784b5cb5119
I can see

rrn3 | GO:0001169 | transcription factor activity, RNA polymerase I CORE element sequence-specific binding

this term still exists (although I think it is moving, or going
https://www.ebi.ac.uk/QuickGO/term/GO:0001169

but it doesn't appear on the gene page?
https://www.pombase.org/gene/SPAC18G6.11c

**Comment by ValWood** [comment]
These annotation need removing from Artemis as I am curating in Canto so assign to me when resolved....

**Comment by kimrutherford** [comment]
Fixed.  Sorry about that.  It's been a week or two since I updated Canto to point the a new Chado update so it was seeing old data.

**Comment by ValWood** [comment]
Ah that explains a lot!

I have been reannotating quite a lot of stuff for the transcription overhaul. I thought GO was the hold up.
For the rest of this week, could you update daily, I will try to get all of the transcription reannotation finished...... After that it becomes less important again.
