### ISSUE TITLE
export a list of the GO slim term IDs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#685]
put it somewhere where we could link to it from here
~/fission-yeast-go-slim-terms

**Comment by kimrutherford** [comment]
So just a file with the IDs from this page?:
https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms

Should it have a column with the term names?

**Comment by ValWood** [comment]
Yes ID and term would be useful.

**Comment by ValWood** [comment]
very quick?

**Comment by kimrutherford** [comment]
I've made the changes to write the GO slim.  It also writes out the disease slim.

I'll check the nightly load in the morning.

**Comment by ValWood** [comment]
OK,

Can we add an FAQ "Can I access the term IDs used in the PomBAse GO slims"
and
a link from here:
https://www.pombase.org/datasets

**Comment by mah11** [comment]
Please open a website ticket for any FAQ change.

Closing because Kim has done the originally requested thing.
