### ISSUE TITLE
Task for unknowns paper

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#686]
How many of these:
697 | (subset: characterisation_status:conserved unknown OR subset: characterisation_status:S. pombe specific protein, uncharacterized OR subset: characterisation_status:Schizo. specific protein, uncharacterized)

Have BIOGRID  type  
a) IPI
b) IGI
data 
(Will only be from HTP, and I don't think many have any)

**Comment by kimrutherford** [comment]
> Have BIOGRID type
> a) IPI
> b) IGI

Do you need separate counts for each of protein and genetic interactions?

**Comment by ValWood** [comment]
You can lump them.  I don't think many will have any....

**Comment by kimrutherford** [comment]
>  I don't think many will have any....

I get 487 from that list with interactions from BioGRID?

**Comment by ValWood** [comment]
OK that's quite a lot. I will look at those..... could you attach the list?

**Comment by kimrutherford** [comment]
Here are the IDs:

https://www.dropbox.com/s/m35f69kqqyo3v3p/unknowns_with_biogrid_data_sysid_only.tsv?dl=0

and here are the IDs and gene names:

https://www.dropbox.com/s/jivqm1jsskf3o6i/unknowns_with_biogrid_data.tsv?dl=0

**Comment by ValWood** [comment]
OK I changed my mind. Could you do them in searate files. The genetic interactions are not so interesting. They are mainly from Colm's paper and they seem to be very heterogeneous mixture.

The physical interactions on the other hand look to be very promising.

Could you also split into   conserved unknownr (as I need these for the paper), and species specific. The species specific ones I can do later.

Cheers

Val

**Comment by ValWood** [comment]
can we exclude this data set from physical interactions, 

everybody is in here.....PMID:28218250

**Comment by kimrutherford** [comment]
> and species specific

Could you send me this list?

**Comment by ValWood** [comment]
Its (subset: characterisation_status_Schizosaccharomyces_pombe_specific_protein_uncharacterized OR subset: characterisation_status_Schizosaccharomyces_specific_protein_uncharacterized)

**Comment by ValWood** [comment]
[gene_list_species_specific.txt](https://github.com/pombase/pombase-chado/files/2243599/gene_list_species_specific.txt)

**Comment by kimrutherford** [comment]
> can we exclude this data set from physical interactions,
> everybody is in here.....PMID:28218250

It looks like there are no interactions from that publication that we load from BioGRID.

**Comment by kimrutherford** [comment]
I have made four files:

https://www.dropbox.com/sh/73s9vd1250jwdor/AAAzstbnx1oJ-QrYj4gTNoYia?dl=0

Is that what you needed?

**Comment by ValWood** [comment]
> It looks like there are no interactions from that publication that we load from BioGRID.

Hmm, let me check that. I saw loads.....

**Comment by ValWood** [comment]
there are lots of physical interactions 
https://www.pombase.org/reference/PMID:28218250
(Biogrid format)

**Comment by ValWood** [comment]
Great thanks. That's perfect. I'll look through these.

**Comment by kimrutherford** [comment]
> there are lots of physical interactions
> https://www.pombase.org/reference/PMID:28218250
> (Biogrid format)

In Chado all the interaction annotations from that publication have "PomBase" as the source.  I'll dig deeper.

**Comment by ValWood** [comment]
yes they might have com through PomBase. Sorry I wasn't clear. I meant "Biogrid section" interactions.

(We also curate physical interactions in GO, but these would be accompanied by detailed info so none of these would end up in the 'unknown' category.

**Comment by kimrutherford** [comment]
> I meant "Biogrid section" interactions.

The interaction section includes annotation that isn't from BioGRID.

For the queries do you want to include genes that have interactions that didn't come from BioGRID?  The queries I've been doing are only for interactions that have BioGRID as the source because you said "Have BIOGRID type ..." in the initial comment.

**Comment by ValWood** [comment]
Sorry I wasn't clear. Its everything in the physical/genetic interaction sections  (whoever curated by). Most of the large scale ones will be BioGRID though....

leaving out PMID:28218250

**Comment by kimrutherford** [comment]
I've updated the query results to include everything except PMID:28218250:
  https://www.dropbox.com/sh/73s9vd1250jwdor/AAAzstbnx1oJ-QrYj4gTNoYia?dl=0

**Comment by kimrutherford** [comment]
Do you have what you need here?

**Comment by ValWood** [comment]
Yes thanks,

Just to note for future.
I looked at these (for conserved only). They aren't informative. FOr axample over half of the 410  conserved unknowns show interactions with these 4 genes

430 | genetic_interactors_of: SPAC23D3.09 | ...
  | 516 | genetic_interactors_of: SPCC31H12.08c | ...
  | 101 | genetic_interactors_of: SPAC31A2.05c | ...
  | 493 | genetic_interactors_of: SPBC725.16

I'm convinced that what we see here  is just  some already sick cell that doesn't grow well anyway (but is just 'viable') with another  combination that just pushes it over the edge. The connections are to transcription, translation, splicing but I'm sure that the majority of these are not informative about functional connections. They can't be used as function predictors......
