### ISSUE TITLE
InterPro update

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#690]
There was an InterPRo release on  June 18th. Can we update?
https://www.ebi.ac.uk/interpro/release_notes.html

I found this by chance I don't know if there is any alerting ?

**Comment by kimrutherford** [comment]
I've started downloading the Interpro update.  It currently says it's going to take 25 hours.

**Comment by ValWood** [comment]
I wanted to see if the species-specific GPs has picked up new domains

I think they only have a release very 6 months or so .....so would be good to update... but 25 hours!

didn't we ask before about downloading subsets? I think rob Finn mentioned some new download methods they were thinking about?

**Comment by kimrutherford** [comment]
The download sped up and we now have a copy of the new XML file.

Unfortunately the XML format has changed slightly.  I need to fix the parser before I can update.

Note to self: 'unknown attribute name: model'

```rust
   7: pombase_domain_process::make_match
             at src/main.rs:260
   8: pombase_domain_process::parse
             at src/main.rs:305
```

**Comment by ValWood** [comment]
hmph...

**Comment by kimrutherford** [comment]
Some entries in the XML have a new attribute "model".  So we have `model="2bwnA02"` here:

```xml
<match id="G3DSA:3.40.640.10" name="G3DSA:3.40.640.10" dbname="CATHGENE3D"
       status="T" model="2bwnA02" evd="HMMPfam">
```

and `model="0046747"` here:

```xml
<match id="SSF53383" name="SSF53383" dbname="SSF" status="T"
       model="0046747" evd="HMMPfam">
```

I'll ignore the new attribute for now just so we can get the new file loaded.  We can add it to the gene pages if it's useful.

**Comment by ValWood** [comment]
OK, I'll find out what it means.

**Comment by kimrutherford** [comment]
> I'll ignore the new attribute for now just so we can get the new file loaded.

I made the code change so the new Interpro data should be visible in the morning.

**Comment by kimrutherford** [comment]
> I made the code change so the new Interpro data should be visible in the morning.

The load worked and the main site is updated with the latest data.  Let me know if you spot any problems.

**Comment by ValWood** [comment]
Great. Found cerevisiae  Lst4 ortholog!

**Comment by Antonialock** [comment]
The Attribute model is a red to the domain within a PDB model

https://www.rcsb.org/pdb/explore/macroMoleculeData.do?structureId=2BWN

-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by kimrutherford** [comment]
Thanks for checking.  We have links to the external database entries for domain on the gene page, so maybe it's not useful to display that reference?

**Comment by ValWood** [comment]
I don't think we need to do anything with that.....

**Comment by ValWood** [comment]
From Alex (M)

SUPERFAMILY and Gene3D are a bit different to our other member databases, as
they use a set of different HMMs to represent their entries (there is not a 1
entry to 1 HMM relationship). We have now added a link to the exact HMM that a
sequence hits for these entries, which is what the model attribute represents.
It is only used in SUPERFAMILY and Gene3D matches.

**Comment by ValWood** [comment]
we could add this link but it isn't really urgent
