### ISSUE TITLE
create downloadable FYPO viability summary file

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#691]
There is a file, FYPOviability.tsv, that contains the super-simple "is a deletion viable?" data for each gene. But it hasn't been updated in a long time, and that's sad.

So the task is to generate the file on a regular basis (whatever frequency is easiest to implement), and copy it over to FTP. It can go in the /nightly_update/ directory, but should also get copied to the stable location linked on pombase.org/downloads/phenotype-annotations - ftp_site/pombe/annotations/Phenotype_annotations/FYPOviability.tsv in pombe-embl svn.

The format is one of those really simple ones that we like so much:

col 1: systematic ID
col 2: one of: viable | inviable | condition-dependent
there is no column 3 ;)

Use the same criteria as for the viability summary on the gene pages (which will also be the same as the canned query, per https://github.com/pombase/website/issues/848).

As usual, holler if questions or problems crop up.

**Comment by kimrutherford** [comment]
I've changed the code to write the viability file.  I'll check that it's all OK tomorrow then make add it to the pombe-embl SVN repo.

Currently the file has a line for every gene.  If the viability status is unknown it says "unknown".  If you think that's useful, I'll leave it in.  If it's not useful I'll change the code before I add the file to SVN.

**Comment by kimrutherford** [comment]
The file is now in the nightly update directory:
  ftp://ftp.pombase.org/nightly_update/misc/FYPOviability.tsv

**Comment by kimrutherford** [comment]
I've changed the nightly script so that it updates FYPOviability.tsv in SVN.  I'll check on Wednesday morning.

**Comment by kimrutherford** [comment]
The file is now updated nightly in SVN and on the FTP site:
 ftp://ftp.pombase.org/pombe/annotations/Phenotype_annotations/FYPOviability.tsv
