### ISSUE TITLE
Load PAINT annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#695]
TASK: IMPORT PAINT ANNOTATION, wth lowest priority for redundancy filtering

**Comment by ValWood** [comment]
(The PANTHER ID should be the first in the list)

**Comment by ValWood** [comment]
maybe we could try loading the panther data while you are here. Although we have a lot to do so probably unlikely. Anyway I will remove "future" now.

**Comment by ValWood** [comment]
Hi Kim,

Could  you load the PAINT annotation on dev at some point  ( I only really need the  post filtering GO GAF with the PAINT data that we would retain). After that you can delete it  again. I don't want it to go on the live site yet.

Once I have the filtered list I will do some QC checking to see if  we are happy for it to go live.

**Comment by kimrutherford** [comment]
I'll give it a go.  It's easiest to do a Chado load on my desktop with the PAINT data so I don't need to mess with the main load.

Where is the GAF file for PAINT?  Is there a pombe-only file?

**Comment by ValWood** [comment]
It will just be the normal GAF that is exported. Hang on I missed some important information here. Although there did used to be a ticket with this in, I just can't find it.

Essentially, we want to load the PAINT data from the GO file  (we must presumably have a filter not to load at present?)

Then we want to make IBA  the lowest priority evidence code in the filter  (temporarily), this is just to give everything else precedence (Including IEA NAS, TAS which I believe are largely OK).
This will give me fewer to check.

I'm hoping that after the filters there will not be very much left, otherwise we have missed a lot of stuff that it would be possible to annotate by ISS. I have no idea really, it will be very interesting ;)

Does that make sense or do you need more info?

**Comment by kimrutherford** [comment]
> Essentially, we want to load the PAINT data from the GO file

Do you mean from the GOA/UniProt GAF file?  I can't see any annotation that looks like it's from PAINT.  What should I look for?

**Comment by ValWood** [comment]
Anthing with  the pombe taxon that we don't load currently should include it. I can't think of anything else that we don't load.

It will have "PANTHER" somewhere in the with file,  IBA evidence. I think the assignee is GOC...

**Comment by ValWood** [comment]
contributer is GO_Central

Also, I realise I did not answer the whole question.  Yes GOA/GAF. We will take them from there because it's easiert.

Can you see them?

**Comment by ValWood** [comment]
Like this

UniProtKB:A6X980 | sfc7 | part_of | GO:0000127    transcription factor TFIIIC complex | ECO:0000318   IBA | PMID:21873635 | PANTHER:PTN001474144 more... | 284812 Schizosaccharomyces pombe (strain 972 / ATCC 24843) | GO_Central

**Comment by mah11** [comment]
No, not the GOA/UniProt GAF; use the PomBase file that's been through the GO pipeline.

Get the file from http://snapshot.geneontology.org/annotations/pombase.gaf.gz (there's also a .gpad.gz) and grep for evidence IBA and/or assigned by GO_Central.

**Comment by ValWood** [comment]
Currently we use the Uniprot GAF for everything else, so this will be easier to test from (the differences  between the 2 sources should be small)

We can switch once I have done the bulk of the testing to mop up the residual stuff (if there is any). This is quick and dirty before we alter the pipelines (which we should do).

We would also need to  switch to get other GO derived stuff from GO (function process links which we also get currently from GOA)

Kim: We will always need to get the  InterPro and Uniprot from GOA (because we  filter a lot of stuff before Pombe data  goes into GO)

**Comment by ValWood** [comment]
> (which we  probably should do)

I'm hoping that in the long term there is no need for these inferences, so it might not be worth switching just for this. Although  I suspect we are a way off that with the IBA

**Comment by kimrutherford** [comment]
Thank you both.  Got it now.

I've just tried a quick test to make sure those annotations can be loaded.  It's mostly OK except for these lines where the systematic ID (P50525) looks like a UniProt ID instead of a pombe ID:
```
UniProtKB	P50525	apn1		GO:0003906	PMID:21873635	IBA	PANTHER:PTN000485019|SGD:S000001597|WB:WBGene00000151	F	DNA-(apurinic or apyrimidinic site) lyase 1	UniProtKB:P50525|PTN000485041	protein	taxon:284812	20170228	GO_Central		
UniProtKB	P50525	apn1		GO:0005634	PMID:21873635	IBA	PANTHER:PTN000485021|SGD:S000001597	C	DNA-(apurinic or apyrimidinic site) lyase 1	UniProtKB:P50525|PTN000485041	protein	taxon:284812	20170228	GO_Central		
UniProtKB	P50525	apn1		GO:0006284	PMID:21873635	IBA	PANTHER:PTN000485019|SGD:S000001597|WB:WBGene00000151	P	DNA-(apurinic or apyrimidinic site) lyase 1	UniProtKB:P50525|PTN000485041	protein	taxon:284812	20170228	GO_Central		
UniProtKB	P50525	apn1		GO:0005739	PMID:21873635	IBA	PANTHER:PTN000485021|SGD:S000001597	C	DNA-(apurinic or apyrimidinic site) lyase 1	UniProtKB:P50525|PTN000485041	protein	taxon:284812	20170228	GO_Central		
UniProtKB	P50525	apn1		GO:0008081	PMID:21873635	IBA	PANTHER:PTN000485019|SGD:S000001597|WB:WBGene00000151	F	DNA-(apurinic or apyrimidinic site) lyase 1	UniProtKB:P50525|PTN000485041	protein	taxon:284812	20170228	GO_Central		
```

Apart from those 5 lines, there are no other warnings.  Tomorrow I'll look more closely at what got loaded to check that it's OK.

In case it needs reporting, there are also these lines which also have a UniProt systematic ID but the pombe systematic ID is in column 3, so they load OK:
```
UniProtKB	Q9P3E3	SPAC750.08c		GO:0005739	PMID:21873635	IBA	PANTHER:PTN001157969|SGD:S000001512	C	NAD-dependent malic enzyme (Predicted), partial (Fragment)	UniProtKB:Q9P3E3|PTN002361248	protein	taxon:284812	20170228	GO_Central		
UniProtKB	Q9P3E3	SPAC750.08c		GO:0006108	PMID:21873635	IBA	FB:FBgn0002719|PANTHER:PTN000601050|PomBase:SPCC794.12c|TAIR:locus:2017854|TAIR:locus:2052045|TAIR:locus:2054085|TAIR:locus:2127038|TAIR:locus:2180547|TAIR:locus:2181980|UniProtKB:P48163|UniProtKB:Q16798	P	NAD-dependent malic enzyme (Predicted), partial (Fragment)	UniProtKB:Q9P3E3|PTN002361248	protein	taxon:284812	20170228	GO_Central		
UniProtKB	Q9P3E3	SPAC750.08c		GO:0004470	PMID:21873635	IBA	FB:FBgn0002719|MGI:MGI:97043|PANTHER:PTN000601050|PomBase:SPCC794.12c|RGD:3074|SGD:S000001512|TAIR:locus:2017854|TAIR:locus:2052045|TAIR:locus:2054085|TAIR:locus:2127038|TAIR:locus:2180547|TAIR:locus:2181980|UniProtKB:P23368|UniProtKB:P26616|UniProtKB:P48163|UniProtKB:Q16798	F	NAD-dependent malic enzyme (Predicted), partial (Fragment)	UniProtKB:Q9P3E3|PTN002361248	protein	taxon:284812	20170228	GO_Central		
UniProtKB	Q9P3E3	SPAC750.08c		GO:0004471	PMID:21873635	IBA	PANTHER:PTN001157969|PomBase:SPCC794.12c	F	NAD-dependent malic enzyme (Predicted), partial (Fragment)	UniProtKB:Q9P3E3|PTN002361248	protein	taxon:284812	20170228	GO_Central		
UniProtKB	Q9P3E3	SPAC750.08c		GO:0005829	PMID:21873635	IBA	PANTHER:PTN002361249|UniProtKB:P26616	C	NAD-dependent malic enzyme (Predicted), partial (Fragment)	UniProtKB:Q9P3E3|PTN002361248	protein	taxon:284812	20170228	GO_Central		
UniProtKB	Q9P3E3	SPAC750.08c		GO:0006090	PMID:21873635	IBA	PANTHER:PTN000601050|PomBase:SPCC794.12c|SGD:S000001512|UniProtKB:Q16798	P	NAD-dependent malic enzyme (Predicted), partial (Fragment)	UniProtKB:Q9P3E3|PTN002361248	protein	taxon:284812	20170228	GO_Central
```

**Comment by kimrutherford** [comment]
One thing that will need a code change is processing the "with" column (col 8).  There are lots of IDs in each field and the loader only knows how to store the first ID.  Should we store just the PANTHER ID from the with fields? 

Here's an example:
```
FB:FBgn0013674|PANTHER:PTN000046096|SGD:S000007260
```

**Comment by kimrutherford** [comment]
> There are lots of IDs in each field and the loader only knows how to store the first ID.

Sorry, that's not right.  The loader can store all the IDs and there's also an option to store just the first ID.

**Comment by ValWood** [comment]
For display we will need to do something to reduce this field (possibly only dispolaying the panther ID but letting people maybe see the others in mouse over, if that is possible). I don't think we will want to see these e long strings of IDs by default. 
But we can chat about that after the preliminary  clean up, there is no hurry (I won't be doing this quickly I suspect I will chug through them over a few Friday afternoons when I am braindead from curation session checking).

**Comment by kimrutherford** [comment]
> For display we will need to do something to reduce this field (possibly only dispolaying the
> panther ID but letting people maybe see the others in mouse over, if that is possible).

We can do that but I think initially it's easier to just store and display the PANTHER ID.  There's less code to change that way.  Displaying the other IDs can be a task for latter.

> But we can chat about that after the preliminary clean up, there is no hurry

I'm doing a test Chado load now on my Desktop.  Tomorrow you'll be able to see the initial results of loading the PANTHER annotations with all the usual annotation and filtering.

**Comment by kimrutherford** [comment]
> I'm doing a test Chado load now on my Desktop.

There are 5211 annotations from PAINT after loading everything and filtering.  The input file has 14560 PAINT annotations.

You can see the results on my desktop until 1pm or so.

Here's an example of a more specific PAINT term filtering an existing term:
original: https://www.pombase.org/gene/SPBC336.04
with PAINT: http://desktop.kmr.nz:4242/gene/SPBC336.04
("3'-5'-exodeoxyribonuclease" activity instead of "3'-5' exonuclease activity")

This is the gene with the largest number of annotations from PAINT (14 after GO filtering):
http://desktop.kmr.nz:4242/gene/SPAC57A7.12

To speed things up I disabled most of the non-GO annotation loading for this test so only the GO annotation will be complete on my desktop.

**Comment by ValWood** [comment]
Great. Let me know when. I started work early today. My new working pattern seems to be early start, siesta.

**Comment by kimrutherford** [comment]
It's ready!
 http://desktop.kmr.nz:4242

**Comment by ValWood** [comment]
That's great!

Can I get a GAF?

**Comment by ValWood** [comment]
I  can manage with it like this if not. I can check a slim process a day probably .
Just one thing. I think the IBA are given precedence over ISS?

At least 
mug14 has
GO:0030036 | actin cytoskeleton organization | ISO with P35611 | GO_REF:0000024
in PomBAse
but 
this is not visible here
http://desktop.kmr.nz:4242/gene/SPBC359.06

**Comment by kimrutherford** [comment]
> I think the IBA are given precedence over ISS?

IBD is lowest priority, IBA is second lowest.

> mug14 has
> GO:0030036 | actin cytoskeleton organization | ISO with P35611 | GO_REF:0000024

mug14 has
GO:0051017 | actin filament bundle assembly | IBA with PTN000072560 , P35611 , P35612

which is a descendant of GO:0030036 actin cytoskeleton organization.

**Comment by kimrutherford** [comment]
> IBD is lowest priority, IBA is second lowest.

Here's the full priority list, with the highest priority first:

```
 inferred by curator
 inferred from sequence orthology
 inferred from sequence or structural similarity
 inferred from sequence model
 traceable author statement
 non-traceable author statement
 inferred from expression pattern
 inferred from electronic annotation
 inferred from reviewed computational analysis
 inferred from biological aspect of ancestor
 inferred from biological aspect of descendant
```

That list is from this issue: https://github.com/pombase/pombase-chado/issues/594#issue-184221717

**Comment by ValWood** [comment]
Oh yes, ignore me!

**Comment by kimrutherford** [comment]
Here's the GAF file: https://send.firefox.com/download/704965af26d3bfd6/#5IlTGHbsK7v8UpbmcBOoVA

**Comment by ValWood** [comment]
Do you know why

http://desktop.kmr.nz:4242/gene/SPBC409.09c

GO:0000941 | condensed nuclear chromosome inner kinetochore 10
  | IBA with PTN001804338 , mis13

is showing?

there is also an IDA

**Comment by kimrutherford** [comment]
Looks like a bug!  I'll investigate.

**Comment by ValWood** [comment]
Oddly I didn't spot any others. I wonder if i. should have an extension of some sort? or something?

**Comment by kimrutherford** [comment]
I've found a bug and I think it's the bug that causing the problem you found.  It's a slightly embarrassing bug that's been there for ages: the redundant annotation filtering is currently done before the GO term remapping (using pombe-embl/chado_load_mappings/GO_mapping_to_specific_terms.txt).

mis13 has this annotation in the contig file:
```
FT                   /GO="aspect=C; term=inner kinetochore of condensed
FT                   chromosome; GOid=GO:0000939; evidence=IDA;
FT                   db_xref=PMID:15502821; date=20040914"
```

And the mapping file has:
```
GO:0000939      GO:0000941      condensed nuclear chromosome inner kinetochore 
```

When the filtering is done the annotation is still to GO:0000939 so the IBA annotation isn't filtered.  At the remapping stage GO:0000939 is changed to GO:0000941 so we get the redundant annotation.  I'll run a local test to make sure that's all true.

I'll also change the load script to do the re-mapping before filtering.

**Comment by ValWood** [comment]
OK no need to  do anything else with this ticket for a while. I opened a load of tickets and it will l clearly take a  while until those are fixed.

There are a few more process and component slim terms I would like to check but I made good progress this morning:

 https://github.com/pombase/curation/issues/2739
https://github.com/pombase/curation/issues/2737
and this covers most of the processes where fission yeast is a major model so I'm a bit fussier
I'm expecting  metabolism etc will be fine anyway...

**Comment by kimrutherford** [comment]
> I'll also change the load script to do the re-mapping before filtering.

Doing the filtering after the mapping has fixed the PAINT test load:
  http://desktop.kmr.nz:4242/gene/SPBC409.09c

I've fixed the nightly load script too so the main site should be fixed in the morning.

**Comment by ValWood** [comment]
It's giving an error right now. Although I'm not going to do any more on this right now so that is good;)
Back to curation...

**Comment by kimrutherford** [comment]
> It's giving an error right now

Yep, it's slightly in flux.  :-)

Let me know when you get back to this and I'll make sure the latest GO/PAINT annotations are loaded.  I'll also make sure the site isn't broken on my desktop.  I'm happy to leave my machine on overnight (my time) if you need access.

**Comment by ValWood** [comment]
How many PAINT annotation remain after that filter is applied?

**Comment by ValWood** [comment]
no hurry, just curious...

**Comment by kimrutherford** [comment]
After filtering there are 5199 PAINT annotations.  There are 14560 before filtering.

**Comment by ValWood** [comment]
Oh it was 5211  before the bug, so it only dropped by 12. shame !

**Comment by ValWood** [comment]
Assigned to me for the checking phase

**Comment by ValWood** [comment]
I did quite a lot of checking  a while ago, at least an the slim tem level.I reported a lot of errors, but further checking wold be diminishing returns. These were the. checks I did
https://github.com/pombase/curation/issues/2739
https://github.com/pombase/curation/issues/2737

I  went through the  GO annotation tracker and added filters  for any PANTHER ids where there are outstanding  queries about annotation valididyy (and just checked this in)



next:
 - [ ] make sure the latest GO/PAINT annotations are loaded. Using this priority list:
 inferred by curator
 inferred from sequence orthology
 inferred from sequence or structural similarity
 inferred from sequence model
 traceable author statement
 non-traceable author statement
 inferred from expression pattern
 inferred from electronic annotation
 inferred from reviewed computational analysis
 inferred from biological aspect of ancestor
 inferred from biological aspect of descendant
(Note that eventually we might change the priority but for now we still want the smallest possible number of PAINT annotation)


- [ ]  Last time I asked "After filtering there are 5199 PAINT annotations. There are 14560 before filtering." It will be useful to know  these numbers with eh current evidence heirarchy filtering  after the new PANTHER family filters are applied (out of curiosity).

- [ ] PANTHER annotations have a long list of supporting IDs . Long term it might be better to display only for the Panther node ID: (e.g. PANTHER:PTN000678822) - but at fist we will display the  complete lists, might be interesting for people, and it would be good if there was a way to make these accessible (I will look into panther external  links which might provide this detail), or make visible in mouse over (THIS CAN HAPPEN LATER- POSSIBLY MOVE TO A NEW TICKET?)

**Comment by kimrutherford** [comment]
> make sure the latest GO/PAINT annotations are loaded.

Do you mean add PAINT to the main load?  Or would you like another test load?

**Comment by ValWood** [comment]
I think maybe do one more test load and I will validate the numbers and do a very quick sanity check. Then we can move to live.

It's a lot of annotation so I think there will be a lot of  annotation issues  but hopefully  we can squash them pretty quickly.

**Comment by kimrutherford** [comment]
> I think maybe do one more test load and I will validate the numbers and do a very quick sanity check. Then we can move to live.

OK, I'll run a full load with PAINT on my desktop early next week.  I'll let you know when it's done.

**Comment by kimrutherford** [comment]
> make sure the latest GO/PAINT annotations are loaded. Using this priority list:

I just checked and that's the priority list we're currently using.

I'm running a test load now.  It should be ready by the morning.

**Comment by kimrutherford** [comment]
The load finished on my desktop.  It will be here until midday UK time or so: http://desktop.kmr.nz:4242/

The load doesn't include all datatypes because I wanted it finish quickly.

> It will be useful to know these numbers with eh current evidence hierarchy filtering after the new PANTHER family filters are applied (out of curiosity).

Before filtering: 14168.  After: 4975

**Comment by kimrutherford** [comment]
If you'd like to look at the GAF from this load it's (temporarily) here: http://desktop.kmr.nz/pombase/dumps/builds/pombase-build-2020-10-19-d1/pombase-build-2020-10-19-d1.gaf.gz

**Comment by ValWood** [comment]
Thanks I won't have time to check this a.m as I'll be working with Alayne until about 1.
So I will probably do this tomorrow.

**Comment by kimrutherford** [comment]
> The load finished on my desktop. It will be here until midday UK time or so: http://desktop.kmr.nz:4242/

New and faster link: https://desktop.kmr.nz/

**Comment by kimrutherford** [comment]
> So I will probably do this tomorrow.

OK.  My desktop will be on until noon-ish tomorrow.

**Comment by ValWood** [comment]
I won't get to this today, or possibly even tomorrow as I need to finish a CC session and prepare/record my sys biol lecture (that will likely take a full day).
I will let you know which day I plan to do checking the evening before.

**Comment by kimrutherford** [comment]
> I will let you know which day I plan to do checking the evening before.

I can re-run the load when you need it.

In the meantime I've copied the current data and website from my desktop to oliver1.  So you can now access it even when my desktop is off using this URL: http://paint.pombase.kmr.nz/

**Comment by ValWood** [comment]
wow thanks. i shouldn't be doing this today. need to record talk...ok just a little peek

**Comment by ValWood** [comment]
Is that the current DB rather than the one with the PAINT annotations?

**Comment by kimrutherford** [comment]
> Is that the current DB rather than the one with the PAINT annotations?

It's the one with PAINT annotations.  There are definitely more annotations.  For example the slim categories have more genes:

  - https://www.pombase.org/browse-curation/fission-yeast-bp-go-slim-terms
  - http://paint.pombase.kmr.nz/browse-curation/fission-yeast-bp-go-slim-terms

**Comment by ValWood** [comment]
ok thanks, not looking now

**Comment by ValWood** [comment]
OK let's go for it.
Include the PAIN annotation with the current precedent  for evidence codes (We might bump IBA up a bit later)

I will follow up with an e-mail to crowd-source the final QC. Then nobody can complain if they are wrong, they know that they just need to let us know...

**Comment by ValWood** [comment]
PINT, NOT PAIN!

**Comment by ValWood** [comment]
arggh

**Comment by kimrutherford** [comment]
Great.  I've added the PAINT annotations to tonight's load.  The main site will update itself at 6am-ish.

**Comment by ValWood** [comment]
oooh , excitiing!

**Comment by kimrutherford** [comment]
Done!  It's on the dev site: http://dev.pombase.kmr.nz/

> The main site will update itself at 6am-ish.

I've disabled that for today.  I'll update it manually when you're happy with the dev site.

**Comment by ValWood** [comment]
I'm happy, there are still problems, but I am happy to crowdsource the QC!

**Comment by kimrutherford** [comment]
OK, it's done.  The main site is updated.

**Comment by ValWood** [comment]
Whoop whoop!

**Comment by kimrutherford** [comment]
I guess this can be closed now?

**Comment by ValWood** [comment]
yes!
