### ISSUE TITLE
export RNA sequence and annotations to RNA central using new Json format

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#696]
The schema and a JSON schema validator are available at github.com/RNAcentral/rnacentral-data-schema.

**Comment by ValWood** [comment]
Don't need to include GO data as they can get this from GO.

Sequence, description, type, identifiers, publications  should do.

**Comment by kimrutherford** [comment]
Here's the list of RNA genes types I can see in Chado.  Does this look right?:

rRNA
snoRNA
snRNA
ncRNA
tRNA

**Comment by ValWood** [comment]
Yup it seems so. I thought we might have some SO IDs to specify sub-types like telomerase, but it appears not.

**Comment by kimrutherford** [comment]
I'm working on this today.  For the record, these are the SO IDs I've configured: 

SO:0000252                                                                                                                                                                                    
SO:0000253
SO:0000274
SO:0000275
SO:0000655

**Comment by ValWood** [comment]
great.

**Comment by kimrutherford** [comment]
I've sent a test file to RNAcentral.

Val, one part of the JSON file requires a assembly ID.  It can be any string.  The FlyBase example file uses "R6".

What should we use?

**Comment by ValWood** [comment]
This is a bit rubbish:
https://www.pombase.org/about/version-history

not the page, the contents...

**Comment by kimrutherford** [comment]
> A lot of the features are supported by a /db_xref, can this be included in the json?

I'll work on that.

> https://www.pombase.org/about/version-history

So maybe just use "2017-01-30" as the version?

**Comment by kimrutherford** [comment]
> A lot of the features are supported by a /db_xref, can this be included in the json?

Are the db_xrefs visible on the gene pages or does that need fixing too?

**Comment by mah11** [comment]
I think they're after a genome sequence build version, not a feature annotation version. So I"d be inclined to use that ASM294v2 accession.

**Comment by ValWood** [comment]
That makes sense. It's easiest ;)

**Comment by ValWood** [comment]
> Are the db_xrefs visible on the gene pages or does that need fixing too?

No they aren't there.
They should appear in the literature section for sure. There will be some for proteins too.

They support the "coordinates' of a feature so it would be nice longer term to make them a pop up somehow on genomic location
I, | 3086472-3086930 (459nt)

Shall I open a ticket?

**Comment by ValWood** [comment]
When the data is updated  (frequently) in RNA central we should announce.

**Comment by kimrutherford** [comment]
> They should appear in the literature section for sure.

They currently don't appear there by the looks of it.  The literature sections only has references from annotations.  I'll make a separate issue about that.

There are also a few like this that I was worried about:
  /db_xref="EMBL:AF087836" 
(I'm sure we've talked about these before but I can't remember the details)

> So I"d be inclined to use that ASM294v2 accession.

Thanks.  I'll go with that.

**Comment by kimrutherford** [comment]
> I'll make a separate issue about that.

pombase/website#925

**Comment by ValWood** [comment]
We can 'discard' the EMBL ones
/db_xref="EMBL:AF087836"
They will be managed by RNA central anyway and  any useful refes will be included from these.

**Comment by kimrutherford** [comment]
This is done.  We're waiting for feedback from RNAcentral.

ftp://ftp.pombase.org/nightly_update/misc/rnacentral.json

I'll close this and open new issues for anything they report.
