### ISSUE TITLE
Should the Chado load use the snapshot version of go-basic.obo?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#698]
We're using:
  http://purl.obolibrary.org/obo/go/go-basic.obo

Should we use:
  http://purl.obolibrary.org/obo/go/snapshot/go-basic.obo

**Comment by mah11** [comment]
Yes. Use the snapshot version, because the non-snapshot URLs are about to change to monthly updates.

**Comment by kimrutherford** [comment]
OK, I've changed that for tonight's load.
