### ISSUE TITLE
new interaction file PMID:19111658

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#699]
I made a file of physical interactions for PMID:19111658, based on the file that worked for #565. I committed it in svn on Friday but the annotations aren't showing up yet (there'll be a pile for swi6 and a few for other genes).

Does the loader do the "load PMID_*_interactions.tab2.txt" thing, analogous to PHAFs and modification data files?

Shout if I should fix anything in the file - it's pombe-embl/external_data/interactions/PMID_19111658_interactions.tab2.txt

**Comment by kimrutherford** [comment]
> I made a file of physical interactions for PMID:19111658,

I've tried loading it locally and it was fine.


> Does the loader do the "load PMID_*_interactions.tab2.txt" thing, analogous to PHAFs and modification data files?

Currently it has the file name for PMID:25795664 hard coded.  I'll change it to load anything in that directory that ends with ".tab2.txt"

**Comment by mah11** [comment]
Cool; thanks. I don't think we'll have nearly as many of these as we do PHAFs, but it doesn't hurt to future-proof.

**Comment by kimrutherford** [comment]
Looks OK:
  https://www.pombase.org/reference/PMID:19111658

**Comment by mah11** [comment]
yup, thanks!
