### ISSUE TITLE
Update to InterPro 70.0

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#700]
https://twitter.com/InterProDB/status/1044578691576061952

**Comment by kimrutherford** [comment]
I tried processing the XML file from the 70.0 release.  I noticed that the MobiDB entries are missing.

I'll contact InterPro about that.

**Comment by kimrutherford** [comment]
> I'll contact InterPro about that.

EBI support ticket number 299364.

**Comment by ValWood** [comment]
We are not bothered about MoBiDB :)

**Comment by kimrutherford** [comment]
> We are not bothered about MoBiDB :)

That's good because it seems they removed it on purpose.  :-)

I'll go ahead with updating PomBase with the latest InterPro.
