### ISSUE TITLE
human disease genes

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#701]
When you get chance  could you query for the human names for the orthologs of these?
I might have found the complete human disease gene list.

I want to remove the annotated ones so I can spot check the unannotated.

Thanks

Val

**Comment by kimrutherford** [comment]
I've put the query result here in Dropbox:
  Dropbox/pombase/Chado/queries/pombe_human_disease-2018-10-01.txt
  https://www.dropbox.com/s/9b79oyge3sv88kg/pombe_human_disease-2018-10-01.txt?dl=0

It includes one-to-many orthologs.  It that what you need?

**Comment by Antonialock** [comment]
I have the disease ontology mappings (well...ALL the mappings...)

[MalaCards_external_ids_v480(1).zip](https://github.com/pombase/pombase-chado/files/2489235/MalaCards_external_ids_v480.1.zip)

**Comment by Antonialock** [comment]
I'll create a ticket on the website tracker? I though this was the right ticket...

**Comment by ValWood** [comment]
done
