### ISSUE TITLE
Missing warning for unknown CHEBI term

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#704]
There is no warning or error for this annotation.  The annotation_extension is slightly dropped.

FT                   /controlled_curation="term=gene expression, RNA level;
FT                   annotation_extension=in_presence_of(CHEBI:142517);
FT                   qualifier=increased ; evidence=ECO:0000231;
FT                   db_xref=PMID:29900664; date=20181113"

**Comment by mah11** [comment]
This is just a timing issue - there was a warning in the logs I saw yesterday, so I added the term to mini-chebi, and the warning went away as expected. The annotations show up on the gene pages (ctt1 & gpd1) with the extensions today.

https://curation.pombase.org/dumps/builds/pombase-build-2018-11-18/logs/qualifier_problems.txt
and pombe-embl/mini-ontologies/chebi.obo r5210
