### ISSUE TITLE
Handle output of new owltools version when computing closure

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#706]
In the latest version of owltools, "part_of" has changed to "BFO:0000050" in the relation column.  Other relations have changed too.  eg. "negatively_regulates" in now "RO:0002212".

This needs fixing in the loader code before we can upgrade.  Upgrading isn't urgent though.

Refs geneontology/go-ontology#16776

**Comment by ValWood** [comment]
Is the priority of this still medium? how  quick is it?

**Comment by kimrutherford** [comment]
I've just made the changes to support the new output style.  In case the results will be slightly different from the current version, I won't check the changes in today.  I'll test it in the nightly load over the weekend.

**Comment by kimrutherford** [comment]
> I'll test it in the nightly load over the weekend.

I've checked in the changes to support the new OWLTools.  Tomorrow I'll see if I can spot any major ontology problems.

**Comment by kimrutherford** [comment]
> Tomorrow I'll see if I can spot any major ontology problems.

There's good news and, er, other news.

The good news is that it mostly looks fine.  The other news is that I spotted an ontology closure problem that been around for a while.

In the main site now, sister chromatid segregation (GO:0000819) has 184 gene annotated according to this page: https://www.pombase.org/term/GO:0000819
but in yesterday's load it has 186: http://pombase-dev.bioinformatics.nz/term/GO:0000819 (that's temporarily yesterday's load)

The difference is that "meiosis I spindle assembly checkpoint (GO:1905318)" annotations appear on yesterday's "sister chromatid segregation (GO:0000819)" page, but not after updating OWLTools.

Here's the GO terms and relations that connect those terms.  There might be other paths, I didn't check.  Maybe the problem is caused by the "regulates" relation?

- meiosis I spindle assembly checkpoint (GO:1905318)
- *is_a* meiotic spindle assembly checkpoint (GO:0033316)
- *is_a* meiotic spindle checkpoint (GO:0044779)
- *is_a* negative regulation of metaphase/anaphase transition of meiotic cell cycle (GO:1902103)
- *is_a* regulation of metaphase/anaphase transition of meiotic cell cycle (GO:1902102)
- *is_a* regulation of metaphase/anaphase transition of cell cycle (GO:1902099)
- *is_a* regulation of sister chromatid segregation (GO:0033045)
- *regulates* sister chromatid segregation (GO:0000819)

I don't think the OWLTools update is causing this problem.  I checked the Chado databases going back a few weeks and sometimes "meiosis I spindle assembly checkpoint (GO:1905318)" is a descendent of "sister chromatid segregation (GO:0000819)" page and sometimes not.

This seems similar to https://github.com/geneontology/go-ontology/issues/16687

**Comment by ValWood** [comment]
Yes! This is the problem with owl tools that we tried to track down  *ages* ago.
The number 'flip-flop'   even when the data does not change.
We need @cmungall  @balhoff to look at this.  
So, this problem has existed for a while, independently of the update owltools update.

**Comment by ValWood** [comment]
I can only find this ticket
https://github.com/pombase/website/issues/699

I know  I opened some tickets on the GO tracker about this. I described it as "annotation flip-flopping". I can't find any of the tickets relating to this issue.  The only other thing I remember is that the examples were from "cytoskeleton organization" and "conjugation with cellular fusion"

**Comment by mah11** [comment]
In our earlier encounters with this problem, we pinned it on owltools (tho apparently some part of it that's unaffected by the update). The most informative tickets aren't the ones on the GO ontology tracker; they're #678 on this tracker and the [linked ticket on the owltools tracker](https://github.com/owlcollab/owltools/issues/256).

**Comment by ValWood** [comment]
Thanks.
I knew I had written flip-flopping somewhere:
https://github.com/pombase/pombase-chado/issues/678

**Comment by kimrutherford** [comment]
I've commented in the owltools issue about this: https://github.com/owlcollab/owltools/issues/256

**Comment by kimrutherford** [comment]
> I've commented in the owltools issue about this: owlcollab/owltools#256

I'll close this one since there's an owltools issue for the problem.
