### ISSUE TITLE
Load pombe-embl/supporting_files/PB_references.txt

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#707]
We should load PB_references.txt so that the reference pages have more details.  eg.
https://www.pombase.org/reference/PB_REF:0000001

See: pombase/website#1072

**Comment by kimrutherford** [comment]
That's done now and added to the nightly load.  I didn't check it in soon enough for tonight's load.  It should be visible on Wednesday.  I'll check then and close the issue.

**Comment by ValWood** [comment]
Looks good, closing
