### ISSUE TITLE
distinguishing data from small and large scale publications

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#708]
We need to do a number of things here, will require some discussion:

We should be able to summarize in the grant somewhere how much we have curated, AND to distinguish between small and large scale publications or datasets.

This is tricky because most will not fit neatly into one of the other.
There are a number of approaches we could take:

Ideally we need something like:
Genome browser 224 tracks hosted from 18 datasets *
Proteomics, modifications   7  (xxx annotations)
Protein/RNA  expression level	5  (xxx annotations)
Genome-wide phenotype screens  83 (xxx annotations)
(probably  using the figure space)

in addition  the existing small scale annotation  summary from the metrics page

(* can we automate this from the spreadsheet @Antonialock  creates?)

We could use counts of "external  data files"  for those not curated in Canto
but 
- some external  files  are small scale 
- some contain a mixture of HTP screens and low throughput data 
(maybe we can use a flag?)

**Comment by ValWood** [comment]
once we have separate HTP LTP numbers we want to display both data HTP vs LOTP in these graphs
https://curation.pombase.org/pombe/stats/annotation

**Comment by kimrutherford** [comment]
Did we decide on how to distinguish high and low throughput publications?  Sorry, I've forgotten what we talked about.

**Comment by ValWood** [comment]
Hmmph, I thought I put a comment in this ticket when we talked about it....now what did we decide?
