### ISSUE TITLE
add to  complex filters config file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#710]
GO:0000778 | condensed nuclear chromosome kinetochore

thanks
(cant remember where)

**Comment by mah11** [comment]
The configuration is in pombe-embl/website/pombase_v2_config.json, this part:

    "file_exports": {
      "macromolecular_complexes": {
        "parent_complex_termid": "GO:0032991",
        "excluded_terms": [
           (many GO IDs)
        ] 

I've added GO:0000778 to the ID list, on the assumption that you want it excluded from now on (49 entries in today's Complex_annotation.tsv file).
