### ISSUE TITLE
send interaction data to biogrid

### ISSUE THREAD

**Issue by Antonialock** [pombase/pombase-chado#713]
BioGrid has requested that we send them our interaction data from April 2017-now.
The last file was sent April 19, 2017

**Comment by ValWood** [comment]
see also
https://github.com/pombase/pombase-chado/issues/411

**Comment by ValWood** [comment]
Although I really don't want to label any more of your tickets as "high priority" this request came through to Antonia a long time before the ticket was opened. Also the longer we leave it the harder it will be for them to synchronise. We need to reestablish a regular BioGRID update.

**Comment by ValWood** [comment]
...so let up know if there are any outstanding questions

**Comment by ValWood** [comment]
will close since it really is a duplicate of 
https://github.com/pombase/pombase-chado/issues/411
