### ISSUE TITLE
logs , strange gene product number

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#714]
I was just looking for something in the logs and I spotted

https://curation.pombase.org/dumps/latest_build/logs/log.2019-02-05-21-26-13.annotation_counts_by_cv
56439 | PomBase gene products

seems odd?

**Comment by kimrutherford** [comment]
I was alarmed to until I checked the database and reminded myself.  We use the "PomBase gene products" CV to store the gene product for human and cerevisiae genes too.  The CV is badly named.  There are only 7001 product for pombe genes.

**Comment by ValWood** [comment]
OK!
