### ISSUE TITLE
nightly update

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#715]
can you sanity check this for me ..i.e @kimrutherford  check load stuff and  @mah11  check the GO obo file we used

I opened this ticket. I thought it was a GO issue but now I'm not so sure

https://github.com/geneontology/go-ontology/issues/16936

**Comment by mah11** [comment]
reopen if this GO ticket doesn't fix it:

https://github.com/geneontology/helpdesk/issues/192

**Comment by kimrutherford** [comment]
We're using the snapshot release of go-basic.obo: http://purl.obolibrary.org/obo/go/snapshot/go-basic.obo

I just downloaded the latest version and the geneontology/helpdesk#192 problem is still there.

Would you like the main site to go back to a previous nightly PomBase Chado that doesn't have the problem?

**Comment by kimrutherford** [comment]
> Would you like the main site to go back to a previous nightly PomBase Chado that doesn't have the problem?

I had a quick look and I think we would need to go back to the Chado from 2019-02-13.

**Comment by ValWood** [comment]
We could go back if it is quick and easy. How long would it take?

**Comment by kimrutherford** [comment]
> We could go back if it is quick and easy. How long would it take?

Yesterday morning I moved the site back to the Chado load from 2019-02-13.  It's a quick process.  I'll leave it on that release today too since last night's load doesn't include the fixed version of GO.  Hopefully all will be OK on Saturday morning.

**Comment by ValWood** [comment]
good plan.
