### ISSUE TITLE
There are 589 annotation marked as community curation by Val

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#716]
They're all from Canto and are flagged as community curated in the Chado summary table:

Need to fix for pombase/website#1080

SQL:

```sql
select * from pombase_annotation_summary
 where community_curated = 't' and curator_name = 'Val Wood';
```

Example session: https://curation.pombase.org/pombe/curs/654d33ea7fb3acba/ro/

**Comment by ValWood** [comment]
Did I do something wrong?

**Comment by kimrutherford** [comment]
> Did I do something wrong?

It wasn't you.  I think there was Canto bug that caused this and was fixed years ago.  The annotations that have this problem are all from 2014 or earlier.  I'll fix the annotation flags with a bit of SQL.  This will bump the community curated number up slightly.

**Comment by kimrutherford** [comment]
I've fixed the annotations.
