### ISSUE TITLE
Li-Lin's interaction data file

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#717]
... is in biogrid format, ready to go (background in helpdesk ticket 6733).

Normally I would just stick it in svn and wait for loading-pipeline magic to happen, but. In case it's still going to be a while before svn access is restored via oliver1, can we sneak the file in any other way? I could email the file to @kimrutherford or we could go ahead with the temporary svn location; I don't mind which.

**Comment by kimrutherford** [comment]
If it's not too big, could you add it to Dropbox?  I'll remove it once I've put it in SVN.

**Comment by ValWood** [comment]
good plan to get this through...
I 'll try to find out what is happening  thursday.  i have a few call phi curators etc weds...

**Comment by mah11** [comment]
> If it's not too big, could you add it to Dropbox?

It's only 91 K, so I didn't even zip it. Dropbox/pombase/Data/PMID_30824696_interactions.tab2.txt

**Comment by mah11** [comment]
Li-Lin also sent a picture for a research spotlight item. I put it in but haven't flagged it to go live. I'll activate it once the data file gets loaded.

**Comment by kimrutherford** [comment]
> Dropbox/pombase/Data/PMID_30824696_interactions.tab2.txt

Thanks.  I've added that to SVN and deleted the copy in Dropbox.  I didn't add the file in time for the load but it should be visible on Thursday morning.

**Comment by mah11** [comment]
ooh, excellent. I'll tell Li-Lin, and add the 'live' flag to the spotlight for tomorrow (Thurs). Thanks!

(I'll reopen this if anything goes awry.)

**Comment by kimrutherford** [comment]
It's now on the main site: https://www.pombase.org/reference/PMID:30824696

**Comment by ValWood** [comment]
Nice. This comes up as curated by PomBase staff. It would be nice if we had a way to attribute  HTP curation via spreadsheets to community too.  Or even attribute more than one curator...

discuss.

**Comment by mah11** [comment]
I just stuck a Canto session through with the gene list and "Experimental data, not of available types", so the paper will look completed there. I assigned the session to Li-Lin, so Canto has it connected with him. Will that affect the attribution on the web pages?

**Comment by kimrutherford** [comment]
> I just stuck a Canto session through with the gene list and "Experimental data, not of available types",
> so the paper will look completed there. I assigned the session to Li-Lin, so Canto has it connected
> with him. Will that affect the attribution on the web pages?

Thanks Midori.  That fixed it.

It now says:

```
 Community curation provided by Li-Lin Du
```

**Comment by mah11** [comment]
yay me!

;)
