### ISSUE TITLE
Make interaction evidence case-insensitive

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#718]
"Dosage Rescue" works but "Dosage rescue" doesn't.

The configuration to find the text in the first column (like "overexpression rescues") needs the exact case at the moment.

**Comment by ValWood** [comment]
This looks quick so I added "next"?

**Comment by kimrutherford** [comment]
> The configuration to find the text in the first column (like "overexpression rescues") needs the exact case at the moment.

I don't know what I was meaning there.
But I've changed the interaction file importing code to handle evidence codes in any case.
