### ISSUE TITLE
Add a README to each release snapshot directory

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#720]
I would be good to say what each file is about and what's in the sub directories.

https://curation.pombase.org/releases/pombase-2019-03-01/

**Comment by ValWood** [comment]
Adding new starter as this could be done in a session with Manu while explaining release contents?

**Comment by kimrutherford** [comment]
That sounds like a good plan.

**Comment by ValWood** [comment]
https://github.com/pombase/pombase-chado/issues/1022

**Comment by kimrutherford** [comment]
I've added a comment to: 
  - pombase/website#2058

so we can close this.

**Comment by ValWood** [comment]
duplicate
