### ISSUE TITLE
mechanism to attribute more than one curator for a session

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#721]
from
https://github.com/pombase/pombase-chado/issues/717

need a mechanism to attribute more than one curator for a session

**Comment by Antonialock** [comment]
curator is stored against annotation so can just acknowledge anyone who has contributed annotations to a specific paper?

**Comment by kimrutherford** [comment]
> curator is stored against annotation so can just acknowledge anyone who has contributed annotations to
> a specific paper?

I think that's the most reliable method because it will ignore curators who just reassign the session.

**Comment by ValWood** [comment]
This appears to be on the wrong tracker?

**Comment by ValWood** [comment]
although i guess this means display both curators if there is more than one.

**Comment by kimrutherford** [comment]
I think this is done and/or covered by other issues.
