### ISSUE TITLE
reciprocate protein binding annotations, but not their "involved_in' extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#723]
When we curate 
proteinA binds proteinB we want this to be reciprocated.

However, the annotation extension is not always true in both directions. If we want to extend these annotations, we need to do it explicitly.

Here is an example:

pds5 (cohesin subunit)  binds and localizes hrk1 (histone kinase)

this is correct:
binds hrk1  part of protein localization to nuclear pericentric heterochromatin part of attachment of spindle microtubules to kinetochore involved in meiotic sister chromatid segregation during mitotic M phase

but this isn't:

hrk1
binds pds5  part of protein localization to nuclear pericentric heterochromatin part of attachment of spindle microtubules to kinetochore involved in meiotic sister chromatid segregation during mitotic M phase

**Comment by ValWood** [comment]
If you have chance it would be good to address this. If the extension is transferred to the reciprocal gene it is incorrect and hence misleading. It bothers me ....

**Comment by kimrutherford** [comment]
I've dug into this a bit more.  Do these annotations come just from Canto?  If so it won't take long to fix the reciprocals annotations.

**Comment by ValWood** [comment]
I would like to say no but I can't be sure. There are some part_of(involved_in) annotation in Artemic, but not many and I think they are unlikely to be "protein binding" terms. Most are probably on TAS/ISO/ISS annotations and we don't do those by these evidence codes.

Is ther an easy way to see if there are any experimental ones? they should be migrated to the  corresponding  Canto sessions

**Comment by kimrutherford** [comment]
A quick Chado query gives about 1000 IPI protein binding annotations that don't come from Canto.  I'm digging into where they come from.

**Comment by ValWood** [comment]
There are probably that many protein binding annotations in Artemis (we are slowly replacing), but only a small number have "involved_in" extensions....

**Comment by kimrutherford** [comment]
> but only a small number have "involved_in" extensions....

I had a look and could see any.  So I'll go ahead and fix the Canto to Chado loading code to correctly add a reciprocal annotation without the extensions.  After that is working I'll query Chado to check that there are no missing reciprocal annotations.

**Comment by kimrutherford** [comment]
I've got this mostly done now, except:

> Basically need to when we make reciprocal binding annotation, copy only the "during" extension,
> and not anything else.

There are lots of different during extensions.  Your example above is happens_during.  Is that the only one that should be copied?

**Comment by ValWood** [comment]
Actually I think it is only a subset of the extensions that are invalid.
Let me check...

**Comment by ValWood** [comment]
Any "during" can be copied.

I think we should not copy any part_of even though some are correct.
It will be difficult to figure out which are not. I think the problem mainly affectes localizations (A localizes B) but could also affect "regulation of " terms.

I  think  most of these annotations are likely to be localizations so we will apply to all. Curators will need to add the reciprocal part_of extension explicitly if it is correct.

**Comment by kimrutherford** [comment]
> Any "during" can be copied.

OK, thanks.

As far as I can tell happens_during is the only "during" extension relation in the binding annotations.

I think this is ready to go.  I'll commit the changes and check the Friday night load to make sure it looks OK.  I'll revert the fix if I see any problems.

**Comment by ValWood** [comment]
Let me know when it is live. I can check some examples too.

**Comment by kimrutherford** [comment]
> Let me know when it is live. I can check some examples too.

I noticed some problems after the load.  Some redundant annotations are being created.  So I've cancelled the update for today and reverted the change.  I'll fix it when I'm back from holiday in January.

Here's an example for hrk1.  Before my changes:

![redundant-bind-annotaion-before-1](https://user-images.githubusercontent.com/90474/70842674-6b6fd500-1e8b-11ea-9ba5-db56a5dd4dfa.png)

And after:

![redundant-bind-annotaion-after-1](https://user-images.githubusercontent.com/90474/70842678-7296e300-1e8b-11ea-9301-58d2e0033935.png)

**Comment by kimrutherford** [comment]
> I noticed some problems after the load. Some redundant annotations are being created. So I've
> cancelled the update for today and reverted the change. I'll fix it when I'm back from holiday
> in January.

I've got back to this and had another go at fixing it.  It looks OK locally but I'll check the load in the morning.

**Comment by kimrutherford** [comment]
> It looks OK locally but I'll check the load in the morning.

It's still not quite right so I've cancelled today's update.  I've tweaked the load script and I'll check again tomorrow.

**Comment by kimrutherford** [comment]
>  I've tweaked the load script and I'll check again tomorrow.

It didn't work.  :-)

I've made a minor tweak and I'll check again in the morning.

**Comment by kimrutherford** [comment]
> I've made a minor tweak and I'll check again in the morning.

It looks like it's doing what I think it should do.  Could you have a look to make sure it's doing what you think it should do?  :-)

Last night's Chado load is only visble in the dev site.  The two genes in your example are here:
 - http://dev.pombase.kmr.nz/gene/SPAC23C4.03
 - http://dev.pombase.kmr.nz/gene/SPAC110.02

The main site usually get the update automatically at 6am but I've cancelled that and I'll update it manually if the dev site looks OK to you.

**Comment by ValWood** [comment]
I think this seems OK.

**Comment by kimrutherford** [comment]
Great.  I've updated the main site.

> Also for this one,
> binds hrk1 part of protein localization to chromatin

I've made a separate issue about filtering:
pombase/pombase-chado#747
