### ISSUE TITLE
Split BioGRID annotation that are HTP and LTP

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#724]
There are 25-ish interactions from BioGRID that have "High Throughput|Low Throughput" in the Throughput column.  We should make two annotations for each for these, one with with "High Throughput" and one with "Low Throughput".

**Comment by ValWood** [comment]
I'm not sure, I think because there are so few we could just call them HTP if we don't know.

I'm pretty sure I sent BioGRID the list so I presume they will fix at some point if separate annotations are required.

**Comment by kimrutherford** [comment]
> I'm not sure, I think because there are so few we could just call them HTP if we don't know.

That's quick to do.  Should I go ahead?

**Comment by ValWood** [comment]
Yes go on. Hopefully it will be fully resolved externally and its a really small number. We don't really lose anything.

**Comment by kimrutherford** [comment]
That's done for tonight's load.  I'll check things when it's done.

**Comment by kimrutherford** [comment]
> I'll check things when it's done.

It's all good.  The interactions that are LTP and HTP now flagged as HTP in Chado.
