### ISSUE TITLE
malformed annotation not reported

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#725]
Just spotted this...seems odd that it doesn't get logged as a problem?

/GO="aspect=F; term=0097177; GOid=GO0097177:; evidence=ISO; db_xref=GO_REF:0000024; with=SGD:S000000956; date=20040507"

**Comment by mah11** [comment]
It does - it's in misc_term_warnings.txt (and it's new; I botched fixing something else on Friday; oops)

**Comment by ValWood** [comment]
Ah OK , I couldn't figure out how it could have crept in recently since I  haven't touched anything. It didn't occur to me that it might be you ;)
