### ISSUE TITLE
New relationship type for modification

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#726]
see helpdesk ticket
 Re: Confirmation of curation session for PMID:30726745

Can we add a relation "affected_by" or some other phrase so that we can capture direct OF indirect modification event?

https://www.pombase.org/documentation/modification-data-bulk-upload-format

**Comment by ValWood** [comment]
I think @Antonialock  will need this new relationship for  Ye De TAys phosphorylation sites so putting at high priority.
Let us know if it isn't clear what is needed.

**Comment by Antonialock** [comment]
Yeah I thought w could talk about this. I've always done these as phenotypes?

**Comment by ValWood** [comment]
@Antonialock  is anything else holding up this paper?

**Comment by ValWood** [comment]
> Yeah I thought w could talk about this. I've always done these as phenotypes?

I thought these were orb6 phosphorylation sites (proteomics data)

like the Mathew Swaffer dataset?
https://www.pombase.org/reference/PMID:27984725

(at least that is what Ye Dee Tay implied in an early e-mail.

Isn't this the case?  (I did not look at the paper yet)

**Comment by Antonialock** [comment]
they determine phosphorylated sites in WT + in orb6 mutant
they then compiled a list of the proteins that are differentially phosphorylated in the mutant compared to wild-type.
then they looked at protein motifs and narrowed down a list of "strong candidates"
they tested two of their strong candidates experimentally

**Comment by ValWood** [comment]
checking the Swaffer/Nurse papere

To rigorously define a class of direct CDK substrate sites, we identified phosphorylation events at the minimal CDK consensus sequence (S/T-P), which decreased more than 2-fold after CDK inactivation and whose dephosphorylation was immediate and continuous, fitting an exponential decay (n = 275) (Table S1) (Figures 1C–1E and ​andS1G).S1G). These sites are enriched for the full CDK consensus site (+3 K/R) (Songyang et al., 1994) (Figure S1I) and do not overlap with non-specific 1-NmPP1 effects (Koch et al., 2011) (Figures S1E and S1F). It is possible a fraction of these sites are phosphorylated by kinases regulated very rapidly downstream of CDK. Phosphosites at the consensus site of other kinases do change in this experiment (e.g., Plk1 and Aurora), although the vast majority of these were not dephosphorylated immediately and did not fit an exponential decay (data not shown). Many of the proteins we identified have been previously characterized as CDK substrates, including orthologs of proteins with mitotic functions, such as SMC4 (Cut3), Cdc25, Plk1 (Plo1), Survivin (Bir1), INCENP (Pic1), Ask1, and TOG (Dis1 and Alp14), and proteins involved in DNA replication, such as Sld2 (Drc1), Sld3, Fen1 (Rad2), Orc1, and Orc2. Furthermore, these sites are enriched for cell-cycle-related GO categories as well as being enriched on the orthologs of human and S. cerevisiae CDK targets (Table S2) (Holt et al., 2009, Hornbeck et al., 2015). This, and the fact that these data can be used to derive half-lives that are quantitatively reproducible between biological repeats (Figure 1B), corroborates our conclusion that this set of 275 sites predominantly constitutes direct in vivo CDK substrates.

**Comment by ValWood** [comment]
What is the consensus site for orb6 and how many candidate substrates do they have?

Matthew was probably confident because of the combination of rapid phosphorylation and a strong CDK consensus, although they say some may be indirect they think it unlikely (I remember @mah did check, and lower confidence sites that did not satisfy all these criteria were excluded- it wasn't the full proteomics dataset).





Even if Tay's experiment was the same, unless there is a strong phosphosite associated with orb6 maybe we should be a bit more conservative?

but we can include all as modifications "affected buy ' orb6

**Comment by ValWood** [comment]
So basically we want to  include modification data for all of the proposed targets with the new relation affected_by orb6 . OK?

https://github.com/pombase/pombase-chado/issues/726

**Comment by ValWood** [comment]
> Yeah I thought w could talk about this. I've always done these as phenotypes?

Do we have many other examples? I can't think of any. In small scale they would probably do some more experiments to confirm. Or we have historically used "phosphorylation" process with these as targets. This makes them easy to locate and add  "affected_by"  with the kinase if we do not know that it is direct.

 We need to capture this information because it is really informative about the network, even if we cannot make a direct connection. 

In this session we have no record of the other targets.
https://www.pombase.org/reference/PMID:30726745

**Comment by ValWood** [comment]
So the action for this itcket is to add the relation affected_by for use with modification data extensions.

**Comment by mah11** [comment]
> So the action for this itcket is to add the relation affected_by for use with modification data extensions.

That was done on August 14th.

I'll add it to the documentation now.

**Comment by ValWood** [comment]
@Antonialock  I think  you could also use the affeted_by list
 to provide phenotypes of orb6, in addition to the modifications
