### ISSUE TITLE
directly_positively_regulates /directly_negatively_regulates 

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#728]
need to change to "has_input"  for GO submission.

We still need to find a solution for this (should be on the curation tracker, but I can never find the ticket)

==

...During import into our database we check the annotation extension and if they are invalid then we hide them. In the case of P28829 for GO:0004709 extension error is

Invalid range for directly_positively_regulates: PomBase:SPAC1D4.13

If this is correct extension then GO consortium need to add this relation type as valid.

**Comment by ValWood** [comment]
oddly it is allowed in GO even though it isn'y a 'blessed' relation

![go](https://user-images.githubusercontent.com/7359272/57914281-3d3efe00-7886-11e9-82f0-63150725e71c.jpg)

**Comment by mah11** [comment]
superseded by #744
