### ISSUE TITLE
GO issue to trace

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#729]
I was waiting for the GO to be updated again to check the parentage of 
"regulation of mitochondrial translation"
https://www.pombase.org/gene/SPAC1B3.04c
https://www.pombase.org/gene/SPAC25B8.04c

this is currently not slimming and I can't figure out why?

parentage looks OK in QuickGO (but maybe QuickGO is out of date?)

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0070131

Could you see if you can  figure?

**Comment by ValWood** [comment]
maybe GO did not update in PomABse yet?

here is a similar issue

GO:0034203 | glycolipid translocation
for
https://www.pombase.org/gene/SPBC887.19

does not slim to "transport" but it has this parent in QuickGO

**Comment by kimrutherford** [comment]
Which slim category is "regulation of mitochondrial translation" supposed to be in?

We get a new go-basic.obo at the start of each load from:
http://purl.obolibrary.org/obo/go/snapshot/go-basic.obo

**Comment by ValWood** [comment]
Ah OK it's actually "mitochondrial gene expression"

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/17345

**Comment by kimrutherford** [comment]
I've checked the owltools output. There is no inferred relationship between "regulation of mitochondrial translation" and "mitochondrial gene expression".

**Comment by ValWood** [comment]
caused by a missing parent in GO
