### ISSUE TITLE
Load the KEGG pathways IDs mapping into Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#730]
http://rest.kegg.jp/link/pathway/spo

See: pombase/website#1239

**Comment by kimrutherford** [comment]
> http://rest.kegg.jp/link/pathway/spo

We also need to load the pathway names for each of those pathways.

**Comment by ValWood** [comment]
I'll put this as low priority for now since its a stand alone task and not critical
(unless it is super-quick)

**Comment by kimrutherford** [comment]
> I'll put this as low priority for now since its a stand alone task and not critical
> (unless it is super-quick)

The KEGG pathway IDs are now loaded into Chado.  It was quite quick.  I had it in my head and the code wasn't difficult.

https://github.com/pombase/pombase-legacy/commit/950d028e452296cf6909c39b6f06c44d5ca8fccc
