### ISSUE TITLE
update wee1.50 globally in chado

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#732]
can we replace all occurrences of wee1-50(other)

with  wee1-50
description "G850E" 
type "amino acid mutation"

ideally when something is updated from other or unknown to another type it will be updated throughout the database (single and multi-genotype alleles)

@mah11  @Antonialock is there  any problem with this?

**Comment by kimrutherford** [comment]
> can we replace all occurrences of wee1-50(other)

No problem.  Let me know if I should go ahead.

> ideally when something is updated from other or unknown to another type it will be updated throughout
> the database (single and multi-genotype alleles)

If the type is "unknown" then you'd only need to update one session and Chado will get the new type.  The alleles don't do that if the type is "other".

**Comment by ValWood** [comment]
yes, go ahead with the switch.

I think we can manage reannotation for type "other" for now. It would have worked as expected if wee1-50 was "unknown".

**Comment by kimrutherford** [comment]
OK, done.

**Comment by ValWood** [comment]
thanks! that saved me an hour! I hope it didn't take so long ;)

**Comment by kimrutherford** [comment]
> thanks! that saved me an hour! I hope it didn't take so long ;)

It took 5 minutes but if I had to do it again it would only be seconds.

**Comment by ValWood** [comment]
In that case, I will find some more later!

**Comment by Antonialock** [comment]
I think it works fine for "unknown"

I don't like to implement the same for "other" - we shouldn't record "unknowns" as "other"

I would prefer if you:
1.  alert if two alleles with different descriptions are recorded
2. implement a nifty way to update several sessions in one go

**Comment by ValWood** [comment]
> I don't like to implement the same for "other" - we shouldn't record "unknowns" as "other"

that's exactly what I said above. If we want a new feature it's a new ticket...

Note that
1. Already exists as a log file
2. Already exists as a Kim (we need to request it but Kim can update the database with a script, as described above)

**Comment by Antonialock** [comment]
ok, I just misunderstood -  I thought Kim said he switched so that 'other' would be overridden by more specific allele descriptions.

**Comment by ValWood** [comment]
Nope, this was a one-off replacement of  the other wee1.50 description, which ai think is what you were requesting ;)  So if you have any global replacement requests like this,  Kim can now do them quickly ....

**Comment by ValWood** [comment]
It wasn't very clear what was going on I agree. I'm glad Kim understood.
