### ISSUE TITLE
messing logs for SPBC8E4.02c but I don't see a problem?

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#733]
warning in 9a6cbb66c43cb971: in extension for PomBase-genotype-1044, can't find feature with identifier: SPBC8E4.02c - can't find feature for: SPBC8E4.02c

https://www.pombase.org/gene/spncrna.9001
(it is a non-coding RNA though)

**Comment by mah11** [comment]
SPBC8E4.02c is now an alternate ID for spncrna.9001 - I think that's why it's spawning a log message. I've fixed that one.
