### ISSUE TITLE
Fix warning in curation-tool-data-load-output log file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#735]
more the one relation cvterm returned for part_of:
terms: BFO:0000050 and BFO:0000050

Also occurs when loading PHAF files: https://curation.pombase.org/dumps/builds/pombase-build-2022-01-02/logs/log.2022-01-02-21-30-14.phenotypes_from_PMID_28410370_phaf

**Comment by ValWood** [comment]
Is this quick?

**Comment by kimrutherford** [comment]
> Is this quick?

I'm not sure.  Probably it will be a quick fix but I haven't tracked down the bug yet.

**Comment by ValWood** [comment]
OK I removed 'next' and 'quick' !

**Comment by kimrutherford** [comment]
> I'm not sure. Probably it will be a quick fix but I haven't tracked down the bug yet.

I think I've tracked this down.  I've committed a fix but not in time for the load.  I'll check the logs on Thursday morning.

**Comment by kimrutherford** [comment]
It all looks OK.
