### ISSUE TITLE
Fix duplicate annotation warning in Canto load log

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#737]
This annotation is not being loaded.  The "already been stored" message seems wrong.

warning in 8b7a4bf27652b9d5: storing feature_cvterm from SPBC725.11c.1 
to RNA polymerase II proximal promoter sequence-specific DNA binding 
[occurs_at] CCAAT_motif - failed to store feature_cvterm: that 
annotation has already been stored in Chado

**Comment by ValWood** [comment]
any insight? seems odd....

**Comment by kimrutherford** [comment]
I had a look and I can't work it out.  There is an identical (except for evidence code) annotation from a different publication (https://www.pombase.org/reference/PMID:1899284) but it should be fine to have the same annotation from two publications.  When I have time I'll trace through what's going on.

**Comment by ValWood** [comment]
Yes I looked last night and that was all I could see too, but as you say we have loads of those...

**Comment by kimrutherford** [comment]
I've finally fixed this.  There is an annotation on chr2 that is the same is in that session except that the evidence code is different:
```
FT                   /GO="aspect=F; term=RNA polymerase II core promoter
FT                   proximal region sequence-specific DNA binding;
FT                   qualifier=contributes_to; GOid=GO:0000978;
FT                   annotation_extension=occurs_at(SO:0001856); evidence=TAS;
FT                   db_xref=PMID:16963626; date=20111214"
```

It's TAS in the contig file and IDA in the session.  The code that checks for duplicate annotation when loading the Canto sessions was ignoring the evidence and so refusing to load the Canto annotation.

I've fixed the code to pay attention to the evidence code so that the Canto annotation will load unless there is an existing annotation with exactly the same gene, publication, term, extension and evidence.

I'll close this after the next load.  I want to check that the log message has gone.

**Comment by kimrutherford** [comment]
I didn't fix the error.  It's now worse.  :-(


```
warning in cf34c0340e2dff28: storing feature_cvterm from SPCC162.04c.1 to cytoplasm [part_of] ascospore - failed to store feature_cvterm: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  duplicate key value violates unique constraint "feature_cvterm_c1"
DETAIL:  Key (feature_id, cvterm_id, pub_id, rank)=(96639, 171638, 3213, 0) already exists. [for Statement "UPDATE feature_cvterm SET cvterm_id = ? WHERE ( feature_cvterm_id = ? )" with ParamValues: 1='171638', 2='334862'] at /local-homes/pbuild/git/pombase-chado/lib/PomBase/Chado/ExtensionProcessor.pm line 323
```

**Comment by kimrutherford** [comment]
I've had another go at this.  I think it's fixed, but I'll check the load on Tuesday morning.

**Comment by kimrutherford** [comment]
> I've had another go at this. I think it's fixed, but I'll check the load on Tuesday morning.

My fix broke the load in different way so I tried yet again.  I've tested locally and it was OK.  I'll check again when tonight's load finishes.

In my latest attempt I had a good look at the code and it can now more precisely identify duplicates.  As a result it's now finding and reporting duplicate annotations in the Canto loading that weren't reported before.  I've made a separate issue about that: https://github.com/pombase/curation/issues/2949

**Comment by kimrutherford** [comment]
> My fix broke the load in different way so I tried yet again. I've tested locally and it was OK. I'll check again when tonight's load finishes.

It broke again.  Some duplicates were found in `pombe-embl/external_data/qualitative_gene_expression_data/Duncan_29432178.txt` and unfortunately the gene expression loading code is currently all or nothing.  If there is an error the whole load fails.

I've made an issue: pombase/curation#2951

**Comment by kimrutherford** [comment]
I think the code is OK now and the load worked.  There are extra warnings about duplicates but I think they're all real.  If there are any warnings that don't make sense, please let me know.
