### ISSUE TITLE
types of GI

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#738]
How many GI's do we have of each type. 
Is there a list in the log files. I can't see one?

**Comment by kimrutherford** [comment]
It's not in a log file.  Here's what Chado says:

| count | type |
----|-----
| 57037 | interacts_genetically |
| 15125 | interacts_physically |

**Comment by ValWood** [comment]
Sorry I wan't clear. I wanted GI by type

synthetic lethal etc (i.e how many of each evidence code)?

**Comment by kimrutherford** [comment]
Ah, sorry.  I mis-read that.

| count |          value          
|-------|-------------------------
| 14340 | Positive Genetic
|  2437 | Synthetic Growth Defect
|  1122 | Dosage Rescue
|  1323 | Synthetic Lethality
|  1570 | Phenotypic Suppression
|  1453 | Phenotypic Enhancement
|    93 | Dosage Lethality
|  1390 | Synthetic Rescue
| 33221 | Negative Genetic
|    88 | Dosage Growth Defect

**Comment by ValWood** [comment]
ok, not sur what I'm going to do with that information. I was curious if we used them all...
