### ISSUE TITLE
Update to the latest InterPro

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#740]
For after the conference.

https://www.ebi.ac.uk/interpro/beta/release_notes/

**Comment by ValWood** [comment]
can this be done now?

**Comment by kimrutherford** [comment]
> can this be done now?

I forgot about that.  I'm downloading the latest version now.

**Comment by kimrutherford** [comment]
The processing of the InterPro XML file have finished and is ready for Thursday night's update.  I'll check on Friday morning.

**Comment by ValWood** [comment]
I was going to check this but I'm not sure how I will know...

**Comment by kimrutherford** [comment]
The protein feature sections look OK.
