### ISSUE TITLE
Investigate load warnings

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#742]
loading HTP phenotype data from PMID_30647105_phaf
too many columns at line 2 starting with: 2019-06-18
too many columns at line 3 starting with: 2019-06-18
too many columns at line 4 starting with: 2019-06-18
too many columns at line 5 starting with: 2019-06-18
too many columns at line 6 starting with: 2019-06-18
too many columns at line 7 starting with: 2019-06-18
too many columns at line 8 starting with: 2019-06-18
too many columns at line 9 starting with: 2019-06-18
too many columns at line 10 starting with: 2019-06-18
too many columns at line 11 starting with: 2019-06-18
too many columns at line 12 starting with: 2019-06-18
too many columns at line 13 starting with: 2019-06-18
too many columns at line 14 starting with: 2019-06-18
too many columns at line 15 starting with: 2019-06-18
too many columns at line 16 starting with: 2019-06-18
too many columns at line 17 starting with: 2019-06-18
too many columns at line 18 starting with: 2019-06-18
too many columns at line 19 starting with: 2019-06-18
too many columns at line 20 starting with: 2019-06-18
too many columns at line 21 starting with: 2019-06-18
too many columns at line 22 starting with: 2019-06-18
too many columns at line 23 starting with: 2019-06-18
too many columns at line 24 starting with: 2019-06-18
too many columns at line 25 starting with: 2019-06-18
...

**Comment by mah11** [comment]
The warnings were accurate - there was an extra column in that phaf (oops, my bad). I've fixed the file. Reopen if that doesn't make the warnings go away!

**Comment by kimrutherford** [comment]
Thanks!  I'll check the next load.

**Comment by kimrutherford** [comment]
> Reopen if that doesn't make the warnings go away!

It's fixed.  Thanks.
