### ISSUE TITLE
display refs on Pombase families"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#745]
Henry Levin asked why 

" When I look at the pages for the Tf2s there is no reference to our Bowen et al paper in the literature section. That’s the paper that mapped and defined the coordinates of them. The wtf pages use the Bowen reference. Why isn’t it listed on the Tf2 pages. "

I couldn't figure out where the ref was coming from because I don't see it on the pages
but in Art it has:

/controlled_curation="term=wtf element; db_xref=PMID:12952871; date=20070223"

on the gene page:
	PBO:0002829	wtf element 25

**Comment by ValWood** [comment]
I'm adding 

/db_xref="PMID:12952871"

to the transposon features.
Will that be sufficient to get this publication to appear in the bibliography?

**Comment by kimrutherford** [comment]
There are a bunch of wtf element annotations on this page:

https://www.pombase.org/reference/PMID:12952871

Is that what was needed?

**Comment by ValWood** [comment]
yes but the reference (db_xref) does not show where  on the gene page (see protein feature section)

**Comment by kimrutherford** [comment]
> yes but the reference (db_xref) does not show where on the gene page (see protein feature section)

It's in the Literature section and I've just changed the configuration so that there is now a reference column in the "Families and domain annotated by PomBase" table.

> Will that be sufficient to get this publication to appear in the bibliography?

By bibliography do you mean the Literature section?

**Comment by ValWood** [comment]
> By bibliography do you mean the Literature section?

yes, sorry!

**Comment by ValWood** [comment]
OK is now appearing in the bibliography for both. Closing.
