### ISSUE TITLE
suppress "unknown" from check for same allele description

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#746]
This item in the chado_checks log (e.g. [today's](https://curation.pombase.org/dumps/builds/pombase-build-2019-12-12/logs/log.2019-12-12-21-58-10.chado_checks)):

    alleles with the same description that have different names - CHECK FAILURE:  expected 0 but got 3614

... has *tons* of spurious entries from "unknown" matching "unknown" for alleles of a gene that have different names and therefore could turn out to be different. The log would be a lot more useful if it only reported known descriptions.

**Comment by kimrutherford** [comment]
I've changed the check to ignore alleles with the description "unknown".  I'll have a look at the logs on Friday morning.

**Comment by kimrutherford** [comment]
The log looks OK now.  (it's still a long list though)
