### ISSUE TITLE
problem with non-ascii character check (chado_checks)

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#748]
From the 2020-01-07 build onwards, the chado_checks logs report non-ascii characters in feature names but don't give details, and the logs look truncated.

Specifically, https://curation.pombase.org/dumps/builds/pombase-build-2020-01-07/logs/log.2020-01-07-21-58-49.chado_checks and subsequent chado_checks logs have

    Check for non-ascii characters in feature names - CHECK FAILURE:  expected 0 but got 6

as the last line in the log. It doesn't give any hint what the offending names are, and also doesn't show the last few checks (list below) as though the ascii check fail is aborting the whole thing.

missing checks:
- Check that gene identifiers used in extensions exist
- annotation_with_no_evidence
- All duplicate GO annotation.  Columns are: count, systematic ID, gene name, term name, evidence, PubMed ID, 'with', session ID
- 'with' values that have an unsupported DB prefix
- relation ranges / annotation properties where the term is missing from the database, eg. from(...) or column_17(...)
- alleles with the same description that have different names

**Comment by mah11** [comment]
p.s. I also tried looking at the contig files and their svn logs, diff, etc. but nothing jumped out at me.

**Comment by kimrutherford** [comment]
There was an SQL error and that caused the Chado checking to stop.  Fixed now and I'll check the load on Friday morning.
