### ISSUE TITLE
new MONDO disease associations

### ISSUE THREAD

**Issue by Antonialock** [pombase/pombase-chado#749]
⁨currently, new disease associations between disease ontology (DO) and pombe genes are added to the file
 pombase_disease_associations
which lives in
external_data⁩ ▸ ⁨disease⁩

I made a new file for new disease associations made between MONDO and pombe genes. I used the same format as the old file
The new file is named 
mondo_pombase_disease_associations

**Comment by kimrutherford** [comment]
Hi Antonia.

I've just changed this line in mondo_pombase_disease_associations.txt:

     SPAC18G6.1     mal3    MONDO:0014755   ...

to

     SPAC18G6.15     mal3    MONDO:0014755   ...

Is that the right fix?

**Comment by kimrutherford** [comment]
> I've just changed this line in mondo_pombase_disease_associations.txt:

I meant to say that apart from that line, the file loads without a warning now that MONDO is in Chado.

**Comment by ValWood** [comment]
yep!

**Comment by ValWood** [comment]
> Is that the right fix?
yep

**Comment by Antonialock** [comment]
great, obvs can't check until the switch is live.

**Comment by kimrutherford** [comment]
> great, obvs can't check until the switch is live.

Thanks.  Once everything is ready to go, my plan is to do a test load on my desktop so you can check the things haven't gone too wrong.

**Comment by kimrutherford** [comment]
All live now on the main site.
