### ISSUE TITLE
malacards disease associations in logs

### ISSUE THREAD

**Issue by Antonialock** [pombase/pombase-chado#750]
There were 1100+ malacards gene-disease associations that didn't map to any DO term stuck in the logs. I can't load the FTP logs right now to link to the relevant file but it is called malacards_data

I have mapped these terms to mondo so that we can load them.

[Mondo mappings - malacards logs mappings.txt](https://github.com/pombase/website/files/4087177/Mondo.mappings.-.malacards.logs.mappings.txt)

**Comment by kimrutherford** [comment]
> Mondo mappings - malacards logs mappings.txt

There are some diseases in that file that I can't see in the files we load.  What am I missing.  An example is the first one:
```
anemia hypochromic microcytic with iron overload 1    MONDO:0000104
```
I can't see that disease name anywhere.

**Comment by Antonialock** [comment]
I ccan't access the log files when I tether of my mobile so I can't link to the file. 

This is thhe file I was mapping from though (one I downloaded in December rather than linking to the daily load)

it has
no DO ID for anemia_hypochromic_microcytic_with_iron_overload_1 -> SLC11A2 (SPAC27F1.08)


[log.2018-12-15-21-16-38.malacards_data.txt](https://github.com/pombase/pombase-chado/files/4113372/log.2018-12-15-21-16-38.malacards_data.txt)

**Comment by kimrutherford** [comment]
OK, thanks.  I think that solves the mystery.  I was searching for the string
"anemia hypochromic microcytic with iron overload 1" - with no underscores.
In malacards_data_for_chado.tsv it's:
```
anemia, hypochromic microcytic, with iron overload 1       anemia_hypochromic_microcytic_with_iron_overload_1      Anemia, Hypochromic Microcytic, with Iron Overload 1    SLC11A2
```

**Comment by Antonialock** [comment]
ah yes they are all underscored in the logs

**Comment by mah11** [comment]
depends which log - the malacards_data logs have underscores; disease items in qualifier_problems.txt don't (and yeah, disease stuff in both places :P )

**Comment by kimrutherford** [comment]
Antonia, could you remind me: does malacards_data_for_chado.tsv include human genes where there isn't a pombe ortholog?

**Comment by kimrutherford** [comment]
I've had a go at this now.  I've added a new file in Subversion with the DO IDs mapped to MONDO:
  external_data/disease/malacards_data_for_chado_mondo_ids.tsv

Once the other changes are ready we should load this new file instead of the malacards_data_for_chado.tsv

**Comment by Antonialock** [comment]
> Antonia, could you remind me: does malacards_data_for_chado.tsv include human genes where there isn't a pombe ortholog?

yes it does

**Comment by kimrutherford** [comment]
> yes it does

Thanks.  I think we're mostly ready to try switching to MONDO.  I'll try this week.

**Comment by ValWood** [comment]
exciting!

**Comment by kimrutherford** [comment]
I've done a test load it's all more or less working I think.  There are warnings while loading the new MalaCards data file (pombe-embl/external_data/disease/malacards_data_for_chado_mondo_ids.tsv) but not that many.  Could you have a look and see if any of these error are major problems?

[malacards.log.txt](https://github.com/pombase/pombase-chado/files/4573906/malacards.log.txt)

**Comment by ValWood** [comment]
Seems that there was a merge if Leigh  syndrome probably merged

https://github.com/monarch-initiative/mondo/issues/675

ClinGen Mitochondrial Disease Gene Curation Expert Panel has chosen to curate under the MONDO ID MONDO:0009723, specifically for the nomenclature of Leigh Syndrome.

**Comment by ValWood** [comment]
and
https://github.com/monarch-initiative/mondo/pull/1141

**Comment by ValWood** [comment]
id: MONDO:0008289
name: porencephaly 1
name: brain small vessel disease 1 with or without ocular anomalies
seems to be the new ID for brain_small_vessel_disease_with_or_without_ocular_anomalies

**Comment by kimrutherford** [comment]
Is there anything else to do here?

**Comment by ValWood** [comment]
I think this is  all OM. There are some issues in the logs  I think from name changes to Artemis.

I'm going to delete these from Artemis and make additions to the MONDO file.
