### ISSUE TITLE
Moving to MONDO from DO 

### ISSUE THREAD

**Issue by Antonialock** [pombase/pombase-chado#751]
I have mapped the DO terms we are currently using to MONDO.

updated file with typo and id fix:
[Mondo_mappings_-_Mondo_to_DO_existing_annotations_mappings.txt](https://github.com/pombase/pombase-chado/files/4108423/Mondo_mappings_-_Mondo_to_DO_existing_annotations_mappings.txt)

old file:
~[Mondo mappings - Mondo to DO existing annotations mappings.txt](https://github.com/pombase/website/files/4087174/Mondo.mappings.-.Mondo.to.DO.existing.annotations.mappings.txt)~

**Comment by ValWood** [comment]
Brilliant. Exciting to see how many disease genes we have now!

**Comment by Antonialock** [comment]
currently 982....stay tuned..

**Comment by kimrutherford** [comment]
MONDO:0009053 and MONDO:0027451 appear twice.  Is that expected?

```
MONDO:0027451   DOID:0070140
MONDO:0027451   DOID:0070129
```

```
MONDO:0009053   DOID:0070143
MONDO:0009053   DOID:0070132
```

**Comment by kimrutherford** [comment]
As a first step, MONDO is now loaded into Chado during the nightly load.

**Comment by kimrutherford** [comment]
We load `pombe-embl/chado_load_mappings/pombase_disease_name_to_DOID_mapping.txt` to map  existing "term=disease associated" annotation in the contig files to DO terms.  We'll need a similar file for mapping to MONDO.

I had a look at doing that but these DO IDs from that file aren't in your mapping file:

        DOID:0050427
        DOID:0050776
        DOID:0050977
        DOID:0080134
        DOID:1056
        DOID:10579
        DOID:906
        DOID:9268
        DOID:9269
        DOID:9278

**Comment by Antonialock** [comment]
That's odd - I can see these in the text file linked above.

I did spot 2 or 3 typos though - "ONDO" instead of "MONDO" - I have fixed these and updated the above file
> 
> I had a look at doing that but these DO IDs from that file aren't in your mapping file:
> 
> ```
>     DOID:0050427
>     DOID:0050776
>     DOID:0050977
>     DOID:0080134
>     DOID:1056
>     DOID:10579
>     DOID:906
>     DOID:9268
>     DOID:9269
>     DOID:9278
> ```

**Comment by Antonialock** [comment]
and fixed ID

**Comment by kimrutherford** [comment]
> That's odd - I can see these in the text file linked above.

Yep, sorry, I got my command line wrong.  All the IDs are there.  I'll go ahead and make a new mapping file for Chado loading.

**Comment by Antonialock** [comment]
super!

**Comment by kimrutherford** [comment]
>  All the IDs are there.

Unfortunately my command line was still messed up.  :-)

It looks like there is one ID in the Chado mapping file that's not in the DO to MONDO file, DOID:0070275 from:
```
hereditary nonpolyposis colorectal cancer type 4        DOID:0070275
```

Everything else looks good.

**Comment by kimrutherford** [comment]
I've added preliminary version of the new mapping file to subversion:
  pombe-embl/chado_load_mappings/disease_name_to_MONDO_mapping.txt

We can add the missing "hereditary nonpolyposis colorectal cancer type 4" mapping later.

I wanted to add it so that I could work on the Chado loading side of things.  I'm going to do local testing first and then when it looks OK we can try a test run in the nightly load.

**Comment by kimrutherford** [comment]
Do we need a new PB_REF?

The current annotations have this reference which doesn't mention MONDO:
https://www.pombase.org/reference/PB_REF:0000003

**Comment by Antonialock** [comment]
MONDO:0013699 for
"hereditary nonpolyposis colorectal cancer type 4"  

yes pb ref needs updating, I  did a text change and swapped MONDO for DO in the svn "supporting files"  @mah11  is that ok to do?

**Comment by ValWood** [comment]
@cmungall if it is useful @Antonialock  did a manual mapping of all of the DO IDs we were using to (939). Top of this ticket. Is this useful for you? (Even if you have a mapping it might be a good double check)?.

**Comment by kimrutherford** [comment]
Hi Antonia.  I'm working on mapping the term IDs in pombase_disease_associations.txt to MONDO IDs.   There are some DO IDs in the associations file that aren't in your mapping file.  Is that expected?

[doids_with_no_mapping.txt](https://github.com/pombase/pombase-chado/files/4519467/doids_with_no_mapping.txt)

**Comment by Antonialock** [comment]
> 
> 
> Hi Antonia. I'm working on mapping the term IDs in pombase_disease_associations.txt to MONDO IDs. There are some DO IDs in the associations file that aren't in your mapping file. Is that expected?
> 

Have we annotated to them? I spot checked a few and can't see them on the website using the simple search

**Comment by kimrutherford** [comment]
Some of them are not loaded because of warnings:
  https://curation.pombase.org/dumps/latest_build/logs/log.2020-04-22-22-01-15.disease_associations

The DO OBO file we load is from 2018-10-24.  Sorry I haven't set up the load so that it is updated automatically.  Should I update to the latest DO OBO for tonight's load?

**Comment by Antonialock** [comment]
So following an update there will be a number of DO terms that need mapping to Mondo?

**Comment by kimrutherford** [comment]
> So following an update there will be a number of DO terms that
> need mapping to Mondo?

Yep.  I'll update to the latest DO OBO for tonight's load.  I'll let you know tomorrow if there are any problems.

**Comment by kimrutherford** [comment]
> I'll let you know tomorrow if there are any problems.

The load failed but I think I've fixed it for tomorrow.  The latest doid.obo had a definition for the is_a relation so we ended up with two definitions for is_a in Chado.  That didn't work out well.  The quick fix was to edit the doid.obo file and remove the is_a defintion.

**Comment by kimrutherford** [comment]
> The load failed but I think I've fixed it for tomorrow. 

That worked so there are now 2588 disease annotations instead of 2528.

**Comment by kimrutherford** [comment]
We're getting there.  In my local Chado load there are 1135 genes with associated MONDO terms. If you'd like to have a look, go to the test site on my desktop: http://desktop.kmr.nz:4242/

My desktop version is available until about 1pm UK time each day.  The autocomplete isn't available for disease terms.

I haven't checked in any of these changes yet.

![mondo-1](https://user-images.githubusercontent.com/90474/81032540-5a7c3a80-8ee4-11ea-8461-95643c8855a1.png)

**Comment by ValWood** [comment]
Nice! and a nice increase 1005-> 1135

https://github.com/pombase/website/issues/1506> 
(it would be funny if the remapping gets us over 1113 because then pombe would have a higher percentage of human disease-associated genes than human ;)))

It's official. Pombe has a higher % of disease causing genes than human.  How funny ;)

**Comment by ValWood** [comment]
I'm sure it will be fine.
Should I have a stab at the slim remapping or can that be automated too?

**Comment by kimrutherford** [comment]
> Should I have a stab at the slim remapping or can that be automated too?

I'll map them over automatically as a starting point but I assume that will need a lot of tweaking.  Perhaps the MONDO curators have something like a slim already?

**Comment by kimrutherford** [comment]
Here's the list of terms in the slim that can be mapped using the DO -> MONDO mapping file.  And a log file containing the IDs that don't map:

[slim_mapped.tsv.txt](https://github.com/pombase/pombase-chado/files/4584678/slim_mapped.tsv.txt)
[slim_update.log.txt](https://github.com/pombase/pombase-chado/files/4584679/slim_update.log.txt)

**Comment by ValWood** [comment]
> Perhaps the MONDO curators have something like a slim already?
I'd be surprised if they do @cmungall ?

**Comment by ValWood** [comment]
@Antonialock 
maybe you only mapped the directly annotated terms, as I am presuming these are in MONDO?

can't find: DOID:0050013 (carbohydrate metabolism disease)
can't find: DOID:870 (neuropathy)
can't find: DOID:1289 (neurodegenerative disease)
can't find: DOID:607 (paraplegia)
can't find: DOID:1443 (cerebral degeneration)
can't find: DOID:1561 (cognitive disorder)
can't find: DOID:0080006 (bone development disease)
can't find: DOID:2355 (anemia)
can't find: DOID:557 (kidney disease)
can't find: DOID:3118 (hepatobiliary disease)
can't find: DOID:9120 (amyloidosis)
can't find: DOID:2914 (immune system disease)
can't find: DOID:0050177 (monogenic disease)
can't find: DOID:0050736 (autosomal dominant disease)
can't find: DOID:0050737 (autosomal recessive disease)

**Comment by ValWood** [comment]
...addinf them now

**Comment by ValWood** [comment]
all mapped above.

**Comment by Antonialock** [comment]
ta!

**Comment by kimrutherford** [comment]
Thanks.  All of the original slim terms have MONDO terms now.  You should be able to see the slim page here:
http://desktop.kmr.nz:4242/browse-curation/disease-slim

**Comment by kimrutherford** [comment]
> http://desktop.kmr.nz:4242/browse-curation/disease-slim

The text on that page needs updating.

Here's the current text.  Let me know what you'd like instead.

---------------

Disease Ontology slim

A “slim” is a high-level subset of terms from an ontology, used to analyze sets of annotated genes. The table below shows a slim set of grouping terms that we have selected from the Disease Ontology (DO), and the number of annotations to each term. DO IDs link to PomBase ontology term pages. The annotation totals link to pages with information about the term and a list of annotated genes. A gene may be included in the annotation sets for more than one slim term.

If you would like to have any terms added to the DO slim, please contact the helpdesk.

**Comment by ValWood** [comment]
I don't see the slim (only the text)

**Comment by kimrutherford** [comment]
Sorry about that.  Could you try again?

**Comment by kimrutherford** [comment]
Some MONDO terms don't have definitions, like:
http://desktop.kmr.nz:4242/term/MONDO:0017828
http://desktop.kmr.nz:4242/term/MONDO:0015962

**Comment by kimrutherford** [comment]
> Here's the current text. Let me know what you'd like instead.

We also need to change the "External links" section on the term pages to point to MONDO.  What should we link to?

http://desktop.kmr.nz:4242/term/MONDO:0004992

**Comment by ValWood** [comment]
Looks good. A good increase for most. I will sanity check these:

<img width="1040" alt="Screenshot 2020-05-07 at 09 34 48" src="https://user-images.githubusercontent.com/7359272/81273569-fa51d980-9046-11ea-8e53-8dd5269b96a2.png">

**Comment by ValWood** [comment]
When I first started looking I could access the lists, but not I cant (I get tot he page but the annotations don't load).

Is it possible to reboot or something?

**Comment by ValWood** [comment]
can we get a list of the terms we use with no definitions?

**Comment by kimrutherford** [comment]
I haven't changed anything but it's probably going to be a bit flakey to access it on my desktop.

> can we get a list of the terms we use with no definitions?

I'll do that.

**Comment by kimrutherford** [comment]
> can we get a list of the terms we use with no definitions?

There are lots:

[mondo_terms_no_definition.tsv.txt](https://github.com/pombase/pombase-chado/files/4592665/mondo_terms_no_definition.tsv.txt)

**Comment by ValWood** [comment]
Reported missing definitions 
https://github.com/monarch-initiative/mondo/issues/1487

**Comment by kimrutherford** [comment]
Is the DO to MONDO change ready to go?  I think a Friday or Saturday night would be a good time to try it out in the main Chado load.  It could be this weekend if we're ready.

**Comment by ValWood** [comment]
Just a bit longer. We might be able to do it this weekend. I will have a better idea tomorrow.

**Comment by kimrutherford** [comment]
> Just a bit longer. We might be able to do it this weekend. I will have a better idea tomorrow.

OK.  I'm doing a new local load now with your mapping fixing.  I'll let you know how that goes.

**Comment by kimrutherford** [comment]
> OK. I'm doing a new local load now with your mapping fixing. I'll let you know how that goes.

That's done now.  There are 1183 disease genes:
http://desktop.kmr.nz:4242/results/from/id/c72d1a18-ff11-4cca-a1f8-ad391c0b7740

Here's the slim:
http://desktop.kmr.nz:4242/browse-curation/disease-slim

**Comment by ValWood** [comment]
Looking good. 
Can we have a c category for "annotations with a disease association that does not map to the slim"

This will help us to see if we should include any other classes in the slim.

**Comment by ValWood** [comment]
But I think we can make the switch anyway. The rest is just tweaking...

**Comment by ValWood** [comment]
actually, don't swithcxh yet. I would like to check all of the differences, I can see other p[possible Modo issues. It's easier to do the checks if I can still access the DO lists.

**Comment by kimrutherford** [comment]
Let me know when you make changes so I can re-run the load on my desktop.

**Comment by ValWood** [comment]
I can't do the checking because I can't see the current version. I'm comparing the before and after lists.

**Comment by ValWood** [comment]
its gone again so maybe you are updating?

I get
**Failed to compile.
Path "/home/kmr44/pombase-www-new/src/docs/browse-curation/.#disease-slim.md" does not exist.
**

but I'm going for a run now so don't hurry to get it back up if you are working on the other slim stuff. Just let me know when it's back.

**Comment by kimrutherford** [comment]
It's not a show-stopper but one of the slim terms has no annotations: http://desktop.kmr.nz:4242/term/MONDO:0024238

Is that expected?

**Comment by kimrutherford** [comment]
All the changes are checked in, ready for Wednesday night's load.  I'll check things are OK on Thursday morning before updating the main site.

**Comment by ValWood** [comment]
That one is reported
https://github.com/monarch-initiative/mondo/issues/1486

On the curation tracker I have a list of the  slim terms linked to the related MONDO  tickets spawned
https://github.com/pombase/curation/issues/2700

I did a direct comparison of the old/new lists for most terms (missed 5 because  they were big increases, and I can eyeball them later).

**Comment by kimrutherford** [comment]
> All the changes are checked in, ready for Wednesday night's load. I'll check things are OK
> on Thursday morning before updating the main site.

Done!

https://www.pombase.org/browse-curation/disease-slim

**Comment by ValWood** [comment]
We are done here...
