### ISSUE TITLE
allele synonyms to load

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#752]
After several rounds of forgetting, I have at last remembered to open this ticket to get a bunch of allele synonyms added. They're in the attached file (.txt extension to please GitHub, but it's tsv on the inside). It just has two columns, 'name' and 'synonym'. Let me know if you need any more info, or a different file format/syntax, or whatever.

[allele_synonyms_to_load.txt](https://github.com/pombase/pombase-chado/files/4160383/allele_synonyms_to_load.txt)

**Comment by kimrutherford** [comment]
As a first step, I had a look to make sure all of the allele names where in Chado.  The missing ones are below.

There were three names ("mcm7-KA-HA", "mcm7-KR-HA" and "mcm7-DA-HA") that were missing but alleles with similar names were in Chado:

```
mcm7-KA-HA-C
mcm7-KA-HA-N
mcm7-KR-HA-N
mcm7-KR-HA-C
mcm7-DA-HA-C
mcm7-DA-HA-N
```
(all from session `0d06afc3089ee763`)

And "rad51-II3A" was missing but there is an allele named "rad51-II3A(rad51-3A)" from session `6a42f3bfbbc08463`.

"SPAPB2B4.04cdelta", "aindelta" and "fimdelta" were missing too but we will handle those as a special case.  For deletions we don't store an allele name in Chado as the name can be inferred from the gene name or ID.

--------------------------

Missing allele names:

```
 mcm2delta::his3+
 mcm4delta::his3+
 mcm5delta::his3+
 mcm6delta::his3+
 dfp1delta::ura4+
 cdc25-rr43
 mcm4-2T-2A
 mcm4-2T-2S
 mcm4-2T-2E
 mcm6-KR-HA
 mcm6-DA-HA
 mcm7-KA-HA
 mcm7-KR-HA
 mcm7-DA-HA
 rad15delta::LEU2
 cdc2-F84G
 top2-Sma
 top2-Xba
 cdc19-D5
 Ppb1deltaC
 myo2delta-IQ2
 orb1-167
 rad51-II3A
```

**Comment by mah11** [comment]
Thanks. Some of the "missing" items (e.g. `fimdelta` must be fim1delta)  are almost certainly typos, so I'll go through and check the original list.

**Comment by mah11** [comment]
OK, I've gone through the list ...

> mcm2delta::his3+
> mcm4delta::his3+
> mcm5delta::his3+
> mcm6delta::his3+

I see these in [6998329e8f9ad0bc](https://curation.pombase.org/pombe/curs/6998329e8f9ad0bc/genotype_manage/ro), although with the greek-letter 'delta' display handling they appear as mcm2Δ::his3+ etc. Could that explain why they seem to be missing? If so, the same would apply to `dfp1delta::ura4+` and `rad15delta::LEU2`.

**Comment by mah11** [comment]
For the rest, I've made some corrections and am uploading an updated list.
[corrected_allele_synonyms_2021-03-26.txt](https://github.com/pombase/pombase-chado/files/6212928/corrected_allele_synonyms_2021-03-26.txt)

**Comment by kimrutherford** [comment]
I've looked a bit closer at this.  I had forgotten that a synonym in Chado needs a reference or publication.  It could be a new "PB_REF".  Or alternatively we have a "null" reference for cases where a reference/publication doesn't make sense.  Let me know what you'd like to do.

**Comment by kimrutherford** [comment]
> For the rest, I've made some corrections and am uploading an updated list.

Thanks.

Just to check, is this two synonyms or does the synonym contain a space?:
```
spt5-delta-CTD  1-835 deltaCTD
```

Could you add your synonyms file to SVN?

**Comment by mah11** [comment]
OK, the file is now in SVN at `pombe-embl/supporting_files/allele_synonyms.txt`.

I'll look at that funny spt5 synonym and see which ones I can dig up references for later today or tomorrow (after I do some FYPO work).

**Comment by kimrutherford** [comment]
> I see these in 6998329e8f9ad0bc, although with the greek-letter 'delta' display handling they appear as mcm2Δ::his3+ etc. Could that explain why they seem to be missing? If so, the same would apply to dfp1delta::ura4+ and rad15delta::LEU2.

It's worse than that - all deletion names are missing: https://github.com/pombase/pombase-chado/issues/824
I'll fix that first thing tomorrow for the next load.

Meanwhile, the allele synonym loading code is ready to go.

> OK, the file is now in SVN

Thanks.  I'll hopefully be able to fix #824 and activate the loading code before Tuesday night's load.

**Comment by mah11** [comment]
> It's worse than that - all deletion names are missing: #824

oopsy ...

I'll ping here when I get refs into the file, since it'll be a biggish change. For some of them, I was just looking at the papers the other day so I might as well fill in the PMIDs. It'll only take me a few minutes to craft a PB_REF for the rest.

**Comment by kimrutherford** [comment]
> I'll ping here when I get refs into the file, since it'll be a biggish change. For some of them, I was just looking at the papers the other day so I might as well fill in the PMIDs. It'll only take me a few minutes to craft a PB_REF for the rest.

Thanks.  No rush.

**Comment by kimrutherford** [comment]
> OK, the file is now in SVN at pombe-embl/supporting_files/allele_synonyms.txt.

I've changed spaces to tabs in the file.

**Comment by kimrutherford** [comment]
Is this synonym needed?

> SPAPB2B4.04cdelta       pmc1delta

SPAPB2B4.04c is pmc1

**Comment by ValWood** [comment]
> Is this synonym needed?

probably not It might have been included if it was called that in a publication for text mining/pattern matching purposes......but we probably don't really need to record that.

**Comment by mah11** [comment]
> Is this synonym needed?
> 
>>    SPAPB2B4.04cdelta pmc1delta

No. My guess is that I saw "pmc1delta" used before the gene name was assigned.

**Comment by mah11** [comment]
I added a "reference" column to the synonym file. A few lines have PMIDs; the rest have a new PB_REF I also just added.

**Comment by kimrutherford** [comment]
> I added a "reference" column to the synonym file. A few lines have PMIDs; the rest have a new PB_REF I also just added.

Thanks.  I'll close this issue once they're successfully loaded.

**Comment by kimrutherford** [comment]
I've added a missing reference for
```
pol1-ts13      polalpha-ts13
```
I put in a PB_REF since I didn't know better.

I also removed an extra PB_REF from this line:
```
hsk1-KK        hsk1-ka PB_REF:0000004  PB_REF:0000004
```

**Comment by kimrutherford** [comment]
This has been working fine for a few days now.

**Comment by mah11** [comment]
Thanks for the whole lot, including the little fixes.
