### ISSUE TITLE
allele comments to load

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#753]
Similar to #752, but for comments that should connect to alleles.

 For this one the uploaded file has 'name' and 'comment' columns. Holler if it needs work.

[allele_comments_to_load.txt](https://github.com/pombase/pombase-chado/files/5355867/allele_comments_to_load.txt)

**Comment by mah11** [comment]
note to self: two more to add

     spt5-T1A    description refers to position within each CTD repeat
     spt5-T1E    description refers to position within each CTD repeat

**Comment by mah11** [comment]
updated attached file

**Comment by kimrutherford** [comment]
Are there any references for the comments?

**Comment by mah11** [comment]
Lost in the mists of time for the ones in the attachment here, I'm afraid :/

More generally, sometimes we'll be able to attribute a comment to a paper, but others will pretty much be made up by one of us.

**Comment by kimrutherford** [comment]
Do the allele comments need to be shown on the website.  If so, where?

**Comment by ValWood** [comment]
Depending how sensibly we have crafted them we could put them on the allele pages?
https://github.com/pombase/website/issues/1294

I have a feeling  these are more 'formal' than annotation comments, and probably not much used yet so we could probably easily fix any crud.

**Comment by mah11** [comment]
I don't think I gave adequate thought to how & where to use this info, but it would make sense to show them on allele pages. I woudn't bother on gene pages; genotype pages are kind of a grey area so I'd flip a coin if nobody else has a strong opinion.

They're terse but reasonably presentable.

**Comment by kimrutherford** [comment]
Conveniently, we have a loader for feature properties like this that reads from TSV files.  It needed a tweak to handle input files with feature names rather than systematic IDs (`uniquename` in Chado-speak).  Alleles don't have useful systematic IDs at the moment so putting the names in the input file makes sense.

I'll do a local load and then add the comments to the main load in the next day or two.

(Then we can worry about where the comments should appear on the website)

**Comment by kimrutherford** [comment]
I've added the file to SVN as `pombe-embl/supporting_files/allele_comments.txt`

I noticed one line where the comment column is empty:
```
mei4Δ(828-1554nt)::GFP
```

**Comment by kimrutherford** [comment]
> I noticed one line where the comment column is empty

I've commented that out in the file.

There are a few other warnings:
```
line 2: searched for name - can't find feature for: sre1-N(441-900)
line 7: searched for name - can't find feature for: Rlc1p-DD
line 8: searched for name - can't find feature for: Myo2p-S1444D
line 23: searched for name - can't find feature for: nmt1:pyp3
line 30: searched for name - can't find feature for: mdn1-ts2
```

**Comment by kimrutherford** [comment]
I've added the allele comment loading to the nightly script.  It works fine locally.  I'll check the main load on Wednesday morning.

**Comment by mah11** [comment]
Thanks! I'll check up on the oddities and commit fixes as & when.

**Comment by mah11** [comment]
I did some fixes (and commented out another one)
