### ISSUE TITLE
curated papers graph (A)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#754]
Time between publication and curation, with number of reminders sent

https://curation.pombase.org/kmr44/curated_sent_counts_graph-1.png

bin all>10 years into a single bin
these will mainly be Jacky

I wonder if most of the zero reminders remaining are Jacky selecting the papers herself?
Or has anyone else done this?
After the update it would be interesting to see who they are...

I think we can use this to say
1) papers are usually curated  in the same year as published
2) Older publications will still be curated but require more reminders
3) A very small number papers were not curated until 6th reminder

**Comment by kimrutherford** [comment]
> bin all>10 years into a single bin

So should we have a bin for each year until 10 years?

**Comment by ValWood** [comment]
Yes please.

**Comment by ValWood** [comment]
Actually, we need a slightly different graph  to say that people are more. likely to curate papers close to publication date. I will open another ticket for this.

**Comment by ValWood** [comment]
We will probably still use this graph to show curation/reminder number

**Comment by kimrutherford** [comment]
Here is the graph from last night's Chado and the spreadsheet I used: https://curation.pombase.org/kmr44/binned_curated_sent_count-v2.ods

What changes are needed?

![curated_resent_counts_v2](https://user-images.githubusercontent.com/90474/74137477-c1c37f00-4c54-11ea-8579-a8418e9021d5.png)

**Comment by ValWood** [comment]
Axis will be

x Years between first request  to curate and curation submission
y  Number of papers
Key =number of reminders

I think we should bin everything over 5 years in this graph.

We can use this one to show that repeat requests work.

**Comment by kimrutherford** [comment]
How's this?:

![uncurated_sent_counts_graph-v3](https://user-images.githubusercontent.com/90474/74188898-45f91f00-4cb4-11ea-984c-170cbadb6a1e.png)

**Comment by kimrutherford** [comment]
It took me a while but I've now worked out how to change colours.  :-)

Let me know if you'd like changes.

**Comment by ValWood** [comment]
Just to check, this graph is called uncurated_sent_counts., but it's curated right?

**Comment by ValWood** [comment]
I'm still interested in the "0" times sent out int eh curated graph. Are these all JAcky, or are other people self -selecting (need to know this, because we always say that nobody does ;)

**Comment by kimrutherford** [comment]
> I'm still interested in the "0" times sent out in the "curated" graph.

I've add a new report to help: "Community sessions never sent".  It includes all sessions that have had a non-admin curator at any point because that was easier to query.  So there are a couple of session the show you, Midori or Antonia as the curator.  In those case you're the current curator.

**Comment by kimrutherford** [comment]
> Just to check, this graph is called uncurated_sent_counts., but it's curated right?

Whoops.  I just checked and it's the file name that was wrong.  The graph is OK.

> I'm still interested in the "0" times sent out in the "curated" graph.

Does it make sense to remove the 0 times sent values from the graph?

**Comment by ValWood** [comment]
Most are old. I think they might be sessions done as part of the pilot or very early on?
A lot are Jacky.
Some are sessions we stole back for some reason.
Some are sessions  where the curation was largely in spreadsheets.

I think we *could* leave these out of the graph as they are odd bods and outliers, and difficult to explain. In this particular  graph we are really only looking "how effective are repeat reminders" so omiting this would not really distort anything.

**Comment by kimrutherford** [comment]
> I think we could leave these out of the graph as they are odd bods and outliers, and difficult to explain. 

OK.  I'm off to bed now but I'll do that as my first job tomorrow.

**Comment by ValWood** [comment]
Great. could you do this second?
https://github.com/pombase/pombase-chado/issues/756
cheers,

**Comment by kimrutherford** [comment]
> I think we could leave these out of the graph as they are odd bods and outliers, and difficult
> to explain.

How's this?:
![curated_sent_counts_graph-v4](https://user-images.githubusercontent.com/90474/74274262-b0729380-4d76-11ea-8807-dc9b9e9480a3.png)

**Comment by ValWood** [comment]
I think that works.
I  will write some txt to include this one.

Can the years be
0-1, 1-2 etc?

**Comment by kimrutherford** [comment]
> Can the years be
> 0-1, 1-2 etc?

Like this?:

![curated_sent_counts_graph-v5](https://user-images.githubusercontent.com/90474/74277431-65f41580-4d7c-11ea-888e-658f3c8b5b35.png)

**Comment by ValWood** [comment]
yep, thanks

**Comment by kimrutherford** [comment]
Same, but with a better size for the labels:
![curated_sent_counts_graph-v6](https://user-images.githubusercontent.com/90474/74407310-a1830280-4e96-11ea-8b7d-7de6cf9f43b3.png)

**Comment by ValWood** [comment]
The number in the 5 year bin seems to have dropped from earlier versions of the graph. At the top it appears to be ~25 not it seems to be about ~10?

**Comment by ValWood** [comment]
Number of papers -> number of curated papers

**Comment by ValWood** [comment]
The number in the 5 year bin seems to have dropped from earlier versions of the graph. At the top it appears to be ~25 not it seems to be about ~10?

i.e I would have expected the  5+ bin to be larger than the 4-5 bin
<img width="534" alt="Screenshot 2020-02-13 at 17 33 41" src="https://user-images.githubusercontent.com/7359272/74461822-0cc4d880-4e87-11ea-9ec0-1c3ed882822f.png">

**Comment by ValWood** [comment]
Number of papers -> number of curated papers

instead of 5- would 5+ be clearer?

**Comment by kimrutherford** [comment]
> i.e I would have expected the 5+ bin to be larger than the 4-5 bin

Thanks for spotting that.  It looks like the numbers were wrong for all the bins.

This looks better.  I'll do a tidy version if it looks OK:

![curated_sent_counts_graph-v8](https://user-images.githubusercontent.com/90474/74521598-7bd12880-4f7e-11ea-8675-a5b4074b947b.png)

**Comment by ValWood** [comment]
Yes, great go ahead. I think this one is OK now @Antonialock ?

**Comment by Antonialock** [comment]
have we really got 35 or so sessions back after 5+ years with no reminders? (red in bin 5+)

**Comment by ValWood** [comment]
Mostly Jacky....I think. Some are  also be HTP datasets assigned to the submitter and "approved" after the tracks were submitted.

**Comment by ValWood** [comment]
Kim provided a list at some point ....
I forgot which ticket. I don't think i would have hidden that comment but I can't see it in here.

**Comment by kimrutherford** [comment]
> Kim provided a list at some point ....
> I forgot which ticket. I don't think i would have hidden that comment but I can't see it in here

Can you remind me which list you mean?  It's easy to re-create from Chado.

**Comment by ValWood** [comment]
found it above

>>I'm still interested in the "0" times sent out in the "curated" graph.

> I've add a new report to help: "Community sessions never sent". It includes all sessions that have had a non-admin curator at any point because that was easier to query. So there are a couple of session the show you, Midori or Antonia as the curator. In those case you're the current curato


So:
https://curation.pombase.org/pombe/track
https://curation.pombase.org/pombe/view/list/community_sessions_never_sent?model=track

mainly
1) JAcky & Ryoko
2) Sessions with HTP data (E.g. JAnel Beckley)
3) The ones that were done for the pilot (I put these through because I didn't want people to have to do them again)
4) Some that have been "reclaimed" by us. We don't do this currently.
5) some really do appear to be selected by the author (i.e the Chris Norbury ones, some Sophie MArtin ones, Shajahan Anver and others) have curation by the author?

**Comment by Antonialock** [comment]
it looks a bit confusing to conglomerate things that were sent out for the first time in year two?

did we really send 4 reminders for a proportion of papers in year one?

to me it just looks like "**Fig 4 Sending reminders work**: a number of people will curate their papers on first email, sending a reminder will catch more people, continuous nagging will pick up even more"

**Comment by ValWood** [comment]
> it looks a bit confusing to conglomerate things that were sent out for the first time in year two?

I don't understand this comment. This graph is time between publication and curation?

> did we really send 4 reminders for a proportion of papers in year one?

Almost certainly. I now send reminders more frequently, and I'm more likely to send reminders sooner for newer papers.

> to me it just looks like "Fig 4 Sending reminders work: a number of people will curate their papers on first email, sending a reminder will catch more people, continuous nagging will pick up even more"

but this is exactly what the reviewers were asking about?

The graph shows

Papers are usually curated in the same year as published
Older publications will still be curated but require more reminders
A very small number papers were not curated until 6th reminder (so sending more reminders works a bit)

**Comment by ValWood** [comment]
> it looks a bit confusing to conglomerate things that were sent out for the first time in year two?

I don't understand this comment. This graph is time between publication and curation?

> did we really send 4 reminders for a proportion of papers in year one?

Almost certainly. I now send reminders more frequently, and I'm more likely to send reminders sooner for newer papers.

> to me it just looks like "Fig 4 Sending reminders work: a number of people will curate their papers on first email, sending a reminder will catch more people, continuous nagging will pick up even more"

but this is exactly what the reviewers were asking about?

The graph shows

Papers are usually curated in the same year as published
Older publications will still be curated but require more reminders
A very small number papers were not curated until 6th reminder (so sending more reminders works a bit)

**Comment by ValWood** [comment]
Note this isn't about the time  between published and sent out, its the time between sent out and curation.

**Comment by ValWood** [comment]
Note this isn't about the time  between published and sent out, its the time between sent out and curation.

**Comment by ValWood** [comment]
Note this isn't about the time  between published and sent out, its the time between sent out and curation.

**Comment by ValWood** [comment]
Note this isn't about the time  between published and sent out, its the time between sent out and curation.

**Comment by ValWood** [comment]
Note this isn't about the time  between published and sent out, its the time between sent out and curation.

**Comment by ValWood** [comment]
Sorry GitHub is having a wobbly!

**Comment by ValWood** [comment]
Actually, this got mixed up.
This IS the graph for 
time published  and length of time before curation with number of requests.
This means the axis labels were wrong?. KIm can you confirm that this is what it is.

**Comment by ValWood** [comment]
Change of tack.

We now decided to simplify and show:

Number of papers curated vs. number of reminders sent

**Comment by kimrutherford** [comment]
Here are the raw numbers I get for reminder count vs publication count for curated publications.  I'm happy to make a graph but it will look better if done in Excel.

```
sent_count,pub_count
0,114
1,424
2,168
3,75
4,18
5,6
6,1
```

**Comment by ValWood** [comment]
@Antonialock should we omit the zero bin from the graph. These were mainly either pilot, or HTP spreadsheet, browser track etc so the contact was made in a different way. They aren't relevant to the question about reminder number

**Comment by Antonialock** [comment]
yes makes sense

**Comment by Antonialock** [comment]
Kim can you confirm that this is howing "session sent count" and not "reminder count" ?

**Comment by kimrutherford** [comment]
> Kim can you confirm that this is howing "session sent count" and not "reminder count" ?

It's the session sent counts.  Subtract 1 from the first column to get the reminder counts.

**Comment by Antonialock** [comment]
happy with this too!

![image](https://user-images.githubusercontent.com/12727506/75392610-49132280-58e4-11ea-923a-eb637c28bb9d.png)
