### ISSUE TITLE
papers curated close to publication date (graph C)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#756]
I think we need to do this something like:

publication date - date sent out for curation 

bins
~0-1 week~
1 w -1 m
1m -2m
2m-6m
6m-1y
1y-2y
>2 y
then coloured by curated/uncurated

Once we see this we can figure out  if it shows what we  expect, and how to present it properly.

It might seem odd to have different sized bins but we need more bins closer to publication date,  (where we expect to see a difference) and fewer bins as time goes on

**Comment by kimrutherford** [comment]
> publication date - date sent out for curation

I don't think we can do that accurately.  PubMed doesn't report the publication day in a lot of cases. Nearly half the time it just has the month (like "Apr 2005") and in about 10% of cases we only have the year.

**Comment by ValWood** [comment]
Ah OK so we don't even always have the month...damn.

Can we see what we get if we miss the 1 week bin.
We can put those where only the year is reported in the "1 year bin" (but shade them  differently so we can see if it makes a big difference, and so we can explain they may have been curated faster)

**Comment by kimrutherford** [comment]
There is some weirdness.  There are over 200 publications where the session was sent before publication.  eg.
 https://curation.pombase.org/pombe/view/object/pub/11423?model=track
 https://www.ncbi.nlm.nih.gov/pubmed?holding=pombase&term=27613427

 https://curation.pombase.org/pombe/view/object/pub/11917?model=track
 https://www.ncbi.nlm.nih.gov/pubmed/?term=28674280%5Buid%5D

 https://curation.pombase.org/pombe/view/object/pub/12270?model=track
 https://www.ncbi.nlm.nih.gov/pubmed/?term=29549582%5Buid%5D

**Comment by kimrutherford** [comment]
Here's a first rough look at the data:
![months_from_pub_dates-1](https://user-images.githubusercontent.com/90474/74321997-14817000-4de8-11ea-92e9-3f16dc268905.png)

**Comment by ValWood** [comment]
>There is some weirdness. There are over 200 publications where the session was sent before publication. eg.

I think that might be possible because they can appear in PMID before the offical 'published date'

**Comment by ValWood** [comment]
The data is quite clear. People are more likely to curate closer to publication date. However, we don't really get that from the histogram because of the different time size bins.

Could you replot  one month bins up to 24 months? That will show a very clear decline.

**Comment by kimrutherford** [comment]
> Could you replot one month bins up to 24 months? That will show a very clear decline.

Do you want to include the >24 month values in a catch-all bin?

Here's what it looks like with a catch-all:
![months_from_pub_dates-2](https://user-images.githubusercontent.com/90474/74325969-7644d880-4dee-11ea-8661-0d73f2330bfe.png)

and without (ie excluding >24 months from the data):
![months_from_pub_dates-3](https://user-images.githubusercontent.com/90474/74326017-91174d00-4dee-11ea-8b39-c03e0adae900.png)

both graphs include the <0 data.

**Comment by ValWood** [comment]
Without the catch is perfect. This shows very clearly that  people are much more likely to curate close to publication date and answers:

"Is data available to support the claim that ‘Soliciting curation as soon as possible after publication therefore increases the response rate.’?"

**Comment by ValWood** [comment]
So let me check..... The first bin is all papers curated before the publication date?
This is a lot. Can I get the list?

**Comment by kimrutherford** [comment]
OK, I'll do a version with nicer colours and labels tomorrow.  I'm heading to bed now.

> So let me check..... The first bin is all papers curated before the publication date?

Yep.

> This is a lot. Can I get the list?

[curated_before_published-2.txt](https://github.com/pombase/pombase-chado/files/4191430/curated_before_published-2.txt)

**Comment by ValWood** [comment]
OK night  I'll sanity check this later.
Hopefully I can get back to the reviewer's comments today and work these into the text.
Thanks!
val

**Comment by mah11** [comment]
> There is some weirdness. There are over 200 publications where the session was sent before publication.

Not weird. All three of your examples have epub (online) dates earlier than the Canto session creation date. The "publication date" from PubMed must be the *print* pub date.

Likewise,

> > The first bin is all papers curated before the publication date?
> 
> Yep.

These aren't curated before publication; they're only curated before they appear in dead-tree format.

Can you get epub dates from your PubMed data? If so, that would be the date to use in the graphs, since it's the date that matters in reality. The first bin shows that Val doesn't wait for a paper to appear in print before creating & sending a Canto session.

**Comment by ValWood** [comment]
Wow I really should send the links as soon as possible. It does make a big difference...

**Comment by ValWood** [comment]
I think it's OK to use these dates, as long as we say in the legend. If the other dates are easy to access we can see the difference...

**Comment by kimrutherford** [comment]
> Can you get epub dates from your PubMed data?

In a lot of cases, yes.  But it would be a bit of work as the epub dates are stored in the XML differently to the publication dates.

**Comment by ValWood** [comment]
OK I think this graph will work to demonstrate people are more likely to curate close to publication date.

**Comment by kimrutherford** [comment]
> I think it's OK to use these dates, as long as we say in the legend. If the other dates are easy
> to access we can see the difference...

If you can wait until Monday I should be able to re-do the graph using the e-pub dates where available.

> OK, I'll do a version with nicer colours and labels tomorrow.

Here's how it looks after some tidying:
![months_from_pub_dates-4](https://user-images.githubusercontent.com/90474/74501523-4f51e800-4f4f-11ea-8474-5853e6efc92a.png)

**Comment by ValWood** [comment]
Now, I am thinking about this and I am not sure that it shows what I thought it showed (although it looks impressive at first glance)!

Certainly it seems that papers are  more likely to be curated if they are sent out for curation in the 3 months following publication but if this was done as ratios rather than absolute numbers it would not look so impressive.
The situation is more impressive than it looks in the graph because the earlier papers will be curated sooner often without reminders. The later bins catch up, but often people will go back to curate these after multiple reminders which also increases the likelihood of curation. It  would be good if we can somehow articulate  this bias in the legend
@Antonialock 


 - [ ]   The final bin is not  currently a 'catch-all' (we just truncate this analysis at 24 months). If it was a 'catch-all' it would have a lot of papers (over 400 according to the above, although that seems a lot). Maybe we should include the catch all because these are much less likely to be curated. Which supports our argument.

- [ ] I also now think that this would look better in 3 month bins
0-3, 3-6 etc. could we try that too

Sorry!

**Comment by Antonialock** [comment]
> > publication date - date sent out for curation
> 
> I don't think we can do that accurately. PubMed doesn't report the publication day in a lot of cases. Nearly half the time it just has the month (like "Apr 2005") and in about 10% of cases we only have the year.

I think it is possible using the EDAT line in the medline description
eg
https://www.ncbi.nlm.nih.gov/pubmed/26504246?report=medline&format=text

Entrez Date (EDAT)
In most cases, Entrez Date is the date the citation was added to PubMed. However, prior to October 9, 2008, the Entrez Date was set equal to the Publication Date (DP) on records with publication dates before September 1997. Beginning on October 9, 2008, the Entrez Date is set equal to the Publication Date (DP) when the record enters PubMed more than twelve months after the date of publication.

Format: YYYY/MM/DD HH:MM

Example:
EDAT- 2003/01/02 04:00

https://www.nlm.nih.gov/bsd/mms/medlineelements.html

**Comment by kimrutherford** [comment]
> I think it is possible using the EDAT line in the medline description

Thanks for that.  We can load that if it makes sense.  It's easy to find in the XML:
```xml
<PubMedPubDate PubStatus="entrez">
   <Year>2015</Year>
   <Month>10</Month>
   <Day>28</Day>
   <Hour>6</Hour>
   <Minute>0</Minute>
</PubMedPubDate>
```

**Comment by Antonialock** [comment]
I think that would make sense (sending out sessions is tied to pubmed integration date, not publication date)

**Comment by kimrutherford** [comment]
OK, thanks.  I'll have a go at getting those dates into Chado.

**Comment by kimrutherford** [comment]
> I'll have a go at getting those dates into Chado.

I've made the code changes.  I'm testing locally and I'll check the load on Wednesday morning.

**Comment by Antonialock** [comment]
yeah I think this doesn't show what we want it to show.

it seems to be 50/50 no matter age

**Comment by ValWood** [comment]
I still think the graph shows. Its more than 50:50 and response  definitely decreases with time between publication and request.

Its quite a lot over 50:50 in the first few months and then less than 50:50 later.
Also,  the early ones have curated sooner with fewer reminders but we can't control for that, although we can say in the explanation.

But it would be clearer with the changes above (I think?)

- [ ] The final bin is not currently a 'catch-all' (we just truncate this analysis at 24 months). If it was a 'catch-all' it would have a lot of papers (over 400 according to the above, although that seems a lot). Maybe we should include the catch all because these are much less likely to be curated. Which supports our argument.

- [ ]   I  now think that this would look better in 3 month bins
0-3, 3-6 etc. could we try that too?

**Comment by ValWood** [comment]
- [ ]. also we aren't sure which dates we are using now EDAT?

**Comment by kimrutherford** [comment]
Change to 3 month bins.  Get the numbers for curated vs uncurated proportions.

**Comment by Antonialock** [comment]
this is the last one we need!

**Comment by Antonialock** [comment]
I don't think we need proportions. I think it will look good like this:

![image](https://user-images.githubusercontent.com/12727506/75394093-4f56ce00-58e7-11ea-80c1-eba16550476b.png)

**Comment by kimrutherford** [comment]
> also we aren't sure which dates we are using now EDAT?

Val, what did you mean in that comment?

> this is the last one we need!

Working on it now!

> I don't think we need proportions. I think it will look good like this:

I'll pull the raw numbers out.

**Comment by kimrutherford** [comment]
I've got the counts again.  This time instead of the publication date it's using the e-pub date or the date the publication entered PubMed/Entrez.  The e-pub date is mostly earlier but not every publication has an e-pub date.  Is that OK?

Here are the counts:
```
months  uncurated  curated
0-3           452      455
3-6            84       67
6-9            54       32
9-12           33       19
12-15          24        7
15-18          29       20
18-21          14        6
21-24           7        7
24-             5        0
```

As CSV:
```
month_diff,uncurated,curated
0-3,452,455
3-6,84,67
6-9,54,32
9-12,33,19
12-15,24,7
15-18,29,20
18-21,14,6
21-24,7,7
24-,5,0
```

Quick plot:
![close_to_pub_date_binned-2020-02-26](https://user-images.githubusercontent.com/90474/75410583-44e91280-5981-11ea-9c9b-0da775818b10.png)

**Comment by Antonialock** [comment]
Yes that is ok, it’s just old publications that don’t have the edat date


Just to confirm, the second date is the date when the session was first  sent to the curator?

Or is it the date the session was completed?
--
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by kimrutherford** [comment]
> Just to confirm, the second date is the date when the session was first  sent to the curator?

Yep!

**Comment by Antonialock** [comment]
It looks like the proportions have changed from your earlier graph. I guess that is due to changing from journal publication date to edat date?

**Comment by kimrutherford** [comment]
> I guess that is due to changing from journal publication date to edat date?

I think so.  I did a spot check on a few publications and the numbers made sense.

**Comment by ValWood** [comment]
Compelling!

**Comment by Antonialock** [comment]
sorry, I meant 'e-pub date' not edat... cool, this looks great! I'll probably change to %s to make it more clear, with numbers in a table (because sample size very varied)

**Comment by kimrutherford** [comment]
> meant 'e-pub date' not edat

I think edat is PubMed's abbreviation for electronic publication date so they're the same.
