### ISSUE TITLE
Load the epub dates from PubMed XML into Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#757]

**Comment by kimrutherford** [comment]
I've changed the code to get the e-pub dates from PubMed and store them in Chado.  I'm running a full test load locally.  If that's OK then the e-pub will be available on Saturday morning.

Not surprisingly the e-pub dates aren't available for all publications.  Maybe half by the looks of things.

**Comment by ValWood** [comment]
OK that will make things quite inconsistent.

**Comment by ValWood** [comment]
Although it could be because many of them predate the internet, or online availability in which case the paper published date *is* the first published date, so maybe this is OK?

**Comment by kimrutherford** [comment]
> OK that will make things quite inconsistent.

Yep, but at the moment the graph is a bit misleading.  Using the e-pub dates where available will make the graph a bit less wrong.

> Although it could be because many of them predate the internet

I wondered about that.  Once they're in Chado I'll query to see how many that are missing the e-pub dates are recent publications.
