### ISSUE TITLE
Curation paper graph D

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#759]
@Antonialock  typed:
if people have curated before, they are more likely to curate again.

This needs to be done on the person the paper was first assigned to
(so a paper may have been assigned to a group leader, who sent it to a phd studen)

**Comment by ValWood** [comment]
people with a number of sessions sent to them (3-5?)

3 bars

bar 1=no papers curated
bar2=a proportion of papers curated
bar3=all papers assigned curated

**Comment by kimrutherford** [comment]
> This needs to be done on the person the paper was first assigned to

We need to add the initial curator name to Chado ("canto_initial_curator_name"?)

**Comment by ValWood** [comment]
so ultimately we want to see that people either dont curate, or they curate everything

**Comment by kimrutherford** [comment]
Note to self:
 - include all curators not just those who have completed a session
 - remember to remove Val, Antonia and Midori

**Comment by kimrutherford** [comment]
We now have the name of the initial curator in Chado.  That changes the numbers a bit.

There are 128 community members who are the current curator of a session.  But there are 140 initial curators (before possible reassignment).

Here are the counts of papers assigned per person (based on the initial assignee) and the number of papers submitted or approved.  Does this look right?  It should include the sessions in progress in the "total_count" column:

[all_vs_curated_counts.txt](https://github.com/pombase/pombase-chado/files/4254731/all_vs_curated_counts.txt)

**Comment by kimrutherford** [comment]
> Here are the counts of papers assigned per person

I forgot to say, this only includes people who have been assigned 4 or more sessions.

**Comment by kimrutherford** [comment]
Here (I think) are the counts per bin.  I'm not sure this shows what you hoped? 

| % curated | count |
|--------|-------|
|      0 |    23 |
|   1-25 |    23 |
|  25-50 |    17 |
|  50-75 |    34 |
| 75-100 |    23 |
|    100 |    20 |

**Comment by kimrutherford** [comment]
> 75-100

That bin label should be 75-99.  I've edited my comment.

**Comment by kimrutherford** [comment]
> I'm not sure this shows what you hoped?

Now I think about it, I don't think you asked for a 100% bin.  If you move that count into the 75-99 bin if doesn't look too bad.

**Comment by ValWood** [comment]
I wonder if 10% bind would work for this?

 I expect to see an "upside down binomial distribution" (i.e people will tend to be "all" or "nothing")

These numbers do have that trend but it would probably be clearer with more smaller bins.

**Comment by ValWood** [comment]
> Now I think about it, I don't think you asked for a 100% bin. If you move that count into the 75-99 bin if doesn't look too bad.

that also works!

**Comment by kimrutherford** [comment]
Does this need a graph or even bins?  You could summarise this with:

> For groups with 4 or more curatable pombe publications, 55% (77 out of 140) have curated
> more than half the sessions that have been assigned to them.

(with better grammar)

**Comment by Antonialock** [comment]
can we do 3 bins? 

0-33
33-66
66-100

**Comment by ValWood** [comment]
I think it is good to see the switch  high-low-high if we can show that.  3 bins could work...

**Comment by kimrutherford** [comment]
> I wonder if 10% bins would work for this?

Here are the raw counts and a quick graph with 10% bins.  I don't think that's going to work if we are looking at people with 4 or more publications.  Most have less than 10 publications so it will make the distribution weird.

```
percent_bins       curator
[0, 1)             23
[1, 10)             2
[10, 20)           14
[20, 30)           14
[30, 40)            4
[40, 50)            6
[50, 60)           13
[60, 70)           20
[70, 80)            7
[80, 90)           12
[90, 101)          25
```

![all_vs_curated_binned-1](https://user-images.githubusercontent.com/90474/75337140-4bc84480-58f1-11ea-827d-da964d74233f.png)

**Comment by Antonialock** [comment]
actually 4 bins, 4+ papers looks fine

few people do one paper and then stop / people who do one paper are likely to go on and do more

![image](https://user-images.githubusercontent.com/12727506/75339267-19363180-5888-11ea-90cd-c3609b5c1d2a.png)

maybe 3+ papers and 3 bins would work too but I think this looks ok?

**Comment by ValWood** [comment]
Yeash ANtonias suggeestion was better 3 bins

**Comment by ValWood** [comment]
4 bins works well!

**Comment by ValWood** [comment]
Nice! That really shows people aren't put off after they do it .
Well one was....

**Comment by ValWood** [comment]
I *never* forget

**Comment by Antonialock** [comment]
having a 0 bin is better

Kim -can you confirm that the categories dont overlap, it looks confusing (sorry, my bad)
is this how the data is subdivided?

0
--
1-25
26-50
51-75
76-100



![image](https://user-images.githubusercontent.com/12727506/75339555-a7aab300-5888-11ea-869d-74bc9226a861.png)

**Comment by kimrutherford** [comment]
> Kim -can you confirm that the categories dont overlap, it looks confusing

Sorry the labels aren't very good.  It should be:

| % curated | count |
|--------|-------|
|      0 |    23 |
|   1-24 |    23 |
|  25-49 |    17 |
|  50-74 |    34 |
| 75-99 |    23 |
|    100 |    20 |

**Comment by kimrutherford** [comment]
> actually 4 bins, 4+ papers looks fine

That looks good to me!

**Comment by Antonialock** [comment]
happy with this!

**Comment by Antonialock** [comment]
![image](https://user-images.githubusercontent.com/12727506/75392703-84155600-58e4-11ea-9e17-356520509b43.png)

**Comment by Antonialock** [comment]
![image](https://user-images.githubusercontent.com/12727506/75392776-a8713280-58e4-11ea-8472-c6475dcba3fe.png)

**Comment by ValWood** [comment]
looks great!
remember legend to say 3+ publications assigned
might be good to say the range too?
