### ISSUE TITLE
Update InterPro 

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#760]
There has been an InterPro release since our last update.  The release was in November and we last updated in September.

https://www.ebi.ac.uk/interpro/release_notes/

This should be an easy update.

**Comment by kimrutherford** [comment]
The new InterPro release will go in tonight.  I've had a look and there are no surprises in the XML file, it's just slightly bigger.  All ID types are the same.  I'll check the load in the morning before updating the main site.

**Comment by kimrutherford** [comment]
All looks good.

**Comment by ValWood** [comment]
we'll do  a news item, just because we can

**Comment by ValWood** [comment]
closing because the newsitem should be on website tracker
