### ISSUE TITLE
lost annotations (hir4)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#762]
where is the 'other place' annotations can live?
I am trying to trace these:

- | GO:0030702 | chromatin silencing at centromere | IMP | Anderson HE et al. (2010) | 24
-- | -- | -- | -- | -- | --
- | GO:0030466 | chromatin silencing at silent mating-type cassette | IMP | Anderson HE et al. (2010) | 20

They aren't in the session, and they aren't in Artemis.

**Comment by kimrutherford** [comment]
They are from this file in Subversion:
```
pombe-embl/external_data/external-go-data/From_curation_tool
```

That file from ancient history is still included in every load.

**Comment by ValWood** [comment]
I knew there was another file. I was sure that I looked in there. Thanks!
