### ISSUE TITLE
FYPO:0005504 anomaly

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#763]
It looks like FYPO:0005504 is somehow not getting loaded into Canto. It isn't available in the term search/autocomplete, and there are two copies of this warning in the curation-tool-data-load-output log:

    warning in 9cf15ade89e44016: can't load annotation, FYPO:0005504 not found in database

FYPO:0005504 is present and not obsolete in every FYPO file I've checked, including the copy of fypo-simple.obo in the latest_build/ontologies/ directory. Whassup?

**Comment by kimrutherford** [comment]
I think it could be because there's another term with the same name:

```
[Term]
id: FYPO:0003318
name: abolished galactose-specific flocculation

[Term]
id: FYPO:0005504
name: abolished galactose-specific flocculation
```

**Comment by mah11** [comment]
oops! at least that's easy to fix. well spotted! (FYPO:0003318 doesn't have a logical def; if it did, the reasoner would've caught the duplicate)

**Comment by mah11** [comment]
fixed in FYPO
