### ISSUE TITLE
Drop in GO annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#765]
Pascale was showing me some  new GO stats showing annotation changes between releases.

It showed that the PomBase GO annotations net change between Jan and Feb was -243

I can't think. of any reason for this?
We have removed thing, sure, but we must have added more than we. removed.

I didn't check the files but these are the 2 releases.  @mah11  could you have a look to see if there are any obvious reason for this (or can you think of anything obvious I am overlooking?)

**Comment by ValWood** [comment]
It's between these 2 releases

**http://release.geneontology.org/2020-01-01/products/annotations/index.html
pombase-src.gaf.gz

http://release.geneontology.org/2020-02-26/products/annotations/index.html
pombase-src.gaf.gz

**Comment by mah11** [comment]
I've traced the big difference to between the 2020-01-03 and 2020-01-04 builds. There was a net drop of 293 annotations, mainly due to a loss of 295 annotations to 'protein binding' (GO:0005515). That followed straight on from the tweak to reciprocals in #723, so it's probably not a coincidence.

**Comment by ValWood** [comment]
Pascale also provided this yesterday, big drip in IMP


UPCOMING   RELEASE (pombase file from 03/16/2020) |   | CURRENT RELEASE   (pombase file from 02/17/2020)
-- | -- | --
4559 | mutant phenotype evidence used   in manual assertion |   | 4697 | mutant phenotype evidence used   in manual assertion
-- | -- | -- | -- | --


might just be in logs but over 100- so seems a lot
let me know if you  want me to do any fixing

**Comment by ValWood** [comment]
[pombase-annotations-upcoming release.xlsx](https://github.com/pombase/pombase-chado/files/4388078/pombase-annotations-upcoming.release.xlsx)

**Comment by kimrutherford** [comment]
Let me know if you'd like me to check anything here.

**Comment by ValWood** [comment]
I think it's fine...
