### ISSUE TITLE
Rename PECO

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#766]
I wasn't really sure where to open this, it seems to span multiple trackers.

Rename PECO.

From Chris:

You can fix your github repo just with a one line perl
perl -pi -ne 's@PECO@PBECO@g' *.{obo,owl}
But you will have to sync that with SQL updates in your chado and probably codebase changes.... sorry

and re the alignment
Bill is doing a first pass at aligning every single exposure vocabulary we can get our hands on, including the pombase one, no idea how accurate an automated approach will be but we can show you when it's ready

**Comment by kimrutherford** [comment]
Changes needed:
 - [ ] Canto test OBO file (https://github.com/pombase/canto/blob/master/t/data/peco_small.obo) and Canto tests
 - [ ] Canto configuration
 - [ ] IDs in the Canto database
 - [ ] .contig files
 - [ ] PHAF files
 - [ ] Website docs, there's one mention of PECO here: https://github.com/pombase/website/blob/master/src/docs/documentation/ontology-term-page.md

**Comment by mah11** [comment]
@matentzn is also interested in following progress

**Comment by mah11** [comment]
@kimrutherford, I can do my bits pretty much any time with about a day's notice. I'll claim the P(B)ECO file itself, the .contig files, PHAFs, and documentation. Everything Canto is yours ;)

**Comment by mah11** [comment]
Now that JaponicusDB is a thing, and they're using FYPO, maybe we should change PECO to FYCO or FYECO instead of PBECO. Neither would clash with anything I see on the OBO Foundry list.

Comments, questions, etc.?

**Comment by ValWood** [comment]
Good plan. I don't know which is best. FYECO  maybe?

**Comment by mah11** [comment]
All this needs is an executive decision to pick a date and do it. Let's schedule it for shortly after Kim gets back from holiday.

**Comment by ValWood** [comment]
Name your day Kim....

**Comment by mah11** [comment]
ping

just making sure this gets done soon - @kimrutherford pick a day

**Comment by mah11** [comment]
I just updated the documentation, since there's only one mention of the conditions ontology, and that's at the end of a sorta-longish page. I don't think it'll hurt anything for it to have the new abbreviation a week or two in advance of the rest.

Let me know if you want me to update the contig and/or PHAF files, and if so, when. Pretty much any time is OK, since it's a quick job.

**Comment by kimrutherford** [comment]
I've just taken the pombe and japonicus Canto instances offline while I attempt to change "PECO:" to "FYECO:".  Hopefully it will be back in an hour or two.

I've taken an extra backup.  :-)

**Comment by kimrutherford** [comment]
The pombe Canto is back up now.  japonicus shouldn't be long.  Let me know if you spot any problems with conditions.

The changed PECO to FYECO in the Chado loading code and all of the configuration and data files I can find.  I'll check the nightly load on Sunday morning.

**Comment by kimrutherford** [comment]
> I think it (mostly) worked: http://dev.pombase.kmr.nz/term/FYECO:0000268
> There 94 fewer annotations then the previous successful load so I'm going to investigate that before updating the main site.

I think that's OK.  It looks like this session went back into approved status which accounted for most of the 94:
https://curation.pombase.org/pombe/curs/d2fab1f2b453d796
PMID:20838651

I've now updated the main site.

**Comment by mah11** [comment]
hooray!
