### ISSUE TITLE
One-off annotation migration

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#767]
automagically move ALL direct annotation to
GO:0000781 | chromosome, telomeric region
and
GO:0000784 | nuclear chromosome, telomeric region

to the new term specific for the telomeres
+id: GO:0140445
+name: chromosome, telomeric repeat region

The existing term will be broadened to cover the telomere and  heterochromatin subtelomere
I already reannotated  to check that  everything heterochromatin specific  was correctly annotated to the "subtelomeric heterochromatin"  term (some things will be both)

**Comment by mah11** [comment]
I have
- updated the annotations in the contig files directly
- addede GO:0000781 and GO:0000784 to the GO_mapping_to_specific_terms.txt file

That might sort it ...

**Comment by ValWood** [comment]
OK done
