### ISSUE TITLE
create a export file of chemical sensitivities and resistances

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#768]
using all annotations to
increased sensitivity to chemical (FYPO:0002683) [single allele genotypes]
and
increased resistance to chemical (FYPO:0002682) [single allele genotypes] 
and their descendants.

thanks
Val

**Comment by ValWood** [comment]
I have asked. I'm sure that she will probably want the term name, because it is such a lot it will save looking up each one. So it won't really be possible to be a PHAF because we don't include therm name in the PHAF.

I  asked if anything  else is required in  addition to the minimum I gleaned from the request

**Comment by ValWood** [comment]
requested data types required:


* systematic name - yes

* gene standard name (very useful for us to make quick connections between genes if we have names we recognise)

* allele - yes

* FYPO ID (if it can also have the actual description as well, such as 'resistant to caffeine' etc, that would be helpful but not essential). I was interested in population phenotype mostly (see below)

* term name - maybe useful (see below) not essential

**Comment by kimrutherford** [comment]
I started work on this today.  I'm hoping to at least get the two files for sending to the user by tomorrow.  I'll then work on getting it into the nightly load and onto the FTP site.

**Comment by kimrutherford** [comment]
This took longer than I thought.
Could you have a look at these two new files and see if they are what's needed?:

https://curation.pombase.org/dumps/latest_build/misc/increased_resistance_to_chemical.tsv
https://curation.pombase.org/dumps/latest_build/misc/increased_sensitivity_to_chemical.tsv

We need to decide which directory they should go in on the FTP site.

**Comment by ValWood** [comment]
I did some spot checking of the files and they seem correct t to me.
