### ISSUE TITLE
export lists for new slims

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#775]
Write out a file of slim term names and IDs for each of the new slims (GO MF, GO CC, MONDO) and put them in the same directory as the BP list, i.e. ftp://ftp.pombase.org/nightly_update/misc/.

When this is done I'll add links back to the blurbs on each slim page.

(like #685 but for the new slims)

**Comment by kimrutherford** [comment]
That's done as the code was already there to write a file for each configured slim.  Unfortunately there was a glitch updating the FTP site last night so the CC slim didn't get copied over, but it is on the latest build directory:
  https://curation.pombase.org/dumps/latest_build/misc/

The MF slim file will be there tomorrow.

Note that the disease slim file name has changed to match the mondo slim name.

**Comment by mah11** [comment]
excellent. must admit, I didn't spot the disease one when I looked (not very observant these days ...)

**Comment by kimrutherford** [comment]
> The MF slim file will be there tomorrow.

Done!
ftp://ftp.pombase.org/nightly_update/misc/

**Comment by mah11** [comment]
I've committed updates to link the slim pages to the lists, so will close this. Thanks again :)
