### ISSUE TITLE
Write a disease association file when loading from contig files

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#776]
We'd like to move the disease annotation out of the contig files.  One way to speed that up would be to write a tab delimited disease file as we are loading into Chado.  We'd need:

   - gene ID
   - MONDO:ID
   - reference 

We could then move those annotations into: malacards_data_for_chado_mondo_ids.tsv

**Comment by ValWood** [comment]
Isn't this done. I think something is outstanding, but we don't use disease associations from Artemis right?
If not I can try to delete them (I think that is possible from Artemis?)

**Comment by kimrutherford** [comment]
> but we don't use disease associations from Artemis right?

They are still being loaded.  For example, from SPCC757.13:

```
FT                   /controlled_curation="term=disease associated, metabolic
FT                   disorders; date=20160106"
FT                   /controlled_curation="term=disease associated, lysosomal
FT                   storage disorders; date=20160106"
FT                   /controlled_curation="term=disease associated, Salla
FT                   disease; date=20160106"
```
https://www.pombase.org/gene/SPCC757.13

I haven't written the code to write them out into a tab delimited file when loading.

**Comment by kimrutherford** [comment]
> We could then move those annotations into: malacards_data_for_chado_mondo_ids.tsv

That should be: pombase_disease_associations_mondo_ids.txt

Here are the disease_association annotations from the contig files, mapped to MONDO IDs, in the same format as `pombase_disease_associations_mondo_ids.txt`: [mondo_annotations_from_contigs.tsv.txt](https://github.com/pombase/pombase-chado/files/5984928/mondo_annotations_from_contigs.tsv.txt)

There are 3 duplicate annotations:
```
      SPAC1556.08c            MONDO:0002412           PB_REF:0000003  2016-01-06
      SPAC343.15              MONDO:0004069           PB_REF:0000003  2015-07-01
      SPCC4B3.11c             MONDO:0013675           PB_REF:0000003  2012-07-19
```

If you're happy with that I can go ahead and add those annotations to `pombase_disease_associations_mondo_ids.txt` and remove the disease associated qualifiers from the contig files.

**Comment by ValWood** [comment]
This will be great, so much less hassle!

But I think we are still missing some

If I do
cat mondo_annotations_from_contigs.tsv\ \(1\).txt pombase_disease_associations_mondo_ids.txt  |cut -f1 |sort |uniq |wc
     851

(the pombase file, and this new file) I should get 1244 IDs?

**Comment by ValWood** [comment]
The small number of duplicate annotations is also a red flag, I see many in pombase.

**Comment by ValWood** [comment]
I get it. I think you are creating the file from only the "malacards" annotations maybe?

But we would want to include the Pombase ones too.
vw253-mbp13196:pombe-embl vw253$ grep "disease" *.contig |wc
    1109 

I think the Pombase ones are  in 2 places, some are in contigs and some in
pombase_disease_associations_mondo_ids.txt

Once they are *all* in the flat file, we can delete the whole lot  from Artemis.

**Comment by kimrutherford** [comment]
> (the pombase file, and this new file) I should get 1244 IDs?

Why 1244?

> The small number of duplicate annotations is also a red flag, I see many in pombase.

Can you give me an example?

> I think you are creating the file from only the "malacards" annotations maybe?

It's creating a line for each "disease associated" /controlled_curation in the contig files.

> But we would want to include the Pombase ones too.

I don't understand that.

> vw253-mbp13196:pombe-embl vw253$ grep "disease" *.contig |wc
> 1109

That's getting extra lines.  Try:

```sh
grep 'disease associated' *.contig | wc -l
1037
```

**Comment by ValWood** [comment]
> Why 1244?
https://www.pombase.org/results/from/id/e9a13d21-7b2a-4d9f-902d-27f9ff203fbe

>>The small number of duplicate annotations is also a red flag, I see many in pombase.
> Can you give me an example?

I will need to look but I see them all the time... will find a couple

**Comment by ValWood** [comment]
some paralogs missing disease associations #808
isn't the reason for the missing ones though. These (#808) are missing  from our current dataset.
They will increase the current number of genes with disease associations  from 1244

**Comment by ValWood** [comment]
duplicate examples:
https://www.pombase.org/gene/SPBC577.06c
https://www.pombase.org/gene/SPBC146.12
https://www.pombase.org/gene/SPBC3F6.02c (2)

**Comment by kimrutherford** [comment]
Those duplicates aren't from the contig files, they're from the files in pombe-embl/external_data/disease/

In all those cases there's line in pombase_disease_associations_mondo_ids.txt and a matching line in malacards_data_for_chado_mondo_ids.tsv

```sh
grep MONDO:0010441   external_data/disease/*.t??
```
```
external_data/disease/malacards_data_for_chado_mondo_ids.tsv:ck syndrome        ck_syndrome     Ck Syndrome     NSDHL   MONDO:0010441
external_data/disease/pombase_disease_associations_mondo_ids.txt:SPBC3F6.02c    erg26   MONDO:0010441           PB_REF:0000003  2020-01-20

```

**Comment by kimrutherford** [comment]
> Why 1244?
> https://www.pombase.org/results/from/id/e9a13d21-7b2a-4d9f-902d-27f9ff203fbe

That's the count of all disease genes from all source.  I was counting the number of disease annotations in the contig files.

**Comment by ValWood** [comment]
>  I was counting the number of disease annotations in the contig files.

I know, but I was trying to check that final total when these were merged with the annotations in the flat file:

I was catting both files together to check the number to see if it matched or current PomBNase total:

cat mondo_annotations_from_contigs.tsv\ (1).txt pombase_disease_associations_mondo_ids.txt |cut -f1 |sort |uniq |wc
851

**Comment by kimrutherford** [comment]
I've moved the disease association annotations from the contig file to `pombe-embl/external_data/disease/pombase_disease_associations_mondo_ids.txt`

I'll check the load in the morning to make sure that this doesn't change the disease annotation counts.

**Comment by kimrutherford** [comment]
> I'll check the load in the morning to make sure that this doesn't change the disease annotation counts.

There are 3 fewer disease annotations in Chado after moving the annotation details from the contig files to the main disease association file.  That makes sense because I removed three duplicates: https://github.com/pombase/pombase-chado/issues/776#issuecomment-779551959

The number of disease associated genes is the same: 1246

That doesn't match number from the "All disease associated genes" query on the website: 1244
https://www.pombase.org/results/from/id/e9a13d21-7b2a-4d9f-902d-27f9ff203fbe

I looked into that.  There are two genes that are annotated only with disease susceptibility (MONDO:0042489) terms which isn't a descendant of MONDO:0000001:
  - sod2 (SPAC1486.01)
  - tif452 (SPBC1709.18)

**Comment by ValWood** [comment]
perfect. I will check if 
sod2 (SPAC1486.01)
tif452 (SPBC1709.18)
can be annotated to a disease.

If we decide to curate susceptibility more, this could eventually be a separate section. In fact, lots of the annotations to "cancer" should really be susceptibility.

But we can go ahead and  archive the old stuff and move forward with the new files. `Should I attempt to remove the 'disease associations' from the config files in Artemis, or can you script it?

**Comment by kimrutherford** [comment]
> Should I attempt to remove the 'disease associations' from the config files in Artemis, or can you script it?

That's already done.  I removed them when I added the annotations to the disease association file so that they wouldn't be loaded twice.

**Comment by ValWood** [comment]
great. this will be a nice time saver. It  was taking me ages to figure out which thing was actually wrong from the errors in the logs. v. happy ;)

**Comment by ValWood** [comment]
so now I see 2 files

-rw-r--r--  1 vw253  staff  1086689 15 Feb 20:36 malacards_data_for_chado_mondo_ids.tsv
-rw-r--r--  1 vw253  staff    79899 17 Feb 09:18 pombase_disease_associations_mondo_ids.txt

malacards_data_for_chado_mondo_ids.tsv (should be archived)

pombase_disease_associations_mondo_ids.txt has only 851 unique genes. Where are the others?

**Comment by kimrutherford** [comment]
> malacards_data_for_chado_mondo_ids.tsv (should be archived)

We still need those annotations don't we?

> pombase_disease_associations_mondo_ids.txt has only 851 unique genes. Where are the others?

The other genes come from the Malacards data.

**Comment by ValWood** [comment]
These aren't the annotations though, it's the crazy mapping file that I want to get rid of

hutchinson-gilford progeria syndrome    hutchinson_gilford_progeria_syndrome    Hutchinson-Gilford Progeria Syndrome    ZMPSTE24        MONDO:0008310
maple syrup urine disease       maple_syrup_urine_disease       Maple Syrup Urine Disease       BCKDHB  MONDO:0009563
mevalonic aciduria      mevalonic_aciduria      Mevalonic Aciduria      MVK     MONDO:0012481
noonan syndrome 1       noonan_syndrome_1       Noonan Syndrome 1       PTPN11  MONDO:0018997
m

there are no genes in here?

**Comment by kimrutherford** [comment]
> there are no genes in here?

There are human gene IDs.  The loading code looks up the pombe ortholog(s) and makes an annotation on each of them.  It also stores the Malacards IDs so we can link to their website.

**Comment by ValWood** [comment]
OK all good!
