### ISSUE TITLE
consolidate disease gene mappings into a single file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#777]
Create a single file with all of the disease associations.

We won't reimport from Malacards. Periodically I will check ours against Mondo and add new ones (I can do this relatively easily ).

**Comment by ValWood** [comment]
realted to 
https://github.com/pombase/pombase-chado/issues/778

**Comment by ValWood** [comment]
I'd like to move this forward because it takes me aged to fix things that go wrong of MONDO changes but we are still mapping through from DO.....

**Comment by kimrutherford** [comment]
> but we are still mapping through from DO

I thought we had got rid of DO?  As far I can see we aren't using it during loading and it's not in Chado.

**Comment by kimrutherford** [comment]
I think the first step is pombase/pombase-chado#776. I'm doing that now.

**Comment by kimrutherford** [comment]
Can we close this issue?

**Comment by ValWood** [comment]
yes, i thought I had ;)
