### ISSUE TITLE
GO extensions fix

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#782]
GO:0007067 is now a secondary ID for GO:0000278 'mitotic cell cycle'
but was used for "mitotic nuclear division"
At the time we fixed the direct annotations, but I wasn't aware that it was used in some extensions.

These extensions  should be GO:0000087    mitotic M phase

(Canto and external files, possible Artemis, may be affected)

**Comment by ValWood** [comment]
It might be easier to fix these manually, first need to know where the occurences are

**Comment by ValWood** [comment]
fixed in 
Quantitative_gene_expression_data/Heinrich_PMID24161933_expression.txt

maybe that was the only place...

**Comment by kimrutherford** [comment]
> (Canto and external files, possible Artemis, may be affected)

I can only see one use of GO:0007067 in Canto, it's used in an extension on a protein modification here:
  https://curation.pombase.org/pombe/curs/2f5adb6aec169e1f/feature/gene/view/3/ro

> fixed in Quantitative_gene_expression_data/Heinrich_PMID24161933_expression.txt

Have you checked-in that change?

**Comment by ValWood** [comment]
no sorry now done.

**Comment by kimrutherford** [comment]
> it's used in an extension on a protein modification here:
> https://curation.pombase.org/pombe/curs/2f5adb6aec169e1f/feature/gene/view/3/ro

I think that's the only use of GO:0007067

**Comment by ValWood** [comment]
ok closing
