### ISSUE TITLE
Update to latest MONDO?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#784]
There's a new release:
  https://github.com/monarch-initiative/mondo/releases/tag/current

Should I update every time I see a release or would some notice and planning be a good plan?

Permanent link for the release: https://github.com/monarch-initiative/mondo/releases/tag/v2020-08-10

**Comment by ValWood** [comment]
I don't need any notice, so whenever you are ready. I probably have quite a few fixes in this one. As time goes by we probably don't need to update to every single new release because we will be pretty stable. There is quite a lot of churn right  now as ontology fixes are implemented.

**Comment by kimrutherford** [comment]
Now that I've looked, I completely forgot that I had changed the load script to grab the latest OBO file automatically.  :-)

So sorry for the pointless issue.  The new MONDO is in tonight's load.
