### ISSUE TITLE
Phenotype data severity column

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#786]
In Henry's phenotype spreadsheet he used the synonyms weak/strong for

Severity (formerly designated “expressivity) uses”high" (synonym: strong), “medium”, or “low” (synonym: weak). We will convert to suitable IDs for loading. Severity data will be displayed as annotation extensions on gene pages.

but he also use "moderate" so could we add this as a synonym for medium?

(I'm assuming that synonyms will parse OK?)

**Comment by mah11** [comment]
All PHAFs use the FYPO_EXT:nnn IDs in the severity and penetrance columns. Converting text to IDs is part of the curation we do when we receive files.
