### ISSUE TITLE
Missing reciprocal binding annotations

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#788]
From Val:

> cdc12 binds cdc3, this is not reciprocated.

https://www.pombase.org/gene/SPAC1F5.04c
vs
https://www.pombase.org/gene/SPAC4A8.15c

See also: #723

**Comment by kimrutherford** [comment]
I think the problem was that in #723 I changed the loading so that only protein binding reciprocals are only added for Canto annotations.  It was easier to implement #723 while loading the Canto data.

The half-fix is to re-enable the code for adding the missing reciprocals but only for annotations that don't have extensions.  Handling the extensions properly is tricky (as documented in #723).

There are 7 protein binding annotations in the contig files that have extensions and a "with=" qualifier.  Would it be possible to add those reciprocals manually?

```
 SPAPB1E7.02c.1  | chromosome1.contig | protein binding [happens_during] mitotic S phase
 SPBC646.13.1    | chromosome2.contig | protein binding [happens_during] G1 to G0 transition
 SPAC3H5.06c.1   | chromosome1.contig | protein binding [happens_during] mitotic S phase
 SPCC188.07.1    | chromosome3.contig | protein binding [happens_during] meiotic cell cycle
 SPBC11C11.04c.1 | chromosome2.contig | unfolded protein binding [has_substrate] SPBC26H8.07c [part_of] protein folding
 SPAC328.08c.1   | chromosome1.contig | unfolded protein binding [has_substrate] SPBC26H8.07c [part_of] protein folding
 SPAC8E11.02c.1  | chromosome1.contig | protein binding [has_substrate] transcription factor ste11 phosphorylated 1 (Schizosaccharomyces pombe) [part_of] negative regulation of transcription by RNA polymerase II
```

**Comment by ValWood** [comment]
Yes,  n problem or we could priorities these for Canto annotation.

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/2812
for recuration.

**Comment by ValWood** [comment]
The above are fixed  in
https://github.com/pombase/curation/issues/2812
