### ISSUE TITLE
positive regulation of actin nucleation/ not slimming

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#789]
https://www.pombase.org/gene/SPAC15A10.16

positive regulation of actin nucleation
is not slimming to
actin cytoskeleton organization | GO:0030036 | 127

even though it has this ancestry:
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0051127

**Comment by kimrutherford** [comment]
I think it might be the same flip-flopping issue: https://github.com/geneontology/go-ontology/issues/17171

I checked previous Chado databases and in some SPAC15A10.16 is in GO:0030036 and in some it isn't.  It was fine on 2020-08-29 but gone the next day.

**Comment by ValWood** [comment]
This is OK now
