### ISSUE TITLE
GO inference , membrane fusion

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#791]
There is definitely something a bit awry with GO inference ATM.

See

  | 19 | SNAP receptor activity (GO:0005484) | ...
  | 19 | membrane fusion (GO:0061025)
4 | SNAP receptor activity (GO:0005484) AND membrane fusion (GO:0061025) 

BUT all 
SNAP receptor activity should be annotated to membrane fusion

<img width="426" alt="Screenshot 2020-09-04 at 22 35 54" src="https://user-images.githubusercontent.com/7359272/92286477-15eac500-eeff-11ea-9c85-c509f13a23a2.png">

**Comment by kimrutherford** [comment]
It looks like a problem at our end.  The part_of relation between SNAP receptor activity and membrane fusion is missing from Chado but it is in the OBO file we load.  That's very strange.  I'll investigate.

**Comment by kimrutherford** [comment]
Sorry, I got that wrong.  The part_of relation is missing from "go-basic.obo":
```
[Term]
id: GO:0005484
name: SNAP receptor activity
namespace: molecular_function
alt_id: GO:0005485
alt_id: GO:0005486
def: "Acting as a marker to identify a membrane and interacting selectively with one or more SNAREs on another membrane to mediate membrane fusion." [GOC:mah, PMID:14570579]
subset: goslim_chembl
synonym: "Q-SNARE activity" NARROW []
synonym: "R-SNARE activity" NARROW []
synonym: "SNAP-25" NARROW []
synonym: "SNARE" EXACT []
synonym: "t-SNARE activity" NARROW []
synonym: "v-SNARE activity" NARROW []
is_a: GO:0030674 ! protein-macromolecule adaptor activity
```

which we get from: http://purl.obolibrary.org/obo/go/snapshot/go-basic.obo

The part_of is in go.obo from http://purl.obolibrary.org/obo/go/snapshot/go.obo

**Comment by ValWood** [comment]
ok will open a GO ticket..
