### ISSUE TITLE
GPAD & GPI - header, file location, submission

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#792]
One more angle on generating GPAD, which I think should be easy to implement:

The file header needs one more line, and could include more.

- The `date-generated: YYYY-MM-DD or YYYY-MM-DDTHH:MM` line is required.

- Some of the optional columns aren't much use to us (Project-release, Columns) but do we want to include any of:
   - URL (i.e. https://www.pombase.org/)
   - Funding (can just put Wellcome Trust; they don't seem to need the grant ID)
   - ontology versions (would need the version-specific PURLs, so probably only if it's easy to look them up and capture them)

Final question: when do we want to start sending GPAD & GPI to GO? I think it's entirely up to us now; all we have to do is decide on the "real life" location for the current version of each file and then open a pull request at go-site to update our dataset metadata.

I suggest (using GO-friendly filenames, and assuming it'll be straightforward to gzip the files and copy them wherever automagically):

- ftp://ftp.pombase.org/pombe/annotations/Gene_ontology/pombase.gpad.gz
- ftp://ftp.pombase.org/pombe/annotations/Gene_ontology/pombase.gpi.gz

or the https equivalents. (Tangent: what's the status of switching our URLs etc. away from ftp:yada?)
 
Whenever we want to switch over I can put in the go-site pull request.

@ValWood for input on whether to include any of the optional header lines
@kimrutherford for implementing header additions & file locations
me for link updates on our pages, and the go-site PR

**Comment by ValWood** [comment]
I think adding the extra header info is good.
It's a pity we can't include a  citation option?  Is there a comment field we can put that in?

**Comment by mah11** [comment]
> include a citation option

What do you mean?

> Is there a comment field we can put that in?

I don't see anything about one in the spec, but you could ask on the [request-for-comments ticket](https://github.com/geneontology/go-annotation/issues/2864).

**Comment by mah11** [comment]
Clarification on headers (since I've realized the original doesn't explicitly say much about GPI):

Both GPAD and GPI need the `date-generated` line.
Both can get the `URL` and `funding` lines.
Ontology version PURLs would only go in the GPAD header.

**Comment by ValWood** [comment]
include a citation option

What do you mean?

It would be good if we could say for use of this data cite PMID: (PomBase paper)
OIf people downloaded the pombase GPAD specifically to do some analyses.

**Comment by mah11** [comment]
Let's do this, to keep things moving:

GPI header
- add `date-generated: YYYY-MM-DD`
- add `URL: https://www.pombase.org/`
- add `funding: Wellcome Trust`

GPAD header
- add `date-generated: YYYY-MM-DD`
- add `URL: https://www.pombase.org/`
- add `funding: Wellcome Trust`
- optional (if easy to look up the PURLs): add ontology versions, e.g. `go-version: PURL`

Punt on the comment/citation item; there isn't any obvious place for them in the current GPAD/GPI spec, so Val will have to open a ticket with GO to pursue further. We can open an new ticket here when they respond.

**Comment by kimrutherford** [comment]
I've added the headers, except for `date-generated` in the GPI file which was already there.

And haven't add this yet:
> optional (if easy to look up the PURLs): add ontology versions, e.g. go-version: PURL

> ontology versions (would need the version-specific PURLs, so probably only if it's easy to look them up and capture them)

Could you add an example of a version-specific PURL so I can look into it?

> all we have to do is decide on the "real life" location for the current version of each file and then open a pull request at go-site to update our dataset metadata.
> ...
> or the https equivalents

I think https is the better plan since we're moving in that direction.  For now, I'll put the files here:

 -    https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpad
 -    https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpi

We can leave off the ".gz" as https connections to www.pombase.org are automatically compressed.  We can change the paths later if that makes sense.

**Comment by kimrutherford** [comment]
> Whenever we want to switch over I can put in the go-site pull request.

We're getting closer.  Still need to fix #799 and #800 (and probably other things).

**Comment by kimrutherford** [comment]
I've done a bit more checking a tweaking.  I think both files are looking quite good.

Still need to decide what to put in GPAD column 3 (Relation) - #799.

Next it would be good if there was a validation tool we could run on the files.

**Comment by kimrutherford** [comment]
> Next it would be good if there was a validation tool we could run on the files.

I asked: https://github.com/geneontology/go-annotation/issues/2864#issuecomment-727699296

**Comment by kimrutherford** [comment]
> I think https is the better plan since we're moving in that direction. For now, I'll put the files here:

Last night's load has finished.  I've checked now that the files are now updated each night automatically.

**Comment by mah11** [comment]
>> ontology versions (would need the version-specific PURLs, so probably only if it's easy to look them up and capture them)
>
> Could you add an example of a version-specific PURL so I can look into it?

They don't make it easy to find, but from stuff in my email attic I *think* for releases the PURLs follow this pattern:

https://purl.obolibrary.org/obo/go/releases/yyyy-mm-dd/[filename]
e.g. https://purl.obolibrary.org/obo/go/releases/2020-10-09/go.owl

But we may be SOL if we're using ontology files from the "snapshot" instead of a "release" -- I haven't found any clues to whether a similar pattern works for the snapshot on a given date. You could try if you want ... or we could

- omit the ontology line(s) from the header (which would be fine with me; the spec does say they're optional); or
- ask GO what they want in the header if we're using a snapshot; or
- stick something in (e.g. the snapshot PURL http://purl.obolibrary.org/obo/go/snapshot/go.obo plus a download date) and see if they howl.

**Comment by kimrutherford** [comment]
> omit the ontology line(s) from the header (which would be fine with me; the spec does say they're optional);

Let's go with that for now.  :-)

We can add it later.  (Also I'm lazy)

> Whenever we want to switch over I can put in the go-site pull request.

I assume it's too early for that?

**Comment by mah11** [comment]
>> omit the ontology line(s) from the header (which would be fine with me; the spec does say they're optional);
> 
> Let's go with that for now. :-)
> 
> We can add it later. (Also I'm lazy)

Works for me!

>> Whenever we want to switch over I can put in the go-site pull request.
> 
> I assume it's too early for that?

Actually, I'm very tempted see what happens if we add the GPI and GPAD URLs to our yaml -- I think we could try it, since there are a couple other groups that already produce them (MGI for one). I will wait to remove the GAF link until the new ones have been there for at least a week, maybe a month. But let's stir the pot!

**Comment by kimrutherford** [comment]
> Actually, I'm very tempted see what happens if we add the GPI and GPAD URLs to our yaml -- I think we could try it, 

Sounds good.  It's all set to go as far as I can tell.  These URLs are stable and are now automatically updated each night:

  -  https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpad
  -  https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpi

**Comment by mah11** [comment]
OK! The GO pull request is here: https://github.com/geneontology/go-site/pull/1583

how exciting ...

**Comment by mah11** [comment]
@kimrutherford We've had some feedback on the GPI in https://github.com/geneontology/go-annotation/issues/3607 - from the description I think it translates into "include the prefix `UniProtKB:` along with the ID in column 10".

**Comment by kimrutherford** [comment]
The fix that adds the "UniProtKB:" prefix solved the problem: geneontology/go-annotation#3607

I think I'll close this issue and output new issues for any other problems.
