### ISSUE TITLE
use of phase terms in modification extension

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#794]
Hi Kim,

Could you let us know whether 
any of the Modification annotations use any of this branch of GO
GO:0044848   biological phase

for  "required for process"

The answer I am looking for is "none"

**Comment by kimrutherford** [comment]
Sorry this took so long.

> The answer I am looking for is "none"

That's answer I got.  :-)

**Comment by ValWood** [comment]
;)
