### ISSUE TITLE
make transcript isoform IDs usable

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#795]
Well, it looks like it's time to revive the issue of using transcript isoform IDs (not needed back when #236 was open). As noted in the [Canto ticket](https://github.com/pombase/canto/issues/2351) and [website ticket](https://github.com/pombase/website/issues/1613), we now have actual examples where either an annotation or an extension is specific for a transcript isoform.

On the website, info seems to appear only for one transcript; in the tco1 example, it's got the product for the longest transcript but qualitative expression for the shorter (maybe because the shorter one comes first in the contig file??). 

In Canto I've stuck some notes about isoform specificity in comments for a few wtf annotations, because I can't add transcript-specific IDs to the gene list. For extensions, these warnings now crop up in the Canto log:

    warning in fd7d19b1aed14f7c: in annotation extension for fd7d19b1aed14f7c-genotype-1, can't parse identifier: SPAC17G6.02c.2
    warning in fd7d19b1aed14f7c: in annotation extension for PomBase-genotype-3269, can't parse identifier: SPAC17G6.02c.2
    warning in fd7d19b1aed14f7c: in annotation extension for PomBase-genotype-3269, can't parse identifier: SPAC17G6.02c.1
    warning in fd7d19b1aed14f7c: in annotation extension for fd7d19b1aed14f7c-genotype-3, can't parse identifier: SPAC17G6.02c.2
    warning in fd7d19b1aed14f7c: in annotation extension for fd7d19b1aed14f7c-genotype-3, can't parse identifier: SPAC17G6.02c.1

(Note: there are also a bunch of copies of this warning for the same session, which appear to be spurious, as there's no "figure" entry: `warning in fd7d19b1aed14f7c: some data from annotation isn't used: figure`.)

**Comment by kimrutherford** [comment]
We now have an extension relation to select the isoform ("transcript isoform ID", pombase/canto#2351).
The Canto->Chado loader needs changing to use the new relation.

**Comment by kimrutherford** [comment]
> The Canto->Chado loader needs changing to use the new relation.

I forgot that I had already done that last week.  I've tweaked it to use "transcript isoform ID" instead of "annotated transcript ID".

Let me know when you start using the "transcript isoform ID" in Canto so I can test that everything works.

The next task is:
   - pombase/website#1789

**Comment by kimrutherford** [comment]
I think this is done.
