### ISSUE TITLE
log warnings from gene expression evidence

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#797]
The current Canto load log (log.2020-10-22-21-50-19.curation-tool-data-load-output) has one of these for each RNA level annotation in the session:

`warning in 5e96383ce64d7245: unknown evidence code: Northern blot`

I haven't added any RNA level annotations with any of the other evidence options, nor any protein level annotations, anywhere, so I don't know if it's specific to the "Northern blot" evidence.

**Comment by kimrutherford** [comment]
Sorry, I forgot that the Chado load and Canto have different evidence code configurations.  The config doesn't match up at the moment.

Canto has "Microarray", the Chado config has:
"Microarray RNA expression level data"  and "expression microarray evidence"  (from ECO)

Canto has "Northern blot", Chado has:
"Northern assay evidence"  (from ECO)

These three match in Chado and Canto:
   - Quantitative PCR
   - Reporter gene assay
   - Western blot

So should we change Canto to use "expression microarray evidence" and "Northern assay evidence" from ECO?  Those names can be shortened to "expression microarray" and "Northern assay" as the "evidence" is optional.

**Comment by mah11** [comment]
> So should we change Canto to use "expression microarray evidence" and "Northern assay evidence" from ECO? Those names can be shortened to "expression microarray" and "Northern assay" as the "evidence" is optional.

OK. I like the shorter versions, since these appear in a pulldown labeled "evidence code".

**Comment by kimrutherford** [comment]
I've changed the evidence codes in Canto.  If there are lots of annotations that need fixing to match the changes, let me know.  If it's not so many, changing them in Canto will probably be quicker.

**Comment by mah11** [comment]
There are 8, all in the same session, so I'll fix them manually. Thanks!

**Comment by ValWood** [comment]
closing?
