### ISSUE TITLE
filtering some external data

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#798]
GO:0006468 | protein phosphorylation
is in the file
filtered_GO_IDs
which contains IDs where we filter data from alternate sources.

Howeer this seems to not be used for the PAINT annotation. Possibly this needs to be configured.

https://www.pombase.org/gene/SPCC16C4.11

**Comment by ValWood** [comment]
I think that file is being ignored. I still see
negative regulation of insulin receptor signaling pathway (GO:0046627)
(although I can't remember when I added that one so will check on Monday)

**Comment by ValWood** [comment]
also this:


GO:0007064 | mitotic sister chromatid cohesion | IBA with FBgn0260987 , S000002161 , PTN000286904 , rad21 , ZDB-GENE-030131-994

is visible
https://www.pombase.org/gene/SPBC29A10.14

but PTN000286904 is In the "filtered_mappings" file

**Comment by kimrutherford** [comment]
> but PTN000286904 is In the "filtered_mappings" file

The PANTHER loading step wasn't using that file because the file is in the goa-load-fixes directory.  I didn't know it applied to PANTHER too.

I've added that filter now but not in time for the Sunday night load.

**Comment by ValWood** [comment]
I forgot that we load PAINT directly from G
So both filtered_GO_IDs and filtered_mappings apply to PANTHER too.
those files are really  "external_GO_annotation_fixes"

**Comment by kimrutherford** [comment]
> So both filtered_GO_IDs and filtered_mappings apply to PANTHER too.

OK, I changed the load script so that PANTHER annotation will be filtered with filtered_GO_IDs too.

**Comment by kimrutherford** [comment]
> GO:0007064 | mitotic sister chromatid cohesion | IBA with FBgn0260987 , S000002161 , PTN000286904 , rad21 , ZDB-GENE-030131-994
> is visible

Looks like that one is gone now.

**Comment by ValWood** [comment]
all good
