### ISSUE TITLE
add ND annotations to GPAD

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#799]
as discussed on 2020-11-05 call; GO wants 'em included for bookkeeping
use same criteria as for adding them to the GAF
holler if any questions ...

**Comment by kimrutherford** [comment]
Do we need to put anything in column 3 (Relation) for ND lines?

Also is this the correct ECO ID for ND?:
  https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000307

And should we use GO_REF:0000015 for the reference like we do for the GAF files?

**Comment by ValWood** [comment]
Good question !
I don't remember this ever being asked. I'll find out...

**Comment by ValWood** [comment]
1.  Thinking about it, here, since we are normally referring to  MF enabled by, BP  involved in  and CC (localized to?) , if we negate we should use these codes in negation
2. That is the correct ECO code
3. Yes, although this isn't clear  https://github.com/geneontology/go-site/issues/1575

**Comment by kimrutherford** [comment]
> I don't remember this ever being asked. I'll find out...

Thanks.

> 2. That is the correct ECO code
> 3. Yes, although this isn't clear geneontology/go-site#1575

Great.  That's what I've implemented.

**Comment by kimrutherford** [comment]
I've now check the output and we get the same number of annotation lines in the new GPAD output and the GAF files that we're currently sending to GO.  Same number of ND lines too so I'm fairly confident that it's all OK.

**Comment by kimrutherford** [comment]
> Thinking about it, here, since we are normally referring to MF enabled by, BP involved in and CC (localized to?) , if we negate we should use these codes in negation

It sounds like the relation can be inferred from the aspect.  I don't know what GO will require but if the relation can be inferred I think the column should be blank for ND lines.  Otherwise it's redundant noise.

**Comment by mah11** [comment]
> Do we need to put anything in column 3 (Relation) for ND lines?

This came up at the last GO annotation call. [Minutes](http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2020-11-03#GAF_2.2_and_GPAD.2FGPI_2.0) don't have much besides the bottom line, which is:

-   Biological Process -> involved_in
-   Molecular Function -> enables
-   Cellular Component -> is_active_in

**Comment by mah11** [comment]
p.s. "redundant noise" is the name of the game!

**Comment by kimrutherford** [comment]
Thanks.  I've added the noise in column 3 and updated:
 https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpad

I think this is done now.
