### ISSUE TITLE
ncRNA annotation in GPAD/GPI

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#801]
In the GAF files for ncRNAs we only add an ND line for an aspect if there is annotation for one of the other two aspects.  If there is no annotation for an ncRNA (eg. SPNCRNA.933) we don't write anything.  Should we continue to do that for GPAD?

We only have this special case in the code for ncRNA genes.  Is that correct?  Other RNA types are in the GAF output even if there are no annotations (eg. SPSNORNA.10 just has 3 ND lines).

Also does an ncRNA gene need to be in the GPI file if there is no annotation in the GPAD file?  I'm inclined to put all our gene IDs in the GPI file but mostly because that's what it does at the moment and I'm lazy.  :-)

I noticed that the GPAD/GPI writing code isn't handling ncRNAs properly but I thought I'd double check before I get it to match the GAF output.

**Comment by ValWood** [comment]
> In the GAF files for ncRNAs we only add an ND line for an aspect if there is annotation for one of the other two aspects.  If there is no annotation for an ncRNA (eg. SPNCRNA.933) we don't write anything.  Should we continue to do that for GPAD?

Yes

> We only have this special case in the code for ncRNA genes.  Is that correct?  Other RNA types are in the GAF output even if there are no annotations (eg. SPSNORNA.10 just has 3 ND lines).

Yes, include rRNA, snoRNA, tRNA but exclude ncRNA unless these is an annotation to a single aspect

> Also does an ncRNA gene need to be in the GPI file if there is no annotation in the GPAD file?  I'm inclined to put all our gene IDs in the GPI file but mostly because that's what it does at the moment and I'm lazy.  :-)

I  think you can go ahead and include them. even if we decide to exclude a subset later.

**Comment by kimrutherford** [comment]
> Yes, include rRNA, snoRNA, tRNA but exclude ncRNA unless these is an annotation to a single aspect

Thanks.  That's what I've implemented.

> I think you can go ahead and include them. even if we decide to exclude a subset later.

I've done that too.

The load is still running.  I had to re-start it because the EBI FTP server is offline and the load script couldn't cope.  I've fixed the script.

When the load is done in a few hours, the test GPAD and GPI will have the fixes.  Currently they are here:
 - https://curation.pombase.org/dumps/latest_build/misc/gene_product_annotation_data_taxonid_4896.tsv
 - https://curation.pombase.org/dumps/latest_build/misc/gene_product_information_taxonid_4896.tsv

but I'm working on putting them somewhere better as discussed in: https://github.com/pombase/pombase-chado/issues/792

**Comment by mah11** [comment]
>>> I'm inclined to put all our gene IDs in the GPI file ...
>> 
>> I think you can go ahead and include them. even if we decide to exclude a subset later.
> 
> I've done that too.

I'm in favor too. It's consistent with the stated aim of GO having GPI files.

**Comment by ValWood** [comment]
> I'm in favor too. It's consistent with the stated aim of GO having GPI files.

yes but including all of the annotated ncRNAs in their current state would be  akin to including dubious protein  entries  in GO (which we don't do), or including Trembl protein (redundant), which we also don't do in GO. Personally I think ncRNAs shouldn't be included until the gene structures are reviewed, and a consensus is reached. This would be more consistent with other databases, no other databases have created ncRNA features form RNA seq data (as far as I am aware).

**Comment by kimrutherford** [comment]
> Personally I think ncRNAs shouldn't be included

Just to check: do you mean the ncRNAs without annotation shouldn't be included or all ncRNA shouldn't be included?

**Comment by ValWood** [comment]
I meant without annotation. But they can all be included for now if it is easier, and weeded out later. I just had a slight preference to  keep them out of GO at this stage until we know what we are dealing with.

**Comment by kimrutherford** [comment]
> I meant without annotation.

Thanks.  I've implemented that.
