### ISSUE TITLE
Load gene expression annotation from Canto

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#802]
Currently they're being ignored apart from checking that the evidence code is valid.

**Comment by kimrutherford** [comment]
I've tested loading the Canto gene expression annotation and that works.  But the terms used in Canto don't match up nicely with terms used when loading gene expression from the contig files and from the qualitative gene expression HTP files.

Canto uses terms like "RNA level increased" (from `pombase_gene_expression_ontology.obo`) but everything else uses just "RNA level" and "protein level" and has a qualifier to shows what happened to the level.  Which plan is best?  I'd prefer to change all the annotation to use the terms that Canto uses because it makes the Canto implementation simple.

The section on the gene pages would need to change a bit too.  Currently we have a special case for gene expression so that the qualifier+extension column is labelled "Level":

![Screenshot from 2021-01-22 16-45-32](https://user-images.githubusercontent.com/90474/105444192-44144a00-5cd2-11eb-8ca6-b43d080e1157.png)

**Comment by mah11** [comment]
> I'd prefer to change all the annotation to use the terms that Canto uses because it makes the Canto implementation simple.

I'm happy to change the entries in Artemis for this (a good Friday afternoon kind of task). One question: at present they look like this:

`/controlled_curation="term=gene expression, RNA level; qualifier=increased; [etc.]`

Should I change them to
`/controlled_curation="term=gene expression, RNA level increased; [etc.]`

or
`/controlled_curation="term=gene expression; qualifier=RNA level increased; [etc.]` ?

**Comment by mah11** [comment]
> The section on the gene pages would need to change a bit too.

Yeah, I think it'll probably end up looking nicer - we can put the gene first (where relevant) and just have a "Description" column with the PomGeneEx term names.

**Comment by kimrutherford** [comment]
> I'm happy to change the entries in Artemis for this (a good Friday afternoon kind of task).

Thanks but there's no need for that.  I've changed the loading code to remove the qualifier while processing the annotation and then to modify the term name using the qualifier.  For example it changes (in memory):
```
term=gene expression, protein level; qualifier=increased; ...
```
to
```
term=gene expression, protein level increased; ...
```

and it changes:
`term=gene expression, RNA level; qualifier=absent;` to `term=gene expression, RNA absent;`

So no need to edit the contig files.

The code also supports using the new term names directly like:
```
FT                   /controlled_curation="term=gene expression, RNA level increased;
FT                   annotation_extension=during(GO:0042149);
FT                   evidence=ECO:0005653;
FT                   db_xref=PMID:20396879; date=20120227"
```

I'll check the next load to make sure this all worked OK.

**Comment by mah11** [comment]
even better ;)

**Comment by kimrutherford** [comment]
The load failed last night due to these changes.  I think I've fixed things so I'll try again tonight.

**Comment by kimrutherford** [comment]
It's all looking good now.
