### ISSUE TITLE
Decide how to export multi-transcript RNAs for RNAcentral

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#803]
Currently we export the sequence of the first transcript (eg. SPNCRNA.103.1)

**Comment by ValWood** [comment]
overlapping?
https://github.com/pombase/pombase-chado/issues/795

I think we should just export all annotated isoforms?

**Comment by ValWood** [comment]
Although the RNAs need work. Ticket to open shortly...

**Comment by kimrutherford** [comment]
> I think we should just export all annotated isoforms?

I'll investigate how the multiple isoforms should be represented in the RNACentral JSON format.

**Comment by kimrutherford** [comment]
> I'll investigate how the multiple isoforms should be represented in the RNACentral JSON format.

It looks like it won't be a problem.  We just need to add a section for each transcript.  

Unfortunately while checking I noticed that we are putting the gene ID in the field where the transcript ID should go.  I've contacted RNACentral to make sure it's OK for us to change the ID of every RNA we send them.

**Comment by kimrutherford** [comment]
I've made the changes needed to support exporting multi-transcript RNA genes for RNAcentral.  I'll commit the fix once I hear back from their help desk about the ID changes.

**Comment by kimrutherford** [comment]
Reply from RNAcentral:

> Thank you for telling us about this change. You should be able to change the ids
> as you would like and it shouldn't cause any issues. If it does then they are
> bugs on our end. Thanks!

So it's all good.  I've commit the changes and I'll check that it's all OK on the FTP tomorrow morning.
