### ISSUE TITLE
wis1 GO annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#804]
I can't figure where this 'existing' annotation in my Canto session is coming from:

wis1 | GO:0005634 | nucleus | IDA | exists_during cellular response to stress

It isn't in Artemis, or in external_GO_data (including From_curation_tool)

Is there another place ? I can't think of anywhere...

**Comment by mah11** [comment]
What paper?

**Comment by ValWood** [comment]
PMID:12181336

**Comment by ValWood** [comment]
I'm baffled. It's def one of ours and not an inference via GOC (at least it has assigned by PomBAse in QuickGO)

**Comment by mah11** [comment]
It is in Artemis. chromosome2.contig has

    FT                   /GO="aspect=C; term=nucleus; GOid=GO:0005634;
    FT                   annotation_extension=exists_during(GO:0033554);
    FT                   evidence=IDA; db_xref=PMID:12181336; date=20060503"

**Comment by ValWood** [comment]
That very weird. I must have deleted it and forgotten....

**Comment by ValWood** [comment]
Like in the past half hour...
