### ISSUE TITLE
Revise gene structure boundaries  (UTRs)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#805]
Proposed plan (revised)

 1. @kimrutherford 
Rerun the old scripts to use only the manually curated from small scale publications and the curated Lantermann data.

2. @ValWood 
Remove existing UTRS and replace with these as the default curated set (1) and perform a quick sanity check

3. Announce the changes (pombelist/tweet, and explain that we will manually annotate UTRs on a case by case bases as requested @ValWood 

4. Update FAQs for UTR sources, and create news item @mah11 

5. After all the gene structure-related data is hosted in JBrowse, I will whiz through  the annotation in a couple of days and look for obvious errors like grossly misannotated UTRS,  or missing/ incorrect introns etc (I.e comparing the new annotation to the informative data tracks TSS, polyA and Transcription unit)

This will make the whole process easier to manage from a curation point of view. I will confirm this as soon as  the Lantermann and Gagneur datasets are hosted, but I'm pretty confident that these datasets will be OK.

We will deal with ncRNA annotation separately in consultation with @bahler

The Gagneur paper reports:
487 novel TU (but these could be ncRNAs)
could not recover 1,011 previously recovered RNAs
Refined 1481 coding transcripts by >200 not (I suspect these proposed refinements are entirely due to the Broad/Rhind dataset, because more were reported as over extended)
REVISIONS TO 34% of gene boundaries

**Comment by kimrutherford** [comment]
Hi Val.

How much of this is still relevant after our chat last Thursday.

Does this still need doing?:

> Rerun the old scripts to use only the manually curated from small scale publications and the curated Lantermann data.

**Comment by ValWood** [comment]
Based on the discussion last week I think we can close this one. I summarized where I got stuck today in 2 new tickets.
