### ISSUE TITLE
 GO IDs  not in the OBO file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#806]
Looking in the logs I spotted  these in the gaf check- seems odd because these terms aren't  new?

@mah11 any idea why?

1: GOID column=5 This ID "GO:0140445" is not in the OBO file.  Is the OBO file up-to-date? Is it the correct GOID?
PomBase	SPAC212.11	tlh1		GO:0140445	PMID:15591066	IDA		C	RecQ type DNA helicase		protein	taxon:4896	20050110	PomBase		

88: GOID column=5 This ID "GO:0140318" is not in the OBO file.  Is the OBO file up-to-date? Is it the correct GOID?
PomBase	SPAC13G6.04	tim8		GO:0140318	GO_REF:0000024	ISO	SGD:S000007348	F	Tim8-Tim13 mitochondrial intermembrane space protein transporter complex subunit Tim8 (predicted)		protein	taxon:4896	20040505	PomBase		

171: GOID column=5 This ID "GO:0140490" is not in the OBO file.  Is the OBO file up-to-date? Is it the correct GOID?
PomBase	SPAC806.08c	mod21	contributes_to	GO:0140490	PMID:21993292	TAS		F	gamma tubulin complex GPC5 subunit Mod21		protein	taxon:4896	20200710	PomBase		

794: GOID column=5 This ID "GO:0106300" is not in the OBO file.  Is the OBO file up-to-date? Is it the correct GOID?
PomBase	SPAC521.02	wss1		GO:0106300	GO_REF:0000024	ISO	SGD:S000001176	P	WLM domain metallopeptidase implicated in DNA repair Wss1 (predicted)		protein	taxon:4896	20201104	PomBase

**Comment by ValWood** [comment]
I could see the terms in QuickGO

**Comment by mah11** [comment]
The "gaf-check" log is no longer reliable, because it's just a deployment of Mike Cherry's ancient GAF-checking script, and points to a GO OBO file that isn't kept up to date any more.

Options: ask @kimrutherford to turn off that check, or simply ignore that log file. It doesn't do enough checks to be worth carrying on with it.

**Comment by kimrutherford** [comment]
> @kimrutherford to turn off that check, 

Sounds sensible, especially as we're moving away from GAF.

**Comment by ValWood** [comment]
OK, I wos only fixing the ortholog logs and I got side-tracked!

**Comment by kimrutherford** [comment]
I've changed the load script so that we now don't run that gaf-check.
