### ISSUE TITLE
Malacards log file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#807]
These are in the log file
log.2020-12-12-21-28-22.malacards_data.txt
but I don't know where they originate from?

~"phenotype" doesn't look like a MONDO ID - skipping~
~"not a disease" doesn't look like a MONDO ID - skipping~
~"phenotype" doesn't look like a MONDO ID - skipping~
~"phenotype" doesn't look like a MONDO ID - skipping~
~"not a disease" doesn't look like a MONDO ID - skipping~
~"phenotype" doesn't look like a MONDO ID - skipping~
~"blood group" doesn't look like a MONDO ID - skipping~
~"phenotype" doesn't look like a MONDO ID - skipping~
~"blood group" doesn't look like a MONDO ID - skipping~
~"blood group" doesn't look like a MONDO ID - skipping~
~"phenotype" doesn't look like a MONDO ID - skipping~
~"blood group" doesn't look like a MONDO ID - skipping~
~"can't find literature references to this" doesn't look like a MONDO ID - skipping~
~"not a single disease" doesn't look like a MONDO ID - skipping~
~"phenotype" doesn't look like a MONDO ID - skipping~
~"not a single disease" doesn't look like a MONDO ID - skipping~
~"doesn't map, no mondo ID - phenotype?" doesn't look like a MONDO ID - skipping~
~"maps to HPO" doesn't look like a MONDO ID - skipping~
~"These are two conditions" doesn't look like a MONDO ID - skipping~
~"These are two conditions" doesn't look like a MONDO ID - skipping~

**Comment by kimrutherford** [comment]
They're from column 5 of external_data/disease/malacards_data_for_chado_mondo_ids.tsv

Some MONDO IDs are missing and some have rows have a note like "phenotype" instead of an ID.
