### ISSUE TITLE
some paralogs missing disease associations

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#808]
based on the malacards mapping file
https://curation.pombase.org/dumps/latest_build/pombe-embl/external_data/disease/
malacards_data_for_chado_mondo_ids.tsv:hyperinsulinemic hypoglycemia, familial, 3 hyperinsulinemic_hypoglycemia_familial_3_2    Hyperinsulinemic Hypoglycemia, Familial, 3    GCK    MONDO:0011236
malacards_data_for_chado_mondo_ids.tsv:maturity-onset diabetes of the young, type 2 maturity_onset_diabetes_of_the_young_type_2    Maturity-Onset Diabetes of the Young, Type 2    GCK    MONDO:0007453
malacards_data_for_chado_mondo_ids.tsv:diabetes mellitus, noninsulin-dependent    diabetes_mellitus_noninsulin_dependent Diabetes Mellitus, Noninsulin-Dependent    GCK    MONDO:0005148
malacards_data_for_chado_mondo_ids.tsv:fasting plasma glucose level quantitative trait locus 5 fasting_plasma_glucose_level_quantitative_trait_locus_5Fasting Plasma Glucose Level Quantitative Trait Locus 5    GCKR
malacards_data_for_chado_mondo_ids.tsv:monogenic diabetes monogenic_diabetes    Monogenic Diabetes    GCK    MONDO:0015967
malacards_data_for_chado_mondo_ids.tsv:maturity-onset diabetes of the young    maturity_onset_diabetes_of_the_young Maturity-Onset Diabetes of the Young    GCK    MONDO:0018911 

hxk1
should have
MONDO:0011534    Charcot-Marie-Tooth disease type 4G
MONDO:0011236    hyperinsulinism due to glucokinase deficiency
MONDO:0018911    maturity-onset diabetes of the young (disease)
MONDO:0007453    maturity-onset diabetes of the young type 2
MONDO:0015967    monogenic diabetes
MONDO:0009340    non-spherocytic hemolytic anemia due to hexokinase deficiency
MONDO:0005148    type 2 diabetes mellitus

because GCK is listed as an orthlog.

However these mappings are only applied to hsk2:
hxk2.  https://www.pombase.org/gene/SPAC4F8.07c

https://www.pombase.org/gene/SPAC24H6.04

**Comment by ValWood** [comment]
A similar situation with htr11/12
htr11 has only one association (from artemis)
all of the malacards mappings are on htr12

**Comment by ValWood** [comment]
You can probablly ignore this. I don't really know how this mapping file is used to generate the malacards annotstion, but it seems I can add these annotations  to the Pombase file anyway....

**Comment by ValWood** [comment]
Is there a way to automate this fix?

Essentially if 2  (or more) pombe genes map to a single human gene, we want the disease mapping on all of the pombe genes/proteins.

Perhaps  this shouldn't be done until we get rid of the convoluted disease gene pipeline (I'm still finding this very confusing  to keep updated, and I'm not really sure how old DO ids get mapped over to MONDO). Perhaps we should discuss this  on the next call and outline a plan to make the  disease mappings easier for me to maintain.

**Comment by ValWood** [comment]
actually we have a ticket for this already
https://github.com/pombase/pombase-chado/issues/777
so this one can come after.

**Comment by kimrutherford** [comment]
>  I don't really know how this mapping file is used to generate the malacards annotation,

Which mapping file?

**Comment by ValWood** [comment]
there is a file
malacards_data_for_chado_mondo_ids.tsv
I *think* all of the associations in Artemis are assigned a MONDO id via this mapping file based on pattern matching. 
This is the step I want to get rid of because its a maintenance headache.

**Comment by kimrutherford** [comment]
> I think all of the associations in Artemis are assigned a MONDO id via this mapping file based on pattern matching.

The /controlled_curation annotations in the contig files are mapped to MONDO IDs using this file:
`pombe-embl/chado_load_mappings/disease_name_to_MONDO_mapping.txt`

But those annotations will soon be gone once I finish this: pombase/pombase-chado#776

The Malacards data file (malacards_data_for_chado_mondo_ids.tsv) contains MONDO IDs so it gets loaded directly.  We also load the Malacards description and ID so we can link to the right page on Malacards website.

Once pombase/pombase-chado#776 is done we'll be left with:
   - `malacards_data_for_chado_mondo_ids.tsv` - which has human gene IDs, MONDO IDs and the Malacard Ids
   - `pombase_disease_associations_mondo_ids.txt` - which has pombe gene IDs and MONDO IDs

**Comment by kimrutherford** [comment]
Now I've thought about it and looked at the code I think I understand the original problem with paralogs/orthologs.  It looks like there is a bug in the code that means the human IDs are only mapped to one pombe ID.  Sorry, I was ignoring the case where there are pombe paralogs.  Should be a quick fix!

**Comment by ValWood** [comment]
> Should be a quick fix!

I would do this once we are sure that exporting the annotations from artemis we still  get 
1244.

**Comment by kimrutherford** [comment]
OK, that makes sense.

**Comment by kimrutherford** [comment]
I've just tried the fix locally.

Before the fix, I get 2431 annotations to 966 pombe genes.
After I get 3076 annotations to 1187 pombe genes.

So that's a nice improvement.  Sorry about the bug and the slow fix.

I'll commit this fix tomorrow after we've checked the contig annotation changes.

**Comment by kimrutherford** [comment]
I've now committed the fix so the changes should be visible in the morning.

**Comment by kimrutherford** [comment]
That seems to have worked.

The count of genes with disease associations has gone from 1246 to 1350.  And the number of annotations has gone from 3892 to 4537.

Here's before and after:
https://www.pombase.org/results/from/id/e9a13d21-7b2a-4d9f-902d-27f9ff203fbe
http://dev.pombase.kmr.nz/results/from/id/989b9e7b-8119-4c4f-8f23-4928bbfc19cd

Shall I go ahead and update the main site?

**Comment by ValWood** [comment]
Yay, yes!

**Comment by kimrutherford** [comment]
> Shall I go ahead and update the main site?

The main site now has the new annotations.
