### ISSUE TITLE
protein coding cohort dropped by one

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#809]
5065->5064...I don't know why?? have I deleted a CDS by mistake?

**Comment by kimrutherford** [comment]
The difference is:


SPCC548.03c | wtf4 | wtf meiotic drive poison Wtf4 | protein coding | dubious
-- | -- | -- | -- | --

it was "biological role inferred"

**Comment by ValWood** [comment]
fixed, changed to "published"
