### ISSUE TITLE
disease logs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#810]
the logs say
https://curation.pombase.org/dumps/latest_build/logs/log.2020-12-21-21-16-53.malacards_data

could not find cvterm for MONDO:0010935 - maybe obsolete?  Skipping annotation for SPAC3A11.04 / neuronopathy_distal_hereditary_motor_type_va
could not find cvterm for MONDO:0019523 - maybe obsolete?  Skipping annotation for SPBC16C6.09 / walker_warburg_syndrome

but these IDs seem to be existing in Mondo- I can't seem to trace the problem?

**Comment by kimrutherford** [comment]
They're both obsolete:

```
[Term]
id: MONDO:0010935
name: obsolete neuronopathy, distal hereditary motor, type 5A
comment: OMIM merged these.
property_value: seeAlso https://github.com/monarch-initiative/mondo/issues/2354 xsd:string
is_obsolete: true
replaced_by: MONDO:0015353

[Term]
id: MONDO:0019523
name: obsolete Walker-Warburg syndrome
comment: These are considered equivalent in OMIM.
property_value: seeAlso https://github.com/monarch-initiative/mondo/issues/1223 xsd:string
is_obsolete: true
replaced_by: MONDO:0000171
```

**Comment by ValWood** [comment]
Thanks.  OLS and Monarch are always behind us...Could you add the replaced_by tag to the log file  so I don't need to look in the ontology?

**Comment by kimrutherford** [comment]
> Could you add the replaced_by tag to the log file so I don't need to look in the ontology?

That will take a bit of work.  We aren't loading the replaced_by property into Chado so the disease loading code has no easy way to look it up so it can write it to the log.  It will probably take a hour-ish to implement.

**Comment by ValWood** [comment]
I think it would be worth it....there is a hell of a lot of churn in MONDO and various  different reasons that mappings break, some are merges, some are splits- it's quite a bit of work to know which action to take. Knowing there is a replaced by would save a lot of time because those are a quicker fix.

**Comment by kimrutherford** [comment]
OK, I've made an issue: pombase/chobo#15

**Comment by ValWood** [comment]
So this one can close?

**Comment by kimrutherford** [comment]
The replaced_by term is now mentioned in the log messages when loading obsolete terms from malacards_data_for_chado_mondo_ids.tsv

(Well, it probably is - there were no log messages last night to double check)

I'll change the code that loads pombase_disease_associations_mondo_ids.txt to do the same thing.

**Comment by kimrutherford** [comment]
> I'll change the code that loads malacards_data_for_chado_mondo_ids.tsv to do the same thing.

I've done that now.

I've also changed the code that reads `malacards_data_for_chado_mondo_ids.tsv` and `malacards_data_for_chado_mondo_ids.tsv` to give a sensible warning, rather than failing, when there are spaces instead of tabs.  You'll see a message like:
```
needed 6 columns, got 5 - ignoring line 4
```

**Comment by ValWood** [comment]
brill, thanks

**Comment by kimrutherford** [comment]
> I'll change the code that loads pombase_disease_associations_mondo_ids.txt to do the same thing.

I forgot to do that but it's done now.
