### ISSUE TITLE
disease logs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#811]
These don't appear in the logs, but I think they should as they don't appear on the gene pages

pombase_disease_associations_mondo_ids.txt:SPBC17A3.01c    tim50    MONDO:0016021        PMID:30190335    2019-05-18
pombase_disease_associations_mondo_ids.txt:SPAC22G7.06c    ura1    MONDO:0016021        PB_REF:0000003    2020-05-12

**Comment by kimrutherford** [comment]
MONDO:0016021is obsolete:

```
[Term]
id: MONDO:0016021
name: obsolete early infantile epileptic encephalopathy
comment: This term will be renamed to 'developmental epileptic encephalopathy' in OMIM.
property_value: seeAlso https://github.com/monarch-initiative/mondo/issues/2027 xsd:string
is_obsolete: true
replaced_by: MONDO:0100062
```
