### ISSUE TITLE
some data missing from HCPIN download datasets

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#812]
cut12
https://www.pombase.org/gene/SPBC649.05

has

GO:0030295 protein kinase activator activity
regulates activity of plo1

and
signaling adaptor activity
has input dis2 p
has input plo1

but these substrate relation annotations do not appear in
pombase-go-substrates.tsv.gz
ftp://ftp.pombase.org/pombe/high_confidence_physical_interactions/

these are the only ones (with cut12 as the target , not the effector)
SPBC11B10.09    SPBC649.05    PMID:23333317
SPAC19E9.02    SPBC649.05    PMID:23333317

**Comment by kimrutherford** [comment]
The code to create pombase-go-substrates.tsv.gz only looks for `has_direct_input()`, `directly_negatively_regulates()` and `directly_positively_regulates()`.  From this issue: https://github.com/pombase/pombase-chado/issues/638#issuecomment-316963470

> GO:0030295 protein kinase activator activity
> regulates activity of plo1
 
This is `has_regulation_target(plo1)`

> signaling adaptor activity
> has input dis2
> has input plo1

These are both `has_input()`

Should I change the code?

**Comment by ValWood** [comment]
yes please. has_direct_input was changed to has_input for molecular function. So these should probably be bulk replaced. This will increase the connections a lot- I thought the coverage wasn't going up very quickly !

It would be good to check how many "has regulation target" there are. I think these should be has_input too... with display label "regulates activity of" , but wait to check that with Midori.

If quick  you could include "has regulation target" for now (but only if the connection is on MF, not on BP)

**Comment by kimrutherford** [comment]
> If quick you could include "has regulation target" for now (but only if the connection is on MF, not on BP)

I think it will be quick.

Does has_input() need to be restricted to MF too?

**Comment by ValWood** [comment]
yes, i think it might only be used for MF, but I'm not sure....

**Comment by kimrutherford** [comment]
Last night I change the code to include has_input() and has_regulation_target() for MF annotations.  Re-reading this morning I wonder if I misunderstood and you're waiting for Midori's comments?

**Comment by ValWood** [comment]
As long as that is only for MF what you have done is fine.
I just want to check which relations and display labels we should use here. The config file might need reviewing to, so keep the ticket open. I'll check the HCPIN data and see if the connections I expected get through to the networks.

**Comment by kimrutherford** [comment]
> As long as that is only for MF what you have done is fine.

OK, great.  The changes should be in the pombase-go-substrates.tsv.gz from last night's load.

**Comment by ValWood** [comment]
This worked in principle, as I. cansee missing annotations in the file.
However the directional interaction data did not make  it through to the esyN networks because
the lines now have a new column "molecular function":

molecular_function	SPBP4H10.04.1	SPAC4G8.13c	PMID:15657058
molecular_function	SPAC1565.04c.1	SPBC1D7.05	PMID:8816472
molecular_function	SPAC23E2.01.1	SPAC23G3.02c	PMID:20435771

**Comment by kimrutherford** [comment]
Sorry about that!

I've fixed the code and I've remove that column from the file in: https://curation.pombase.org/dumps/latest_build/exports/

**Comment by ValWood** [comment]
Yay! This increases the number of proteins included in the network figures from
2505 to 2740. I feel as though I am making progress again. I couldn't understand why I was stuck  at the 50% mark ;) 3000 is my new target!

**Comment by ValWood** [comment]
Well the networks are not yet updated, that will probably take a few days, but the data is there!

**Comment by ValWood** [comment]
Closing, because any remaining problem must be esyN updating. I mailed Dan.
