### ISSUE TITLE
reciprocating protein binding doesn't work if the  entity binding the protein is an RNA

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#815]
small bug.

For GO protein binding we reciprocate if the interactions are missing.

However here:
<img width="524" alt="Screenshot 2021-02-23 at 17 53 42" src="https://user-images.githubusercontent.com/7359272/108885887-3d922e80-7600-11eb-82a7-441cc7777e70.png">

The annotations were made
mei2 RNA binding to sme2
and
sme2 protein binding mei2

this has been reciptocated to
mei2 protein binding sme2 BUT sme2 is an ncRNA (SPNCRNA.103)

**Comment by kimrutherford** [comment]
I've fixed that for tonight's load and I'll check in the morning.

**Comment by kimrutherford** [comment]
> I've fixed that for tonight's load and I'll check in the morning.

My fix was a failure.  I've tried again and I'll check after the next load.

**Comment by kimrutherford** [comment]
> My fix was a failure. I've tried again and I'll check after the next load.

It looks good now.
