### ISSUE TITLE
loading GAF 2.2 from GO - handling multiple qualifier entries

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#816]
GO has switched the snapshot output GAFs to GAF 2.2 format. As a result, the gaf-load-output logs now flag a few lines that we're loading from http://snapshot.geneontology.org/annotations/pombase.gaf.gz:

`annotation with multiple qualifiers (NOT|enables)` and
`annotation with multiple qualifiers (NOT|involved_in)` appear.

To fix them for our GAF, just discard the pipe and everything after it in the column. For the GPAD, the `NOT` goes in its own column, so the bit after the pipe should be either retained (or re-created using our usual GPAD-generating thingamajig, whichever's easier for you) and go into the relation column.

Let me know if anything isn't clear and I can try to explain more.

**Comment by kimrutherford** [comment]
That should be fixed for Thursday night's load.  I'll check on Friday.
