### ISSUE TITLE
GO GAF file from Pombase downloads

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#817]
column 16 contains a mixture of 'source' and 'extensions

part_of(GO:0140326)
part_of(GO:0140357)
part_of(GO:0140425)
part_of(GO:0140480)
part_of(GO:1900038)
.
.
GO_Central
InterPro
PomBase
UniProt

**Comment by ValWood** [comment]
and column 17 a mixture of extensions and modified form.

Sorry- I thought I reported already, but I can't find a ticket.....

**Comment by kimrutherford** [comment]
Which file is this?  Could you add the URL to the issue?

**Comment by ValWood** [comment]
I can add the direct link because it is an automatic download.

It's the "Pombase" link from here:
https://www.pombase.org/downloads/go-annotations

It downloads the file
gene_association.pombase

**Comment by ValWood** [comment]
can't, not can

**Comment by mah11** [comment]
Fixed. (This was nothing to do with what Kim generates; it's the script I run to convert v2.1 to v2.2.)
