### ISSUE TITLE
pipe separated IDs in 'with' field

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#818]
I thought this was allowed? I can delete one ID, but I wanted to check if something changed? Or if I should use a different seperator (I'm sure I have used a pipe in this field historically, maybe not?)

with value "UniProtKB:P39986|UniProtKB:Q9HD20" should be in the form "DB:ACCESSION": failed to load qualifier 'aspect=F; term=transmembrane protein dislocase activity; GOid=GO:0140567; evidence=ISO; db_xref=GO_REF:0000024; with=UniProtKB:P39986|UniProtKB:Q9HD20; date=20210305' from SPACUNK4.07c.1:

with value "UniProtKB:P39986|UniProtKB:Q9HD20" should be in the form "DB:ACCESSION": failed to load qualifier 'aspect=P; term=extraction of mislocalized protein from ER membrane; GOid=GO:0140569; evidence=ISS; db_xref=GO_REF:0000024; with=UniProtKB:P39986|UniProtKB:Q9HD20; date=20210305' from SPACUNK4.07c.1:

**Comment by kimrutherford** [comment]
They need to be comma separated.

**Comment by kimrutherford** [comment]
I can't see any warnings like this in the logs now.  Can we close this issue?

**Comment by ValWood** [comment]
yup!
