### ISSUE TITLE
 next grant: community data/ colleague information

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#82]
We need to do something about this at some point, opening an item so I can get this off my to do list:

Steve: Ways of tracking users who move lab, people with the same name etc, perhaps a user ID?
Steve: Capturing users "topics" of interest \(can be used to get the community to curate papers other than their own during jamborees etc\).
allow community to see their list of Pubs

Original comment by: ValWood

**Comment by ValWood** [comment]
ORCID will manage this
