### ISSUE TITLE
same allele different names

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#821]
spotted this morning, check appears in logs?

<img width="617" alt="Screen Shot 2021-03-23 at 07 50 24" src="https://user-images.githubusercontent.com/7359272/112179083-44f22b00-8bf2-11eb-9739-01be161ef29e.png">

**Comment by mah11** [comment]
This is reported in the chado_checks log. Does it really need its own ticket?

**Comment by ValWood** [comment]
I couldn't find it in the logs, so I thought it was getting through for some reason. Just wanted to check.
I still can't find it.

**Comment by ValWood** [comment]
but assuming willl get fixed.

**Comment by mah11** [comment]
ctrl-f for 'tws' leads to

`  SPBC11B10.09	cdc2-N22	0fdb9d39a84d84ec	E42K	tws1-N22	011e491e`

but I'll fix it now

**Comment by ValWood** [comment]
OMG I was looking in the wrong file, there are 100s!

alleles with the same description that have different names - CHECK FAILURE:  expected 0 but got 626
