### ISSUE TITLE
S. cerevisiae ortholog IDs to fix

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#823]
These SGD IDs aren't loading for SPAC869.07c in chromosome1.contig:

FT                   /controlled_curation="term=orthologous to S. cerevisiae                                                                                                                  
FT                   SGD:S000029663 and SGD:S000029664 and SGD:S000029665 and                                                                                                                 
FT                   SGD:S000029662; date=19700101"

**Comment by ValWood** [comment]
I think SGD have solved this problem for us.
From the recent newsletter:
https://wiki.yeastgenome.org/index.php/SGD_Newsletter,_Fall_2021#New_systematic_nomenclature_for_yeast_genes_not_in_the_reference_genome

"This new systematic nomenclature is similar to, but distinct from, that used for ORFs and that used for ncRNAs. Non-reference genes are designated by a symbol consisting of three uppercase letters and a four-digit number, as follows: Y for "Yeast", SC for "Saccharomyces cerevisiae", and a four-digit number corresponding to the sequential order in which the gene was added to SGD. We currently have 55 of these genes in SGD, some of which are old favorites like MAL21/YSC0004 and MATA/YSC0046, while others are more recent additions like XDH1/YSC0051"

- [ ] a) As  a first step I will update the names we use from the SGD:ID to the new systematic nomenclature. This might be enough.
- [ ] b) If A is not sufficient to fix https://curation.pombase.org/dumps/latest_build/logs/identifier_problems.txt
@kimrutherford will need to check that the additional names are imported

**Comment by ValWood** [comment]
I added the systematic IDs, so this part needs checking.

**Comment by ValWood** [comment]
still in logs, so presumably a file from SGD needs updating:
mRNA SPAC869.07c.1: can't find feature for: YSC0021
mRNA SPAC869.07c.1: can't find feature for: YSC0024
mRNA SPAC869.07c.1: can't find feature for: YSC0025
mRNA SPAC869.07c.1: can't find feature for: YSC0019

**Comment by kimrutherford** [comment]
I've updated the SGD data file but not in time for the load.  The new one contains those four IDs.  I'll check the logs on Wednesday morning.

**Comment by ValWood** [comment]
https://curation.pombase.org/dumps/latest_build/logs/ortholog_problems.txt
mRNA SPAC869.07c.1: ortholog (YSC0021) not found
mRNA SPAC869.07c.1: ortholog (YSC0024) not found
mRNA SPAC869.07c.1: ortholog (YSC0025) not found
mRNA SPAC869.07c.1: ortholog (YSC0019) not found

**Comment by ValWood** [comment]
https://curation.pombase.org/releases/pombase-2019-03-01/logs/ortholog_problems.txt

now has:
mRNA SPAC869.07c.1: ortholog (SGD:S000029663) not found
mRNA SPAC869.07c.1: ortholog (SGD:S000029664) not found
mRNA SPAC869.07c.1: ortholog (SGD:S000029665) not found
mRNA SPAC869.07c.1: ortholog (SGD:S000029662) not found

**Comment by kimrutherford** [comment]
The problem was that those genes have a different feature type in the SGD data.  They aren't ORFs like the other genes.  I've fixed the load script to include them for Saturday night's load and I'll check on Sunday.

**Comment by kimrutherford** [comment]
This is fixed now but there are new warnings: #913

**Comment by ValWood** [comment]
reopening because the linked ticket does not seem to correspond to this issue

https://curation.pombase.org/dumps/latest_build/logs/identifier_problems.txt
mRNA SPAC869.07c.1: can't find feature for: YSC0021
mRNA SPAC869.07c.1: can't find feature for: YSC0024
mRNA SPAC869.07c.1: can't find feature for: YSC0025
mRNA SPAC869.07c.1: can't find feature for: YSC0019

**Comment by kimrutherford** [comment]
> https://curation.pombase.org/dumps/latest_build/logs/identifier_problems.txt

Sorry!  That was another old log file.  I've removed it now. 

Those orthologs are definitely on the page: https://www.pombase.org/gene/SPAC869.07c
