### ISSUE TITLE
Fix missing deletion allele names

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#824]
If the type of an allele is "deletion", then name isn't stored.

Some of the missing names:
```
72c1277f6497035f  poz1∆
72c1277f6497035f  ccq1delta::hphMX6
b2192f51379c99f3  elf1delta P
661292025a8cdee8  gls1delta-S
f33df0b48bb1431a  SPAC17H9.08
4072a96378948dec  Δelp2
```

**Comment by kimrutherford** [comment]
That's fixed in time for the nightly load.  I'll check in the morning.

**Comment by kimrutherford** [comment]
This is fixed now but I'd like to check that the result is what you expect.

Before the fix, all the deletion allele for a gene were considered identical so "mcm2Δ::his3+" was the same as "mcm2Δ".  And the "mcm2Δ::his3+" name was lost.  Now "mcm2Δ::his3+" is considered different to "mcm2Δ" so there is a separate genotype page for each:

http://dev.pombase.kmr.nz/genotype/mcm2delta
http://dev.pombase.kmr.nz/genotype/mcm2delta::his3%2B-deletion

And in the annotation tables the two genotype are shown separately:
<img src="https://user-images.githubusercontent.com/90474/113091775-240c8400-9249-11eb-9089-45ef58c7ae01.png" width="70%"/>

So my question is: is this all OK?

**Comment by ValWood** [comment]
Shouldn't  mcm2Δ::his3+ be a synonym of  mcm2Δ?

(Unless we know/suspect  that the entire gene is not deleted, then mcm2Δ::his3+ would be classeiofied as a disruption)

**Comment by ValWood** [comment]
Are these synonyms or primary names?

**Comment by kimrutherford** [comment]
They are all primary names.

**Comment by kimrutherford** [comment]
```
         allele_name       |     session      
---------------------------+------------------
 his5::ura4                | ffef0a4669e1a0fd
 dmc1-12                   | 903cb37e16a1d237
 pof8∆::kanMX6             | 72c1277f6497035f
 sec61delta::ura4+         | ae590c5c93d4cceb
 ypt1delta::ura4+          | b05aa0892640b958
 rap1∆                     | 72c1277f6497035f
 ccq1delta::hphMX6         | 72c1277f6497035f
 mcm6delta::his3+          | 6998329e8f9ad0bc
 orc1::ura4+               | f284fe43c381666f
 rec10-175::kanMX6         | 35aab4b08bf43fb8
 rec12-169::kanMX6         | 35aab4b08bf43fb8
 rdl1-25                   | 903cb37e16a1d237
 Δelp2                     | 4072a96378948dec
 sfr1-2                    | 903cb37e16a1d237
 ypt3delta::ura4+          | b05aa0892640b958
 bip1delta::ura4+          | 24f64aba648fcdac
 gls1delta-S               | 661292025a8cdee8
 php2delta::ura4+          | 30e4ef054e6bbaf7
 rep1delta::ura4+          | fb7a0a2c9bb5df54
 rrp6∆                     | a93df4140a4b1e4c
 SPAC17H9.08               | f33df0b48bb1431a
 met9::ura4                | ce75498c19ea15fb
 met11::his3               | ce75498c19ea15fb
 pac1delta::ura4+          | 864b5a9a8777fb8f
 Δrpl31                    | 4072a96378948dec
 mam1-A221                 | 5f32676a85e99635
 sws1-23                   | 903cb37e16a1d237
 rec11::kanMX6             | 35aab4b08bf43fb8
 orc4delta::ura4+          | f0bafc3507c42594
 rec8-206::kanMX6          | 35aab4b08bf43fb8
 swi10::ura4+              | 3448b2e04419517c
 elf1delta P               | b2192f51379c99f3
 cap1delta::ura4+          | 3bce65ea848fff57
 mcm2delta::his3+          | 6998329e8f9ad0bc
 pch1::his7                | bccb6092e76df671
 mdm31delta::LEU2          | df21e2714ebca0b4
 cyr1delta::ura4+          | fc07dc88b6ff742e
 rec27-184::kanMX6         | 35aab4b08bf43fb8
 cuf2                      | 2306fd737a53d0b4
 mcm5delta::his3+          | 6998329e8f9ad0bc
 rec25-180::kanMX6         | 35aab4b08bf43fb8
 taz1∆                     | 72c1277f6497035f
 dfp1delta::ura4+          | 982304b134332abd
 mcm7delta::his3+          | 4b4b351e3a8818f3
 rec8-176::3HA-6His-kanMX6 | 35aab4b08bf43fb8
 rad15delta::LEU2          | a13c28b0b31f2f04
 Δrpl2501                  | 4072a96378948dec
 cig1::ura4                | b65b4c7d7b9528f2
 rep2delta::ura4+          | fb7a0a2c9bb5df54
 orc1delta::ura4+          | 583e1c4287dab5f2
 mug20::NatMX6             | 35aab4b08bf43fb8
 mcm4delta::his3+          | 6998329e8f9ad0bc
 qtrtd1                    | 466ed4e946c15c3f
 sfr1-11                   | 903cb37e16a1d237
 cdc13delta::ura4+         | a64fc9a5b004423d
 pof8∆                     | 72c1277f6497035f
 mcm3delta::his3+          | 9dca83e6946db798
 his1::ura4                | ffef0a4669e1a0fd
 rlp1-7                    | 903cb37e16a1d237
 dis2delta::ura4+          | 77e60bd014f07c05
 poz1∆                     | 72c1277f6497035f
 sws1-18                   | 903cb37e16a1d237
```

**Comment by kimrutherford** [comment]
I'm going to fix the names that end in "∆" when they are loaded to match have "delta" instead for consistency.  I think they're occurring in Chado because the curator has pasted in something like "rap1∆" in Canto so that's what gets written to Chado.  That's a reasonable thing for the curator to do.  I'll change the loading code.

**Comment by kimrutherford** [comment]
> I didn't realize that they get in anyway. I've been fixing them manually!

The checks are done after loading.  Thanks for the manual fixes.  Hopefully changing the loader will reduce the work load a little bit.

I've changed the code to replace the delta symbol with "delta" if the next character in the name isn't a letter.  That's because there are some (like "Δrpl2501") that need curator decision.  Although we could easily change "Δrpl2501" to "rpl2501delta" automatically if you like and it that's something that happens regularly.

**Comment by kimrutherford** [comment]
> I've changed the code to replace the delta symbol with "delta" if the next character in the name isn't a letter

I've checked and that's working fine.

I think everything else mentioned here is curation related so I made a separate issue: pombase/curation#2984
