### ISSUE TITLE
target of, self

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#827]
I thought we didn't display target of relations to the same protein, but I see on one isu1 page?

**Comment by kimrutherford** [comment]
It seems like a bug because in detailed display mode it shows "D37A (aa)" as the genotype.  Very strange!

**Comment by ValWood** [comment]
oh yes with mouse over it is cia1. I wonder if that is an allele synonym or something. I'll have a look at the session first....


![Uploading Screenshot 2021-04-30 at 09.13.37.png…]()

**Comment by ValWood** [comment]
I fixed the allele name to isu1-D37A. It was just D37A.

**Comment by ValWood** [comment]
and all the ones in the cia1 session PMID:18334479

Do we have a handle on how many alleles we have left without a gene name?
I wonder if we can automate the fixing of these (at least the ones with standard descriptions?)

**Comment by kimrutherford** [comment]
I did a quick query that ignores gene name synonyms and found 2000-ish allele names that don't start with the gene name: [odd_allele_names.tsv.txt](https://github.com/pombase/pombase-chado/files/6404734/odd_allele_names.tsv.txt)

**Comment by ValWood** [comment]
some start with allele synonyms or other mutant names, which is fine.

We only need to fix those which have only an amino acid description.
