### ISSUE TITLE
PMID:33771877, some terms and extensions not displayed

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#828]
A few of the terms, and most of the extension that we used in this session
https://www.pombase.org/reference/PMID:33771877

are not on the website
https://www.pombase.org/reference/PMID:33771877

**Comment by ValWood** [comment]
OK, it is where we used the new  "assayed region" extension, so presumably some configuration is missing somewhere.....

**Comment by kimrutherford** [comment]
Yep "assayed_region() not allowed for fission_yeast_phenotype".  Shall I add it?

From https://curation.pombase.org/dumps/builds/pombase-build-2021-05-02/logs/log.2021-05-02-21-44-17.curation-tool-data-load-output :

```
warning in d21245ab5467d47b: assayed_region() not allowed for fission_yeast_phenotype, annotation: d21245ab5467d47b-genotype-2 <-> protein displaced from 3' end to 5' end of RNA polymerase II-transcribed genes during mitotic metaphase
warning in d21245ab5467d47b: assayed_region() not allowed for fission_yeast_phenotype, annotation: d21245ab5467d47b-genotype-2 <-> protein displaced from 3' end to 5' end of RNA polymerase II-transcribed genes during mitotic metaphase
warning in d21245ab5467d47b: assayed_region() not allowed for fission_yeast_phenotype, annotation: d21245ab5467d47b-genotype-2 <-> protein displaced from 3' end to 5' end of RNA polymerase II-transcribed genes during mitotic metaphase
warning in d21245ab5467d47b: assayed_region() not allowed for fission_yeast_phenotype, annotation: d21245ab5467d47b-genotype-2 <-> protein displaced from 3' end to 5' end of RNA polymerase II-transcribed genes during mitotic metaphase
warning in d21245ab5467d47b: storing feature_cvterm from PomBase-genotype-2350 to increased protein localization to chromatin at 3' end of RNA polymerase III-transcribed genes during mitotic metaphase [assayed_using] SPCC306.03c - failed to store feature_cvterm: that annotation has already been stored in Chado with properties:  evidence: "Chromatin immunoprecipitation experiment"  from session: d21245ab5467d47b
warning in d21245ab5467d47b: assayed_region() not allowed for fission_yeast_phenotype, annotation: d21245ab5467d47b-genotype-3 <-> normal protein distribution along RNA polymerase II-transcribed genes during mitotic metaphase
warning in d21245ab5467d47b: assayed_region() not allowed for fission_yeast_phenotype, annotation: d21245ab5467d47b-genotype-2 <-> abnormal protein distribution along RNA polymerase II-transcribed genes
warning in d21245ab5467d47b: assayed_region() not allowed for fission_yeast_phenotype, annotation: d21245ab5467d47b-genotype-2 <-> abnormal protein distribution along RNA polymerase II-transcribed genes
warning in d21245ab5467d47b: assayed_region() not allowed for fission_yeast_phenotype, annotation: d21245ab5467d47b-genotype-2 <-> abnormal protein distribution along RNA polymerase II-transcribed genes
warning in d21245ab5467d47b: assayed_region() not allowed for fission_yeast_phenotype, annotation: d21245ab5467d47b-genotype-2 <-> abnormal protein distribution along RNA polymerase II-transcribed genes
```

**Comment by kimrutherford** [comment]
> Yep "assayed_region() not allowed for fission_yeast_phenotype". Shall I add it?

I went ahead and committed the config change.

**Comment by ValWood** [comment]
great, thanks.

**Comment by kimrutherford** [comment]
The load had a glitch so I restarted.  It's still running.  I'll check this when it's done.

**Comment by kimrutherford** [comment]
Changing the configuration didn't fix things.  The error has changed though.  I'll investigate tomorrow.

```
warning in d21245ab5467d47b: can't find relation cvterm for: assayed_region in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
warning in d21245ab5467d47b: can't find relation cvterm for: assayed_region in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
warning in d21245ab5467d47b: can't find relation cvterm for: assayed_region in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
warning in d21245ab5467d47b: can't find relation cvterm for: assayed_region in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
warning in d21245ab5467d47b: storing feature_cvterm from PomBase-genotype-2350 to increased protein localization to chromatin at 3' end of RNA polymerase III-transcribed genes during mitotic metaphase [assayed_using] SPCC306.03c - failed to store feature_cvterm: that annotation has already been stored in Chado with properties:  evidence: "Chromatin immunoprecipitation experiment"  from session: d21245ab5467d47b
warning in d21245ab5467d47b: can't find relation cvterm for: assayed_region in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
warning in d21245ab5467d47b: can't find relation cvterm for: assayed_region in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
warning in d21245ab5467d47b: can't find relation cvterm for: assayed_region in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
warning in d21245ab5467d47b: can't find relation cvterm for: assayed_region in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
warning in d21245ab5467d47b: can't find relation cvterm for: assayed_region in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype
```

**Comment by kimrutherford** [comment]
I can't see assayed_region in the extension configuration.  Where does it come from?

**Comment by mah11** [comment]
The config just uses "assayed region" as display text for some `assayed_using` entries. Val, did you add some assayed_region by admin text edit?

**Comment by ValWood** [comment]
Hmm, I did, but in that case, how will Canto know the difference when gene product has an assayed region and an assayed protein. They will both be assayed_using?


tfs1 | tfs1DN(aaD274A, E275A)[Overexpression] | FYPO:0007736 | protein displaced from 3' end to 5' end of RNA polymerase II-transcribed genes during mitotic metaphase | 
assayed_using cut3 , assayed_region exg1 | 
assayed_using cut3 , assayed_region ecm33 | 
assayed_using cut3 , assayed_region gas1 | 
assayed_using cut3 , assayed_region eng1

**Comment by mah11** [comment]
> how will Canto know the difference when gene product has an assayed region and an assayed protein?

From the domain and range specifications in the config

**Comment by ValWood** [comment]
but this gene has both protein (cut3), and region (exg1)? both would be assayed_using?

**Comment by mah11** [comment]
> both would be assayed_using?

which is the relation, not the domain or range

**Comment by ValWood** [comment]
but I cant do this simultaneously:
assayed protein cut3 , assayed gene or region exg1 |

they are mutually exclusive...once I use one, the other option isn't available.

**Comment by mah11** [comment]
Hmm. Kim will have to confirm, but I think that may be because Canto is mushing together three ID types that are distinct in the config - GeneID, TranscriptID, ProteinID. If so, adding an assayed_region relation should be an effective workaround.

**Comment by kimrutherford** [comment]
> Hmm. Kim will have to confirm, but I think that may be because Canto is mushing together three ID types that are distinct in the config - GeneID, TranscriptID, ProteinID.

Yep, they are just aliases for each other.  They are treated identically.

**Comment by ValWood** [comment]
What do I need to do hare @mah11 ?

**Comment by mah11** [comment]
close if & when the changes in #65 work

**Comment by kimrutherford** [comment]
I think this is done now.  https://www.pombase.org/reference/PMID:33771877 looks OK.

**Comment by ValWood** [comment]
this looks good
https://www.pombase.org/reference/PMID:33771877

I wonder if in these cases the label should be "assayed protein" to be explicit?
Also, can we make any severity or penetrance  qualifier come at the end after the other extensions? It seems odd for it to be in the middle of the qualifiers.

**Comment by mah11** [comment]
If you have any actual requests for configuration changes, open new tickets on the config tracker.

> I wonder if in these cases the label should be "assayed protein" to be explicit?

What are "these cases"? Do you mean the display in Canto or on the web pages? (Include the answers in the config ticket.)
