### ISSUE TITLE
logs - PHAF ploidy column

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#829]
This may be expected (see https://github.com/pombase/curation/issues/2991#issuecomment-826770943) but I'm reporting it for completeness, posterity, etc.:

For every line in a PHAF that has an entry in the "ploidy" column, the logs report too many columns - even though I added the column to all the PHAFs. The "ploidy" header and the empty column in most of the PHAFs don't generate errors.

These two files are affected:
ltp_phafs/PMID_16169489_phaf.tsv
htp_phafs/PMID_29259000_phaf.tsv

This is the error:
`too many columns at line 2 starting with: homozygous diploid`

**Comment by kimrutherford** [comment]
The "too many columns" error is fixed, but there's a typo in htp_phafs/PMID_29259000_phaf.tsv:

https://curation.pombase.org/dumps/builds/pombase-build-2021-05-11/logs/log.2021-05-11-21-53-02.phenotypes_from_PMID_29259000_phaf

**Comment by mah11** [comment]
Thanks! I fixed the typo.

**Comment by mah11** [comment]
Well, turns out I replaced the old typo with a new typo. But now I've fixed that too.

**Comment by kimrutherford** [comment]
The error is gone from the log file.
