### ISSUE TITLE
protein binding phenotype extensions

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#831]
There's a check in the chado_checks log to make sure protein binding phenotype annotations respect cardinality, i.e. specify both proteins assayed:

`check that protein binding annotations have two assayed_using extensions`

Now that we've deployed the new, more specific extension relations (per [this ticket](https://github.com/pombase/pombase-config/issues/65)), though, newly created annotations will have 0 assayed_using extensions and should have two assayed_protein extensions, i.e. the configuration is now:

     FYPO:0000702	is_a	assayed_protein	ProteinID	affected proteins (add TWO, i.e. both binding partners)		2	user

(In the log.2021-05-13-21-52-13.chado_checks file, there's a report for an annotation that had one of each because one was added before and the other after the new relations went live. Fun times. Both are now assayed_protein.)

Can the check be updated to accommodate the shiny new extensions (but also still allow the heaps of existing annotations that have assayed_using)?

Thanks!

**Comment by kimrutherford** [comment]
I've updated the Chado checking to include assayed_protein.  I ran that check locally and it passed.  I hope that's what you expect.

I also noticed that the Chado checks were broken because of the changes I made two days ago.  I've fixed that for tonight's load.

**Comment by kimrutherford** [comment]
Looks like everything is working.
