### ISSUE TITLE
GO load filtering

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#833]
Could we get  a copy of (or a link to) the code that is used for PomBase  GO filtering for the GO consortium?

**Comment by kimrutherford** [comment]
> Could we get a copy of (or a link to) the code that is used for PomBase GO filtering for the GO consortium?

It's here: https://github.com/pombase/pombase-chado/blob/master/lib/PomBase/Chado/GOFilter.pm

I'm not sure it's going to be helpful to anyone as it's very Chado and somewhat pombe specific.  Would a description of the algorithm be more useful?

**Comment by ValWood** [comment]
Yes the algorithm description would be much better. I think you actually provided this once before for Chris many moons ago when GO were thinking about filtering.

**Comment by kimrutherford** [comment]
> Yes the algorithm description would be much better.

Sorry for the slow reply.  Here's the overview of the algorith:

---------------------------------------------------

We have a priority list of evidence codes:

    inferred from biological aspect of descendant
    inferred from biological aspect of ancestor
    inferred from reviewed computational analysis
    inferred from electronic annotation
    inferred from expression pattern
    non-traceable author statement
    traceable author statement
    inferred from sequence model
    inferred from sequence or structural similarity
    inferred from sequence orthology
    inferred by curator

Annotations with evidence codes at the bottom are kept in preference to those nearer the top of the list.

 - we iterate through the evidence codes above in order then:

   - for each annotation with that evidence code, delete the annotation if there is another annotation for the same gene with:

     - a more specific term
     - or same term but a different evidence code

   - if there are duplicate annotations (same term and gene) with that evidence code, delete all but one

**Comment by ValWood** [comment]
Also the list is configurable and we intend to make the PAINT codes (IBA and IBD?)
primary codes once we are happy that the QC is completed.

And now I can't remember who asked for this. Tagging @cmungall 

I guess we can close the ticket though.

**Comment by cmungall** [comment]
Thanks, v useful.

Wow, you rank IEP over IBA. But this of course reflects pombase curation standards and presumably more conservative use of IEP than seen elsewhere

Yes, you can close the ticket, thanks

**Comment by ValWood** [comment]
Well it isn't that we particularly trust IEP over IBA.  The only reason that I'm still reviewing PAINT annotations We implement this order at the moment is so that  we don't see any IBA which are covered by *any* other annotation. The ones we did not make ourselves already  are the only ones we need to check.  It is much easier for me to review the  3281 remaining  PAINT annotations rather than the total 15944. I thought we would have switched by now to give IBA the 'best status', but I'm still reporting quite a lot of errors:

57 open 493 closed
https://github.com/geneontology/go-annotation/issues?q=is%3Aopen+is%3Aissue+label%3A%22PAINT+annotation%22+author%3AValWood

But yes IEP is a crap evidence code, and we are phasing out its use completely, we only use it 18 times...

**Comment by ValWood** [comment]
correction:
 I thought we would have switched by now to give IBA the 'best non-experimental status (but above IEP)'
