### ISSUE TITLE
annotation number drop

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#834]
Annotation number is currently ~275,000 it is usually >283,000

any clues why?

v

**Comment by kimrutherford** [comment]
When did you see >283,000?

I've checked the Chado DBs going back a couple of months and the number of stored annotations is quite stable, just creeping up slowly.  I checked the GAF, PHAF and interaction export files for the last few months and they're creeping up slowly too.

I also loaded up a version of Chado and Canto on my desktop from 2021-03-01 and there were 274491 annotations.

**Comment by ValWood** [comment]
Maybe I made a misttake. I was sure it was over 280 at one point...

I also think it dropped and rose again.

No worries...

**Comment by ValWood** [comment]
That is really freaking bizzare, just now it is
Last updated 2021-05-19: 282946 annotations from 4072 curated

**Comment by ValWood** [comment]
Ok, that's why I am seeing different numbers.  One is the graph and one is the front page.

So it is OK I think the front page also includes taxonomic distribution, which accounts for  the difference.

**Comment by ValWood** [comment]
I  had an idea of the total in my head, but I forgot  I was looking in 2 different places....
