### ISSUE TITLE
in the logs, misreported ID

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#836]
https://curation.pombase.org/dumps/latest_build/logs/identifier_problems.txt

CDS SPAC750.08c.1 from gene: SPAC750.08c: can't find feature for: FAM155A
CDS SPAC750.08c.1 from gene: SPAC750.08c: can't find feature for: FAM155B
CDS SPAC750.08c.1 from gene: SPAC750.08c: can't find feature for: SGD:S000029663
CDS SPAC750.08c.1 from gene: SPAC750.08c: can't find feature for: SGD:S000029664
CDS SPAC750.08c.1 from gene: SPAC750.08c: can't find feature for: SGD:S000029665
CDS SPAC750.08c.1 from gene: SPAC750.08c: can't find feature for: SGD:S000029662

the first 2 aren't SPAC750.08c, they are SPAC1F5.08c ?

**Comment by kimrutherford** [comment]
I think I've fixed this, but not in time for tonight's load.  It should be OK from Saturday morning onwards.

**Comment by kimrutherford** [comment]
This is still buggy.  I'll look at it again.

**Comment by kimrutherford** [comment]
> This is still buggy. I'll look at it again.

Fixed again.  I'll check after Friday night's load.

**Comment by kimrutherford** [comment]
There are still log messages but they make sense now: https://curation.pombase.org/dumps/latest_build/logs/identifier_problems.txt
