### ISSUE TITLE
export all alleles

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#840]
Export a file with all curated alleles. I guess the usual tab-delimited text .. suggested columns:

gene systematic ID, gene name, allele systematic ID, allele name, allele type, allele description

... have I missed anything?

Inspired by the author curation tools under development for microPublications (they'd want to load this file); could have other uses as well somewhere along the line. Let me know if it's worth pinging anyone in microPublication-dom about what they need, or if you have any other questions.

**Comment by mah11** [comment]
I've just been chatting with Daniela & Karen about micropub stuff, and they asked about this again. Will you be able to get to it soonish, now that the JaponicusDB dust is starting to settle?

**Comment by kimrutherford** [comment]
I'm implementing that now.  Could you suggest a name for the file?

**Comment by kimrutherford** [comment]
> allele systematic ID

We have those internally in Chado (like "SPAC24H6.09:allele-2"), but they aren't very useful because they aren't stable.  They can change what they refer to from load to load.

**Comment by kimrutherford** [comment]
Here's a first pass at this:
 http://curation.pombase.org/kmr44/tmp/allele_table.tsv

**Comment by mah11** [comment]
> Could you suggest a name for the file?

Erm, I guess `all_alleles.tsv` ... not very exciting, but also hard to misinterpret.

>> allele systematic ID
> 
> We have those internally in Chado (like "SPAC24H6.09:allele-2"), but they aren't very useful because they aren't stable. They can change what they refer to from load to load.

Ah, OK, I think I just (re-?)learned that. Now I'm not sure if it's still worth including ... it would be nice to have something unique for each entry, and I know we haven't finished slogging through the same-description-different-names allele log report. But "unstable" IDs are risky and potentially confusing.

If you leave out the internal IDs, would you make entries for all unique names or just unique descriptions? I'm kind of leaning towards unique descriptions - on the grounds that we'll get through that log someday - but not in a defend-it-vigorously kind of way.

> Here's a first pass

That looks great. The only thing I see (apart from the ID question above) is that it should have column headers. If the ID column doesn't get the ax, it could have a scary header like "current internal ID" or something to that effect.

**Comment by kimrutherford** [comment]
> Erm, I guess all_alleles.tsv ... not very exciting, but also hard to misinterpret.

OK, I've gone with that.

> The only thing I see (apart from the ID question above) is that it should have column headers.

I've added a header.

I'll have a think about the unique identifier problem.

**Comment by ValWood** [comment]
I'll put this at "low priority" until Micropubs follow up about  it  with me. It hasn't been mentioned yet, and may be resolved by the InterMine ticket.

**Comment by kimrutherford** [comment]
> I'll have a think about the unique identifier problem.

I've made a separate issue for that: pombase/pombase-chado#986
