### ISSUE TITLE
change exists_during to RO_0002490 existence overlaps (GAF & GPAD)

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#841]
1.
GO plans to deprecate the `exists_during` relation for annotation extensions (see https://github.com/geneontology/go-annotation/issues/2677). We'll change ours to "existence overlaps" (RO:0002490).

The easiest way to do it is to carry on using exists_during internally, and make adjustments to our GAF and GPAD when we prepare them for submission to GO. I'm already munging some other extension relations so we can keep displaying more specific things than `has_input` anyway.

- [ ] GAF: change all to `exists_during` to `existence_overlaps` (@mah11)
- [ ] GPAD: change all `GOREL:0000032` to `RO:0002490` (@kimrutherford)

I don't know what happens if we plug in `existence_overlaps` (with the underscore) in the GAF we submit to GO, so I guess we'll find out when we first send them a file with it. GPAD uses the RO ID anyway.

-----
2.
It would be a bit more complicated to switch over to "existence overlaps" further upstream, but I'll put some notes here in case we want to at some point. We'd have to work on Chado, Canto, the contig files, and various bits of the website -- and make sure it all stays in sync.

For Chado loading ...

This gem is the OBO stanza for the relation:

	[Typedef]
	id: RO:0002490
	name: existence overlaps
	def: "x existence overlaps y if and only if either (a) the start of x is part of y or (b) the end of x is part of y. Formally: x existence starts and ends during y iff (α(x) >= α(y) & α(x) <= ω(y)) OR (ω(x) <= ω(y) & ω(x) >= α(y))" []
	comment: The relations here were created based on work originally by Fabian Neuhaus and David Osumi-Sutherland. The work has not yet been vetted and errors in definitions may have occurred during transcription.
	property_value: IAO:0000117 "Chris Mungall" xsd:string
	is_a: RO:0002487 ! relation between physical entity and a process or stage

Awkward bit 1: This relation isn't in gorel.obo (and I've totally forgotten what, if anything, we do with RO).

Awkward bit 2: Note that it doesn't have a text "ID" like the relations in gorel.obo (and, as noted above, seeing what happens if I put one in the GAF anyway is part of the adventure).

For Canto, the relation would have to get loaded somehow, and we'd have to update the extension configuration files.

For the website, update
- extension display configs
- documentation

Update GO annotations in the Artemis contig files (5-minute job).

-----

**Comment by kimrutherford** [comment]
> GPAD: change all GOREL:0000032 to'RO:0002490 (@kimrutherford)

Shall I go ahead and do that?
We just need a config change at this line: https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L6453

**Comment by mah11** [comment]
> > GPAD: change all GOREL:0000032 to RO:0002490 (@kimrutherford)
> 
> Shall I go ahead and do that?

Might as well, since the GPAD just sits there waiting for its turn in the spotlight.

I can also see what happens if I put `existence_overlaps` in the version of the GAF I munge into v2.0 for GO.

**Comment by kimrutherford** [comment]
> GPAD: change all GOREL:0000032 to RO:0002490

That's done now.

**Comment by kimrutherford** [comment]
Let me know if there's anything else I need to do here.

**Comment by mah11** [comment]
I think this one's OK -- GPAD is sorted, my munging script takes care of GAFs-for-GOC for now, and the remaining bits of future-proofing GAF generation will go in a new ticket, as discussed in today's meeting. (I don't think we want to bother with option 2 from the original summary; life's too short.)
