### ISSUE TITLE
disease logs reporting - show the "consider" field for obsolete terms

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#849]

**Comment by ValWood** [comment]
At present we have "replaced by"IDs reported. in the logs.

Could we also display the "consider" tags(some of these are quite difficult to track down, especially because we are sometimes  trying to fix ahead of  monarch and  OLS, and they aren't aways easy to locate in the  MONDO tracker.

cheers
v

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/3108
we currently see
 MONDO:0018297 is obsolete (replaced by: MONDO:0014176) - skipping annotation for SPAC6F6.01 / hypotonia_speech_impairment_severe_cognitive_delay_syndrome

or
 MONDO:0016606 is obsolete (no "replaced_by" tag) - skipping annotation for SPBC14F5.13c / prenatal_benign_hypophosphatasia

I don't think I have seen the "consider" tag
https://github.com/monarch-initiative/mondo/issues/3265#issuecomment-915435853

**Comment by kimrutherford** [comment]
I've implemented this, but not in time for last night's load.  I'll check it worked on Thursday morning and then close this issue.

**Comment by kimrutherford** [comment]
> I'll check it worked on Thursday morning and then close this issue.

There are no warnings at the moment so I'll leave this open for now.

**Comment by ValWood** [comment]
I can't remember if I have seen this in action. yet.....

**Comment by ValWood** [comment]
I'm a bit worried considering my comments here:
https://github.com/pombase/pombase-chado/issues/853
because I haven't needed to do any disease remapping for ages- it used to be a big time sink. Maybe there have not been very many changes. I just wanted to check that the reporting is still working.

**Comment by kimrutherford** [comment]
> Maybe there have not been very many changes.

I think that might be part of it.  I've just checked the MONDO OBO file and the there have been only 39 "consider:" tags added in the last 6 months.

> I just wanted to check that the reporting is still working.

I haven't changed the relevant code since I added it so I think it's probably OK.

**Comment by ValWood** [comment]
@kimrutherford  do you think I should have seen any of these yet?

**Comment by kimrutherford** [comment]
> do you think I should have seen any of these yet?

Maybe not as there are a lot of terms and not so many consider: fields.

How often do you notice term obsoletions?

**Comment by ValWood** [comment]
There haven't been so many. Possible MONDO don't use consider, and the GO ones I usually fix pre obsoletion.

We can close this for now, I will reopen if I see one with a tag that is not reported
