### ISSUE TITLE
Automate disease inferences

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#853]
We need to  a quicker way of doing this, the flux is too great to manage (it sucks up about a day every time MONDO updates because it is never completely clear where or what the change is.
https://github.com/pombase/curation/issues/3108

when we used   lots of sources to curate diseases,and there was no mapping between the DO term and the human disease we had to maintain by hand.

Now we use MONDO  there should be a way to automate this, since Monarch have connections between human genes and MONDO:Ids and we have orthologs.

**Comment by kimrutherford** [comment]
> Now we use MONDO there should be a way to automate this, since Monarch have connections between human genes and MONDO:Ids and we have orthologs.

Would these inferences be in addition to the existing annotations or would they replace them?

**Comment by ValWood** [comment]
I envisaged for updates.  This isn't super urgent. It was taking quite a lot of time but it seems to not be at the moment.
I think there is potential to get rid of some of the middle mapping and potentially  weed out incorrect mappings, get missing mappings and supply missing associations to MONDO, but this is more of a mini-project.

It might be a good one for Manu.

**Comment by ValWood** [comment]
Mondo has downloadable association working again
https://github.com/monarch-initiative/monarch-app/issues/327

we can work on this together after  paper, apicuron report,

**Comment by ValWood** [comment]
We can chat about this soon. Using the Monarch disease associations cover most of our existing associations:

<img width="597" alt="disease_differences" src="https://github.com/pombase/pombase-chado/assets/7359272/23aff013-4286-4fe4-919e-c606e4f798c2">

I suspect the difference is the "correlated" but I'm not sure.
Some of the ones I looked at that are in PomBase,  are correlated, but not causal in MONDO/Monarch.

<img width="597" alt="disease_differences" src="https://github.com/pombase/pombase-chado/assets/7359272/b726a61f-ff67-45b6-8cd8-ca8b68f72491">

The MONARCH IDS which have pombe orthologs:
https://www.pombase.org/results/from/id/d3903069-02c0-478e-bd56-c9a394e4979b

I think we should:
a) Take associations primarily from Monarch on a regular basis.
- add the causal qualifier
-  do the same  for correlated
b) figure out which associations are NOT covered by Monarch, and keep them in a separate file. We will still display them, but we will review

**Comment by ValWood** [comment]
oddly cap2 is in the unannotated in Monarch list but it is causal
https://monarchinitiative.org/MONDO:0957545

**Comment by ValWood** [comment]
Some of the 106 come from tandem fusions in fission yeast that I have not properly annotated with human orthologs yet.
eg.
https://www.pombase.org/gene/SPAC1420.04c
https://www.pombase.org/gene/SPAC19B12.13

**Comment by ValWood** [comment]
Some of those missing from  Monarch  are definitely in the "correlated" see, including
alp7 https://www.pombase.org/gene/SPAC890.02c
atg16 https://www.pombase.org/gene/SPBC405.05 https://monarchinitiative.org/MONDO:0012610

**Comment by kimrutherford** [comment]
The plan is to map the human disease associations from this file to pombe via orthologs:
https://data.monarchinitiative.org/monarch-kg/latest/tsv/gene_associations/gene_disease.9606.tsv.gz

Then drop the Malacards associations.

We'll then compare before and after using the exported disease_association.tsv file:
https://curation.pombase.org/dumps/builds/pombase-build-2024-06-18/misc/disease_association.tsv

**Comment by kimrutherford** [comment]
I forgot to ask, what reference should be used for the associations/annotations from Monarch?

**Comment by kimrutherford** [comment]
The code and config is mostly ready to go.  Should I commit the changes for tonight's load or is it better to wait for the weekend?

I've done a test load of the Monarch data locally and got 2351 disease associations in Chado.  We get 2769 associations from MalaCards.

There are also 1546 manual associations in
`pombe-embl/external_data/disease/pombase_disease_associations_mondo_ids.tsv`

**Comment by ValWood** [comment]
What is the gene coverage? 1480?

I will write a pombe reference.

**Comment by ValWood** [comment]
Draft text for a PB reference:
Disease associations are created by taking human gene-disease causal, and correlated associations created by Monarch  <https://monarchinitiative.org/> using the MONDO  disease ontology <https://mondo.monarchinitiative.org/ .
and mapping to fission yeast orthologs <https://www.pombase.org/data/orthologs/> using the manually maintained fission yeast/human ortholog table.




We might add this part later if we need to keep any PomBAse annotations
This is supplemented by manually annotated gene-disease connections at PomBase

**Comment by kimrutherford** [comment]
> Draft text for a PB reference:

Thanks.

Can you suggest a title for the reference?  Like "Disease associations from Monarch via human-pombe orthologs" but better.  :-)

**Comment by ValWood** [comment]
"Disease associations from Monarch via human-pombe orthologs"  sounds fine!

**Comment by kimrutherford** [comment]
> The code and config is mostly ready to go.

It's all done now.  I just need to "git push" when we're ready.

**Comment by ValWood** [comment]
OK this can go live.
The next steps are:
1. add a qualifier "causal" for the associations from this file
2. download the other file (non causal) . From this one, for the time being, we should only include  those with the qualifier "contributes_to" but  not those with the qualifier "gene_assocated_with_condition (I am trying to find out what this means but nobody has answered yet)
3. Let me have the list from our "old set" which are no longer covered (it should be small if any)

**Comment by ValWood** [comment]
Re Let me know if you want those lists.

I'll have the lists after step2, they should be smaller

**Comment by kimrutherford** [comment]
Oddly, the file from Monarch includes some associations for obsolete terms:
```
MONDO:0012233 is obsolete (consider: MONDO:0018875) - skipping annotation for SPCC18B5.11c
MONDO:0020734 is obsolete (no "replaced_by" or "consider" tag) - skipping annotation for SPBC106.04
MONDO:0012357 is obsolete (no "replaced_by" or "consider" tag) - skipping annotation for SPCC1672.07
MONDO:0007798 is obsolete (consider: MONDO:0600011) - skipping annotation for SPBC14F5.13c
MONDO:0020619 is obsolete (no "replaced_by" or "consider" tag) - skipping annotation for SPCC737.09c
MONDO:0033571 is obsolete (no "replaced_by" or "consider" tag) - skipping annotation for SPAC1556.08c
MONDO:0020610 is obsolete (no "replaced_by" or "consider" tag) - skipping annotation for SPBC543.05c
MONDO:0044222 is obsolete (no "replaced_by" or "consider" tag) - skipping annotation for SPAC2F3.01
MONDO:0014709 is obsolete (consider: MONDO:0100263) - skipping annotation for SPAC17A5.01
MONDO:0020625 is obsolete (no "replaced_by" or "consider" tag) - skipping annotation for SPBC543.05c
MONDO:0009427 is obsolete (consider: MONDO:0600011) - skipping annotation for SPBC14F5.13c
MONDO:0009428 is obsolete (consider: MONDO:0600011) - skipping annotation for SPBC14F5.13c
MONDO:0044256 is obsolete (no "replaced_by" or "consider" tag) - skipping annotation for SPAC2F3.08
MONDO:0020624 is obsolete (no "replaced_by" or "consider" tag) - skipping annotation for SPBC543.05c
MONDO:0044280 is obsolete (no "replaced_by" or "consider" tag) - skipping annotation for SPAC977.17
MONDO:0024544 is obsolete (consider: MONDO:0100259) - skipping annotation for SPCC553.03
```

**Comment by kimrutherford** [comment]
> download the other file (non causal) 

Download then load into Chado?

**Comment by kimrutherford** [comment]
No problem.  I was just checking that you wanted it loaded.

All the changes are checked in to load the causal associations and the contributes_to associations, with qualifiers attached.

As an example, the htr11 / SPBC1685.05 disease table should look like this tomorrow:

![image](https://github.com/pombase/pombase-chado/assets/90474/ed827bab-f7a8-41e0-810f-91f53da94820)

**Comment by kimrutherford** [comment]
> 1536 (vs 1470 currently)

After load the contributes_to associations, it's 1551.

**Comment by ValWood** [comment]
Nice increase 1463 -> 1536.
I'll announce this change tomorrow

If you  could let me have the old associations that are not covered by he new, that would be great.

I'm not surprised there are obsolete terms in Monarch. There seems to be a time lag between Mondo releases and monarch updates. I guess they will resolve eventually. These were the things I used to fix manually, but now they should resolve over time. There will probably always be a number which are obsolete at any point.

**Comment by ValWood** [comment]
If there is a PomBAse annotation that is identical to a Monarch annotation but has reference PBREF 0000003
we can drop it....

**Comment by kimrutherford** [comment]
> If you could let me have the old associations that are not covered by he new, that would be great.

No problem.  After the load finishes tonight, I'll compare old and new.

> If there is a PomBAse annotation that is identical to a Monarch annotation but has reference PBREF 0000003
we can drop it....

So remove it from the source data file (`external_data/disease/pombase_disease_associations_mondo_ids.tsv`) or remove it from Chado when loading?

**Comment by ValWood** [comment]
You can remove it from the source, it provides nothing extra.

**Comment by kimrutherford** [comment]
> If there is a PomBAse annotation that is identical to a Monarch annotation but has reference PBREF 0000003
we can drop it.... 

OK, that's done for tomorrow.
I've removed 670 lines from `external_data/disease/pombase_disease_associations_mondo_ids.tsv`

**Comment by kimrutherford** [comment]
> OK, that's done for tomorrow.
> I've removed 670 lines from external_data/disease/pombase_disease_associations_mondo_ids.tsv

I forgot to commit the change.  I've done that now so I'll check again on Friday morning.

The other changes are on the main site:

https://www.pombase.org/gene/SPBC1685.05

![image](https://github.com/pombase/pombase-chado/assets/90474/ed827bab-f7a8-41e0-810f-91f53da94820)

**Comment by kimrutherford** [comment]
> If you could let me have the old associations that are not covered by he new, that would be great.

These are the 1470 genes with MONDO terms from two days ago (uploaded from the old [`disease_association.tsv`](https://github.com/pombase/pombase-chado/issues/853#issuecomment-2175890186)):
https://www.pombase.org/results/from/id/ecc08627-b79a-4aaa-800e-51eff3bb091b

These are the 1564 genes annotated now (uploaded from the current `disease_association.tsv`):
https://www.pombase.org/results/from/id/4b21373a-5642-4ff5-bbb6-1724411229dc
(As a double-check, the same list using an ontology query: https://www.pombase.org/results/from/id/aafa9e7f-1563-43d7-a4b1-25819c2917c6)

Genes that did have an annotation, but don't now (32):
https://www.pombase.org/results/from/id/1e6c9274-e462-4bbc-8623-df0d8943ff3e

Genes that didn't have an annotation two days ago, but do now (126):
 https://www.pombase.org/results/from/id/38b48b56-de18-4356-a8e2-5558b4ceab67

I've switched the dev site back to the database from two days ago in case you'd like to check anything about the old annotations.  Here are the 32 genes with no annotation now:
http://dev.pombase.kmr.nz/results/from/id/0465da64-b950-4fa0-b9be-ce249a67cf58

And here are the MalaCards annotations as a table for the 32 genes that don't have annotation now:

|gene           |name     |term           |
|---------------|---------|---------------|
|https://www.pombase.org/gene/SPAC1071.07c  |rps1502  |https://www.pombase.org/term/MONDO:0004948  |
|https://www.pombase.org/gene/SPAC11H11.01  |sst6     |https://www.pombase.org/term/MONDO:0004989  |
|https://www.pombase.org/gene/SPAC16.05c    |sfp1     |https://www.pombase.org/term/MONDO:0006745  |
|https://www.pombase.org/gene/SPAC22G7.10   |iss1     |https://www.pombase.org/term/MONDO:0012883  |
|https://www.pombase.org/gene/SPAC22G7.10   |iss1     |https://www.pombase.org/term/MONDO:0015687  |
|https://www.pombase.org/gene/SPAC22G7.10   |iss1     |https://www.pombase.org/term/MONDO:0017833  |
|https://www.pombase.org/gene/SPAC23G3.05c  |         |https://www.pombase.org/term/MONDO:0000992  |
|https://www.pombase.org/gene/SPAC23H3.08c  |bub3     |https://www.pombase.org/term/MONDO:0000141  |
|https://www.pombase.org/gene/SPAC31A2.14   |bun107   |https://www.pombase.org/term/MONDO:0018417  |
|https://www.pombase.org/gene/SPAC3G9.08    |png1     |https://www.pombase.org/term/MONDO:0010150  |
|https://www.pombase.org/gene/SPAC607.04    |arg82    |https://www.pombase.org/term/MONDO:0018698  |
|https://www.pombase.org/gene/SPAC688.10    |rev3     |https://www.pombase.org/term/MONDO:0008006  |
|https://www.pombase.org/gene/SPAC750.08c   |         |https://www.pombase.org/term/MONDO:0005579  |
|https://www.pombase.org/gene/SPAC750.08c   |         |https://www.pombase.org/term/MONDO:0012402  |
|https://www.pombase.org/gene/SPAC890.02c   |alp7     |https://www.pombase.org/term/MONDO:0016682  |
|https://www.pombase.org/gene/SPAC890.02c   |alp7     |https://www.pombase.org/term/MONDO:0016681  |
|https://www.pombase.org/gene/SPAC9E9.08    |rad26    |https://www.pombase.org/term/MONDO:0019342  |
|https://www.pombase.org/gene/SPAP8A3.06    |uaf2     |https://www.pombase.org/term/MONDO:0018881  |
|https://www.pombase.org/gene/SPAPB18E9.02c |ppk18    |https://www.pombase.org/term/MONDO:0008555  |
|https://www.pombase.org/gene/SPBC119.08    |pmk1     |https://www.pombase.org/term/MONDO:0005392  |
|https://www.pombase.org/gene/SPBC1709.11c  |png2     |https://www.pombase.org/term/MONDO:0010150  |
|https://www.pombase.org/gene/SPBC19F5.02c  |utp4     |https://www.pombase.org/term/MONDO:0011497  |
|https://www.pombase.org/gene/SPBC20F10.03  |         |https://www.pombase.org/term/MONDO:0011834  |
|https://www.pombase.org/gene/SPBC25H2.07   |tif11    |https://www.pombase.org/term/MONDO:0015447  |
|https://www.pombase.org/gene/SPBC337.08c   |ubi4     |https://www.pombase.org/term/MONDO:0016064  |
|https://www.pombase.org/gene/SPBC3H7.13    |csc1     |https://www.pombase.org/term/MONDO:0015263  |
|https://www.pombase.org/gene/SPBC582.05c   |brc1     |https://www.pombase.org/term/MONDO:0100087  |
|https://www.pombase.org/gene/SPCC11E10.03  |jnm1     |https://www.pombase.org/term/MONDO:0015626  |
|https://www.pombase.org/gene/SPCC1235.15   |dga1     |https://www.pombase.org/term/MONDO:0044625  |
|https://www.pombase.org/gene/SPCC1393.03   |rps1501  |https://www.pombase.org/term/MONDO:0004948  |
|https://www.pombase.org/gene/SPCC1450.07c  |dao1     |https://www.pombase.org/term/MONDO:0005090  |
|https://www.pombase.org/gene/SPCC4G3.02    |aph1     |https://www.pombase.org/term/MONDO:0005086  |
|https://www.pombase.org/gene/SPCC576.09    |rps20    |https://www.pombase.org/term/MONDO:0018604  |
|https://www.pombase.org/gene/SPCC584.04    |sup35    |https://www.pombase.org/term/MONDO:0005027  |
|https://www.pombase.org/gene/SPCC794.12c   |mae2     |https://www.pombase.org/term/MONDO:0005579  |
|https://www.pombase.org/gene/SPCC794.12c   |mae2     |https://www.pombase.org/term/MONDO:0012402  |
|https://www.pombase.org/gene/SPCC962.02c   |bir1     |https://www.pombase.org/term/MONDO:0007650  |

**Comment by ValWood** [comment]
Fantasic! So fast!

and also not many to check which is good. Will save me lots of time going forward.

**Comment by ValWood** [comment]
I checked the missing ones at OMIM, and although some have tentative assignments, they are inconclusive.

**Comment by kimrutherford** [comment]
Hi Val.

I meant to ask this yesterday.

There are a 101 genes annotated with "disease susceptibility" (MONDO:0042489):
https://www.pombase.org/results/from/id/567f5173-4849-45c7-bf3f-ed141a990908

Of those, 13 genes don't appear in the "All disease associated genes" (MONDO:0000001) commonly used query: 
https://www.pombase.org/results/from/id/a0c8f835-3984-4b57-9c5e-8cef6aa1f5aa

Just to check: is that what we want?

**Comment by ValWood** [comment]
There are a 101 genes annotated with "disease susceptibility" (MONDO:0042489):
https://www.pombase.org/results/from/id/567f5173-4849-45c7-bf3f-ed141a990908

We want to include these

**Comment by kimrutherford** [comment]
OK, I've changed the query in the config and have set off a re-release of the website.
