### ISSUE TITLE
include missing external GO annotation based on  assigned_by filters 

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#854]
Include missing external GO annotation (mainly iEA)

~change the PomBase/JaponicusDB assigned by filters so. that we actively filter resources rather than default remove the one we do not elect to keep.
So when new assigned_by  arrives like  Rhea (and nobody announces it), we include rather than exclude~

**Comment by ValWood** [comment]
we can discuss which on the next call. I'm curious about some of them

**Comment by ValWood** [comment]
sorted. we will check annually for changes in "assigned_by"

We just let in RHEA, intact, RNACentral and Complex_Portal, but I am expecting most will be redundant.

**Comment by kimrutherford** [comment]
> We just let in RHEA, intact, RNACentral and Complex_Portal, but I am expecting most will be redundant.

I forgot to commit the changes in time for Thursday night's load.  I've done that now so the extra annotations will be visible from Saturday.

**Comment by ValWood** [comment]
99 GOC
3162 GO_Central
1781 InterPro
38469 PomBase
1471 UniProt

so I think nothing came through yet?

Note to self, ingest included:
RHEA 1426
Intact 944
RNACentral 570
Complex Portal 74
(I am expecting most to be filtered as redundant)

**Comment by kimrutherford** [comment]
Hi Val.  The load failed on Friday night.

The process that automatically adds reciprocal IPI protein binding annotations failed when processing the new data from IntAct.  The code didn't like the "with" field not being a PomBase ID.  They're UniProtKB IDs, which makes sense.

I changed the code to only add reciprocal IPI annotations if the source of the annotation is PomBase.  We can fix that if the IntAct annotations are useful.

So last night's load worked OK.

**Comment by ValWood** [comment]
13 CAFA
  61 ComplexPortal
  99 GOC
3149 GO_Central
 944 IntAct
1772 InterPro
38447 PomBase
 204 RHEA
1461 UniProt

So quite a few, even Intact oddly because I thought they would be largely IPI.

**Comment by ValWood** [comment]
Looks good. We need to fix this link to the  db_xref and DB prefix:
I forget how we do both of these things.

<img width="963" alt="Screenshot 2022-01-09 at 09 35 58" src="https://user-images.githubusercontent.com/7359272/148677059-35810d3e-e2ed-4071-97c7-483ed981ebe3.png">

<img width="1221" alt="Screenshot 2022-01-09 at 09 37 34" src="https://user-images.githubusercontent.com/7359272/148677078-ecdffeca-f629-4616-8d76-9ba6f3e9ef6f.png">

The prefix is RHEA
and should link to 
https://www.rhea-db.org/rhea/16237

and the db-xref should link to
https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000116.md
from the ID here https://www.pombase.org/reference/GO_REF:0000116

It's important for us to do this because we don't display the 'assigned_by' field, we need to make sure the link outs and references work for attribution.

**Comment by kimrutherford** [comment]
> We need to fix this link to the db_xref and DB prefix:

Could you explain this a bit?  Are there two links needed?  That screenshot isn't from PomBase.  What page should the links appear on?

**Comment by ValWood** [comment]
II see we don't link our to these anyway, we probably should:
https://www.pombase.org/reference/GO_REF:0000024


It might also be useful to display the description of the 
reference:

i.e for RHEA Rhea (https://www.rhea-db.org/, PMID:30272209) is an expert-curated knowledgebase of chemical and transport reactions of biological interest - and the standard for enzyme and transporter annotation in UniProtKB (PMID:31688925). Rhea uses the chemical dictionary ChEBI (Chemical Entities of Biological Interest) to describe reaction participants and their chemical transformations in a computationally tractable manner. GO terms corresponding to Rhea reactions are assigned a Rhea database cross-reference. The corresponding GO term is automatically applied to all UniProt entries annotated with a Rhea reaction.

**Comment by ValWood** [comment]
We can discuss this, not super urgent.

**Comment by kimrutherford** [comment]
The RHEA IDs in the with fields are now links to RHEA, using the configuration from [GO db-xrefs](http://current.geneontology.org/metadata/db-xrefs.yaml).

**Comment by kimrutherford** [comment]
> and the db-xref should link to

I've made a separate issue about that: pombase/pombase-chado#916

Is there anything else to do on this issue?
