### ISSUE TITLE
error message instead of log file for  the same allele name/description  for different genes

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#855]
https://curation.pombase.org/dumps/latest_build/logs/log.2021-09-26-21-52-06.allele-comments
gives
DBIx::Class::Storage::DBI::select_single(): Query returned more than one row.  SQL that returns multiple rows is DEPRECATED for ->find and ->single at /local-homes/pbuild/git/pombase-chado/lib/PomBase/Role/FeatureFinder.pm line 134

and
https://curation.pombase.org/dumps/latest_build/logs/log.2021-09-26-21-52-06.allele-synonyms
gives
DBIx::Class::Storage::DBI::select_single(): Query returned more than one row.  SQL that returns multiple rows is DEPRECATED for ->find and ->single at /local-homes/pbuild/git/pombase-chado/lib/PomBase/Role/FeatureFinder.pm line 134

(or is that intended behaviour?)

**Comment by mah11** [comment]
I don't know what's making that message appear, but I do know that 
- it first appeared in the logs for the 2021-07-28 build; and
- since it started appearing, it hasn't prevented actual problems from being reported (e.g. [this log](https://curation.pombase.org/dumps/builds/pombase-build-2021-07-31/logs/log.2021-07-31-21-53-56.allele-synonyms))

**Comment by ValWood** [comment]
I fixed this one. Are there a lot like this?
Will they be in there own log file?

**Comment by kimrutherford** [comment]
> I fixed this one. Are there a lot like this?

That was the only problem with the allele synonym and comment loading.

> Will they be in there own log file?

I don't understand.  They already have their own log files that end in ".allele-comments" and ".allele-synonyms"

**Comment by ValWood** [comment]
I was thinking that it would replace

alleles with the same description that have different names - CHECK FAILURE:  expected 0 but got 626
  SPCC338.08	ctp1-delta-N60	48be31dcce9039d3	1-60	ctp1-N60	699def6a055fb333
  SPCC338.08	ctp1-160	[null]	61-294	ctp1-1-60	[null]
  SPCC338.08	ctp1-1-60	[null]	61-294	ctp1-160	[null]
  SPAC644.04	pct1-41-303	[null]	1-40	pct1-Ndelta40	ce3349acca59ef69
  SPAC644.04	pct1-51-303	[null]	1-50	pct1-Ndelta50	ce3349acca59ef69
  SPAC23C11.16	plo1-DHK625AAA	[null]	DHK625AAA	plo-1-DHK625AAA	b74f9d9ca791af8a
  SPBC1A4.03c	top2delta(26-40)	[null]	27-41	top2delta(26-40)-delta-Sph	[null]
  SPBC1A4.03c	top2delta(42-74)	[null]	43-75	top2delta(42-74)-delta-Sph	[null]
  SPBC1A4.03c	top2delta(1-53)	6f1818d4183cd160	1-54	top2delta(1-53)-delta-Sph	[null]
  SPBC1A4.03c	top2delta(26-40)-delta-Sph	[null]	27-41	top2delta(26-40)	[null]

in 
https://curation.pombase.org/dumps/releases/pombase-2021-09-01/logs/log.2021-09-01-22-03-34.chado_checks

I got mixed up!

**Comment by ValWood** [comment]
these are in logs so closing...
