### ISSUE TITLE
separate log files

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#857]
Can we have separate files for

alleles with the same description that have different names - CHECK FAILURE:  expected 0 but got 600

and

PRO IDs used for more than one gene - CHECK FAILURE:  expected 0 but got 4
  PR:000028992	4d5512a5dc8ea4bc	SPBC19C2.09.1
  PR:000028992	4d5512a5dc8ea4bc	SPBC6B1.08c.1
  PR:000044737	7c2513328f82d364	SPBC28F2.12.1
  PR:000044737	7c2513328f82d364	SPCC757.07c.1

They get a bit buried in 
https://curation.pombase.org/dumps/latest_build/logs/log.2021-09-26-21-52-06.chado_checks
(especially the PRO IDS which come right at the end)

**Comment by ValWood** [comment]
..and also for
alleles with the same description that have different names - CHECK FAILURE:  expected 0 but got 600
  SPCC338.08	ctp1-delta-N60	48be31dcce9039d3	1-60	ctp1-N60	699def6a055fb333
  SPCC338.08	ctp1-60	[null]	61-294	ctp1-1-60	[null]
  SPCC338.08	ctp1-1-60	[null]	61-294	ctp1-60	[null]
  SPAC644.04	pct1-41-303	[null]	1-40	pct1-Ndelta40	ce3349acca59ef69
  SPAC644.04	pct1-51-303	[null]	1-50	pct1-Ndelta50	ce3349acca59ef69
  SPAC23C11.16	plo1-DHK625AAA	[null]	DHK625AAA	plo-1-DHK625AAA	b74f9d9ca791af8a
currently in 
https://curation.pombase.org/dumps/latest_build/logs/log.2021-09-27-21-52-56.chado_checks


(we might need some additional reporting later to make these easier to track down)

**Comment by kimrutherford** [comment]
Separate files will take a bit of work because it's all from of one step of the load process.

As a quick fix, would it help to move the results of the interesting checks to the top of the output?  We can do that by changing the order of checks in the configuration file.

**Comment by kimrutherford** [comment]
I've gone ahead and moved the checks that have lots of output to the end of the log file.  I didn't do that in time for the load.  The change will be visible from Saturday morning.

**Comment by kimrutherford** [comment]
I've changed things so that the logs from each of the checks goes into a separate file.  The changes weren't committed in time for tonight's load so I'll check that it's OK on Friday morning.

**Comment by kimrutherford** [comment]
That's done now: https://curation.pombase.org/dumps/latest_build/logs/

**Comment by ValWood** [comment]
I like this ;)

**Comment by kimrutherford** [comment]
> I like this ;)

Yeah, I should have done that ages ago.  Oh well, done now.
