### ISSUE TITLE
UniProt entries with no systematic ID

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#858]
https://curation.pombase.org/dumps/latest_build/logs/log.2021-09-26-21-52-06.gaf-load-output

**Comment by kimrutherford** [comment]
I can't see any major changes in that part of the load script recently.  It has looked like that for a while.  Here's the same file from Jan 1st:
https://curation.pombase.org/dumps/builds/pombase-build-2021-01-01/logs/log.2021-01-01-21-16-54.gaf-load-output

And from 2018:
https://curation.pombase.org/dumps/releases/2018/pombase-2018-08-01/logs/log.2018-08-01-20-12-11.gaf-load-output

**Comment by ValWood** [comment]
Right, I  previously thought this was just incremental evidence codes, but maybe it didn't contain errors when I looked before.
I'll work through them. SOme were fixed yesterday.

**Comment by ValWood** [comment]
I'm. a bit perplexed by these errors in this file

feature not found, no synonym matches a feature (cox3 A0A516IJZ4 cox3)
feature not found, no synonym matches a feature (cox3 A0A516IJZ4 cox3)
feature not found, no synonym matches a feature (cox3 A0A516IJZ4 cox3)
feature not found, no synonym matches a feature (cox3 A0A516IJZ4 cox3)
feature not found, no synonym matches a feature (cox3 A0A516IJZ4 cox3)
feature not found, no synonym matches a feature (cox3 A0A516IJZ4 cox3)
feature not found, no synonym matches a feature (spt6 S6BSK0 spt6)
feature not found, no synonym matches a feature (spt6 S6BSK0 spt6)
feature not found, no synonym matches a feature (spt6 S6BSK0 spt6)
feature not found, no synonym matches a feature (spt6 S6BSK0 spt6)

anyone know what generates these?

**Comment by kimrutherford** [comment]
Sorry for the confusing messages.  These warnings are from the GOA GAF loading and occur when there isn't a pombe systematic ID for an annotation.

I'll change the message to say something like "none of the identifiers from this annotation match a systematic ID in Chado"

**Comment by ValWood** [comment]
So does this mean  all data from uniprot?
(I don't think it would add much, but we could import if we swapped the uniprot acc for the pombase systematic ID - or is it a different problem?)

**Comment by kimrutherford** [comment]
The GAF loader doesn't use the pombe-UniProt mapping.  It just uses the pombe systematic IDs (if any).  There's probably a good reason for that but I can't think of one at the moment.  I'll have another look (and think) tomorrow.

**Comment by ValWood** [comment]
I don't think we should change this.  I see what you mean, we use the fission yeast systematic ID for integrations- I think we should continue to do so.

Clearly we load most of the Uniprot annotations:
1852 UniProt
The ones we don't load must be because they are a) fully redundant or b)  do not have the official systematic ID in the GOA file (as above).
If you can extract this list tomorrow we can send it to GOA @Antonialock @alexsign  to see what the problem is. This needs fixing at UniProt.

**Comment by ValWood** [comment]
Actually these Spt6 entries are unreviewed
https://www.uniprot.org/uniprot/S6BSK0
https://www.uniprot.org/uniprot/S6BMF4
so it is still in Trembl. I'm not sure why that is exported and it only has automated annotation  that duplicated the reviewed Spt6

This is the only useful spt6 entry:
https://www.uniprot.org/uniprot/Q09915
@alexsign is there a way to prevent these redundant entries being exported to GOA?

**Comment by ValWood** [comment]
@Antonialock  it seems the mitochondrial entries do not have systematic IDs.
Could these be added?
[mito gene_list (87).csv](https://github.com/pombase/pombase-chado/files/7245746/mito.gene_list.87.csv)

**Comment by ValWood** [comment]
Since the log file link changes daily- here is the  complete list of entries not loaded:
[UniProt_not _loaded.txt](https://github.com/pombase/pombase-chado/files/7245794/UniProt_not._loaded.txt)

**Comment by Antonialock** [comment]
2 things with the trembl entries:

A. some seem to have the wrong taxon code:
eg cox1-I2b A0A516ILU5  SCHPM

B. I can also see Tf1-107

Ignore things like this? I thought pombe only had tf2 type transposons? And it is not in pombase? How did it make the list?

Also some wtf genes will have sys IDs next release eg 

O74512 | wtf14
Q96WS1 | wtf11

**Comment by Antonialock** [comment]
> 
> 
> @Antonialock it seems the mitochondrial Uniprot entries do not have systematic IDs. Could these be added? [mito gene_list (87).csv](https://github.com/pombase/pombase-chado/files/7245746/mito.gene_list.87.csv)


I'm not following, all of these appear to have stable uniprot identifiers mapped to pombe systematic IDs

I spot checked the below ones, searching for the pombase sys ID retrieves the correct uniprot entries.


SPMIT.05 | P05501
SPMIT.01 | P07657
SPMIT.11 | P21534
SPMIT.04 | P14575
SPMIT.07 | P21535

**Comment by ValWood** [comment]
>I'm not following, all of these appear to have stable uniprot identifiers mapped to pombe systematic IDs

Maybe it is because, in addition  to the entries with systematic IDs, there are Trembl entries without systematic IDs for these genes that are getting into the GOA file?

**Comment by ValWood** [comment]
>B. I can also see Tf1-107
which entry is this?

**Comment by Antonialock** [comment]
that was in the second list for alex
feature not found, no synonym matches a feature (retrotransposon Tf1-107 Q01910 retrotransposon Tf1-107)\

**Comment by Antonialock** [comment]
are all these SCHPM not SCHPO?

**Comment by Antonialock** [comment]
> cox1-I2b A0A516ILU5 SCHPM

this is actually a different strain, MT50, submitted by lilin

**Comment by ValWood** [comment]
> this is actually a different strain, MT50, submitted by lilin

That makes sense he sequenced some mitochondrial genomes. Can  strain labels be added? that would help people. And systematic IDs.

**Comment by kimrutherford** [comment]
I'm not sure what the next step is here.

**Comment by ValWood** [comment]
https://curation.pombase.org/dumps/latest_build/logs/log.2021-12-07-22-23-18.gaf-load-output

These errors could go in their own log file. 
reading /var/pomcur/sources/gene_association.goa_uniprot.gz
gene feature not found, none of the identifiers  (cox2-I1 A0A516ILW4 cox2-I1) from this annotation match a systematic ID in Chado
gene feature not found, none of the identifiers  (cw17 A0A1X9Q9G2 cw17) from this annotation match a systematic ID in Chado
gene feature not found, none of the identifiers  (cw17 A0A1X9Q9G2 cw17) from this annotation match a systematic ID in Chado
gene feature not found, none of the identifiers  (wtf31 A0A482AR08 wtf31) from this annotation match a systematic ID in Chado

Other than that, we don't need to do anything. This is a UniProt issue.

Or, we could just choose to ignore any UniProt entry without a systematic identifier. Let's make it simple!

**Comment by ValWood** [comment]
Ignoring will be fine, since the likelihood we will lose useful GO annotation is infinitesimally small

**Comment by ValWood** [comment]
OK,   I think we can close this.
