### ISSUE TITLE
Dealing with GO duplicate annotation in the log files

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#860]
https://curation.pombase.org/dumps/latest_build/logs/log.2021-09-27-21-52-56.chado_checks

All duplicate GO annotation.  Columns are: count, systematic ID, gene name, term name, evidence, PubMed ID, 'with', session ID - CHECK FAILURE:  expected 0 but got 76

Now we have established that the UniProt data does get in, I suspect this is what is causing the majority of the duplicates.

For instance  this one:

 2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPAC17G6.17	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPAC29E6.01	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPAC57A10.05c	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPAC6F6.02c	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPBC1271.01c	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPBC1703.06	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPBC25B2.11	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPBC29A3.08	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPBC336.01	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPBC3H7.06c	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPBC56F2.01	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPCC18.04	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15147268	PomBase:SPCC338.16	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15555586	PomBase:SPBC776.18c	
  2	SPBC409.05.1	skp1	protein binding	Inferred from Physical Interaction	PMID:15555586	PomBase:SPBP16F5.02	
  2	SPBC646.05c.1	erg9	protein binding	Inferred from Physical Interaction	PMID:17016471	PomBase:SPAC13D6.01	

all of the existing annotation seems to be in Artemis (Paper not yet curated in Canto)
AND  I remember that Skp1 has a lot of duplicate annotation from UniProt

/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPAC17G6.17; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPAC29E6.01; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPAC57A10.05c; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPAC6F6.02c; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPBC1271.01c; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPBC1703.06; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPBC25B2.11; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPBC29A3.08; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPBC336.01; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPBC3H7.06c; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPBC56F2.01; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPCC18.04; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15147268; with=PomBase:SPCC338.16; date=20080122"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15555586; with=PomBase:SPBC776.18c; date=20050119"
/GO="aspect=F; term=protein binding; GOid=GO:0005515; evidence=IPI; db_xref=PMID:15555586; with=PomBase:SPBP16F5.02; date=20050119"

Clearly we don't want exact duplicate annotation from the same paper, and this should not happen any more because UniProt don't really curate fission yeast entries. But, in these cases can we filter the redundant entry if the annotation provider is UniProt  (we don't need to report these)? 
This way we would know if the exact duplicates are due to something internal (like a term merge)

**Comment by mah11** [comment]
I reviewed these a while back, with occasional updates (most recently over a year ago, but the UniProt duplicates hardly ever change) ... see attached.

In the past I've fixed a few genuine duplicates on our end. I don't think I ever seen any that could be attributed to term merges; the most common thing seemed to be not deleting an annotation from contig files after redoing it in Canto.

[duplicate_GO_to_filter_2020-06-26.txt](https://github.com/pombase/pombase-chado/files/7250399/duplicate_GO_to_filter_2020-06-26.txt)

**Comment by ValWood** [comment]
- [ ] Action, don't report duplicate Uniprot annotations int he log file

**Comment by kimrutherford** [comment]
Shouldn't these duplicate be removed by the GO filtering step?  Should I be investigating a bug in that code?

**Comment by ValWood** [comment]
The code is working  as currently expected.

We  keep all UniPRot experimental annotation, AND we filter exact duplicates (other than date), this  annotation will stay because the "assigned by" field is different.

 This is really a GO issue. Different resources shouldn't need to make a GO annotation that already exists, duplicate annotations of the same experiment, same paper/experiment redundancy is not useful.

 GO should already have mechanisms in the pipeline to deal with this type of duplication since it will be an inherent feature of Noctua annotation. 

It might be useful to put the UniProt and Intact EXP duplicates in a separate log. `There is nothing we can do to fix those, but it is good to have a record so that we can keep an eye on the extent of the issue. For instance, if Intact starts to do lots of pombe annotation this would generate lots of redundant IPI data.

**Comment by kimrutherford** [comment]
> We keep all UniPRot experimental annotation, AND we filter exact duplicates (other than date), this annotation will stay because the "assigned by" field is different.

Should the GO filtering handle that by having a priority system for assigned by too?  So that if two annotations are the same except for assigned by, we just keep one?  That seems better than having two identical annotations in Chado.

**Comment by ValWood** [comment]
Yes that is probably what should happen. We don't need to ever load the duplicates.
However, it would be good to see a list in a separate log just to keep handle on it. We are the database authority, and we should know how much of other resources annotations we are removing (and discourage them from making such duplicate annotations). Would it be possible to put the filtered annotation of this type into a log file?

**Comment by kimrutherford** [comment]
> Would it be possible to put the filtered annotation of this type into a log file?

Yep.  The duplicate removal process can do that.

**Comment by kimrutherford** [comment]
I've written the code to report and delete the annotations from UniProt that are a duplicates of PomBase annotations.  Here's my first attempt at a log file:
https://curation.pombase.org/kmr44/tmp/uniprot_annotations_to_delete.tsv

I realise there are a few too many columns, but do the rows like sensible?

**Comment by ValWood** [comment]
yes, that's all I need actually...

**Comment by kimrutherford** [comment]
I've added the duplicate deletion process for tonight's load.

**Comment by kimrutherford** [comment]
Can we close this?

**Comment by ValWood** [comment]
I think so, we have the file of UniProt duplicates that are filtered, and the ones which need fixing remain in the logs. Much better.
