### ISSUE TITLE
automagically fix allele names where the name is a standard gene description with no gene name prefix

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#868]
There are a LOT of these. We are fixing them by hand, but they  usually only come to our notice  (or at least appear in the logs) once someone names the allele correctly.

when they appear in the logs
 SPAC19B12.05c	R223K	15ee54d35bd94b18	R223K	fcp1-452	8c6ccb0ae9834279

However the issue is far more pervasive because one alert often reveals a full session with no prefixes
<img width="685" alt="Screenshot 2021-11-01 at 10 31 06" src="https://user-images.githubusercontent.com/7359272/139658751-e83d6245-ded4-4c4d-9190-bad18105aaf0.png">

It would save a lot of time 
if allele_name == standard description and  allele type  ≠ 'other'
insert gene_name- (the hyphen is critical) in front of the allele description.

**Comment by kimrutherford** [comment]
> if allele_name == standard description and allele type ≠ 'other'

Should we ignore allele with type "disruption" as well?

> insert gene_name- (the hyphen is critical) in front of the allele description.

Do you want to do that only for the descriptions that look like "R194L" or "K428A,K429A"?  That are some that don't like like that:

```
       uniquename       |              name               |            type             |              session              
------------------------+---------------------------------+-----------------------------+-----------------------------------
 SPBC11B10.09:allele-29 | cdc2-T14A                       | amino_acid_mutation         | 9a3197e7865f3d22,9a3197e7865f3d22
 SPAC1F5.04c:allele-4   | 1451-1538                       | partial_amino_acid_deletion | b42a7324f08b6a24
 SPBC19C7.03:allele-3   | 174-188                         | partial_amino_acid_deletion | f85ced2727868dc3
 SPBC19C7.03:allele-4   | 181-195                         | partial_amino_acid_deletion | f85ced2727868dc3
 SPBC19C7.03:allele-5   | 163-176                         | partial_amino_acid_deletion | f85ced2727868dc3
 SPBC146.13c:allele-3   | myo1-S361D                      | amino_acid_mutation         | 897ea00b9e24c756
 SPCC5E4.03c:allele-8   | 579-600                         | partial_amino_acid_deletion | 24e1cb4e93273c16
 SPBC31E1.02c:allele-4  | pmr1-R155->stop                 | nonsense_mutation           | 0572af570458b258
 SPAC19D5.03:allele-6   | N165                            | amino_acid_mutation         | 173b353377d08cd6
 SPAC29A4.16:allele-5   | 181-230                         | partial_amino_acid_deletion | 09a2ea749be9cd03
 SPAC2E12.02:allele-3   | 476-609                         | partial_amino_acid_deletion | ede6ebd38992d401
 SPAC2E12.02:allele-4   | 267-410                         | partial_amino_acid_deletion | ede6ebd38992d401
 SPAC2E12.02:allele-5   | 505-609                         | partial_amino_acid_deletion | ede6ebd38992d401
 SPAC2E12.02:allele-6   | 411-504                         | partial_amino_acid_deletion | ede6ebd38992d401
 SPCC70.12c:allele-3    | Q14->stop                       | nonsense_mutation           | 118ddd6c56f3dd56
 SPBC409.08:allele-2    | 3 bp deletion in 5'-UTR         | partial_nucleotide_deletion | b792e3d40839cdbd
 SPBC725.06c:allele-2   | 1 bp insertion in 5'-UTR (uORF) | nucleotide_insertion        | b792e3d40839cdbd
 SPAC23E2.01:allele-9   | 5-261                           | partial_amino_acid_deletion | 72b789a688713879
 SPAC23E2.01:allele-11  | 5-59                            | partial_amino_acid_deletion | 72b789a688713879
 SPAC23E2.01:allele-12  | 5-129                           | partial_amino_acid_deletion | 72b789a688713879
 SPBC1718.07c:allele-16 | zfs1 S141AS145A,S154A,S155A     | amino_acid_mutation         | efc5a5e85ec7f642
```

**Comment by ValWood** [comment]
Not sure why
 SPBC11B10.09:allele-29 | cdc2-T14A 
is in the list.

Insert name for any like this:
1451-1538                       | partial_amino_acid_deletion
or 
 N165                            | amino_acid_mutation   
or
Q14->stop                       | nonsense_mutation 

Some are not following standard syntax for the allele tyope and should be ignored for now but  reported in the logs(the prefix can be fixed whilts fixing the. other issues):
 SPBC409.08:allele-2 | 3 bp deletion in 5'-UTR         | partial_nucleotide_deletion | b792e3d40839cdbd
 SPBC725.06c:allele-2   | 1 bp insertion in 5'-UTR (uORF) | nucleotide_insertion       

Any like this:
 SPBC1718.07c:allele-16 | zfs1 S141AS145A,S154A,S155A 
need the hyphen inserted

**Comment by ValWood** [comment]
edited the comment above

**Comment by kimrutherford** [comment]
> Any like this:
> SPBC1718.07c:allele-16 | zfs1 S141AS145A,S154A,S155A
> need the hyphen inserted

Does the description need fixing on that one to remove the "zfs1"?

**Comment by ValWood** [comment]
>SPBC1718.07c:allele-16 | zfs1 S141AS145A,S154A,S155A

I think this is the allele name, not the description.
So this one is missing a hyphen.

In face I will fix this now. There is a comma missing too, plus I think thas allele has a short name zfs1-4A

**Comment by ValWood** [comment]
there were quite a few allele inconsistencies in the zfs1 session- now fixed.

You were right also the zfs1 was in the description too, in addition to missing the hyphen in the label.

**Comment by kimrutherford** [comment]
Thanks.

I've added a step in the load to do this allele name fixing.  About 570 will be automatically fixed.

There will be a new log file on Saturday ending with `.fix-allele-names`.  It's a log of the cases where the allele and description are the same but the allele name can't be fixed automatically.

It will look a bit look this:
```
 gene_name          | allele_name+desc   | session
 cdc2               | cdc2-T14A          | 9a3197e7865f3d22
 [unnamed]          | 3 bp deletion in 5…| b792e3d40839cdbd
 ppk31              | 1 bp insertion in …| b792e3d40839cdbd
 myo1               | myo1-S361D         | 897ea00b9e24c756
 pmr1               | pmr1-R155->stop    | 0572af570458b258
```

I'll close this issue once I've checked the load results.
