### ISSUE TITLE
PombeMine - use ECO ID instead of term name

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#869]
export json file for PombeMine with ECO ID instead or term name

**Comment by ValWood** [comment]
@rachellyne
@danielabutano

**Comment by kimrutherford** [comment]
> export json file for PombeMine with ECO ID instead or term name

Is this for GO or FYPO or both?

**Comment by mah11** [comment]
I think it came up in the context of FYPO, but perhaps best for @danielabutano to say whether it's useful for both

**Comment by kimrutherford** [comment]
> export json file for PombeMine with ECO ID instead or term name

Is there a mapping from the phenotype evidence codes to ECO?

**Comment by rachellyne** [comment]
This is for FYPO as we just have the evidence name/description in the file.  We have codes for GO.

**Comment by mah11** [comment]
> Is there a mapping from the phenotype evidence codes to ECO?

It's a subset of the entries in pombe-embl/chado_load_mappings/ECO_evidence_mapping.txt

**Comment by kimrutherford** [comment]
> It's a subset of the entries in pombe-embl/chado_load_mappings/ECO_evidence_mapping.txt

Thanks.  And thanks for making the file.

I'll add a loading step that adds the ECO terms to each annotation in Chado: #878

Once that's done, changing the export file for PombeMine will be straightforward.

**Comment by kimrutherford** [comment]
> export json file for PombeMine with ECO ID instead or term name

The evidence codes aren't in the JSON file.  It contains the gene details like IDs, names, transcripts, locations and sequence.

I believe PombeMine is getting the annotation from the GAF and PHAF files.  I've added an extra step after the Chado loading to export a PHAF file with ECO IDs instead of the usual evidence field.  I'll check the output on Wednesday morning and report back with the URL.

**Comment by kimrutherford** [comment]
> I'll check the output on Wednesday morning and report back with the URL.

That all worked so here's the URL of PHAF file with ECO IDs: https://curation.pombase.org/dumps/latest_build/pombase-latest.eco.phaf.gz

It's updated nightly.
