### ISSUE TITLE
Where does the "binds SPAC1F7.05.2" come from for spd1 / SPAC29B12.03?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#870]
https://www.pombase.org/gene/SPAC29B12.03

It's just "with cdc22" in the session:
  https://curation.pombase.org/pombe/curs/dfd6ea81df55ce19/ro/

**Comment by kimrutherford** [comment]
The "binds SPAC1F7.05.2" was generated by the code that automatically makes reciprocal IPI annotations.  It was getting things wrong because SPAC1F7.05/cdc22 has two transcripts.  I've fixed this for Wednesday night's load and I'll check on Thursday morning.

After this fix there will still be some duplicate annotations, but there's a separate issue for that: pombase/website#1789

**Comment by mah11** [comment]
The `chado_checks` log now reports about a zillion (well, 4454) duplicate GO annotations. Is that connected with this? It looks suspicious because the vast majority are 'protein binding' annotations. Or should I put it in a separate ticket?

**Comment by kimrutherford** [comment]
I see what you mean. 

> Is that connected with this? It looks suspicious because the vast majority are 'protein binding' annotations.

Yep, I think it must be caused by my "fix".  I'll fix it better this time.

**Comment by kimrutherford** [comment]
I've committed a fix for my fix.  I'll check in the morning.

As far as I can tell the annotation on the gene pages turned out OK despite all the warnings.

**Comment by kimrutherford** [comment]
> I've committed a fix for my fix. I'll check in the morning.

The log file is looking better so I'll be an optimist and close this issue.
