### ISSUE TITLE
output GAF: genes in extensions need prefix

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#871]
In the "GO style" v2.2 GAF, pombe gene IDs in annotation extensions should get the "PomBase" prefix. That will stop errors like this (from the [snapshot report](http://snapshot.geneontology.org/reports/pombase-report.html) as of today 2021-11-03):

    ERROR - Syntax error in annotation extension field: extensions should be relation(curie) and relation should have corresponding URI (coincident_with(SPAC821.08c)) -- PomBase SPAC23H4.17c srb10 is_active_in GO:0000791 PMID:22451489 IDA C mediator complex, cyclin-dependent protein kinase subunit Srb10 prk1|cdk8 protein taxon:4896 20131101 PomBase coincident_with(SPAC821.08c),existence_overlaps(GO:0000087)

Yep, all that to say "include a prefix". In this example the change is `coincident_with(SPAC821.08c)` --> `coincident_with(PomBase:SPAC821.08c)`

(also, oops, I missed this in the #848 discussion & testing)

**Comment by kimrutherford** [comment]
I've fixed that for tonight's load.  Most of the genes had prefixes.  In a few cases the gene ID came from a promoter (like "SPAC821.08c-promoter") and the prefix was missing.

I'll double check the output in the morning.
