### ISSUE TITLE
intermine export

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#877]
Don't export the legacy  150-200 phenotype annotation in Artemis that have no name
https://github.com/intermine/pombemine/issues/7#issuecomment-969093345

I have prioritised these for proper curation.

**Comment by kimrutherford** [comment]
The are about 600 alleles without a name in Chado and those alleles are parts of genotypes with about 4900 annotations.  Is it OK to not have those annotations in the InterMine file?

**Comment by ValWood** [comment]
Ooh no, that is way more than I thought.

I think sometimes though we might give a description but not a name and the name can be inferred?
Do any have a no name but a description? We can name those easily?

**Comment by kimrutherford** [comment]
All of the alleles with no name have a description of some sort, although sometimes it's just "unrecorded".

**Comment by ValWood** [comment]
Here it  is the name that is causing a problem, not the description -some alleles are unknown description, that isn't an issue - we  just don't know what the description is. All alleles should all have a name though?

**Comment by kimrutherford** [comment]
Here are some examples of alleles without names:
 - https://curation.pombase.org/pombe/curs/dc907bc500c1a07a/genotype_manage/ro
 - https://curation.pombase.org/pombe/curs/88f605195653964e/genotype_manage/ro
 - https://curation.pombase.org/pombe/curs/92cda7cb8c6c7a8c/genotype_manage/ro
 - https://curation.pombase.org/pombe/curs/396866ab84f69995/genotype_manage/ro

**Comment by ValWood** [comment]
I think we decided here that the name would be automatically added in the output where possible.
If this is done how many alleles are left without names?

**Comment by kimrutherford** [comment]
> If this is done how many alleles are left without names?

I just checked and there are 234 unnamed alleles.

**Comment by kimrutherford** [comment]
> how does that relate to this log
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-24-21-31-25.chado_checks.unnamed_unrecorded_alleles

That's alleles that have no name and no description ("unrecorded").  There are fewer of those.

**Comment by ValWood** [comment]
Right so to summarize.

We have:
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-24-21-31-25.chado_checks.unnamed_unrecorded_alleles
140
alleles that have no name and no description ("unrecorded"). 
(Pombemine to ignore these for now, most will be redundant- we will prioritise for cuation)


234 unnamed alleles, but some have descriptions 
is this after the ones which can be names are named? or before? 
Is there a list of those with descriptions that are not currently auto-named? (we can see if we can automagically name  these)

**Comment by kimrutherford** [comment]
> 234 unnamed alleles, but some have descriptions
> is this after the ones which can be names are named? or before?

That's after all the automatic naming is done.

> Is there a list of those with descriptions that are not currently auto-named? (we can see if we can automagically name these)

I've added a new log file ending in ".unnamed_alleles" for the next load.  I'll check it's there on Thursday morning.

Here's what it will look like: [log.file.unnamed_alleles.tsv.txt](https://github.com/pombase/pombase-chado/files/7939727/log.file.unnamed_alleles.tsv.txt)

**Comment by ValWood** [comment]
The current file has 140 unnamed unrecorded alleles from legacy data. Most of these are  viability and elongation phenotypes that Jacky and I added for the cell cycle paper pre Canto. 
Most, if not all will be covered by the  cell cycle paper anyway, so we will not really lose anything by not exporting for Intermine and I have a curation tracker ticket to  prioritise the older papers for curation.

So,  if these are now excluded from the PombeMine export, this ticket can close. this ticket can close
