### ISSUE TITLE
Add a loading step that adds the ECO terms to each annotation in Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#878]
From #869

Add an "eco_evidence_code" property to each `feature_cvterm` row.

**Comment by kimrutherford** [comment]
@mah11 There were some evidence codes that weren't in the mapping file.   They had obvious ECO IDs, so I added them:

PomBase | ECO
-- | -- 
experimental phenotypic evidence  | ECO:0000059
high throughput nucleotide sequencing assay evidence | ECO:0000221
microscopy evidence used in manual assertion | ECO:0001232
sodium dodecyl sulfate polyacrylamide gel electrophoresis evidence | ECO:0000333
western blot evidence used in manual assertion | ECO:0000279
tryptic phosphopeptide mapping assay evidence used in automatic assertion | ECO:0007464

There are also some FYPO annotations with "Other" and "Other direct assay" as evidence codes.  Is that expected?

**Comment by kimrutherford** [comment]
> Add a loading step that adds the ECO terms to each annotation in Chado

That's done now.

**Comment by mah11** [comment]
> There are also some FYPO annotations with "Other" and "Other direct assay" as evidence codes. Is that expected?

Yes, there's an option for "other" in the Canto evidence pulldown for FYPO. I guess it can just map to ECO:0000059.

The other additions look fine. Thanks!

**Comment by kimrutherford** [comment]
> Yes, there's an option for "other" in the Canto evidence pulldown for FYPO. I guess it can just map to ECO:0000059.

Thanks.  I've done that for Wednesday night's load.

Tuesday night's load worked and Chado now has the ECO term IDs loaded.
