### ISSUE TITLE
Fix chado check: 'with' values that have an unsupported DB prefix

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#879]
It can't handle "with" value that have multiple IDs:

```
'with' values that have an unsupported DB prefix - CHECK FAILURE:  expected 0 but got 66
  ECOGENE:EG10986,ECOGENE	[null]	PMID:8921872
  GO:0000262,GO	[null]	GO_REF:0000036
  GO:1990817,GO	[null]	GO_REF:0000036
  PomBase:SPAC16A10.07c,PomBase	[null]	PMID:18160711
  PomBase:SPAC17G8.07,PomBase:SPAC9G1.13c,PomBase	[null]	PMID:19040720
  PomBase:SPAC25B8.03,PomBase	[null]	PMID:19286980
...
```

https://curation.pombase.org/dumps/builds/pombase-build-2021-11-14/logs/log.2021-11-14-22-48-53.chado_checks

**Comment by mah11** [comment]
Ah. I think it should handle comma-separated multiple entries, because we use those when the evidence needs more than one `with` or `from` entry to properly support the annotation (e.g. a three-way interaction or an IC that's "from" a combination of two or more other annotations).

**Comment by kimrutherford** [comment]
Fixed for Monday night's load.
