### ISSUE TITLE
Automatically name alleles in Chado using the description if not named

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#881]
Start with 
amino acid substitution
nucleic acid substitution

At the same time, check syntax for these.

(related to Intermine issue)

**Comment by kimrutherford** [comment]
I've nearly finished implementing this.  Below are the details for the unnamed `nucleotide_mutation` and `amino_acid_mutation` alleles that can't be automatically names.  It warns if the allele description isn't in the form "G107A" or a comma separated list like that.  It also complains if the `nucleotide_mutation` desciption has a letter that isn't A,T,C,G or U.  If any of these are OK, letter me know and I'll change the checking code.

Sorry, only the last 5 have a session ID.  Maybe they're from PHAF files or contig files?

```
nucleotide_mutation  srp7 G72A,G78A,G100A,G107A,Gl12A,G141A    
nucleotide_mutation  srp7 T(-5)C,T(-3)C,U88C    
nucleotide_mutation  srp7 T(-61)C,G(-75)C,U62C,U101C    
nucleotide_mutation  srp7 A163U,C169U6    
amino_acid_mutation  uaf2 del aa 53-113    
amino_acid_mutation  uaf2 E68A,E71A,E74A,ED78AA    
amino_acid_mutation  uaf2 ER31AA    
amino_acid_mutation  uaf2 ED78AA    
amino_acid_mutation  uaf2 EE114AA    
amino_acid_mutation  uaf2 RE145AA    
amino_acid_mutation  uaf2 Q174->stop    
amino_acid_mutation  uaf2 RK177AA    
amino_acid_mutation  uaf2 KK195AA    
amino_acid_mutation  uaf2 C157S,C163,C167I    
amino_acid_mutation  sap1 1-21    
amino_acid_mutation  sap1 1-21,151-254    
amino_acid_mutation  sap1 204-254    
amino_acid_mutation  sap1 241-254    
amino_acid_mutation  sap1 144-254    
amino_acid_mutation  sap1 151-254    
amino_acid_mutation  sap1 158-254    
amino_acid_mutation  sap1 1-21,144-254    
amino_acid_mutation  sap1 137-254    
amino_acid_mutation  prp2 deletion    
amino_acid_mutation  cnd2 k639R   396866ab84f69995 
nucleotide_mutation  mei2 -G1512T   5943de801ceb71fa 
nucleotide_mutation  mei2 -G1512T,-G1692T   5943de801ceb71fa 
amino_acid_mutation  cut1 1-1452   3926aad5386b9286 
amino_acid_mutation  hhp2 W214stop   4d3b0d5a0015df91 
```

**Comment by ValWood** [comment]
We  will standardize these since there are so few. I think we deliberated with  RK177AA  in some situations but. it seems to have fallen out of favour.

@mah11  could you take the PHAF files and I'll do the Canto sessions.
I thought that uaf2 might be in Artemis, but it isn't

**Comment by ValWood** [comment]
Actually, we should allow AA111BB
because there will be more of these.  I forgot that these are only the ones with no name. It is quite useful for big block amino acid replacements.

**Comment by kimrutherford** [comment]
> We will standardize these since there are so few.

Thanks.

From tomorrow there will be a log file.  I'll add the URL here when it's done tomorrow morning.

> Actually, we should allow AA111BB

No problem.  I'll fix the code.

**Comment by ValWood** [comment]
These are also OK, minus sign indicates promoter region
nucleotide_mutation  mei2 -G1512T   5943de801ceb71fa 
nucleotide_mutation  mei2 -G1512T,-G1692T   5943de801ceb71fa

**Comment by kimrutherford** [comment]
> Actually, we should allow AA111BB

> These are also OK, minus sign indicates promoter region

I've made those changes.  So the warnings are now:

```
alelle type          gene name  allele description   session (if available)
nucleotide_mutation  srp7       G72A,G78A,G100A,G107A,Gl12A,G141A    
nucleotide_mutation  srp7       T(-5)C,T(-3)C,U88C    
nucleotide_mutation  srp7       T(-61)C,G(-75)C,U62C,U101C    
nucleotide_mutation  srp7       A163U,C169U6    
amino_acid_mutation  uaf2       del aa 53-113    
amino_acid_mutation  uaf2       Q174->stop    
amino_acid_mutation  uaf2       C157S,C163,C167I    
amino_acid_mutation  sap1       1-21    
amino_acid_mutation  sap1       1-21,151-254    
amino_acid_mutation  sap1       204-254    
amino_acid_mutation  sap1       241-254    
amino_acid_mutation  sap1       144-254    
amino_acid_mutation  sap1       151-254    
amino_acid_mutation  sap1       158-254    
amino_acid_mutation  sap1       1-21,144-254    
amino_acid_mutation  sap1       137-254    
amino_acid_mutation  prp2       deletion    
amino_acid_mutation  cnd2       k639R    396866ab84f69995
amino_acid_mutation  cut1       1-1452    3926aad5386b9286
amino_acid_mutation  hhp2       W214stop    4d3b0d5a0015df91

```

**Comment by mah11** [comment]
From the latest list, I've found and named all except this one in PHAFs:

>    amino_acid_mutation  prp2       deletion

**Comment by ValWood** [comment]
> amino_acid_mutation prp2 deletion

I wonder where that is? Not in Art either... maybe I fixed it in another session this morning, I did fix a couple of things (although then it would have a canto link??)

**Comment by mah11** [comment]
>> amino_acid_mutation prp2 deletion
>
> I wonder where that is? Not in Art either.

yeah, I saw that and I'm stumped too :/

**Comment by ValWood** [comment]
I'll see if it is gone by tomorrow and then dig deeper. There are some canto sessions hidden somewhere that predated the official Canto release. I don't think they have  session IDs. Must be in there, but I can't locate them. I checked external data and supporting files....

**Comment by ValWood** [comment]
Got it! will fix

**Comment by ValWood** [comment]
Nope thats GO annotations....hmmph

**Comment by kimrutherford** [comment]
I think it's from:
```
pombe-embl/external_data/phaf_files/chado_load/ltp_phafs/PMID_9917066_phaf.tsv
```

**Comment by mah11** [comment]
OK; I definitely looked at that file yesterday, but I'll check it again.

**Comment by mah11** [comment]
Got it - the PHAF has "amino acid mutation" as the allele *type*. Took ages to spot that :stuck_out_tongue:  

I now have it fixed locally, but can't commit until the server is back.

**Comment by mah11** [comment]
just snuck it in before oliver1 goes offline again

**Comment by kimrutherford** [comment]
The load worked last night.  Here's the log file for adding allele names:

https://curation.pombase.org/dumps/builds/pombase-build-2021-11-20/logs/log.2021-11-20-21-58-52.add-missing-allele-names

**Comment by ValWood** [comment]
>https://curation.pombase.org/dumps/builds/pombase-build-2021-11-20/logs/log.2021-11-20-21-58-52.add-missing-allele-names

thanks, now really are all fixed (I keep missing alleles in multi allele genotypes)
