### ISSUE TITLE
check for strain backgrounds in allele names

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#882]
Follow on from https://github.com/intermine/pombemine/issues/10

We should look for mentions of h90 and 972  in the allele name. I think this is a fudge from way back before we could capture background separately.

(I know there were more, I only screenshotted one example)

**Comment by mah11** [comment]
The downloadable PHAF only has two, `h- sty1delta` and `h90 sty1delta` with one annotation apiece.

(also put same comment on intermine ticket by mistake)

**Comment by ValWood** [comment]
in that case I think I got them all ( 1 paper)
