### ISSUE TITLE
Add a log file with allele descriptions that look weird

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#883]
Following on from #881.

We can probably warn about some descriptions.  Especially for `nucleotide_mutation` and `amino_acid_mutation` allele types.

**Comment by ValWood** [comment]
Yes, I was going to open a ticket about that. Don't do it quickly, it will freak me out since I won't have time to fix them yet.

**Comment by ValWood** [comment]
- [ ] warn about  amino acid descriptions not following the format  X#X(,X#X)n

**Comment by kimrutherford** [comment]
> Don't do it quickly, it will freak me out since I won't have time to fix them yet.

It's been 2 months.  Would it freak you out if we implemented this now?

**Comment by ValWood** [comment]
let's do it. I can cope now. It would be good to know what we are dealing with.

**Comment by ValWood** [comment]
I think this ticket is now made obsolete by @manulera  s work.. read the history and feel the pain.
