### ISSUE TITLE
 untracable annotation, possible problem with remapping

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#887]
<img width="1158" alt="Screenshot 2021-11-22 at 21 44 44" src="https://user-images.githubusercontent.com/7359272/142939737-7a4d6903-4007-4125-a064-3b2f11dac30b.png">

I was looking to fix the annotation
conversion of ds siRNA to ss siRNA involved in RNA interference
 to 
heterochromatin assembly by small RNA

because GO is removing the former.

However, I can't find it in
pombe-embl/supporting_files/legacy_go_annotations_from_contigs.txt
or
pombe-embl/external_data/external-go-data/From_curation_tool

I  seem to remember that there was some automated remapping of legacy terms in Artemis to new terms (I need to learn where, how), might that be the reason.

Or am I missing something obvious? tired....

**Comment by kimrutherford** [comment]
I think it's from GOA:

```
UniProtKB       Q9P7B8  arb1    enables GO:0008428      PMID:17310250   IDA             F       Argonaute-binding protein 1     arb1|SPAC140.03 protein taxon:284812    20070323        PomBase       has_input(PomBase:SPCC736.11)
```

**Comment by ValWood** [comment]
phew OK. Unirpto must have curated this paper. Maybe  I already asked about this?

**Comment by ValWood** [comment]
I still don't understand. The annotation source of this annotation  in Uniprot is  PomBase
https://www.uniprot.org/uniprot/O74957

**Comment by ValWood** [comment]
Also it has an extension so definitely one of ours...

**Comment by kimrutherford** [comment]
Ah sorry.  I was searching the annotation at the top of your screenshot.

It is this one in legacy_go_annotations_from_contigs.txt:
```
PomBase SPCC736.11      ago1            GO:0033168      PMID:17310250   IMP             P       argonaute       csp9    protein taxon:4896      20070323        PomBase
```

**Comment by ValWood** [comment]
Right I couldn't find it becasue it was already removed...
