### ISSUE TITLE
not enough information  in log file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#889]
https://curation.pombase.org/dumps/latest_build/logs/log.2021-11-22-22-01-23.allele-synonyms
skipping line 182 - more than one feature found with name "dhp1-1a":
skipping line 183 - more than one feature found with name "dhp1-1a":

needs session info

**Comment by mah11** [comment]
This check reports on the contents of `pombe-embl/supporting_files/allele-synonyms.txt`, not any Canto session.

**Comment by mah11** [comment]
p.s. I've also just converted the two versions of "dhp1-1" to description-based names and updated `allele-synonyms.txt` accordingly

**Comment by ValWood** [comment]
So allele-synonyms.txt is just for if you have a bunch of synonyms and want to add them quickly? I never used it...

**Comment by mah11** [comment]
Originally it was for a batch of synonyms that I'd been keeping in a pack-rat file, so they could be loaded in one go ;)

But now, yes, you can indeed use it to add more allele synonyms quickly. Three columns - name, synonym, reference.

**Comment by ValWood** [comment]
cool! thanks

**Comment by mah11** [comment]
oh yeah, one synonym per line; use multiple lines for an allele with multiple synonyms
