### ISSUE TITLE
The same allele, not reported

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#890]
https://www.pombase.org/genotype/nda3-KM311-unknown-unknown
nda3-311, nda3-311cs

but
https://www.pombase.org/genotype/nda3-311-unknown-unknown-expression-not_assayed

but does not appear here
https://curation.pombase.org/dumps/latest_build/logs/log.2021-11-24-04-28-54.chado_checks

**Comment by kimrutherford** [comment]
So the synonym matches?  I don't think there are any checks for synonyms yet.

**Comment by ValWood** [comment]
Hmm, here a primary name of one gene is the synonym of another gene which would not cause an alert unless the description are the same. But here the descriptions are the same "unknown".
If we have   2 tye "unknown" with a shared name (primary, or synonym), for the SAME GENE that should be looked into, because they are almost certainly going to be the same allele.... Can we report these?

**Comment by ValWood** [comment]
If a specific gene has more than 1 alleles of type "unknown", with a shared allele name or synonym, report.

**Comment by ValWood** [comment]
We need to standardize the background use too.

It seems that we have settled on nda3-KM311. I will fix the genotypes.

**Comment by ValWood** [comment]
I meant to say could you access the usage of nda3-311 in backgrounds so that I can fix this too.

**Comment by kimrutherford** [comment]
> If a specific gene has more than 1 alleles of type "unknown", with a shared allele name or synonym, report.

I've had a go at this.  It didn't make it into the current load but it should be there on Wednesday morning.  Here's an example output:  [unknown_allele_name_synonym_matches.tsv.txt](https://github.com/pombase/pombase-chado/files/7664714/unknown_allele_name_synonym_matches.tsv.txt)

The first column is the allele name.  The third column is the name or synonym that is duplicated.  The if it was a synonym that was duplicated the fourth column will contain "synonym".  The synonym will occur in or more of canto sessions listed.  Sorry, it's not the clearest.

**Comment by ValWood** [comment]
I will try to parse that *when* I look at the logfile ;)

**Comment by kimrutherford** [comment]
> t didn't make it into the current load but it should be there on Wednesday morning.

https://curation.pombase.org/dumps/builds/pombase-build-2021-12-07/logs/log.2021-12-07-22-23-18.chado_checks.unknown_allele_name_synonym_matches
