### ISSUE TITLE
human ortholog data

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#893]
Hi Kim,
From pombeMine call:

Currently, human gene linking in pombeMine is not retrieving OMIM disease associations. It seems this is because our ortholog data is modelled on HGNC symbol, rather than HGNC identifier.

Since we have both (Symbol and ID), should we add an additional column to the ortholog table to  include the HGNC Identifier to the downloadable ortholog file?  It would be more robust for Ingtermine to sue the HGNC as the primary key since the symbols  are still in flux.

**Comment by ValWood** [comment]
Actually this might not be practical,because our current ortholog representation for download is:

SPAC1002.05c	KDM5D|KDM5C|KDM5B|KDM5A
SPAC1002.06c	NONE
SPAC1002.07c	SAT2|SATL1|SAT1
SPAC1002.08c	TFB1M|TFB2M

it isn't a one to one mapping.

If it is helpful for pombemine could we instead add this info to their Json file?

SPAC1002.05c	HGNC:11114|HGNC:11115|HGNC:18039|HGNC:9886

OR 
SPAC1002.05c.      HGNC:11114
SPAC1002.05c.      HGNC:11115
SPAC1002.05c.      HGNC:18039
SPAC1002.05c.      HGNC:9886

@danielabutano @rachellyne 
which would you prefer?

**Comment by ValWood** [comment]
It might be nice to give pombase users an option of

pombe human orthologs (using HGNC identifier)
SPAC1002.05c HGNC:11114|HGNC:11115|HGNC:18039|HGNC:988

pombe human orthologs (using HGNC symbol)
SPAC1002.05c KDM5D|KDM5C|KDM5B|KDM5A

**Comment by kimrutherford** [comment]
There's also this file with HGNC IDs: https://www.pombase.org/nightly_update/exports/pombe-human-orthologs-with-systematic-ids.txt.gz

**Comment by ValWood** [comment]
@danielabutano @rachellyne
that will  work won't it. Could you switch to use this file (ideally populate the  synonym too?)

**Comment by ValWood** [comment]
Can probably close this. I added to my list to discuss with Rachel.

**Comment by kimrutherford** [comment]
OK.  Let me know if you or InterMine need anything else.
