### ISSUE TITLE
report MONDO "replaced by" term in log

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#896]
Report MONDO "replaced by" term in log, if ​available.

i.e https://curation.pombase.org/dumps/latest_build/logs/log.2021-12-09-19-21-41.disease_associations

can't load annotation for SPAC19A8.14, line 264 - MONDO:0014554 not found in database

OLS has 

This term is obsolete Replaced by MONDO:0024189

so I presume this is available for most terms?

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0014554

**Comment by kimrutherford** [comment]
The replaced_by term is supposed to be in the logs already:
https://github.com/pombase/pombase-chado/issues/810#issuecomment-751427883

I'll fix that.

**Comment by kimrutherford** [comment]
I had implemented this for the MalaCards data file but I had forgotten to implement it for reading `pombase_disease_associations_mondo_ids.txt`.

I had even commented about it in #810:

> I'll change the code that loads pombase_disease_associations_mondo_ids.txt to do the same thing.

Sorry about that.  It's done now so the `replaced_by` and `consider` fields (if any) will be shown in the log for obsolete terms.

**Comment by ValWood** [comment]
https://curation.pombase.org/releases/pombase-2019-03-01/logs/log.2019-03-02-04-17-44.malacards_data

is now reporting bzillions of errors:


no DO ID for ribose_5_phosphate_isomerase_deficiency -> RPIA (SPAC144.12)
no DO ID for gracile_syndrome -> BCS1L (SPAC644.07)
no DO ID for peripheral_neuropathy_myopathy_hoarseness_and_hearing_loss -> MYH14 (SPCC645.05c)
no DO ID for infantile_liver_failure_syndrome_1 -> LARS (SPAC26F1.13c)
no DO ID for fumarase_deficiency -> FH (SPCC18.18c)
no DO ID for autoimmune_interstitial_lung_joint_and_kidney_disease -> COPA (SPBPJ4664.04)
no DO ID for myopathy_isolated_mitochondrial_autosomal_dominant -> CHCHD10 (SPAC6C3.02c)
no DO ID for hereditary_leiomyomatosis_and_renal_cell_cancer -> FH (SPCC18.18c)
no DO ID for alopecia_neurologic_defects_and_endocrinopathy_syndrome -> RBM28 (SPBC4F6.14)
no DO ID for combined_oxidative_phosphorylation_deficiency_21 -> TARS2 (SPAC24C9.09)
no DO ID for combined_oxidative_phosphorylation_deficiency_25 -> MARS2 (SPAC27E2.06c)
no DO ID for combined_oxidative_phosphorylation_deficiency_19 -> LYRM4 (SPBC13G1.06c)
no DO ID for cutaneous_telangiectasia_and_cancer_syndrome_familial -> ATR (SPBC216.05)
no DO ID for ataxia_telangiectasia_like_disorder_2 -> PCNA (SPBC16D10.09)
no DO ID for polymicrogyria_bilateral_temporooccipital -> FIG4 (SPAC1093.03)
no DO ID for spastic_ataxia_4_autosomal_recessive -> MTPAP (SPBC1685.06)
no DO ID for sensory_ataxic_neuropathy_dysarthria_and_ophthalmoparesis -> POLG (SPCC24B10.22)
no DO ID for myopathy_scapulohumeroperoneal -> ACTA1 (SPBC32H8.12c)
no DO 

and refers to DO, not MONDO?

**Comment by kimrutherford** [comment]
> https://curation.pombase.org/releases/pombase-2019-03-01/logs/log.2019-03-02-04-17-44.malacards_data

That's a very old log file.

Here's the latest: https://curation.pombase.org/dumps/builds/pombase-build-2021-12-30/logs/log.2021-12-30-21-33-40.malacards_data

**Comment by ValWood** [comment]
right!

**Comment by ValWood** [comment]
working:
MONDO:0008956 is obsolete (replaced by: MONDO:0009744) - skipping annotation for SPBC530.12c / ceroid_storage_disease
