### ISSUE TITLE
create a list of log files on wiki and document contents

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#897]
Once we have list and contents, I will add how to fix specific issues (some are non-obvious)

**Comment by kimrutherford** [comment]
I've started this here: https://github.com/pombase/pombase-chado/wiki/Log-files-generated-by-the-nightly-load

**Comment by kimrutherford** [comment]
I've done a first pass now but it's mostly bullet points.  I'll update and expand it as questions and confusion come up.

**Comment by ValWood** [comment]
That's probably enough, I can continue from here. I know how to fix most things, and I will document the edge cases.

**Comment by kimrutherford** [comment]
Great.  Thanks.

If anything needs clarifying, let me know.

**Comment by ValWood** [comment]
chado_checks.alleles_instance_of_gene
Check that all alleles are an instance_of gene.

What does that mean? It's empty, but I don't recall it

**Comment by ValWood** [comment]
@kimrutherford 
- [ ] fix file name
badly_foramtted_pro_ids
->
badly_formatted_pro_ids

**Comment by kimrutherford** [comment]
> fix file name

Done!

**Comment by kimrutherford** [comment]
> chado_checks.alleles_instance_of_gene
> Check that all alleles are an instance_of gene.

It's a very internal loading check to make sure the database has the right structure for alleles and genes.  It was useful early on but it should always be empty now.

Would it be better if we didn't write a log file if it would be empty?

**Comment by ValWood** [comment]
No I was just curious. Keep it. I will update docs...

**Comment by ValWood** [comment]
We can probably close this. I can extend as and when I find new things?

**Comment by kimrutherford** [comment]
> We can probably close this. I can extend as and when I find new things?

I think so.  I've been adding new log files to the wiki when they are created.
