### ISSUE TITLE
logfile chado_checks.duplicate_pro_ids

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#900]
This logfile, I don't understand where the error comes from

PRO IDs used for more than one gene - CHECK FAILURE:  expected 0 but got 4
pro_id	session	uniquename
  PomBase:SPCC548.03c.1	06d77d7ac3f77bbc	SPCC548.03c.1
  PomBase:SPCC548.03c.1	06d77d7ac3f77bbc	SPCC548.03c.2
  PomBase:SPCC548.03c.2	06d77d7ac3f77bbc	SPCC548.03c.1
  PomBase:SPCC548.03c.2	06d77d7ac3f77bbc	SPCC548.03c.2

This is the session, which looks OK:

<img width="932" alt="Screenshot 2021-12-13 at 17 22 15" src="https://user-images.githubusercontent.com/7359272/145860082-6543435a-2dfe-4584-b5cd-eb4b5198e913.png">

I looking in the inferred gaf and I don't see any annotations  for SPCC548.03c, so now I am baffled...

**Comment by kimrutherford** [comment]
It's a bug.  Something is going wrong during the loading because the gene has two transcripts.

**Comment by ValWood** [comment]
It might not be in the logs tomorrow as I only just remembered to re-approve the session.

**Comment by kimrutherford** [comment]
Now I've looked into this, I think the problem will go away if you change the `column_17` extensions to `transcript_isoform_id`.  See: https://github.com/pombase/canto/issues/2351

If I'm understanding things correctly, the `column_17` extensions should only be used for PRO IDs and the like.

**Comment by kimrutherford** [comment]
> I think the problem will go away if you change the column_17 extensions to transcript_isoform_id

I've done that and re-approved the session.  I'll check the logs tomorrow morning.

**Comment by kimrutherford** [comment]
> I've done that and re-approved the session. I'll check the logs tomorrow morning.

Fixed!
