### ISSUE TITLE
new log error that I do not understand

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#901]
Running check: PomBase::Check::DuplicateInteractions
Running check: PomBase::Check::FeatureCount
Running check: PomBase::Check::PhenotypesNotInCategory
Wide character in print at /local-homes/pbuild/git/pombase-chado/lib/PomBase/Check.pm line 148, <$website_config_fh> line 1.

**Comment by kimrutherford** [comment]
The message has gone away but I think I've found and fixed the problem.  I'll close this issue.  Let me know if you see it again.
