### ISSUE TITLE
missing session in log file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#902]
https://curation.pombase.org/dumps/latest_build/logs/log.2021-12-17-21-33-02.chado_checks.duplicate_allele_descriptions

there is no session  listed for the allele1_sessions?

uniquename	allele1_name	allele1_sessions	description	allele2_name	allele2_sessions
  SPBC1734.02c	cdc27-1-169		170-372	cdc27(1-169)	cf72468ea0fb98d3
  SPBC1734.02c	cdc27-1-159		160-372	cdc27(1-159)	cf72468ea0fb98d3
  SPBC1734.02c	cdc27-1-159		160-372	cdc27-D1	e976a54955ad43a4,e976a54955ad43a4,cf72468ea0fb98d3,f76448cf5f73c99d,9d8a86ce7ba5c91b,220d35c90a1310b0
  SPBC1734.02c	cdc27-1-149		150-372	cdc27(1-149)	cf72468ea0fb98d3
  SPBC1734.02c	cdc27-273-372		1-272	cdc27(273-372)	cf72468ea0fb98d3
  SPBC1734.02c	cdc27-273-352		1-272,353-372	cdc27(273-352)	cf72468ea0fb98d3
  SPBC1734.02c	cdc27-293-372		1-292	cdc27(293-372)	cf72468ea0fb98d3
  SPBC1734.02c	cdc27-313-372		1-312	cdc27(313-372)	cf72468ea0fb98d3
  SPBC1734.02c	cdc27-333-372		1-332	cdc27(333-372)	cf72468ea0fb98d3

**Comment by kimrutherford** [comment]
Looks like they're from: `pombe-embl/external_data/phaf_files/chado_load/ltp_phafs/PMID_15579205_phaf.tsv`

**Comment by ValWood** [comment]
fixed
