### ISSUE TITLE
Check background genotypes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#903]
On the call we decided to check the genotype backgrounds and remove anything that shouldn't be there.

Here are all the backgrounds: [all_genotype_backgrounds-2020-06-19.txt](https://github.com/pombase/curation/files/4801544/all_genotype_backgrounds-2020-06-19.txt)

I'll filter out the backgrounds that only mention allele names and then see what's left.

**Comment by ValWood** [comment]
Hi Kim,

Can we update this list and convert to a log file?
I think I have done all the fixes in the ticket so we can begin afresh...
v

**Comment by ValWood** [comment]
Action: convert to a log file.

**Comment by kimrutherford** [comment]
I forgot to make a note of the code I used for this.  I try to stuck it in the issue but I didn't for this one.

So my first attempt at making this a log file is likely to need a bit of fixing before it's useful.

**Comment by ValWood** [comment]
OK!

**Comment by kimrutherford** [comment]
> I forgot to make a note of the code I used for this. 

I found the code and I've fixed it so that it can generate a log file.

Here's what the output currently looks like.  The second column is the background exactly as it's stored in Chado.  The third column contains the bits of the background that aren't allele names, gene names, gene deletions, gene wild types or "h+"/"h-" etc.

Let me know what else can be ignored in the background.

[genotype_background_log.txt](https://github.com/pombase/pombase-chado/files/7819645/genotype_background_log.txt)

**Comment by ValWood** [comment]
I have fixed a few.
It will take a few goes, lots of typos and things that should not be there.

Additional filters for now:
KanR
ade6-M216
KanMX6
leu1-32

Also ignore any existing alleles in database, so I think
cig1Δ
nda3-km311
should be ignored?

**Comment by kimrutherford** [comment]
I've added these to the filtering:
> KanR
> ade6-M216
> KanMX6

We had "kanR" already.

"leu1-32" is already filtered - it's not in column 3.

"cig1Δ" is ignored - not in column 3.

For nda3-km311 do you mean "nda3-KM311", with the "km" capitalised?   Should we ignore capitalisation when filtering?

Here's the updated output:
[genotype_background_log-2.txt](https://github.com/pombase/pombase-chado/files/7825375/genotype_background_log-2.txt)

**Comment by ValWood** [comment]
>  Should we ignore capitalisation when filtering?

Good question. I think the capitalization on some is wrong. I should fix really.

If you could add this to the logs I will chip away at it.

**Comment by kimrutherford** [comment]
I've added this but not in time for tonight's load.  It should be visible on Wednesday morning in the file ending with ".chado_checks"

**Comment by ValWood** [comment]
One thing to filter  next is:
Any valid gene name -GFP

**Comment by kimrutherford** [comment]
> One thing to filter next is:
> Any valid gene name -GFP

I've made that change in time for tonight's load (I think).

**Comment by kimrutherford** [comment]
Should we transfer this to the curation tracker now?

**Comment by ValWood** [comment]
I don't need  a ticket since I have the log file to chip away at
