### ISSUE TITLE
exists_during annotation (convert this output to a log file)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#905]
I will probably look at the non-phase ones later but will need a reduced list

[exists_during.txt](https://github.com/pombase/curation/files/3748248/exists_during.txt)

**Comment by kimrutherford** [comment]
I've added that.  Look out for a log file ending in `.exists_during_extensions_not_in_cell_cycle_phase`

**Comment by ValWood** [comment]
This is great!
Can you also exclude:
any term in "response to" branch of GO.
and
single-celled organism vegetative growth phase (which /might be in a mini-ontology?)

**Comment by ValWood** [comment]
correction.

both queries should use
GO:0044848 biological phase,
which covers
cell cycle phase
AND
single-celled organism vegetative growth phase

**Comment by ValWood** [comment]
both queries should include:

GO:0044848 biological phase
(which includes cell cycle phase and "single-celled organism vegetative growth phase")
AND
"GO:0050896 response to stimulus"

**Comment by kimrutherford** [comment]
How's this?:

[exists_during.txt](https://github.com/pombase/pombase-chado/files/7765802/exists_during.txt)

----------------------------

Note to self:
```sql
select distinct f.uniquename, t.name
  from feature_cvterm fc join feature f on f.feature_id = fc.feature_id
  join cvterm t on t.cvterm_id = fc.cvterm_id
  join cvterm_relationship ext_rel on ext_rel.subject_id = t.cvterm_id
  join cvterm ext_rel_type on ext_rel.type_id = ext_rel_type.cvterm_id
  join cvterm obj on ext_rel.object_id = obj.cvterm_id
 where ext_rel_type.name = 'exists_during'
   and obj.cvterm_id not in
       (select subject_id from cvtermpath p
            join cvterm o on p.object_id = o.cvterm_id
            join cvterm pt on p.type_id = pt.cvterm_id
            where pt.name = 'is_a' and (o.name = 'biological phase' or o.name = 'response to stimulus'))
order by t.name;
```

**Comment by ValWood** [comment]
This looks correct. You can close this. There will be more filters in the future but I will open a new ticket.

**Comment by kimrutherford** [comment]
I'll close it after I've arranged for it to go into a log file.

**Comment by ValWood** [comment]
I see the log(s).

Currently the 'phases' are filtered, but not the "response to" terms

**Comment by kimrutherford** [comment]
This should be fixed now.

**Comment by ValWood** [comment]
These logs look good. I may add additional filters (new ticket). FOr now I need to fix quite a free to make them either 'part_of' or 'phase' terms  so I will do this first.
