### ISSUE TITLE
non phase "happens_during" (convert this output to a log file)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#906]
These should be the only non-phase terms we are using after the fixes:

GO:0034599    cellular response to oxidative stress
GO:0072738    cellular response to diamide
GO:0072711    cellular response to hydroxyurea
GO:0071470    cellular response to osmotic stress
GO:0071474    cellular hyperosmotic response
GO:0071242    cellular response to ammonium ion
GO:0034605    cellular response to heat 
GO:0006995    cellular response to nitrogen starvation
GO:0071456    cellular response to hypoxia (these could be involved_in Or even a parent of the pathway? some are ‘involved in’)
GO:0071472    cellular response to salt stress
GO:0042149    cellular response to glucose starvation  (these could be involved_in Or even a parent of the pathway)
GO:0071333    cellular response to glucose stimulus
GO:0016036    cellular response to copper ion starvation (these could be involved_in ?)
GO:0010106    cellular response to iron ion starvation
GO:0071276    cellular response to cadmium ion  (these could be involved_in ?)
GO:0016036    cellular response to phosphate starvation
GO:0006974    cellular response to DNA damage stimulus
GO:0071280    cellular response to copper ion    (these could be involved_in ?)
GO:0072757    cellular response to camptothecin 
GO:0034644    cellular response to UV  

we need to decide
1 Are these all required? 
GO:0072738    cellular response to diamide (probably not)
GO:0072711    cellular response to hydroxyurea (is just a condition for slowing replication?)
GO:0072757 cellular response to camptothecin

look more like conditions than processes

2. Some could probably be involved_in?

3. I'm guessing the "response to copper ion etc came about because things like "copper responsive TF were obsoleted"  perhaps these could be "involved_in"

**Comment by kimrutherford** [comment]
> which annotation type are these? I thought the were GO, but I see no "happens_during" extensions in the gaf file?

Did this get solved?

**Comment by kimrutherford** [comment]
For the log file, does it make sense to just write the extensions where the annotation count is not zero?

**Comment by ValWood** [comment]
I don't need to see all extensions (otherwise I would see every correct one, included all of the has_input.

This file should've exactly the  same as 
https://github.com/pombase/pombase-chado/issues/905
which is occurs_during for component,
but will be on happens_furing for MF and BP.

It should have the same filters (i.e. I don't need to see the "cell cycle phase", or "response to" terms). I will review them and either fix the remaining, or add additional filters. 
Some are tricky as we use a process (i.e cytokinesis, conjugation) to describe the time when something occurs since it is  easier than to report the phase. Some processes will need to stay, but I could still standardize to a single term). 

Does that make sense?

**Comment by ValWood** [comment]
correction.

both queries should use
GO:0044848 biological phase,
which covers
cell cycle phase
AND
single-celled organism vegetative growth phase

**Comment by ValWood** [comment]
both queries should include:

GO:0044848 biological phase
(which includes cell cycle phase and "single-celled organism vegetative growth phase")
AND
"GO:0050896 response to stimulus"

**Comment by kimrutherford** [comment]
Here is the result after updating the query: [happens_during.txt](https://github.com/pombase/pombase-chado/files/7768563/happens_during.txt)

If that looks right I'll make sure it goes into a log file.

**Comment by ValWood** [comment]
Looks right.
v

**Comment by kimrutherford** [comment]
Sorry, I thought I had done that.  I've updated the query and the one for #905.

**Comment by kimrutherford** [comment]
Does the log file look OK now?

**Comment by ValWood** [comment]
yes, thanks!
