### ISSUE TITLE
check log reporting of duplicate GO annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#908]
the reporting in this log
https://curation.pombase.org/dumps/latest_build/logs/log.2021-12-29-21-29-47.chado_checks.duplicate_go_annotation
might be slightly odd.

|(xap5 isn't the name for SPAC1556.06.1?)

 2	SPAC1556.06.1	xap5	cytosol	Inferred from high throughput direct assay	PMID:16823372	[null]	e442ede7e2d1dbdb

**Comment by kimrutherford** [comment]
I've fixed that for Saturday night's load.  The SQL query was slightly wrong.  It looks like it was only one row (the one you spotted) that was incorrectly included.
