### ISSUE TITLE
Query binding MF

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#91]
I'd like to know all instances where I have used a binding MF term
I suspect many of these can be migrated to activated_by / inhibited by extensions 
(these may have extension required_for, but don't think it is true for all cases)

Original comment by: Antonialock

**Comment by ValWood** [comment]
Is this still valid? @Antonialock

**Comment by Antonialock** [comment]
I can't remember this. I'm sure we can spot them if there is anything that needs fixing.
