### ISSUE TITLE
log errors, can't fix 2 

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#911]
can't find new term for methylated lysine in mapping for PSI-MOD: failed to load qualifier 'term=modification, methylated lysine; residue=K20; db_xref=PB_REF:0000001; evidence=ISS; cv=pt_mod; date=20100311' from SPAC1834.03c.1
can't find new term for methylated lysine in mapping for PSI-MOD: failed to load qualifier 'term=modification, methylated lysine; residue=K9; db_xref=PMID:14561399; annotation_extension=present_during(GO:0031508); cv=pt_mod; date=20100311' from SPAC1834.04.1
can't find new term for methylated lysine in mapping for PSI-MOD: failed to load qualifier 'term=modification, methylated lysine; residue=K4; cv=pt_mod; db_xref=PB_REF:0000001; evidence=ISS; date=20100311' from SPAC1834.04.1
can't find new term for methylated lysine in mapping for PSI-MOD: failed to load qualifier 'term=modification, methylated lysine; residue=K14; db_xref=PMID:14561399; annotation_extension=present_during(GO:0031508); cv=pt_mod; date=20100311' from SPAC1834.04.1

I know why these errors are occurring, but I don't know how to fix it.
I changed some "modification" annotations in Artemis from
methylated residue  (which was OK)
to "methylated lysine" 
which fails?

Maybe there is a file somewhere which reads the term and maps to an ID?

**Comment by kimrutherford** [comment]
SVN says the change was from "term=modification, methylated; residue=K4; cv=pt_mod; ..." to "term=modification, methylated lysine; residue=K4; cv=pt_mod; ..."

The mapping file is: pombe-embl/chado_load_mappings/modification_map.txt

It has "methylated" but not "methylated lysine".

**Comment by ValWood** [comment]
Thanks. Fixed and documented in log wiki.

**Comment by ValWood** [comment]
I think this is fixed, check tomorrow

**Comment by kimrutherford** [comment]
> I think this is fixed, check tomorrow

Your change fixed the problem.

**Comment by ValWood** [comment]
This is still not fixed, I can't figure out why. Will look next week.

**Comment by kimrutherford** [comment]
I think it's all OK.  An old copy of `all_warnings.txt` was in the logs directory.  Sorry about that.  We renamed the file to `all_contig_warnings.txt`, which doesn't have the modification warnings.

**Comment by ValWood** [comment]
right!
