### ISSUE TITLE
log issue, insufficient info to fix

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#912]
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-02-21-30-14.allele-synonyms

skipping line 162 - more than one feature found with name "pak1-deltaN":

**Comment by kimrutherford** [comment]
Sorry about that.  The warning come from a typo in the synonym loading code.  It should have said:

```
can't find feature with name "pak1-deltaN" at line 162 - skipping
```

I've fixed the code for Tuesday night's load.

If the loader does find more than one feature with the same name, it will also log the sessions they come from.
