### ISSUE TITLE
new warnings, how to fix?

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#914]
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-03-21-30-47.allele-synonyms

whare is this errorr from?

skipping line 99 - more than one feature found with name "ras1-V12":
skipping line 100 - more than one feature found with name "ras1-V12":
skipping line 101 - more than one feature found with name "ras1-V12":

**Comment by kimrutherford** [comment]
That was this bug: pombase/pombase-chado#912

It's now fixed:
https://curation.pombase.org/dumps/builds/pombase-build-2022-01-04/logs/log.2022-01-04-21-30-47.allele-synonyms

```
can't find feature with name "ras1-V12" at line 99 - skipping
can't find feature with name "ras1-V12" at line 100 - skipping
can't find feature with name "ras1-V12" at line 101 - skipping
can't find feature with name "pak1-deltaN" at line 162 - skipping
```

This is the input file: pombe-embl/supporting_files/allele_synonyms.txt

**Comment by ValWood** [comment]
right got it, I forgot about that file. So I can just delete those  lines ( this error is because the primary name on all of these is now ras1-val17 which was most used.

**Comment by ValWood** [comment]
I  see this was already clear from the log docs when I wen to read them. I had  been confusing this with he other allele synonyms log. To make it clearer (as `i will forget again), can we rename this log as

allele-synonyms-from-supporting-data
(I already updated the logs as if this change was made)

**Comment by ValWood** [comment]
wiki

**Comment by kimrutherford** [comment]
> To make it clearer (as `i will forget again), can we rename this log as allele-synonyms-from-supporting-data

Yep, no problem.  I guess we should rename the allele-comments log file too?: allele-comments-from-supporting-data

**Comment by ValWood** [comment]
Makes sense.

**Comment by kimrutherford** [comment]
OK, that's done.
