### ISSUE TITLE
bulk updating of alleles required

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#915]
I have a few examples of 'bulk changes' required- I have done most manually but these have been used too many times to do manually. 

1.  SPCC320.13c	ark1-as3
https://www.pombase.org/gene/SPCC320.13c
There are **93** uses

In sessions	1823b4aa025cae13,200ad9dc9f52e2f1,21d843433d804639,2a9bce7ccbdd5c56,4e1a549f9ec3252a,50ae65179f9a18da,70f8ac4a3ff0e8c5,7341b39d1e6a56ef,a7ecbdb97e27015e,bc6337774fa106c2,caf685fa8d7a836f,f0afc6fe7b0b439a,fdc3419730dab35f	analog-sensitive	(and tomorrow f21f4f173822b0e2,c83c3de5e5b69049)

This should  is currently:

ark1-as3 | analogue-sensitive | other
needs changing globally to 

 - [ ] ark1-as3 | amino acid substitution | L166A,S229A,Q28R,Q176R

-  [ ] Note to self,  add allele comment Q28R,Q176R are unintentional

**Comment by ValWood** [comment]
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-03-21-30-47.chado_checks.unknown_allele_name_synonym_matches

I only have one of these left to fix but it has 31 geonypes
  stf1-1	SPBC649.05	stf1-1	name	27524319ad84c25c

https://curation.pombase.org/pombe/curs/27524319ad84c25c/genotype_manag

for thesethe primary name should be 
cut12.s11  (this isn't standard name syntax but everyone uses a '.' for this one rather than a "-"
(with stf1-1 as a synonym, although you  do not need to add that because other alleles already have it)

**Comment by kimrutherford** [comment]
> ark1-as3 | analogue-sensitive

So only change the ark1-as3 alleles that have "analogue-sensitive" as the description?  There are some sessions where the description is unkown:

  - https://curation.pombase.org/pombe/curs/2a9bce7ccbdd5c56/feature/gene/view/12/ro
  - https://curation.pombase.org/pombe/curs/4e1a549f9ec3252a/feature/gene/view/3/ro
  - https://curation.pombase.org/pombe/curs/caf685fa8d7a836f/feature/genotype/view/2/ro
  - https://curation.pombase.org/pombe/curs/70f8ac4a3ff0e8c5/feature/gene/view/2/ro
  - https://curation.pombase.org/pombe/curs/a7ecbdb97e27015e/feature/gene/view/5/ro

**Comment by ValWood** [comment]
no sorry, all of the ark1-as3 ones.
The genotype comment applies to all   ark1-as3 genotypes.
I will chat to you about  the allele and genotype comments next week.

**Comment by kimrutherford** [comment]
I should have asked earlier: would you like these fixed in Canto or fixed as they are loaded into Chado.  Both are possible and they're about the same amount of work.

**Comment by ValWood** [comment]
In Canto.

There might be others to fix via this query when it is available!

**Comment by kimrutherford** [comment]
> In Canto.

Thanks.  I'm ready to go on this.  There is only a short list to fix:

```
c83c3de5e5b69049    ark1-as3    analog-sensitive    Not assayed    other
2a9bce7ccbdd5c56    ark1-as3    unknown    Not assayed    unknown
4e1a549f9ec3252a    ark1-as3    unknown    Not assayed    unknown
7341b39d1e6a56ef    ark1-as3    analog-sensitive    Wild type product level    other
fdc3419730dab35f    ark1-as3    analog-sensitive    Wild type product level    other
fdc3419730dab35f    ark1-as3    analog-sensitive    Not assayed    other
caf685fa8d7a836f    ark1-as3    unknown    Not assayed    unknown
70f8ac4a3ff0e8c5    ark1-as3    unknown    Not assayed    unknown
70f8ac4a3ff0e8c5    ark1-as3    unknown    Not assayed    unknown
200ad9dc9f52e2f1    ark1-as3    analog-sensitive    Not assayed    other
a7ecbdb97e27015e    ark1-as3    unknown    Not assayed    unknown
bc6337774fa106c2    ark1-as3    analog-sensitive    Not assayed    other
50ae65179f9a18da    ark1-as3    analog-sensitive    Wild type product level    other
1823b4aa025cae13    ark1-as3    analog-sensitive    Not assayed    other
f21f4f173822b0e2    ark1-as3    analog-sensitive    Not assayed    other
f0afc6fe7b0b439a    ark1-as3    analog-sensitive    Not assayed    other
e66906b54c5398a2    ark1-as3    analog-sensitive    Knockdown    other
21d843433d804639    ark1-as3    analog-sensitive    Wild type product level    other
```

**Comment by kimrutherford** [comment]
Done now.

> There might be others to fix via this query when it is available!

No problem.  Just let me know what you need.

**Comment by ValWood** [comment]
Right I could easily have done thos manually! I  was thinking there were 93  alleles to fix but  there were 93 annotations. However I do have a few left with more fixes required (where the alle has need used in lots of multi-gene alleles). I'll make a list of those next time I do the logs.

**Comment by ValWood** [comment]
Did you consider multi-gene alleles containing ark1-as3 (I realise i did not say this explicitly)

**Comment by kimrutherford** [comment]
> Did you consider multi-gene alleles containing ark1-as3 (I realise i did not say this explicitly)

The update covered all alleles, including those in multi-allele genotypes.

**Comment by kimrutherford** [comment]
> I have a few examples of 'bulk changes' required

Did you have some other cases to fix or should we close this issue?

**Comment by ValWood** [comment]
this can close. I will open tickets when I get back to them. I'm currently working through other logs that affect the data in Intermine.
