### ISSUE TITLE
Do not import duplicate Intact annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#917]
Re https://github.com/pombase/pombase-chado/issues/854#issuecomment-1010500628
"The process that automatically adds reciprocal IPI protein binding annotations failed when processing the new data from IntAct. The code didn't like the "with" field not being a PomBase ID. They're UniProtKB IDs, which makes sense.

I changed the code to only add reciprocal IPI annotations if the source of the annotation is PomBase. We can fix that if the IntAct annotations are useful."

Before this, we all the 944 IntAct.
This results in quite a bit of exact duplicate annotation.
See for example: MF IPI's
https://www.pombase.org/reference/PMID:14655046
We need to apply the same 'redundancy filter to Intact that we apply to the UniProt import (I think there is a filter that does not import UniProt annotation if everything is the same except the assigned by (after switching the with field to PomBase form ID),
ignoring data and assigned by.

We could also make a log of these filtered EXP annotations the same as we now do for UiProt.

**Comment by ValWood** [comment]
I think that will fix a lot of this log
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-11-21-33-18.chado_checks.duplicate_go_annotation

...right, back to sleep ;)

**Comment by kimrutherford** [comment]
I've added that filter for Wednesday night's load.  The log output looks like: [intact-duplicates.tsv.txt](https://github.com/pombase/pombase-chado/files/7851444/intact-duplicates.tsv.txt)

**Comment by ValWood** [comment]
Re the |IDs which ate still UniprotKB IDs:
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-11-21-33-18.export_warnings

I will need to report these. These are non-pombe UniProt Ids (S. cerevisiae and human),  in the with filed so they should be curated for GO I will report that to Intact.

**Comment by kimrutherford** [comment]
> I've added that filter for Wednesday night's load.

Here is the log file from last night:
https://curation.pombase.org/dumps/builds/pombase-build-2022-01-13/logs/log.2022-01-14-00-13-51.go-filter-intact-duplicates

**Comment by ValWood** [comment]
Actually, I won't report this because I think it is a valid thing to do for GO. It is just that we do not do this at PomBAse. so we should just filter these and add them to the filtered log.

**Comment by ValWood** [comment]
done.
