### ISSUE TITLE
background log content

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#919]
Now has:

PomBase::Check::_do_query_checks(): DBI Exception: DBD::Pg::st execute failed: ERROR:  function starts_with(character varying, character varying) does not exist
LINE 23:   AND NOT starts_with(allele.name, gene.name)) as sub
                   ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts. [for Statement "select count(*) from (SELECT array_to_string(array
         (SELECT value
          FROM featureprop p
          WHERE p.feature_id = allele.feature_id
            AND p.type_id in
              (SELECT cvterm_id
               FROM cvterm
               WHERE name = 'canto_session')), ',') AS canto_session,
       allele.name AS allele_name,
       gene.name AS gene_name, gene.uniquename as gene_uniquename
FROM feature allele
JOIN feature_relationship rel ON rel.subject_id = allele.feature_id
JOIN cvterm rel_type ON rel.type_id = rel_type.cvterm_id
JOIN feature gene ON rel.object_id = gene.feature_id
JOIN cvterm allele_type ON allele_type.cvterm_id = allele.type_id
JOIN featureprop allele_type_prop ON allele_type_prop.feature_id = allele.feature_id
JOIN cvterm allele_type_prop_type ON allele_type_prop_type.cvterm_id = allele_type_prop.type_id
WHERE rel_type.name = 'instance_of'
  AND allele_type.name = 'allele'
  AND allele_type_prop_type.name = 'allele_type'
  AND (allele_type_prop.value = 'amino_acid_mutation'
       OR allele_type_prop.value = 'nucleotide_mutation')
  AND NOT starts_with(allele.name, gene.name)) as sub"] at /local-homes/pbuild/git/pombase-chado/lib/PomBase/Check.pm line 186

**Comment by kimrutherford** [comment]
I've fixed that for tonight's load.  The query to check that allele names start with a gene name was failing because I used SQL syntax not supported by the (quite old) version of Postgres on the server.  The illegal query was causing the whole Chado checking stage to fail.
