### ISSUE TITLE
log file of unnamed and unrecorded alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#921]
https://www.pombase.org/genotype/SPBC887.14c-unnamed-unrecorded-unrecorded

**Comment by kimrutherford** [comment]
I've added that.  Look for a log file ending in `.chado_check.unnamed_unrecorded_alleles` from Saturday morning.

Here's what it will contain: [unnamed_unrecorded_alleles.txt](https://github.com/pombase/pombase-chado/files/7909397/unnamed_unrecorded_alleles.txt)

**Comment by ValWood** [comment]
I see this file.

 It doesn't seem to include this:
https://www.pombase.org/gene/SPBC21.05c (ra2)

<img width="857" alt="Screenshot 2022-01-24 at 12 41 36" src="https://user-images.githubusercontent.com/7359272/150784923-1a9e2e25-201f-419f-a370-71e8fdcb01f7.png">

**Comment by ValWood** [comment]
It would be good to report session ID or publication in this file
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-23-21-30-10.chado_checks.unnamed_unrecorded_alleles

**Comment by ValWood** [comment]
I'm not sure where the ral2 23A annotation is coming from. It isn't in Artemis?

**Comment by ValWood** [comment]
Another example that wasn't in the logs:
<img width="620" alt="Screenshot 2022-01-24 at 13 07 45" src="https://user-images.githubusercontent.com/7359272/150816219-44861832-4b38-46c4-a102-396dfdbdd07a.png">

**Comment by ValWood** [comment]
and these mrp1 ( now fixed
<img width="1075" alt="Screenshot 2022-01-24 at 13 01 43" src="https://user-images.githubusercontent.com/7359272/150816896-f527b3c9-aed5-4dce-bde3-816debbe8ebc.png">
)

**Comment by ValWood** [comment]
and these tts1,(now fixed in Canto)
<img width="555" alt="Screenshot 2022-01-24 at 12 51 55" src="https://user-images.githubusercontent.com/7359272/150817194-a6959832-add3-4c9a-8988-a5ed17a45bbb.png">

**Comment by kimrutherford** [comment]
I'm confused.  All your examples look like they have names?  The query is for unnamed, unrecorded alleles.

**Comment by ValWood** [comment]
Sorry wrong log file. I expected to see them in this log file.

https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-24-21-31-25.chado_checks.allele_names_not_starting_with_gene_name

**Comment by kimrutherford** [comment]
Could it be that they're not amino_acid_mutation or nucleotide_mutation alleles?  That log file is restricted to those types: https://github.com/pombase/pombase-chado/issues/617#issue-212724605

Currently partial types like partial_amino_acid_deletion aren't included.

**Comment by ValWood** [comment]
Hmm, a few of these seem to be  "amino acid mutation" (the ncs1 for example). But I think we will look at this after pombemine is next reloaded. We can probably come up with an automated way to get names on more of these.

**Comment by kimrutherford** [comment]
> Hmm, a few of these seem to be "amino acid mutation" (the ncs1 for example).

Are you looking at the G2A allele?  That one wasn't in the logs because it was automatically fixed.

**Comment by ValWood** [comment]
Right. Got it. It is fixed in PomBase now, because I fixed  in Canto yesterday.

I still think it would be good to always include the automagically fixed gene name prefix for the allele locally.
It might seem redundant, and partly it is, but not always. 
They serve different purposes. One is a label that researchers will understand (and should always include the gene prefix) and one is a description of the underlying genetic change. 

Also in the cases where the name matches the description, we do not display the description, so it doesn't take up space:
<img width="128" alt="Screenshot 2022-01-26 at 11 26 34" src="https://user-images.githubusercontent.com/7359272/151156175-bc3c5d90-a6c9-402f-8491-efb0057cb18e.png">

Officially all allele names should be prefixed by the gene name. The fact that they aren't is sloppy curation (sometimes researchers will omit the gene prefix from figures (or even text) if all of the figures refer to different alleles of the same gene but this is really just shorthand.

The advantage of always including the gene name is that the alleles will make sense even in absence of the gene details (pombemine is one example but this could happen in other contexts too).

I am fixing the ones which can't be fixed automagically manually. But currently the automagically fixed ones are only fixed for export to PombeMine.
We can discuss if there is some reason I have not thought of for not doing this.

**Comment by kimrutherford** [comment]
> I still think it would be good to always include the automagically fixed gene name prefix for the allele locally.

Do you mean always include in the output of the process that automatically adds allele names?  Or should it be a separate file?
What do you mean by locally?
