### ISSUE TITLE
logfile,  phenotype without evidence

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#922]
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-19-21-32-38.chado_checks.annotation_with_no_evidence

I think this  must be  legacy from phenotypes in Artemis, but I checked a few and now have evidence+ do I'm not sure where we get the evidence for the others currently (Or whether only the first instance is reported)

annotation_with_no_evidence - CHECK FAILURE:  expected 0 but got 1
pmid	term_name	name	uniquename
  PMID:19237545	abnormal glucan synthesis during vegetative growth	chr4delta	SPBC1289.01c:allele-2

**Comment by kimrutherford** [comment]
There is a big map in the Chado load config file that sets evidence automatically for a lot of cases in the contig files:

https://github.com/pombase/pombase-legacy/blob/master/load-pombase-chado.yaml#L639

**Comment by ValWood** [comment]
Ah OK, so for thesse few reported errors can I just add evidence= qualifiers in artemis?

**Comment by ValWood** [comment]
actually ignore, I will get the paper through
https://github.com/pombase/curation/issues/3186

**Comment by kimrutherford** [comment]
> actually ignore, I will get the paper through

Yep, that's the best plan.  evidence= qualifiers or adding the to config file would also work.
