### ISSUE TITLE
report session in log

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#923]
I need to fix a lot of these , so the session ID will make it quicker

https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-19-21-32-38.chado_checks.exists_during_extensions_not_in_cell_cycle_phase

**Comment by ValWood** [comment]
and here
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-19-21-32-38.chado_checks.happens_during_extensions_not_in_cell_cycle_phase

**Comment by kimrutherford** [comment]
I've added a session ID column which should be there in the morning.
