### ISSUE TITLE
Some annotations in legacy GO are not appearing

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#924]
e.g.
PomBase	SPCC825.04c	naa40		GO:0051604	GO_REF:0000051	NAS		P	histone N-acetyltransferase Naa40 (predicted)		protein	taxon:4896	20170727	PomBase		
PomBase	SPCC16C4.12	naa20		GO:0051604	GO_REF:0000051	NAS		P	NatB N-acetyltransferase complex catalytic subunit Naa20 (predicted)	nat3	protein	taxon:4896	20170727	PomBase		

I have not seen any errorrs about this. in the logs. I might have stuffed up the file formatting...

**Comment by ValWood** [comment]
I also can't get the colouring to work in VSC

**Comment by kimrutherford** [comment]
Sorry, I don't understand.  What is the error?

**Comment by ValWood** [comment]
Sorry that should say that the annotations are not appearing.

**Comment by ValWood** [comment]
hang on, I need to check something...

**Comment by ValWood** [comment]
Ignore, it is a parent aleady. I thought it wasn't
