### ISSUE TITLE
add-missing-allele-names log file is empty

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#925]
add-missing-allele-names
Output from the process that adds missing allele names, where possible, using the gene name and allele description.

This log file is empty,I'm not sure that it should be?
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-23-21-30-10.add-missing-allele-names

**Comment by ValWood** [comment]
Also  "fix allele names"
https://curation.pombase.org/dumps/latest_build/logs/log.2022-01-23-21-30-10.fix-allele-names

Message from the process that fixes incomplete allele names.

If name and description are the same and look like a residue change (eg. "A123K" or "K21A,T23A"), add the gene name as a prefix to the allele name: "abc1-A123K" "abc1-K21A,T23A"

**Comment by kimrutherford** [comment]
> add-missing-allele-names
> Output from the process that adds missing allele names, where possible, using the gene name and allele description.
> This log file is empty,I'm not sure that it should be?

I think it's OK.  It only reports the case when the allele doesn't have a name and the description doesn't look like a mutation ("A123B" etc.)

In the other cases the name is automatically set and no warning is generated.

It's similar for the ".fix-allele-names" file - it only warns if the description doesn't look like a mutation.

**Comment by ValWood** [comment]
got it.
