### ISSUE TITLE
phenotypes with very low penetrance

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#926]
@kimrutherford could you do a query for all phenotypes with penetrance less than 3?

https://user-images.githubusercontent.com/7359272/150556226-078305f4-4aa9-46d7-9ac1-986871859351.png

https://github.com/intermine/pombemine/issues/21

It seems odd,but with the query I could not find what they are associated with (I will figure that out with @rachellyne)

**Comment by kimrutherford** [comment]
The majority are from session a15216784fcaa950

Here is the full list:

[low_penetrance_alleles.tsv.txt](https://github.com/pombase/pombase-chado/files/7929463/low_penetrance_alleles.tsv.txt)

--------------------------------------------------------

Note to self:

```sql
SELECT allele.uniquename, allele.name,
       t.name,
       array_to_string(array
                         (SELECT value
                          FROM feature_cvtermprop p
                          WHERE p.feature_cvterm_id = fc.feature_cvterm_id
                            AND p.type_id in
                              (SELECT cvterm_id
                               FROM cvterm
                               WHERE name = 'canto_session')), ',') AS canto_session
FROM feature_cvterm fc
JOIN feature genotype ON genotype.feature_id = fc.feature_id
JOIN feature_relationship genotype_rel ON genotype_rel.object_id = genotype.feature_id
JOIN feature allele ON genotype_rel.subject_id = allele.feature_id
JOIN cvterm t ON t.cvterm_id = fc.cvterm_id
WHERE t.cvterm_id in
    (SELECT cvterm_id
     FROM cvterm
     WHERE cvterm_id in
         (SELECT cvterm_id
          FROM cvtermprop
          WHERE type_id = 72371
            AND value ~ '^\d+(?:\.\d+)?$'
            AND value::float < 3
          ORDER BY value::float));
```

**Comment by ValWood** [comment]
OK the one which was  baffling me  0.054 s now gone ! it is a control there is another assay with this allele  9.7% with different conditions .  

I fixed some like "normal sporulation 2% when it should have been abnormal sporulation 98% to make sense in queries!).

the others are actually very low penetrance phenotypes. Never occur in WT but occur  at a very low % in mutants (usually chromosome separation or septum positioning phenotypes)

**Comment by kimrutherford** [comment]
> OK the one which was baffling me 0.054 s now gone !

Did you remove it from the session?

**Comment by ValWood** [comment]
yes.
