### ISSUE TITLE
report ALL alleles which do not prefix with a gene name or synonym

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#927]
Follow on from
https://github.com/pombase/pombase-chado/issues/617

This will identify things like
https://user-images.githubusercontent.com/7359272/150784923-1a9e2e25-201f-419f-a370-71e8fdcb01f7.png

(Eventually we will also exclude those where the prefix matches an allele synonym, but at  there are some of thee that I want to update first).

I will prioritise these for fixing so that they look sensible in the pombemine queries.

**Comment by kimrutherford** [comment]
I've renamed the existing log ending with `.allele_names_not_starting_with_gene_name` to have the ending `.mutation_allele_names_not_starting_with_gene_name`, for clarity, from tomorrow.

And from tomorrow the `.allele_names_not_starting_with_gene_name` log will contain all alleles that where the name doesn't start with the gene name (assuming the gene and allele are both named).  Checking the allele synonyms too will take more thought.

**Comment by kimrutherford** [comment]
>  Checking the allele synonyms too will take more thought.

Sorry, I think I meant gene synonyms not allele synonyms.

The new log file is there this morning: https://curation.pombase.org/dumps/builds/pombase-build-2022-01-26/logs/log.2022-01-26-21-30-36.chado_checks.allele_names_not_starting_with_gene_name
