### ISSUE TITLE
Automagically update antisense RNA names to refer to gene symbols

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#928]
Exisiting RNAs identified as antisense  (before the Atkinson data was imported)

had identifiers, but we also name them in a standard way:

SPNCRNA.1005
SPAC1093.05-antisense-1

or dhc1-antisense-1 if the gene is named.

A lot of these should be updated
for example
SPAC1093.05-antisense-1 -> hca4-antisense-1 

(although the original  identifier name should remain as a synonym)

**Comment by kimrutherford** [comment]
The are a lot "antisense" IDs stored in `/obsolete_name` qualifiers.  Are those the ones you mean?  The obsolete names are stored in Chado as obsolete synonyms.  They aren't shown on the web site.

```
FT   ncRNA           complement(4619539..4621625)
FT                   /db_xref="PMID:29914874"
FT                   /db_xref="PMID:21511999"
FT                   /systematic_id="SPNCRNA.1005"
FT                   /product="non-coding RNA"
FT                   /obsolete_name="SPAC1093.05-antisense-1"
```

**Comment by ValWood** [comment]
yes, this is now out of date...
