### ISSUE TITLE
check separators in with/from field

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#929]
Learning intermine with  Rach today, I spotted this:

<img width="296" alt="Screenshot 2022-01-28 at 11 08 38" src="https://user-images.githubusercontent.com/7359272/151613125-a3a2d24e-57c4-4cd9-b980-a5519bb74e7f.png">

GO IDs are only used in the "with/from" field with evidence code IC.
When two GO IDs are used, this (should!) mean that the GO term combination is required to infer the annotated terem. In this case, the separator should always be a comma (compound) and never a "|" (independent annotations).

**Comment by kimrutherford** [comment]
Which gene was this?  I can't find any "|" separated GO IDs in Chado.

**Comment by ValWood** [comment]
Here are some examples:



IC | GO:0005783,GO:0016020 | SPAC1851.02
-- | -- | --
IC | GO:0005783,GO:0016020 | SPAC19G12.08
IC | GO:0005783,GO:0016020 | SPAC22A12.10
IC | GO:0005783,GO:0016020 | SPAC25B8.01
IC | GO:0005783,GO:0016020 | SPAC30D11.11
IC | GO:0005783,GO:0016020 | SPAC328.07c
IC | GO:0005783,GO:0016020 | SPAC8F11.06
IC | GO:0005783,GO:0016020 | SPBC16A3.10
IC | GO:0005783,GO:0016021 | SPAC23A1.05
IC | GO:0005783,GO:0016021 | SPAC607.09c

**Comment by ValWood** [comment]
Ignoe,comma iscorrect. I'll find the pipes!

**Comment by ValWood** [comment]
IC | GO:0003677\|GO:0005739 | SPAC13F5.01c
-- | -- | --
IC | GO:0003677\|GO:0005739 | SPAC25G10.02
IC | GO:0003677\|GO:0005739 | SPAC688.10
IC | GO:0003677\|GO:0005739 | SPBC887.14c
IC | GO:0003677\|GO:0005739 | SPMIT.02
IC | GO:0003677\|GO:0005739 | SPMIT.03
IC | GO:0003677\|GO:0005739 | SPMIT.06
IC | GO:0003756\|GO:0005788 | SPAC13F5.05
IC | GO:0004100\|GO:0000935 | SPBC1709.01
IC | GO:0005783\|GO:0016021 | SPAC23A1.02c

**Comment by ValWood** [comment]
In our display it is a comma separator.If it's always a comma in the XML I'll open a pombemine ticket

**Comment by kimrutherford** [comment]
As I understand it, they read the GAF file.  They are comma separated there.  
For example, here's the GAF line for "IC   GO:0003677|GO:0005739 SPAC13F5.01c":

```
PomBase     SPAC13F5.01c    msh1            GO:0000262      GO_REF:0000111  IC      GO:0003677,GO:0005739   C       mitochondrial MutS protein Msh1 SPAC23C11.18c   protein taxon:4896   20190128 PomBase
```

**Comment by ValWood** [comment]
OK. Odd that  in pombemine some are commas and some are pipes...

**Comment by ValWood** [comment]
https://github.com/intermine/pombemine/issues/25
