### ISSUE TITLE
allele_names_not_starting_with_gene_name

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#932]
I am currently working through this file:

https://curation.pombase.org/dumps/latest_build/logs/log.2022-02-01-21-50-32.chado_checks.allele_names_not_starting_with_gene_name

There is a lot to fix.
I would like to reduce the file size to make it easier by also ignoring
alleles which have a prefix which is a synonym of the gene, which are also valid. Thios will likely remove most and make checking eaier- there are still a lot.

I could just ignore them,  and fix the ones which clearly have no name as the prefix 9which is what I am doing right now). However, I have spotted
quit e lot where the allele is assigned to the wrong gene!

For example
 gtr1-S17L	gtr2	SPCC777.05	dd1b44baa214d190
 rad1-R179E	rad21	SPCC338.17c	8ba2dcc4ee76f79b 
 moa1-deltaN	moe1	SPAC637.07	333ca30ce9c2eb22 

pol3-C1041A	cdc1	SPAC27E2.05	44ae5ece389a1b0a XXXXXXXXXXXXX pol3 is cdc6 not cdc1
  pol3-C1051A	cdc1	SPAC27E2.05	44ae5ece389a1b0a
  pol3-C1056A	cdc1	SPAC27E2.05	44ae5ece389a1b0a
  pol3-C1056S	cdc1	SPAC27E2.05	44ae5ece389a1b0a
  pol3-T2	cdc6	SPBC336.04	44ae5ece389a1b0a
  pol3-C1038A	cdc6	SPBC336.04	44ae5ece389a1b0a
 tea2-1	tea1	SPCC1223.06	66b7ec899d565a8b,88f668cbb0dd4816 XXXXXXXXX
  rpa51delta::ura4+	rpa49	SPAC2F3.03c	6cdebcc5bb8f2240

These are  name mix-ups or typos.
I am only spotting these by chance because they look like they *could* be synonyms.
Filtering the synonyms will leave only the bon fida errors

**Comment by ValWood** [comment]
I fixed 90 yesterday only doing it for a couple of hours, so should not take to long to get through without the synonyms.

**Comment by kimrutherford** [comment]
> I would like to reduce the file size to make it easier by also ignoring alleles which have a prefix which is a synonym of the gene, which are also valid. 

I've done that.  I couldn't do work out how to do it with SQL so I used Perl.  Because of the current implementation of these check the `.chado_checks.allele_names_not_starting_with_gene_name` log file will be gone in the morning and these allele name warnings will be in the `.chado_checks` file instead.

There is also a `.mutation_allele_names_not_starting_with_gene_name` file which is a subset of the `.allele_names_not_starting_with_gene_name` log file.  I think we should remove it.

**Comment by ValWood** [comment]
> I've done that.

Cool, I fixed about 110 of them in the past couple of days.
This reduction brings the file down to 365 which is not quite so daunting. This is a really great QC check- I am finding/fixing lots of problems.

>I think we should remove it.
Yep, no redundancy. ;)

**Comment by ValWood** [comment]
110 more in the past couple of days- I already did ~100 the day before.
The file I am working with had

Check for allele names that don't start with the gene name - CHECK FAILURE:  expected 0 but got 1141

I want to clean these so that they look sensible in Intermine (will also be useful for the micropublication entity recognition purposes.

**Comment by kimrutherford** [comment]
> There is also a .mutation_allele_names_not_starting_with_gene_name file which is a subset of the .allele_names_not_starting_with_gene_name log file. I think we should remove it.

I've removed it.
