### ISSUE TITLE
multiple representation of deletion alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#933]
Sometimes a deletion allele is named from a previous gene name:

bob1delta	pfd5	SPBC215.02	411b08353c057dbf,9a84ff9ab5f5d661

So we have a situation where we get 2 deletion alleles pages for a single gene:
https://www.pombase.org/genotype/pfd5delta
https://www.pombase.org/genotype/bob1delta

Old alleles  deletion alleles should be renamed to the new name (provided there is no other data, comments, background  or notes which imply the allele behaviour would  not be identical.

The old name should be retained as a synonym.

**Comment by kimrutherford** [comment]
> provided there is no other data, comments, background or notes which imply the allele behaviour would not be identical.

What sort of things should the code check for?  Just the existence of any an allele comment, a background or note?

**Comment by ValWood** [comment]
there might not be so many of these.Maybe as a first pass we just get a list of deletion alleles which don't have the current name.

**Comment by kimrutherford** [comment]
> Maybe as a first pass we just get a list of deletion alleles which don't have the current name.

They should be in this log file: https://curation.pombase.org/dumps/builds/pombase-build-2022-02-02/logs/log.2022-02-03-03-12-09.chado_checks.allele_names_not_starting_with_gene_name

**Comment by ValWood** [comment]
OK I can check from this file that the deletion alleles are sensible to auto-repair
