### ISSUE TITLE
log file allele_names_not_starting_with_gene_name disappeared

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#936]
I no longer see this log

  | log.2022-01-17-21-31-40.chado_checks.allele_names_not_starting_with_gene_name

(it's the big one I am working on)

**Comment by kimrutherford** [comment]
Those warnings have moved to the file ending with `.chado_checks`: https://github.com/pombase/pombase-chado/issues/932#issuecomment-1029508983

**Comment by ValWood** [comment]
I forgot. I was still looking for files with 'allele ' in the name. brain like a seive.
