### ISSUE TITLE
bulk change PMID:16537923

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#938]
All
GO:0001228 | DNA-binding transcription activator activity, RNA polymerase II-specific
in  PMID:16537923
need extension 
happens_during  GO:0071456 cellular response to hypoxia

I started to do it manually, but there are 97.
Because the session is so big it takes a long time for the extension pop up. to arrive so each one takes  ~27 seconds.

(or if canto pop-up were faster that would also work )

**Comment by kimrutherford** [comment]
That's done now.

**Comment by ValWood** [comment]
Thanks, I went in to do the edits with speeded upCanto and you already did them automagically. Thank you!

But it is very much faster loading big sessions!
