### ISSUE TITLE
difference between Thodburg data in browser and files for UTR. update

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#939]
I had curated the TSS for pof13 as:

I spotted a potential problem. I was looking at pof13
TSS in the browser.

In art I used the major TSS from the prepared files:
254.839000

<img width="182" alt="pof13_in_art" src="https://user-images.githubusercontent.com/7359272/153586092-1c76e907-0a47-459b-8d10-8ac8f390c8d4.png">

I could not see this TSS in the browser:
<img width="254" alt="pof13_in_browser" src="https://user-images.githubusercontent.com/7359272/153586196-5d2142a1-95e8-4348-812c-a0a5c93b6d17.png">

The chrr2 TSS's are a bit weird.
I have 3 files binning high medium and low scores
i.e.
chr2_GSE110976_EMM_exp-0.5.gff
chr2_GSE110976_EMM_exp-5.gff
chr2_GSE110976_EMM_exp-50.gff

~sometimes there is a really high scoring TSS in the low scoring file. I 
never saw this on chr1. I will provide an example next time I see it.
I will also check the next few against the browser data. Any I looked at previously looked fine...~

**Comment by ValWood** [comment]
more examples:

eg1
<img width="883" alt="eg1" src="https://user-images.githubusercontent.com/7359272/154478042-effc3cc9-1043-4a7c-9a43-21b7fe8bd658.png">

the highest scoring TSS (19664.800000) is in the lowest scoring bin

**Comment by ValWood** [comment]
eg3 cys1
<img width="914" alt="eg3 cys2 ii" src="https://user-images.githubusercontent.com/7359272/154478702-d07bfc77-97e9-442b-9ae4-e79793c9f7b2.png">

high scoring peak present on correct strand, but in low scoring bin

the same high scoring peak is present in the wrong strand (but in the medium scoring bin)
<img width="1098" alt="eg3 cys2 i" src="https://user-images.githubusercontent.com/7359272/154478834-0ffa123b-7de0-4a1d-be1d-52cb116130c1.png">

In the browser it is correct:
<img width="701" alt="eg3 cys2 browser" src="https://user-images.githubusercontent.com/7359272/154478992-682b4aa0-f919-425f-ab44-0dba8420d02e.png">

**Comment by ValWood** [comment]
the files are called
chr2_GSE110976_EMM_exp-0.5.gff
chr2_GSE110976_EMM_exp-5.gff
chr2_GSE110976_EMM_exp-50.gff

Note that I did not see these issues with chromosome 1 and I didn't look at chr3 yet.....

**Comment by kimrutherford** [comment]
> the highest scoring TSS (19664.800000) is in the lowest scoring bin

I think that's expected.  The three files have different score cut offs, they aren't bins.  High scoring features will be in all three files.

> the same high scoring peak is present in the wrong strand

That seems like a bug.  I'm checking now to see if it's in the original file or it was caused by my Perl code.

**Comment by kimrutherford** [comment]
> The three files have different score cut offs, they aren't bins. High scoring features will be in all three files.

I need to recreate the files to fix the strand bug so I could make them bins at the same time if you like.

**Comment by ValWood** [comment]
done & used
