### ISSUE TITLE
New relations required to describe modifications

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#941]
Need to be enabled in Chado, Canto and added to this documentation:
https://www.pombase.org/documentation/modification-data-bulk-upload-format

decreased_during
identifies a biological process or cell cycle phase during which the modification is actively increased

increased_during
identifies a biological process or cell cycle phase during which the modification is actively deceased

The following extension is a bit of a fudge.  We haven't needed it before because we have been looking at mutants of the studied kinase. This paper is more complex. The mutant is used to switch off one of the 'feed in' pathways so the contribution from the pathway of interest can be more accurately assessed.
It's slightly different from the other types of extension, and  we might eventually want to capture this a different way.

in_absence_of(gene ID)
         Used to indicate  attenuation of the activity of a specific gene product
         (either by deletion or inactivation). This extension must be connected
         to another extension describing the modification.

**Comment by ValWood** [comment]
fix typo
https://www.pombase.org/documentation/modification-data-bulk-upload-format
removed_by | identifies a gene product that removes the modification | added_by(PomBase:SPAC24H6.05)

(I realise this ticket should be separate tickets on multiple tackers but it can migrate)

**Comment by kimrutherford** [comment]
> decreased_during
> increased_during

Those two extension relations are already available in Canto and allowed in Chado:
  - https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/PSI-MOD_A_E_config
  - https://github.com/pombase/pombase-legacy/blob/master/load-pombase-chado.yaml#L241

I've added `in_absence_of` to Canto and to the Chado config but I don't understand this bit:
"This extension must be connected to another extension describing the modification."

**Comment by kimrutherford** [comment]
What should we put in the "Meaning" column for the new relation?:
https://www.pombase.org/documentation/modification-data-bulk-upload-format

I also noticed that `in_presence_of` is allowed in Chado but isn't documented and isn't allowed in Canto.  Should we document it or remove it?

**Comment by ValWood** [comment]
>Those two extension relations are already available in Canto and allowed in Chado:

OK, I think they are only currently configured for expression data though?

>I've added in_absence_of to Canto and to the Chado config but I don't understand this bit:
"This extension must be connected to another extension describing the modification."

This means that it needs to be combined with another term containing an "actual" relation. 

i.e. increased_during(blah),in_absence_of(blah)

this is because this 'relation' is describing a totally orthogonal feature (it isn't a relationship describing the modification itself)

so, you could not use only "in_absence_of(blah)" with no other extension at all.
It can only be used in a 'compound annotation'. I don't think we should allow this one in Canto, it's a real 'edge case' . I can check the usage in the htp datasets.

Note, I couldn't think of another way to do this because it would be impossible to make compound relations. Also "increased_in_absence_of(blah) would not be quite correct. The absence of blah is more like a 'background'. It isn't causing the increase
in this case, its removing some of the background 'noise' to reveal the contribution of the pathways of interest. It's complicated and we might never use it again!

**Comment by ValWood** [comment]
> What should we put in the "Meaning" column for the new relation?:
https://www.pombase.org/documentation/modification-data-bulk-upload-format

This relation is used to indicate attenuation of the activity of a specific gene product
(either by deletion or inactivation). This extension must be ~connected
to another~ used with an additional  extension describing the modification.

> I also noticed that in_presence_of is allowed in Chado but isn't documented and isn't allowed in Canto. Should we document it or remove it?

If it isn't used anywhere I think we can remove it.

**Comment by kimrutherford** [comment]
> I think they are only currently configured for expression data though?

They're in this list.  Am I missing something?

![mod-ext-1](https://user-images.githubusercontent.com/90474/155283145-50883abd-0c2b-4107-ba37-8427e50381c7.png)

**Comment by kimrutherford** [comment]
> This relation is used to indicate attenuation of the activity of a specific gene product

Thanks.  I've updated the docs and it will be on the site tomorrow morning.

**Comment by ValWood** [comment]
>They're in this list. Am I missing something?

OK! I was referring to this page because  it was htp data. 
https://www.pombase.org/documentation/modification-data-bulk-upload-formatI didn't think to check Canto ;)

I didn't rreilise the documentation was out of synch.

**Comment by kimrutherford** [comment]
I can add those two relations to the docs if you could suggest something to put in the "Meaning" column.

**Comment by ValWood** [comment]
decreased_during
identifies a biological process or cell cycle phase during which the modification is actively increased

increased_during
identifies a biological process or cell cycle phase during which the modification is actively deceased

**Comment by kimrutherford** [comment]
Thanks.  I've added docs for decreased_during() and increased_during().  The change will be on the main site in the morning.

I think this is all done now.
