### ISSUE TITLE
Include ECO ID in pombemine export file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#942]
I thought we had a ticket about this but I can't find it...

@RachelLyne

**Comment by kimrutherford** [comment]
The file we export for PombeMine doesn't contain any annotation so there is nowhere to attach the ECO IDs there.  I believe PombeMine reads the GAF and PHAF files, which don't have ECO IDs.  We could create PombeMine-specific GAF and PHAF file each night containing the ECO IDs but then the normal evidence codes wouldn't be available.  I don't know what the best solution is.

**Comment by kimrutherford** [comment]
Here is the GO/PHAF to ECO mapping TSV file in case that's useful: [ECO_evidence_mapping.txt](https://github.com/pombase/pombase-chado/files/8121247/ECO_evidence_mapping.txt)

**Comment by ValWood** [comment]
The mapping file might do it !
@rachellyne

**Comment by kimrutherford** [comment]
Can we close this?
