### ISSUE TITLE
Gene Name for Intermine

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#943]
Export  “gene name”  for PombeMine as 
i) gene symbol if present 
OR
ii) systematic ID and if not present as 

@rachellyne

**Comment by kimrutherford** [comment]
All gene names and systematic IDs are in the JSON file.

**Comment by ValWood** [comment]
I think a new field "gene name " is required to load into the gene name column. This will have the primary name if present and the systematic ID if not.

@rachelline is this something that is easy for daniella to do during the loading?

**Comment by kimrutherford** [comment]
OK, thanks.  It's easy enough to add a field with name / systematic ID like that.  I just need a name for it.

Currently each gene has a "name" field, so something different to that would be good.

**Comment by ValWood** [comment]
I think Intermine call this "gene name” (it is essentially what  we put in the GO GAF 


3 | DB Object Symbol
which is also a mixture of "symbol" and "systematic ID"

**Comment by kimrutherford** [comment]
It sounds like Daniela fixed this at the InterMine end:

```
Hi Val, Kim,

I have changed the code to set the Allele's name, symbol and primary 
identifier(suffix description removed) using the allele name provided in 
the phaf file.
Let me know when I can run another build.
cheers,

Daniela
```
