### ISSUE TITLE
Export publications attached to genes

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#944]
Please export all genes with publications that are attached to them for any annotation type (GO, FYPO, MOD, expression etc).

This is currently not pop[ulated in Intermine because publications are not attached automatically y to genes. Exporting all will ensure that we don't miss any.

@rachellyne

**Comment by kimrutherford** [comment]
> Exporting all will ensure that we don't miss any.

I'll add a references section to each gene but it seems redundant.

> Exporting all will ensure that we don't miss any.

Every line in the GAF and PHAF files has a reference for that annotation.  Why would any be missed?

**Comment by kimrutherford** [comment]
> I'll add a references section to each gene

That's done.  It's documented here: https://github.com/pombase/pombase-chado/wiki/InterMine-data-files

**Comment by ValWood** [comment]
>Every line in the GAF and PHAF files has a reference for that annotation. Why would any be missed?

we also have "pombase publication" which have annotations which are not GO, MOD or FYPO  (warnings, expression browser tracks etc).
I also sometimes link reviews to genes in Canto.
