### ISSUE TITLE
export feature type "protein"

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#945]
For all mRNA features

**Comment by ValWood** [comment]
@rachllyne

**Comment by kimrutherford** [comment]
Sorry, I don't understand.  Which file does this go in?

**Comment by kimrutherford** [comment]
The JSON file we export has a `protein` section for each coding gene.  Is more needed?

The protein sections look like:

```json
 "protein": {
   "uniquename": "SPAC1002.01.1:pep",
   "sequence": "MLPPTIRISGLAKTLHIPSRSPLQALKGSFILLNKRKFHYSPFILQEKVQSSNHTIRSDTKLWKRLLK...*",
   "product": "mitochondrial expression network (MIOREX) component Mrx11",
   "molecular_weight": 20.2386,
   "average_residue_weight": 0.11243,
   "charge_at_ph7": 14.9,
   "isoelectric_point": 10.77,
   "codon_adaptation_index": 0.57
 }
```

**Comment by ValWood** [comment]
Hi @rachellyne, I think what probably needs to happen is that some connection is made between the gene and the protein ID so that we can access protein features from gene?
