### ISSUE TITLE
Suggestion for legacy phenotypes/alleles 

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#948]
So, I  am pretty sure that all of the alleles  with no name or description are in Artemis.
What if we

- [ ] 1. Do the same as we have done for  legacy GO data and move into a flat file (gets rid of another chunk of data to maintain in Artemis. Since most updates to these data involve deletion, maintaining in a flat-file is much easier.

- [ ] 2. Check that the alleles from Artemis with no name or description are all from sessions that have not been through Canto yet (if any have been through Canto , possibly the legacy annotation was overlooked, I will update the session or delete as necessary

- [ ] 3. Once 2 is done, and I am happy that the legacy annotation **_WITHOUT ALLELE NAMES_** is from sessions that have not been curated,  put these annotations in a separate file, linked to this ticket:
- https://github.com/pombase/curation/issues/3146
(it should actually be almost the same content as the files in alrredy there), and remove them from the "legacy PHAF file".
This data does not need to be loaded into PomBase - the were made by me and Jacky to compare to the cell cycle viability and morphology phenotypes. They were all subsequently recovered by the  deletion project. I think this is better practice than having phenotypes floating around that are not attached to alleles.

These papers will be among the next bunch of legacy papers curated so they will appear back as fully formed annotations fairly soon, hopefully.

**Comment by kimrutherford** [comment]
I slightly forgot what we decided to do here because I went straight into chatting with James after our Skype on Friday.  But I think the plan was to add more detail to the unnamed, unrecorded log file as a first step.  I've changed the query, hopefully in time for the load.  It's the log file that ends with `.chado_checks.unnamed_unrecorded_alleles`

I've added the gene name and a column with the PMID of the annotation from the contig file and the session ID of that PMID, if there is one.

Here's what it looks like from the Chado from the 24th: [unnamed_unrecored_alleles.tsv.txt](https://github.com/pombase/pombase-chado/files/8149811/unnamed_unrecored_alleles.tsv.txt)

**Comment by ValWood** [comment]
Right, so some of the papers are already through  to Canto.
I will add to canto  and  delete from contigs phenotypes all of the ones from those sessions, as appropriate. Then you can continue.

**Comment by ValWood** [comment]
I removed all of the ones that are in the sessions. That was  a  useful exercise, it confirmed that most if not all will be recovered  via other publications.

YOu can move to the next step|(s)

**Comment by ValWood** [comment]
Hi Kim,
I forgot to put "next" on this. I am doing that now. Can you prioritise the next steps (when feasible) because I need to check that all of the phenotypes/alleles look OK in Intermie after the next load.

**Comment by kimrutherford** [comment]
So is the summary that I need to move the phenotype annotation from the contig files into a PHAF file?

**Comment by kimrutherford** [comment]
Some of the phenotype annotations in the contigs have no date but it's a required field in PHAF files.  Is there a date we can put in the PHAF file for those cases?

**Comment by kimrutherford** [comment]
I've made these changes:

- Added the phenotype annotations from the contig files to a new PHAF file in SVN:
    `pombe-embl/supporting_files/legacy_phenotype_annotations_from_contigs.phaf.tsv`
- Removed the annotations from the contig files.
- Changed the load script to load the annotations from the PHAF file (https://github.com/pombase/pombase-legacy/commit/74fc809292e6090461208de0cbf72b40edc6126b)

I'm doing a local test load now.  When it's done I'll compare the Chado database from before and after to make sure we're getting the same annotation.

>  Is there a date we can put in the PHAF file for those cases?

For testing the loading I put in a dummy date (1999-09-09).

**Comment by ValWood** [comment]
Dummy date is fine. Once this is done, we will not load any phenotypes which do not have an allele description.

**Comment by kimrutherford** [comment]
I moved the annotations using unnamed alleles into a separate file before the load started:
`pombe-embl/supporting_files/unnamed_legacy_phenotype_annotations_from_contigs.phaf.tsv`

What's the next step?

**Comment by kimrutherford** [comment]
> I moved the annotations using unnamed alleles into a separate file before the load started

Everything worked so the website now has the phenotype annotations from the legacy phenotypes file and there are now no phenotype annotations in the contig files.

**Comment by ValWood** [comment]
We. can close this and new tickets for anything else but that should be all.
