### ISSUE TITLE
interMine export URLs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#949]
Supply URLs for PomBase data sources.
<img width="1081" alt="Screenshot 2022-02-24 at 15 52 43" src="https://user-images.githubusercontent.com/7359272/155562102-a0c129af-916b-4549-8857-5183ae4e6578.png">

for these
PomBase phenotypes https://www.pombase.org/downloads/phenotype-annotations
GO data. https://www.pombase.org/downloads/go-annotations
cerevisiae orthologs  https://www.pombase.org/data/orthologs/

also add
Modification https://www.pombase.org/data/annotations/modifications/
human orthologs https://www.pombase.org/data/orthologs/
others?

@rachellyne should this be in the json export? If so what should the label/ format be

**Comment by kimrutherford** [comment]
> should this be in the json export? If so what should the label/ format be

That sounds like something for a configuration file rather than the JSON export.

**Comment by rachellyne** [comment]
For humanmine and flymine we configure an XML file which has all the dataset data.  I update it manually for each build which is ok for flymine and humanmine as we only update quarterly.  It would be nice to find a more automated way to update it. (we have data versions in it which is the main thing that needs updating each time).

**Comment by ValWood** [comment]
Right, updating manually would be a faff. Presumably it is relatively simple to automatically populate a config file. Which resources will need versioning info?
UniProt
BioGRID
InterPro
I supplied URLs for PomBase but these would be incorrect. We presumably need to link to the data in builds
https://curation.pombase.org/dumps/builds/ and ensure that the updates relate to an archived build.
@kimrutherford  would that make sense.

**Comment by kimrutherford** [comment]
> We presumably need to link to the data in builds
> https://curation.pombase.org/dumps/builds/ and ensure that the updates relate to an archived build.

Everything in the builds directory is temporary.
If we link from PombeMine it should probably be to files in the releases directory:
https://www.pombase.org/releases/

I think a quick fix for now is to link to www.pombase.org for the datasets from PomBase.
