### ISSUE TITLE
recent additions to legacy GO data file not showing up

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#950]
These  GO annotations do not seem to be appearing, but I don't see anything in the log files.

- [ ] PomBase	SPBC32H8.03			GO:0008474 	GO_REF:0000024	ISO	MGI:MGI:1916154	F	XXXXX		protein	taxon:4896	20220219	PomBase	
- [x] PomBase	SPAC26H5.11			GO:0043495	GO_REF:0000024	ISO	SGD:S000001303	F	XXXXX		protein	taxon:4896	20220214	PomBase		has_input(PomBase:SPAC110.03),part_of(GO:0032120)
- [x] PomBase	SPAC26H5.11			GO:0032120	GO_REF:0000024	ISO	SGD:S000001303	F	XXXXX		protein	taxon:4896	20220214	PomBase

**Comment by ValWood** [comment]
excuse the XXXX for product line, I can't be bothered. to fill it in as it isn't used from here. It also keeps the rows shorter ;)

**Comment by kimrutherford** [comment]
Sorry, looks like there are a variety of problems.  The first one is that I made a typo in the load script so most of the errors and warnings from loading the legacy file aren't going into the log file.  I'll fix that now for tonight's load.

The second problem is that some of the new GO IDs have a space after them, followed by the tab.  The loader to currently too dumb to cope with that.  I'll fix that too.

I don't why the two GO:0032120 lines aren't loading.  Still working on that.

Some of the columns are out of wack in the file because the tabs are in the wrong place.  You'll see the problems if you load the file into Excel.  Could you have a look?

Here are the current log messages.  Some of them aren't very good, no line number or not enough detail.  I'll improve the code on Monday.

```
can't load annotation, GO:0043486  not found in database
can't load annotation, GO:0043486  not found in database
can't load annotation, GO:0043486  not found in database
can't load annotation, GO:0043486  not found in database
can't load annotation, GO:0043486  not found in database
can't load annotation, GO:0008474  not found in database
Taxon missing - skipping
Taxon is not a number: protein - skipping
Failed to load row: {UNKNOWN}: annotation extension qualifier on SPAC18G6.03.1 not understood: PomBase at lib/PomBase/Import/GeneAssociationFile.pm line 485

Taxon missing - skipping
Failed to load row: {UNKNOWN}: annotation extension qualifier on SPAC167.02.1 not understood: PomBase at lib/PomBase/Import/GeneAssociationFile.pm line 485

Failed to load row: {UNKNOWN}: annotation extension qualifier on SPAC25H1.02.1 not understood: PomBase at lib/PomBase/Import/GeneAssociationFile.pm line 485

Failed to load row: {UNKNOWN}: annotation extension qualifier on SPAC1006.02.1 not understood: PomBase at lib/PomBase/Import/GeneAssociationFile.pm line 485
```

**Comment by kimrutherford** [comment]
> I don't why the two GO:0032120 lines aren't loading. Still working on that.

False alarm.  Those two lines are fine, both they are identical so only one is loaded:
https://www.pombase.org/gene/SPAC26H5.11

**Comment by ValWood** [comment]
No prob , I'll load into VS code and fix what I can

**Comment by ValWood** [comment]
I think I have fixed the above errors and the formatting problems.

Could you do me a huge favour and swap ALL of the product lines forr XXXX.
I don't need these here, It will make the file much earlier to manage. At the moment it is line wrapping for most lines on my laptop at full screen width which makes it really difficult to check that the columns align (especially with the "PomBase" at the beginning and the end. A number of lines had been inappropriately appended to the previous line, or split.

**Comment by kimrutherford** [comment]
> The first one is that I made a typo in the load script so most of the errors and warnings from loading the legacy file aren't going into the log file. I'll fix that now for tonight's load.

Sorry, I forgot to commit the fix.  I've done that now and I'll check on Sunday or Monday.

**Comment by kimrutherford** [comment]
> Could you do me a huge favour and swap ALL of the product lines forr XXXX.

Done!

At the same time I removed this truncated line:
```
pfh1        protein      taxon:4896    20040625     PomBase
```

And there was a line missing a newline which I've fixed.

I'll check the log tomorrow or Monday.

**Comment by kimrutherford** [comment]
I've just fixed a missing close bracket at the end of this line too:
```
PomBase    SPAC26H5.11         GO:0043495  GO_REF:0000024  ISO SGD:S000001303  F   XXXX        protein taxon:4896  20220214    PomBase has_input(PomBase:SPAC110.03),part_of(GO:0032120
```

After that change the are no errors or warnings when I test loading on my desktop.  I'll still check the main load in the morning.

**Comment by ValWood** [comment]
Thank you,  much easier ;)

**Comment by kimrutherford** [comment]
> The second problem is that some of the new GO IDs have a space after them, followed by the tab. The loader to currently too dumb to cope with that. I'll fix that too.

I fixed it but forgot to commit the fix so there are still some warnings:
```
can't load annotation, GO:0034728  not found in database
can't load annotation, GO:0034728  not found in database
can't load annotation, GO:0034728  not found in database
can't load annotation, GO:0034728  not found in database
can't load annotation, GO:0034728  not found in database
can't load annotation, GO:0008474  not found in database
```

They should disappear on Tuesday morning.

**Comment by ValWood** [comment]
I think this is all sorted. I just fixed the remaining log issues.
