### ISSUE TITLE
Put Perl Chado check output in separate files

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#952]
Currently they all end up in one file which is quite messy.

https://curation.pombase.org/dumps/builds/pombase-build-2022-02-24/logs/log.2022-02-24-21-51-04.chado_checks

**Comment by kimrutherford** [comment]
This is done now so the different parts of the output in the .chado_checks file will be split into separate files from tomorrow.  For example the genotype background output will be in a file that ends with `.chado_checks.GenotypeBackgrounds`

**Comment by ValWood** [comment]
Thanks!
