### ISSUE TITLE
allele-synonyms-from-supporting-data

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#954]
I don't have enough info to fix this:
https://curation.pombase.org/dumps/latest_build/logs/log.2022-03-12-21-07-37.allele-synonyms-from-supporting-data
41HAclc1 

It looks like it should brer an allele of clc1, but I do not see such an allele on the clc1 page...

**Comment by kimrutherford** [comment]
It's complaining about lines 41 and 113 in pombe-embl/supporting_files/allele_synonyms.txt
Those two lines are all the information there is.

**Comment by ValWood** [comment]
I deleted them. Sorted. 
I think this is because I swapped primary names and synonyms in Canto and so these are no longer mapping to the original primary name.
