### ISSUE TITLE
log file legacy_go_from_contigs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#956]
https://curation.pombase.org/dumps/latest_build/logs/log.2022-03-12-21-07-37.legacy_go_from_contigs

ignoring "with" value containing a comma: PomBase:SPAC25B8.03,PomBase:SPAC31G5.15
ignoring "with" value containing a comma: PomBase:SPBC16E9.18,PomBase:SPAC31G5.15
ignoring "with" value containing a comma: PomBase:SPAC25B8.03,PomBase:SPBC16E9.18
ignoring "with" value containing a comma: GO:0003677,GO:0036003
ignoring "with" value containing a comma: GO:0005658,GO:0003896
ignoring "with" value containing a comma: GO:0005658,GO:0003896
ignoring "with" value containing a comma: GO:0005783,GO:0016020
ignoring "with" value containing a comma: GO:0005783,GO:0016020
ignoring "with" value containing a comma: GO:0005783,GO:0016020
ignoring "with" value containing a comma: GO:0005783,GO:0016020
ignoring "with" value containing a comma: GO:0005783,GO:0016020
ignoring "with" value containing a comma: GO:0016020,GO:0005783
ignoring "with" value containing a comma: GO:0005783,GO:0016020

I can fix the ones where genes are comma separated, but the GO IDs in the 'from filed'  with IC evidence code should be comma separated

**Comment by kimrutherford** [comment]
Sorry I misunderstood this.  I misread the GAF docs which doesn't help.  When (if ever?) should the loader warn about commas in the with/from column?

I was looking and the old documentation when I changed how this worked last week: http://geneontology.org/docs/go-annotation-file-gaf-format-2.0/#with-or-from-column-8
The GAF v2.2 docs are clearer about comma versus pipe.

I think I need to change the code to warn about pipes in the with/from field because they are not being stored as independent annotations.  Storing annotations with pipes correctly isn't a quick fix.

**Comment by ValWood** [comment]
Yep, if we use pipes in the 'with' field it would mean separate annotations (the same meaning as a pipe in an extension). However, we don't _need_ to use pipes, we could make separate annotations (and I think this is what we do, for example for protein binding with x, we would always make independent annotations). So I think it is  fine if we **don't** support pipes in the with field.

The 'from' field is used with IC, and here, the separator should always be a comma. This is because both terms in the 'from' field are required to make the inference.

For example, if a gene product is known to be a) a "membrane protein" and b) localizes to the ER, you need both  a & b simultaneously to make an inference to "ER membrane".
If IC is used correctly it should always have  2 GO IDs, comma separated.

**Comment by kimrutherford** [comment]
> So I think it is fine if we don't support pipes in the with field.

Thanks for clarifying.  The current code (as of last night) should warn if there's a pipe in the with/from field.  Unfortunately I managed to mangle the warning that it gives: https://curation.pombase.org/dumps/latest_build/logs/log.2022-03-13-23-24-51.legacy_go_from_contigs

I'll fix that for tonight's load and make sure it includes more details like the line number.

**Comment by kimrutherford** [comment]
It's looking better now: https://curation.pombase.org/dumps/latest_build/logs/log.2022-03-14-21-06-10.legacy_go_from_contigs

**Comment by ValWood** [comment]
Right so there are some GO IDs separated by  a pipe rather than a comma?

**Comment by ValWood** [comment]
I see they are. I tried it fix but my substitution did not work. I want to do this but I can't remember how to escape the comma (at least I think that is the problem)

's/|GO/,GO/g'

**Comment by kimrutherford** [comment]
Commas are OK in substitutions but pipes need escaping:

```
s/\|GO/,GO/g
```

**Comment by ValWood** [comment]
fixed thanks
