### ISSUE TITLE
annotations that refer to a secondary GO ID: 770 (from EBI syntax checker)

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#958]
Number of annotations that refer to a secondary GO ID: 770
	GO:0000728 (replaced by GO:0007534): 1
	GO:0000734 (replaced by GO:0007534): 1
	GO:0000780 (replaced by GO:0000779): 18
	GO:0000784 (replaced by GO:0000781): 1
	GO:0000788 (replaced by GO:0000786): 10
	GO:0000790 (replaced by GO:0000785): 526
	GO:0000799 (replaced by GO:0000796): 12
	GO:0004724 (replaced by GO:0004722): 1
	GO:0005086 (replaced by GO:0005085): 4
	GO:0005087 (replaced by GO:0005085): 2
	GO:0005088 (replaced by GO:0005085): 2
	GO:0005089 (replaced by GO:0005085): 14
	GO:0005719 (replaced by GO:0000791): 9
	GO:0005720 (replaced by GO:0000792): 32
	GO:0006151 (replaced by GO:0009115): 1
	GO:0008536 (replaced by GO:0031267): 6
	GO:0017048 (replaced by GO:0031267): 1
	GO:0017091 (replaced by GO:0035925): 1
	GO:0017112 (replaced by GO:0005085): 5
	GO:0017137 (replaced by GO:0031267): 6
	GO:0031292 (replaced by GO:0007534): 3
	GO:0031618 (replaced by GO:0005721): 55
	GO:0034636 (replaced by GO:0007534): 1
	GO:0052824 (replaced by GO:0052917): 1
	GO:0060733 (replaced by GO:0140469): 1
	GO:0061500 (replaced by GO:0007534): 1
	GO:1902377 (replaced by GO:0033553): 12
	GO:1904834 (replaced by GO:0061638): 4
	GO:1905121 (replaced by GO:0000022): 2
	GO:1905185 (replaced by GO:1990942): 2
	GO:1990707 (replaced by GO:0099115): 35

**Comment by ValWood** [comment]
Do these get fixed automatically?

**Comment by ValWood** [comment]
Also these
Number of annotations that refer to an obsolete GO ID: 10
	GO:0036207 (no replacement term defined): 1
	GO:0044397 (replaced by GO:0006897): 2
	GO:0045155 (no replacement term defined): 1
	GO:1904162 (no replacement term defined): 1
	GO:1904499 (no replacement term defined): 1
	GO:1990847 (no replacement term defined): 4

but I have no reports of this?

**Comment by ValWood** [comment]
Number of annotations with problematic extension: 203
	Incorrect syntax: 2
	Invalid domain for has_input: 3
	Invalid domain for has_participant: 1
	Invalid domain for occurs_in: 1
	Invalid domain for results_in_development_of: 5
	Invalid range for coincident_with: 8
	Invalid range for exists_during: 1
	Invalid range for has_input: 14
	Invalid range for occurs_in: 163
	Invalid range for part_of: 1
	String index out of range: 2
	Unknown/unsupported relation: 2

**Comment by kimrutherford** [comment]
Which file did you check?

**Comment by ValWood** [comment]
I can't see anything in our logs, is it there?

**Comment by kimrutherford** [comment]
> I can't see anything in our logs, is it there?

Is what there?  I don't understand where the EBI check message are from.  I didn't know it existed.

**Comment by ValWood** [comment]
I think we might be able to ignore some of these. If we fix IDs these are possibly to do with the time lag....because EBI will get the data from GO.  I think I remem ber Midori saying most of these warnings could be ignored.    Let's do nothing and I'll see what the next one looks like...
