### ISSUE TITLE
modified form warnings

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#959]
lots:
https://curation.pombase.org/dumps/latest_build/logs/log.2022-03-29-22-06-12.curation-tool-data-load-output

did I stuff up the modification ontology?

warning in f30149c5fcc7f553: modified_form() not allowed for molecular_function, annotation: SPAC17G8.10c.1 <-> protein binding
warning in f30149c5fcc7f553: modified_form() not allowed for molecular_function, annotation: SPBC244.01c.1 <-> protein binding
warning in de3fe5786898e2f8: modified_form() not allowed for cellular_component, annotation: SPCC4B3.15.1 <-> nucleus
warning in de3fe5786898e2f8: modified_form() not allowed for cellular_component, annotation: SPCC4B3.15.1 <-> medial cortical node
warning in de3fe5786898e2f8: modified_form() not allowed for cellular_component, annotation: SPCC4B3.15.1 <-> mitotic actomyosin contractile ring
warning in de3fe5786898e2f8: modified_form() not allowed for molecular_function, annotation: SPCC4B3.15.1 <-> protein binding
warning in de3fe5786898e2f8: modified_form() not allowed for molecular_function, annotation: SPCC4B3.15.1 <-> protein binding
warning in 31b52625e666e444: modified_form() not allowed for molecular_function, annotation: SPBC776.02c.1 <-> protein serine/threonine phosphatase activity
warning in 260532ed016fea91: modified_form() not allowed for molecular_function, annotation: SPAC1D4.13.1 <-> MAP kinase kinase activity
warning in 260532ed016fea91: modified_form() not allowed for molecular_function, annotation: SPAC31G5.09c.1 <-> MAP kinase activity
warning in a5f8ece090d3d081: modified_form() not allowed for biological_process, annotation: SPAC664.07c.1 <-> mitotic DNA replication checkpoint signaling
warning in 709eb266115f50d4: modified_form() not allowed for molecular_function, annotation: SPAC1565.06c.1 <-> signaling adaptor activity
warning in 709eb266115f50d4: modified_form() not allowed for molecular_function, annotation: SPAC1565.06c.1 <-> signaling adaptor activity
warning in 4927cddae28a3185: modified_form() not allowed for molecular_function, annotation: SPAC19E9.02.1 <-> protein serine/threonine kinase activity
warning in 28333b01f58bc586: modified_form() not allowed for molecular_function, annotation: SPBC4F6.12.1 <-> F-bar domain binding
warning in 1de58f8a4e93861a: modified_form() not allowed for molecular_function, annotation: SPAC20G8.05c.1 <-> cytoskeletal protein-membrane anchor activity
warning in d4e73d1a93ec5860: modified_form() not allowed for cellular_component, annotation: SPAC1834.04.1 <-> pericentric heterochromatin
warning in d4e73d1a93ec5860: modified_form() not allowed for cellular_component, annotation: SPBC8D2.04.1 <-> pericentric heterochromatin
warning in d4e73d1a93ec5860: modified_form() not allowed for cellular_component, annotation: SPBC1105.11c.1 <-> pericentric heterochromatin
warni

**Comment by ValWood** [comment]
It looks like it- all  'modified forms' seem to have disappeared....

**Comment by kimrutherford** [comment]
Sorry that's my fault.  I forgot to change the Chado load code to match the changes in https://github.com/pombase/canto/issues/2509

I'll do that now.

**Comment by kimrutherford** [comment]
> Sorry that's my fault. I forgot to change the Chado load code to match the changes in

I got the fix wrong so I've tried again and re-started the load.  I won't finish until 10am-ish.

**Comment by kimrutherford** [comment]
> I won't finish until 10am-ish.

The load finished, the main site is updated, the warnings are gone from the logs and the gene pages look correct.

**Comment by ValWood** [comment]
Thanks!
