### ISSUE TITLE
ortholog table: sort pipe seaprated genes in second column

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#961]
From 
https://github.com/pombase/pombase-chado/issues/202

Hi Kim,
I wonder if when you write out the human ortholog table, the Human Id lists could be alphabetised.
I have a list of cut and grep command I can use on the cerevisiae ortholog table to generate a table
of 1:1,
1:many
many:1
many:many.

It doesn't work on the human table becasue it depends on sorting similar, so these currently sort individually even though they have the same orthologs:

1 ATAD2B|ATAD2
1 ATAD2|ATAD2B

1 RPL10L|RPL10
1 RPL10|RPL10L

1 SLC17A1|SLC17A6|SLC17A2|SLC17A3|SLC17A8|SLC17A5|SLC17A7|SLC17A4
1 SLC17A1|SLC17A6|SLC17A3|SLC17A2|SLC17A4|SLC17A7|SLC17A5|SLC17A8
1 SLC17A1|SLC17A6|SLC17A3|SLC17A2|SLC17A5|SLC17A8|SLC17A4|SLC17A7
1 SLC17A3|SLC17A2|SLC17A6|SLC17A1|SLC17A5|SLC17A8|SLC17A4|SLC17A7
1 SLC17A3|SLC17A2|SLC17A6|SLC17A1|SLC17A8|SLC17A5|SLC17A4|SLC17A7
1 SLC17A4|SLC17A7|SLC17A5|SLC17A8|SLC17A3|SLC17A2|SLC17A6|SLC17A1
1 SLC17A4|SLC17A7|SLC17A5|SLC17A8|SLC17A6|SLC17A1|SLC17A3|SLC17A2
1 SLC17A5|SLC17A8|SLC17A7|SLC17A4|SLC17A1|SLC17A6|SLC17A2|SLC17A3
1 SLC17A8|SLC17A5|SLC17A4|SLC17A7|SLC17A3|SLC17A2|SLC17A1|SLC17A6

**Comment by kimrutherford** [comment]
> > I wonder if when you write out the human ortholog table, the Human Id lists could be alphabetised.
>
> Yep, no problem.  I didn't get to it today but I will tomorrow.

Sorry I forgot.  I've changed the code now but not in time for the current load.  It will be visble on Tuesday morning.

https://curation.pombase.org/dumps/latest_build/pombase-latest.human-orthologs.txt.gz

**Comment by ValWood** [comment]
This seems a picky request 
but it will be useful in situations like
SPAC19G12.06c	H2AB2|H2AC1|H2AC13|H2AC11|H2AC15|H2AC12|H2AX|H2AC4|H2AC14|H2AC21|H2AW|H2AB1|H2AB3|H2AJ|H2AC8|H2AC17|H2AC6|H2AC16

and also ,  it is always trickier to check what is already there when they are in different orders
SPAC1A6.03c	PLA2G4F|PLA2G4D|PLA2G4C|PLA2G4A|PLA2G4E|PLA2G4B
SPAC1A6.04c	PLA2G4C|PLA2G4E|PLA2G4D|PLA2G4A|PLA2G4F|PLA2G4B
