### ISSUE TITLE
New  GO annotation provider

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#962]
There is a new GO annotation source (AI)
Format of with field ARBA:ARBA00026955

 I am just about to filter a bunch of them. How many are there in  total in the GOA download file pre filtering?

**Comment by kimrutherford** [comment]
> I am just about to filter a bunch of them. How many are there in total in the GOA download file pre filtering?

There are 1879 pombe annotations with a ARBA ID in the "with" column.

> Also we don't display the prefix (ARBA) for these entries (because we weren't aware of it.

We usually don't show the prefix.

> Will the filter work if I add ARBA:ARBA00026955 to the filtering file, or should I use just ARBA00026955 ?

Is that for the `filtered_mappings` file?  I think all the IDs in that file need their prefixes.

Should I add ARBA to the config file so that the IDs are links?

**Comment by kimrutherford** [comment]
> Should I add ARBA to the config file so that the IDs are links?

ARBA isn't in the GO.db-xrefs file.  Any idea what we should link to (if anything)?

QuickGO don't have links for ARBA IDs for the example I checked.  I looked up the same annotation (for rfc3/SPAC27E2.10c) in Amigo but couldn't find the annotation so I gave up.

Maybe there's nothing to link to?

**Comment by ValWood** [comment]
I couldn't find any of the annotation in QuickGO  yesterday because there wasn't a way to search on the "with" field. I  speak to pascale about these.

When you get chance could you send me the rows from the GAF file with these annotations. The accuracy does not seem too bad, but I suspect most are just high-level redundant terms based on existing PomBAse annotation.....

**Comment by kimrutherford** [comment]
Here's a file with the pombe and japonicus annotation from GOA.  It's much smaller than the full GOA file so I find it useful for grepping.

http://curation.pombase.org/kmr44/gene_association.goa_uniprot.pombe+japonicus-2022-04-01.tsv.gz

You can get the pombe ARBA lines with:


gzip -d < gene_association.goa_uniprot.pombe+japonicus-2022-04-01.tsv.gz | perl -ne 'print if /\ttaxon:(4896|284812)\t/' | grep ARBA:

**Comment by ValWood** [comment]
thanks!

**Comment by kimrutherford** [comment]
> I couldn't find any of the annotation in QuickGO yesterday because there wasn't a way to search on the "with" field.

The last row in this table has an example:
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=O42662 

Is there anything else to do on this issue?

> I speak to pascale about these.

Did you get a chance to do that?  (Just curious - I know very you've busy and ill!)

**Comment by ValWood** [comment]
Hi Kim
Tip
You can search on the "with field" in quickGO under "more" (final tab) there are other options. But it does not appear there. Maybe  this is because the data does not have a DB prefix. You can filter on the "assigned by"   "ASAP"  to remove all, not only the ones that I identified as incorrect. Although this might be the best solution  until the tracker tickets are addressed since  there are a lot of annotations that we would not make.

I have not spoken to @pgaudet about this yet. We were leaving it until after the GO meeting. Pascale I can chat about this when you have chance.

**Comment by ValWood** [comment]
Pascale is going to ask about these data on the managers call. I will take this until we know what is happening with it.
