### ISSUE TITLE
GPI file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#963]
Just curious, do we create a GPI file?
http://geneontology.org/docs/gene-product-information-gpi-format/
Will be come mandatory once we move from GAF to GPAD (I think?)

**Comment by kimrutherford** [comment]
Yep!  We make a GPAD and a GPI file each night.  Here's the story: #276, #792, #851

GPAD: https://curation.pombase.org/dumps/latest_build/misc/gene_product_annotation_data_taxonid_4896.tsv
GPI: https://curation.pombase.org/dumps/latest_build/misc/gene_product_information_taxonid_4896.tsv

**Comment by ValWood** [comment]
OK thanks!
