### ISSUE TITLE
legacy_go log

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#964]
I don't see a problem with this annotation in the log file
https://curation.pombase.org/dumps/latest_build/logs/log.2022-04-29-21-26-25.legacy_go_from_contigs

PomBase	SPBC9B6.03			GO:0140786 	GO_REF:0000024	ISO	SGD:S000002991	F	XXX		protein	taxon:4896	20220327	PomBase	has_input(CHEBI:28300),part_of(GO:1904263)

but it isn't appearing on the gene page

**Comment by kimrutherford** [comment]
I think the problem is this missing CHEBI term:

> Failed to load row: {UNKNOWN}: can't find term with ID: CHEBI:28300 at /local-homes/pbuild/git/pombase-chado/lib/PomBase/Import/GeneAssociationFile.pm line 502

Sorry the message so untidy and it doesn't report the line number.  I'll tidy it up.

**Comment by ValWood** [comment]
The term is in CHEBI though?
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:28300
 We don't maintain a minor ontology with CHEBI terms in extensions do we?

**Comment by ValWood** [comment]
We have pombe-embl/mini-ontologies/chebi.obo, so maybe we do... but if so do you know why we need it ?

**Comment by kimrutherford** [comment]
> We have pombe-embl/mini-ontologies/chebi.obo, so maybe we do...

Yep, we do.

> but if so do you know why we need it ?

The full Chebi is huge so we decided to load just a subset.

**Comment by ValWood** [comment]
Of course. I forgot that we link to pages from extensions for these too.
https://www.pombase.org/term/CHEBI:29108

**Comment by kimrutherford** [comment]
> I forgot that we link to pages from extensions for these too.

I think that's a bug.  We should linking out to Chebi.

**Comment by kimrutherford** [comment]
>> I forgot that we link to pages from extensions for these too.
>
> I think that's a bug.  We should linking out to Chebi.

I made a separate issue for that: pombase/website#1875

**Comment by kimrutherford** [comment]
> Sorry the message so untidy and it doesn't report the line number. I'll tidy it up.

I've done that for Monday night's load.

**Comment by kimrutherford** [comment]
I've added CHEBI:28300 to the mini ontology file so the warning will be gone on Wednesday morning.

> Sorry the message so untidy and it doesn't report the line number. I'll tidy it up.

Turns out that tidying it properly would require a bit of code rearranging which isn't high priority.  I have added the GAF file line number to the message though.

Shall we close this?

**Comment by ValWood** [comment]
I think we do eventually want pages for terms in extensions:
https://github.com/pombase/website/issues/473
but this can close.
