### ISSUE TITLE
Check for typos from column 15 / Assigned By

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#965]
We should ensure there are no typos from column 15 / Assigned By in Chado.  Maybe with a new Chado check.

**Comment by ValWood** [comment]
I will put on group  meeting list but can you provide the list of current "assigned By" field contents (I imagine  it is not huge?? or am I mistaken?

**Comment by ValWood** [comment]
Also putting at low priority, but I'm interested how it came up so I'll put it on the  discuss list...

**Comment by ValWood** [comment]
Do we have examples (I presume this is the GO file)?

**Comment by kimrutherford** [comment]
> Do we have examples (I presume this is the GO file)?

There are no examples at the moment:

|Assigned By  |count  |
|-------------|------:|
|PomBase      |35747  |
|GO\_Central  |5761   |
|UniProt      |1163   |
|InterPro     |1034   |
|IntAct       |669    |
|RHEA         |173    |
|GOC          |120    |
|ComplexPortal|46     |
|CAFA         |10     |


> Also putting at low priority, but I'm interested how it came up so I'll put it on the discuss list...

It's because of this I think:

On 03/05/2022 19:10, Pascale Gaudet wrote:
>
> Hi Val,
>
> It looks like there is a typo in the pombase GAF file – we have 2 annotations with Assigned by ‘pombas’ rather than ‘pombase’, one IEA from Japonicus and one ISO from pombase:
>
> japonicusdb.gaf.gz:
>
> JaponicusDB       SJAG_03401       vhc1       involved_in         GO:0034486       GO_REF:0000107             IEA                PomBase:SPBC18H10.16               P             vacuolar membrane cation-chloride cotransporter Vhc1                 protein taxon:4897         20220425PomBas
>
> pombase.gaf.gz:
>
> PomBase              SPBC18H10.16   vhc1       involved_in         GO:0034486       GO_REF:0000024             ISO                SGD:S000000439              P             vacuolar membrane cation-chloride cotransporter Vhc1                 protein                taxon:4896         20220327            PomBas
>
> Is that coming from PomBase? It would be nice if it could be fixed for the upcoming release.


You replied:

> I fixed this at PomBAse.  I am not sure if it was in time for the nightly update. The japonicus file won't be updated until the next 24 hour cycle.
>
> We will add a check for this.

**Comment by ValWood** [comment]
Yep, this happens when I copy paste lines in the legacy file in an odd way. It shoudn't really happen if I do it properly but good to have a check.

**Comment by kimrutherford** [comment]
>  but we shoud also check the legacy phenotype file

You should get log file messages if there are problems with the phenotype file.

I'll add a check that the assigned_by in the legacy GO file is OK.  Currently most values are "PomBase".  There are 16 "ComplexPortal" and 15 "GOC".   Should we allow just those three values?

**Comment by ValWood** [comment]
No UniProtKB? these should be allowed too.
For those we do not show redundant if UniProt curated the same paper (usually they don't)

I expected many more GOC?
and more Complex portal, but I think a lot of those are not imported because they have a non compliant "with" field

**Comment by kimrutherford** [comment]
> I expected many more GOC?

I don't understand why there are legacy GO annotations that aren't assigned_by PomBase.  Shouldn't the GOC and ComplexPortal annotations come in from external GAF files instead?

**Comment by ValWood** [comment]
Yes, that is very weird. I'll have a look at these.
They should all be PomBase.

**Comment by kimrutherford** [comment]
> I fixed them, and I have no idea why they were there.

Thanks.  I'll add a check when loading that file that assigned_by is always PomBase.

**Comment by kimrutherford** [comment]
> Thanks. I'll add a check when loading that file that assigned_by is always PomBase.

You'll now see a warning like this in the log if the assigned_by columns isn't "PomBase":
```
line 3: ignoring because this value does match the assigned_by filter: PomBas
```

**Comment by ValWood** [comment]
thank you!
