### ISSUE TITLE
Why are we exporting "SPAC1556.06.1" as a exact synonym in the InterMine JSON?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#967]
For meu1/SPAC1556.06

It's appears in the PombeMine results as a separate gene object if you search for "SPAC1556.06.1"

https://curation.pombase.org/dumps/latest_build/intermine_data/pombemine_gene_details.gz

**Comment by ValWood** [comment]
I can remove it, but I don't understand why it is causing a problem (i.e  why it creates a separate gene object as it isn't a systematic_id). There are many unique synonyms. I think we keep it because it was in use for a while?

**Comment by kimrutherford** [comment]
> I can remove it, but I don't understand why it is causing a problem (i.e why it creates a separate gene object as it isn't a systematic_id).

I think it probably isn't causing the PombeMine problem.  It's mostly a tidy up for us.  If it fixes PombeMine that's a bonus.

**Comment by ValWood** [comment]
Can we chat about this. I don't understand. And I dn't understand "unique synonym"

We have
gene names (symbols)
systematic IDs
synonyms (everything else).

Synonyms are unique and non-unique. This synonym is valid (it used to be a primary ID when we represented as alternative features). I. think it even pedates the use of this syntax fo Ensembl transcript.  Ideally I would like to keep it ,(although if it really causes problems I can just make a note somewhere)

**Comment by kimrutherford** [comment]
> And I dn't understand "unique synonym"

Sorry!  That was meant to be "EXACT" synonym.  I've fixed the title.

> Ideally I would like to keep it

Yep, no problem.  I didn't realise it was the gene primary ID at one point.

We can close this.

**Comment by ValWood** [comment]
Historically, SPAC1556.06 were the only alternative trancripts we curated because there is a mitotic and a meiotic from. We wanted to represent this before we had an 'offical' way to do it.
Although oddly I can't find the paper about this. I am sure that there was one...There was a long and short transcript identified. But this gene no longer has alternative forms, and it doesn't have any GO annotation . I will try to find out why.

**Comment by ValWood** [comment]
I have a curation tracker ticket to check up on this?
https://github.com/pombase/curation/issues/3261
