### ISSUE TITLE
Warn if two contig features have the same systematic ID

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#968]
See this issue for an example: https://github.com/pombase/curation/issues/3159#issuecomment-1080996932=

**Comment by kimrutherford** [comment]
That's done for tonight's load.  I'll check the logs for a warning about "SPNCRNA.111" in a day or two and then close the issue if it's there.

**Comment by kimrutherford** [comment]
> That's done for tonight's load. I'll check the logs for a warning about "SPNCRNA.111" in a day or two and then close the issue if it's there.

Looks OK:
https://curation.pombase.org/dumps/latest_build/logs/feature_warnings.txt

**Comment by ValWood** [comment]
Has same ID in first and second column (One gene one transcript)

**Comment by kimrutherford** [comment]
> Has same ID in first and second column (One gene one transcript)

I don't understand.  Should I remove the transcript ID?  I thought it would be useful but maybe not?

**Comment by ValWood** [comment]
Ignore me. They have the same IDs...(I think I was expecting the other systematic ID that the entry was merged into, but this isn't necessary)
