### ISSUE TITLE
Do not load genes from BioGRrid that are not in PomBase

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#969]
Add a warning log.

from https://github.com/intermine/pombemine/issues/47

**Comment by kimrutherford** [comment]
We don't load genes from BioGrid, just interactions.  Here's the log file: https://curation.pombase.org/dumps/latest_build/logs/log.2022-05-22-21-26-39.biogrid-load-output

Was this for PombeMine?

**Comment by ValWood** [comment]
OK , I got confused. If InterMIne get this  data directly from BIOGIRD we will need to wait for the fix to trickle through.

**Comment by ValWood** [comment]
Although presumably the Interactions file includes  the gene names for the genes. that no longer exist. DO we just skip those?

**Comment by kimrutherford** [comment]
> Although presumably the Interactions file includes the gene names for the genes. that no longer exist. DO we just skip those?

Yep.  They should show as an error.

**Comment by ValWood** [comment]
OK I  need to look in that log. I tended to ignore it because I thought it was all warnings about the co-localizations (which we do not load) , but there is other stuff in there (more than the number that I just reported back from IntterrMIne)
I will look at these in due course...

**Comment by kimrutherford** [comment]
> Although presumably the Interactions file includes the gene names for the genes. that no longer exist. DO we just skip those?

Here are some examples:

```
skipping BioGRID ID 755615: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 755670: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 757452: can't find feature for: SPBC8E4.02c
skipping BioGRID ID 757575: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 760304: can't find feature for: SPBC8E4.02c
skipping BioGRID ID 762200: can't find feature for: SPBC8E4.02c
skipping BioGRID ID 762759: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 767241: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 768582: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 768928: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 769015: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 770226: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 770463: can't find feature for: SPBC8E4.02c
skipping BioGRID ID 775283: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 776339: can't find feature for: SPBC8E4.02c
skipping BioGRID ID 777307: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 777937: can't find feature for: SPBC8E4.02c
skipping BioGRID ID 779485: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 780189: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 781969: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 784287: can't find feature for: SPBC8E4.02c
skipping BioGRID ID 785844: can't find feature for: SPBC8E4.02c
skipping BioGRID ID 787292: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 791615: can't find feature for: SPBC8E4.02c
skipping BioGRID ID 792777: can't find feature for: SPBC8E4.02c
skipping BioGRID ID 793076: can't find feature for: SPAC1F12.03c
skipping BioGRID ID 795323: can't find feature for: SPBC8E4.02c
```

**Comment by ValWood** [comment]
Yep I was just checking. Those are the 3 I reported this morning.
