### ISSUE TITLE
Use the correct prefix for IDs in the GAF "with" column

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#970]
In this case "PomBase:Q9H9V9" should be "UniProtKB:Q9H9V9" (or some such):

```
PomBase:SPAC25H1.02             RO:0002331      GO:0002184      GO_REF:0000050  ECO:0000266     PomBase:Q9H9V9          2007-05-31      PomBase
PomBase:SPAC25H1.02             RO:0002327      GO:0106156      GO_REF:0000050  ECO:0000266     PomBase:Q9H9V9          2007-05-31      PomBase
```

We should check for other cases like cerevisiae/SGD genes.

**Comment by ValWood** [comment]
This is because I missed a prefix in the legacy file.
Maybe we could   report if anything has no prefix as an error.
Not sure urgent any longer though.

**Comment by kimrutherford** [comment]
> This is because I missed a prefix in the legacy file.
> Maybe we could report if anything has no prefix as an error.

Ah!  Yes, that will be it.  Yes, there should be an warning about it.

**Comment by ValWood** [comment]
I just checked and I can't see any other  non-PomBAse Ids with a PomBase prefix

**Comment by kimrutherford** [comment]
Thanks.  I'll close this.

**Comment by kimrutherford** [comment]
> I just checked and I can't see any other non-PomBAse Ids with a PomBase prefix

I've queried Chado and Q9H9V9 was the only ID without a prefix.

I've checked the legacy contig loading code and that did check for prefixes.  It's the GAF loading code that needs fixing.
