### ISSUE TITLE
publications for pombemine

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#973]
I can't remember the route forr publications-> intermine, but I don't think we  should  export the 
"
the "wrong organism" or "loaded in error" publications

**Comment by kimrutherford** [comment]
Can you give me some examples to look at?  We're supposed to be exporting the same data and publications as on the web site.

**Comment by ValWood** [comment]
I saw publication PMID:1 and some other non pombe papers when I filtered on papers from PomBase

**Comment by kimrutherford** [comment]
> I saw publication PMID:1 and some other non pombe papers when I filtered on papers from PomBase

That's odd.  I've just checked the main JSON file we export from Chado for InterMine and PMID:1 isn't there.

I tracked down a few entities in PombeMine with that publication attached.  For example:
  http://pombemine.rahtiapp.fi/pombemine/report/ProteinDomain/6060554

That's from the "InterPro data set".  I don't understand that one.

Here's a query with some others:
```xml
<query model="genomic" view="Publication.pubMedId Publication.meshTerms.name Publication.entities.dataSets.name" constraintLogic="(A)" sortOrder="">
   <constraint path="Publication.pubMedId" value="1" op="=" code="A"/>
   <constraint path="Publication.entities" type="ProteinDomain"/>
</query>
```

**Comment by ValWood** [comment]
I wonder if it is just an out of date version of the publication import in the Mine?

**Comment by ValWood** [comment]
Maybe that particular publication is coming from somewhere else.I am surer that yesterday I filtered on "source" pombase. However today I cannot see a way to do that?  (perhaps I was doing it a different way) Maybe we can look at this later?

**Comment by ValWood** [comment]
See
https://github.com/intermine/pombemine/issues/33#issuecomment-1135510323

**Comment by kimrutherford** [comment]
> Maybe we can look at this later?

Yep!

There's also a publication page for PMID:1 - http://pombemine.rahtiapp.fi/pombemine/report/Publication/6033710

**Comment by ValWood** [comment]
Actually that could be me. I just checked and PMID:2 was currently "curatable"
I should stop  playing with non-curatable papers in. the curation tool.

Do we export out publication 'tags' ? this would be useful to query on curatable papers! or methods/review/biotechnology  papers etc

**Comment by kimrutherford** [comment]
> Do we export out publication 'tags' 

Do you mean triage status?  We store that in Chado.

**Comment by ValWood** [comment]
Ha, ha, https://www.ebi.ac.uk/interpro/entry/InterPro/IPR028931/
will report to. InterPRO (they probably do the same as us!)

**Comment by ValWood** [comment]
Yes, is that tag in the PombeMine export. It  would make useful queries (Probably only fo me!)

**Comment by kimrutherford** [comment]
> Yes, is that tag in the PombeMine export. It would make useful queries (Probably only fo me!)

It's a JSON file of genes and transcripts.  There's nothing much else in it.  We only export a list of references for each gene in the file, as PMIDs and GO_REFs.  There isn't really any place we could add fields for publications.  We'd need a new JSON file with publication details to export the triage status.

**Comment by kimrutherford** [comment]
Should we close this?  It sounds like there isn't time to add new data to PombeMine.
