### ISSUE TITLE
Global replace has_direct_input with has_input everywhere

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#974]
From https://github.com/pombase/website/issues/1887:
> Can we do a global replace of has_direct_input with has_input (anywhere that we have used it). That will get rid of quite a lot of differences in the summaries and make everything collapse better.

Need to edit the Canto database and `pombe-embl/supporting_files/legacy_go_annotations_from_contigs.txt`

**Comment by kimrutherford** [comment]
Also: remove has_direct_input from the config file.

**Comment by ValWood** [comment]
I have done the legacy file.

**Comment by kimrutherford** [comment]
I'll update the Canto database at the weekend.  It will need to be offline for a few minutes.

**Comment by kimrutherford** [comment]
> I'll update the Canto database at the weekend. It will need to be offline for a few minutes.
>
> Should the relation to has_input change for modifications too?

So it turns out that there are only 4 annotations of any type in Canto that have a has_direct_input() relation.  All 4 are modifications.  Three annotations for SPCC1795.06 and one for SPAC6F6.15.

So we must have got rid of the has_direct_input() from Canto GO annotation previously.  (I don't remember that though)

**Comment by ValWood** [comment]
>So we must have got rid of the has_direct_input()
Right, that's why I thought it was done. But I had totally forgotten about the legacy file...

**Comment by ValWood** [comment]
> Should the relation to has_input change for modifications too?

Yes, I didn't know we ever used has_direct_input for modifications.

**Comment by kimrutherford** [comment]
I've changed the 4 relations in Canto.  I'll check Chado after the next load to see if we've missed any from other files.  (I don't think we have.  I've just grepped all of pombe-embl and there we're any has_direct_input relations in current files that we load.)

**Comment by kimrutherford** [comment]
> I've changed the 4 relations in Canto. I'll check Chado after the next load to see if we've missed any from other files.

I checked Chado and there were still nearly 600 GO annotation with a `has_direct_input()` in the extension.  I double checked Canto and all the files and couldn't work it out.

But I think what's happening is that there are a bunch of `has_substrate()` extensions (like in https://curation.pombase.org/pombe/curs/615084ae39833661/ro/) but there is no `has_substrate` term in any of the relation ontologies.  Instead `has_substrate` is an `alt_id` of `has_direct_input` (in `pombe-embl/mini-ontologies/gene_ex_extension_relations.obo`).

So anywhere that `has_substrate()` is used in an extension, it ends up as `has_direct_input()` in Chado (and on the website and in GAF files).

You originally asked "Can we do a global replace of has_direct_input with has_input".

Should we change `has_substrate()` to `has_input()` too?

**Comment by ValWood** [comment]
Yes we can do that. I was thinking that it was one of our display mapping substitutions, but obviously it isn't!
These should be has_input  too. I'll check the legacy file.

**Comment by ValWood** [comment]
none in legacy...

**Comment by kimrutherford** [comment]
> Should we change has_substrate() to has_input() too?

I did a local test of the change and the summary looks tidier for the example I looked at: clp1(SPAC1782.09c).

Before:
![substrate-fix-0](https://user-images.githubusercontent.com/90474/170864113-f0183a49-d5ba-4943-bc0f-d2b37984165f.png)

After:
![substrate-fix-1](https://user-images.githubusercontent.com/90474/170864117-2dc14423-d5e8-4e7f-a91d-38016f002b69.png)

> none in legacy...

Thanks.

I'm about to update the main Canto database (changing `has_substrate()` to `has_input()`) so it should all be done by Monday morning.

We may still have have configuration to tweak though.

**Comment by kimrutherford** [comment]
> I'm about to update the main Canto database (changing has_substrate() to has_input()) so it should all be done by Monday morning.

All the has_direct_input and has_substrate relations are gone from the GAF file.  I haven't had a good look at the configuration yet but I will before the next load.  In the meantime, if you spot any "has input" in the extensions on the website it might be because there is configuration to fix.  Let me know if you see any.

**Comment by ValWood** [comment]
This looks great by the way. It had been bugging me for ages. The display makes much more sense  (Now just need to figure what to do about the 'directly inhibits')

**Comment by kimrutherford** [comment]
Hi Val.  I'm gong through the configuration for "has_direct_input".  Most of it is the same for "has_input" so changing the relation in the extensions hasn't changed anything.

I can see two bits of configuration that we don't have for has_input:

For descendants of GO:0004857 "has_direct_input" was configured to display as "negatively regulates".  But as far I can tell this configuration didn't do anything because there was always more specific config that overrode it.
In the current version "has_input" mostly displays as "regulates" for GO:0004857 and descendants:
https://www.pombase.org/term/GO:0004857
Is that OK?

The second config is that for descendants of GO:0140597, "has_direct_input" was configured to display as "chaperones".  There are a few extensions on this page that now show as "has input":
https://www.pombase.org/term/GO:0140597
So should "has_input" be shown as "chaperones" for descendants of GO:0140597?

**Comment by ValWood** [comment]
> In the current version "has_input" mostly displays as "regulates" for GO:0004857 and descendants:
https://www.pombase.org/term/GO:0004857
Is that OK?

ideally all descendants of GO:0004857 would display as "inhibits"

> So should "has_input" be shown as "chaperones" for descendants of GO:0140597?

Yes that would be  perfect

**Comment by kimrutherford** [comment]
OK, I've made those changes but not in time for Sunday night's load.  They'll be on the main site on Tuesday morning.

The term pages with the changes are available on my desktop in the meantime:

 - https://desktop.kmr.nz/term/GO:0004857
 - https://desktop.kmr.nz/term/GO:0140597

**Comment by ValWood** [comment]
For inhibits, some say "directly inhibits"
and some say "regulates activity of"
I suspect that I need to fix these to has_input

chaperones looks good

**Comment by ValWood** [comment]
I fixed these to has_inout, will check tomorrow

**Comment by ValWood** [comment]
weird. There was def. an update. I see  a lot of changes I made to GO txn annotations. but here , although I changed all of the "inhibitor" annotations to "has input" they don't all now display as "inhibits"

**Comment by kimrutherford** [comment]
I think this is done.
