### ISSUE TITLE
empty log reports

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#976]
log.2022-05-26-21-25-48.chado_checks.extension_relation_genes_exist | 2022-05-27 01:29 | 0 |  
-- | -- | -- | --
  | log.2022-05-26-21-25-48.chado_checks.go_annotation_count | 2022-05-27 01:29 | 0 |

**Comment by kimrutherford** [comment]
Empty means there are no warnings of that type.

**Comment by ValWood** [comment]
Ah I thought they were counts (like some of the others)
But they are just checking that they exist?

**Comment by kimrutherford** [comment]
The chado_checks log files will be zero length in the "normal" case: when the test passes.  If a test fails the file will contain the error or warning and usually list of the genes, alleles, annotations etc.  Sometimes it contains a count instead if that makes sense.
