### ISSUE TITLE
Use term names in PHAF output instead of FYPO_EXT:...

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#978]
See discussion here: https://github.com/intermine/pombemine/issues/57

**Comment by ValWood** [comment]
Could you do this next?

**Comment by kimrutherford** [comment]
That's done now, so both PHAF files have term names instead of term IDs for penetrance and severity:
  - https://curation.pombase.org/dumps/latest_build/pombase-latest.eco.phaf.gz
  - https://curation.pombase.org/dumps/latest_build/pombase-latest.phaf.gz
