### ISSUE TITLE
 More background alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#981]
Please. add to filterr
ura4-D19
ura4-D6
ura4-294

CC @manulera

**Comment by ValWood** [comment]
I just checked and these don't seem to be existing alleles.

**Comment by kimrutherford** [comment]
OK, that's done.  I'll check the output in the morning before closing this.

**Comment by kimrutherford** [comment]
> I'll check the output in the morning before closing this.

All done.
