### ISSUE TITLE
qtr1delta alleles not merging

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#985]
There are two "qtr1delta" alleles in Chado that should be merging into one feature.

**Comment by ValWood** [comment]
Can you let me know the sources?

**Comment by ValWood** [comment]
I  just changed SPAC1687.19cdelta  into qtr1 delta in
curs/59866e3fe9bebea8/
but I don't think that is the issue?

The Canto session look OK, so maybe there is a trailing space in one of the PHAF files?

**Comment by kimrutherford** [comment]
I think it's a bug in the Chado loader.  I'll dig out the sources.

**Comment by ValWood** [comment]
I think I already changed it.... but I might not have. I can't remember!

**Comment by kimrutherford** [comment]
I think this is a duplicate of: pombase/pombase-chado#992
