### ISSUE TITLE
ARBA annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#987]
It is not clear whther these will stay in GO long term, because they are from machine learning.
However, in the meantime I would like to filter the inappropriate ones (but still see them so that I can explain why they might be problematic)

Do these  generate an error because there is not an entry in the GO DBxrerfs file?
https://curation.pombase.org/dumps/latest_build/logs/log.2022-06-29-22-26-15.chado_checks.illegal_with_prefix

If that is the problem I will get it added so that the filtering works.

**Comment by ValWood** [comment]
ACtually, when I did the first filters there was no prefix. 

I added as PANTHER:PTN000296424
InterPro:IPR004045
ARBA00033559
ARBA00028932
ARBA00028368

so if there is now a prefix I will add it and the filtering might work even if they are not in the db-xrefs file?

**Comment by kimrutherford** [comment]
> Do these generate an error because there is not an entry in the GO DBxrerfs file?

There is a hard-coded list of allowed prefixes in the config for the Chado checking.  Shall I add "ARBA" as a legal prefix so the warnings go away?

> so if there is now a prefix I will add it and the filtering might work even if they are not in the db-xrefs file?

Yep, the filtering is independent of the db-xrefs file and the prefix is needed in the filter file.

**Comment by ValWood** [comment]
Please.
SO I just add the prefixes to the file. 

Check it is working with this one
https://www.pombase.org/gene/SPAC1687.03c
I filtered because it will be obsoleted (Now represented as a MF)

**Comment by kimrutherford** [comment]
> Shall I add "ARBA" as a legal prefix so the warnings go away?

I've done that now and I'll check the log tomorrow.

**Comment by kimrutherford** [comment]
> I've done that now and I'll check the log tomorrow

The illegal_with_prefix log file is now empty.  Let me know if there's anything else to do here.
