### ISSUE TITLE
Duplicate alleles in Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#992]
While testing pombase/pombase-chado#986 I noticed that there are a bunch of duplicate alleles in Chado.  That's annoying as I thought I had fixed that years ago.  They seem to be mostly deletions.

Examples: zip3delta, scs22delta, tif1delta
but there are over 100 others.

**Comment by ValWood** [comment]
how are they duplicated?

**Comment by kimrutherford** [comment]
> how are they duplicated?

I don't know yet.  I'll investigate more on Monday.  It's annoying because deletions are the easiest case to handle and I'm sure we didn't have duplicate deletions in the past.

**Comment by kimrutherford** [comment]
> While testing https://github.com/pombase/pombase-chado/issues/986 I noticed that there are a bunch of duplicate alleles in Chado.

I think I've fixed at least part of the problem.  The deletion names from Canto were a bit inconsistent.  For example in [session 8c85c01f83c1d4eb for PMID:23041194](https://curation.pombase.org/pombe/curs/8c85c01f83c1d4eb/feature/gene/view/1/ro) we have separate alleles for `scs22Δ` and `SPAC17C9.12Δ`.  They both should be `scs22Δ`.

There are others that might need checking, like this `nde1Δ` which is curated as an allele of `ndi1` in this session: 
https://curation.pombase.org/pombe/curs/1719104d313ca4be/feature/genotype/view/39/ro
Looks like a typo for `ndi1Δ` as `nde1` is not in the session.

I'll make a list of deletion allele names in Canto that don't match the gene and let you know.

I've changed the code that exports from Canto to always set the deletion names to gene name + "delta" in the JSON file.

I'll check on Monday to see how many duplicates that fixes.

**Comment by kimrutherford** [comment]
> While testing https://github.com/pombase/pombase-chado/issues/986 I noticed that there are a bunch of duplicate alleles in Chado.

We should have a log file about this so I made an issue: pombase/pombase-chado#994

**Comment by kimrutherford** [comment]
> I'll check on Monday to see how many duplicates that fixes.

The list is much smaller now:
https://curation.pombase.org/dumps/builds/pombase-build-2022-07-10/logs/log.2022-07-10-22-25-05.chado_checks.duplicated_allele_names

I can see two reasons for the remaining duplicates.

In some cases there really are two alleles with the same name but different genes, like: cys2-1 with genes: SPBC106.17c and SPBC428.11
Those will need to be fixed manually, but there aren't too many cases.

There also are cases where in the log it looks like the same allele name/description/gene combination occurs twice like:
cce1-D46N(D46N) SPAC25G10.02  
In that example the allele is named "D46N" in one session and "cce1-D46N" in another so the loading code thinks that they are two different alleles.  A [later post-processing step](https://github.com/pombase/pombase-chado/issues/868) fixes those in Chado but doesn't merge them.  I've made a separate issue about this bug: pombase/pombase-chado#995

**Comment by ValWood** [comment]
I think some of the examples might be in the existing logs which I am working through slowly (the prromoter ones look familiar). But I planned to do the logs this pm to fix any of the small files, so I will do these today.

**Comment by kimrutherford** [comment]
> But I planned to do the logs this pm to fix any of the small files, so I will do these today.

It would be good if you could not change the cases where the gene is missing from the front of the allele name so I can make sure my fix works.

Thanks.

**Comment by ValWood** [comment]
These remain for testing.

Let me know if I can fix tomorrow

cce1-D230N	SPAC25G10.02:allele-2	D230N	amino_acid_mutation	68c407dfd4d11f5e
  cce1-D230N	SPAC25G10.02:allele-8	D230N	amino_acid_mutation	7ab16ed95ce889ee
  cce1-D46N	SPAC25G10.02:allele-6	D46N	amino_acid_mutation	68c407dfd4d11f5e
  cce1-D46N	SPAC25G10.02:allele-9	D46N	amino_acid_mutation	7ab16ed95ce889ee
  cut1-C1730A	SPCC5E4.04:allele-10	C1730A	amino_acid_mutation	310b16bb1a103044
  cut1-C1730A	SPCC5E4.04:allele-23	C1730A	amino_acid_mutation	809618c56c11583b,809618c56c11583b

   grx4-C172S	SPBC26H8.06:allele-4	C172S	amino_acid_mutation	57ee19731b127383
  grx4-C172S	SPBC26H8.06:allele-6	C172S	amino_acid_mutation	4f30f3893b88315a
  grx4-C35S	SPBC26H8.06:allele-3	C35S	amino_acid_mutation	57ee19731b127383
  grx4-C35S	SPBC26H8.06:allele-5	C35S	amino_acid_mutation	4f30f3893b88315a

**Comment by kimrutherford** [comment]
Thanks, that's great.  My fix worked too and there's only one duplicate left:

https://curation.pombase.org/dumps/latest_build/logs/log.2022-07-11-22-27-19.chado_checks.duplicated_allele_names

**Comment by kimrutherford** [comment]
> there's only one duplicate left

Fixed!  Thanks Val.

The log file is now empty:
https://curation.pombase.org/dumps/builds/pombase-build-2022-07-19/logs/log.2022-07-19-18-27-04.chado_checks.duplicated_allele_names
