### ISSUE TITLE
help needed locating source

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#996]
I'm not sure where these are?
https://curation.pombase.org/dumps/latest_build/logs/log.2022-07-10-22-25-05.allele-synonyms-from-supporting-data

**Comment by ValWood** [comment]
I grepped in htp and ltp phafs?

**Comment by kimrutherford** [comment]
They are from `pombe-embl/supporting_files/allele_synonyms.txt`

**Comment by ValWood** [comment]
I still don't get this ;)

These are in the allele comments file.
It says
skipping line 34 - more than one feature found with name "spt5-T1A":
skipping line 35 - more than one feature found with name "spt5-T1E":

but how do I know what I need to fix? I presumed this problem should be reported in another log (it sounds from the comment  like the same name is used for multiple alleles). But I don't see it reported elsewhere.

**Comment by kimrutherford** [comment]
Sorry!  The allele comment loading code had a bug so it was displaying the wrong message when the allele couldn't be found.

From tomorrow it will say something like:

```
can't find feature with name "spt5-T1A" at line 34
can't find feature with name "spt5-T1E" at line 35
```

I checked Chado.  "spt5-T1A" is now a synonym of "spt5-(T1A)7".  It looks like "spt5-T1E" has been removed.

**Comment by ValWood** [comment]
Actions
- [ ] Add spt5-T1E as a synonym of spt5-(T1E)7
- [ ] move comments to spt5-(T1E)7 and spt5-(T1A)7 respectively
