### ISSUE TITLE
annotation drop

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#999]
We recently reported over 300,000 annotation but currently we are reporting 297,,424, so I assume  we have some dataset that isn't loading.
I can't see anything obvious in the logs.

**Comment by kimrutherford** [comment]
> We recently reported over 300,000 annotation

When was that?  I've just checked the Chado databases going back to March 1st and the highest annotation count I could see was 297441 on July 1st.

**Comment by ValWood** [comment]
maybe we never went over 300,,0000 yet? I think I have been saying nearly 300,000 for a while so I thought it was true!

**Comment by ValWood** [comment]
Weird because we are at 304764 today and I don't think we added any new datasets recently.

I though I had seen it over 300,000

**Comment by kimrutherford** [comment]
Where are you looking to see 304764?

It's 297323 on the stats page: https://curation.pombase.org/pombe/stats/annotation

**Comment by ValWood** [comment]
I had not clicked that I was looking in 2 different places ;)
<img width="476" alt="Screenshot 2022-07-26 at 13 55 35" src="https://user-images.githubusercontent.com/7359272/181011103-9e3c654f-1479-4777-b881-af8e6974ddab.png">

I think this number includes the ~3202 IEA's

**Comment by ValWood** [comment]
But that would still be over 300.000.
I cant remember the exact overlap between these 2 numbers.

**Comment by ValWood** [comment]
At some point recently, a large proportion of these annotations

https://www.pombase.org/reference/PMID:20473289
were not being loaded (I had a note to myself to check this page and it looks fine now).

So that could explain the number drop.

**Comment by kimrutherford** [comment]
> But that would still be over 300.000.
> I cant remember the exact overlap between these 2 numbers.

The number on the Canto stats page only includes the annotations shown on the graph:
  - GO annotations
  - Phenotypes
  - Protein modifications
  - Gene expression
  - Genetic interactions
  - Physical interactions

The number on the pombase.org front page includes all the ontology annotation in Chado, including all the little CVs like m_f_g, cat_act and species_dist.  It don't include the interaction annotations.  Perhaps it should?

**Comment by ValWood** [comment]
> The number on the pombase.org front page includes all the ontology annotation in Chado, including all the little CVs like m_f_g, cat_act and species_dist. It don't include the interaction annotations. Perhaps it should?

I guess they could all go in the 'other' bin

**Comment by kimrutherford** [comment]
> I guess they could all go in the 'other' bin

It's just one number?

**Comment by kimrutherford** [comment]
> It don't include the interaction annotations. Perhaps it should?

This question was about the number of the front page of pombase.org.  It currently says "304495 annotations" but it doesn't include interaction annotations.  Should we add those annotations to that number?

**Comment by ValWood** [comment]
I'm confused. It should include the interactions we curated (but that would make the difference between the histogram and the number on the front page even higher?)

**Comment by kimrutherford** [comment]
The histogram excludes:
  - BIOGRID annotation
  - IEA annotation
  - these annotation types
     - "PomBase gene products" - the `/products` are stored as annotations in Chado
     - "cat_act"
     - "subunit_composition"
     - "external_link"
     - "pathway"

The number on the front page currently counts all the ontology/CV annotations from any source, but doesn't count interaction annotations.

**Comment by ValWood** [comment]
OK got it.
We do not include the imported BIOGRID, or imported GO annotations in our histogram (I think this is correct).

We could include the 'other' types in the histogram.

**Comment by ValWood** [comment]
Action: include "products" in the histogam. These are a "curation", and there are a lot of them, especially including the RNAs.

**Comment by kimrutherford** [comment]
> Action: include "products" in the histogram.

Done!

The total is now 308837 instead of 298799.

**Comment by kimrutherford** [comment]
I think this is done.
